{
  "hash": "08bf32e7b7bf7cd76c82117426b26f60",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Decision Trees {#sec-trees}\n\nA *decision tree* is a chain of yes/no questions, the kind an experienced auditor asks without thinking. Was the tender open for less than three weeks? If yes, did it get fewer than three bids? If yes, this contract needs a close look. A tree learns such questions from data. It finds which feature to ask about first, where to draw the line (why three weeks, and not two?), and what to ask next, separately for each answer.\n\nTrees have two great strengths for audit work.\n\n- **Their results are rules**, which can be read, discussed and written into an audit programme: \"contracts with a tender window under 21 days and at most two bidders were irregular about 60% of the time\".\n- **They find combinations by themselves.** A short tender window may matter only when there are few bidders. Logistic regression (@sec-logistic) treats each feature separately, unless we know the combination in advance and tell it. A tree discovers it.\n\nIn this chapter we use trees for two audit tasks: learning risk rules from past audit results, and finding out what rule a department *actually* follows in its decisions, as against the rule it is supposed to follow.\n\n**Prerequisites**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(rpart)        # fits decision trees\nlibrary(rpart.plot)   # draws them\n```\n:::\n\n\n`rpart` comes with every installation of R. `rpart.plot` is installed from CRAN with `install.packages(\"rpart.plot\")`.\n\n## Our data, audited works contracts {#sec-trees-data}\n\nLast year's audit examined 3,000 works contracts of a State's public works, irrigation and water supply departments, and recorded whether each was found irregular (excess payment, splitting of works, inflated quantities, and so on). For each contract we know\n\n- `department`,\n- `tender_mode`, whether the contract was awarded through an open tender, a limited tender, or on nomination to a single contractor,\n- `value_lakh`, the value of the contract in ₹ lakh,\n- `window_days`, the days the tender was open for bids (the General Financial Rules require at least three weeks for open tenders),\n- `bidders`, the number of bids received.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the contracts data\"}\nset.seed(33)\nn <- 3000\nworks <- tibble(\n  work_id     = sprintf(\"WK-%04d\", 1:n),\n  department  = sample(c(\"Roads\", \"Buildings\", \"Irrigation\", \"Water Supply\"), n, TRUE),\n  tender_mode = sample(c(\"Open\", \"Limited\", \"Nomination\"), n, TRUE, prob = c(0.7, 0.2, 0.1)),\n  value_lakh  = round(rlnorm(n, log(60), 0.9), 1),\n  window_days = pmax(3, round(rnorm(n, 26, 7))),\n  bidders     = pmax(1, rpois(n, 4.5))\n) |>\n  mutate(bidders = if_else(tender_mode == \"Nomination\", 1, bidders),\n         # The true risk, unknown to the auditor. Planted:\n         # - short tender windows with at most two bidders are very risky\n         # - large contracts awarded on nomination are very risky\n         risk = case_when(\n           tender_mode == \"Nomination\" & value_lakh > 100 ~ 0.60,\n           window_days < 21 & bidders <= 2               ~ 0.65,\n           window_days < 21                              ~ 0.15,\n           TRUE                                          ~ 0.04),\n         irregular = as.numeric(runif(n) < risk)) |>\n  select(-risk)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworks\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,000 × 7\n   work_id department   tender_mode value_lakh window_days bidders irregular\n   <chr>   <chr>        <chr>            <dbl>       <dbl>   <dbl>     <dbl>\n 1 WK-0001 Buildings    Open              16.6          35       5         0\n 2 WK-0002 Water Supply Open             158.           31       3         0\n 3 WK-0003 Buildings    Limited           35.6          37       5         0\n 4 WK-0004 Water Supply Open              99.6          16       3         0\n 5 WK-0005 Roads        Limited            7.6          24       6         0\n 6 WK-0006 Buildings    Open              77.1          20       5         0\n 7 WK-0007 Water Supply Limited           59.2          34       7         0\n 8 WK-0008 Water Supply Open              69.4          23       3         0\n 9 WK-0009 Roads        Open              92.6          40       6         0\n10 WK-0010 Roads        Open              46.7          28       3         0\n# ℹ 2,990 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(works$irregular)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.112\n```\n\n\n:::\n:::\n\n\n`irregular` is 1 for an irregular contract and 0 otherwise, so its mean, 0.112, is the share of irregular contracts, about 11%. As in @sec-logistic-split, we keep 30% of the contracts aside as a test set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ntrain_rows <- sample(nrow(works), size = 0.7 * nrow(works))\ntrain <- works[train_rows, ]\ntest  <- works[-train_rows, ]\n```\n:::\n\n\n## Growing a tree {#sec-trees-grow}\n\n`rpart()` takes a formula, like `lm()` and `glm()`. Since `irregular` is coded 0 and 1, we use `method = \"anova\"`. The tree then predicts the *share* of irregular contracts in each group, which is exactly the risk score we want. (For a yes/no label instead of a score, `method = \"class\"` is used, as we will see in @sec-trees-rules-actual.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)   # rpart uses random numbers for cross-validation, explained later\ntree1 <- rpart(irregular ~ department + tender_mode + value_lakh + window_days + bidders,\n               data = train, method = \"anova\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrpart.plot(tree1, roundint = FALSE, digits = 2)\n```\n\n::: {.cell-output-display}\n![Decision tree for irregularity in works contracts](12-4c-trees_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\n**How to read the tree.** Start at the top, the *root*, which holds all the training contracts. Each box shows two numbers. The upper one is the share of irregular contracts in that group, and the lower one is the percentage of all contracts which fall in it. The root shows the overall share, 0.11, for 100% of contracts. Below each box is a question. Contracts for which the answer is *yes* go to the left, and the others to the right. The boxes at the bottom, the *leaves*, are the final groups.\n\nThe first question is whether the tender was open for 21 days or more. For the contracts where it was not, on the right, the tree next asks about bidders. Short-window contracts with fewer than 2.5 (that is, at most two) bidders end in a leaf where about three in five were irregular. On the left, among contracts with a proper window, the tree separates those awarded on nomination, and among them those worth more than about ₹1 crore, another high-risk leaf. Every other group has a low share. The tree has found both the planted patterns, and even the 21-day line of the rules, without being told any of them.\n\n## How a tree chooses its questions {#sec-trees-how}\n\nAt each step, the tree tries every feature and every possible dividing line. For `window_days` it tries \"less than 4\", \"less than 5\", and so on. It picks the question which splits the contracts into two groups that are each as *pure* as possible, one group with mostly irregular contracts and the other with mostly clean ones. Then it repeats the search inside each group separately. That is why the second question can be different on each side. The tree asks about bidders only for contracts with short windows, because that is where bidders matter.\n\nLeft alone, this splitting would go on until every leaf held a single contract. `rpart()` stops earlier, by default, when a split would improve the fit by less than 1%. This limit is the *complexity parameter*, `cp`, which we will meet again in @sec-trees-prune.\n\n## From a tree to audit rules {#sec-trees-rules}\n\n`rpart.rules()` writes out the path to each leaf as a rule, sorted by risk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrpart.rules(tree1, roundint = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n irregular                                                                                             \n     0.024 when window_days >= 21 & tender_mode is      Nomination                  & value_lakh <  109\n     0.043 when window_days >= 21 & tender_mode is Limited or Open                                     \n     0.180 when window_days <  21                                  & bidders >= 2.5                    \n     0.590 when window_days >= 21 & tender_mode is      Nomination                  & value_lakh >= 109\n     0.612 when window_days <  21                                  & bidders <  2.5                    \n```\n\n\n:::\n:::\n\n\nThese read almost like paragraphs of an audit programme. The rules can be turned into `dplyr` code to flag contracts in any new data set. For example, the two high-risk rules become the following. (The tree's line for nomination was ₹109 lakh, which we have rounded to ₹1 crore, for the reason explained below.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworks |>\n  mutate(risk_rule = case_when(\n    window_days < 21 & bidders <= 2                     ~ \"Short window, few bidders\",\n    tender_mode == \"Nomination\" & value_lakh >= 100     ~ \"Large nomination\",\n    .default = \"Other\")) |>\n  summarise(contracts = n(), irregular_pct = round(100 * mean(irregular), 1), .by = risk_rule)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  risk_rule                 contracts irregular_pct\n  <chr>                         <int>         <dbl>\n1 Other                          2760           6.9\n2 Short window, few bidders       176          62.5\n3 Large nomination                 64          54.7\n```\n\n\n:::\n:::\n\n\nThe thresholds from a tree, like ₹109 lakh here, come from the data and can wobble a little from sample to sample. Before writing them into an audit programme, round them to the nearest limit with a meaning, such as the ₹1 crore beyond which a higher authority must approve, or the 21 days required by the rules.\n\n::: callout-tip\n## Audit tip\n\nShow the tree itself to the audit team and to the department. Unlike most models, a tree can be checked against experience. If a rule makes no sense, say a high risk for contracts awarded on a Tuesday, it is probably chance, and the tree should be pruned or the feature dropped. If a rule makes sense but was not known, it is a finding worth sharing.\n:::\n\n## How good is the tree? {#sec-trees-evaluate}\n\nWe judge the tree on the test set, using the AUC from @sec-logistic-evaluate. `predict()` on a tree gives the share of irregular contracts in the leaf each contract falls into.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nauc <- function(score, actual) {\n  r  <- rank(score)\n  n1 <- sum(actual)\n  n0 <- sum(!actual)\n  (sum(r[actual]) - n1 * (n1 + 1) / 2) / (n1 * n0)\n}\ntest <- test |> mutate(tree_score = predict(tree1, newdata = test))\nauc_tree <- auc(test$tree_score, test$irregular == 1)\nauc_tree\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7749985\n```\n\n\n:::\n:::\n\n\nHow does a logistic regression with the same features do?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit1 <- glm(irregular ~ department + tender_mode + value_lakh + window_days + bidders,\n              family = binomial, data = train)\nauc_logit <- auc(predict(logit1, newdata = test), test$irregular == 1)\nauc_logit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6897514\n```\n\n\n:::\n:::\n\n\nThe tree ranks the contracts better, with an AUC of 0.775 against 0.69. The reason is the combinations. In this data, a short window is risky mainly when there are few bidders, and nomination mainly when the contract is large. Logistic regression adds up the effect of each feature separately, so it cannot see this unless we build such combinations ourselves, and to do that we would have to know them already.\n\nThis does not make trees always better. When risk rises smoothly with a feature, like the share of credit from non-filers in @sec-logistic, logistic regression captures it in one number, while a tree can only approximate it with steps. In practice, fit both and compare them on the test set.\n\n**Which features matter?** The tree also reports how much each feature contributed to its splits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(tree1$variable.importance / sum(tree1$variable.importance) * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwindow_days     bidders  value_lakh tender_mode \n         37          32          17          14 \n```\n\n\n:::\n:::\n\n\nThe department does not appear at all. Irregularity here does not depend on the department, which is itself useful to know.\n\n## Trees that grow too far {#sec-trees-prune}\n\nA tree can always be grown until it fits the training data almost perfectly. Let us lower `cp` and the smallest group allowed to split, `minsplit`, and see what happens.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ndeep_tree <- rpart(irregular ~ department + tender_mode + value_lakh + window_days + bidders,\n                   data = train, method = \"anova\",\n                   control = rpart.control(cp = 0.0005, minsplit = 10))\n\nc(leaves    = sum(deep_tree$frame$var == \"<leaf>\"),\n  auc_train = round(auc(predict(deep_tree, train), train$irregular == 1), 3),\n  auc_test  = round(auc(predict(deep_tree, test), test$irregular == 1), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   leaves auc_train  auc_test \n  147.000     0.967     0.653 \n```\n\n\n:::\n:::\n\n\n\n\nThe deep tree has 147 leaves. On the training data its AUC is a splendid 0.967, but on the test data it falls to 0.653, worse than the small tree. It has *memorised* the training contracts, chance coincidences included, instead of learning the general pattern. This is called *overfitting*, and it is the main danger with trees.\n\nThe cure is *pruning*, cutting the tree back to the size that works best on new data. `rpart()` helps by *cross-validation*. While growing the tree, it splits the training data into 10 parts, grows the tree on 9 and checks it on the tenth, ten times over. The results are in the *complexity table*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(deep_tree$cptable, 4) |> head(8)   # the first 8 rows of the complexity table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      CP nsplit rel error xerror   xstd\n1 0.1052      0    1.0000 1.0006 0.0544\n2 0.0859      1    0.8948 0.8970 0.0467\n3 0.0279      2    0.8088 0.8120 0.0476\n4 0.0070      4    0.7530 0.7635 0.0449\n5 0.0051      7    0.7319 0.8022 0.0475\n6 0.0048     10    0.7165 0.8257 0.0489\n7 0.0047     12    0.7068 0.8248 0.0492\n8 0.0041     13    0.7021 0.8362 0.0503\n```\n\n\n:::\n:::\n\n\n\n\nEach row is a tree of a different size (`nsplit` is the number of splits, one less than the number of leaves). `rel error` is the error on the training data, which keeps falling as the tree grows. `xerror` is the cross-validated error, an estimate of the error on new data. It falls at first, and then rises again as the tree starts memorising. The lowest `xerror` here is at 4 splits. `plotcp()` shows the same thing as a chart.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotcp(deep_tree)\n```\n\n::: {.cell-output-display}\n![Cross-validated error by tree size](12-4c-trees_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nWe prune the deep tree at the `cp` with the lowest cross-validated error.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbest_cp <- cpt[which.min(cpt[, \"xerror\"]), \"CP\"]\npruned_tree <- prune(deep_tree, cp = best_cp)\n\nc(leaves   = sum(pruned_tree$frame$var == \"<leaf>\"),\n  auc_test = round(auc(predict(pruned_tree, test), test$irregular == 1), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  leaves auc_test \n   5.000    0.775 \n```\n\n\n:::\n\n```{.r .cell-code}\nrpart.rules(pruned_tree, roundint = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n irregular                                                                                             \n     0.024 when window_days >= 21 & tender_mode is      Nomination                  & value_lakh <  109\n     0.043 when window_days >= 21 & tender_mode is Limited or Open                                     \n     0.180 when window_days <  21                                  & bidders >= 2.5                    \n     0.590 when window_days >= 21 & tender_mode is      Nomination                  & value_lakh >= 109\n     0.612 when window_days <  21                                  & bidders <  2.5                    \n```\n\n\n:::\n:::\n\n\nPruning brings the tree back to 5 leaves, with the same rules and the same test AUC as our first tree, far better than the deep tree. A common, more cautious alternative is the *one standard error rule*: choose the smallest tree whose `xerror` is within one `xstd` of the lowest. It gives simpler trees, which are easier to explain.\n\n::: callout-caution\nTrees are *unstable*. A small change in the data can change the first question, and with it the whole tree below. Do not read too much into the exact thresholds or the lower branches of a single tree. Check that the main rules hold on the test set, and, where possible, on a second year's data. Methods which average many trees, such as *random forests* (the package `ranger`), are much more stable and usually rank better, but give up the readable rules which are a tree's main attraction for audit.\n:::\n\n## What rule is actually being applied? {#sec-trees-rules-actual}\n\nTrees have a second, quite different use in audit. Instead of predicting irregularity, we can fit a tree to the *decisions* an office has made, and read off the rule it actually follows. Then we compare it with the rule it is supposed to follow.\n\nA State scholarship scheme is open to students whose family income is up to ₹2.5 lakh a year and who scored at least 60% in their last examination. Here are 2,000 applications from five districts, with the decision taken on each.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the scholarship applications\"}\nset.seed(5)\nm <- 2000\napplications <- tibble(\n  app_id      = sprintf(\"SCH-%04d\", 1:m),\n  district    = sample(c(\"Anandpur\", \"Bhimnagar\", \"Keshavpur\", \"Lalganj\", \"Motipur\"), m, TRUE),\n  applicant   = sample(c(\"Fresh\", \"Renewal\"), m, TRUE, prob = c(0.6, 0.4)),\n  income_lakh = round(runif(m, 0.5, 6), 2),\n  marks_pct   = round(pmin(99, rnorm(m, 66, 12)), 1)\n) |>\n  mutate(decision = case_when(\n    # Planted. Keshavpur quietly applies an income limit of 4 lakh\n    district == \"Keshavpur\" & income_lakh <= 4 & marks_pct >= 60 ~ \"Approved\",\n    income_lakh <= 2.5 & marks_pct >= 60                         ~ \"Approved\",\n    .default = \"Rejected\"))\n# A few decisions which follow no rule at all\nodd <- sample(m, 30)\napplications$decision[odd] <- if_else(applications$decision[odd] == \"Approved\",\n                                      \"Rejected\", \"Approved\")\napplications <- applications |>\n  mutate(decision = factor(decision, levels = c(\"Rejected\", \"Approved\")))\n```\n:::\n\n\nThis time the outcome is a category, so we use `method = \"class\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndecision_tree <- rpart(decision ~ district + applicant + income_lakh + marks_pct,\n                       data = applications, method = \"class\")\nrpart.plot(decision_tree, roundint = FALSE, extra = 104)\n```\n\n::: {.cell-output-display}\n![The rule actually followed in scholarship decisions](12-4c-trees_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nIn a class tree, each box shows the predicted decision, the share of each decision in the group, and the percentage of applications in it (`extra = 104` asks for these). The rules make it plain.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrpart.rules(decision_tree, roundint = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n decision                                                                                                           \n     0.00 when income_lakh is 2.5 to 4.0 & marks_pct <  61 & district is                                   Keshavpur\n     0.00 when income_lakh <  2.5        & marks_pct <  60                                                          \n     0.01 when income_lakh >=        4.0                   & district is                                   Keshavpur\n     0.02 when income_lakh >=        2.5                   & district is Anandpur or Bhimnagar or Lalganj or Motipur\n     0.97 when income_lakh is 2.5 to 4.0 & marks_pct >= 61 & district is                                   Keshavpur\n     0.99 when income_lakh <  2.5        & marks_pct >= 60                                                          \n```\n\n\n:::\n:::\n\n\nThe numbers are the share approved. Across the State, the tree recovers the scheme's rule: income below ₹2.5 lakh and marks of about 60% or more. But in Keshavpur alone there is one more approving rule, for incomes between ₹2.5 lakh and ₹4 lakh. The district has been applying an income limit of ₹4 lakh. No one told the tree to look at districts. It found the deviation because the decisions themselves could not be explained without it.\n\nThe finding is then confirmed and quantified directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napplications |>\n  filter(decision == \"Approved\", income_lakh > 2.5 | marks_pct < 60) |>\n  count(district, name = \"approved_outside_rule\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  district  approved_outside_rule\n  <chr>                     <int>\n1 Anandpur                      7\n2 Bhimnagar                     4\n3 Keshavpur                    67\n4 Lalganj                       3\n5 Motipur                       7\n```\n\n\n:::\n:::\n\n\nThe handful of such cases in the other districts are the scattered odd decisions, each worth checking, but the pattern is in Keshavpur. The next step in audit would be to examine the Keshavpur files, and to see whether any order authorised the higher limit.\n\n::: callout-tip\n## Audit tip\n\nThis \"what rule is really applied\" analysis works for any decision taken against stated criteria: admissions, recruitment, pension and subsidy sanctions, grant of licences, or selection of beneficiaries. If the tree's rule matches the stated one, the process is consistent. If it splits on something that should not matter, such as a district, an officer or a time period, there is a deviation to investigate.\n:::\n\n## A suggested workflow\n\n1. **Define the outcome**: a past audit result coded 0/1 for risk rules, or the decision taken for rule discovery.\n2. **Split** the data into training and test sets (for rule discovery on the full data, this can be skipped).\n3. **Grow a tree** with `rpart()`, `method = \"anova\"` for a 0/1 risk score, or `method = \"class\"` for a category.\n4. **Draw it** with `rpart.plot()`, and **write out the rules** with `rpart.rules()`.\n5. **Check for overfitting**: grow a deeper tree, look at `printcp()` and `plotcp()`, and `prune()` at the lowest cross-validated error.\n6. **Evaluate on the test set** with the AUC, and compare with logistic regression.\n7. **Sense-check the rules** with experienced auditors, and round thresholds to meaningful limits.\n8. **Turn the rules into `dplyr` filters**, and apply them to new data.\n\n::: callout-important\n## Remember\n\n- A decision tree is a chain of yes/no questions learnt from data, and its result is a set of readable rules.\n- Trees find combinations of features, like \"short window *and* few bidders\", by themselves.\n- Deep trees memorise their training data. Prune them using the cross-validated error.\n- Trees are unstable. Trust the main rules that hold on test data, not every branch.\n- A tree fitted to an office's decisions shows the rule it actually applies.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `rpart()` | rpart | Grow a decision tree; `method = \"anova\"` for a 0/1 risk share or number, `\"class\"` for a category |\n| `rpart.control()` | rpart | Settings for growing, like `cp` and `minsplit` |\n| `printcp()`, `plotcp()` | rpart | Complexity table and chart, with cross-validated error |\n| `prune()` | rpart | Cut a tree back to a given `cp` |\n| `predict()` | stats | Risk score, or class, for new data |\n| `rpart.plot()` | rpart.plot | Draw a tree |\n| `rpart.rules()` | rpart.plot | Write out the rules of a tree, one per leaf |\n| `glm()` | stats | Logistic regression, for comparison |\n| `case_when()` | dplyr | Turn the tree's rules into flags |\n\n: Functions used in this chapter {#tbl-treefunctions}\n",
    "supporting": [
      "12-4c-trees_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}