{
  "hash": "f059131d1d7dcd293bd2390f306c7e05",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Large Data with DuckDB {#sec-duckdb}\n\nAudit data keeps getting bigger. A year of treasury vouchers of a State, the GST returns of a commissionerate, the billing records of an electricity distribution company, or the transactions of a scheme paid through PFMS easily run into crores of rows. Excel stops at 10,48,576 rows. R does better, but it normally reads the whole data into the computer's memory (RAM) before doing anything. With a few crore rows, that is slow, and on an ordinary office laptop it may not be possible at all.\n\n**DuckDB** solves this problem. It is a database engine that runs *inside* R, with nothing to set up, no server, and no database administrator. It can read CSV and Parquet files directly from the disk, without loading them into R, and it is remarkably fast. Best of all, with the package **dbplyr** we use the same `dplyr` verbs we already know (@sec-DPLYRR). We write `filter()`, `summarise()` and `left_join()` as usual, and dbplyr quietly translates them into SQL, the language of databases, for DuckDB to run.\n\nThink of it like this. R is the officer who decides what is to be examined. DuckDB is a very fast assistant in the record room. Instead of having every register carried to the officer's table, the officer sends instructions, the assistant goes through the registers where they lie, and brings back only the summary asked for.\n\n**Prerequisites**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(duckdb)   # the database engine; also loads DBI\nlibrary(dbplyr)   # translates dplyr code into SQL\n```\n:::\n\n\nInstall them once with `install.packages(c(\"duckdb\", \"dbplyr\"))`.\n\n## Our data, a year of treasury vouchers {#sec-duckdb-data}\n\nThe treasuries of a State have given us the payment vouchers of the financial year 2024-25, as 12 monthly CSV files. Each row is one payment: the voucher number, the drawing and disbursing officer (DDO) who drew it, the date, the type of bill, the payee, the payee's bank account and the amount. There are 24 lakh rows in all, more than twice what Excel can open.\n\nThe code below creates the files in a temporary folder. In a real audit the files would arrive from the department, and this step would not exist. Two kinds of irregularity are planted, which we will find later.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the 12 monthly voucher files\"}\nset.seed(2025)\nn <- 2400000\nddo_master <- tibble(\n  ddo_code   = sprintf(\"DDO%04d\", 1:800),\n  treasury   = sample(sprintf(\"TR%02d\", 1:20), 800, TRUE),\n  department = sample(c(\"Education\", \"Health\", \"Police\", \"Revenue\", \"Public Works\",\n                        \"Agriculture\", \"Rural Development\", \"Water Resources\"), 800, TRUE)\n)\n# More payments towards the end of the year, especially in March\nmonth_wt <- c(7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 13)    # April to March\ndates    <- seq(as.Date(\"2024-04-01\"), as.Date(\"2025-03-31\"), by = \"day\")\nfy_month <- (month(dates) - 4) %% 12 + 1\ndate_wt  <- month_wt[fy_month] / tabulate(fy_month)[fy_month]\n\nvouchers <- tibble(\n  voucher_no   = sprintf(\"V%08d\", 1:n),\n  ddo_code     = sample(ddo_master$ddo_code, n, TRUE),\n  voucher_date = sample(dates, n, TRUE, prob = date_wt),\n  bill_type    = sample(c(\"Salary\", \"Contingent\", \"Works\", \"Grant\", \"Pension\"), n, TRUE,\n                        prob = c(0.45, 0.25, 0.10, 0.10, 0.10)),\n  payee_id     = sprintf(\"P%07d\", sample(1:400000, n, TRUE)),\n  amount       = round(rlnorm(n, log(25000), 1.1))\n) |>\n  mutate(payee_account = paste0(\"AC\", substr(payee_id, 2, 8), \"0\"))\n\n# Planted 1. Contingent and works bills paid twice, under a new voucher number\ndup <- vouchers |>\n  filter(bill_type %in% c(\"Contingent\", \"Works\")) |>\n  slice_sample(n = 400) |>\n  mutate(voucher_no = sprintf(\"V9%07d\", row_number()))\n\n# Planted 2. Salaries of 14 \"employees\" in three DDOs credited to one bank account\nghost <- vouchers |>\n  filter(bill_type == \"Salary\") |>\n  slice_sample(n = 14 * 12) |>\n  mutate(payee_id      = rep(sprintf(\"P8%06d\", 1:14), 12),\n         ddo_code      = rep(c(\"DDO0117\", \"DDO0342\", \"DDO0655\"), length.out = n()),\n         payee_account = \"AC00451230\",\n         amount        = round(runif(n(), 38000, 52000)))\n\nvouchers <- bind_rows(vouchers, dup, ghost) |> arrange(voucher_date)\n\n# Write one CSV file per month, as received from the treasuries\ndata_dir <- file.path(tempdir(), \"treasury\")\ndir.create(data_dir, showWarnings = FALSE)\nvouchers |>\n  split(format(vouchers$voucher_date, \"%Y_%m\")) |>\n  iwalk(\\(d, m) write_csv(d, file.path(data_dir, paste0(\"vouchers_\", m, \".csv\"))))\n\nrm(vouchers)   # from here on, the data exist only as files on the disk\n```\n:::\n\n\nLet us see what we have received.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncsv_files <- list.files(data_dir, pattern = \"^vouchers_.*csv$\", full.names = TRUE)\ntibble(file = basename(csv_files), size_mb = round(file.size(csv_files) / 1e6, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 2\n   file                 size_mb\n   <chr>                  <dbl>\n 1 vouchers_2024_04.csv    10.5\n 2 vouchers_2024_05.csv    10.5\n 3 vouchers_2024_06.csv    12.1\n 4 vouchers_2024_07.csv    12.1\n 5 vouchers_2024_08.csv    12.1\n 6 vouchers_2024_09.csv    12.1\n 7 vouchers_2024_10.csv    12.1\n 8 vouchers_2024_11.csv    12.1\n 9 vouchers_2024_12.csv    12  \n10 vouchers_2025_01.csv    12  \n11 vouchers_2025_02.csv    13.6\n12 vouchers_2025_03.csv    19.6\n```\n\n\n:::\n:::\n\n\n\n\nTwelve files, 151 MB in all. Notice that we removed the data from R's memory at the end of the code above. From now on, we work on the files directly.\n\n## Connecting to DuckDB {#sec-duckdb-connect}\n\nFirst we start DuckDB and *connect* to it. `dbConnect()` comes from the package `DBI`, which works the same way for every database R can talk to.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncon <- dbConnect(duckdb())\n```\n:::\n\n\nThis creates a database in memory, which disappears when we disconnect. Now we tell DuckDB where the files are. A single line of SQL creates a *view* named `vouchers`, a name for \"all the rows in all the files matching this pattern\". The `*` in the file name matches every month.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncsv_pattern <- file.path(normalizePath(data_dir, winslash = \"/\"), \"vouchers_*.csv\")\ndbExecute(con, paste0(\"CREATE VIEW vouchers AS SELECT * FROM read_csv('\", csv_pattern, \"')\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n(`normalizePath(..., winslash = \"/\")` writes the folder path with forward slashes, which DuckDB prefers, even on Windows.) Finally, `tbl()` gives us an R object pointing at the view, which we can use like a data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvouchers <- tbl(con, \"vouchers\")\nvouchers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A query:  ?? x 7\n# Database: DuckDB 1.5.6 [Anil@Windows 10 x64:R 4.5.2/:memory:]\n   voucher_no ddo_code voucher_date bill_type  payee_id amount payee_account\n   <chr>      <chr>    <date>       <chr>      <chr>     <dbl> <chr>        \n 1 V00000471  DDO0580  2024-04-01   Salary     P0005033  19806 AC00050330   \n 2 V00000710  DDO0194  2024-04-01   Salary     P0188115  24896 AC01881150   \n 3 V00000948  DDO0512  2024-04-01   Salary     P0290244  26076 AC02902440   \n 4 V00001349  DDO0074  2024-04-01   Works      P0226584 185274 AC02265840   \n 5 V00002042  DDO0277  2024-04-01   Contingent P0299634  36128 AC02996340   \n 6 V00002913  DDO0211  2024-04-01   Pension    P0244040  16991 AC02440400   \n 7 V00003324  DDO0791  2024-04-01   Grant      P0050727  17697 AC00507270   \n 8 V00003476  DDO0218  2024-04-01   Grant      P0023304  11740 AC00233040   \n 9 V00003543  DDO0078  2024-04-01   Salary     P0278314   3648 AC02783140   \n10 V00003697  DDO0434  2024-04-01   Salary     P0295210   3762 AC02952100   \n# ℹ more rows\n```\n\n\n:::\n:::\n\n\nIt looks like a tibble, with two differences. The header says `# Source: SQL` and the database, and the number of rows is shown as `??`. DuckDB has only peeked at the first few rows to show us a preview. It has not read the files yet.\n\n## Lazy queries and `collect()` {#sec-duckdb-lazy}\n\nThis is the one new idea in this chapter. A table from a database is **lazy**. When we write `dplyr` code on it, nothing is computed. dbplyr only writes down what we want. The work is done when we ask to see the result, and then only the *result* comes into R.\n\nLet us count the rows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrow_time <- system.time(\n  n_rows <- vouchers |> count() |> pull(n)\n)\nn_rows\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2400568\n```\n\n\n:::\n:::\n\n\nDuckDB read all twelve files and counted 2,400,568 rows in 0.44 seconds. Now a real summary, the number and value of payments in each month.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly <- vouchers |>\n  mutate(year = year(voucher_date), month = month(voucher_date)) |>\n  summarise(payments = n(), crore = sum(amount, na.rm = TRUE) / 1e7, .by = c(year, month)) |>\n  arrange(year, month)\n\nmonthly\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A query:    ?? x 4\n# Database:   DuckDB 1.5.6 [Anil@Windows 10 x64:R 4.5.2/:memory:]\n# Ordered by: year, month\n    year month payments crore\n   <dbl> <dbl>    <dbl> <dbl>\n 1  2024     4   167934  772.\n 2  2024     5   167501  767.\n 3  2024     6   192435  880.\n 4  2024     7   192070  881.\n 5  2024     8   192671  877.\n 6  2024     9   192538  877.\n 7  2024    10   192201  884.\n 8  2024    11   192310  884.\n 9  2024    12   191729  878.\n10  2025     1   191369  873.\n11  2025     2   215955  989.\n12  2025     3   311855 1428.\n```\n\n\n:::\n:::\n\n\nPrinting a lazy query shows the first rows of the result, which is enough to check that it is right. To bring the full result into R as an ordinary tibble, for a chart or for further work, we use **`collect()`**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly_df <- collect(monthly)\nclass(monthly_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"tbl_df\"     \"tbl\"        \"data.frame\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly_df |>\n  mutate(month_label = factor(month.abb[month], levels = month.abb[c(4:12, 1:3)])) |>\n  ggplot(aes(month_label, crore)) +\n  geom_col(fill = \"steelblue\") +\n  labs(x = NULL, y = \"₹ crore\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Payments by month, 2024-25. March stands out.](12-8b-duckdb_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n**What does dbplyr send to DuckDB?** `show_query()` prints the SQL it has written for us.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshow_query(monthly)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<SQL>\nSELECT \"year\", \"month\", COUNT(*) AS payments, SUM(amount) / 10000000.0 AS crore\nFROM (\n  SELECT\n    *,\n    EXTRACT(year FROM voucher_date) AS \"year\",\n    EXTRACT(MONTH FROM voucher_date) AS \"month\"\n  FROM vouchers\n) AS q01\nGROUP BY \"year\", \"month\"\nORDER BY \"year\", \"month\"\n```\n\n\n:::\n:::\n\n\nWe never have to write this ourselves. But it is worth a look. Auditors who know SQL, or the \"equations\" of tools like IDEA and ACL, will recognise `SELECT`, `GROUP BY` and `ORDER BY`. And reading the SQL is a good way to confirm that dbplyr has understood what we meant.\n\n::: callout-note\n## Missing values in databases\n\nIn R, `sum(c(5, NA))` is `NA`, as we saw in @sec-basics. In SQL, missing values (called `NULL`) are simply *left out* of sums and averages. dbplyr warns about this the first time, unless we write `na.rm = TRUE`, as we did above, to show that we know. Keep the difference in mind. A total from a database never tells you that some amounts were missing, so count the missing values separately with `sum(is.na(amount))`.\n:::\n\n## Audit tests on the full data {#sec-duckdb-tests}\n\nNow let us run some real tests, on all 24 lakh rows, exactly as we would on a small data frame.\n\n### Which DDOs rushed their spending into March?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmarch_rush <- vouchers |>\n  summarise(total = sum(amount, na.rm = TRUE),\n            march = sum(if_else(month(voucher_date) == 3, amount, 0), na.rm = TRUE),\n            .by = ddo_code) |>\n  mutate(march_share = march / total) |>\n  slice_max(march_share, n = 10) |>\n  collect()\n\nmarch_rush |> mutate(across(c(total, march), \\(x) round(x / 1e5, 1)),\n                     march_share = round(100 * march_share, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   ddo_code total march march_share\n   <chr>    <dbl> <dbl>       <dbl>\n 1 DDO0070  1367.  232         17  \n 2 DDO0469  1440.  243.        16.8\n 3 DDO0687  1463.  243.        16.6\n 4 DDO0045  1344.  216         16.1\n 5 DDO0731  1378.  220         16  \n 6 DDO0583  1308.  208         15.9\n 7 DDO0231  1298.  206.        15.9\n 8 DDO0166  1388.  220.        15.9\n 9 DDO0374  1424.  225         15.8\n10 DDO0700  1370.  216.        15.8\n```\n\n\n:::\n:::\n\n\n\n\nAcross the State, March accounts for 13% of the year's payments. These DDOs spent 16% or more in March alone, and would be the first to examine for the rush of expenditure.\n\n### Duplicate payments\n\nA *same-same-same* test (@sec-dup): the same bank account, the same amount and the same date, under different voucher numbers. We restrict it to contingent and works bills, where a repeated payment is suspicious. (Salaries and pensions legitimately repeat the same amount every month, though not on the same date.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduplicates <- vouchers |>\n  filter(bill_type %in% c(\"Contingent\", \"Works\")) |>\n  summarise(times_paid = n(), .by = c(payee_account, amount, voucher_date)) |>\n  filter(times_paid > 1)\n\nduplicates |>\n  summarise(groups = n(), excess_paid = sum(amount * (times_paid - 1), na.rm = TRUE)) |>\n  collect()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  groups excess_paid\n   <dbl>       <dbl>\n1    400    18090218\n```\n\n\n:::\n:::\n\n\n\n\n400 groups of payments were made more than once, with ₹1.81 crore paid in excess. To examine them, we bring only these rows into R. A join with the full table gives the voucher details, and still only the matching rows are collected.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndup_vouchers <- vouchers |>\n  semi_join(duplicates, by = c(\"payee_account\", \"amount\", \"voucher_date\")) |>\n  arrange(payee_account, voucher_date) |>\n  collect()\nnrow(dup_vouchers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 800\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(dup_vouchers, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  voucher_no ddo_code voucher_date bill_type  payee_id amount payee_account\n  <chr>      <chr>    <date>       <chr>      <chr>     <dbl> <chr>        \n1 V01632177  DDO0319  2024-05-05   Contingent P0000121   3921 AC00001210   \n2 V90000293  DDO0319  2024-05-05   Contingent P0000121   3921 AC00001210   \n3 V02344665  DDO0144  2024-10-25   Contingent P0000664  34458 AC00006640   \n4 V90000317  DDO0144  2024-10-25   Contingent P0000664  34458 AC00006640   \n5 V90000304  DDO0147  2024-12-06   Contingent P0001019   8647 AC00010190   \n6 V00910001  DDO0147  2024-12-06   Contingent P0001019   8647 AC00010190   \n```\n\n\n:::\n:::\n\n\n### One bank account, many employees\n\nSalaries of different employees should go to different bank accounts. An account receiving the salary of several persons may indicate *ghost employees*, whose pay is drawn into one person's account.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshared_accounts <- vouchers |>\n  filter(bill_type == \"Salary\") |>\n  summarise(employees = n_distinct(payee_id), ddos = n_distinct(ddo_code),\n            amount = sum(amount, na.rm = TRUE), .by = payee_account) |>\n  filter(employees > 1) |>\n  arrange(desc(employees)) |>\n  collect()\nshared_accounts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  payee_account employees  ddos  amount\n  <chr>             <dbl> <dbl>   <dbl>\n1 AC00451230           15     4 7560303\n```\n\n\n:::\n:::\n\n\n\n\nOne account, AC00451230, received the salary of 15 different payees, drawn by 4 DDOs, ₹75.6 lakh in the year. The next step is to collect its vouchers, and ask the DDOs for the service records of these \"employees\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvouchers |>\n  filter(payee_account == !!sa$payee_account) |>\n  count(ddo_code, payee_id) |>\n  arrange(ddo_code, payee_id) |>\n  collect() |>\n  head(8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 3\n  ddo_code payee_id     n\n  <chr>    <chr>    <dbl>\n1 DDO0096  P0045123     1\n2 DDO0117  P8000001     4\n3 DDO0117  P8000002     4\n4 DDO0117  P8000003     4\n5 DDO0117  P8000004     4\n6 DDO0117  P8000005     4\n7 DDO0117  P8000006     4\n8 DDO0117  P8000007     4\n```\n\n\n:::\n:::\n\n\nThe first row is the account's genuine holder, a single payee in one DDO. The other 14 payees, in three other DDOs, all have their salaries credited to this one account. The `!!` in front of `sa$payee_account` tells dbplyr to insert the *value* of this R object into the query, rather than look for a column of that name in the database.\n\n## Joining with data in R {#sec-duckdb-join}\n\nOften a small table lives in R, like the DDO master with each DDO's department, and we want to join it with the large table in the database. `copy_to()` sends the small table to DuckDB, and the join is then done there.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nddo_db <- copy_to(con, ddo_master, name = \"ddo_master\", overwrite = TRUE)\n\nvouchers |>\n  left_join(ddo_db, by = \"ddo_code\") |>\n  summarise(crore = sum(amount, na.rm = TRUE) / 1e7, .by = department) |>\n  arrange(desc(crore)) |>\n  collect()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 2\n  department        crore\n  <chr>             <dbl>\n1 Health            1654.\n2 Agriculture       1480.\n3 Rural Development 1413.\n4 Education         1328.\n5 Public Works      1309.\n6 Revenue           1278.\n7 Police            1266.\n8 Water Resources   1263.\n```\n\n\n:::\n:::\n\n\nAll the join checks of @sec-joins still apply. Compare row counts and totals before and after, and use `anti_join()` to find vouchers whose DDO code is not in the master.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvouchers |> anti_join(ddo_db, by = \"ddo_code\") |> count() |> pull(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n## When dbplyr cannot translate {#sec-duckdb-translate}\n\ndbplyr knows how to translate most `dplyr` verbs, and many common functions, like `if_else()`, `case_when()`, `year()`, `month()`, `n_distinct()`, `str_detect()` and `round()`, into SQL. But it cannot translate a function it does not know, such as one we wrote ourselves. Remember the `fin_year()` function of @sec-lubri-audit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfin_year <- function(date) {\n  start <- if_else(month(date) >= 4, year(date), year(date) - 1)\n  paste0(start, \"-\", sprintf(\"%02d\", (start + 1) %% 100))\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvouchers |> mutate(fy = fin_year(voucher_date)) |> head()\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `collect()`:\n! Failed to collect lazy table.\nCaused by error in `DBI::dbSendQuery()`:\n! Catalog Error: Scalar Function with name fin_year does not exist!\nDid you mean \"isoyear\"?\n\nLINE 1: SELECT *, fin_year(voucher_date) AS fy\n                  ^\nℹ Context: rapi_prepare\nℹ Error type: CATALOG\n```\n\n\n:::\n:::\n\n\ndbplyr does not look inside our function. It passes the name `fin_year` on to DuckDB as it is, and DuckDB has never heard of it. (Even if we copied the code in, `sprintf()` has no translation either.) There are two ways out.\n\n1. **Filter and summarise in the database, then `collect()`, then use any R function** on the much smaller result. This is the usual pattern: let DuckDB cut the data down, and let R do the rest.\n2. **Rewrite the logic with functions dbplyr knows.** Here, `if_else()`, `year()` and `month()` are enough to compute the starting year of the financial year inside the database.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvouchers |>\n  mutate(fy_start = if_else(month(voucher_date) >= 4, year(voucher_date), year(voucher_date) - 1)) |>\n  count(fy_start) |>\n  collect()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  fy_start       n\n     <dbl>   <dbl>\n1     2024 2400568\n```\n\n\n:::\n:::\n\n\n::: callout-caution\nRows in a database have no fixed order. Without `arrange()`, the same query may return rows in a different order each time, and `head()` may show different rows. Always `arrange()` before `head()`, or before comparing results.\n:::\n\n## Writing SQL directly {#sec-duckdb-sql}\n\nThose who know SQL can send it straight to DuckDB with `dbGetQuery()`, which returns a data frame. This is also how audit queries written for other databases can be reused.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbGetQuery(con, \"\n  SELECT bill_type, COUNT(*) AS payments, ROUND(SUM(amount) / 1e7, 1) AS crore\n  FROM vouchers\n  GROUP BY bill_type\n  ORDER BY crore DESC\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   bill_type payments  crore\n1     Salary  1080416 4947.9\n2 Contingent   600993 2744.6\n3      Grant   240263 1101.6\n4      Works   239308 1100.4\n5    Pension   239588 1096.6\n```\n\n\n:::\n:::\n\n\n## Parquet, a better format for large data {#sec-duckdb-parquet}\n\nCSV files are simple, but large and slow to read, because every number is stored as text. **Parquet** is a file format designed for large data. It stores each column together, compressed, with its type. DuckDB can write and read it directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparquet_file <- file.path(normalizePath(data_dir, winslash = \"/\"), \"vouchers_2024_25.parquet\")\ndbExecute(con, paste0(\"COPY (SELECT * FROM vouchers) TO '\", parquet_file, \"' (FORMAT parquet)\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2400568\n```\n\n\n:::\n\n```{.r .cell-code}\nparquet_mb <- file.size(parquet_file) / 1e6\nc(csv_mb = round(csv_mb), parquet_mb = round(parquet_mb))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    csv_mb parquet_mb \n       151         58 \n```\n\n\n:::\n:::\n\n\nThe same data take 58 MB instead of 151 MB. And queries are faster still. `read_parquet()` takes the place of `read_csv()` in the view.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbExecute(con, paste0(\"CREATE VIEW vouchers_pq AS SELECT * FROM read_parquet('\", parquet_file, \"')\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nvouchers_pq <- tbl(con, \"vouchers_pq\")\n\npq_time <- system.time(\n  by_type <- vouchers_pq |> count(bill_type) |> arrange(bill_type) |> collect()\n)\nby_type\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  bill_type        n\n  <chr>        <dbl>\n1 Contingent  600993\n2 Grant       240263\n3 Pension     239588\n4 Salary     1080416\n5 Works       239308\n```\n\n\n:::\n:::\n\n\nThis query took 0.04 seconds.\n\n::: callout-tip\n## Audit tip\n\nWhen a large data set arrives, keep the original files untouched, record their hashes as in @sec-file-hash, and convert a working copy to Parquet once. All further analysis then runs on the Parquet file, which is smaller and much faster, and the original files remain as received, for evidence.\n:::\n\n## How much faster? {#sec-duckdb-speed}\n\nLet us compare with the usual way, reading all the CSV files into R with `read_csv()` and then summarising.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreadr_time <- system.time({\n  all_rows <- read_csv(csv_files, show_col_types = FALSE)\n  all_rows |> count(bill_type)\n})\nin_memory_mb <- as.numeric(object.size(all_rows)) / 1e6\nrm(all_rows)\n\nduck_time <- system.time(\n  vouchers |> count(bill_type) |> collect()\n)\n```\n:::\n\n\n| Approach | Time (seconds) | Memory used by R |\n|----------|---------------|------------------|\n| `read_csv()`, then `count()` | 7 | about 339 MB for the data |\n| DuckDB on the CSV files | 0.29 | only the small result |\n| DuckDB on the Parquet file | 0.04 | only the small result |\n\n: Reading 24 lakh rows, three ways {#tbl-duckdb-speed}\n\nThe times will differ on your computer, but the pattern will not. And the difference grows with the data. With a few crore rows, `read_csv()` may fail for lack of memory, while DuckDB works through the files on disk without trouble.\n\n## A database file for repeated work {#sec-duckdb-file}\n\nSo far, DuckDB lived in memory and read the files afresh for every query. For data we will query again and again, over days, we can keep a DuckDB *database file*. Give `dbConnect()` a file name, and load the data into a table once.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncon <- dbConnect(duckdb(), dbdir = \"treasury_2024_25.duckdb\")\ndbExecute(con, \"CREATE TABLE vouchers AS SELECT * FROM read_parquet('vouchers_2024_25.parquet')\")\n# ... next day, in a new R session\ncon <- dbConnect(duckdb(), dbdir = \"treasury_2024_25.duckdb\")\nvouchers <- tbl(con, \"vouchers\")\n```\n:::\n\n\nWhichever way we connect, we disconnect at the end, which also frees the memory.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbDisconnect(con)\n```\n:::\n\n\n## A suggested workflow\n\n1. **Keep the original files untouched**, and record their hashes.\n2. **Connect** with `dbConnect(duckdb())`, and create a view over the files with `read_csv()`, using a `*` pattern for many files.\n3. **Point `tbl()` at the view**, and check a preview and the row count against the control totals received with the data.\n4. **Convert to Parquet** if the data will be used more than once, and query that instead.\n5. **Write the analysis in `dplyr`**, as usual. Use `show_query()` when in doubt.\n6. **Filter and summarise in DuckDB**, and `collect()` only the small result, or the exceptions.\n7. **Use R-only functions after `collect()`**, or rewrite them with translatable functions.\n8. **Disconnect** at the end.\n\n::: callout-important\n## Remember\n\n- DuckDB runs inside R and queries large CSV and Parquet files on disk, without loading them into memory.\n- With dbplyr, we use the same `dplyr` verbs; they are translated into SQL.\n- Database tables are lazy. Nothing happens until we print or `collect()` the result.\n- Let DuckDB cut the data down, and bring only the result into R.\n- Missing values are silently left out of SQL sums; check for them separately.\n- Parquet files are smaller and faster than CSV; keep the originals for evidence.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `dbConnect(duckdb())`, `dbDisconnect()` | DBI, duckdb | Start and close a DuckDB database, in memory or in a file |\n| `dbExecute()` | DBI | Run an SQL command, like creating a view or writing Parquet |\n| `dbGetQuery()` | DBI | Run an SQL query and get a data frame |\n| `read_csv()`, `read_parquet()` (inside SQL) | DuckDB | Read CSV or Parquet files, including many files with a `*` pattern |\n| `tbl()` | dplyr | Point at a table or view in the database |\n| `collect()` | dplyr | Run the query and bring the result into R |\n| `show_query()` | dplyr | Show the SQL that dbplyr has written |\n| `copy_to()` | dplyr | Send a small R table to the database, for joins |\n| `!!` | rlang | Insert the value of an R object into a database query |\n| `normalizePath()` | base R | Write a folder path with forward slashes for DuckDB |\n| `system.time()` | base R | Time a piece of code |\n\n: Functions used in this chapter {#tbl-duckdbfunctions}\n",
    "supporting": [
      "12-8b-duckdb_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}