# Various Datasets, in base R, used in this book
```{r echo=FALSE}
helpExtract <- function(Function, section = "Usage", type = "m_code", ...) {
  A <- deparse(substitute(Function))
  x <- capture.output(tools:::Rd2txt(utils:::.getHelpFile(help(A, ...)),
                                     options = list(sectionIndent = 0)))
  B <- grep("^_", x)                    ## section start lines
  x <- gsub("_\b", "", x, fixed = TRUE) ## remove "_\b"
  X <- rep(FALSE, length(x))
  X[B] <- 1
  out <- split(x, cumsum(X))
  out <- out[[which(sapply(out, function(x) 
    grepl(section, x[1], fixed = TRUE)))]][-c(1, 2)]
  while(TRUE) {
    out <- out[-length(out)]
    if (out[length(out)] != "") { break }
  } 

  switch(
    type,
    m_code = c("```r", out, "```"),
    s_code = c("<<>>=", out, "@"),
    m_text = paste("    ", out, collapse = "\n"),
    s_text = c("\\begin{verbatim}", out, "\\end{verbatim}"),
    stop("`type` must be either `m_code`, `s_code`, `m_text`, or `s_text`")
  )
}
```

- `Nile`:
```{r, echo=FALSE, results='asis'}
cat(helpExtract(Nile, section = "Desc", type = "m_text"))
```

- `lynx`: 
```{r, echo=FALSE, results='asis'}
cat(helpExtract(lynx, section = "Desc", type = "m_text"))
```

- `mtcars`: 
```{r, echo=FALSE, results='asis'}
cat(helpExtract(mtcars, section = "Desc", type = "m_text"))
```

- `sunspot.month`:
```{r, echo=FALSE, results='asis'}
cat(helpExtract(sunspot.month, section = "Desc", type = "m_text"))
```

- `nhtemp`:
```{r, echo=FALSE, results='asis'}
cat(helpExtract(nhtemp, section = "Desc", type = "m_text"))
```

- `airquality`:
```{r, echo=FALSE, results='asis'}
cat(helpExtract(airquality, section = "Desc", type = "m_text"))
```

- `JohnsonJohnson`:
```{r, echo=FALSE, results='asis'}
cat(helpExtract(JohnsonJohnson, section = "Desc", type = "m_text"))
```

- `iris`:
```{r, echo=FALSE, results='asis'}
cat(helpExtract(iris, section = "Desc", type = "m_text"))
```

- `attitude`:
```{r, echo=FALSE, results='asis'}
cat(helpExtract(attitude, section = "Desc", type = "m_text"))
```

- `longley`:
```{r, echo=FALSE, results='asis'}
cat(helpExtract(longley, section = "Desc", type = "m_text"))
```

- `USArrests`:
```{r, echo=FALSE, results='asis'}
cat(helpExtract(USArrests, section = "Desc", type = "m_text"))
```


