project:
  type: book
  output-dir: _book

book:
  title: "R for Audit Analytics"
  author: "Anil Goyal"
  date: today
  site-url: https://anilyayavar.github.io/new-book/
  repo-url: https://github.com/anilyayavar/new-book
  repo-actions: [edit, issue]
  cover-image: images/cover.jpg
  description: "This book is intended for auditors performing exploratory data analytics using R programming language, mainly Base R and Tidyverse."
  license: "CC BY-NC"
  chapters:
    - index.qmd
    - index-preface.qmd
    - index-about-author.qmd
    - 00-Zero.qmd
    - part: "Part I: R Basics"
      chapters:
        - 02-basics.qmd
        - 03-Subsets.qmd
        - 04-functions.qmd
        - 04-functions-existing-and-useful-functions-in-base-r.qmd
        - 04-functions-pipes-in-r.qmd
        - 05-1conditionals.qmd
        - 06-1-functionalprog.qmd
    - part: "Part II: Getting and Shaping Data"
      chapters:
        - 06-2-workflow.qmd
        - 07-1-reading.qmd
        - 07-1-reading-data-cleaning-in-r.qmd
        - 07-2-merge.qmd
        - 10-1-dplyr.qmd
        - 10-2-joins.qmd
        - 11-tidyr.qmd
        - 12-8Lubridate.qmd
    - part: "Part III: Exploring Data, Statistics and Sampling"
      chapters:
        - 08-plot.qmd
        - 09-1ggplot2.qmd
        - 14-3Factors.qmd
        - 12-1Desc.qmd
        - 12-2stats.qmd
        - 12-3Samp.qmd
        - 12-3b-tests.qmd
    - part: "Part IV: Working with Strings"
      chapters:
        - 14-1Stringr.qmd
        - 14-2Regex.qmd
        - 14-2Regex-regex-in-human-readble-format-using-rebu.qmd
        - 15-stringdist.qmd
    - part: "Part V: Forensic Tests for Audit"
      chapters:
        - 17-Anamolous.qmd
        - 19-nigrini-tests.qmd
        - 20-duplicates.qmd
        - 21-gaps.qmd
    - part: "Part VI: Patterns and Anomalies (Machine Learning)"
      chapters:
        - 12-4Reg.qmd
        - 12-4b-logistic.qmd
        - 12-4c-trees.qmd
        - 12-5PCA.qmd
        - 12-6KMeans.qmd
        - 12-7Apriori.qmd
        - 12-9ts.qmd
        - 18-anomaly.qmd
        - 26-DEA.qmd
    - part: "Part VII: Text Analytics"
      chapters:
        - 14-4text.qmd
        - 14-4text-sentiment-analysis.qmd
        - 14-4text-visualising-text-analytics-through-wordc.qmd
    - part: "Part VIII: Network Analytics"
      chapters:
        - 13-Network.qmd
        - 13-Network-applying-network-analysis-in-audit-fraud.qmd
    - part: "Part IX: Geospatial Analytics"
      chapters:
        - 16-Rgeo.qmd
        - 16-Rgeo-geo-coding-in-r.qmd
        - 16-Rgeo-reverse-geo-coding.qmd
    - references.qmd
  appendices:
    - 97-colors.qmd
    - 98-datasets.qmd

bibliography: [book.bib, packages.bib]
csl: chicago-fullnote-bibliography.csl

execute:
  freeze: auto

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: style.css
    code-link: true
    toc-depth: 3
    fig-align: center

editor: source
