```{r}
#| include: false
source("_common.R")
```

# About author {.unnumbered}

Anil Goyal is a data analytics enthusiast who has been working in the Indian Audit and Accounts Department since 1998. Anil has a passion for learning and applying programming languages/other tools such as R and Tableau to solve data-related challenges.

Anil is a self-taught expert in R, and has been involved in a variety of data analytics projects and audits.

Anil holds a post-graduate degree in Mathematics from the University of Rajasthan, Jaipur, which he received in 1998. This book is his first book. He continues to expand his skill set and knowledge in this field. Anil also loves to solve problems raised by various users on [StackOverflow.com](https://stackoverflow.com/users/2884859/anilgoyal) mainly related to R language.

When not working with data, Anil enjoys pursuing his personal interests, which include [photographying birds](https://www.flickr.com/search/?user_id=121352773%40N04&view_all=1&text=birds), [nature](https://www.flickr.com/search/?user_id=121352773%40N04&view_all=1&text=landscape); reading and watching movies, etc..
