{
  "hash": "9375bebe74927f41699d97d8d0b9f89c",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Statistical Tests for Auditors {#sec-tests}\n\nAn auditor finds that one office approves 91 out of every 100 medical claims, while the rest of the department approves 84. Is that office lax in its checks, or is the difference just the kind of variation we should expect between any two offices? One dealing officer's claims are larger on average than everyone else's. Is that a pattern worth an inquiry, or a coincidence?\n\nThese are the questions a *statistical test* answers. It tells us whether a difference we see is larger than chance alone would usually produce. A test does not prove an irregularity. But it helps us decide where to spend our limited audit time, and it protects us from two embarrassments: chasing differences that mean nothing, and missing ones that matter.\n\nIn this chapter we learn the idea of a test in plain words, and then the tests an auditor needs most often. Each answers a question that comes up in real audits.\n\n**Prerequisites**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)   # turns test results into tidy tables\n```\n:::\n\n\nAll the tests themselves come with base R, in the package `stats`, which is always loaded.\n\n## The idea of a test {#sec-tests-idea}\n\nEvery test follows the same reasoning, which is very close to how an auditor already thinks.\n\n1. **Start by assuming nothing is unusual.** This assumption is called the *null hypothesis*. For example, \"this office approves claims at the same rate as the others\". It is like presuming an auditee innocent until the evidence says otherwise.\n2. **Ask how surprising the data would be, if nothing were unusual.** The answer is the *p-value*, a probability between 0 and 1. A p-value of 0.30 means that, if nothing were unusual, a difference at least this large would turn up 30% of the time by chance alone. Not surprising at all. A p-value of 0.001 means it would turn up only once in a thousand times. Very surprising.\n3. **Decide.** If the p-value is small, below a limit we fix in advance, we conclude that chance is an unlikely explanation, and call the difference *statistically significant*. The usual limit is 0.05, or 5%.\n\nA test can go wrong in two ways, and both have an audit meaning.\n\n| | Nothing is actually unusual | Something is actually unusual |\n|-------------------|--------------------------|--------------------------|\n| **Test says significant** | *Type I error*, a false alarm. Time wasted on an inquiry, and an auditee questioned unfairly. | Correct. A real issue found. |\n| **Test says not significant** | Correct. No time wasted. | *Type II error*, a miss. A real issue goes unreported. This is audit risk. |\n\n: The two errors of a test, in audit terms {#tbl-test-errors}\n\nThe 5% limit is the chance of a false alarm we are willing to accept. A smaller limit means fewer false alarms but more misses. With a small sample, a test may miss even a large difference, as we will see.\n\n::: callout-note\n## What if we have the whole population?\n\nAuditors often analyse 100% of the data, not a sample. If one office approved 94% of its claims and another 86%, that difference is a *fact*. Why test it? Because claims are approved or rejected for many reasons, and even two identical offices would not show identical rates in a year. The test asks whether the difference is larger than this ordinary variation in the process. So tests are useful on full data too, as long as we read \"significant\" as \"unlikely to be ordinary variation\", and not as a finding in itself.\n:::\n\n## Our data\n\nWe use one data set through most of the chapter. It is a year's register of medical reimbursement claims of a department with six offices, each office with two dealing officers. For each claim we have the amount, whether it was approved, and the days taken to settle it.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the claims register\"}\nset.seed(6)\nn <- 3000\noffices <- c(\"Amarpur\", \"Belapur\", \"Chandpur\", \"Devgarh\", \"Fatehpur\", \"Rampur\")\nclaims <- tibble(\n  claim_id = sprintf(\"MR-%04d\", 1:n),\n  office   = sample(offices, n, TRUE, prob = c(0.2, 0.18, 0.17, 0.16, 0.15, 0.14)),\n  desk     = sample(1:2, n, TRUE),\n  amount   = round(rlnorm(n, log(18000), 0.8), -1)\n) |>\n  mutate(officer = paste0(toupper(substr(office, 1, 3)), \"-\", desk),\n         # Planted. Officer RAM-2 approves almost everything\n         approved = runif(n) < if_else(officer == \"RAM-2\", 0.97, 0.86),\n         # Planted. Chandpur is slow to settle claims\n         days_to_settle = round(rgamma(n, shape = 4,\n                                       rate = 4 / if_else(office == \"Chandpur\", 27, 21))),\n         # Planted. Claims handled by DEV-2 are inflated\n         amount = if_else(officer == \"DEV-2\", round(amount * 1.4, -1), amount)) |>\n  select(claim_id, office, officer, amount, approved, days_to_settle)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclaims\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,000 × 6\n   claim_id office   officer amount approved days_to_settle\n   <chr>    <chr>    <chr>    <dbl> <lgl>             <dbl>\n 1 MR-0001  Devgarh  DEV-2    91630 TRUE                 15\n 2 MR-0002  Rampur   RAM-1    64380 FALSE                13\n 3 MR-0003  Belapur  BEL-2    55860 FALSE                16\n 4 MR-0004  Chandpur CHA-1    10320 FALSE                45\n 5 MR-0005  Fatehpur FAT-1    44060 TRUE                 20\n 6 MR-0006  Rampur   RAM-2    10610 TRUE                 13\n 7 MR-0007  Rampur   RAM-2    15150 TRUE                  9\n 8 MR-0008  Fatehpur FAT-1    12210 FALSE                15\n 9 MR-0009  Chandpur CHA-1    10460 TRUE                 25\n10 MR-0010  Amarpur  AMA-1    32840 TRUE                  2\n# ℹ 2,990 more rows\n```\n\n\n:::\n:::\n\n\n## Is the error rate above the tolerable rate? {#sec-tests-binom}\n\nLet us start with a question from a test of controls. The auditor checks a random sample of 60 claims, and finds 6 settled without the required verification. The tolerable deviation rate is 5%. The sample's rate is 10%, twice the tolerable rate. Can we conclude that the control is failing?\n\n`binom.test()` compares a count of \"successes\" (here, deviations) in a number of trials with an expected proportion. Since we only care whether the rate is *above* 5%, we use `alternative = \"greater\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndev_test <- binom.test(x = 6, n = 60, p = 0.05, alternative = \"greater\")\ndev_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  6 and 60\nnumber of successes = 6, number of trials = 60, p-value = 0.07872\nalternative hypothesis: true probability of success is greater than 0.05\n95 percent confidence interval:\n 0.04445297 1.00000000\nsample estimates:\nprobability of success \n                   0.1 \n```\n\n\n:::\n:::\n\n\nThe p-value is 0.079, above 0.05. Surprisingly, a sample of 60 with 6 deviations is *not* enough to conclude that the true rate exceeds 5%. With 60 claims, a true rate of 5% would give 6 or more deviations about 8% of the time. The confidence interval says the same: the true rate could be as low as 4.4%.\n\nWhat if the auditor had found 9 deviations instead?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinom.test(x = 9, n = 60, p = 0.05, alternative = \"greater\")$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.002848606\n```\n\n\n:::\n:::\n\n\nNow the conclusion is clear. This is the reason why sample sizes for tests of controls are planned in advance, as we did in @sec-samplesize. A test on a sample too small to detect the difference we care about can only end in \"not proven\".\n\n::: callout-caution\n\"Not significant\" does not mean \"no problem\". It means the data are not strong enough to rule out chance. Never report a control as effective only because a test was not significant, least of all on a small sample. Report what was found, 6 deviations in 60, and the limit of what the sample can tell.\n:::\n\n## Comparing two rates {#sec-tests-prop}\n\nBack to the full register. Rampur approves more claims than the rest of the department. Is the difference more than chance?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclaims |>\n  summarise(claims = n(), n_approved = sum(approved),\n            approval_rate = round(mean(approved), 3),\n            .by = office) |>\n  arrange(desc(approval_rate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  office   claims n_approved approval_rate\n  <chr>     <int>      <int>         <dbl>\n1 Rampur      433        395         0.912\n2 Fatehpur    445        381         0.856\n3 Belapur     527        445         0.844\n4 Amarpur     587        495         0.843\n5 Chandpur    523        440         0.841\n6 Devgarh     485        405         0.835\n```\n\n\n:::\n:::\n\n\n`prop.test()` compares two (or more) proportions. We give it the number approved and the number of claims in each group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrampur <- claims$office == \"Rampur\"\nrampur_test <- prop.test(x = c(sum(claims$approved[rampur]), sum(claims$approved[!rampur])),\n                         n = c(sum(rampur), sum(!rampur)))\nrampur_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(sum(claims$approved[rampur]), sum(claims$approved[!rampur])) out of c(sum(rampur), sum(!rampur))\nX-squared = 13.355, df = 1, p-value = 0.0002577\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.03697932 0.09992800\nsample estimates:\n   prop 1    prop 2 \n0.9122402 0.8437865 \n```\n\n\n:::\n:::\n\n\nRampur approved 91.2% of its claims, against 84.4% elsewhere. The p-value is 0.00026, far below 0.05. A difference this large would almost never arise by chance. The confidence interval says that Rampur's rate is higher by somewhere between 3.7 and 10 percentage points.\n\n## Comparing many groups at once {#sec-tests-chisq}\n\nRampur caught our eye because we looked at the table first. A fairer way is to test all six offices together, without picking one in advance. The *chi-square test of independence* checks whether two categorical variables, here office and approval, are related. If approval did not depend on the office, every office would approve about the same share.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napproval_table <- table(claims$office, claims$approved)\napproval_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          \n           FALSE TRUE\n  Amarpur     92  495\n  Belapur     82  445\n  Chandpur    83  440\n  Devgarh     80  405\n  Fatehpur    64  381\n  Rampur      38  395\n```\n\n\n:::\n\n```{.r .cell-code}\noffice_test <- chisq.test(approval_table)\noffice_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  approval_table\nX-squared = 14.77, df = 5, p-value = 0.01139\n```\n\n\n:::\n:::\n\n\nThe p-value of 0.011 is below 0.05, so approval rates do differ between offices. But the test does not say *which* office is different. For that, look at the *standardised residuals*. Each says how far an office's count is from what we would expect if all offices were alike, in units of standard deviation. Values beyond about 2 (or below -2) deserve attention.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(office_test$stdres, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          \n           FALSE  TRUE\n  Amarpur   0.79 -0.79\n  Belapur   0.66 -0.66\n  Chandpur  0.88 -0.88\n  Devgarh   1.27 -1.27\n  Fatehpur -0.16  0.16\n  Rampur   -3.73  3.73\n```\n\n\n:::\n:::\n\n\nOnly Rampur stands out, with 3.7 standard deviations more approvals than expected. Every other office is within 2.\n\n::: callout-tip\n## Audit tip\n\nThe chi-square test with its residuals is one of the most useful tests in audit. It works on any cross-table of counts: rejections by inspector, tenders won by bidder and department, cases disposed of by officer and type, or exceptions by branch. The residuals point straight at the cells which are out of line.\n:::\n\nThe chi-square test needs enough data in every cell. If any *expected* count, `office_test$expected`, is below 5, R gives a warning that the result may be inaccurate. Then use `fisher.test()`, which is exact, or combine small groups.\n\n## Drilling down, and the problem of many tests {#sec-tests-multiple}\n\nRampur has two dealing officers. Is the high approval rate the office's, or one officer's? A natural step is to test every officer against the rest. But with many tests, a new problem appears.\n\n**Many tests mean some false alarms.** Each test at the 5% level has a 5% chance of a false alarm. Run 20 tests where nothing is unusual, and on average one will come out \"significant\" anyway. Let us see this with 40 imaginary offices which all approve at exactly the same true rate of 86%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\np_values <- map_dbl(1:40, \\(i) {\n  approved_here <- rbinom(1, size = 300, prob = 0.86)    # this office, 300 claims\n  approved_rest <- rbinom(1, size = 12000, prob = 0.86)  # all the others\n  prop.test(c(approved_here, approved_rest), c(300, 12000))$p.value\n})\nsum(p_values < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n2 of the 40 identical offices look \"significantly\" different, purely by chance. Reporting them would be unfair to their staff. The remedy is to *adjust* the p-values for the number of tests. `p.adjust()` does this. The Holm method is a safe general choice.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(p.adjust(p_values, method = \"holm\") < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nAfter adjustment, no false alarms remain. Now the real drill-down. We test each of the 12 officers against all the others, collect the results with `broom::tidy()`, and adjust.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nofficer_tests <- map(sort(unique(claims$officer)), \\(o) {\n  mine <- claims$officer == o\n  prop.test(x = c(sum(claims$approved[mine]), sum(claims$approved[!mine])),\n            n = c(sum(mine), sum(!mine))) |>\n    tidy() |>\n    mutate(officer = o, claims = sum(mine), .before = 1)\n}) |>\n  list_rbind() |>\n  mutate(p_adjusted = p.adjust(p.value, method = \"holm\")) |>\n  select(officer, claims, own_rate = estimate1, rest_rate = estimate2, p.value, p_adjusted) |>\n  arrange(p.value)\n\nofficer_tests |> mutate(across(c(own_rate, rest_rate), \\(x) round(x, 3)),\n                        across(c(p.value, p_adjusted), \\(x) signif(x, 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 6\n   officer claims own_rate rest_rate   p.value p_adjusted\n   <chr>    <int>    <dbl>     <dbl>     <dbl>      <dbl>\n 1 RAM-2      216    0.963     0.845 0.0000039   0.000047\n 2 DEV-1      243    0.819     0.857 0.13        1       \n 3 AMA-2      277    0.83      0.856 0.29        1       \n 4 BEL-2      281    0.833     0.856 0.34        1       \n 5 FAT-1      240    0.871     0.852 0.49        1       \n 6 CHA-1      261    0.839     0.855 0.54        1       \n 7 FAT-2      205    0.839     0.855 0.61        1       \n 8 CHA-2      262    0.844     0.855 0.69        1       \n 9 RAM-1      217    0.862     0.853 0.8         1       \n10 BEL-1      246    0.858     0.853 0.93        1       \n11 DEV-2      242    0.851     0.854 0.99        1       \n12 AMA-1      310    0.855     0.854 1           1       \n```\n\n\n:::\n:::\n\n\n\n\nThe picture is clear. Officer RAM-2 approved 96.3% of claims, and stays significant even after adjustment (adjusted p-value less than 0.0001). The other Rampur officer, RAM-1, approved 86.2%, in line with the department. So the office's high rate comes from one desk. That is where the audit should look, at a sample of the claims RAM-2 approved, to see whether the checks were actually done.\n\n::: callout-tip\n## Audit tip\n\n`broom::tidy()` turns the output of almost any test into a one-row table. Together with `map()` and `list_rbind()`, it lets us run the same test over every officer, vendor or district, and get one table to sort, filter and attach to working papers. Always add a column of adjusted p-values when you do this.\n:::\n\n## Comparing averages {#sec-tests-t}\n\nRates are about counts. Many audit questions are about amounts and times instead. Is Chandpur slower to settle claims than the other offices? The *t-test* compares the means of two groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclaims |>\n  summarise(mean_days = round(mean(days_to_settle), 1),\n            median_days = median(days_to_settle), .by = office)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  office   mean_days median_days\n  <chr>        <dbl>       <dbl>\n1 Devgarh       21.8          20\n2 Rampur        21.4          20\n3 Belapur       20.3          19\n4 Chandpur      27            25\n5 Fatehpur      21.3          19\n6 Amarpur       21.4          20\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchandpur_test <- t.test(days_to_settle ~ (office == \"Chandpur\"), data = claims)\nchandpur_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  days_to_settle by office == \"Chandpur\"\nt = -9.1182, df = 652.93, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0\n95 percent confidence interval:\n -7.057826 -4.556638\nsample estimates:\nmean in group FALSE  mean in group TRUE \n           21.22527            27.03250 \n```\n\n\n:::\n:::\n\n\n\n\nChandpur takes 27 days on average, against 21.2 days elsewhere, and the p-value is extremely small. The difference is real, not chance. R uses *Welch's* t-test by default, which does not assume that the two groups vary equally. Keep this default.\n\nThe formula `days_to_settle ~ (office == \"Chandpur\")` reads \"days to settle, by whether the office is Chandpur\". The group `FALSE` (the other offices) comes first in the output.\n\n## When amounts are skewed {#sec-tests-wilcox}\n\nThe t-test compares *means*. Money amounts are usually skewed, with many small values and a few very large ones, as we saw in @sec-descriptive. A handful of large claims can pull a mean up or down, and make the t-test unreliable. The *Wilcoxon rank-sum test* (also called the Mann-Whitney test) avoids this. It ranks all the values together, and asks whether one group's values tend to rank higher than the other's. A single huge claim is then just \"the highest rank\", whatever its size.\n\nAre the claims handled by officer DEV-2 larger than everyone else's?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclaims |>\n  mutate(group = if_else(officer == \"DEV-2\", \"DEV-2\", \"Others\")) |>\n  summarise(claims = n(), mean_amount = round(mean(amount)),\n            median_amount = median(amount), .by = group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  group  claims mean_amount median_amount\n  <chr>   <int>       <dbl>         <dbl>\n1 DEV-2     242       36081         26020\n2 Others   2758       24549         17980\n```\n\n\n:::\n\n```{.r .cell-code}\ndev2_test <- wilcox.test(amount ~ (officer == \"DEV-2\"), data = claims)\ndev2_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  amount by officer == \"DEV-2\"\nW = 234586, p-value = 1.68e-14\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n\nThe p-value is less than 0.0001, so DEV-2's claims are systematically larger. The median tells the same story more plainly than the mean. A follow-up might compare the hospitals, bills and rates in DEV-2's claims with the others.\n\n::: callout-note\nTests like Wilcoxon's, which work on ranks, are called *non-parametric*, because they do not assume the data follow a normal distribution. For audit data, which are rarely normal, they are often the safer choice. When both tests are run and they agree, as they usually do on large data, we can be confident. When they disagree, trust the rank test and look for extreme values.\n:::\n\n## More than two groups {#sec-tests-kruskal}\n\nTo compare settlement times across all six offices at once, rather than one office against the rest, use the *Kruskal-Wallis test*, the rank-based version for several groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(days_to_settle ~ office, data = claims)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  days_to_settle by office\nKruskal-Wallis chi-squared = 86.219, df = 5, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\nIt says the offices differ, but not which ones. To find out, compare every pair with `pairwise.wilcox.test()`, which adjusts the p-values for the many comparisons, just as we learnt above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairwise.wilcox.test(claims$days_to_settle, claims$office, p.adjust.method = \"holm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using Wilcoxon rank sum test with continuity correction \n\ndata:  claims$days_to_settle and claims$office \n\n         Amarpur Belapur Chandpur Devgarh Fatehpur\nBelapur  1.00    -       -        -       -       \nChandpur 4.4e-11 3.0e-15 -        -       -       \nDevgarh  1.00    0.26    1.2e-08  -       -       \nFatehpur 1.00    1.00    1.4e-10  1.00    -       \nRampur   1.00    0.76    4.3e-09  1.00    1.00    \n\nP value adjustment method: holm \n```\n\n\n:::\n:::\n\n\nEvery pair involving Chandpur has a tiny p-value, while the other pairs do not differ. (The classic test for comparing the means of several groups is *analysis of variance*, `aov()`. It is closely related to linear regression, which we meet in @sec-regression.)\n\n## Does the data follow an expected pattern? {#sec-tests-gof}\n\nSometimes we know what pattern the data *should* follow, and want to test whether it does. This is the *chi-square goodness-of-fit test*. The number of claims from each office should be roughly in proportion to its staff strength.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstaff <- c(Amarpur = 400, Belapur = 360, Chandpur = 340,\n           Devgarh = 320, Fatehpur = 300, Rampur = 280)\nobserved <- table(claims$office)[names(staff)]\nrbind(observed = observed, expected = round(sum(observed) * staff / sum(staff)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Amarpur Belapur Chandpur Devgarh Fatehpur Rampur\nobserved     587     527      523     485      445    433\nexpected     600     540      510     480      450    420\n```\n\n\n:::\n\n```{.r .cell-code}\nfit_test <- chisq.test(observed, p = staff / sum(staff))\nfit_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  observed\nX-squared = 1.436, df = 5, p-value = 0.9203\n```\n\n\n:::\n:::\n\n\nThe p-value of 0.92 is large. The claims follow the staff strength well, and there is nothing to report. This, too, is a useful audit result. Not every test should find something, and a clean result lets us move on with confidence.\n\nWe have already used goodness-of-fit tests in this book without calling them that. The Benford chi-square in @sec-chis and the digit tests in @sec-nigrini compare observed counts of digits with the counts expected under a known pattern.\n\n## Are two things related? {#sec-tests-cor}\n\nDo larger claims take longer to settle? `cor.test()` tests whether a correlation is different from zero. For skewed amounts, use Spearman's rank correlation, `method = \"spearman\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_test <- cor.test(claims$amount, claims$days_to_settle, method = \"spearman\", exact = FALSE)\ncor_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  claims$amount and claims$days_to_settle\nS = 4.469e+09, p-value = 0.7061\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n        rho \n0.006888644 \n```\n\n\n:::\n:::\n\n\nThe correlation is 0.007, practically zero, and not significant (p = 0.71). Settlement time does not depend on the claim amount here. If it did, say if large claims were settled much faster than small ones, it would be worth asking why.\n\n## Significant is not the same as important {#sec-tests-effect}\n\nA p-value measures how sure we are that a difference is not chance. It does not measure how *large* or how *important* the difference is. Two points follow, and both matter in audit.\n\n**With very large data, tiny differences become significant.** Two districts, each with two lakh claims, approve 85.0% and 85.4% of them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = c(170000, 170800), n = c(200000, 200000))$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0003741535\n```\n\n\n:::\n:::\n\n\nThe difference is highly significant, but 0.4 percentage points is unlikely to matter to anyone. Always look at the size of the difference, the *effect size*, alongside the p-value. For rates, that is the difference in percentage points, and for amounts, the difference in rupees.\n\n**With small data, even large differences may not be significant.** Two small offices, each with 12 claims, approve 10 and 7 of them, 83% against 58%. With counts this small, `prop.test()` warns that its approximation may be inaccurate, so we use the exact `fisher.test()` on the cross-table of approved and rejected claims.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmall_offices <- matrix(c(10, 2,    # office 1: approved, rejected\n                          7, 5),    # office 2: approved, rejected\n                        nrow = 2, byrow = TRUE)\nsmall_test <- fisher.test(small_offices)\nsmall_test$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3707094\n```\n\n\n:::\n:::\n\n\nA large difference, but far from significant (p = 0.37), because 12 claims are too few to tell. As in @sec-tests-binom, the honest conclusion is \"not proven\", not \"no difference\".\n\n**How much data is enough?** The function `power.prop.test()` answers this before the analysis. How many claims per office do we need to detect a difference between an approval rate of 86% and one of 95%, with an 80% chance of catching it (the *power*)?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower.prop.test(p1 = 0.86, p2 = 0.95, power = 0.80)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample comparison of proportions power calculation \n\n              n = 165.4353\n             p1 = 0.86\n             p2 = 0.95\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\nAbout 166 claims in each group. For smaller differences, many more are needed. `power.t.test()` does the same for comparing means.\n\n## Choosing a test {#sec-tests-choose}\n\n| Question | Data | Test | R function |\n|---------------------------|-------------------|-------------------|-------------------|\n| Is a rate above (or below) a benchmark? | One count out of a total | Binomial test | `binom.test()` |\n| Do two groups have different rates? | Counts and totals of two groups | Test of proportions | `prop.test()` |\n| Do rates differ across several groups? | Cross-table of counts | Chi-square test of independence | `chisq.test()`, or `fisher.test()` for small counts |\n| Do counts follow an expected pattern? | Counts and expected proportions | Chi-square goodness of fit | `chisq.test(x, p = )` |\n| Do two groups have different averages? | Amounts or times, roughly symmetric | Welch t-test | `t.test()` |\n| Do two groups have different typical values? | Skewed amounts | Wilcoxon rank-sum test | `wilcox.test()` |\n| Do several groups differ? | Amounts or times | Kruskal-Wallis test, then pairwise tests | `kruskal.test()`, `pairwise.wilcox.test()` |\n| Are two measures related? | Two numeric columns | Correlation test | `cor.test(method = \"spearman\")` |\n| Many tests at once? | p-values | Adjust for multiple testing | `p.adjust()` |\n| How much data do I need? | Expected rates or means | Power calculation | `power.prop.test()`, `power.t.test()` |\n\n: Choosing a statistical test {#tbl-choose-test}\n\n::: callout-tip\n## Audit tip\n\nDecide the test, and the limit for significance, *before* looking at the results. If we try test after test until one gives a small p-value, the result means nothing, because with enough attempts chance alone will oblige. Write down the question, the test and the limit in the audit plan, just as we fix the sample size in advance.\n:::\n\n## A suggested workflow\n\n1. **State the question in plain words**, such as \"does this officer approve more claims than the others?\", and the null hypothesis it implies.\n2. **Look at the data first.** Summarise by group and plot. A test should confirm what you see, not replace looking.\n3. **Choose the test** from @tbl-choose-test. Prefer rank tests for money amounts, and check that the chi-square test has enough data in each cell.\n4. **Fix the significance limit in advance**, usually 5%.\n5. **When testing many groups, adjust the p-values** with `p.adjust()`.\n6. **Report the size of the difference** with the p-value, in percentage points or rupees.\n7. **Treat a significant result as a lead, not a finding.** Follow it up by examining the actual records, as with RAM-2's approved claims.\n8. **Treat a non-significant result as \"not proven\"**, especially on small samples, and say what the data could and could not show.\n\n::: callout-important\n## Remember\n\n- A test asks one question: is this difference larger than chance would usually produce?\n- The p-value is the chance of seeing a difference at least this large if nothing were unusual. Small means surprising.\n- A false alarm wastes effort and is unfair to the auditee; a miss is audit risk. The significance limit balances the two.\n- Many tests produce false alarms by chance. Adjust the p-values with `p.adjust()`.\n- For skewed amounts, prefer rank-based tests like `wilcox.test()` and `kruskal.test()`.\n- Significant does not mean important, and not significant does not mean no problem.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `binom.test()` | stats | Test a count of events against an expected proportion |\n| `prop.test()` | stats | Compare proportions of two or more groups |\n| `chisq.test()` | stats | Chi-square test of independence for a cross-table, or goodness of fit with `p =`; `$stdres` gives standardised residuals |\n| `fisher.test()` | stats | Exact test for a cross-table with small counts |\n| `t.test()` | stats | Compare the means of two groups (Welch's test by default) |\n| `wilcox.test()` | stats | Compare two groups by ranks, safe for skewed amounts |\n| `kruskal.test()` | stats | Compare several groups by ranks |\n| `pairwise.wilcox.test()` | stats | Compare every pair of groups, with adjusted p-values |\n| `aov()` | stats | Analysis of variance, comparing the means of several groups |\n| `cor.test()` | stats | Test whether a correlation differs from zero |\n| `p.adjust()` | stats | Adjust p-values for multiple testing |\n| `power.prop.test()`, `power.t.test()` | stats | Sample size needed to detect a given difference |\n| `tidy()` | broom | Turn a test result into a one-row table |\n\n: Functions used in this chapter {#tbl-testfunctions}\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}