{
  "hash": "18ab3c116a25cc63827c0865ecf488d3",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n# Dates and Times {#sec-lubridate}\n\n## Base R classes to deal with date and time variables\n\n\n\nThere is hardly any data analysis in which we do not deal with dates and times. In audit, they are everywhere. Dates of bills and payments, periods of contracts, days taken to settle claims, the financial year and its quarters, and transactions on holidays. In this chapter we will learn the base R classes for dates and times, then the package `lubridate`, which makes working with them much easier, and finally some date-based audit tests in @sec-lubri-audit.\n\nTo deal with dates and times, R has four core classes,\n\n-   `Date` To deal with date objects (note: `D` in UPPER case)\n-   `POSIXct` To deal with times\n-   `POSIXlt` To deal with times (for difference between these two refer @sec-timm.)\n-   `difftime` To deal with time-spans\n\n### Dates\n\n`Date` objects can be created from `string/character` type objects (we will just see that date objects can be created from numeric objects too), using base R's function `as.Date()` which accepts a character vector and a format to parse the date from the given string of characters. E.g.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas.Date(\"2000-12-12\") # default format\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2000-12-12\"\n```\n\n\n:::\n\n```{.r .cell-code}\nas.Date(\"12-12-2000\", format = \"%d-%m-%Y\") # custom format\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2000-12-12\"\n```\n\n\n:::\n:::\n\n\nIn the above example, we can see that a custom format has been given to parse the character string into the date type object. We can check the `class` of the object created.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na_date <- as.Date(\"20-12-2022\", format = \"%d-%m-%Y\")\nclass(a_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Date\"\n```\n\n\n:::\n:::\n\n\nThe format used in the above function accepts special codes, which can be seen by running `?strptime` in your R console. A ready reference for most used codes is however, given in @tbl-lubri001 in @sec-strpp. The date objects in R, are actually based on numeric classes which actually store the number of days since an epoch. Check the following code-\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nclass(Sys.Date())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Date\"\n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(Sys.Date())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"double\"\n```\n\n\n:::\n\n```{.r .cell-code}\nunclass(Sys.Date())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20731\n```\n\n\n:::\n:::\n\n\nSo, in R versions 4.3.0 and later, it also accepts a number to convert into a date using the number of days elapsed since epoch. So,\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas.Date(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1970-01-02\"\n```\n\n\n:::\n:::\n\n\nHere date since one day of default origin date 1970-01-01 has been returned.  However, default `origin` can be changed using the argument `origin`.  Example,\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# One day since launch of R version 1.0\nas.Date(1, origin = \"2000-02-29\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2000-03-01\"\n```\n\n\n:::\n:::\n\n\n### Times {#sec-timm}\n\nNow, to create date-time objects we can use either of `POSIXct` and `POSIXlt` classes, i.e. by using `as.POSIXct()` and/or `as.POSIXlt()` functions, as shown below.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas.POSIXct(\"1990/2/17 12:20:05\") # default format\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1990-02-17 12:20:05 IST\"\n```\n\n\n:::\n\n```{.r .cell-code}\nas.POSIXct(\"17-2-1990 15:30:00\", format = \"%d-%m-%Y %H:%M:%S\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1990-02-17 15:30:00 IST\"\n```\n\n\n:::\n\n```{.r .cell-code}\nas.POSIXlt(\"17-2-1990 15:30:00\", format = \"%d-%m-%Y %H:%M:%S\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1990-02-17 15:30:00 IST\"\n```\n\n\n:::\n:::\n\n\nAs regards, the difference between these two classes, `POSIXct` stores *seconds* since UNIX epoch (and other information), and `POSIXlt`, which stores a list of *day*, *month*, *year*, *hour*, *minute*, *second*, etc., which can be understood from the following codes.\n\n> `ct` in `POSIXct` stands for calendar time whereas, `lt` in `POSIXlt` stands for local time, explaining the conceptual difference.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntime_ct <- as.POSIXct(\"17-2-1990 15:30:00\", format = \"%d-%m-%Y %H:%M:%S\")\nclass(time_ct)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"POSIXct\" \"POSIXt\" \n```\n\n\n:::\n\n```{.r .cell-code}\nunclass(time_ct)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 635248800\nattr(,\"tzone\")\n[1] \"\"\n```\n\n\n:::\n\n```{.r .cell-code}\n## POSIXlt\n# Convert above object into POSIXlt type\ntime_lt <- as.POSIXlt(time_ct)\n# Let us print\ntime_lt\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1990-02-17 15:30:00 IST\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(time_lt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"POSIXlt\" \"POSIXt\" \n```\n\n\n:::\n\n```{.r .cell-code}\nunclass(time_lt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$sec\n[1] 0\n\n$min\n[1] 30\n\n$hour\n[1] 15\n\n$mday\n[1] 17\n\n$mon\n[1] 1\n\n$year\n[1] 90\n\n$wday\n[1] 6\n\n$yday\n[1] 47\n\n$isdst\n[1] 0\n\n$zone\n[1] \"IST\"\n\n$gmtoff\n[1] 19800\n\nattr(,\"tzone\")\n[1] \"\"      \"IST\"   \"+0630\"\nattr(,\"balanced\")\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nSimilar to `as.Date()`, `as.POSIXct()` also accepts a number and converts it into a date-time object using that much number of seconds since epoch.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas.POSIXct(60)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1970-01-01 05:31:00 IST\"\n```\n\n\n:::\n:::\n\n\n### Times (without dates)\n\nIn base R, we do not have specific class to deal with time objects. However, there is a package `hms` part of `tidyverse` which can be used to create time objects to perform required calculations.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhms::as_hms(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n00:00:10\n```\n\n\n:::\n:::\n\n\n### Timespan {#sec-diffftime}\nIn base R, besides above date/date-time object classes, there is a special class which creates time difference between two given temporal objects in specified units.  The class is `difftime`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(freedom_age <- Sys.Date() - as.Date(\"1947-08-15\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime difference of 28906 days\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(freedom_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"difftime\"\n```\n\n\n:::\n\n```{.r .cell-code}\nunclass(freedom_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28906\nattr(,\"units\")\n[1] \"days\"\n```\n\n\n:::\n:::\n\nFunction `difftime` can create difftime objects, as per specific requirement due to presence of an argument `units` which can take values from one of `“auto”`, `“secs”`, `“mins”`, `“hours”`, `“days”`, `“weeks”`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndifftime(as.Date(\"2020-02-29\"), as.Date(\"2019-02-28\"), units = \"weeks\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime difference of 52.28571 weeks\n```\n\n\n:::\n:::\n\nWe can also create a difftime object by coercion.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\na_difftime <- as.difftime(15, units = \"days\")\na_difftime\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime difference of 15 days\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(a_difftime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"difftime\"\n```\n\n\n:::\n:::\n\n\n### Time zones\n\nRun the function `Sys.timezone()` in your console to check the current timezone. Function `OlsonNames()` will however, display the known location for time-zones.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nSys.timezone()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Asia/Calcutta\"\n```\n\n\n:::\n\n```{.r .cell-code}\ngrep(\"Kolkata|London\", OlsonNames(), value = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Asia/Kolkata\"  \"Europe/London\"\n```\n\n\n:::\n:::\n\n\nSo, we may use the `tz` argument of `as.POSIXlt()` and `as.POSIXct()` to give the time zone while converting numbers or text into date-times. Indian Standard Time is `\"Asia/Kolkata\"`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas.POSIXct(1, tz = \"GMT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1970-01-01 00:00:01 GMT\"\n```\n\n\n:::\n:::\n\n\n### Coercion\nIn earlier sections we have already seen coercing functions useful to coerce the objects from one class to another.\n\n- `as.Date()`\n- `as.POSIXct()`\n- `as.POSIXlt()`\n- `as.difftime()`\n\n### Extracting parts from dates/times\nBase R provides us some useful function to extract relevant part of objects of dates/times classes.\n\n- `weekdays(x, abbreviate = FALSE)` to extract the weekday name.  (Output is in character vector)\n- `months(x, abbreviate = FALSE)` to extract the month name.  (Output is in character vector)\n- `quarters(x)` to extract the quarter.  Output is in character vector.\n- `julian(x)` to extract the days elapsed since origin.  Output is in numeric vector.\n\nExamples-\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndates_vec <- as.Date(15001 + 1:7)\nweekdays(dates_vec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Friday\"    \"Saturday\"  \"Sunday\"    \"Monday\"    \"Tuesday\"   \"Wednesday\"\n[7] \"Thursday\" \n```\n\n\n:::\n\n```{.r .cell-code}\nmonths(dates_vec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"January\"  \"January\"  \"January\"  \"January\"  \"February\" \"February\" \"February\"\n```\n\n\n:::\n\n```{.r .cell-code}\nquarters(dates_vec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Q1\" \"Q1\" \"Q1\" \"Q1\" \"Q1\" \"Q1\" \"Q1\"\n```\n\n\n:::\n\n```{.r .cell-code}\njulian(dates_vec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15002 15003 15004 15005 15006 15007 15008\nattr(,\"origin\")\n[1] \"1970-01-01\"\n```\n\n\n:::\n:::\n\n\n### Other useful related functions\nThere are certain other useful functions to the related classes which are useful in data analytics.\n\n1. `seq.Date(from, to, by, length.out = NULL, along.with = NULL, ...)` where-\n\n- `from` and `to` are start and end dates respectively\n- `by` is increment of sequence which can accept either of these\n    + a number to be taken in days,\n    + an object of class `difftime`\n    + a character string, containing one of \"day\", \"week\", \"month\", \"quarter\" or \"year\". This can optionally be preceded by a (positive or negative) integer and a space, or followed by \"s\".\n- `length.out` is optional argument accepting an integer, for desired length of the sequence.\n- `along.with` take the length from the length of this argument.\n\nExample-\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nseq(as.Date(\"2000/1/1\"), by = \"month\", length.out = 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"2000-01-01\" \"2000-02-01\" \"2000-03-01\" \"2000-04-01\" \"2000-05-01\"\n [6] \"2000-06-01\" \"2000-07-01\" \"2000-08-01\" \"2000-09-01\" \"2000-10-01\"\n[11] \"2000-11-01\" \"2000-12-01\"\n```\n\n\n:::\n:::\n\n\n\n### `strptime` character codes {#sec-strpp}\n\nA few format codes useful to parse date/date-time objects in R, are listed below for ready reference.  To know more about these codes, readers can see the output of `?strptime()` in their console.  Some useful codes have been reproduced in the @tbl-lubri001 for ready reference.\n\n\n|     Format     | Meaning                                                                                                                                                                                                                                                                          |\n|:------------------:|----------------------------------------------------|\n| `%y` (or `%Y`) | Year without (or with) Century                                                                                                                                                                                                                                                   |\n|      `%m`      | Month as decimal number (01-12)                                                                                                                                                                                                                                                  |\n| `%B` (or `%b`) | Month name in full (or abbreviated) in current locale                                                                                                                                                                                                                            |\n|      `%d`      | Day of the month (01-31)                                                                                                                                                                                                                                                         |\n|      `%H`      | Hours as decimal number (00-23)                                                                                                                                                                                                                                                  |\n|      `%I`      | Hours as decimal number, in 12 hour format (01-12)                                                                                                                                                                                                                               |\n|      `%M`      | Minute as decimal number (00-59)                                                                                                                                                                                                                                                 |\n|      `%S`      | Second as integer (00-61) allowing up to two leap-seconds                                                                                                                                                                                                                         |\n|     `%OS`      | Second(s) as decimal number                                                                                                                                                                                                                                                      |\n|      `%T`      | Equivalent to `%H:%M:%S`                                                                                                                                                                                                                                                         |\n|      `%p`      | AM/PM indicator in the locale.                                                                                                                                                                                                                                                   |\n| `%A` (or `%a`) | Full (or abbreviated) week-day name, in current locale                                                                                                                                                                                                                               |\n|      `%j`      | Day of year as decimal number (001--366): For input, 366 is only valid in a leap year.                                                                                                                                                                                           |\n|      `%u`      | Weekday as a decimal number (1--7, Monday is 1)                                                                                                                                                                                                                                  |\n|      `%w`      | Weekday as decimal number (0--6, Sunday is 0).                                                                                                                                                                                                                                   |\n|      `%U`      | Week of the year as decimal number (00--53) using Sunday as the first day 1 of the week (and typically with the first Sunday of the year as day 1 of week 1). **The US convention.**                                                                                             |\n|      `%V`      | Week of the year as decimal number (01--53) as defined in ISO 8601. If the week (starting on Monday) containing 1 January has four or more days in the new year, then it is considered week 1. Otherwise, it is the last week of the previous year, and the next week is week 1. |\n|      `%W`      | Week of the year as decimal number (00--53) using Monday as the first day of week (and typically with the first Monday of the year as day 1 of week 1). **The UK convention**.                                                                                                   |\n|      `%z`      | Offset from UTC                                                                                                                                                                                                                                                                  |\n|      `%Z`      | Time Zone name                                                                                                                                                                                                                                                                   |\n\n: Conversion Specifications for Date/Date-time {#tbl-lubri001}\n\n## Using `lubridate` package for parsing/creating dates\nPackage `lubridate` which is now part of core `tidyverse` is extremely helpful package while analysing temporal variables in data.  Creating date/date-time objects and converting variables from numeric/character to these types is easier than in base R.  Besides, it offers us some other temporal class objects to make our time-series analysis easier.\n\n### Date/date-time objects creation\nDate and Date-time object classes in `lubridate` are defined similarly as in base R.  So we can create a date (or date-time) using a number of days (or seconds) elapsed since epoch.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lubridate, warn.conflicts = FALSE)\n# Creation using numbers\nas_date(2392)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1976-07-20\"\n```\n\n\n:::\n\n```{.r .cell-code}\nas_datetime(206668800)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1976-07-20 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Converting from one type to another\n(date_today <- as_date(now()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2026-10-05\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check its class\nclass(date_today)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Date\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Or see what's all in there\nunclass(date_today)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20731\n```\n\n\n:::\n:::\n\n\n### Parsing date/date-time objects  from `character`\nIn `lubridate` parsing date/date-time objects from character strings is pretty easy as we have a number of functions useful to parse dates/date-times written in any specific locale/order irrespective of the delimiter used to separate different components of date/time therein. In these functions, the orders of the year (`y`), quarter (`q`), month (`m`) date (`d`) hour (`h`) minute (`m`) and second (`s`) are represented by their first characters.  These are -\n\n- `ymd_hms`, `ymd_hm`, `ymd_h`, `ymd`\n- `dmy_hms`, `dmy_hm`, `dmy_h`, `dmy`\n- `mdy_hms`, `mdy_hm`, `mdy_h`, `mdy`\n- `ydm_hms`, `ydm_hm`, `ydm_h`, `ydm`\n- `myd`, `dym`\n- `yq`, `ym`, `my`\n\nA few of the examples are -\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nymd(\"19760720\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1976-07-20\"\n```\n\n\n:::\n\n```{.r .cell-code}\ndmy(\"01.12.2004\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2004-12-01\"\n```\n\n\n:::\n\n```{.r .cell-code}\ndmy(\"15th of January, 2006\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2006-01-15\"\n```\n\n\n:::\n\n```{.r .cell-code}\nmdy_hm(\"August 15th, 1947 at 10:45 PM\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1947-08-15 22:45:00 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nmy(\"04-2006\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2006-04-01\"\n```\n\n\n:::\n\n```{.r .cell-code}\nyq(\"2024: Quarter 4\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2024-10-01\"\n```\n\n\n:::\n:::\n\nTo parse date-time from a fraction of year passed, we can use `date_decimal()`. Example-\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndate_decimal(2024.162)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2024-02-29 07:00:28 UTC\"\n```\n\n\n:::\n:::\n\n\n### Parsing dates/date-times from individual components\nFor the scenario, where we have to create date/date-times we can make use of two functions `make_date` and `make_datetime`.  Syntax is\n\n```\nmake_datetime(\n  year = 1970L,\n  month = 1L,\n  day = 1L,\n  hour = 0L,\n  min = 0L,\n  sec = 0,\n  tz = \"UTC\"\n)\n\nmake_date(year = 1970L, month = 1L, day = 1L)\n```\n\nExample-\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmake_date(year = 1947, month = 8, day = 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1947-08-15\"\n```\n\n\n:::\n:::\n\n\n## Extracting and setting date/date-time components\n\n### Extraction\nWe can extract the specific components from date/date-times using, intuitively named accessor functions, which are listed below.  Note that in all of these functions the individual date components is in singular; as plural component functions will be used in different context, as we will discuss in @sec-perriod.\n\n- `year()` for Year; `isoyear()` for ISO 8601 Year\n- `semester()` for Semester\n- `quarter()` for Quarter\n- `month()` for Month\n- `week` for Week of the year, `isoweek()` for ISO 8601 Week\n- `day` for Day of the month, `wday()` for Day of the week, `qday()` for Day of the quarter\n- `hour()`, `minute()` and `second()` for Hour, Minute and Second respectively\n- `tz()` for Time Zone\n\nSee following examples.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Make an example date\n(a_time <- as_datetime(999999999))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2001-09-09 01:46:39 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract the DAY of the month\nday(a_time)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract Weekday name in full\nwday(a_time, label = TRUE, abbr = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Sunday\n7 Levels: Sunday < Monday < Tuesday < Wednesday < Thursday < ... < Saturday\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract second component\nsecond(a_time)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 39\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract Month name (abbreviated)\nmonth(a_time, label = TRUE, abbr = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Sep\n12 Levels: Jan < Feb < Mar < Apr < May < Jun < Jul < Aug < Sep < ... < Dec\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract week number of the year\nweek(a_time)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 36\n```\n\n\n:::\n:::\n\nBesides above functions, there are a few functions which are helpful in knowing certain characteristics of date/date-time variable.  These functions, which return logical vectors, are\n\n- `am(x)`, `pm(x)` to know whether the `x` is in AM or PM, respectively.\n- `dst(x)` to know whether `x` is in Daylight savings.\n- `leap_year(x)` to know whether `x` is a leap year.\n\nExamples-\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Is our a_time AM?\nam(a_time)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\n# Is a_time falling in leap year?\nleap_year(a_time)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\n# Is it during DST?\ndst(a_time)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n### Setting Components\nJust like we used accessor functions to extract the date-time components, we can use those functions to set specific component in date/date-time object/variable.  See Example-\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Initial variable\na_time\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2001-09-09 01:46:39 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Setting component - Year\nyear(a_time) <- 2024\n# Print modified variable\na_time\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2024-09-09 01:46:39 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Modify Time zone\ntz(a_time) <- \"Asia/Kolkata\"\n# print modified variable\na_time\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2024-09-09 01:46:39 IST\"\n```\n\n\n:::\n:::\n\nFinally, function `update` can also be used to return a date with the specified elements updated.  Example-\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nEOD <- dmy(\"31-01-2024\")\nEOD <- update(EOD, year = 2020)\nEOD\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2020-01-31\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# If values are too big, they will roll-over:\nupdate(EOD, month = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2020-03-02\"\n```\n\n\n:::\n:::\n\n\n## Time spans\n\nWhen we subtract a date-time object from another in base R, we get a `difftime` object, as we have already seen in @sec-diffftime.\n\nWe know that every time/date unit is not same in strict sense.  Like leap years may have 366 days whereas others have 365 days.  Now there is a concept of leap seconds too.  Moreover, certain countries have daylight saving time and thus, every day is not of equal length there.  In order to deal with specific and clear requirements on date calculations, there are three different classes in `lubridate`, as discussed next.\n\nLubridate has three classes, which may sound similar at first, but are different in their working.  These are -\n\n- `period`\n- `duration`\n- `interval`\n\nLet us discuss about each one separately.\n\n### Periods {#sec-perriod}\nThe `period` objects track changes in clock times and ignore time line irregularities.  So every time object is of standard length like our clocks.\n\nPeriod objects can be created in `lubridate` using **pluralized** date component functions.  Example-\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(one_year <- years(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"1y 0m 0d 0H 0M 0S\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(one_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Period\"\nattr(,\"package\")\n[1] \"lubridate\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Add one year PERIOD to get a leap year?\na_date <- dmy(\"01-03-2019\")\na_date + years(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2020-03-01\"\n```\n\n\n:::\n:::\n\n\n### Durations\nDurations, on the other hand track changes in physical time, i.e. taking into account all the timeline adjusting irregularities.  These duration objects can be created in lubridate, by adding `d` as prefix to all pluralized `period` objects.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(one_year_duration <- dyears(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"31557600s (~1 years)\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(one_year_duration)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Duration\"\nattr(,\"package\")\n[1] \"lubridate\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Add one year DURATION to get a leap year date?\na_date + dyears(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2020-02-29 06:00:00 UTC\"\n```\n\n\n:::\n:::\n\n\n### Intervals\nThe objects of class `interval` represent **specific** interval on the timeline.  In other words, these have a specific start and end date/datetimes.  These can be created in lubridate using function `interval`, which has syntax like -\n\n```\ninterval(start = NULL, end = NULL, tzone = tz(start))\n```\nThis should be clear with the following examples.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(a_interval <- interval(dmy(\"15-08-1947\"), today()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1947-08-15 UTC--2026-10-05 UTC\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(a_interval)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Interval\"\nattr(,\"package\")\n[1] \"lubridate\"\n```\n\n\n:::\n:::\n\n\nIntervals can also be created using special operator `%--%`. E.g.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(interval1 <- dmy(\"15-08-1947\") %--% dmy(\"26-01-1950\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1947-08-15 UTC--1950-01-26 UTC\n```\n\n\n:::\n:::\n\n\n## Performing calculations on intervals/dates\nThere are a few functions to make our life easier while performing data analysis on temporal fields.  These are -\n\n### `%within%` operator\nOperator `a %within% b` checks whether interval/date-time `a` falls with interval `b`.  Returns boolean value(s).\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninterval1 %within% a_interval\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n### Backward intervals\nIntervals in lubridate can be backwards too.  E.g.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(back_interval <- dmy(\"26-01-2024\") %--% dmy(\"15-01-2024\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2024-01-26 UTC--2024-01-15 UTC\n```\n\n\n:::\n:::\n\n\n### Flipping intervals\nFunction `int_flip()` can flip the interval.  E.g.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nint_flip(back_interval)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2024-01-15 UTC--2024-01-26 UTC\n```\n\n\n:::\n:::\n\n\n### Checking alignment of two intervals\nFunction `int_aligns` tests if two intervals share an endpoint. The direction of each interval is ignored.  In other words, it actually tests whether the earliest or latest moments of each interval occur at the same time.  E.g.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nint1 <- interval(ymd(\"2001-01-01\"), ymd(\"2002-01-01\"))\nint2 <- interval(ymd(\"2001-06-01\"), ymd(\"2002-01-01\"))\nint3 <- interval(ymd(\"2003-01-01\"), ymd(\"2004-01-01\"))\n\nint_aligns(int1, int2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nint_aligns(int1, int3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n### Checking Overlap in two intervals\nFunction `int_overlaps` can test if two intervals overlap each other.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nint_overlaps(int1, int2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n### Length of the interval\nFunction `int_length()` can calculate the length of interval and returns a `numeric` variable equal to the seconds in that interval.  E.g.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nint_length(back_interval)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -950400\n```\n\n\n:::\n:::\n\n\n### Adding Months without exceeding last day of the month.\nOperators `%m+%` and `%m-%` will add (or subtract) months to a date without exceeding the last day of the new month.  E.g.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(leap <- ymd(\"2012-02-29\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2012-02-29\"\n```\n\n\n:::\n\n```{.r .cell-code}\nleap %m+% years(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2013-02-28\"\n```\n\n\n:::\n\n```{.r .cell-code}\nleap %m+% years(-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2011-02-28\"\n```\n\n\n:::\n\n```{.r .cell-code}\nleap %m-% years(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2011-02-28\"\n```\n\n\n:::\n:::\n\nAnother Example-\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\njan <- ymd_hms(\"2010-01-31 03:04:05\")\njan + months(1:3) # Feb 31 and April 31 returned as NA\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA                        \"2010-03-31 03:04:05 UTC\"\n[3] NA                       \n```\n\n\n:::\n\n```{.r .cell-code}\n# NA \"2010-03-31 03:04:05 UTC\" NA\njan %m+% months(1:3) # No rollover\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2010-02-28 03:04:05 UTC\" \"2010-03-31 03:04:05 UTC\"\n[3] \"2010-04-30 03:04:05 UTC\"\n```\n\n\n:::\n:::\n\n\n### Adding with Rollback\nOne more function `add_with_rollback()` which performs similarly, but has more control due to specific syntax-\n\n```\nadd_with_rollback(e1, e2, roll_to_first = FALSE, preserve_hms = TRUE)\n```\nExample-\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- ymd_hms(\"2019-01-29 01:02:03\")\nadd_with_rollback(x, months(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2019-02-28 01:02:03 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nadd_with_rollback(x, months(1), preserve_hms = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2019-02-28 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nadd_with_rollback(x, months(1), roll_to_first = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2019-03-01 01:02:03 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nadd_with_rollback(x, months(1), roll_to_first = TRUE, preserve_hms = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2019-03-01 UTC\"\n```\n\n\n:::\n:::\n\n\n### Coercing one time span unit to another\n\nTime-span objects in lubridate can be coerced from one to another using coercing functions,\n\n- `as.period(x, unit)`\n- `as.duration(x)`\n- `as.interval(x, start)`\n- `make_difftime(x)`\n\nExamples-\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# With Period - clock time\n(per <- days(31))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"31d 0H 0M 0S\"\n```\n\n\n:::\n\n```{.r .cell-code}\n(int1 <- as.interval(per, dmy(\"01022020\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2020-02-01 UTC--2020-03-03 UTC\n```\n\n\n:::\n\n```{.r .cell-code}\n# With Duration - physical time\n(dur <- ddays(31))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2678400s (~4.43 weeks)\"\n```\n\n\n:::\n\n```{.r .cell-code}\n(int2 <- as.interval(dur, dmy(\"01022020\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2020-02-01 UTC--2020-03-03 UTC\n```\n\n\n:::\n:::\n\n\n## Rounding date-time variables\nThere are dedicated functions to round the dates as per specific requirements.\n\n- `floor_date()` takes a date-time object and rounds it down to the nearest boundary of the specified time unit.\n- `ceiling_date()` takes a date-time object and rounds it up to the nearest boundary of the specified time unit.\n- `round_date()` takes a date-time object and time unit, and rounds it to the nearest value of the specified time unit.\n\nExamples-\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- ymd_hms(\"2009-08-03 12:01:59.23\")\nround_date(x, \"month\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2009-08-01 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nround_date(x, \"week\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2009-08-02 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nfloor_date(x, \"day\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2009-08-03 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nceiling_date(x, \"month\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2009-09-01 UTC\"\n```\n\n\n:::\n:::\n\nThree other functions helps rolling a date forward or backwards, as\n\n- `rollbackward()` changes a date to the last day of the previous month or to the first day of the month.\n- `rollforward()` rolls to the last day of the current month or to the first day of the next month. Optionally, the new date can retain the same hour, minute, and second information.\n- `rollback()` is a synonym for `rollbackward()`.\n\nSee these examples-\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndate <- ymd_hms(\"2010-03-03 12:44:22\")\n\nrollbackward(date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2010-02-28 12:44:22 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nrollbackward(date, roll_to_first = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2010-03-01 12:44:22 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nrollbackward(date, preserve_hms = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2010-02-28 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nrollbackward(date, roll_to_first = TRUE, preserve_hms = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2010-03-01 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nrollforward(date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2010-03-31 12:44:22 UTC\"\n```\n\n\n:::\n\n```{.r .cell-code}\nrollforward(date, roll_to_first = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2010-04-01 12:44:22 UTC\"\n```\n\n\n:::\n:::\n\n## Representing date and date-times in customised formats\nIn all of the above sections, we saw that once R recognises a temporal object, it depicts that objects in a uniform format.  See\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(date1 <- dmy(\"01-01-2020\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2020-01-01\"\n```\n\n\n:::\n\n```{.r .cell-code}\n(date2 <- ymd(\"2020/01/01\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2020-01-01\"\n```\n\n\n:::\n\n```{.r .cell-code}\nas.character(date1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2020-01-01\"\n```\n\n\n:::\n:::\n\nIn the console, all dates print in the same `yyyy-mm-dd` form. Reports, however, often need another format, like `15 August 2024` or `15/08/2024`. The functions `format()` and `strftime()` convert dates and date-times into text in any format we specify.  Character codes can be used from the @tbl-lubri001 in @sec-strpp.\n\nSee following examples-\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nformat(as.Date(\"2024-08-15\"), \"%d %B %Y\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"15 August 2024\"\n```\n\n\n:::\n\n```{.r .cell-code}\nformat(as.Date(\"2024-08-15\"), \"%d/%m/%Y\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"15/08/2024\"\n```\n\n\n:::\n:::\n\n\nIn this context, let's also discuss about a special date stamping function in `lubridate` which can format date/time outputs based on human friendly formats. Functions `stamp()`, `stamp_date` and `stamp_time()` will create a function from the given template, which can be applied to date/time objects to re-format them.  Example-\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\neclipse_dates <- dmy(c(\"11-7-2010\", \"13-11-2012\", \"3-11-2013\"))\neclipse_stamp <- stamp_date(\"There was a solar eclipse on January 13th, 1999\")\neclipse_stamp(eclipse_dates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"There was a solar eclipse on July 11th, 2010\"    \n[2] \"There was a solar eclipse on November 13th, 2012\"\n[3] \"There was a solar eclipse on November 03th, 2013\"\n```\n\n\n:::\n:::\n\n\n## Dates in GGPLOT2 visualisations\nBefore concluding the chapter on date and time variables, it is important to learn the related functions to deal with impact of date and time formats on visualisations.  Since we have already seen that, date and date-time variables are actually continuous variables with labels depicted in a specific formats, we have two `scale` functions in ggplot2 to deal with -\n\n- `scale_x_date()`\n- `scale_x_datetime()`\n\nIn these functions, we have `date_breaks` and `date_minor_breaks` arguments to position the breaks by date units. E.g. `date_breaks = \"6 months\"` will place major tick mark every six months.\n\nUsing another argument `date_labels` we can control the display of the labels in the plots.  The values of the argument may be in `strptime` formats as we have already seen in @tbl-lubri001 above.\n\nExample-\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse, warn.conflicts = FALSE)\n\neconomics |>\n  ggplot(aes(date, uempmed)) +\n  geom_line() +\n  scale_x_date(date_labels = \"%Y\",\n               date_breaks = \"5 years\",\n               date_minor_breaks = \"1 year\") +\n  labs(x = \"\", y = \"\")\n```\n\n::: {.cell-output-display}\n![Use of Date Time Scale in ggplot2](12-8Lubridate_files/figure-html/unnamed-chunk-44-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Date-based audit tests {#sec-lubri-audit}\n\nLet us now apply these functions to three tests which auditors use all the time. We take a register of bills received by an office, with the date each bill was received and the date it was paid. Bills not yet paid have no payment date.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the bill register\"}\nset.seed(1947)\nn <- 400\nbill_register <- tibble(\n  bill_no  = sprintf(\"BL-%04d\", 1:n),\n  received = as.Date(\"2023-04-01\") + sample(0:700, n, TRUE),\n  amount   = round(rlnorm(n, log(60000), 0.9))\n) |>\n  mutate(paid = received + round(rexp(n, 1 / 20)))\n\n# Genuine payments are made on working days. Move Sundays and holidays forward.\nholidays <- as.Date(c(\"2024-01-26\", \"2024-08-15\", \"2024-10-02\",\n                      \"2025-01-26\", \"2025-08-15\", \"2025-10-02\"))\nfor (k in 1:2) {\n  off <- wday(bill_register$paid, week_start = 1) == 7 | bill_register$paid %in% holidays\n  bill_register$paid[off] <- bill_register$paid[off] + 1\n}\n\n# Some bills are still unpaid on 31 March 2025\nunpaid <- sample(1:n, 45)\nbill_register$paid[unpaid] <- NA\n# Payments dated after 31 March 2025 have not happened yet\nbill_register$paid[which(bill_register$paid > as.Date(\"2025-03-31\"))] <- NA\n# Planted. A few payments made on Sundays and on Independence Day\nbill_register$paid[c(12, 57, 133, 260)] <- as.Date(c(\"2024-06-09\", \"2024-08-15\",\n                                                      \"2024-11-17\", \"2025-01-26\"))\n```\n:::\n\n\n### Financial year and its quarters\n\nThe Indian financial year runs from April to March. `lubridate`'s `quarter()` has an argument `fiscal_start`, the month in which the year starts. With `fiscal_start = 4`, April to June is the first quarter. The financial year can be labelled like `2024-25` with a little arithmetic.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfin_year <- function(date) {\n  start <- if_else(month(date) >= 4, year(date), year(date) - 1)\n  paste0(start, \"-\", sprintf(\"%02d\", (start + 1) %% 100))\n}\n\ntibble(date = as.Date(c(\"2024-03-31\", \"2024-04-01\", \"2025-01-15\"))) |>\n  mutate(financial_year = fin_year(date),\n         fy_quarter     = quarter(date, fiscal_start = 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  date       financial_year fy_quarter\n  <date>     <chr>               <int>\n1 2024-03-31 2023-24                 4\n2 2024-04-01 2024-25                 1\n3 2025-01-15 2024-25                 4\n```\n\n\n:::\n:::\n\n\nNow we can summarise the bills by financial year and quarter.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbill_register |>\n  filter(!is.na(paid)) |>\n  mutate(fy = fin_year(paid), qtr = quarter(paid, fiscal_start = 4)) |>\n  summarise(bills = n(), amount_lakh = round(sum(amount) / 1e5, 1), .by = c(fy, qtr)) |>\n  arrange(fy, qtr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 4\n  fy        qtr bills amount_lakh\n  <chr>   <int> <int>       <dbl>\n1 2023-24     1    38        35.1\n2 2023-24     2    56        43.2\n3 2023-24     3    32        23.4\n4 2023-24     4    45        36.7\n5 2024-25     1    49        42.2\n6 2024-25     2    48        40.7\n7 2024-25     3    43        50.6\n8 2024-25     4    40        33  \n```\n\n\n:::\n:::\n\n\n### Payments on Sundays and holidays\n\nGovernment offices are closed on Sundays and gazetted holidays. A payment dated on such a day is unusual. It may be a back-dated entry, or a payment made without the usual checks. `wday()` gives the day of the week, and a list of holidays can be checked with `%in%`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# holidays is a vector of gazetted holidays, created along with the data\nbill_register |>\n  filter(!is.na(paid)) |>\n  mutate(day = wday(paid, label = TRUE, abbr = FALSE)) |>\n  filter(day == \"Sunday\" | paid %in% holidays) |>\n  select(bill_no, paid, day, amount)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  bill_no paid       day      amount\n  <chr>   <date>     <ord>     <dbl>\n1 BL-0012 2024-06-09 Sunday    43960\n2 BL-0057 2024-08-15 Thursday  16388\n3 BL-0133 2024-11-17 Sunday    42375\n4 BL-0260 2025-01-26 Sunday   160164\n```\n\n\n:::\n:::\n\n\nThe four planted payments are found. Three were made on Sundays, one of which was also Republic Day, and one on Independence Day, which was a Thursday. A check on Sundays alone would have missed it.\n\n### Ageing analysis\n\n*Ageing* sorts pending items by how long they have been pending. It is one of the most common audit analyses, for pending bills, outstanding advances, unadjusted suspense entries, or grievances not disposed of. Let us age the unpaid bills as on 31 March 2025.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nas_on <- as.Date(\"2025-03-31\")\n\nageing <- bill_register |>\n  filter(is.na(paid)) |>\n  mutate(days_pending = as.numeric(as_on - received),\n         age_group = cut(days_pending,\n                         breaks = c(-Inf, 30, 90, 180, 365, Inf),\n                         labels = c(\"Up to 30 days\", \"31-90 days\", \"91-180 days\",\n                                    \"181-365 days\", \"Over a year\")))\n\nageing |>\n  summarise(bills = n(), amount_lakh = round(sum(amount) / 1e5, 2), .by = age_group) |>\n  arrange(age_group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  age_group     bills amount_lakh\n  <fct>         <int>       <dbl>\n1 Up to 30 days     1        0.28\n2 31-90 days        7        3.93\n3 91-180 days       4        1.4 \n4 181-365 days      8       10.4 \n5 Over a year      29       23.4 \n```\n\n\n:::\n:::\n\n\n`cut()` sorts the days into age groups, and gives an ordered factor, so the groups print in a sensible order. Bills pending for more than a year deserve particular attention. They may be for supplies never received, duplicates, or genuine dues which are being delayed.\n\n**Time taken to pay.** The same arithmetic, on paid bills, measures how long the office takes to pay.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbill_register |>\n  filter(!is.na(paid)) |>\n  mutate(days_to_pay = as.numeric(paid - received)) |>\n  summarise(bills = n(),\n            median_days = median(days_to_pay),\n            within_30_days_pct = round(100 * mean(days_to_pay <= 30), 1),\n            paid_before_received = sum(days_to_pay < 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  bills median_days within_30_days_pct paid_before_received\n  <int>       <dbl>              <dbl>                <int>\n1   351          13               79.8                    1\n```\n\n\n:::\n:::\n\n\nThe last column is a basic validity test. A bill cannot be paid before it is received. Any such case is either a data entry error or a payment made in advance of the bill, and both need explanation. Here, 1 of the planted holiday payments is dated before its bill was received, which makes it doubly suspicious.\n\n### Transactions by the hour of the day {#sec-lubri-hours}\n\nDates tell us *which day* something happened. Date-times also tell us *what time*, and that can be just as revealing. Most computerised systems, like the treasury's e-payment system, an ERP, or core banking, record a time stamp for every transaction: when a bill was passed, a payment approved, or a record changed. Government offices work roughly from 9:30 in the morning to 6 in the evening on working days. A payment approved at two in the morning, or on a Sunday, is not necessarily wrong, but it deserves a question. Was the approver really at work then? Was someone else using the approver's login?\n\nLet us take the system log of e-payment approvals of a treasury for one quarter.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the approval log\"}\nset.seed(915)\nwork_days <- seq(as.Date(\"2024-10-01\"), as.Date(\"2024-12-31\"), by = \"day\")\nwork_days <- work_days[!wday(work_days) %in% c(1, 7)]       # Monday to Friday\nusers <- sprintf(\"USR%02d\", 1:12)\nn_log <- 6000\napproval_log <- tibble(\n  user = sample(users, n_log, TRUE),\n  # mostly between 10 am and 6 pm, peaking before lunch and in the late afternoon\n  time = force_tz(as_datetime(sample(work_days, n_log, TRUE)), \"Asia/Kolkata\") +\n         round(3600 * pmin(pmax(rnorm(n_log, 14, 2.1), 9.6), 19.5) * 60) / 60,\n  amount = round(rlnorm(n_log, log(40000), 1))\n)\n# Planted. One user approves payments late at night and at weekends\nodd_days <- seq(as.Date(\"2024-10-01\"), as.Date(\"2024-12-31\"), by = \"day\")\nodd <- tibble(\n  user = \"USR07\",\n  time = force_tz(as_datetime(sample(odd_days, 45, TRUE)), \"Asia/Kolkata\") +\n         3600 * sample(c(22, 23, 0, 1, 2), 45, TRUE) + 60 * sample(0:59, 45, TRUE),\n  amount = round(rlnorm(45, log(180000), 0.6))\n)\napproval_log <- bind_rows(approval_log, odd) |> arrange(time)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\napproval_log\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6,045 × 3\n   user  time                amount\n   <chr> <dttm>               <dbl>\n 1 USR07 2024-10-01 02:13:00 202766\n 2 USR04 2024-10-01 09:44:53 117861\n 3 USR03 2024-10-01 10:00:18 156700\n 4 USR10 2024-10-01 10:27:05 208232\n 5 USR05 2024-10-01 10:44:02 103937\n 6 USR03 2024-10-01 10:49:40   9863\n 7 USR05 2024-10-01 10:54:30   5862\n 8 USR04 2024-10-01 10:55:40  55510\n 9 USR08 2024-10-01 10:58:20  13366\n10 USR02 2024-10-01 11:01:15  65749\n# ℹ 6,035 more rows\n```\n\n\n:::\n:::\n\n\n`hour()` extracts the hour from a date-time, from 0 (midnight to 1 am) to 23. Counting approvals by hour, and colouring the hours outside office time, gives the picture at once.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\napproval_log |>\n  mutate(hour = hour(time),\n         office_hours = if_else(hour >= 9 & hour < 19, \"Office hours\", \"Outside office hours\")) |>\n  count(hour, office_hours) |>\n  ggplot(aes(hour, n, fill = office_hours)) +\n  geom_col() +\n  scale_x_continuous(breaks = 0:23) +\n  scale_fill_manual(values = c(\"Office hours\" = \"grey60\", \"Outside office hours\" = \"firebrick\")) +\n  labs(x = \"Hour of the day\", y = \"Approvals\", fill = NULL) +\n  theme_minimal() +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![E-payment approvals by hour of the day](12-8Lubridate_files/figure-html/unnamed-chunk-53-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nThe bulk of approvals fall in office hours, as they should. But there is a small, separate cluster late at night, between 10 pm and 3 am, which no ordinary working pattern explains. A **heat map** of the day of the week against the hour adds the weekends to the picture. `wday(label = TRUE, week_start = 1)` gives the day names, starting the week on Monday.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\napproval_log |>\n  mutate(hour = hour(time), day = wday(time, label = TRUE, week_start = 1)) |>\n  count(day, hour) |>\n  complete(day, hour = 0:23, fill = list(n = 0)) |>\n  ggplot(aes(hour, fct_rev(day), fill = n)) +\n  geom_tile(colour = \"white\") +\n  scale_fill_gradient(low = \"grey95\", high = \"darkred\", transform = \"sqrt\") +\n  scale_x_continuous(breaks = 0:23) +\n  labs(x = \"Hour of the day\", y = NULL, fill = \"Approvals\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Approvals by day of the week and hour](12-8Lubridate_files/figure-html/unnamed-chunk-54-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nThe working week shows as a solid block from about 9 am to 7 pm, Monday to Friday. Outside it, faint cells are scattered through the night, and on Saturdays and Sundays, when there should be nothing at all. (We used `complete()` from @sec-tidyr so that hours with no approvals appear as empty cells, rather than gaps, and a square-root colour scale so that the faint cells remain visible beside the busy ones.)\n\nWho approved these payments?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\noff_hours <- approval_log |>\n  filter(hour(time) < 9 | hour(time) >= 19 | wday(time) %in% c(1, 7))\n\noff_hours |>\n  summarise(approvals = n(), amount_lakh = round(sum(amount) / 1e5, 1), .by = user) |>\n  arrange(desc(approvals))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 3\n   user  approvals amount_lakh\n   <chr>     <int>       <dbl>\n 1 USR07        51       104. \n 2 USR04         7         1.3\n 3 USR08         7         2.5\n 4 USR01         6         7.2\n 5 USR09         5         2.2\n 6 USR06         3         3.9\n 7 USR03         3         0.9\n 8 USR05         2         0.9\n 9 USR10         2         1.3\n10 USR12         1         1.2\n11 USR11         1         1.4\n```\n\n\n:::\n:::\n\n\n\n\nOne user, USR07, stands out: 51 approvals worth ₹104.2 lakh, far larger than the typical payment. Every other user has only a handful, mostly just after 7 pm, when an office sometimes works late. The next steps would be to compare these times with the user's attendance and leave records, to check where the logins came from, and to examine the payments themselves.\n\n::: callout-tip\n## Audit tip\n\nBefore reading anything into the hours, check the **time zone** of the time stamps. Systems often store time in UTC, which is five and a half hours behind Indian Standard Time. Read in the wrong zone, a 3 pm approval appears as 9:30 am, and every pattern shifts. Use `with_tz(time, \"Asia/Kolkata\")` to show a stored time in Indian time, and `force_tz()` when a time was recorded without a zone and is known to be Indian time. The trap is easy to fall into. Even `as.POSIXct()` on a date gives midnight in UTC, which is 5:30 am in India. While preparing the data for this very section, that one slip moved every approval five and a half hours later, and made the whole office look as if it worked through the night. The code above uses `force_tz(as_datetime(date), \"Asia/Kolkata\")`, which gives midnight in Indian time.\n:::\n\n::: callout-tip\n## Audit tip\n\nAlways fix the *as-on date* of an ageing analysis, as we did with `as_on`, instead of using `today()`. The analysis is then reproducible, and matches the date of the accounts being audited. And make the age groups match the rules in force, like the time limit for paying bills or adjusting advances, so that the groups beyond the limit are the exceptions to report.\n:::\n\n## A suggested workflow\n\n1.  **Read the dates correctly.** Dates in files received from the auditee come in many forms. Use `dmy()`, `ymd()` or `mdy()` to match the order in the file, and check a few rows after conversion.\n2.  **Set the time zone.** Time stamps from a system log may be stored in UTC. Use `with_tz()` or `force_tz()` to get Indian Standard Time before any analysis.\n3.  **Add the financial year and quarter.** Use `quarter()` with `fiscal_start = 4`, so that April to June is the first quarter. Then summarise bills and payments by financial year and quarter.\n4.  **Check payments on Sundays and holidays.** Use `wday()` to find the day of the week, and `%in%` to compare with the list of gazetted holidays. Check both, since a holiday can fall on a weekday.\n5.  **Look at the hour of approvals.** Use `hour()` on the time stamps to find approvals made late at night or at weekends. Count them by user.\n6.  **Run validity checks.** Subtract dates to get the days taken to pay. A bill paid before it was received is either an entry error or an advance payment, and needs explanation.\n7.  **Age the pending items.** Fix an as-on date, work out the days pending, and sort them into age groups with `cut()`. Make the groups match the time limits in the rules.\n\n::: callout-important\n## Remember\n\nDates and times are easy to misread. A wrong date order or a wrong time zone shifts every result, without any error message. Check a few converted values by hand. Fix the as-on date instead of using `today()`, so that the analysis can be repeated.\n:::\n\n## Where next\n\nDates are also the backbone of two later chapters. When the question is about how a measure *moves over time*, its trend, its seasons and what to expect next month, see the chapter on time series analysis (@sec-ts). When the question is whether a particular month is *unusual*, or when a series *shifted* to a new level, see the time series methods of the anomaly detection chapter (@sec-ano-ts and @sec-ano-changepoint).\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `as.Date()`, `as.POSIXct()`, `difftime()` | base R | Dates, date-times and time differences |\n| `ymd()`, `dmy()`, `mdy()` and others | lubridate | Read dates written in the given order of year, month and day |\n| `make_date()`, `make_datetime()` | lubridate | Build dates from year, month and day columns |\n| `year()`, `month()`, `day()`, `wday()`, `quarter()`, `hour()` | lubridate | Extract parts of a date or date-time, including the fiscal quarter and the hour |\n| `with_tz()`, `force_tz()` | lubridate | Show a date-time in another time zone, or set its zone |\n| `years()`, `months()`, `dyears()`, `interval()`, `%--%`, `%within%` | lubridate | Periods, durations and intervals |\n| `%m+%`, `add_with_rollback()` | lubridate | Add months without going past the month's last day |\n| `floor_date()`, `ceiling_date()`, `round_date()` | lubridate | Round dates to a unit, like the start of the month |\n| `format()`, `strftime()`, `stamp()` | base R, lubridate | Show dates in a chosen format |\n| `cut()` | base R | Sort numbers, like days pending, into groups |\n| `scale_x_date()` | ggplot2 | Date axes in charts |\n| `geom_col()`, `geom_tile()` | ggplot2 | Bar chart by hour, and heat map of day against hour |\n\n: Functions used in this chapter {#tbl-lubrifunctions}\n",
    "supporting": [
      "12-8Lubridate_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}