{
  "hash": "1a446155368202ab4f4741d5b5b954cf",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Network Analysis in Audit {#sec-netaudit}\n\nMany frauds are about *connections* that someone wants to hide. In a welfare scheme, one person registers several times, each time with a slightly different identity, and draws the benefit several times. In a Public Works Division, a few firms bid against each other in every tender, but they are really one group. In GST returns, the same goods \"move\" round a circle of firms on paper, to create a false turnover. In an office, a vendor is secretly linked to the employee who passes its bills. Each of these leaves a trace in the data. The trace is hard to see in a table, but easy to see in a network.\n\nIn @sec-graph, we learnt the ideas of graph theory and the tools to work with networks in R. In this chapter we apply them to four audit problems.\n\n- One person behind many registrations in a scheme, found with *connected components*.\n- A cartel of firms which always bid together, found with *communities*.\n- Invoices going round in a circle between a few firms, found with *cycles*.\n- A vendor linked with an employee, found with components and *shortest paths*.\n\nThe recipe is nearly always the same. We turn the records into a graph. We reduce the graph to the parts that matter. We find the structure we are looking for, like a connected group, a cycle, a community or a path. Then we go back to the records. At the end of the chapter, we collect tips for working with the large networks that real audit data produces.\n\n## Prerequisites\n\nWe will use `tidyverse` for data handling, `igraph` for the analysis, and `visNetwork` to draw interactive networks. In each interactive network of this chapter, you can zoom, drag the vertices, hover over them for details, and click a vertex to highlight its neighbours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(igraph)\nlibrary(visNetwork)\n```\n:::\n\n\n## Audit use case 1, one person behind many registrations {#sec-dup_net}\n\nImagine a scheme where each person has several IDs, such as a mobile number, an email ID, and an ID issued by a Government Department, like the PAN in India. Using the techniques of @sec-dup, we can easily find duplicates on the basis of any *one* ID. But sometimes a person registers again after changing one or two IDs, while keeping another. For example, in a social sector scheme, each beneficiary is expected to register only once. A scheme audit may require the auditor to find duplicate beneficiaries across *all* the IDs together.\n\nLet us understand this with @tbl-gra101.\n\n\n::: {#tbl-gra101 .cell tbl-cap='A small register of ten applicants'}\n\n```{.r .cell-code}\nPANs <- paste0(\n  \"PANNO\", c(\"0000\", \"0000\", \"1111\", \"2222\", \"3333\", \"4444\", \"5555\", \"5555\", \"6666\", \"7777\"),\n  c(\"A\", \"A\", \"B\", \"C\", \"D\", \"E\", \"F\", \"F\", \"G\", \"H\")\n)\n\nemails <- paste0(c(\"aaaa\", \"bbbb\", \"cccc\", \"dddd\", \"eeee\", \"ffff\", \"gggg\", \"hhhh\", \"iiii\", \"bbbb\"), \"@gmail.com\")\n\ntele <- paste0(\"9\", c(\"1\", \"2\", \"3\", \"4\", \"1\", \"1\", \"5\", \"6\", \"3\", \"2\") %>%\n  map_chr(~ rep(.x, 9) %>%\n    paste0(collapse = \"\")))\n\ndummy_data <- data.frame(\n  ID = 1:10,\n  Mobile = tele,\n  Email = emails,\n  PAN = PANs\n)\n\nknitr::kable(dummy_data)\n```\n\n::: {.cell-output-display}\n\n\n| ID|Mobile     |Email          |PAN        |\n|--:|:----------|:--------------|:----------|\n|  1|9111111111 |aaaa@gmail.com |PANNO0000A |\n|  2|9222222222 |bbbb@gmail.com |PANNO0000A |\n|  3|9333333333 |cccc@gmail.com |PANNO1111B |\n|  4|9444444444 |dddd@gmail.com |PANNO2222C |\n|  5|9111111111 |eeee@gmail.com |PANNO3333D |\n|  6|9111111111 |ffff@gmail.com |PANNO4444E |\n|  7|9555555555 |gggg@gmail.com |PANNO5555F |\n|  8|9666666666 |hhhh@gmail.com |PANNO5555F |\n|  9|9333333333 |iiii@gmail.com |PANNO6666G |\n| 10|9222222222 |bbbb@gmail.com |PANNO7777H |\n\n\n:::\n:::\n\n\nPersons with IDs 6 and 10 share none of the three IDs, Mobile, Email and PAN. But look closely. ID-6 shares the mobile number with ID-1, who in turn shares the PAN with ID-2. ID-2 further shares both the email and the mobile number with ID-10. So ID-6 and ID-10 are linked, through a chain. Such chains are impossible to see in a table of thousands of rows. But they are obvious in a network, as in @fig-idnet1. *Note that we are not using names to find duplicates. Names are easily changed and often spelt differently.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nid_long <- dummy_data |>\n  pivot_longer(-ID, names_to = \"id_type\", values_to = \"value\") |>\n  mutate(person = paste0(\"ID-\", ID),\n         id_node = paste(id_type, value, sep = \":\"))\n\nid_nodes <- bind_rows(\n  tibble(id = unique(id_long$person), group = \"Person\"),\n  distinct(id_long, id = id_node, group = id_type)\n) |>\n  mutate(label = if_else(group == \"Person\", id, \"\"), title = id)\n\nvisNetwork(id_nodes, select(id_long, from = person, to = id_node),\n           width = \"100%\", height = \"450px\") |>\n  visGroups(groupname = \"Person\", color = \"steelblue\", shape = \"dot\") |>\n  visGroups(groupname = \"Mobile\", color = \"orange\", shape = \"square\") |>\n  visGroups(groupname = \"Email\", color = \"seagreen\", shape = \"triangle\") |>\n  visGroups(groupname = \"PAN\", color = \"tomato\", shape = \"diamond\") |>\n  visOptions(highlightNearest = TRUE) |>\n  visLegend()\n```\n\n::: {#fig-idnet1 .cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-f79daa2be81d7307e0d1\" style=\"width:100%;height:450px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f79daa2be81d7307e0d1\">{\"x\":{\"nodes\":{\"id\":[\"ID-1\",\"ID-2\",\"ID-3\",\"ID-4\",\"ID-5\",\"ID-6\",\"ID-7\",\"ID-8\",\"ID-9\",\"ID-10\",\"Mobile:9111111111\",\"Email:aaaa@gmail.com\",\"PAN:PANNO0000A\",\"Mobile:9222222222\",\"Email:bbbb@gmail.com\",\"Mobile:9333333333\",\"Email:cccc@gmail.com\",\"PAN:PANNO1111B\",\"Mobile:9444444444\",\"Email:dddd@gmail.com\",\"PAN:PANNO2222C\",\"Email:eeee@gmail.com\",\"PAN:PANNO3333D\",\"Email:ffff@gmail.com\",\"PAN:PANNO4444E\",\"Mobile:9555555555\",\"Email:gggg@gmail.com\",\"PAN:PANNO5555F\",\"Mobile:9666666666\",\"Email:hhhh@gmail.com\",\"Email:iiii@gmail.com\",\"PAN:PANNO6666G\",\"PAN:PANNO7777H\"],\"group\":[\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Person\",\"Mobile\",\"Email\",\"PAN\",\"Mobile\",\"Email\",\"Mobile\",\"Email\",\"PAN\",\"Mobile\",\"Email\",\"PAN\",\"Email\",\"PAN\",\"Email\",\"PAN\",\"Mobile\",\"Email\",\"PAN\",\"Mobile\",\"Email\",\"Email\",\"PAN\",\"PAN\"],\"label\":[\"ID-1\",\"ID-2\",\"ID-3\",\"ID-4\",\"ID-5\",\"ID-6\",\"ID-7\",\"ID-8\",\"ID-9\",\"ID-10\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"],\"title\":[\"ID-1\",\"ID-2\",\"ID-3\",\"ID-4\",\"ID-5\",\"ID-6\",\"ID-7\",\"ID-8\",\"ID-9\",\"ID-10\",\"Mobile:9111111111\",\"Email:aaaa@gmail.com\",\"PAN:PANNO0000A\",\"Mobile:9222222222\",\"Email:bbbb@gmail.com\",\"Mobile:9333333333\",\"Email:cccc@gmail.com\",\"PAN:PANNO1111B\",\"Mobile:9444444444\",\"Email:dddd@gmail.com\",\"PAN:PANNO2222C\",\"Email:eeee@gmail.com\",\"PAN:PANNO3333D\",\"Email:ffff@gmail.com\",\"PAN:PANNO4444E\",\"Mobile:9555555555\",\"Email:gggg@gmail.com\",\"PAN:PANNO5555F\",\"Mobile:9666666666\",\"Email:hhhh@gmail.com\",\"Email:iiii@gmail.com\",\"PAN:PANNO6666G\",\"PAN:PANNO7777H\"]},\"edges\":{\"from\":[\"ID-1\",\"ID-1\",\"ID-1\",\"ID-2\",\"ID-2\",\"ID-2\",\"ID-3\",\"ID-3\",\"ID-3\",\"ID-4\",\"ID-4\",\"ID-4\",\"ID-5\",\"ID-5\",\"ID-5\",\"ID-6\",\"ID-6\",\"ID-6\",\"ID-7\",\"ID-7\",\"ID-7\",\"ID-8\",\"ID-8\",\"ID-8\",\"ID-9\",\"ID-9\",\"ID-9\",\"ID-10\",\"ID-10\",\"ID-10\"],\"to\":[\"Mobile:9111111111\",\"Email:aaaa@gmail.com\",\"PAN:PANNO0000A\",\"Mobile:9222222222\",\"Email:bbbb@gmail.com\",\"PAN:PANNO0000A\",\"Mobile:9333333333\",\"Email:cccc@gmail.com\",\"PAN:PANNO1111B\",\"Mobile:9444444444\",\"Email:dddd@gmail.com\",\"PAN:PANNO2222C\",\"Mobile:9111111111\",\"Email:eeee@gmail.com\",\"PAN:PANNO3333D\",\"Mobile:9111111111\",\"Email:ffff@gmail.com\",\"PAN:PANNO4444E\",\"Mobile:9555555555\",\"Email:gggg@gmail.com\",\"PAN:PANNO5555F\",\"Mobile:9666666666\",\"Email:hhhh@gmail.com\",\"PAN:PANNO5555F\",\"Mobile:9333333333\",\"Email:iiii@gmail.com\",\"PAN:PANNO6666G\",\"Mobile:9222222222\",\"Email:bbbb@gmail.com\",\"PAN:PANNO7777H\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\"},\"manipulation\":{\"enabled\":false},\"groups\":{\"Person\":{\"color\":\"steelblue\",\"shape\":\"dot\"},\"Mobile\":{\"color\":\"orange\",\"shape\":\"square\"},\"Email\":{\"color\":\"seagreen\",\"shape\":\"triangle\"},\"useDefaultGroups\":true,\"PAN\":{\"color\":\"tomato\",\"shape\":\"diamond\"}}},\"groups\":[\"Person\",\"Mobile\",\"Email\",\"PAN\"],\"width\":\"100%\",\"height\":\"450px\",\"idselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"highlight\":{\"enabled\":true,\"hoverNearest\":false,\"degree\":1,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"legend\":{\"width\":0.2,\"useGroups\":true,\"position\":\"left\",\"ncol\":1,\"stepX\":100,\"stepY\":100,\"zoom\":true}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nNetwork of persons (blue) and their IDs. Hover or click to explore.\n:::\n:::\n\n\nNotice the structure of this graph. It is *bipartite*. Persons are connected only to IDs, and IDs only to persons. Two persons are related if there is any path between them. In graph theory terms, all related persons fall in the same *connected component*. So all we have to do is find the components of this graph.\n\n### The algorithm\n\nHere is the complete algorithm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nid_cols <- c(\"Mobile\", \"Email\", \"PAN\")\n\ndummy_data |>\n  mutate(across(all_of(id_cols), as.character)) |>\n  pivot_longer(cols = all_of(id_cols), names_to = \"id_type\",\n               values_to = \"value\", values_drop_na = TRUE) |>\n  mutate(id_node = paste(id_type, value, sep = \":\")) |>\n  select(ID, id_node) |>\n  graph_from_data_frame(directed = FALSE) |>\n  components() |>\n  _$membership |>\n  stack() |>\n  set_names(c(\"UNIQUE_ID\", \"ID\")) |>\n  filter(!str_detect(ID, \":\")) |>\n  mutate(ID = as.integer(as.character(ID))) |>\n  right_join(dummy_data, by = \"ID\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   UNIQUE_ID ID     Mobile          Email        PAN\n1          1  1 9111111111 aaaa@gmail.com PANNO0000A\n2          1  2 9222222222 bbbb@gmail.com PANNO0000A\n3          2  3 9333333333 cccc@gmail.com PANNO1111B\n4          3  4 9444444444 dddd@gmail.com PANNO2222C\n5          1  5 9111111111 eeee@gmail.com PANNO3333D\n6          1  6 9111111111 ffff@gmail.com PANNO4444E\n7          4  7 9555555555 gggg@gmail.com PANNO5555F\n8          4  8 9666666666 hhhh@gmail.com PANNO5555F\n9          2  9 9333333333 iiii@gmail.com PANNO6666G\n10         1 10 9222222222 bbbb@gmail.com PANNO7777H\n```\n\n\n:::\n:::\n\n\nWe now have a `UNIQUE_ID` for each person, based on all three IDs together. Persons 1, 2, 5, 6 and 10 share one `UNIQUE_ID`, so they may be the same person, or a group acting together. Let us understand the algorithm step by step.\n\n**Step 1.** All the ID columns must be of the same type. Real data often has a mix of character and numeric IDs, like a numeric mobile number and an alphanumeric PAN. Using `across()` inside `mutate()`, we convert all of them to character. Readers may refer to @sec-vectors for changing types, and @sec-across for changing many columns at once with `across()`.\n\n```\nid_cols <- c(\"Mobile\", \"Email\", \"PAN\")\ndummy_data |>\n  mutate(across(all_of(id_cols), as.character))\n```\n\n**Step 2.** Pivot all the ID columns into a longer format, so that each row links one person with one ID. Two things should be kept in mind. First, the data must have a column which identifies each record, here `ID`. If there is none, create one with `row_number()` before pivoting. Second, missing IDs must be removed while pivoting, using `values_drop_na = TRUE`. Otherwise, all persons with a missing PAN would be linked through the common value `NA`.\n\n**Step 3.** Prefix each ID value with its type, like `Mobile:9111111111`. This is important. Without it, a value appearing in two different columns would become one vertex. For example, a record number `\"12\"` and a ward number `\"12\"` would wrongly link two records. Then we keep only the two columns we need, the record `ID` and the prefixed `id_node`. Up to this step, our data looks like this.\n\n::: callout-note\n## Normalise the IDs first\n\nIn real data, the same ID is written in many ways, and each way would become a separate vertex. Before Step 2, standardise every ID column. Mobile numbers lose their `+91` or `0` prefix with `clean_mobile()`, and email IDs are normalised with `normalise_email()`, both from @sec-regex-validate. The second is especially important. Gmail ignores dots and `+tags` in the user name, so `r.kumar@gmail.com` and `rkumar+scheme@gmail.com` reach the same mailbox. Someone registering several times may use exactly this trick, and without normalising, the network would never connect those registrations.\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n     ID id_node             \n  <int> <chr>               \n1     1 Mobile:9111111111   \n2     1 Email:aaaa@gmail.com\n3     1 PAN:PANNO0000A      \n4     2 Mobile:9222222222   \n5     2 Email:bbbb@gmail.com\n6     2 PAN:PANNO0000A      \n```\n\n\n:::\n:::\n\n\n**Step 4.** We create an undirected graph from this data, using `graph_from_data_frame()`. Each row becomes an edge between a person and an ID. Readers may plot it, but for large data the plot will be a cluttered hairball. The tips at the end of this chapter explain how to deal with that.\n\n**Step 5.** `components()` finds the connected components of the graph. Its element `$membership` is a named vector, giving the component number of each vertex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nid_graph <- graph_from_data_frame(id_edges, directed = FALSE)\ncomponents(id_graph)$membership\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   1                    2                    3 \n                   1                    1                    2 \n                   4                    5                    6 \n                   3                    1                    1 \n                   7                    8                    9 \n                   4                    4                    2 \n                  10    Mobile:9111111111 Email:aaaa@gmail.com \n                   1                    1                    1 \n      PAN:PANNO0000A    Mobile:9222222222 Email:bbbb@gmail.com \n                   1                    1                    1 \n   Mobile:9333333333 Email:cccc@gmail.com       PAN:PANNO1111B \n                   2                    2                    2 \n   Mobile:9444444444 Email:dddd@gmail.com       PAN:PANNO2222C \n                   3                    3                    3 \nEmail:eeee@gmail.com       PAN:PANNO3333D Email:ffff@gmail.com \n                   1                    1                    1 \n      PAN:PANNO4444E    Mobile:9555555555 Email:gggg@gmail.com \n                   1                    4                    4 \n      PAN:PANNO5555F    Mobile:9666666666 Email:hhhh@gmail.com \n                   4                    4                    4 \nEmail:iiii@gmail.com       PAN:PANNO6666G       PAN:PANNO7777H \n                   2                    2                    1 \n```\n\n\n:::\n:::\n\n\nThe native pipe placeholder `_$membership` extracts this element inside a pipe. We then convert the named vector into a data frame with `stack()`, and name its two columns with `set_names()`.\n\n**Step 6.** The membership includes the ID vertices too, like `Mobile:9111111111`. We keep only the person vertices, which have no `:` in their name. Their names are characters, so we convert them back to integers. Finally, we join the result back to the original data with `right_join()`.\n\n### A bigger example, beneficiaries of a scheme\n\nThe small register showed the idea. Let us now try it on a more realistic register of 3,000 beneficiaries of an imaginary State scheme. The scheme pays ₹6,000 a year to each beneficiary, by direct benefit transfer into the bank account. Each beneficiary has a mobile number and a bank account. About 60% of them have also given a PAN. We have planted a few cases.\n\n- 60 pairs of beneficiaries share a mobile number. These are families, and genuine.\n- A ring of 7 registrations, each sharing one ID with the previous one, as if one person kept registering again, changing one ID at a time.\n- An agent's mobile number, entered against 30 beneficiaries.\n- A placeholder mobile number, `9999999999`, entered by data entry operators against 45 beneficiaries who did not give a number.\n\nAs usual, the code to create the data is folded.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the beneficiary register\"}\nset.seed(1234)\nn <- 3000\nrand_mobile <- function(k) paste0(sample(6:9, k, TRUE), sprintf(\"%09d\", sample(0:999999999, k)))\nrand_acct   <- function(k) sprintf(\"%011.0f\", runif(k, 1e10, 9e10))\nrand_pan    <- function(k) paste0(replicate(k, paste(sample(LETTERS, 5, TRUE), collapse = \"\")),\n                                  sprintf(\"%04d\", sample(0:9999, k, TRUE)), sample(LETTERS, k, TRUE))\n\nben <- tibble(ben_id  = sprintf(\"B%05d\", 1:n),\n              mobile  = rand_mobile(n),\n              bank_ac = rand_acct(n),\n              pan     = rand_pan(n))\n\n# Genuine. 60 families share a mobile number\nfam <- sample(1:n, 120)\nben$mobile[fam[61:120]] <- ben$mobile[fam[1:60]]\n\n# Planted. A ring of 7 registrations, each sharing one ID with the previous one\nring <- c(101, 502, 903, 1304, 1705, 2106, 2507)\n\n# PAN not given by about 40% of beneficiaries\nben$pan[sample(setdiff(1:n, ring), 0.4 * n)] <- NA\n\nfor (i in 2:length(ring)) {\n  col <- c(\"mobile\", \"bank_ac\", \"pan\")[(i %% 3) + 1]\n  ben[[col]][ring[i]] <- ben[[col]][ring[i - 1]]\n}\n\n# Planted. An agent's mobile number on 30 beneficiaries\nagent <- sample(setdiff(1:n, c(ring, fam)), 30)\nben$mobile[agent] <- \"9876543210\"\n\n# Placeholder number entered when the mobile was not given\njunk <- sample(setdiff(1:n, c(ring, fam, agent)), 45)\nben$mobile[junk] <- \"9999999999\"\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(ben)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  ben_id mobile     bank_ac     pan       \n  <chr>  <chr>      <chr>       <chr>     \n1 B00001 9917386478 18050509803 XOXWL9138R\n2 B00002 9370227021 56371950097 <NA>      \n3 B00003 7167562714 21329966281 LYMCW8437B\n4 B00004 7550824366 76115990430 <NA>      \n5 B00005 6444067445 43472028691 <NA>      \n6 B00006 9758995374 32394157834 DGJHX1642S\n```\n\n\n:::\n:::\n\n\nLet us convert it into the long format, with prefixed IDs, as before.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nben_long <- ben |>\n  pivot_longer(-ben_id, names_to = \"id_type\", values_to = \"value\",\n               values_drop_na = TRUE) |>\n  mutate(id_node = paste(id_type, value, sep = \":\"))\n```\n:::\n\n\n**First, look at the most shared IDs.** Before building any graph, let us count how many beneficiaries each ID is linked with.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nben_long |>\n  count(id_node, sort = TRUE) |>\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  id_node                 n\n  <chr>               <int>\n1 mobile:9999999999      45\n2 mobile:9876543210      30\n3 bank_ac:14356289729     2\n4 bank_ac:55509169120     2\n5 mobile:6018888444       2\n```\n\n\n:::\n:::\n\n\nTwo values stand out at once. `9999999999` is obviously a placeholder, not a real number. If we keep it, it will link 45 unrelated beneficiaries into one false group. The other value, `9876543210`, is linked with 30 beneficiaries. It looks genuine, and is exactly the kind of *hub* an auditor wants to find. It may be the number of an agent or a middleman, who registered and perhaps controls these beneficiaries. We drop the placeholder and keep the rest. In larger data, such junk values can be found systematically, before building any graph. A number made of one repeated digit is matched by the regex `^(\\\\d)\\\\1{9}$`. IDs which fail their format or check digit can also be listed. Both are explained in @sec-regex-validate and @sec-checkdigits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nben_long <- ben_long |>\n  filter(value != \"9999999999\")\n```\n:::\n\n\n**Next, drop the leaf nodes.** Most IDs belong to exactly one beneficiary. In the graph, such an ID is a *leaf*, a vertex with only one edge. A leaf can never link two beneficiaries, so it adds nothing to our analysis. It only makes the graph bigger. Let us compare the graph with and without them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng_full <- graph_from_data_frame(select(ben_long, ben_id, id_node), directed = FALSE)\n\n# Keep only IDs shared by at least two beneficiaries\nben_shared <- ben_long |>\n  add_count(id_node) |>\n  filter(n > 1)\n\ng_ben <- graph_from_data_frame(select(ben_shared, ben_id, id_node), directed = FALSE)\n\ntibble(graph    = c(\"All IDs\", \"Shared IDs only\"),\n       vertices = c(vcount(g_full), vcount(g_ben)),\n       edges    = c(ecount(g_full), ecount(g_ben)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  graph           vertices edges\n  <chr>              <dbl> <dbl>\n1 All IDs            10660  7755\n2 Shared IDs only      224   162\n```\n\n\n:::\n:::\n\n\nThe graph has shrunk from 10,660 vertices to just 224, and the answer is not affected at all. Beneficiaries who share nothing with anyone have dropped out too, which is what we want. With real data of lakhs of records, this one step often makes the difference between a graph R can handle easily and one it cannot.\n\n**Now find the groups.** Let us find the components, and count how many beneficiaries each one has.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nben_groups <- components(g_ben)$membership |>\n  stack() |>\n  set_names(c(\"group\", \"node\")) |>\n  filter(str_starts(node, \"B\")) |>\n  count(group, name = \"beneficiaries\", sort = TRUE)\n\nben_groups |> count(beneficiaries, name = \"number_of_groups\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  beneficiaries number_of_groups\n1             2               60\n2             7                1\n3            30                1\n```\n\n\n:::\n:::\n\n\n\n\nThere are 60 groups of two. These are mostly the families who share a mobile, which is normal. There is one group of 30, around the agent's number. And there is one group of 7, the ring we planted. At ₹6,000 a year each, the ring draws ₹42,000 a year. The beneficiaries around the agent's number draw ₹1.8 lakh a year. These amounts are at risk until the beneficiaries are verified. Let us draw the second largest group, in @fig-ring.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ben_groups is sorted by size. Take the second largest group.\nring_id <- ben_groups$group[2]\nring_nodes <- names(which(components(g_ben)$membership == ring_id))\n\nring_graph <- induced_subgraph(g_ben, ring_nodes)\n\nring_vis <- toVisNetworkData(ring_graph)\nring_vis$nodes <- ring_vis$nodes |>\n  mutate(group = if_else(str_starts(id, \"B\"), \"Beneficiary\", str_extract(id, \"^[a-z_]+\")),\n         title = id)\n\nvisNetwork(ring_vis$nodes, ring_vis$edges, width = \"100%\", height = \"400px\") |>\n  visGroups(groupname = \"Beneficiary\", color = \"steelblue\", shape = \"dot\") |>\n  visGroups(groupname = \"mobile\", color = \"orange\", shape = \"square\") |>\n  visGroups(groupname = \"bank_ac\", color = \"purple\", shape = \"triangle\") |>\n  visGroups(groupname = \"pan\", color = \"tomato\", shape = \"diamond\") |>\n  visOptions(highlightNearest = TRUE) |>\n  visLegend()\n```\n\n::: {#fig-ring .cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-102dddb8d02e24ffa6a7\" style=\"width:100%;height:400px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-102dddb8d02e24ffa6a7\">{\"x\":{\"nodes\":{\"id\":[\"B00101\",\"B00502\",\"B00903\",\"B01304\",\"B01705\",\"B02106\",\"B02507\",\"pan:TNTWC7140B\",\"mobile:7039936789\",\"bank_ac:55509169120\",\"pan:CHVAQ9877I\",\"mobile:8075494714\",\"bank_ac:14356289729\"],\"label\":[\"B00101\",\"B00502\",\"B00903\",\"B01304\",\"B01705\",\"B02106\",\"B02507\",\"pan:TNTWC7140B\",\"mobile:7039936789\",\"bank_ac:55509169120\",\"pan:CHVAQ9877I\",\"mobile:8075494714\",\"bank_ac:14356289729\"],\"group\":[\"Beneficiary\",\"Beneficiary\",\"Beneficiary\",\"Beneficiary\",\"Beneficiary\",\"Beneficiary\",\"Beneficiary\",\"pan\",\"mobile\",\"bank_ac\",\"pan\",\"mobile\",\"bank_ac\"],\"title\":[\"B00101\",\"B00502\",\"B00903\",\"B01304\",\"B01705\",\"B02106\",\"B02507\",\"pan:TNTWC7140B\",\"mobile:7039936789\",\"bank_ac:55509169120\",\"pan:CHVAQ9877I\",\"mobile:8075494714\",\"bank_ac:14356289729\"]},\"edges\":{\"from\":[\"B00101\",\"B00502\",\"B00502\",\"B00903\",\"B00903\",\"B01304\",\"B01304\",\"B01705\",\"B01705\",\"B02106\",\"B02106\",\"B02507\"],\"to\":[\"pan:TNTWC7140B\",\"pan:TNTWC7140B\",\"mobile:7039936789\",\"mobile:7039936789\",\"bank_ac:55509169120\",\"bank_ac:55509169120\",\"pan:CHVAQ9877I\",\"pan:CHVAQ9877I\",\"mobile:8075494714\",\"mobile:8075494714\",\"bank_ac:14356289729\",\"bank_ac:14356289729\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\"},\"manipulation\":{\"enabled\":false},\"groups\":{\"Beneficiary\":{\"color\":\"steelblue\",\"shape\":\"dot\"},\"mobile\":{\"color\":\"orange\",\"shape\":\"square\"},\"bank_ac\":{\"color\":\"purple\",\"shape\":\"triangle\"},\"useDefaultGroups\":true,\"pan\":{\"color\":\"tomato\",\"shape\":\"diamond\"}}},\"groups\":[\"Beneficiary\",\"pan\",\"mobile\",\"bank_ac\"],\"width\":\"100%\",\"height\":\"400px\",\"idselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"highlight\":{\"enabled\":true,\"hoverNearest\":false,\"degree\":1,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"legend\":{\"width\":0.2,\"useGroups\":true,\"position\":\"left\",\"ncol\":1,\"stepX\":100,\"stepY\":100,\"zoom\":true}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nA ring of 7 registrations linked through changing IDs\n:::\n:::\n\n\nEach beneficiary in the chain shares only *one* ID with the next. No check on a single ID column would find more than a pair. Only the network shows the whole ring.\n\nWhat next? The auditor would list the seven registrations with their names, addresses and dates of registration, and ask the scheme office to verify them. If they turn out to be one person, the payments to the extra registrations are recoverable. The agent's number needs a field visit, to find out who the agent is and whether the 30 beneficiaries exist and receive their money.\n\n::: callout-tip\n## Audit tip\n\nThe *degree* of an ID vertex, that is, the number of beneficiaries linked to it, is a quick way to find hubs. A mobile number or bank account linked with many beneficiaries deserves verification in the field. Who is the person behind it, and are the beneficiaries real?\n:::\n\n## Audit use case 2, bidders who bid together {#sec-net-bidders}\n\nCommunity detection, which we learnt in @sec-graph, classifies the vertices of a network into groups of closely linked vertices. In @sec-graph-tenders, we used it on links between firms from their registration papers. Often the auditor has no such papers, only the bids. Let us use the bids alone to find bid rigging. A *cartel* of firms agree among themselves who will win a tender. The others put in higher *cover bids*, to make the tender look competitive. Firms of a cartel therefore keep appearing in the same tenders. We looked for such firms with association rules in @sec-apriori. Let us now look at the same problem as a network.\n\nWe create bids for 200 tenders of an imaginary Public Works Division over a few years. There are 40 firms, and 3 to 6 firms bid in each tender. We have planted a cartel of 5 firms, which bid together in every fourth tender.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the bids\"}\nset.seed(77)\nfirms  <- sprintf(\"F%02d\", 1:40)\ncartel <- c(\"F05\", \"F11\", \"F23\", \"F31\", \"F38\")\n\nbids <- map_dfr(1:200, function(t) {\n  b <- sample(firms, sample(3:6, 1))\n  if (t %% 4 == 0) {\n    # Cartel tender. 3 to 5 cartel firms, with 0 to 2 outsiders\n    b <- union(sample(cartel, sample(3:5, 1)),\n               sample(setdiff(firms, cartel), sample(0:2, 1)))\n  }\n  tibble(tender = sprintf(\"T%03d\", t), firm = b)\n})\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(bids)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  tender firm \n  <chr>  <chr>\n1 T001   F05  \n2 T001   F37  \n3 T001   F29  \n4 T001   F22  \n5 T002   F20  \n6 T002   F31  \n```\n\n\n:::\n:::\n\n\nTenders and firms form a bipartite graph. But we are interested in the relation between *firms*. So we *project* the bipartite graph onto the firms. In the projected graph, two firms are connected if they bid in at least one common tender. The edge `weight` is the number of tenders in which they bid together. The function `bipartite_projection()` does this. It needs a logical vertex attribute `type`, which tells which set each vertex belongs to.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbid_graph <- graph_from_data_frame(bids, directed = FALSE)\nV(bid_graph)$type <- V(bid_graph)$name %in% bids$firm\n\nfirm_graph <- bipartite_projection(bid_graph, which = \"true\")\nfirm_graph\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIGRAPH 9cb6cc2 UNW- 40 666 -- \n+ attr: name (v/c), weight (e/n)\n+ edges from 9cb6cc2 (vertex names):\n [1] F05--F37 F05--F29 F05--F22 F05--F11 F05--F23 F05--F38 F05--F31 F05--F24\n [9] F05--F08 F05--F27 F05--F20 F05--F06 F05--F14 F05--F17 F05--F30 F05--F35\n[17] F05--F36 F05--F34 F05--F33 F05--F15 F05--F19 F05--F18 F05--F32 F05--F03\n[25] F05--F04 F05--F21 F05--F39 F05--F28 F05--F16 F05--F10 F05--F40 F05--F07\n[33] F05--F02 F05--F25 F37--F29 F37--F22 F37--F25 F37--F36 F37--F23 F37--F31\n[41] F37--F10 F37--F27 F37--F28 F37--F26 F37--F21 F37--F14 F37--F18 F37--F15\n[49] F37--F20 F37--F33 F37--F19 F37--F13 F37--F34 F37--F30 F37--F04 F37--F08\n[57] F37--F40 F37--F11 F37--F03 F37--F32 F37--F38 F37--F07 F29--F22 F29--F11\n+ ... omitted several edges\n```\n\n\n:::\n:::\n\n\nLet us see how many times pairs of firms have bid together.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(E(firm_graph)$weight)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   2   3   4   5   6   7   8  25  29  31  32  33  36 \n217 199 145  59  27   5   3   1   2   2   2   2   1   1 \n```\n\n\n:::\n:::\n\n\n\n\nMost pairs of firms have met in only one or two tenders, and no ordinary pair has met in more than 8. But a few pairs have met 25 to 36 times. That is a clear break. Let us keep only the edges with 10 or more joint bids, and see which firms remain.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrequent <- delete_edges(firm_graph, E(firm_graph)[weight < 10])\nfrequent <- delete_vertices(frequent, V(frequent)[degree(frequent) == 0])\nV(frequent)$name\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"F05\" \"F31\" \"F11\" \"F23\" \"F38\"\n```\n\n\n:::\n:::\n\n\nThese are exactly the five firms of our planted cartel. Without choosing any threshold, community detection with the Louvain method reaches the same answer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nfirm_comm <- cluster_louvain(firm_graph)\nsizes(firm_comm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCommunity sizes\n 1  2  3 \n 5 15 20 \n```\n\n\n:::\n\n```{.r .cell-code}\nfirm_comm[[which.min(sizes(firm_comm))]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"F05\" \"F31\" \"F11\" \"F23\" \"F38\"\n```\n\n\n:::\n:::\n\n\nThe smallest community found is again the cartel. @fig-cartel shows the network of firms, coloured by community, with thicker edges for more joint bids. With 40 firms there are 666 edges, and drawing all of them gives an unreadable hairball. So we draw only the pairs which bid together 4 or more times.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncartel_vis <- toVisNetworkData(firm_graph)\ncartel_vis$nodes$group <- paste(\"Community\", membership(firm_comm))\ncartel_vis$edges <- cartel_vis$edges |>\n  filter(weight >= 4) |>\n  mutate(value = weight, title = paste(\"Joint bids:\", weight))\n\nvisNetwork(cartel_vis$nodes, cartel_vis$edges, width = \"100%\", height = \"500px\") |>\n  visIgraphLayout(layout = \"layout_with_fr\", randomSeed = 7) |>\n  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) |>\n  visLegend()\n```\n\n::: {#fig-cartel .cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-be1589d8c7edc7f47091\" style=\"width:100%;height:500px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-be1589d8c7edc7f47091\">{\"x\":{\"nodes\":{\"id\":[\"F05\",\"F37\",\"F29\",\"F22\",\"F20\",\"F31\",\"F34\",\"F16\",\"F30\",\"F25\",\"F03\",\"F11\",\"F23\",\"F38\",\"F09\",\"F04\",\"F19\",\"F40\",\"F35\",\"F10\",\"F26\",\"F06\",\"F24\",\"F39\",\"F21\",\"F14\",\"F02\",\"F17\",\"F01\",\"F13\",\"F08\",\"F36\",\"F18\",\"F12\",\"F27\",\"F32\",\"F28\",\"F07\",\"F15\",\"F33\"],\"label\":[\"F05\",\"F37\",\"F29\",\"F22\",\"F20\",\"F31\",\"F34\",\"F16\",\"F30\",\"F25\",\"F03\",\"F11\",\"F23\",\"F38\",\"F09\",\"F04\",\"F19\",\"F40\",\"F35\",\"F10\",\"F26\",\"F06\",\"F24\",\"F39\",\"F21\",\"F14\",\"F02\",\"F17\",\"F01\",\"F13\",\"F08\",\"F36\",\"F18\",\"F12\",\"F27\",\"F32\",\"F28\",\"F07\",\"F15\",\"F33\"],\"group\":[\"Community 1\",\"Community 2\",\"Community 3\",\"Community 2\",\"Community 3\",\"Community 1\",\"Community 2\",\"Community 2\",\"Community 2\",\"Community 2\",\"Community 2\",\"Community 1\",\"Community 1\",\"Community 1\",\"Community 3\",\"Community 3\",\"Community 2\",\"Community 3\",\"Community 2\",\"Community 2\",\"Community 3\",\"Community 3\",\"Community 3\",\"Community 3\",\"Community 2\",\"Community 2\",\"Community 3\",\"Community 3\",\"Community 3\",\"Community 3\",\"Community 3\",\"Community 3\",\"Community 3\",\"Community 3\",\"Community 3\",\"Community 2\",\"Community 3\",\"Community 3\",\"Community 2\",\"Community 2\"],\"x\":[0.3298390931741162,-0.4919986594751617,0.1410045208894295,0.4328906267492099,-0.1393860053210426,0.03673153111381966,-0.2818970864172088,-0.2673855399921807,-0.05417357656655686,0.9365121357275112,0.3980653840809818,0.211919191377796,0.06936156627523182,0.2651056838949395,-0.7596038649488553,0.07871431289552411,0.4474060041075874,0.08368651330759724,-0.22946050133435,-0.2453227146494369,-0.3092578383704118,0.5405708565757255,0.02798837353863748,0.3189033117071203,-0.3211007507949377,-0.1153665661664703,0.2411726705709929,0.52845656202038,-1,0.2427767444139752,0.1190556794518818,0.2852589291440442,1,0.0281280602925007,0.370227571374409,0.6528469009682971,0.7266665876601914,-0.06201873478666076,0.6510247411684147,-0.3323730977636862],\"y\":[-0.307513775408584,-0.5957442403499504,-0.3382760228808933,-0.3060162454511015,0.3025574386079641,-0.2761197079648966,-1,-0.7413224590293569,-0.5583052516817611,-0.23386582899647,0.3303761643066221,-0.1479409263015613,-0.4076313449304227,-0.06705280107738076,-0.05977710752209198,-0.6121634559692567,-0.1640682173510742,-0.7746251358532307,-0.5304897045436194,-0.3505156000302841,-0.1376709398908638,-0.6028507586602387,-0.02113898662626101,1,-0.00300372089214751,-0.05335115447401351,0.1404775494058228,-0.442968835506459,0.3963832874205877,-0.6075986727091366,-0.03297721764726669,-0.7011614786699616,-0.5549905228507175,0.4383852094212788,-0.472902140107489,0.6047654737047523,-0.6943852236293188,-0.4228210583157417,-0.1228953141127868,0.6325257385748628]},\"edges\":{\"from\":[\"F05\",\"F05\",\"F05\",\"F05\",\"F05\",\"F05\",\"F05\",\"F05\",\"F37\",\"F29\",\"F29\",\"F29\",\"F29\",\"F29\",\"F29\",\"F29\",\"F29\",\"F29\",\"F29\",\"F29\",\"F29\",\"F29\",\"F29\",\"F22\",\"F22\",\"F22\",\"F22\",\"F20\",\"F20\",\"F20\",\"F20\",\"F20\",\"F31\",\"F31\",\"F31\",\"F31\",\"F31\",\"F31\",\"F31\",\"F31\",\"F31\",\"F31\",\"F31\",\"F34\",\"F16\",\"F16\",\"F16\",\"F30\",\"F30\",\"F30\",\"F25\",\"F25\",\"F03\",\"F03\",\"F03\",\"F11\",\"F11\",\"F11\",\"F11\",\"F11\",\"F23\",\"F23\",\"F23\",\"F23\",\"F23\",\"F23\",\"F23\",\"F23\",\"F23\",\"F23\",\"F38\",\"F38\",\"F38\",\"F38\",\"F38\",\"F09\",\"F04\",\"F04\",\"F04\",\"F04\",\"F19\",\"F40\",\"F40\",\"F40\",\"F10\",\"F26\",\"F26\",\"F06\",\"F06\",\"F24\",\"F21\",\"F14\",\"F17\",\"F17\",\"F17\",\"F17\",\"F17\",\"F13\",\"F13\",\"F13\",\"F08\",\"F08\",\"F08\",\"F08\",\"F27\"],\"to\":[\"F29\",\"F22\",\"F11\",\"F23\",\"F38\",\"F31\",\"F06\",\"F19\",\"F23\",\"F22\",\"F11\",\"F19\",\"F26\",\"F06\",\"F38\",\"F13\",\"F04\",\"F17\",\"F31\",\"F40\",\"F24\",\"F21\",\"F35\",\"F11\",\"F19\",\"F15\",\"F30\",\"F24\",\"F08\",\"F12\",\"F33\",\"F14\",\"F30\",\"F11\",\"F23\",\"F38\",\"F36\",\"F27\",\"F10\",\"F14\",\"F35\",\"F26\",\"F02\",\"F30\",\"F30\",\"F23\",\"F35\",\"F23\",\"F04\",\"F24\",\"F17\",\"F15\",\"F38\",\"F32\",\"F24\",\"F23\",\"F38\",\"F19\",\"F14\",\"F02\",\"F38\",\"F35\",\"F10\",\"F24\",\"F08\",\"F36\",\"F19\",\"F27\",\"F13\",\"F17\",\"F24\",\"F08\",\"F14\",\"F17\",\"F02\",\"F26\",\"F40\",\"F07\",\"F17\",\"F10\",\"F15\",\"F07\",\"F13\",\"F36\",\"F14\",\"F21\",\"F08\",\"F28\",\"F27\",\"F14\",\"F14\",\"F07\",\"F13\",\"F36\",\"F28\",\"F18\",\"F15\",\"F27\",\"F36\",\"F07\",\"F27\",\"F12\",\"F07\",\"F15\",\"F28\"],\"weight\":[5,5,25,29,25,29,4,4,4,4,4,4,4,8,4,5,4,6,6,4,7,4,4,5,5,4,6,4,5,4,4,4,4,32,36,31,4,4,4,5,4,4,4,4,4,6,5,5,5,4,4,4,5,5,5,32,31,5,4,4,33,5,5,5,7,4,6,5,4,5,4,4,7,4,5,4,4,4,4,4,4,4,5,5,4,4,4,4,4,5,4,5,4,4,5,4,4,5,4,4,4,4,5,4,4],\"value\":[5,5,25,29,25,29,4,4,4,4,4,4,4,8,4,5,4,6,6,4,7,4,4,5,5,4,6,4,5,4,4,4,4,32,36,31,4,4,4,5,4,4,4,4,4,6,5,5,5,4,4,4,5,5,5,32,31,5,4,4,33,5,5,5,7,4,6,5,4,5,4,4,7,4,5,4,4,4,4,4,4,4,5,5,4,4,4,4,4,5,4,5,4,4,5,4,4,5,4,4,4,4,5,4,4],\"title\":[\"Joint bids: 5\",\"Joint bids: 5\",\"Joint bids: 25\",\"Joint bids: 29\",\"Joint bids: 25\",\"Joint bids: 29\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 8\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 6\",\"Joint bids: 6\",\"Joint bids: 4\",\"Joint bids: 7\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 6\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 32\",\"Joint bids: 36\",\"Joint bids: 31\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 6\",\"Joint bids: 5\",\"Joint bids: 5\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 5\",\"Joint bids: 5\",\"Joint bids: 32\",\"Joint bids: 31\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 33\",\"Joint bids: 5\",\"Joint bids: 5\",\"Joint bids: 5\",\"Joint bids: 7\",\"Joint bids: 4\",\"Joint bids: 6\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 7\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 4\",\"Joint bids: 5\",\"Joint bids: 4\",\"Joint bids: 4\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\",\"physics\":false},\"manipulation\":{\"enabled\":false},\"edges\":{\"smooth\":false},\"physics\":{\"stabilization\":false}},\"groups\":[\"Community 1\",\"Community 2\",\"Community 3\"],\"width\":\"100%\",\"height\":\"500px\",\"idselection\":{\"enabled\":true,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"igraphlayout\":{\"type\":\"square\"},\"highlight\":{\"enabled\":true,\"hoverNearest\":false,\"degree\":1,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"legend\":{\"width\":0.2,\"useGroups\":true,\"position\":\"left\",\"ncol\":1,\"stepX\":100,\"stepY\":100,\"zoom\":true}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nFirms coloured by community. Only pairs with 4 or more joint bids are drawn, and edge width is the number of joint bids.\n:::\n:::\n\n\n::: callout-warning\n## Caution\n\nFirms may bid together often for genuine reasons. There may be only a few qualified firms for specialised work in a district. Joint bidding is a lead. Look for further signs. Do the firms win in turn (bid rotation)? Are the losing bids always slightly higher than the winning bid? Were the bids uploaded from the same computer or IP address? Do the firms share an address, a partner or a bank account? Are there the same mistakes in their bid documents?\n:::\n\n## Audit use case 3, circular trading {#sec-net-circular}\n\nIn *circular trading*, a group of firms issue invoices to each other in a circle. A sells to B, B to C, C to D, and D back to A, often for nearly the same amount, within a few days. No real goods move. The purpose may be to show a false turnover to get bank loans, or to pass on input tax credit under GST fraudulently. In a network of invoices, where each firm is a vertex and each invoice a directed edge from seller to buyer, such trading shows up as a **cycle**.\n\nLet us create the invoices of the financial year 2023-24 among the firms of a district. There are 15 manufacturers, 40 wholesalers and 150 retailers. Genuine goods flow one way, from manufacturers to wholesalers to retailers, so genuine trade has no cycles. We have planted two rings of circular trading. One ring of 4 firms went round twice, in September and November. Another ring of 3 retailers went round once, in January.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the invoices\"}\nset.seed(99)\nmk <- sprintf(\"M%02d\", 1:15)    # manufacturers\nws <- sprintf(\"W%02d\", 1:40)    # wholesalers\nrt <- sprintf(\"R%03d\", 1:150)   # retailers\n\ninvoices <- bind_rows(\n  tibble(seller = sample(mk, 400, TRUE), buyer = sample(ws, 400, TRUE)),\n  tibble(seller = sample(ws, 900, TRUE), buyer = sample(rt, 900, TRUE))\n) |>\n  mutate(date   = as.Date(\"2023-04-01\") + sample(0:364, n(), TRUE),\n         amount = round(rlnorm(n(), log(2e5), 0.8)))\n\n# Planted circular trading. Each invoice a little higher than the last, two days apart\ncircle <- function(firms, start, amount) {\n  k <- length(firms) - 1\n  tibble(seller = head(firms, -1), buyer = firms[-1],\n         date   = start + (0:(k - 1)) * 2,\n         amount = round(amount * (1 + cumsum(runif(k, 0, 0.01)))))\n}\nring1 <- c(\"W07\", \"R015\", \"R088\", \"W23\", \"W07\")\nring2 <- c(\"R040\", \"R121\", \"R063\", \"R040\")\n\ninvoices <- bind_rows(invoices,\n                      circle(ring1, as.Date(\"2023-09-11\"), 4850000),\n                      circle(ring1, as.Date(\"2023-11-20\"), 5200000),\n                      circle(ring2, as.Date(\"2024-01-08\"), 2975000)) |>\n  mutate(invoice_no = sprintf(\"INV%05d\", row_number())) |>\n  relocate(invoice_no)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(invoices)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  invoice_no seller buyer date       amount\n  <chr>      <chr>  <chr> <date>      <dbl>\n1 INV00001   M01    W10   2023-06-23  94037\n2 INV00002   M12    W29   2023-10-03 163762\n3 INV00003   M06    W36   2024-03-23 141778\n4 INV00004   M06    W31   2023-04-04 314428\n5 INV00005   M05    W20   2023-07-27  46476\n6 INV00006   M03    W24   2024-03-11 213715\n```\n\n\n:::\n:::\n\n\nLet us create a directed graph. The invoice number, date and amount become edge attributes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninv_graph <- graph_from_data_frame(select(invoices, seller, buyer, everything()),\n                                   directed = TRUE)\ninv_graph\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIGRAPH 9cd2533 DN-- 202 1311 -- \n+ attr: name (v/c), invoice_no (e/c), date (e/n), amount (e/n)\n+ edges from 9cd2533 (vertex names):\n [1] M01->W10 M12->W29 M06->W36 M06->W31 M05->W20 M03->W24 M10->W38 M14->W38\n [9] M02->W06 M06->W01 M13->W17 M04->W22 M04->W36 M15->W39 M04->W39 M09->W19\n[17] M02->W09 M08->W14 M14->W17 M06->W26 M04->W12 M13->W15 M14->W28 M04->W26\n[25] M14->W28 M01->W36 M07->W35 M02->W21 M07->W04 M06->W37 M14->W32 M05->W33\n[33] M08->W26 M07->W08 M10->W19 M06->W24 M05->W12 M14->W06 M12->W38 M10->W19\n[41] M15->W24 M01->W06 M14->W05 M12->W14 M15->W36 M06->W39 M15->W36 M06->W36\n[49] M07->W26 M15->W23 M04->W25 M05->W25 M15->W19 M07->W03 M01->W30 M11->W06\n[57] M06->W31 M13->W26 M13->W18 M12->W37 M09->W06 M09->W31 M03->W32 M13->W21\n+ ... omitted several edges\n```\n\n\n:::\n:::\n\n\n**Strongly connected components.** In a directed graph, a *strongly connected component* is a group of vertices in which each vertex can reach every other *following the arrows*. A vertex which is not part of any cycle forms a component on its own. So components of more than one vertex contain cycles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscc <- components(inv_graph, mode = \"strong\")\ntable(scc$csize)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   3   4 \n195   1   1 \n```\n\n\n:::\n:::\n\n\nAll firms are on their own, except one group of 4 and one group of 3. These are our two rings.\n\n**Pruning sources and sinks.** There is another way to reach the same answer, which also makes big graphs much smaller. A firm which only sells and never buys (a *source*, with in-degree 0) cannot be part of a cycle. Neither can a firm which only buys and never sells (a *sink*, with out-degree 0). So we can delete them. But deleting them may turn other firms into sources or sinks, so we repeat until nothing more can be deleted. This is the directed version of dropping leaf nodes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npruned <- inv_graph\nrepeat {\n  drop <- V(pruned)[degree(pruned, mode = \"in\") == 0 | degree(pruned, mode = \"out\") == 0]\n  if (length(drop) == 0) break\n  pruned <- delete_vertices(pruned, drop)\n}\npruned\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIGRAPH 9cd8ca0 DN-- 7 12 -- \n+ attr: name (v/c), invoice_no (e/c), date (e/n), amount (e/n)\n+ edges from 9cd8ca0 (vertex names):\n [1] W23 ->R063 W07 ->R015 R015->R088 R088->W23  W23 ->W07  W07 ->R015\n [7] R015->R088 R088->W23  W23 ->W07  R040->R121 R121->R063 R063->R040\n```\n\n\n:::\n:::\n\n\nOut of the 202 firms which traded during the year, only 7 remain. Every one of them is part of a cycle.\n\n**Listing the cycles.** Now `simple_cycles()` lists each cycle. Since the first ring went round twice, there are two invoices for each of its links. So we first combine repeated edges into one with `simplify()`, to list each ring only once.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrings <- simple_cycles(simplify(pruned))\nlapply(rings$vertices, names)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] \"W23\"  \"W07\"  \"R015\" \"R088\"\n\n[[2]]\n[1] \"R063\" \"R040\" \"R121\"\n```\n\n\n:::\n:::\n\n\nLet us pull out the invoices of these rings, and look at their dates and amounts. Note that we keep only the invoices where the seller and the buyer belong to the *same* ring. The two rings may also have genuine dealings with each other, which are not part of any cycle.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nring_firms <- names(scc$membership)[scc$membership %in% which(scc$csize > 1)]\n\n# Invoices where the seller and buyer are in the same ring\nring_invoices <- invoices |>\n  filter(seller %in% ring_firms, buyer %in% ring_firms) |>\n  filter(scc$membership[seller] == scc$membership[buyer]) |>\n  arrange(date)\nring_invoices\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 5\n   invoice_no seller buyer date        amount\n   <chr>      <chr>  <chr> <date>       <dbl>\n 1 INV01301   W07    R015  2023-09-11 4855941\n 2 INV01302   R015   R088  2023-09-13 4887598\n 3 INV01303   R088   W23   2023-09-15 4891067\n 4 INV01304   W23    W07   2023-09-17 4898134\n 5 INV01305   W07    R015  2023-11-20 5241151\n 6 INV01306   R015   R088  2023-11-22 5277501\n 7 INV01307   R088   W23   2023-11-24 5303338\n 8 INV01308   W23    W07   2023-11-26 5324791\n 9 INV01309   R040   R121  2024-01-08 2975970\n10 INV01310   R121   R063  2024-01-10 3004580\n11 INV01311   R063   R040  2024-01-12 3020018\n```\n\n\n:::\n:::\n\n\nThe pattern is unmistakable. The same amount, a little higher each time, goes round the ring within a week. Together these 11 invoices are worth ₹5.0 crore, without any goods moving. @fig-circular shows the rings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# One edge per seller and buyer, with all its invoices in the tooltip\ncirc_edges <- ring_invoices |>\n  group_by(from = seller, to = buyer) |>\n  summarise(label = paste0(\"₹\", round(sum(amount) / 1e5), \" lakh (\", n(), \")\"),\n            title = paste0(invoice_no, \" (\", date, \"), ₹\",\n                           round(amount / 1e5, 2), \" lakh\", collapse = \"<br>\"),\n            .groups = \"drop\")\ncirc_nodes <- tibble(id = ring_firms, label = ring_firms)\n\nvisNetwork(circ_nodes, circ_edges, width = \"100%\", height = \"450px\") |>\n  visIgraphLayout(layout = \"layout_with_kk\", randomSeed = 3) |>\n  visEdges(arrows = \"to\", smooth = list(enabled = TRUE, type = \"curvedCW\", roundness = 0.15),\n           font = list(size = 11, align = \"middle\")) |>\n  visNodes(color = \"orange\") |>\n  visOptions(highlightNearest = TRUE)\n```\n\n::: {#fig-circular .cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-f5a085d9847e1a104593\" style=\"width:100%;height:450px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f5a085d9847e1a104593\">{\"x\":{\"nodes\":{\"id\":[\"W23\",\"W07\",\"R015\",\"R088\",\"R040\",\"R121\",\"R063\"],\"label\":[\"W23\",\"W07\",\"R015\",\"R088\",\"R040\",\"R121\",\"R063\"],\"x\":[1,0.3343944850428759,-0.7070102405199117,0.02092621621713464,-1,-0.6675893957809653,0.07934170155147569],\"y\":[0.35312990625436,1,0.8967598029333017,0.3743047682043068,-0.4144317850681432,-1,-0.7581686901061058]},\"edges\":{\"from\":[\"R015\",\"R040\",\"R063\",\"R088\",\"R121\",\"W07\",\"W23\"],\"to\":[\"R088\",\"R121\",\"R040\",\"W23\",\"R063\",\"R015\",\"W07\"],\"label\":[\"₹102 lakh (2)\",\"₹30 lakh (1)\",\"₹30 lakh (1)\",\"₹102 lakh (2)\",\"₹30 lakh (1)\",\"₹101 lakh (2)\",\"₹102 lakh (2)\"],\"title\":[\"INV01302 (2023-09-13), ₹48.88 lakh<br>INV01306 (2023-11-22), ₹52.78 lakh\",\"INV01309 (2024-01-08), ₹29.76 lakh\",\"INV01311 (2024-01-12), ₹30.2 lakh\",\"INV01303 (2023-09-15), ₹48.91 lakh<br>INV01307 (2023-11-24), ₹53.03 lakh\",\"INV01310 (2024-01-10), ₹30.05 lakh\",\"INV01301 (2023-09-11), ₹48.56 lakh<br>INV01305 (2023-11-20), ₹52.41 lakh\",\"INV01304 (2023-09-17), ₹48.98 lakh<br>INV01308 (2023-11-26), ₹53.25 lakh\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\",\"physics\":false,\"color\":\"orange\"},\"manipulation\":{\"enabled\":false},\"edges\":{\"arrows\":\"to\",\"font\":{\"size\":11,\"align\":\"middle\"},\"smooth\":{\"enabled\":true,\"type\":\"curvedCW\",\"roundness\":0.15}},\"physics\":{\"stabilization\":false}},\"groups\":null,\"width\":\"100%\",\"height\":\"450px\",\"idselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"igraphlayout\":{\"type\":\"square\"},\"highlight\":{\"enabled\":true,\"hoverNearest\":false,\"degree\":1,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nCircular trading. Each arrow shows the total invoiced from a seller to a buyer, with the number of invoices in brackets. Hover for details.\n:::\n:::\n\n\nWhat next? The auditor would ask the GST office for the e-way bills and transport records of these invoices, and check the input tax credit claimed on them. The bank statements of the firms, where available, would show whether money really changed hands.\n\n::: callout-warning\n## Caution\n\nNot every cycle is a fraud. Goods may be returned, or two firms may genuinely buy different goods from each other. Look at the amounts, the dates, the goods described, and whether there is any proof of movement of goods, like e-way bills or transport receipts. Circular trading usually shows nearly equal amounts going round quickly, often between firms with few other transactions.\n:::\n\n## Audit use case 4, vendors linked with employees {#sec-net-empvendor}\n\nA vendor which is secretly owned or controlled by an employee of the organisation is a classic conflict of interest. The employee may push its bills, approve inflated rates, or pass on inside information. Such a link usually leaves traces in the data. The employee and the vendor may share a bank account, a mobile number or an address. Sometimes the link is indirect, through a relative or a third firm.\n\nThis is the same problem as use case 1, but across *two* masters. Let us create an employee master of 150 employees and a vendor master of 80 vendors, each with a bank account, a mobile number and an address. We have planted three links.\n\n- Vendor `V023` has the same bank account as employee `E107`.\n- Vendor `V051` has the same address as employee `E033`.\n- Vendor `V064` shares a mobile number with vendor `V012`, whose address is the same as that of employee `E088`. This is an indirect link, two steps away.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the employee and vendor masters\"}\nset.seed(31)\nemp <- tibble(\n  emp_id  = sprintf(\"E%03d\", 1:150),\n  bank_ac = rand_acct(150),\n  mobile  = rand_mobile(150),\n  address = paste(\"H.No.\", sample(1:999, 150),\n                  sample(c(\"Sector 4\", \"Civil Lines\", \"Model Town\", \"Gandhi Nagar\",\n                           \"Shastri Nagar\"), 150, TRUE))\n)\nven <- tibble(\n  vendor_id = sprintf(\"V%03d\", 1:80),\n  bank_ac   = rand_acct(80),\n  mobile    = rand_mobile(80),\n  address   = paste(\"Shop\", sample(1:300, 80),\n                    sample(c(\"Main Bazar\", \"Industrial Area\", \"Station Road\"), 80, TRUE))\n)\n\n# Planted links\nven$bank_ac[23] <- emp$bank_ac[107]\nven$address[51] <- emp$address[33]\nven$mobile[64]  <- ven$mobile[12]\nven$address[12] <- emp$address[88]\n```\n:::\n\n\nWe stack both masters together and pivot them longer. Then we prefix the IDs and keep only the shared IDs, exactly as in use case 1. In real data, addresses must first be cleaned and standardised, as discussed in @sec-dup and @sec-strng-names. Two more links are worth adding where the data has them. The first is the email ID, after normalising Gmail dot and plus aliases. The second is the PAN embedded in each vendor's GSTIN (characters 3 to 12). It may match the PAN of an employee or a relative. Both are explained in @sec-regex-validate, where three \"different\" vendors turned out to share one Gmail box.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nev_long <- bind_rows(\n  emp |> rename(entity = emp_id),\n  ven |> rename(entity = vendor_id)\n) |>\n  pivot_longer(-entity, names_to = \"id_type\", values_to = \"value\") |>\n  mutate(id_node = paste(id_type, value, sep = \":\")) |>\n  add_count(id_node) |>\n  filter(n > 1)\n\nev_graph <- graph_from_data_frame(select(ev_long, entity, id_node), directed = FALSE)\n```\n:::\n\n\nNow we find the components which contain *both* an employee and a vendor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomponents(ev_graph)$membership |>\n  stack() |>\n  set_names(c(\"group\", \"node\")) |>\n  filter(str_detect(node, \"^[EV]\\\\d\")) |>\n  group_by(group) |>\n  filter(any(str_starts(node, \"E\")), any(str_starts(node, \"V\"))) |>\n  summarise(entities = paste(sort(as.character(node)), collapse = \", \"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  group entities        \n  <dbl> <chr>           \n1     1 E033, V051      \n2     2 E088, V012, V064\n3     3 E107, V023      \n```\n\n\n:::\n:::\n\n\nAll three planted links are found, including the indirect one. To explain *how* a vendor is linked to an employee, we use `shortest_paths()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshortest_paths(ev_graph, from = \"V064\", to = \"E088\")$vpath[[1]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n+ 5/11 vertices, named, from 9ced086:\n[1] V064                           mobile:7220817946             \n[3] V012                           address:H.No. 912 Gandhi Nagar\n[5] E088                          \n```\n\n\n:::\n:::\n\n\nThe path reads like the finding itself. Vendor V064 has the same mobile number as vendor V012, which has the same address as employee E088. @fig-empven shows the links. For each link, the auditor would next list the bills of the vendor that the employee dealt with, and their total in rupees. The office would then be asked to explain the link, and whether the employee had declared it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nev_vis <- toVisNetworkData(ev_graph)\nev_vis$nodes <- ev_vis$nodes |>\n  mutate(group = case_when(str_starts(id, \"E\") ~ \"Employee\",\n                           str_starts(id, \"V\") ~ \"Vendor\",\n                           TRUE ~ \"Shared detail\"),\n         label = if_else(group == \"Shared detail\", \"\", id),\n         title = id)\n\nvisNetwork(ev_vis$nodes, ev_vis$edges, width = \"100%\", height = \"400px\") |>\n  visGroups(groupname = \"Employee\", color = \"tomato\", shape = \"dot\") |>\n  visGroups(groupname = \"Vendor\", color = \"steelblue\", shape = \"dot\") |>\n  visGroups(groupname = \"Shared detail\", color = \"grey\", shape = \"square\", size = 10) |>\n  visOptions(highlightNearest = TRUE) |>\n  visLegend()\n```\n\n::: {#fig-empven .cell-output-display}\n\n```{=html}\n<div id=\"htmlwidget-ff21357b7f85c75364e8\" style=\"width:100%;height:400px;\" class=\"visNetwork html-widget\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-ff21357b7f85c75364e8\">{\"x\":{\"nodes\":{\"id\":[\"E033\",\"E088\",\"E107\",\"V012\",\"V023\",\"V051\",\"V064\",\"address:H.No. 140 Civil Lines\",\"address:H.No. 912 Gandhi Nagar\",\"bank_ac:85304330681\",\"mobile:7220817946\"],\"label\":[\"E033\",\"E088\",\"E107\",\"V012\",\"V023\",\"V051\",\"V064\",\"\",\"\",\"\",\"\"],\"group\":[\"Employee\",\"Employee\",\"Employee\",\"Vendor\",\"Vendor\",\"Vendor\",\"Vendor\",\"Shared detail\",\"Shared detail\",\"Shared detail\",\"Shared detail\"],\"title\":[\"E033\",\"E088\",\"E107\",\"V012\",\"V023\",\"V051\",\"V064\",\"address:H.No. 140 Civil Lines\",\"address:H.No. 912 Gandhi Nagar\",\"bank_ac:85304330681\",\"mobile:7220817946\"]},\"edges\":{\"from\":[\"E033\",\"E088\",\"E107\",\"V012\",\"V012\",\"V023\",\"V051\",\"V064\"],\"to\":[\"address:H.No. 140 Civil Lines\",\"address:H.No. 912 Gandhi Nagar\",\"bank_ac:85304330681\",\"mobile:7220817946\",\"address:H.No. 912 Gandhi Nagar\",\"bank_ac:85304330681\",\"address:H.No. 140 Civil Lines\",\"mobile:7220817946\"]},\"nodesToDataframe\":true,\"edgesToDataframe\":true,\"options\":{\"width\":\"100%\",\"height\":\"100%\",\"nodes\":{\"shape\":\"dot\"},\"manipulation\":{\"enabled\":false},\"groups\":{\"Employee\":{\"color\":\"tomato\",\"shape\":\"dot\"},\"Vendor\":{\"color\":\"steelblue\",\"shape\":\"dot\"},\"useDefaultGroups\":true,\"Shared detail\":{\"color\":\"grey\",\"shape\":\"square\",\"size\":10}}},\"groups\":[\"Employee\",\"Vendor\",\"Shared detail\"],\"width\":\"100%\",\"height\":\"400px\",\"idselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"useLabels\":true,\"main\":\"Select by id\"},\"byselection\":{\"enabled\":false,\"style\":\"width: 150px; height: 26px\",\"multiple\":false,\"hideColor\":\"rgba(200,200,200,0.5)\",\"highlight\":false},\"main\":null,\"submain\":null,\"footer\":null,\"background\":\"rgba(0, 0, 0, 0)\",\"highlight\":{\"enabled\":true,\"hoverNearest\":false,\"degree\":1,\"algorithm\":\"all\",\"hideColor\":\"rgba(200,200,200,0.5)\",\"labelOnly\":true},\"collapse\":{\"enabled\":false,\"fit\":false,\"resetHighlight\":true,\"clusterOptions\":null,\"keepCoord\":true,\"labelSuffix\":\"(cluster)\"},\"legend\":{\"width\":0.2,\"useGroups\":true,\"position\":\"left\",\"ncol\":1,\"stepX\":100,\"stepY\":100,\"zoom\":true}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nEmployees (red) linked with vendors (blue) through shared details\n:::\n:::\n\n\n::: callout-tip\n## Audit tip\n\nExtend the employee master with the details of close relatives, where these are available from declarations, nominations or pension papers. Many conflicts of interest run through a spouse, a son or a brother-in-law, not through the employee directly.\n:::\n\n## Tips for working with big networks\n\nReal audit data has lakhs of records. A network built carelessly from such data can be too big to analyse, or full of false links. Here are some tips which help.\n\n**1. Drop the leaf nodes.** Most IDs belong to only one record. In the graph, these are leaves, vertices with only one edge, and they can never link two records. Dropping them shrinks the graph enormously without changing the answer. We can drop them either *before* building the graph, or *after*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Before building the graph, with dplyr\nedges_shared <- edges_long |>\n  add_count(id_node) |>\n  filter(n > 1)\n\n# After building the graph, with igraph.\n# Delete ID vertices with one edge, then records left with no edge\ng <- delete_vertices(g, V(g)[degree(g) == 1 & str_detect(name, \":\")])\ng <- delete_vertices(g, V(g)[degree(g) == 0])\n```\n:::\n\n\nIn a directed graph where we look for cycles, we drop sources and sinks repeatedly, as we did in use case 3. For an undirected graph where we look for tightly knit groups, the same idea is the *k-core*. The 2-core is what remains after repeatedly removing all vertices with fewer than 2 edges. `coreness()` gives the core number of each vertex, so `induced_subgraph(g, V(g)[coreness(g) >= 2])` keeps the 2-core.\n\n**2. Prefix every ID with its type.** Write `mobile:9876543210`, not `9876543210`. Otherwise two different kinds of ID which happen to have the same value become one vertex, and create false links.\n\n**3. Look at the most connected IDs first, and remove junk values.** Some values are only placeholders, like `9999999999`, `0000000000`, `NA`, `test@gmail.com`, `XXXXX0000X`, or the address of the office itself. Such a value links hundreds of unrelated records into one giant group. Always run `count(id_node, sort = TRUE)` before building the graph. Remove the junk values, and keep the genuine hubs aside for separate examination.\n\n**4. Clean before you connect.** `9876543210`, `+91 98765 43210` and `09876543210` are the same mobile number. `r.kumar@gmail.com` and `rkumar+bids@gmail.com` are the same Gmail box. Standardise IDs before building the graph, with the functions of @sec-strng and @sec-regex-validate, like `clean_mobile()` and `normalise_email()`. Otherwise real links are missed.\n\n**5. Validate before you connect.** An ID in the wrong format, or with a wrong check digit, cannot be a genuine shared ID. A mistyped Aadhaar or GSTIN may by chance equal someone else's, and create a false link. Run the format and check digit tests of @sec-regex-validate and @sec-checkdigits first. Keep the invalid IDs out of the graph, and report them separately as data quality findings.\n\n**6. Work with components, not with the whole graph.** Use `components()` to split the graph, and then study the components of interest one at a time with `induced_subgraph()`. Sort them by size. Groups of 2 are usually families or genuine. Very large groups usually mean a junk value is still present.\n\n**7. Beware of bipartite projection with hubs.** When we project a bipartite graph, an ID shared by $d$ records creates $d(d-1)/2$ edges. One junk value shared by 10,000 records would create about five crore edges. Remove junk values and big hubs before projecting.\n\n**8. Draw only what matters, and draw it fast.** Plot a component or an ego network, not the whole graph. For `visNetwork`, use `visIgraphLayout()`, so that the layout is calculated once in R and the browser does not have to run its slow physics simulation. Keep labels short, and put details in the `title` (tooltip).\n\n**9. Keep the record keys and amounts.** Keep the original record IDs, invoice numbers, amounts and dates as attributes of vertices and edges. Every finding has to be traced back to the documents, and quantified in rupees.\n\n::: callout-tip\n## Share the network\n\n`visSave(network, file = \"ring.html\")` saves an interactive network as a single HTML file. It can be emailed to the audit team or attached to the working papers, and opened in any browser without R.\n:::\n\n## A suggested workflow\n\n1. **Decide the vertices and edges.** What are the entities (persons, firms, accounts), and what links them (shared IDs, bids, invoices)? Is the graph directed?\n2. **Prepare the data.** Clean, standardise and validate the IDs (@sec-regex-validate), prefix them with their type, and pivot to one row per link.\n3. **Look at the most connected IDs.** Remove junk values. Note the genuine hubs.\n4. **Reduce the graph.** Drop leaves, sources and sinks, or take the k-core, depending on the question.\n5. **Find the structure.** Components for related entities, communities for groups, cycles for circular flows, shortest paths to explain a link, centrality for key players.\n6. **Visualise** the parts of interest with `visNetwork`, and share them.\n7. **Go back to the records.** Verify every lead with documents, and quantify it.\n\n::: callout-important\n## Remember\n\nA link in a network shows that two records share something. It does not show *why*. Family members share mobiles, neighbours share addresses, and specialised firms meet in the same tenders. A network gives *leads*, not *findings*. Every lead must be verified with documents, and where needed, in the field.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `pivot_longer()` | tidyr | Turns ID columns into one row per record and ID |\n| `across()` | dplyr | Converts all the ID columns to text in one step |\n| `count()`, `add_count()` | dplyr | Counts records per ID, to find hubs and junk values and to drop leaf IDs |\n| `stack()` | utils | Turns a named vector, like the component membership, into a data frame |\n| `set_names()` | purrr | Names the columns of a data frame inside a pipe |\n| `right_join()` | dplyr | Attaches the group number back to the original records |\n| `graph_from_data_frame()` | igraph | Builds a graph from a data frame of links |\n| `components()` | igraph | Connected components (`mode = \"strong\"` for directed cycles) |\n| `induced_subgraph()` | igraph | Keeps one group of vertices with the edges between them |\n| `bipartite_projection()` | igraph | Turns a bipartite graph into a graph of one type of vertex |\n| `cluster_louvain()`, `sizes()` | igraph | Finds communities, like cartels, and their sizes |\n| `degree()`, `delete_vertices()`, `delete_edges()` | igraph | Find and drop leaves, sources, sinks and weak edges |\n| `coreness()` | igraph | Core number of each vertex, to take the k-core |\n| `simple_cycles()`, `simplify()` | igraph | Lists the cycles of a graph, after merging repeated edges |\n| `shortest_paths()` | igraph | Shows how two entities are linked |\n| `toVisNetworkData()` | visNetwork | Converts an igraph object into nodes and edges data frames |\n| `visNetwork()`, `visGroups()`, `visOptions()`, `visLegend()` | visNetwork | Interactive network plots |\n| `visEdges()`, `visNodes()` | visNetwork | Set the look of all edges or all vertices, like arrows and colour |\n| `visIgraphLayout()`, `visSave()` | visNetwork | Fast layout for big networks, and saving as HTML |\n\n: Functions used in this chapter {#tbl-netauditfunctions}\n",
    "supporting": [
      "13-Network-applying-network-analysis-in-audit-fraud_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"site_libs/vis-9.1.0/vis-network.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/vis-9.1.0/vis-network.min.js\"></script>\n<script src=\"site_libs/visNetwork-binding-2.1.4/visNetwork.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}