{
  "hash": "af98a589a0f579c1165869d2eb440153",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Duplicate Detection {#sec-dup}\n\nDuplicate detection is one of the oldest and most useful checks in audit. It is simple to understand. It is also simple to run. Yet it often gives the quickest results in a fraud or forensic audit.\n\nA duplicate payment means money has gone out twice for the same thing. Sometimes it is an honest mistake. Sometimes it is not. In either case, it is a loss to the organisation, and the auditor must find it.\n\nDuplicates may point to many kinds of problems. A few common ones are:\n\n-   **Double billing.** A supplier submits the same invoice twice, and both get paid.\n-   **Expense reimbursement fraud.** An employee claims the same bill twice, perhaps once in each of two months.\n-   **Payroll fraud.** The same person appears twice on the pay roll, or a \"ghost\" employee shares the bank account of a real one.\n-   **Beneficiary fraud.** In welfare schemes, one person registers twice to get the benefit twice.\n-   **Data entry errors and system glitches.** A record is keyed in twice, or an interface between two systems posts the same transaction again.\n\nIn this chapter we will learn how to find such duplicates in R. We will start with the simplest case, where two records are exactly the same. We will then move to cases where records are *almost* the same. These are harder to find, and they are usually the more interesting ones for an auditor.\n\n## Prerequisites\n\nWe will use three packages in this chapter. `tidyverse` gives us `dplyr` and `stringr`. `janitor` gives us a very handy function `get_dupes()`. `stringdist` will help us find names which are similar but not identical.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(janitor)\nlibrary(stringdist)\n```\n:::\n\n\n## Our sample data\n\nTo learn the tests, we need some data where we already know the answers. So let us create a small *payment register* of an imaginary office for the financial year 2024-25. It has about 170 payments made to 14 vendors. We have deliberately planted a few duplicates in it. Our job in this chapter is to find all of them using R.\n\nThe code to create the data is given below. New readers need not worry about this code right now. You may expand it later, once you are comfortable with `dplyr`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the sample payment register\"}\nset.seed(2025)\n\n# Vendor master\nvendors <- tibble(\n  vendor_id   = sprintf(\"V%03d\", 1:14),\n  vendor_name = c(\"Sharma Traders\", \"Gupta Enterprises\", \"Bharat Stationers\",\n                  \"Kaveri Suppliers\", \"Laxmi Electricals\", \"National Printers\",\n                  \"Om Sai Caterers\", \"Patel Hardware\", \"Rajdhani Computers\",\n                  \"Shree Ganesh Transport\", \"Ashok Estates\", \"Verma & Sons\",\n                  \"Sharma Trader's\", \"Guptha Enterprises\")\n)\n\n# 150 ordinary payments\nn <- 150\npayments <- tibble(\n  vendor_id    = sample(vendors$vendor_id[c(1:10, 12)], n, replace = TRUE),\n  invoice_no   = paste0(\"INV-\", sample(1000:9999, n)),\n  invoice_date = as.Date(\"2024-04-01\") + sample(0:330, n, replace = TRUE),\n  amount       = round(runif(n, 2000, 200000))\n)\n\n# Monthly office rent. Same amount every month, but genuine.\nrent <- tibble(\n  vendor_id    = \"V011\",\n  invoice_no   = paste0(\"AE/RENT/\", 1:12),\n  invoice_date = seq(as.Date(\"2024-04-01\"), by = \"month\", length.out = 12),\n  amount       = 45000\n)\n\n# Planted case 1. Invoices paid twice (one of them thrice).\npaid_again <- payments[c(12, 47, 47, 101), ]\n\n# Planted case 2. Same invoice keyed in again with a slightly different number.\nretyped <- payments[c(23, 88), ] |>\n  mutate(invoice_no = c(str_remove(invoice_no[1], \"-\"),\n                        str_to_lower(invoice_no[2])))\n\n# Planted case 3. Same bill raised again with a suffix \"A\", two days later.\nsuffixed <- payments[64, ] |>\n  mutate(invoice_no   = paste0(invoice_no, \"A\"),\n         invoice_date = invoice_date + 2)\n\n# Planted case 4. Same invoice paid to a look-alike vendor.\nlookalike <- payments |>\n  filter(vendor_id %in% c(\"V001\", \"V002\")) |>\n  slice(c(2, 5)) |>\n  mutate(vendor_id = if_else(vendor_id == \"V001\", \"V013\", \"V014\"))\n\npayments <- bind_rows(payments, rent, paid_again, retyped, suffixed, lookalike) |>\n  mutate(payment_date = invoice_date + sample(7:45, n(), replace = TRUE)) |>\n  arrange(payment_date) |>\n  mutate(voucher_no = sprintf(\"PV-%04d\", row_number())) |>\n  left_join(vendors, by = \"vendor_id\") |>\n  select(voucher_no, payment_date, vendor_id, vendor_name,\n         invoice_no, invoice_date, amount)\n\n# Planted case 5. Two rows repeated in the data extract itself.\npayments <- bind_rows(payments, payments[c(30, 90), ]) |>\n  arrange(voucher_no)\n```\n:::\n\n\nLet us have a look at the first few rows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(payments)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  voucher_no payment_date vendor_id vendor_name   invoice_no invoice_date amount\n  <chr>      <date>       <chr>     <chr>         <chr>      <date>        <dbl>\n1 PV-0001    2024-04-18   V011      Ashok Estates AE/RENT/1  2024-04-01    45000\n2 PV-0002    2024-04-21   V005      Laxmi Electr… INV-6900   2024-04-01   169386\n3 PV-0003    2024-05-02   V009      Rajdhani Com… INV-5628   2024-04-20   171411\n4 PV-0004    2024-05-07   V008      Patel Hardwa… INV-4836   2024-04-27    43171\n5 PV-0005    2024-05-11   V009      Rajdhani Com… INV-2321   2024-04-19    97584\n6 PV-0006    2024-05-13   V004      Kaveri Suppl… INV-9114   2024-04-27     2354\n```\n\n\n:::\n:::\n\n\nEach row is one payment. The columns are:\n\n-   `voucher_no` is the payment voucher number, given by the office.\n-   `payment_date` is the date on which payment was made.\n-   `vendor_id` and `vendor_name` tell us who was paid.\n-   `invoice_no` and `invoice_date` come from the bill submitted by the vendor.\n-   `amount` is the amount paid, in rupees.\n\n## What do we mean by a duplicate?\n\nThis question looks simple. But it is the most important step of the whole exercise. Two records are \"duplicates\" only with respect to some columns, which we choose. These chosen columns are called the **key**.\n\nConsider two payments to Sharma Traders. Both are for ₹ 25,000. Are they duplicates? We cannot say yet. If they also have the same invoice number, they almost certainly are. If the invoice numbers differ and the payments are a month apart, they are probably two genuine supplies.\n\nSo, before running any test, the auditor must decide the key. Forensic auditors commonly use the kinds of tests summarised in @tbl-duptests.\n\n| Test | What matches | What differs | Typical finding |\n|------------------|------------------|------------------|-------------------|\n| Exact duplicate | Every column | Nothing | Same row repeated in data, or keyed in twice |\n| Same-Same-Same | All key columns, say vendor, invoice number and amount | Other columns like voucher number and date | Same invoice paid twice |\n| Same-Same-Different | Two key columns, say vendor and amount | The third key column, say invoice number | Same bill re-submitted with a new or altered number |\n| Fuzzy duplicate | Values are *similar*, not equal | Spelling, case, punctuation | Look-alike vendors, retyped invoice numbers |\n\n: Types of duplicate tests {#tbl-duptests}\n\nThe names *Same-Same-Same* and *Same-Same-Different* are commonly used in forensic analytics literature. They are easy to remember. Three key columns are compared. The name tells us which of the three should match and which should not.\n\n## Exact duplicates\n\nLet us begin with the easiest case. Are there rows which are the same in every column?\n\nBase R has a function `duplicated()`, which we met in @sec-basefuns. It returns `TRUE` for every row which has already appeared earlier in the data. So summing it up gives the number of extra copies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(duplicated(payments))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\nThere are two such rows. But `duplicated()` marks only the *second* copy as `TRUE`. The first copy is marked `FALSE`. An auditor usually wants to see both copies side by side. For this, `get_dupes()` from `janitor` is much more convenient. If we do not give it any column names, it uses all columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npayments |>\n  get_dupes()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 8\n  voucher_no payment_date vendor_id vendor_name   invoice_no invoice_date amount\n  <chr>      <date>       <chr>     <chr>         <chr>      <date>        <dbl>\n1 PV-0030    2024-07-08   V007      Om Sai Cater… INV-2410   2024-06-07    41810\n2 PV-0030    2024-07-08   V007      Om Sai Cater… INV-2410   2024-06-07    41810\n3 PV-0090    2024-10-20   V001      Sharma Trade… INV-7755   2024-09-29   103923\n4 PV-0090    2024-10-20   V001      Sharma Trade… INV-7755   2024-09-29   103923\n# ℹ 1 more variable: dupe_count <int>\n```\n\n\n:::\n:::\n\n\nThe output shows each duplicate row along with a new column `dupe_count`. This column tells us how many times that row appears.\n\nNote that even the voucher numbers are the same here. A real office would never issue the same voucher number twice. So these are not two payments. These are the *same* payment appearing twice in our data. This usually happens when data is exported from a system, or when two files are merged carelessly.\n\n::: callout-tip\n## Audit tip\n\nAlways check exact duplicates first, and *before* any other analysis. If the data itself has repeated rows, every total, average and count you calculate will be wrong. Ask the data owner why the rows are repeated. Do not just delete them silently. The answer may itself be an audit finding about the quality of the IT system.\n:::\n\nOnce we are satisfied with the reason, we may remove the repeated rows using `dplyr::distinct()`. It keeps only the first copy of each row.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npayments <- payments |>\n  distinct()\n\nnrow(payments)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 171\n```\n\n\n:::\n:::\n\n\n## Same-Same-Same test\n\nNow let us look for the real problem. Has any invoice been paid more than once?\n\nFor this, our key will be three columns. These are `vendor_id`, `invoice_no` and `amount`. If all three match, the same bill has been paid again. Voucher numbers and payment dates will be different, of course, because these are two separate payments.\n\nWe just have to pass the key columns to `get_dupes()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsss <- payments |>\n  get_dupes(vendor_id, invoice_no, amount)\n\nsss\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 8\n  vendor_id invoice_no amount dupe_count voucher_no payment_date vendor_name    \n  <chr>     <chr>       <dbl>      <int> <chr>      <date>       <chr>          \n1 V006      INV-3315    50572          3 PV-0069    2024-09-03   National Print…\n2 V006      INV-3315    50572          3 PV-0071    2024-09-05   National Print…\n3 V006      INV-3315    50572          3 PV-0079    2024-09-22   National Print…\n4 V005      INV-2863   135555          2 PV-0087    2024-10-16   Laxmi Electric…\n5 V005      INV-2863   135555          2 PV-0088    2024-10-19   Laxmi Electric…\n6 V005      INV-4296   172125          2 PV-0032    2024-07-10   Laxmi Electric…\n7 V005      INV-4296   172125          2 PV-0035    2024-07-15   Laxmi Electric…\n# ℹ 1 more variable: invoice_date <date>\n```\n\n\n:::\n:::\n\n\nWe see three invoices here. One invoice of National Printers has been paid three times. Two invoices of Laxmi Electricals have been paid twice each. Look at the `payment_date` column. In one case the second payment was made only two days after the first. In real life, such cases need a closer look at the approval process.\n\n### How much money is involved?\n\nAn audit observation is incomplete without the money value. In each group, one payment was correct and the rest were extra. So the excess payment is the amount multiplied by one less than the number of times it was paid.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsss |>\n  summarise(\n    times_paid = n(),\n    amount = first(amount),\n    excess_paid = (n() - 1) * first(amount),\n    .by = c(vendor_id, invoice_no)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  vendor_id invoice_no times_paid amount excess_paid\n  <chr>     <chr>           <int>  <dbl>       <dbl>\n1 V006      INV-3315            3  50572      101144\n2 V005      INV-2863            2 135555      135555\n3 V005      INV-4296            2 172125      172125\n```\n\n\n:::\n:::\n\n\nWe may add a further `summarise()` to get the grand total. That total is the figure which goes into the audit observation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsss |>\n  summarise(excess_paid = (n() - 1) * first(amount), .by = c(vendor_id, invoice_no)) |>\n  summarise(total_excess = sum(excess_paid))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  total_excess\n         <dbl>\n1       408824\n```\n\n\n:::\n:::\n\n\nSo, in our small data, ₹ 4,08,824 has been paid in excess on just three invoices.\n\n::: callout-note\n## Choosing the key wisely\n\nWhy did we not use `invoice_date` in the key? We could have. But dates are often entered differently by different clerks, so adding more columns to the key can make us *miss* duplicates. On the other hand, too few columns produce too many false alarms. Start with a small key. Then add columns if the output is too long to examine.\n:::\n\n## Same-Same-Different test\n\nA clever fraudster knows that most accounting software rejects an invoice number already entered for a vendor. So they change the invoice number a little. They may add a suffix, or change one digit. The Same-Same-Same test above will not catch this.\n\nThis is where the Same-Same-Different test helps. Here we look for records where the **vendor** and the **amount** are the same, but the **invoice number is different**.\n\nIn `dplyr`, we can do this with `filter()` and its `.by` argument, which we learnt in @sec-DPLYRR. Inside each group of vendor and amount, we keep the group only if it has more than one distinct invoice number. The function `n_distinct()` counts the distinct values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nssd <- payments |>\n  filter(n_distinct(invoice_no) > 1, .by = c(vendor_id, amount)) |>\n  arrange(vendor_id, amount, invoice_date)\n\nssd |>\n  select(voucher_no, vendor_name, invoice_no, invoice_date, amount)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 18 × 5\n   voucher_no vendor_name        invoice_no invoice_date amount\n   <chr>      <chr>              <chr>      <date>        <dbl>\n 1 PV-0139    Gupta Enterprises  INV-9665   2025-01-10    29117\n 2 PV-0155    Gupta Enterprises  INV9665    2025-01-10    29117\n 3 PV-0160    Rajdhani Computers INV-8850   2025-02-15    93149\n 4 PV-0171    Rajdhani Computers INV-8850A  2025-02-17    93149\n 5 PV-0066    Rajdhani Computers inv-3601   2024-08-14   127872\n 6 PV-0077    Rajdhani Computers INV-3601   2024-08-14   127872\n 7 PV-0001    Ashok Estates      AE/RENT/1  2024-04-01    45000\n 8 PV-0008    Ashok Estates      AE/RENT/2  2024-05-01    45000\n 9 PV-0034    Ashok Estates      AE/RENT/3  2024-06-01    45000\n10 PV-0047    Ashok Estates      AE/RENT/4  2024-07-01    45000\n11 PV-0058    Ashok Estates      AE/RENT/5  2024-08-01    45000\n12 PV-0078    Ashok Estates      AE/RENT/6  2024-09-01    45000\n13 PV-0099    Ashok Estates      AE/RENT/7  2024-10-01    45000\n14 PV-0116    Ashok Estates      AE/RENT/8  2024-11-01    45000\n15 PV-0133    Ashok Estates      AE/RENT/9  2024-12-01    45000\n16 PV-0152    Ashok Estates      AE/RENT/10 2025-01-01    45000\n17 PV-0149    Ashok Estates      AE/RENT/11 2025-02-01    45000\n18 PV-0169    Ashok Estates      AE/RENT/12 2025-03-01    45000\n```\n\n\n:::\n:::\n\n\nLet us read this output carefully, group by group.\n\n1.  **Gupta Enterprises, ₹ 29,117.** Invoice numbers are `INV-9665` and `INV9665`. Only the hyphen is missing. This is clearly the same invoice entered again.\n2.  **Rajdhani Computers, ₹ 93,149.** Invoice numbers are `INV-8850` and `INV-8850A`, dated two days apart. Adding a suffix like \"A\" is a classic way to get a bill paid twice. This needs to be examined with the original documents.\n3.  **Rajdhani Computers, ₹ 1,27,872.** Invoice numbers are `inv-3601` and `INV-3601`. Only the case differs. Again the same invoice.\n4.  **Ashok Estates, ₹ 45,000.** Twelve invoices, one for each month. This is the monthly rent of the office building. It is *not* a duplicate. The same amount is genuinely paid every month.\n\nSo the test has found the real problems. But it has also raised one **false alarm**. This is normal. Every duplicate test produces some false alarms. The auditor's job is to reduce them sensibly and then examine the rest.\n\n### Reducing false alarms with a date window\n\nRent, salary, annual maintenance charges and similar payments repeat by their very nature. But they repeat after a gap, usually a month or more. A bill re-submitted for double payment usually comes within a few days or weeks of the original.\n\nSo let us also calculate how many days have passed since the previous invoice of the same vendor and amount. The function `lag()` gives us the previous value within each group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nssd <- ssd |>\n  mutate(days_since_previous = as.numeric(invoice_date - lag(invoice_date)),\n         .by = c(vendor_id, amount))\n\nssd |>\n  select(vendor_name, invoice_no, invoice_date, amount, days_since_previous)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 18 × 5\n   vendor_name        invoice_no invoice_date amount days_since_previous\n   <chr>              <chr>      <date>        <dbl>               <dbl>\n 1 Gupta Enterprises  INV-9665   2025-01-10    29117                  NA\n 2 Gupta Enterprises  INV9665    2025-01-10    29117                   0\n 3 Rajdhani Computers INV-8850   2025-02-15    93149                  NA\n 4 Rajdhani Computers INV-8850A  2025-02-17    93149                   2\n 5 Rajdhani Computers inv-3601   2024-08-14   127872                  NA\n 6 Rajdhani Computers INV-3601   2024-08-14   127872                   0\n 7 Ashok Estates      AE/RENT/1  2024-04-01    45000                  NA\n 8 Ashok Estates      AE/RENT/2  2024-05-01    45000                  30\n 9 Ashok Estates      AE/RENT/3  2024-06-01    45000                  31\n10 Ashok Estates      AE/RENT/4  2024-07-01    45000                  30\n11 Ashok Estates      AE/RENT/5  2024-08-01    45000                  31\n12 Ashok Estates      AE/RENT/6  2024-09-01    45000                  31\n13 Ashok Estates      AE/RENT/7  2024-10-01    45000                  30\n14 Ashok Estates      AE/RENT/8  2024-11-01    45000                  31\n15 Ashok Estates      AE/RENT/9  2024-12-01    45000                  30\n16 Ashok Estates      AE/RENT/10 2025-01-01    45000                  31\n17 Ashok Estates      AE/RENT/11 2025-02-01    45000                  31\n18 Ashok Estates      AE/RENT/12 2025-03-01    45000                  28\n```\n\n\n:::\n:::\n\n\nFor rent, the gap is around 30 days each time. For the suspicious groups, the gap is zero or two days. Now we keep only those groups where some invoice came within, say, 15 days of the previous one.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nssd |>\n  filter(any(days_since_previous <= 15, na.rm = TRUE), .by = c(vendor_id, amount)) |>\n  select(voucher_no, vendor_name, invoice_no, invoice_date, amount)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  voucher_no vendor_name        invoice_no invoice_date amount\n  <chr>      <chr>              <chr>      <date>        <dbl>\n1 PV-0139    Gupta Enterprises  INV-9665   2025-01-10    29117\n2 PV-0155    Gupta Enterprises  INV9665    2025-01-10    29117\n3 PV-0160    Rajdhani Computers INV-8850   2025-02-15    93149\n4 PV-0171    Rajdhani Computers INV-8850A  2025-02-17    93149\n5 PV-0066    Rajdhani Computers inv-3601   2024-08-14   127872\n6 PV-0077    Rajdhani Computers INV-3601   2024-08-14   127872\n```\n\n\n:::\n:::\n\n\nThe rent payments are gone. Only the three suspicious groups remain.\n\n::: callout-warning\n## Caution\n\nThe window of 15 days is only an example. Choose it according to the business. A fortnightly payment would need a shorter window. A fraudster who knows about this test may also wait for a few weeks before re-submitting the bill. So treat the date window as a way to *rank* cases for examination, not as a final rule.\n:::\n\n### Other combinations\n\nThe Same-Same-Different idea works with any combination of columns. We only have to decide which two should match and which one should differ. For example, let us look for the same invoice number and amount, but paid to **different vendors**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npayments |>\n  filter(n_distinct(vendor_id) > 1, .by = c(invoice_no, amount)) |>\n  arrange(invoice_no) |>\n  select(voucher_no, vendor_id, vendor_name, invoice_no, amount)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  voucher_no vendor_id vendor_name        invoice_no amount\n  <chr>      <chr>     <chr>              <chr>       <dbl>\n1 PV-0111    V002      Gupta Enterprises  INV-8297    29819\n2 PV-0121    V014      Guptha Enterprises INV-8297    29819\n3 PV-0097    V013      Sharma Trader's    INV-8564    93897\n4 PV-0100    V001      Sharma Traders     INV-8564    93897\n```\n\n\n:::\n:::\n\n\nThis is an interesting result. An invoice of *Sharma Traders* has also been paid to *Sharma Trader's*. An invoice of *Gupta Enterprises* has also been paid to *Guptha Enterprises*. These look-alike names have different vendor codes. This is a serious red flag. We will come back to it in @sec-dup-fuzzy.\n\nA few other useful combinations are given in @tbl-ssdmore.\n\n| Same | Same | Different | What it may reveal |\n|----------------|----------------|----------------|-------------------------|\n| Employee | Amount | Claim number | Same medical or travel bill claimed twice |\n| Bank account | Scheme | Beneficiary ID | One person drawing benefit under two IDs |\n| Bank account | Pay month | Employee ID | Ghost employee sharing a real employee's account |\n| Vendor | Invoice number | Amount | Invoice amount altered after first payment |\n\n: Some other Same-Same-Different combinations {#tbl-ssdmore}\n\n## Hidden duplicates, and why cleaning matters\n\nLook again at the groups found by the Same-Same-Different test. `INV-9665` and `INV9665` are the same invoice. So are `inv-3601` and `INV-3601`. But the Same-Same-Same test missed them, because to a computer these strings are different.\n\nThis teaches us an important lesson. **Clean the key columns before testing for duplicates.** For invoice numbers, a simple cleaning would be to\n\n-   convert everything to upper case, and\n-   remove spaces, hyphens, slashes and other punctuation.\n\nWe learnt the required `stringr` functions in @sec-strng. The regular expression `[^A-Z0-9]` means \"any character which is not a capital letter or a digit\". Removing all such characters leaves only letters and digits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npayments <- payments |>\n  mutate(invoice_clean = invoice_no |>\n           str_to_upper() |>\n           str_remove_all(\"[^A-Z0-9]\"))\n\npayments |>\n  get_dupes(vendor_id, invoice_clean, amount) |>\n  select(vendor_id, invoice_no, invoice_clean, amount, dupe_count, voucher_no)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 6\n   vendor_id invoice_no invoice_clean amount dupe_count voucher_no\n   <chr>     <chr>      <chr>          <dbl>      <int> <chr>     \n 1 V006      INV-3315   INV3315        50572          3 PV-0069   \n 2 V006      INV-3315   INV3315        50572          3 PV-0071   \n 3 V006      INV-3315   INV3315        50572          3 PV-0079   \n 4 V002      INV-9665   INV9665        29117          2 PV-0139   \n 5 V002      INV9665    INV9665        29117          2 PV-0155   \n 6 V005      INV-2863   INV2863       135555          2 PV-0087   \n 7 V005      INV-2863   INV2863       135555          2 PV-0088   \n 8 V005      INV-4296   INV4296       172125          2 PV-0032   \n 9 V005      INV-4296   INV4296       172125          2 PV-0035   \n10 V009      inv-3601   INV3601       127872          2 PV-0066   \n11 V009      INV-3601   INV3601       127872          2 PV-0077   \n```\n\n\n:::\n:::\n\n\nNow the Same-Same-Same test finds five invoices instead of three. The two retyped invoices have been caught as well.\n\n::: callout-tip\n## Audit tip\n\nSimilar cleaning applies to other key columns too. Remove spaces from PAN and bank account numbers. Remove leading zeros where the system may or may not store them. Convert names to one case. A few minutes spent on cleaning can bring out duplicates that would otherwise stay hidden.\n:::\n\n## Fuzzy duplicates in names {#sec-dup-fuzzy}\n\nOur last test found two invoices paid to look-alike vendors. Such vendors are often the root of the problem. A fictitious vendor is created with a name very close to a genuine one. Bills of the genuine vendor are then paid again, to the fictitious one. A casual reader of the payment register will not notice the difference.\n\nCleaning alone cannot catch these. *Sharma Traders* and *Sharma Trader's* differ by an apostrophe. *Gupta* and *Guptha* differ by one letter. We need a way to measure how *similar* two names are. We discussed several such measures in @sec-strsim. Here we will use the Jaro-Winkler distance. It is `0` for identical strings and close to `1` for completely different ones.\n\nThe idea is simple. We compare every vendor name in the vendor master with every other vendor name. Then we look at the pairs with the smallest distance.\n\n**Step-1:** Make all possible pairs of vendors. We do this by joining the `vendors` table with itself. But we do not want a vendor paired with itself. We also do not want each pair twice, once as (A, B) and again as (B, A). So we join each vendor only with those vendors whose ID is *greater* than its own. This is an inequality join, which we learnt in @sec-nonequi. The `suffix` argument tells R how to name the columns coming from the two copies of the table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvendor_pairs <- vendors |>\n  inner_join(vendors, by = join_by(vendor_id < vendor_id), suffix = c(\"_1\", \"_2\"))\n\nnrow(vendor_pairs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 91\n```\n\n\n:::\n:::\n\n\nWith 14 vendors, we get 13 + 12 + ... + 1 = 91 pairs.\n\n::: callout-warning\n## Use `inner_join()` here, not `left_join()`\n\nIf we write `left_join()` in the code above, we get 92 rows instead of 91. A left join keeps *every* row of the left table, even when it finds no match. The last vendor, V014, has no vendor with a greater ID. So `left_join()` keeps it anyway, with `NA` in all the `_2` columns. `inner_join()` keeps only the rows which find a match.\n:::\n\n::: callout-tip\n## Why not `cross_join()`?\n\nAnother way is to make *every* combination using `cross_join()`, and then keep the required pairs with `filter(vendor_id_1 < vendor_id_2)`. The result is the same. But `cross_join()` first builds the full table of n × n rows, and then throws away more than half of it. The inequality join builds only the pairs we need. In a test with 6,000 vendors, the inequality join took less than a second, while `cross_join()` and `filter()` took about 11 seconds and needed more than 1 GB of memory along the way.\n:::\n\n**Step-2:** Calculate the distance between the two names in each pair. We convert both names to lower case first, as the measure is case sensitive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvendor_pairs <- vendor_pairs |>\n  mutate(jw_distance = stringdist(tolower(vendor_name_1),\n                                  tolower(vendor_name_2),\n                                  method = \"jw\"))\n```\n:::\n\n\n**Step-3:** Sort the pairs by distance and look at the closest ones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvendor_pairs |>\n  arrange(jw_distance) |>\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  vendor_id_1 vendor_name_1     vendor_id_2 vendor_name_2      jw_distance\n  <chr>       <chr>             <chr>       <chr>                    <dbl>\n1 V002        Gupta Enterprises V014        Guptha Enterprises      0.0185\n2 V001        Sharma Traders    V013        Sharma Trader's         0.0222\n3 V003        Bharat Stationers V009        Rajdhani Computers      0.292 \n4 V001        Sharma Traders    V007        Om Sai Caterers         0.306 \n5 V002        Gupta Enterprises V004        Kaveri Suppliers        0.306 \n```\n\n\n:::\n:::\n\n\nThe first two pairs stand out clearly. Their distance is about 0.02. The next pair is already at about 0.29, and those names have nothing in common. So, in this data, a cut-off of say 0.1 separates suspicious pairs from the rest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvendor_pairs |>\n  filter(jw_distance < 0.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  vendor_id_1 vendor_name_1     vendor_id_2 vendor_name_2      jw_distance\n  <chr>       <chr>             <chr>       <chr>                    <dbl>\n1 V001        Sharma Traders    V013        Sharma Trader's         0.0222\n2 V002        Gupta Enterprises V014        Guptha Enterprises      0.0185\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## How to choose the cut-off?\n\nThere is no fixed rule. Sort the pairs by distance and read down the list. You will usually find a point after which the pairs stop looking alike. Use that point as the cut-off for this data. With large vendor masters, also compare other fields like PAN, GSTIN, bank account, address and mobile number. Two vendors with different names but the same bank account are even more suspicious than look-alike names.\n:::\n\n### Trying other similarity measures\n\nJaro-Winkler is not the only choice. In @sec-strsim we learnt about several other measures. These include Levenshtein distance, Q-grams and Soundex. All of them are available in the same `stringdist()` function. We only change the `method` argument. Let us calculate a few of them on our vendor pairs and compare.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvendor_pairs |>\n  mutate(\n    name_1  = tolower(vendor_name_1),\n    name_2  = tolower(vendor_name_2),\n    lv      = stringdist(name_1, name_2, method = \"lv\"),\n    jw      = stringdist(name_1, name_2, method = \"jw\"),\n    qgram_3 = stringdist(name_1, name_2, method = \"qgram\", q = 3),\n    soundex = stringdist(name_1, name_2, method = \"soundex\")\n  ) |>\n  arrange(jw) |>\n  select(vendor_name_1, vendor_name_2, lv, jw, qgram_3, soundex) |>\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  vendor_name_1     vendor_name_2         lv     jw qgram_3 soundex\n  <chr>             <chr>              <dbl>  <dbl>   <dbl>   <dbl>\n1 Gupta Enterprises Guptha Enterprises     1 0.0185       5       0\n2 Sharma Traders    Sharma Trader's        1 0.0222       3       0\n3 Bharat Stationers Rajdhani Computers    14 0.292       29       1\n4 Sharma Traders    Om Sai Caterers       11 0.306       23       1\n5 Gupta Enterprises Kaveri Suppliers      14 0.306       29       1\n```\n\n\n:::\n:::\n\n\nAll four measures pick out the same two pairs. But each one speaks in its own language. Let us read them one by one.\n\n-   **Levenshtein (`lv`)** counts the number of single-character edits. Both look-alike pairs need just one edit. Other pairs need 11 or more. But this is a *count*, so it depends on the length of the names. One edit in a five-letter name is a big change. One edit in a thirty-letter name is a small one. So the same cut-off does not suit short and long names alike.\n-   **Jaro-Winkler (`jw`)** is always between 0 and 1, whatever the length of the names. This makes it easier to choose a single cut-off. It also gives more weight to the beginning of the string, where people usually make fewer mistakes.\n-   **Q-gram (`qgram_3`)** counts the groups of three consecutive letters which are present in one name but not in the other. Notice that *Gupta* and *Guptha* score 5, though only one letter differs. A single extra letter breaks several three-letter groups at once.\n-   **Soundex (`soundex`)** checks whether two strings *sound* alike in English. It gives only a yes or no answer. `0` means they sound the same and `1` means they do not. It caught both pairs, because *Gupta* and *Guptha* are pronounced the same way.\n\n::: callout-warning\n## Caution with Soundex on long names\n\nSoundex looks only at the first letter and the next few consonant sounds of a string. It ignores everything after that. So long names which merely *begin* alike will also be called a match.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstringdist(\"sharma traders\",\n           c(\"sharma transport\", \"sharma tours\", \"shree traders\"),\n           method = \"soundex\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0 0 1\n```\n\n\n:::\n:::\n\n\nAll three vendors starting with \"Sharma Tr...\" are treated as the same. Soundex works best on single words like surnames. For full names, use it along with another measure, not alone.\n:::\n\n@tbl-simmeasures sums up when each measure is useful in audit work.\n\n| Measure | `method` | Range | Best suited for |\n|----------------|----------------|----------------|-------------------------|\n| Levenshtein | `\"lv\"` | 0 upwards, counts edits | Codes of fixed length, like PAN, GSTIN or invoice numbers |\n| Jaro-Winkler | `\"jw\"` | 0 to 1 | Names of persons and firms, with one common cut-off |\n| Q-gram | `\"qgram\"` | 0 upwards | Longer text like addresses, where words may be rearranged |\n| Soundex | `\"soundex\"` | 0 or 1 | Single words that sound alike, like *Geeta* and *Gita* |\n\n: Choosing a string similarity measure {#tbl-simmeasures}\n\n::: callout-tip\n## Audit tip\n\nA pair flagged by two different measures is a stronger lead than a pair flagged by only one. For example, a pair with a low Jaro-Winkler distance *and* the same Soundex code deserves a closer look first. For more phonetic measures, such as Metaphone and Double Metaphone, refer back to @sec-strsim.\n:::\n\nComparing every name with every other name creates a very large table when the master is big. A master of 10,000 vendors gives about five crore pairs. In such cases, compare names only within smaller groups, say within the same state or the same first letter. This is called *blocking*.\n\n## Duplicates across more than one ID\n\nSometimes duplicates are hidden even better. A beneficiary may register twice with a different mobile number but the same bank account. Then again with a different bank account but the same Aadhaar or PAN. No single column shows a duplicate. But together, the records form a chain.\n\nSuch chains can be found using graph theory. We have discussed this with a complete example in @sec-dup_net.\n\n## A suggested workflow\n\nLet us put everything together. For any payment, claim or beneficiary data, an auditor may follow these steps.\n\n1.  **Understand the data.** Know what each column means and which columns identify a transaction.\n2.  **Check exact duplicates.** Find repeated rows with `get_dupes()`. Find out why they exist, then remove them with `distinct()`.\n3.  **Clean the key columns.** Fix case, spaces, punctuation and leading zeros.\n4.  **Run the Same-Same-Same test** on the cleaned key. Quantify the excess payment.\n5.  **Run Same-Same-Different tests** on suitable combinations. Use date windows and business knowledge to reduce false alarms.\n6.  **Look for fuzzy duplicates** in master data like vendors, employees and beneficiaries.\n7.  **Verify with documents.** Analytics only points to the cases. The finding is confirmed only after examining the original bills, approvals and bank records.\n\n::: callout-important\n## Remember\n\nA duplicate found in data is a *lead*, not a *finding*. There may be a genuine reason, such as a part payment, a cancelled and re-issued cheque, or a credit note. Always examine the supporting records before reporting.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `duplicated()` | base R | Marks every repeat occurrence as `TRUE` |\n| `get_dupes()` | janitor | Shows all copies of duplicate records, with a count |\n| `distinct()` | dplyr | Keeps only one copy of each row |\n| `n_distinct()` | dplyr | Counts distinct values, used in Same-Same-Different tests |\n| `lag()` | dplyr | Gives the previous value, used for date windows |\n| `str_to_upper()`, `str_remove_all()` | stringr | Clean key columns before testing |\n| `inner_join()` with `join_by(x < y)` | dplyr | Makes each pair of records only once |\n| `stringdist()` | stringdist | Measures how different two strings are, by the chosen `method` |\n\n: Functions used in this chapter {#tbl-dupfunctions}\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}