{
  "hash": "16a57030c8e53acc449cc670220fcf2c",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n# Charts in Base R {#sec-baseplot}\n\nSuppose a Public Works Division gives us its bill register for the year. It has three thousand bills. Officers of the division may approve a bill up to ₹1 lakh. Anything above needs sanction from a higher authority. We want to know whether some bills were kept just below that limit on purpose. We also want to know whether spending rushed up in March, and whether one office pays much larger bills than the others.\n\nA table of three thousand rows will not answer these questions. Totals and averages will not answer them either. A chart will. A histogram of the bill amounts shows a pile of bills just under ₹1 lakh at a glance. A line chart of monthly spending shows the March rush. A box plot puts the offices side by side. This is why we look at the data before we summarise it.\n\nCharts also help us tell others what we found. A well drawn chart in an audit report says more than a table of numbers. It also helps us spot errors and odd values in the data.\n\nIn this chapter we learn the charts that come with base R, without any extra package. We will use `plot()`, `barplot()`, `hist()`, `boxplot()` and density plots, and arrange several charts on one page with `par()`. All the examples use audit data. At the end we use a histogram to find bills split to stay below the limit.\n\n::: callout-note\nIn @sec-ggplot2 we will learn the `ggplot2` package. It is very flexible, and is built on a theory known as the \"grammar of graphics\". This grammar was created by Leland Wilkinson. It is also used by other software, such as Tableau^[[https://statmodeling.stat.columbia.edu/2021/05/14/tableau-and-the-grammar-of-graphics/](https://statmodeling.stat.columbia.edu/2021/05/14/tableau-and-the-grammar-of-graphics/)] and Plotly. Base R charts are still worth learning. They need no package and are very quick for a first look at the data.\n:::\n\n## Our data, a bill register and a scheme {#sec-baseplot-data}\n\nWe will use two small datasets in this chapter.\n\nThe first, `bills`, is the bill register of a Public Works Division for the financial year 2024-25. The division has five sub-divisional offices. Each bill has a number, a date, the office, the head of expenditure and the amount in rupees. We have planted two irregularities in it. Our charts should bring both out.\n\nThe second, `blocks`, gives the number of beneficiaries and the expenditure of a state scheme in 40 blocks of a district. The scheme pays about ₹6,000 a year to each beneficiary. So the expenditure of a block should rise in step with its beneficiaries. One block does not follow this rule.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the bill register and the block data\"}\nset.seed(77)\noffices <- c(\"Nandgaon\", \"Sonpur\", \"Bhimtal\", \"Kesarganj\", \"Rajnagar\")\nheads   <- c(\"Repairs\", \"Supplies\", \"Electricity\", \"Travel\", \"Office expenses\")\nfy_days <- seq(as.Date(\"2024-04-01\"), as.Date(\"2025-03-31\"), by = \"day\")\n\n# Planted. Days in March are three times as likely to get a bill (a March rush)\nday_wt <- ifelse(format(fy_days, \"%m\") == \"03\", 3, 1)\n\nn <- 3000\nbills <- data.frame(\n  office    = sample(offices, n, TRUE),\n  head      = sample(heads, n, TRUE, prob = c(3, 3, 2, 1, 2)),\n  bill_date = sample(fy_days, n, TRUE, prob = day_wt),\n  amount    = round(rlnorm(n, log(30000), 0.9))\n)\n\n# Planted. 60 repair bills of Kesarganj kept just below the limit of Rs 1 lakh\nsplit_bills <- data.frame(\n  office    = \"Kesarganj\",\n  head      = \"Repairs\",\n  bill_date = sample(fy_days, 60, TRUE),\n  amount    = round(runif(60, 94000, 99999))\n)\n\nbills <- rbind(bills, split_bills)\nbills <- bills[order(bills$bill_date), ]\nrownames(bills) <- NULL\nbills$bill_no <- sprintf(\"BL/24-25/%04d\", seq_len(nrow(bills)))\nfy_months <- month.abb[c(4:12, 1:3)]\nbills$month <- factor(month.abb[as.integer(format(bills$bill_date, \"%m\"))],\n                      levels = fy_months)\nbills$quarter <- paste0(\"Q\", (as.integer(bills$month) - 1) %/% 3 + 1)\nbills <- bills[, c(\"bill_no\", \"bill_date\", \"month\", \"quarter\", \"office\", \"head\", \"amount\")]\n\n# Scheme data of 40 blocks, at about Rs 6,000 per beneficiary\nblocks <- data.frame(\n  block         = sprintf(\"Block %02d\", 1:40),\n  beneficiaries = round(runif(40, 800, 5000))\n)\nblocks$expenditure_lakh <- round(blocks$beneficiaries * 6000 * runif(40, 0.92, 1.08) / 1e5, 1)\n# Planted. Block 27 spends far more than its beneficiaries justify\nblocks$expenditure_lakh[27] <- round(blocks$expenditure_lakh[27] * 1.7, 1)\n```\n:::\n\n\nLet us look at the first few rows of each.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(bills)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        bill_no  bill_date month quarter    office            head amount\n1 BL/24-25/0001 2024-04-01   Apr      Q1    Sonpur     Electricity  85801\n2 BL/24-25/0002 2024-04-01   Apr      Q1    Sonpur        Supplies  21666\n3 BL/24-25/0003 2024-04-01   Apr      Q1 Kesarganj         Repairs  32067\n4 BL/24-25/0004 2024-04-01   Apr      Q1    Sonpur Office expenses  98347\n5 BL/24-25/0005 2024-04-01   Apr      Q1    Sonpur        Supplies  25745\n6 BL/24-25/0006 2024-04-02   Apr      Q1  Rajnagar          Travel  27177\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(blocks)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     block beneficiaries expenditure_lakh\n1 Block 01          4798            288.2\n2 Block 02          3440            192.6\n3 Block 03          2628            169.2\n4 Block 04          1233             76.9\n5 Block 05          3879            228.7\n6 Block 06          1547             90.7\n```\n\n\n:::\n:::\n\n\nThe register has 3,060 bills worth ₹14.3 crore in all.\n\n## Using `plot()`\n\nThe `plot()` function is very versatile. Its main use is to draw scatter plots. It can also draw line charts, box plots and other charts, depending on the data we give it. Its basic syntax is:\n\n```\nplot(x, y, ...)\n```\n\nThe `x` and `y` arguments are the values for the x-axis and the y-axis. The `...` can hold many optional arguments that change how the chart looks. The most common are listed here.\n\n- `xlab` is the label of the x-axis.\n- `ylab` is the label of the y-axis.\n- `main` is the main title of the chart.\n- `xlim` and `ylim` set the limits of the x-axis and the y-axis.\n- `type` is the type of chart. `\"p\"` draws points, `\"l\"` draws lines and `\"b\"` draws both.\n- `col` is the colour of the points or lines.\n- `pch` is the symbol used for the points.\n- `cex` is the size of the points and text.\n\n::: callout-note\nHere `x` and `y` are vectors, such as `blocks$beneficiaries`. In @sec-ggplot2 we will give column names instead. The examples below make this clear.\n:::\n\n### A scatter plot\n\nLet us plot the expenditure of each block against its number of beneficiaries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(blocks$beneficiaries,\n     blocks$expenditure_lakh,\n     xlab = \"Number of beneficiaries\",\n     ylab = \"Expenditure (Rs lakh)\",\n     main = \"Expenditure and beneficiaries of 40 blocks\",\n     pch = 19)\n```\n\n::: {.cell-output-display}\n![Expenditure of each block against its beneficiaries](08-plot_files/figure-html/fig-bp-scatter-1.png){#fig-bp-scatter width=672}\n:::\n:::\n\n\n\n\nThe points lie close to a straight line, as they should. One point sits well above the line. It is Block 27. It spent ₹9,858 per beneficiary, against a median of ₹6,086 for all blocks.\n\nWe can mark that point in red with `points()`, and name it with `text()`. Both add to a chart that is already drawn.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(blocks$beneficiaries, blocks$expenditure_lakh,\n     xlab = \"Number of beneficiaries\", ylab = \"Expenditure (Rs lakh)\",\n     pch = 19, col = \"grey50\")\npoints(blocks$beneficiaries[odd], blocks$expenditure_lakh[odd],\n       pch = 19, col = \"red\", cex = 1.5)\ntext(blocks$beneficiaries[odd], blocks$expenditure_lakh[odd],\n     labels = blocks$block[odd], pos = 2)\n```\n\n::: {.cell-output-display}\n![The odd block marked in red](08-plot_files/figure-html/fig-bp-scatter2-1.png){#fig-bp-scatter2 width=672}\n:::\n:::\n\n\nA scatter plot shows that two columns move together. It cannot prove that one causes the other. Here, though, the rule of the scheme tells us they *should* move together. So a point far from the line is a lead to follow up.\n\n### A line chart\n\nLet us total the bills of each month with `tapply()`, in lakh. Then we draw the totals as a line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly <- tapply(bills$amount, bills$month, sum) / 1e5\nround(monthly, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec   Jan   Feb   Mar \n 96.3 102.4  98.0  93.1 102.7  97.4 108.4 111.4 127.5 113.2  77.7 302.3 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(1:12, monthly,\n     type = \"b\",\n     xlab = \"Month of the financial year (1 = April)\",\n     ylab = \"Amount (Rs lakh)\",\n     main = \"Monthly total of bills, 2024-25\")\n```\n\n::: {.cell-output-display}\n![Monthly total of bills](08-plot_files/figure-html/fig-bp-line-1.png){#fig-bp-line width=672}\n:::\n:::\n\n\nHere `type = \"b\"` draws both points and lines. With `type = \"l\"` we would get lines only. The total for March is ₹302.3 lakh. That is about 3 times the median of the other months. This is the March rush we planted.\n\n### A bar chart of counts\n\n`table()` counts the bills under each head. `barplot()` draws the counts as bars.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(table(bills$head),\n        xlab = \"Head of expenditure\",\n        ylab = \"Number of bills\",\n        main = \"Bills by head of expenditure\")\n```\n\n::: {.cell-output-display}\n![Number of bills under each head](08-plot_files/figure-html/fig-bp-count-1.png){#fig-bp-count width=672}\n:::\n:::\n\n\n### A box plot\n\nWhen `x` is a factor and `y` is numeric, `plot()` draws one box plot for each level of the factor. Let us compare the bill amounts under each head.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(x = factor(bills$head),\n     y = bills$amount,\n     log = \"y\",\n     main = \"Bill amounts by head\",\n     xlab = \"Head of expenditure\",\n     ylab = \"Amount (Rs, log scale)\",\n     col = \"darkgray\")\n```\n\n::: {.cell-output-display}\n![Bill amounts under each head, on a log scale](08-plot_files/figure-html/fig-bp-plotbox-1.png){#fig-bp-plotbox width=672}\n:::\n:::\n\n\nBill amounts are skewed. Most bills are small and a few are very large. On an ordinary scale the boxes would be squashed at the bottom. So we used `log = \"y\"`. On a log scale, each step up the axis multiplies the amount, rather than adding to it. The boxes now have room to show their spread.\n\n### A density plot\n\nA density plot is a smooth version of a histogram. We make it with `density()`, and draw it with `plot()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(density(bills$amount / 1000),\n     main = \"Density of bill amounts\",\n     xlab = \"Amount (Rs thousand)\", ylab = \"Density\", col = \"blue\")\n```\n\n::: {.cell-output-display}\n![Density of bill amounts](08-plot_files/figure-html/fig-bp-density-1.png){#fig-bp-density width=672}\n:::\n:::\n\n\nThe curve rises sharply near zero and has a long tail to the right. That is the usual shape of amounts in accounts.\n\nLet us now learn the other chart functions of base R.\n\n## Bar plots using `barplot()`\n\nAs the name suggests, `barplot()` draws bar charts. Its basic syntax is `barplot(height, ...)`. Here `height` is a vector giving the height of each bar. The other arguments can be seen with `?barplot`.\n\n### A basic bar chart\n\nWe already have the monthly totals in `monthly`. The argument `names.arg` gives the label under each bar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(monthly,\n        names.arg = levels(bills$month),\n        main = \"Monthly total of bills, 2024-25\",\n        xlab = \"Month\", ylab = \"Amount (Rs lakh)\",\n        las = 2)\n```\n\n::: {.cell-output-display}\n![Monthly totals as bars](08-plot_files/figure-html/fig-bp-bar1-1.png){#fig-bp-bar1 width=672}\n:::\n:::\n\n\nThe argument `las = 2` turns the labels on the x-axis so that they all fit.\n\n### A bar chart of summarised data\n\nLet us find the average bill of each office with `tapply()`, and draw the averages as horizontal bars.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noffice_mean <- tapply(bills$amount, bills$office, mean) / 1000\nround(office_mean, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Bhimtal Kesarganj  Nandgaon  Rajnagar    Sonpur \n     47.5      48.4      45.0      46.1      46.7 \n```\n\n\n:::\n\n```{.r .cell-code}\nold_par <- par(mar = c(5, 7, 4, 2))   # wider left margin for the names\nbarplot(height = office_mean,\n        main = \"Average bill by office\",\n        xlab = \"Average bill (Rs thousand)\",\n        col = \"steelblue\",\n        horiz = TRUE,\n        las = 1,\n        cex.names = 0.8)\npar(old_par)\n```\n\n::: {.cell-output-display}\n![Average bill of each office](08-plot_files/figure-html/fig-bp-bar2-1.png){#fig-bp-bar2 width=672}\n:::\n:::\n\n\n`horiz = TRUE` draws the bars sideways. `las = 1` keeps the office names upright, and `cex.names = 0.8` makes them a little smaller. The office names need more room on the left than R leaves by default. So we widened the left margin with `par(mar = )`, and restored it afterwards. We learn more about `par()` later in this chapter.\n\nThe averages are close. Kesarganj is a little ahead, at ₹48.4 thousand. An average alone does not show why. We will find out at the end of this chapter.\n\n### A grouped bar chart\n\nNext, let us total the bills by head *and* by quarter. When `tapply()` gets two grouping columns in a `list()`, it gives a matrix. Each row is a head and each column a quarter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead_qtr <- tapply(bills$amount, list(bills$head, bills$quarter), sum) / 1e5\nround(head_qtr, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Q1   Q2   Q3    Q4\nElectricity     47.1 51.9 62.6  73.1\nOffice expenses 58.1 49.6 64.2  93.0\nRepairs         92.4 82.7 99.9 144.3\nSupplies        74.6 81.3 89.7 142.9\nTravel          24.5 27.6 30.8  39.9\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(height = head_qtr,\n        main = \"Spending by head and quarter\",\n        xlab = \"Quarter\", ylab = \"Amount (Rs lakh)\",\n        col = c(\"red\", \"green\", \"blue\", \"yellow\", \"purple\"),\n        beside = TRUE,\n        legend.text = rownames(head_qtr),\n        args.legend = list(x = \"topleft\", cex = 0.8))\n```\n\n::: {.cell-output-display}\n![Spending under each head, quarter by quarter](08-plot_files/figure-html/fig-bp-grouped-1.png){#fig-bp-grouped width=672}\n:::\n:::\n\n\n`barplot()` draws one group of bars for each *column* of the matrix. Inside a group, it draws one bar, in its own colour, for each *row*. So we get a group for each quarter, with one bar per head. The legend names the rows. Every head rises in the fourth quarter, because of the March rush.\n\n### A stacked bar chart\n\nThe same matrix with `beside = FALSE` *stacks* the rows inside each column. Now each bar is a quarter, and each coloured piece is a head.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(head_qtr,\n        main = \"Spending by quarter and head\",\n        xlab = \"Quarter\", ylab = \"Amount (Rs lakh)\",\n        col = c(\"red\", \"green\", \"blue\", \"yellow\", \"purple\"),\n        legend.text = rownames(head_qtr),\n        args.legend = list(x = \"topleft\", cex = 0.8),\n        beside = FALSE)\n```\n\n::: {.cell-output-display}\n![Spending in each quarter, made up of the heads](08-plot_files/figure-html/fig-bp-stacked-1.png){#fig-bp-stacked width=672}\n:::\n:::\n\n\nA stacked bar shows the total of each quarter, and how the heads make it up. A grouped bar is better for comparing one head across quarters.\n\n### A bar chart from a formula\n\nWe can also give `barplot()` a formula and a data frame. `aggregate()` makes the data frame of totals. Then `amount ~ office` means \"amount for each office\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\noffice_total <- aggregate(amount ~ office, data = bills, FUN = sum)\noffice_total$amount <- office_total$amount / 1e5\nbarplot(amount ~ office, data = office_total,\n        ylab = \"Amount (Rs lakh)\")\n```\n\n::: {.cell-output-display}\n![Total of bills of each office](08-plot_files/figure-html/fig-bp-formula-1.png){#fig-bp-formula width=672}\n:::\n:::\n\n\n## Histograms using `hist()`\n\nThe `hist()` function draws a histogram. A histogram shows how the values of a numeric column are spread. The basic syntax is:\n\n```\nhist(x, breaks = \"Sturges\", freq = TRUE, main = NULL,\n     xlab = NULL, ylab = \"Frequency\", ...)\n```\n\nThe arguments are these.\n\n- `x` is the numeric vector to be plotted.\n- `breaks` sets the bins. By default R chooses the number of bins by the Sturges formula. We can give a different number of bins, or a vector of break points.\n- `freq` chooses what the y-axis shows. If `TRUE`, it shows the number of values in each bin. If `FALSE`, it shows the density.\n- `main` is the title of the histogram.\n- `xlab` and `ylab` are the labels of the axes.\n- `...` holds more arguments for the chart, such as `col`, `border` and `xlim`.\n\nLet us draw a histogram of the bill amounts, in thousands of rupees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bills$amount / 1000, breaks = 50, col = \"lightblue\",\n     xlab = \"Amount (Rs thousand)\", ylab = \"Number of bills\",\n     main = \"Histogram of bill amounts\")\n```\n\n::: {.cell-output-display}\n![Histogram of bill amounts](08-plot_files/figure-html/fig-bp-hist1-1.png){#fig-bp-hist1 width=672}\n:::\n:::\n\n\nMost bills are below ₹50 thousand. A few run to several lakh. A long tail on the right like this is called *right skew*.\n\nSkewed amounts are easier to see on a log scale. `log10()` turns ₹10,000 into 4, ₹1 lakh into 5 and ₹10 lakh into 6. Let us draw the histogram of `log10(amount)` as a density, with `freq = FALSE`. Then we add a density curve on top of it with `lines()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(log10(bills$amount),\n     freq = FALSE,\n     breaks = 40,\n     col = \"grey85\",\n     xlab = \"log10 of amount (4 = Rs 10,000, 5 = Rs 1 lakh)\",\n     main = \"Histogram, with density curve\")\n# add density curve\nlines(density(log10(bills$amount)), col = \"blue\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Histogram of log10 of bill amounts, with a density curve](08-plot_files/figure-html/fig-bp-hist2-1.png){#fig-bp-hist2 width=672}\n:::\n:::\n\n\n`lines()` adds a layer to the chart already drawn. The bars and the curve now have a smooth, bell-like shape. Look carefully at the bar just to the left of 5, that is, just below ₹1 lakh. It stands a little above the curve, while its neighbour on the right falls below it. The sign is faint here, among three thousand bills. We will come back to it.\n\n## Box plots using `boxplot()`\n\nA box plot is also called a box and whiskers plot. It shows the spread of a numeric column through a few summary values. @fig-boxplots shows how to read one.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Understanding boxplots](images/boxplots.png){#fig-boxplots fig-align='center' width=336 height=45%}\n:::\n:::\n\n\nThe syntax is `boxplot(x, ...)`. Here `x` is a numeric vector, or a list of numeric vectors. The `...` holds more arguments to change how the chart looks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(bills$amount / 1000, ylab = \"Amount (Rs thousand)\")\n```\n\n::: {.cell-output-display}\n![Box plot of all bill amounts](08-plot_files/figure-html/fig-bp-box1-1.png){#fig-bp-box1 width=672}\n:::\n:::\n\n\n\n\nThe points above the top whisker are values far from the middle of the data. Here there are 197 of them. That is about 6% of all bills. With skewed amounts many bills fall beyond the whisker, and most of them are genuine large bills. So a point beyond the whisker is a candidate to look at, not an error.\n\nBox plots are most useful when drawn side by side for several groups. We can give a formula, such as `amount ~ office`, as we did for `barplot()`. Let us compare the offices.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(amount ~ office,\n        data = bills,\n        log = \"y\",\n        col = \"lightgray\",\n        xlab = \"Office\", ylab = \"Amount (Rs, log scale)\")\n```\n\n::: {.cell-output-display}\n![Bill amounts of each office, on a log scale](08-plot_files/figure-html/fig-bp-box2-1.png){#fig-bp-box2 width=672}\n:::\n:::\n\n\n\n\nThe thick line in each box is the median. Kesarganj has the highest median bill, ₹34,160, against ₹28,663 to ₹31,274 for the other offices. The difference is not large. A box plot shows the overall spread well, but it can hide a narrow pile of values. We need the histogram for that.\n\n::: callout-warning\n## Caution\n\nA log scale cannot show zero or negative values. With `log = \"y\"`, R leaves such values out of some charts with a warning. Other charts, like `boxplot()`, stop with an error. Real registers often have zero amounts (cancelled bills) or negative ones (reversals). Count and examine them separately before drawing a chart on a log scale.\n:::\n\n## Saving and exporting charts\n\nCharts can be saved from the RStudio menu or through code. Both ways are explained near the end of @sec-ggplot2, including the graphics devices used for base R charts.\n\n## Use of `par()`\n\nOne useful function of base R graphics is `par()`. It sets or reads the graphical **par**ameters. In the following example, its argument `mfrow = c(nr, nc)` draws the next charts in a grid of `nr` rows and `nc` columns on the same page.\n\nHere we use a famous built-in dataset, *Anscombe's quartet*. It has four small datasets, created by the statistician Francis Anscombe in 1973 to show why we must look at data. Let us first look at their summary statistics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(set  = 1:4,\n           mean_x = sapply(1:4, \\(i) mean(anscombe[[paste0(\"x\", i)]])),\n           mean_y = sapply(1:4, \\(i) round(mean(anscombe[[paste0(\"y\", i)]]), 2)),\n           cor_xy = sapply(1:4, \\(i) round(cor(anscombe[[paste0(\"x\", i)]],\n                                              anscombe[[paste0(\"y\", i)]]), 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  set mean_x mean_y cor_xy\n1   1      9    7.5  0.816\n2   2      9    7.5  0.816\n3   3      9    7.5  0.816\n4   4      9    7.5  0.817\n```\n\n\n:::\n:::\n\n\nThe four datasets have the same means and practically the same correlation. Now let us draw them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nold_par <- par(mfrow = c(2, 2))\npurrr::walk(1:4,\n     ~plot(anscombe[[paste0('x', .x)]],\n           anscombe[[paste0('y', .x)]],\n           xlab = paste0('x', .x),\n           ylab = paste0('y', .x),\n           main = paste(\"Anscombe's Quartet Chart No.\", .x))\n     )\npar(old_par)   # restore the earlier settings\n```\n\n::: {.cell-output-display}\n![Anscombe's quartet, four datasets with the same summary statistics](08-plot_files/figure-html/fig-anscombe-1.png){#fig-anscombe width=672}\n:::\n:::\n\n\nThe pictures are completely different. Only the first is a normal straight line relationship. The second is a curve. The third is a straight line spoiled by one outlier. In the fourth, a single point creates the whole correlation. Summary statistics alone would never tell us this. This is the strongest argument for always looking at the data.\n\n`par()` returns the old settings. We saved them in `old_par` and restored them at the end. Otherwise all later charts would also be drawn four to a page.\n\nThe same idea is handy in audit. We can draw a histogram, a box plot, a monthly line and a bar chart of a new register on one page, and take in the whole picture at once.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nold_par <- par(mfrow = c(2, 2))\nhist(log10(bills$amount), breaks = 40, main = \"Amounts (log10)\", xlab = NULL)\nboxplot(amount ~ quarter, data = bills, log = \"y\", main = \"By quarter\",\n        xlab = NULL, ylab = NULL)\nplot(1:12, monthly, type = \"b\", main = \"Monthly total (Rs lakh)\",\n     xlab = \"Month (1 = April)\", ylab = NULL)\nbarplot(table(bills$office), main = \"Bills by office\", las = 2, cex.names = 0.7)\npar(old_par)\n```\n\n::: {.cell-output-display}\n![A first look at the bill register, four charts on one page](08-plot_files/figure-html/fig-bp-par-1.png){#fig-bp-par width=672}\n:::\n:::\n\n\n## Audit use case, payments just below a limit {#sec-baseplot-audit}\n\nOfficers of our division may approve a bill up to ₹1 lakh. Anything above needs a higher authority, or a tender. A common irregularity is to *split* a larger purchase into several bills, each just below the limit. A histogram of bill amounts can show this at a glance. Let us draw the bills between ₹50,000 and ₹1.5 lakh, in bins of ₹2,500.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnear_limit <- bills$amount[bills$amount >= 50000 & bills$amount <= 150000]\nhist(near_limit,\n     breaks = seq(50000, 150000, by = 2500),\n     col = \"grey80\", border = \"white\",\n     xlab = \"Amount of bill (Rs)\", main = NULL)\nabline(v = 100000, col = \"red\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Bills between Rs 50,000 and Rs 1.5 lakh, with the approval limit marked in red](08-plot_files/figure-html/fig-belowlimit-1.png){#fig-belowlimit width=672}\n:::\n:::\n\n\nThe number of bills falls steadily as amounts rise, as expected. The exception is a sharp spike just *below* ₹1 lakh, and a drop just after it. The bins of ₹2,500 just under the limit hold far more bills than their neighbours. Such a spike is a strong lead for splitting of purchases.\n\nThe next step is to see *whose* bills these are. Let us take the bills from ₹95,000 up to the limit and count them by office and head.\n\n\n::: {.cell}\n\n```{.r .cell-code}\njust_below <- bills[bills$amount >= 95000 & bills$amount < 100000, ]\ntable(just_below$office, just_below$head)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           \n            Electricity Office expenses Repairs Supplies Travel\n  Bhimtal             2               2       2        0      0\n  Kesarganj           1               3      54        3      0\n  Nandgaon            1               0       0        2      0\n  Rajnagar            1               0       0        2      1\n  Sonpur              3               1       2        1      0\n```\n\n\n:::\n:::\n\n\n\n\nOf the 81 bills in this narrow range, 54 are repair bills of Kesarganj. The other offices have only a few each, spread over the heads. Let us draw them as bars to show the point in a report.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(sort(table(just_below$office), decreasing = TRUE),\n        col = c(\"firebrick\", rep(\"grey70\", 4)),\n        ylab = \"Number of bills\", main = \"Bills just below Rs 1 lakh\")\n```\n\n::: {.cell-output-display}\n![Bills of Rs 95,000 up to the limit, by office](08-plot_files/figure-html/fig-bp-justbelow-1.png){#fig-bp-justbelow width=672}\n:::\n:::\n\n\nThe auditor would now list the 54 repair bills of Kesarganj, sorted by date. Bills for the same work, to the same contractor, on nearby dates point to one job split into many. Ask the office for the estimates and the work orders. Then check who approved each bill and whether the combined value needed higher sanction. Put the chart, the list and the replies in the working papers. We test this pattern more formally in @sec-nigrini.\n\n::: callout-tip\n## Audit tip\n\nChoose the bins carefully. Too wide a bin hides the spike. Here we used bins of ₹2,500 and limited the chart to the range around the limit. Use `abline()` to mark the limit, so that the reader sees the point at once.\n:::\n\n::: callout-warning\n## Caution\n\nBy default, `hist()` counts a value that falls exactly on a break in the bin to its left. So a bill of exactly ₹1 lakh is counted in the bin just *below* the limit. Keep this in mind when the rule says \"up to ₹1 lakh\", and check the bills exactly at the limit separately.\n:::\n\n## A suggested workflow\n\n1.  **Look before you summarise.** Draw a quick chart of any new data, like a bill register, before you work out totals. Anscombe's quartet showed that summary statistics alone can hide very different patterns.\n2.  **Check the spread of amounts with `hist()`.** A histogram of amounts shows skew, outliers and unusual spikes. Try a few values of `breaks`, since bins that are too wide hide the pattern. Use `log10()` for skewed amounts.\n3.  **Mark the limits with `abline()`.** Draw the financial limit, say ₹1 lakh, on the chart. A spike just below the line is a lead for split purchases.\n4.  **Compare groups with `boxplot()`.** Use a formula like `amount ~ office` to compare the spread across offices or heads. Points beyond the whiskers are candidates to look at, not errors.\n5.  **Count and total categories with `barplot()`.** Count bills with `table()`, or total them with `tapply()`, and draw them as bars. Use `beside = TRUE` to compare groups side by side, or stacked bars to show the make-up of each total.\n6.  **See trends with a line chart.** Plot the monthly totals with `type = \"b\"`. A rush in March stands out at once.\n7.  **See relationships with `plot()`.** A scatter plot of two columns shows whether they move together. Mark the odd points with `points()` and `text()`. It shows association, not cause.\n8.  **Put related charts together with `par()`.** Use `par(mfrow = )` to see several charts on one page. Restore the old settings afterwards.\n9.  **Follow up the leads.** Take the bills in the unusual bin or group, and examine them by office, date and supporting documents.\n\n::: callout-important\n## Remember\n\nA chart is the quickest way to see what the numbers hide. Look at the data before trusting any summary. But a spike or an outlier on a chart is only a lead. Confirm it from the original records before reporting.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `plot()` | base R | Scatter plots, line charts (`type = \"l\"` or `\"b\"`), and box plots when `x` is a factor |\n| `points()`, `text()` | base R | Add points and labels to an existing chart |\n| `barplot()` | base R | Bar charts, grouped (`beside = TRUE`) or stacked, from a vector, a matrix or a formula |\n| `table()`, `tapply()`, `aggregate()` | base R | Count or total values by group, to feed a chart |\n| `hist()` | base R | Histograms, with `breaks` controlling the bins |\n| `density()`, `lines()` | base R | Density curves, and adding lines to an existing chart |\n| `log10()` | base R | Logarithm to base 10, to spread out skewed amounts |\n| `boxplot()`, `boxplot.stats()` | base R | Box plots, including by groups with a formula like `y ~ group`, and the points beyond the whiskers |\n| `abline()` | base R | Adds a straight line, like a limit, to an existing chart |\n| `par(mfrow = )`, `par(mar = )` | base R | Several charts on one page, the margins, and other graphical settings |\n",
    "supporting": [
      "08-plot_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}