{
  "hash": "3e32aca9ce2dabed1caa47d8af41fb52",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Reshaping Data with tidyr {#sec-tidyr}\n\nData received from offices is usually laid out for *reading*, not for analysis. A State's Finance Department sends a statement of expenditure with one row for each district and one column for each month. A works register packs the year, office and serial number of a work into one cell, and the amount spent and sanctioned into another. A stores register writes \"-do-\" instead of repeating the item name. A voucher lists several bill numbers in a single cell. Such layouts are easy on the eye. But they make even simple audit questions hard. Which month had the most expenditure? Which bill was paid twice? Which district did not report at all?\n\nIn this chapter we learn to reshape such data into a form that R can analyse easily. We first see what *tidy* data means. We then learn to turn columns into rows and rows into columns, to split crowded cells, to fill \"-do-\" entries, and to bring back periods which are silently missing. At the end, we put these tools together on a month-wise statement, and find a rush of expenditure in March and months that were never reported.\n\nWe use the package `tidyr` [@R-tidyr], which is part of the core `tidyverse`. It can be loaded with `library(tidyr)` or `library(tidyverse)`.\n\n**Prerequisites**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n## Concepts of tidy data\n\n[Hadley Wickham](https://hadley.nz/), the author of the tidyverse, introduced the idea of tidy data in a paper^[[https://www.jstatsoft.org/article/view/v059i10](https://www.jstatsoft.org/article/view/v059i10)] in the Journal of Statistical Software [@JSSv059i10]. Tidy data is a way of laying out a data set so that it can be easily analysed and visualised. It is a goal to aim for when cleaning data. Once we understand it, analysis, visualisation and even data collection become much easier [@JSSv021i12].\n\nA tidy data set has three properties.\n\n1. Each variable forms a column.\n2. Each observation forms a row.\n3. Each type of observational unit forms a table.\n\n@fig-tidy shows this as a diagram^[Image taken from Hadley Wickham's book [R for data science](https://r4ds.had.co.nz/)].\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Diagrammatic representation of tidy data](images/tidy-1.png){#fig-tidy fig-align='center' width=99%}\n:::\n:::\n\n\nOnce a data set is tidy, it can go straight into the functions that transform, model or visualise data.\n\nThe package `tidyr` comes with five small tables which show the same data in different layouts^[These tables show the number of TB cases documented by the World Health Organization in Afghanistan, Brazil and China in 1999 and 2000. The data has four variables (country, year, cases and population), but each table arranges them differently.]. They are a quick way to see the three rules at work.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidyr::table1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  country      year  cases population\n  <chr>       <dbl>  <dbl>      <dbl>\n1 Afghanistan  1999    745   19987071\n2 Afghanistan  2000   2666   20595360\n3 Brazil       1999  37737  172006362\n4 Brazil       2000  80488  174504898\n5 China        1999 212258 1272915272\n6 China        2000 213766 1280428583\n```\n\n\n:::\n\n```{.r .cell-code}\ntidyr::table2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 4\n   country      year type            count\n   <chr>       <dbl> <chr>           <dbl>\n 1 Afghanistan  1999 cases             745\n 2 Afghanistan  1999 population   19987071\n 3 Afghanistan  2000 cases            2666\n 4 Afghanistan  2000 population   20595360\n 5 Brazil       1999 cases           37737\n 6 Brazil       1999 population  172006362\n 7 Brazil       2000 cases           80488\n 8 Brazil       2000 population  174504898\n 9 China        1999 cases          212258\n10 China        1999 population 1272915272\n11 China        2000 cases          213766\n12 China        2000 population 1280428583\n```\n\n\n:::\n\n```{.r .cell-code}\ntidyr::table3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  country      year rate             \n  <chr>       <dbl> <chr>            \n1 Afghanistan  1999 745/19987071     \n2 Afghanistan  2000 2666/20595360    \n3 Brazil       1999 37737/172006362  \n4 Brazil       2000 80488/174504898  \n5 China        1999 212258/1272915272\n6 China        2000 213766/1280428583\n```\n\n\n:::\n\n```{.r .cell-code}\n# The same data in two tables\ntidyr::table4a\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  country     `1999` `2000`\n  <chr>        <dbl>  <dbl>\n1 Afghanistan    745   2666\n2 Brazil       37737  80488\n3 China       212258 213766\n```\n\n\n:::\n\n```{.r .cell-code}\ntidyr::table4b\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  country         `1999`     `2000`\n  <chr>            <dbl>      <dbl>\n1 Afghanistan   19987071   20595360\n2 Brazil       172006362  174504898\n3 China       1272915272 1280428583\n```\n\n\n:::\n\n```{.r .cell-code}\ntidyr::table5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  country     century year  rate             \n  <chr>       <chr>   <chr> <chr>            \n1 Afghanistan 19      99    745/19987071     \n2 Afghanistan 20      00    2666/20595360    \n3 Brazil      19      99    37737/172006362  \n4 Brazil      20      00    80488/174504898  \n5 China       19      99    212258/1272915272\n6 China       20      00    213766/1280428583\n```\n\n\n:::\n:::\n\n\nLet us look at them one by one.\n\n- `table1` follows all three rules, so it is tidy. Every observation has its own row, and each variable has its own column.\n- `table2` spreads one observation over two *rows*, one for cases and one for population. The column `type` tells which is which. So it breaks rule 2.\n- `table3` stores two variables, cases and population, together in one column `rate`. So it breaks rule 1.\n- `table4a` and `table4b` keep one observation in two different tables, breaking rule 3. Both also use *values* of the year, `1999` and `2000`, as column headers. So the variable year is spread over two columns, which breaks rule 1 too.\n- `table5` splits the single variable year into two columns, `century` and `year`, breaking rule 1. Like `table3`, it also crams cases and population into one column.\n\n### Reshaping data {-}\n\nMost data sets we receive in audit are not tidy. To tidy them, we first decide what in the table is a value, what is a variable and what is an observation. We then reshape the data in one of two ways.\n\n- An observation spread over several rows, as in `table2`, is brought into one row.\n- A variable spread over several columns, as in `table4a`, is brought into one column.\n\nThe two most important functions for this are `pivot_longer()` and `pivot_wider()`. Let us learn them.\n\n## Longer format with `pivot_longer()`\n\nStatements from offices often have *values*, like years or months, as column headers. To analyse them, we turn these headers into a column of their own. This makes the table longer. We use `pivot_longer()` for it. The basic syntax is shown below.\n\n```\npivot_longer(\n  data,\n  cols,\n  names_to = \"name\",\n  values_to = \"value\",\n  ...\n)\n```\n\nThe function has many more arguments, but let us start with these.\n\n- `cols` gives the columns to be turned into rows.\n- `names_to` gives the name of the new column which will hold the old column headers.\n- `values_to` gives the name of the new column which will hold the values of those columns.\n\nThe animated @fig-tidy1 shows how this works.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Data Reshaping to longer format](images/long.gif){#fig-tidy1 fig-align='center'}\n:::\n:::\n\n\nLet us take a statement of expenditure, in ₹ crore, of four departments of a State over three financial years. This is how it usually arrives, with one column for each year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndept_exp <- tibble(\n  department  = c(\"Health\", \"Education\", \"Public Works\", \"Rural Development\"),\n  `2022-23`   = c(412.6, 655.3, 298.4, 361.9),\n  `2023-24`   = c(448.2, 690.1, 341.7, 352.5),\n  `2024-25`   = c(471.9, 702.8, 389.2, 410.6)\n)\ndept_exp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  department        `2022-23` `2023-24` `2024-25`\n  <chr>                 <dbl>     <dbl>     <dbl>\n1 Health                 413.      448.      472.\n2 Education              655.      690.      703.\n3 Public Works           298.      342.      389.\n4 Rural Development      362.      352.      411.\n```\n\n\n:::\n:::\n\n\nThe years are values of a variable, the financial year, but here they are column headers. The column names start with a digit and contain a hyphen. So R needs them in backticks, like `` `2022-23` ``. With `pivot_longer()`, we turn the headers into values of a new column `year`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndept_exp |>\n  pivot_longer(cols = c(`2022-23`, `2023-24`, `2024-25`),\n               names_to = \"year\",\n               values_to = \"exp_crore\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 3\n   department        year    exp_crore\n   <chr>             <chr>       <dbl>\n 1 Health            2022-23      413.\n 2 Health            2023-24      448.\n 3 Health            2024-25      472.\n 4 Education         2022-23      655.\n 5 Education         2023-24      690.\n 6 Education         2024-25      703.\n 7 Public Works      2022-23      298.\n 8 Public Works      2023-24      342.\n 9 Public Works      2024-25      389.\n10 Rural Development 2022-23      362.\n11 Rural Development 2023-24      352.\n12 Rural Development 2024-25      411.\n```\n\n\n:::\n:::\n\n\nEach department now has three rows, one for each year. Check the diagram in @fig-plong.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Diagrammatic representation of pivot\\_longer](images/pivot_longer.png){#fig-plong fig-align='center' width=99%}\n:::\n:::\n\n\n### When values are in column headers {-}\n\nNaming every year column gets tiresome when there are many. With the pipe, we may instead say \"all columns except `department`\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndept_exp |>\n  pivot_longer(cols = -department,     # all columns except department\n               names_to = \"year\",\n               values_to = \"exp_crore\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 3\n   department        year    exp_crore\n   <chr>             <chr>       <dbl>\n 1 Health            2022-23      413.\n 2 Health            2023-24      448.\n 3 Health            2024-25      472.\n 4 Education         2022-23      655.\n 5 Education         2023-24      690.\n 6 Education         2024-25      703.\n 7 Public Works      2022-23      298.\n 8 Public Works      2023-24      342.\n 9 Public Works      2024-25      389.\n10 Rural Development 2022-23      362.\n11 Rural Development 2023-24      352.\n12 Rural Development 2024-25      411.\n```\n\n\n:::\n:::\n\n\nThe helpers of `select()` work here too. For example, `cols = starts_with(\"20\")` picks every column whose name begins with \"20\".\n\n### When the headers combine a variable and a value {-}\n\nSometimes a column name holds two things together. Budget statements commonly have one column for the budget and one for the expenditure of each year, with names like `budget_2023-24` and `exp_2023-24`. Here is such a statement, in ₹ crore.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbudget_exp <- tibble(\n  department       = c(\"Health\", \"Education\", \"Public Works\", \"Rural Development\"),\n  `budget_2023-24` = c(470.0, 720.0, 350.0, 420.0),\n  `exp_2023-24`    = c(448.2, 690.1, 341.7, 352.5),\n  `budget_2024-25` = c(495.0, 730.0, 360.0, 445.0),\n  `exp_2024-25`    = c(471.9, 702.8, 389.2, 410.6)\n)\nbudget_exp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  department       `budget_2023-24` `exp_2023-24` `budget_2024-25` `exp_2024-25`\n  <chr>                       <dbl>         <dbl>            <dbl>         <dbl>\n1 Health                        470          448.              495          472.\n2 Education                     720          690.              730          703.\n3 Public Works                  350          342.              360          389.\n4 Rural Developme…              420          352.              445          411.\n```\n\n\n:::\n:::\n\n\nThe argument `names_sep` splits each header at a separator. We give two names in `names_to`, one for each part.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbe_long <- budget_exp |>\n  pivot_longer(cols = !department,\n               names_sep = \"_\",\n               names_to = c(\"item\", \"year\"),\n               values_to = \"amount\")\nbe_long\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16 × 4\n   department        item   year    amount\n   <chr>             <chr>  <chr>    <dbl>\n 1 Health            budget 2023-24   470 \n 2 Health            exp    2023-24   448.\n 3 Health            budget 2024-25   495 \n 4 Health            exp    2024-25   472.\n 5 Education         budget 2023-24   720 \n 6 Education         exp    2023-24   690.\n 7 Education         budget 2024-25   730 \n 8 Education         exp    2024-25   703.\n 9 Public Works      budget 2023-24   350 \n10 Public Works      exp    2023-24   342.\n11 Public Works      budget 2024-25   360 \n12 Public Works      exp    2024-25   389.\n13 Rural Development budget 2023-24   420 \n14 Rural Development exp    2023-24   352.\n15 Rural Development budget 2024-25   445 \n16 Rural Development exp    2024-25   411.\n```\n\n\n:::\n:::\n\n\n::: callout-note\nWe gave two column names in the argument `names_to`, since each header splits into two parts.\n:::\n\nThis table is long, but still not tidy. The budget and the expenditure of a year are in two different rows. We want `budget` and `exp` to stay as columns, and only the year to become a column of values. For this we use the special value `\".value\"` in `names_to`. It tells `pivot_longer()` that this part of the header is the name of a value column. The animated @fig-tidy2 shows the idea.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![When headers contain both headers and data combined together](images/case3.gif){#fig-tidy2 fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbe_tidy <- budget_exp |>\n  pivot_longer(cols = !department,\n               names_sep = \"_\",\n               names_to = c(\".value\", \"year\"))\nbe_tidy\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 4\n  department        year    budget   exp\n  <chr>             <chr>    <dbl> <dbl>\n1 Health            2023-24    470  448.\n2 Health            2024-25    495  472.\n3 Education         2023-24    720  690.\n4 Education         2024-25    730  703.\n5 Public Works      2023-24    350  342.\n6 Public Works      2024-25    360  389.\n7 Rural Development 2023-24    420  352.\n8 Rural Development 2024-25    445  411.\n```\n\n\n:::\n:::\n\n\n::: callout-note\nWith `.value`, the argument `values_to` is not needed, since the names of the value columns come from the headers themselves.\n:::\n\nNow each row is one department in one year, and the audit question is one line away. Did any department spend more than its budget?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbe_tidy |>\n  mutate(saving = budget - exp) |>\n  filter(saving < 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  department   year    budget   exp saving\n  <chr>        <chr>    <dbl> <dbl>  <dbl>\n1 Public Works 2024-25    360  389.  -29.2\n```\n\n\n:::\n:::\n\n\nPublic Works spent ₹29.2 crore more than its budget in 2024-25. Expenditure in excess of the grant needs regularisation by the legislature, so this is a finding to report.\n\n## Wider format with `pivot_wider()`\n\nAs the name suggests, `pivot_wider()` does the opposite of `pivot_longer()`. It turns the values of a column into column headers. With its `values_fn` argument, it can also summarise, like a pivot table in MS Excel. The basic syntax, with the commonly used arguments, is shown below.\n\n```\npivot_wider(\n  data,\n  id_cols = NULL,\n  names_from = name,\n  values_from = value,\n  values_fill = NULL,\n  values_fn = NULL,\n  ...\n)\n```\n\nThe arguments are these.\n\n- `id_cols` gives the columns which identify each row of the output.\n- `names_from` gives the column, or columns, whose values become the new column names.\n- `values_from` gives the column, or columns, whose values fill the cells.\n- `values_fill` gives the value to put where a combination is missing.\n- `values_fn` gives a function to summarise the values when a cell would get more than one.\n\n::: callout-note\nThe function has many other arguments, which help with complicated tables.\n:::\n\nThe animated @fig-tidy3 shows the basic idea.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Basic functionality of Pivot wider](images/wider.gif){#fig-tidy3 fig-align='center'}\n:::\n:::\n\n\n@fig-pwide shows the mechanics as a diagram.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Diagrammatic representation of pivot\\_wider](images/pivot_wider.png){#fig-pwide fig-align='center' width=99%}\n:::\n:::\n\n\nLet us use the long table `be_long` we made above. It has one row for each department, item and year.\n\n**Items as columns.** Taking the column names from `item` gives the budget and the expenditure side by side. This is the same tidy table we got with `.value`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbe_long |>\n  pivot_wider(names_from = item,\n              values_from = amount)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 4\n  department        year    budget   exp\n  <chr>             <chr>    <dbl> <dbl>\n1 Health            2023-24    470  448.\n2 Health            2024-25    495  472.\n3 Education         2023-24    720  690.\n4 Education         2024-25    730  703.\n5 Public Works      2023-24    350  342.\n6 Public Works      2024-25    360  389.\n7 Rural Development 2023-24    420  352.\n8 Rural Development 2024-25    445  411.\n```\n\n\n:::\n:::\n\n\n**Years as columns.** Taking the names from `year` gives a statement with one column for each year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbe_long |>\n  pivot_wider(names_from = year,\n              values_from = amount)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 4\n  department        item   `2023-24` `2024-25`\n  <chr>             <chr>      <dbl>     <dbl>\n1 Health            budget      470       495 \n2 Health            exp         448.      472.\n3 Education         budget      720       730 \n4 Education         exp         690.      703.\n5 Public Works      budget      350       360 \n6 Public Works      exp         342.      389.\n7 Rural Development budget      420       445 \n8 Rural Development exp         352.      411.\n```\n\n\n:::\n:::\n\n\n**Summarising.** When `id_cols` leaves out a column, several values fall into the same cell. `values_fn` says how to combine them. Here we keep only `department` as the identifier, so the two years are added together.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbe_long |>\n  pivot_wider(id_cols = department,\n              names_from = item,\n              values_from = amount,\n              values_fn = sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  department        budget   exp\n  <chr>              <dbl> <dbl>\n1 Health               965  920.\n2 Education           1450 1393.\n3 Public Works         710  731.\n4 Rural Development    865  763.\n```\n\n\n:::\n:::\n\n\n**Summarising on another identifier.** With `year` as the identifier, we get the State's total budget and expenditure for each year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbe_long |>\n  pivot_wider(id_cols = year,\n              names_from = item,\n              values_from = amount,\n              values_fn = sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  year    budget   exp\n  <chr>    <dbl> <dbl>\n1 2023-24   1960 1832.\n2 2024-25   2030 1974.\n```\n\n\n:::\n:::\n\n\n**Several columns in `names_from`.** The new column names then combine the values of both, joined by an underscore.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbe_long |>\n  pivot_wider(names_from = c(year, item),\n              values_from = amount)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  department       `2023-24_budget` `2023-24_exp` `2024-25_budget` `2024-25_exp`\n  <chr>                       <dbl>         <dbl>            <dbl>         <dbl>\n1 Health                        470          448.              495          472.\n2 Education                     720          690.              730          703.\n3 Public Works                  350          342.              360          389.\n4 Rural Developme…              420          352.              445          411.\n```\n\n\n:::\n:::\n\n\nThe order inside `names_from` decides the order of the parts in the new names.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbe_long |>\n  pivot_wider(names_from = c(item, year),\n              values_from = amount)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  department       `budget_2023-24` `exp_2023-24` `budget_2024-25` `exp_2024-25`\n  <chr>                       <dbl>         <dbl>            <dbl>         <dbl>\n1 Health                        470          448.              495          472.\n2 Education                     720          690.              730          703.\n3 Public Works                  350          342.              360          389.\n4 Rural Developme…              420          352.              445          411.\n```\n\n\n:::\n:::\n\n\n**Several columns in `values_from`.** Starting from the tidy table, we may spread both the budget and the expenditure by year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbe_tidy |>\n  pivot_wider(names_from = year,\n              values_from = c(budget, exp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  department       `budget_2023-24` `budget_2024-25` `exp_2023-24` `exp_2024-25`\n  <chr>                       <dbl>            <dbl>         <dbl>         <dbl>\n1 Health                        470              495          448.          472.\n2 Education                     720              730          690.          703.\n3 Public Works                  350              360          342.          389.\n4 Rural Developme…              420              445          352.          411.\n```\n\n\n:::\n:::\n\n\n**The order of the new columns.** By default, all the budget columns come first, then all the expenditure columns. The argument `names_vary = \"slowest\"` keeps the columns of each year together instead.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbe_tidy |>\n  pivot_wider(names_from = year,\n              values_from = c(budget, exp),\n              names_vary = \"slowest\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  department       `budget_2023-24` `exp_2023-24` `budget_2024-25` `exp_2024-25`\n  <chr>                       <dbl>         <dbl>            <dbl>         <dbl>\n1 Health                        470          448.              495          472.\n2 Education                     720          690.              730          703.\n3 Public Works                  350          342.              360          389.\n4 Rural Developme…              420          352.              445          411.\n```\n\n\n:::\n:::\n\n\nFor more details, see the [package vignette](https://tidyr.tidyverse.org/articles/pivot.html) or [the chapter on tidy data in R for Data Science](https://r4ds.had.co.nz/tidy-data.html).\n\n## Splitting a column, and joining columns\n\nRegisters often put several pieces of information in one cell. Let us take a register of works of a Public Works division. The code below creates it.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the works register\"}\nworks <- tibble(\n  work_ref   = c(\"2024-25/AMR/0153\", \"2024-25/BLP/0207\", \"2023-24/CHD/0019\", \"2024-25/AMR/0161\"),\n  head       = c(\"4059-01-051\", \"4059-80\", \"5054-04-337\", \"4059-01\"),\n  contractor = c(\"Ram Kumar Verma\", \"Sita Devi\", \"Mohd Irfan Khan\", \"K Lakshmi Narayana Rao\"),\n  cost       = c(\"45.5/60\", \"12/12\", \"30.25/48\", \"71.8/65\")   # spent/sanctioned, in lakh\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworks\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  work_ref         head        contractor             cost    \n  <chr>            <chr>       <chr>                  <chr>   \n1 2024-25/AMR/0153 4059-01-051 Ram Kumar Verma        45.5/60 \n2 2024-25/BLP/0207 4059-80     Sita Devi              12/12   \n3 2023-24/CHD/0019 5054-04-337 Mohd Irfan Khan        30.25/48\n4 2024-25/AMR/0161 4059-01     K Lakshmi Narayana Rao 71.8/65 \n```\n\n\n:::\n:::\n\n\nEach column crowds several values together.\n\n- `work_ref` holds the financial year, the office and the serial number of the work.\n- `head` holds the budget head, written as major head, sub-major head and minor head. Some entries stop at the sub-major head.\n- `contractor` holds the full name of the contractor.\n- `cost` holds the amount spent and the amount sanctioned, in ₹ lakh, separated by a slash.\n\n### Split a character column into several with `separate()` {-}\n\nThe function `separate()` splits a character column into several columns. It splits either at a separator, given as a regular expression, or at given character positions.\n\n::: callout-note\nSince tidyr version 1.3, `separate()` is *superseded* by three more specific functions. These are `separate_wider_delim()` (split at a separator), `separate_wider_position()` (split at fixed positions) and `separate_wider_regex()` (split by a regular expression). `separate()` still works, and is used in much existing code, so we learn it first. The newer functions are shown after the examples.\n:::\n\nThe syntax is shown below.\n\n```\nseparate(\n  data,\n  col,\n  into,\n  sep = \"[^[:alnum:]]+\",\n  remove = TRUE,\n  convert = FALSE,\n  extra = \"warn\",\n  fill = \"warn\",\n  ...\n)\n```\n\nThe arguments are these.\n\n1. `data` is the data frame.\n2. `col` is the column to be split.\n3. `into` is a character vector of names for the new columns.\n4. `sep` is the separator. By default, it is any run of characters which are neither letters nor digits.\n5. `remove`, if `FALSE`, keeps the original column in the output.\n6. `convert`, if `TRUE`, converts the new columns to numbers or logical values where possible.\n7. `extra` says what to do when a value has more pieces than the names in `into`.\n8. `fill` says what to do when a value has fewer pieces than the names in `into`.\n\n**Converting the pieces.** Let us split `cost` into the amount spent and the amount sanctioned. We give the separator `\"/\"` ourselves. The default separator would also split at the decimal point in `45.5`. `convert = TRUE` turns the pieces into numbers, so that we can compare them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworks |>\n  separate(cost, into = c(\"spent\", \"sanctioned\"),\n           sep = \"/\",\n           convert = TRUE) |>        # optional, converts the text to numbers\n  filter(spent > sanctioned)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  work_ref         head    contractor             spent sanctioned\n  <chr>            <chr>   <chr>                  <dbl>      <int>\n1 2024-25/AMR/0161 4059-01 K Lakshmi Narayana Rao  71.8         65\n```\n\n\n:::\n:::\n\n\nWork AMR/0161 has spent ₹71.8 lakh against a sanction of ₹65 lakh. The excess needs a revised sanction, which the auditor should ask for.\n\n**Filling missing pieces.** The budget head has three parts in some rows and two in others. `fill = \"right\"` puts `NA` in the missing parts on the right, without a warning. `fill = \"left\"` would put them on the left instead.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworks |>\n  separate(head,\n           into = c(\"major\", \"sub_major\", \"minor\"),\n           fill = \"right\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  work_ref         major sub_major minor contractor             cost    \n  <chr>            <chr> <chr>     <chr> <chr>                  <chr>   \n1 2024-25/AMR/0153 4059  01        051   Ram Kumar Verma        45.5/60 \n2 2024-25/BLP/0207 4059  80        <NA>  Sita Devi              12/12   \n3 2023-24/CHD/0019 5054  04        337   Mohd Irfan Khan        30.25/48\n4 2024-25/AMR/0161 4059  01        <NA>  K Lakshmi Narayana Rao 71.8/65 \n```\n\n\n:::\n:::\n\n\n**A custom separator, keeping the original.** The default separator would split `work_ref` at the hyphen inside `2024-25` too. So we give the separator ourselves. With `remove = FALSE`, the original column is kept beside the new ones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworks |>\n  separate(work_ref,\n           sep = \"/\",\n           into = c(\"fy\", \"office\", \"serial\"),\n           remove = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  work_ref         fy      office serial head        contractor            cost \n  <chr>            <chr>   <chr>  <chr>  <chr>       <chr>                 <chr>\n1 2024-25/AMR/0153 2024-25 AMR    0153   4059-01-051 Ram Kumar Verma       45.5…\n2 2024-25/BLP/0207 2024-25 BLP    0207   4059-80     Sita Devi             12/12\n3 2023-24/CHD/0019 2023-24 CHD    0019   5054-04-337 Mohd Irfan Khan       30.2…\n4 2024-25/AMR/0161 2024-25 AMR    0161   4059-01     K Lakshmi Narayana R… 71.8…\n```\n\n\n:::\n:::\n\n\nWe did not use `convert = TRUE` here. It would have turned the serial number `0153` into the number 153 and dropped the leading zero. Codes should stay as text.\n\n**Keeping the extra pieces together.** Suppose we want the first word of each contractor's name in one column, and the rest in another. `extra = \"merge\"` keeps all the remaining pieces together in the last column, instead of dropping them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworks |>\n  separate(contractor,\n           sep = \" \",\n           into = c(\"first_word\", \"rest_of_name\"),\n           extra = \"merge\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  work_ref         head        first_word rest_of_name         cost    \n  <chr>            <chr>       <chr>      <chr>                <chr>   \n1 2024-25/AMR/0153 4059-01-051 Ram        Kumar Verma          45.5/60 \n2 2024-25/BLP/0207 4059-80     Sita       Devi                 12/12   \n3 2023-24/CHD/0019 5054-04-337 Mohd       Irfan Khan           30.25/48\n4 2024-25/AMR/0161 4059-01     K          Lakshmi Narayana Rao 71.8/65 \n```\n\n\n:::\n:::\n\n\n### Join several character columns into one with `unite()` {-}\n\n`unite()` is the opposite of `separate()`. It pastes several columns into one. Its syntax is shown below.\n\n```\nunite(data,\n      col,\n      ...,\n      sep = \"_\",\n      remove = TRUE,\n      na.rm = FALSE)\n```\n\nThe arguments are these.\n\n1. `data` is the data frame.\n2. `col` is the name of the new column, as a string.\n3. `...` are the columns to be joined.\n4. `sep` is the separator to put between them.\n5. `remove`, if `FALSE`, keeps the original columns.\n6. `na.rm`, if `TRUE`, leaves out missing values before joining.\n\nLet us split the budget head into its parts, and then join the parts back with `unite()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheads <- works |>\n  select(work_ref, head) |>\n  separate(head, into = c(\"major\", \"sub_major\", \"minor\"), fill = \"right\")\n\nheads |>\n  unite(\"head_code\",\n        c(\"major\", \"sub_major\", \"minor\"),\n        sep = \"-\",\n        remove = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  work_ref         head_code   major sub_major minor\n  <chr>            <chr>       <chr> <chr>     <chr>\n1 2024-25/AMR/0153 4059-01-051 4059  01        051  \n2 2024-25/BLP/0207 4059-80-NA  4059  80        <NA> \n3 2023-24/CHD/0019 5054-04-337 5054  04        337  \n4 2024-25/AMR/0161 4059-01-NA  4059  01        <NA> \n```\n\n\n:::\n:::\n\n\nFor the second work, the missing minor head has become the text `NA` inside the code, as `4059-80-NA`. With `na.rm = TRUE`, the missing part is left out. Here we also drop the parts, which is the default.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheads |>\n  unite(\"head_code\",\n        c(\"major\", \"sub_major\", \"minor\"),\n        sep = \"-\",\n        na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  work_ref         head_code  \n  <chr>            <chr>      \n1 2024-25/AMR/0153 4059-01-051\n2 2024-25/BLP/0207 4059-80    \n3 2023-24/CHD/0019 5054-04-337\n4 2024-25/AMR/0161 4059-01    \n```\n\n\n:::\n:::\n\n\n**The newer functions.** `separate_wider_delim()` does the job of `separate()` at a separator. It is stricter. If some value has too few or too many pieces, it stops with an error and tells us which rows. It does not fill them with `NA` silently.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworks |>\n  separate_wider_delim(head, delim = \"-\", names = c(\"major\", \"sub_major\", \"minor\"))\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `separate_wider_delim()`:\n! Expected 3 pieces in each element of `head`.\n! 2 values were too short.\nℹ Use `too_few = \"debug\"` to diagnose the problem.\nℹ Use `too_few = \"align_start\"/\"align_end\"` to silence this message.\n```\n\n\n:::\n:::\n\n\nThe arguments `too_few` and `too_many` say what to do in such cases. `too_few = \"align_start\"` fills the missing parts at the end with `NA`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworks |>\n  separate_wider_delim(head, delim = \"-\", names = c(\"major\", \"sub_major\", \"minor\"),\n                       too_few = \"align_start\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  work_ref         major sub_major minor contractor             cost    \n  <chr>            <chr> <chr>     <chr> <chr>                  <chr>   \n1 2024-25/AMR/0153 4059  01        051   Ram Kumar Verma        45.5/60 \n2 2024-25/BLP/0207 4059  80        <NA>  Sita Devi              12/12   \n3 2023-24/CHD/0019 5054  04        337   Mohd Irfan Khan        30.25/48\n4 2024-25/AMR/0161 4059  01        <NA>  K Lakshmi Narayana Rao 71.8/65 \n```\n\n\n:::\n:::\n\n\n`separate_wider_position()` splits at fixed positions, which suits codes. For example, a GSTIN can be split into its State code, the PAN, the entity number and the rest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(gstin = c(\"27AAKFS4821M1ZQ\", \"29AADCR7314H1Z2\")) |>\n  separate_wider_position(gstin, widths = c(state = 2, pan = 10, entity = 1, rest = 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  state pan        entity rest \n  <chr> <chr>      <chr>  <chr>\n1 27    AAKFS4821M 1      ZQ   \n2 29    AADCR7314H 1      Z2   \n```\n\n\n:::\n:::\n\n\n## Splitting a cell into several rows\n\n### Split values into rows with `separate_rows()` {-}\n\nSometimes one cell holds a list of values. A payment voucher, for example, may list all the bills it pays in one cell. `separate_rows()` puts each value in a row of its own. (`separate()` puts them in columns instead.) Its newer, stricter form is `separate_longer_delim()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvouchers <- tibble(\n  voucher_no = c(\"AMR-0141\", \"AMR-0156\", \"BLP-0207\", \"BLP-0233\"),\n  vendor     = c(\"Sharma Traders\", \"Sharma Traders\", \"Ansari Electricals\", \"Ansari Electricals\"),\n  bills_paid = c(\"SB-101, SB-104, SB-109\", \"SB-112, SB-104\", \"AE-77\", \"AE-81, AE-84\")\n)\nvouchers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  voucher_no vendor             bills_paid            \n  <chr>      <chr>              <chr>                 \n1 AMR-0141   Sharma Traders     SB-101, SB-104, SB-109\n2 AMR-0156   Sharma Traders     SB-112, SB-104        \n3 BLP-0207   Ansari Electricals AE-77                 \n4 BLP-0233   Ansari Electricals AE-81, AE-84          \n```\n\n\n:::\n\n```{.r .cell-code}\nvoucher_bills <- vouchers |>\n  separate_rows(bills_paid, sep = \", \")\nvoucher_bills\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 3\n  voucher_no vendor             bills_paid\n  <chr>      <chr>              <chr>     \n1 AMR-0141   Sharma Traders     SB-101    \n2 AMR-0141   Sharma Traders     SB-104    \n3 AMR-0141   Sharma Traders     SB-109    \n4 AMR-0156   Sharma Traders     SB-112    \n5 AMR-0156   Sharma Traders     SB-104    \n6 BLP-0207   Ansari Electricals AE-77     \n7 BLP-0233   Ansari Electricals AE-81     \n8 BLP-0233   Ansari Electricals AE-84     \n```\n\n\n:::\n:::\n\n\nEach bill now has its own row, and a simple count finds a bill paid more than once.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvoucher_bills |>\n  count(vendor, bills_paid) |>\n  filter(n > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  vendor         bills_paid     n\n  <chr>          <chr>      <int>\n1 Sharma Traders SB-104         2\n```\n\n\n:::\n:::\n\n\nBill SB-104 of Sharma Traders has been paid in two vouchers, AMR-0141 and AMR-0156. In the original layout, with bill numbers buried inside the cells, this double payment was very hard to see.\n\nWe may also number the bills within each voucher, with one extra step.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvoucher_bills |>\n  mutate(bill_seq = row_number(), .by = voucher_no)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 4\n  voucher_no vendor             bills_paid bill_seq\n  <chr>      <chr>              <chr>         <int>\n1 AMR-0141   Sharma Traders     SB-101            1\n2 AMR-0141   Sharma Traders     SB-104            2\n3 AMR-0141   Sharma Traders     SB-109            3\n4 AMR-0156   Sharma Traders     SB-112            1\n5 AMR-0156   Sharma Traders     SB-104            2\n6 BLP-0207   Ansari Electricals AE-77             1\n7 BLP-0233   Ansari Electricals AE-81             1\n8 BLP-0233   Ansari Electricals AE-84             2\n```\n\n\n:::\n:::\n\n\n## Missing rows and \"-do-\" entries\n\nMissing data is not always visible. A value may be `NA`, which we can see. Or the whole row may be absent, which we cannot see. The second kind is called an *implicit* missing value. Two functions of tidyr help here. `complete()` brings back the absent rows, and `fill()` fills in the blanks.\n\n### Turn implicit missing values into explicit ones with `complete()` {-}\n\n`complete()` turns implicit missing values (absent rows) into explicit ones (rows with `NA`).\n\nLet us take the price of diesel at the fuel pump from which an office buys fuel for its vehicles. Its bills for fuel must be at the price of the day. Suppose the price was revised on 1 March 2024, and again on 15 March 2024. The price table has only two rows for March. So there are 29 implicit missing values, one for each of the other days.\n\nThe syntax is shown below.\n\n```\ncomplete(data,\n         ...,\n         fill = list(),\n         explicit = TRUE)\n```\n\nThe arguments are these.\n\n- `data` is the data frame.\n- `...` are the columns whose combinations are to be completed.\n- `fill` is a named list giving a value to use instead of `NA` for the new rows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiesel <- tibble(\n  date  = as.Date(c(\"2024-03-01\", \"2024-03-15\")),\n  price = c(89.62, 87.62)\n)\ndiesel\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  date       price\n  <date>     <dbl>\n1 2024-03-01  89.6\n2 2024-03-15  87.6\n```\n\n\n:::\n\n```{.r .cell-code}\n# Bring back every day of March as a row\ndiesel |>\n  complete(date = seq.Date(as.Date(\"2024-03-01\"), as.Date(\"2024-03-31\"), by = \"day\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 31 × 2\n   date       price\n   <date>     <dbl>\n 1 2024-03-01  89.6\n 2 2024-03-02  NA  \n 3 2024-03-03  NA  \n 4 2024-03-04  NA  \n 5 2024-03-05  NA  \n 6 2024-03-06  NA  \n 7 2024-03-07  NA  \n 8 2024-03-08  NA  \n 9 2024-03-09  NA  \n10 2024-03-10  NA  \n# ℹ 21 more rows\n```\n\n\n:::\n:::\n\n\nHere we gave the full list of dates ourselves. More often, `complete()` finds every combination of the values already present in the given columns. Let us take the number of grievances registered on a portal by an office, quarter by quarter. A quarter with no grievance has no row.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrievances <- tibble(\n  year       = c(2023, 2023, 2023, 2024, 2024),\n  qtr        = c(1, 3, 4, 2, 3),\n  registered = c(14, 9, 21, 17, 12)\n)\ngrievances\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n   year   qtr registered\n  <dbl> <dbl>      <dbl>\n1  2023     1         14\n2  2023     3          9\n3  2023     4         21\n4  2024     2         17\n5  2024     3         12\n```\n\n\n:::\n\n```{.r .cell-code}\ngrievances |>\n  complete(year, qtr,       # every combination of year and quarter\n           fill = list(registered = 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 3\n   year   qtr registered\n  <dbl> <dbl>      <dbl>\n1  2023     1         14\n2  2023     2          0\n3  2023     3          9\n4  2023     4         21\n5  2024     1          0\n6  2024     2         17\n7  2024     3         12\n8  2024     4          0\n```\n\n\n:::\n:::\n\n\n::: callout-note\nWithout the `fill` argument, the new rows would have `NA` for `registered`. We filled them with zero because the portal records every grievance, so an absent quarter really means none was registered. That is not always true. A month missing from an expenditure statement may mean the office did not report, not that it spent nothing.\n:::\n\n### Fill missing values from the row above with `fill()` {-}\n\n`fill()` fills missing values with the previous or the next entry. Think of a paper register in which many cells are written as \"-do-\". The syntax is shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfill(data, # the data frame\n     ..., # the columns to be filled\n     .direction = c(\"down\", \"up\", \"downup\", \"updown\"))\n```\n:::\n\n\nThe arguments are simple. Most of the time, `\"down\"` is what we want. For the diesel prices, each day's price is the last revised price.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiesel_daily <- diesel |>\n  complete(date = seq.Date(as.Date(\"2024-03-01\"), as.Date(\"2024-03-31\"), by = \"day\")) |>\n  fill(price, .direction = \"down\")\n\nhead(diesel_daily)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  date       price\n  <date>     <dbl>\n1 2024-03-01  89.6\n2 2024-03-02  89.6\n3 2024-03-03  89.6\n4 2024-03-04  89.6\n5 2024-03-05  89.6\n6 2024-03-06  89.6\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(diesel_daily)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  date       price\n  <date>     <dbl>\n1 2024-03-26  87.6\n2 2024-03-27  87.6\n3 2024-03-28  87.6\n4 2024-03-29  87.6\n5 2024-03-30  87.6\n6 2024-03-31  87.6\n```\n\n\n:::\n:::\n\n\nEvery day of March now has its price, and each fuel bill can be joined to it by date (@sec-joins).\n\nA register typed from paper usually has the \"-do-\" entries as text. We first turn them into `NA` with `na_if()` from dplyr, and then fill them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstock_register <- tibble(\n  entry    = 1:6,\n  item     = c(\"A4 paper (ream)\", \"-do-\", \"-do-\", \"Toner cartridge\", \"-do-\", \"Stapler\"),\n  supplier = c(\"Gupta Stationers\", \"-do-\", \"Sharma Traders\", \"Sharma Traders\", \"-do-\", \"-do-\"),\n  qty      = c(50, 30, 40, 6, 4, 10)\n)\nstock_register\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  entry item            supplier           qty\n  <int> <chr>           <chr>            <dbl>\n1     1 A4 paper (ream) Gupta Stationers    50\n2     2 -do-            -do-                30\n3     3 -do-            Sharma Traders      40\n4     4 Toner cartridge Sharma Traders       6\n5     5 -do-            -do-                 4\n6     6 Stapler         -do-                10\n```\n\n\n:::\n\n```{.r .cell-code}\nstock_register |>\n  mutate(item     = na_if(item, \"-do-\"),\n         supplier = na_if(supplier, \"-do-\")) |>\n  fill(item, supplier)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  entry item            supplier           qty\n  <int> <chr>           <chr>            <dbl>\n1     1 A4 paper (ream) Gupta Stationers    50\n2     2 A4 paper (ream) Gupta Stationers    30\n3     3 A4 paper (ream) Sharma Traders      40\n4     4 Toner cartridge Sharma Traders       6\n5     5 Toner cartridge Sharma Traders       4\n6     6 Stapler         Sharma Traders      10\n```\n\n\n:::\n:::\n\n\n::: callout-warning\n## Caution\n\n`fill()` copies the value from the row above into every blank below it. Use it only where a blank really means \"same as above\", like a \"-do-\" entry. Sort the data in the right order first. Group the data with `group_by()` before filling, so that one office's value does not run into the next office's rows.\n:::\n\n## Audit use case, a month-wise statement {#sec-tidyr-audit}\n\nOffices commonly report expenditure in a statement with one row for each district and one column for each month. The figures are in ₹ lakh.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the statement\"}\nset.seed(42)\nfy_months <- c(\"Apr\", \"May\", \"Jun\", \"Jul\", \"Aug\", \"Sep\",\n               \"Oct\", \"Nov\", \"Dec\", \"Jan\", \"Feb\", \"Mar\")\nstatement <- tibble(district = c(\"Amarpur\", \"Belapur\", \"Chandpur\", \"Devgarh\", \"Fatehpur\")) |>\n  bind_cols(as_tibble(matrix(round(runif(5 * 12, 20, 60), 1), nrow = 5,\n                             dimnames = list(NULL, fy_months))))\n# March rush in two districts\nstatement$Mar[c(2, 5)] <- statement$Mar[c(2, 5)] * 4\n# Chandpur did not report for three months; the cells were left blank\nstatement[3, c(\"Jul\", \"Aug\", \"Sep\")] <- NA\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstatement\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 13\n  district   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec   Jan   Feb\n  <chr>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1 Amarpur   56.6  40.8  38.3  57.6  56.2  40.6  49.5  53.3  35.2  58.3  33.3\n2 Belapur   57.5  49.5  48.8  59.1  25.5  35.6  52.4  20.3  37.4  55.5  33.9\n3 Chandpur  31.4  25.4  57.4  NA    NA    NA    35.5  28.3  21.5  45.6  35.9\n4 Devgarh   53.2  46.3  30.2  39    57.9  37.9  47.4  56.3  58.9  58.8  51.4\n5 Fatehpur  45.7  48.2  38.5  42.4  23.3  53.4  20.2  44.5  37.3  44.8  21.6\n# ℹ 1 more variable: Mar <dbl>\n```\n\n\n:::\n:::\n\n\nThis layout is easy to read, but hard to analyse. To compare months, find a share, or plot a trend, we need one row for each district and month. So we pivot it longer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly <- statement |>\n  pivot_longer(cols = -district, names_to = \"month\", values_to = \"exp_lakh\") |>\n  mutate(month = factor(month, levels = fy_months))   # months in the order of the financial year\n\nmonthly\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 60 × 3\n   district month exp_lakh\n   <chr>    <fct>    <dbl>\n 1 Amarpur  Apr       56.6\n 2 Amarpur  May       40.8\n 3 Amarpur  Jun       38.3\n 4 Amarpur  Jul       57.6\n 5 Amarpur  Aug       56.2\n 6 Amarpur  Sep       40.6\n 7 Amarpur  Oct       49.5\n 8 Amarpur  Nov       53.3\n 9 Amarpur  Dec       35.2\n10 Amarpur  Jan       58.3\n# ℹ 50 more rows\n```\n\n\n:::\n:::\n\n\nWe made `month` a factor with the levels in the order of the financial year. Otherwise the months would sort alphabetically, with April after August. Factors are explained in @sec-factors.\n\n**The share of March.** Now each question is a short pipe. What share of each district's yearly expenditure was spent in March?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmarch_share <- monthly |>\n  summarise(year_total  = sum(exp_lakh, na.rm = TRUE),\n            march       = sum(exp_lakh[month == \"Mar\"], na.rm = TRUE),\n            march_share = round(100 * march / year_total, 1),\n            .by = district) |>\n  arrange(desc(march_share))\nmarch_share\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 4\n  district year_total march march_share\n  <chr>         <dbl> <dbl>       <dbl>\n1 Belapur        664. 188.         28.4\n2 Fatehpur       582. 162.         27.9\n3 Amarpur        570.  50           8.8\n4 Chandpur       308.  26.9         8.7\n5 Devgarh        568.  30.4         5.4\n```\n\n\n:::\n:::\n\n\nBelapur and Fatehpur spent 28.4% and 27.9% of the year's money in March alone. In an even year, March would take about 8%. This is the *rush of expenditure* at the end of the year, which the General Financial Rules ask departments to avoid.\n\n**Months not reported.** Blank cells became `NA` when the statement was pivoted, so Chandpur's missing months are visible. But in long data, missing months are often simply *absent rows*, not `NA`. Suppose a district's months appear only when it reported. `complete()` brings back every district and month combination, so the absent ones show up.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreported <- monthly |> filter(!is.na(exp_lakh))   # data as it often arrives\nnrow(reported)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 57\n```\n\n\n:::\n\n```{.r .cell-code}\nreported |>\n  complete(district, month) |>\n  filter(is.na(exp_lakh))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  district month exp_lakh\n  <chr>    <fct>    <dbl>\n1 Chandpur Jul         NA\n2 Chandpur Aug         NA\n3 Chandpur Sep         NA\n```\n\n\n:::\n:::\n\n\n`complete()` found the 3 months which Chandpur did not report. Without it, a total for Chandpur would quietly cover only 9 months.\n\n**Back to a report.** Finally, `pivot_wider()` turns a summary back into the familiar layout for a report, say quarter-wise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly |>\n  mutate(quarter = paste0(\"Q\", (as.integer(month) - 1) %/% 3 + 1)) |>\n  pivot_wider(id_cols = district, names_from = quarter, values_from = exp_lakh,\n              values_fn = sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  district    Q1    Q2    Q3    Q4\n  <chr>    <dbl> <dbl> <dbl> <dbl>\n1 Amarpur   136.  154. 138    142.\n2 Belapur   156.  120. 110.   278.\n3 Chandpur  114.   NA   85.3  108.\n4 Devgarh   130.  135. 163.   141.\n5 Fatehpur  132.  119. 102    229.\n```\n\n\n:::\n:::\n\n\nChandpur's second quarter is `NA`, since none of its three months was reported. Had we used `sum(x, na.rm = TRUE)`, it would have shown 0, as if Chandpur spent nothing in that quarter. That is not what the data says.\n\nThe auditor would now ask Belapur and Fatehpur for the bills paid in March, to see whether the goods and services were really received and needed before the year closed. Chandpur would be asked for its statements for July to September. Both findings, with the statement and the analysis, go into the working papers.\n\n::: callout-tip\n## Audit tip\n\nPivot data longer for analysis, and wider only at the end, for presentation. Before summing or averaging data over time, always check with `complete()` that no period is silently missing. A missing month and a month with zero expenditure are different findings.\n:::\n\n## A suggested workflow\n\n1.  **Look at the layout first.** Check whether the file received from the auditee is tidy, with one column for each variable and one row for each observation. A statement with one column for each month is not tidy.\n2.  **Pivot longer for analysis.** Use `pivot_longer()` to turn month or year columns into rows. Use `names_sep` and `\".value\"` when headers like `budget_2024-25` combine a variable and a year. Make the month a factor in the order of the financial year, from April to March.\n3.  **Split crowded columns.** Use `separate()` or `separate_wider_delim()` to split a value into its parts, like a budget head into major, sub-major and minor heads. Use `separate_wider_position()` for fixed-width codes, like a GSTIN. Keep codes as text.\n4.  **Split lists into rows.** Use `separate_rows()` when one cell holds several values, like the bills paid by a voucher. Then count to find values that repeat.\n5.  **Fill the \"-do-\" entries.** Turn \"-do-\" into `NA` with `na_if()`, and use `fill()` to copy the value from the row above.\n6.  **Bring back the missing periods.** Use `complete()` to add every combination of office and month. Months which were never reported then show up as `NA`.\n7.  **Analyse in long form.** Work out totals, shares and trends on the long data, like the share of March in the year's expenditure.\n8.  **Pivot wider only for the report.** Use `pivot_wider()` at the end, to present the results in a familiar layout, like district by quarter.\n\n::: callout-important\n## Remember\n\nA missing month and a month with zero expenditure are different findings. Before summing data over time, check with `complete()` that no period is silently absent. Do not fill a gap with zero unless the records show that nothing was spent.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `pivot_longer()` | tidyr | Turn columns into rows, like months in columns into a month column |\n| `pivot_wider()` | tidyr | Turn rows into columns, optionally summarising with `values_fn` |\n| `separate()`, `separate_wider_delim()`, `separate_wider_position()` | tidyr | Split a column into several columns |\n| `unite()` | tidyr | Join several columns into one |\n| `separate_rows()`, `separate_longer_delim()` | tidyr | Split values in a cell into several rows |\n| `complete()` | tidyr | Add the missing combinations, making implicit missing values explicit |\n| `fill()` | tidyr | Fill missing values with the previous or next value, like \"-do-\" |\n| `na_if()` | dplyr | Turn a given value, like \"-do-\", into `NA` |\n| `count()` | dplyr | Count rows for each value, to find repeats |\n\n: Functions used in this chapter {#tbl-tidyrfunctions}\n",
    "supporting": [
      "11-tidyr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}