{
  "hash": "6d948fc034a7f236c0fafb7e6a84e292",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Record Linkage {#sec-linkage}\n\nSome of the most important audit findings come not from one data set, but from putting two together.\n\n- Old-age pension still being paid to persons who appear in the **death register**.\n- Government employees, or income tax payers, drawing benefits meant for the **poor**.\n- The same farmer taking the same subsidy under **two schemes**, or in two districts.\n- A student receiving **scholarships from two States**.\n- An employee who is secretly the **proprietor of a supplier** firm.\n\nIn each case, we have to find the *same person* in two lists. If both lists carried a reliable common number, such as an Aadhaar number seeded in both, this would be a simple join, which we learnt in @sec-joins. But very often they do not. The death register has no pension ID. The scheme lists were made by different departments, at different times, by different data entry operators. The same person is written as *Kamla Devi* in one and *Smt. Kamala Devi* in the other, with an age that differs by a year and a village spelt two ways.\n\n**Record linkage** is the craft of finding records which belong to the same person (or firm, or property) when there is no common key, using several imperfect details together. It is also called *record matching*, *entity resolution* or, when done within one list, *deduplication*. In this chapter we learn it from the beginning, step by step, on a realistic example.\n\n**Prerequisites**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(stringdist)     # string similarity, see @sec-strsim\nlibrary(fullmetaphone)   # phonetic codes, see @sec-strsim\n```\n:::\n\n\nWe use the string similarity measures of @sec-strsim, especially Jaro-Winkler similarity, and Double Metaphone phonetic codes. Readers new to them may read that chapter first.\n\n## Why a simple join is not enough {#sec-linkage-why}\n\nLet us start with a tiny example, three pensioners and three death records.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npension_list <- tibble(\n  ben_id        = c(\"P1\", \"P2\", \"P3\"),\n  name          = c(\"Kamla Devi\", \"Ramesh Yadav\", \"Sita Ram Verma\"),\n  relation_name = c(\"Mohan Lal\", \"Jagdish Yadav\", \"Bhagwan Verma\"),\n  village       = c(\"Amarpur\", \"Chandanpura\", \"Daulatpur\"),\n  age_2024      = c(72, 81, 68)\n)\ndeath_register <- tibble(\n  reg_no        = c(\"D101\", \"D102\", \"D103\"),\n  name          = c(\"Smt. Kamala Devi\", \"Ramesh Yadav\", \"Sitaram Verma\"),\n  relation_name = c(\"Mohan Lal\", \"Rakesh Yadav\", \"Bhagwan Varma\"),\n  village       = c(\"Amarpur\", \"Chandanpura\", \"Daulatpur\"),\n  age_at_death  = c(73, 45, 68)\n)\n```\n:::\n\n\nAn exact join on name and village finds only one pair.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npension_list |>\n  inner_join(death_register, by = c(\"name\", \"village\"), suffix = c(\"_pension\", \"_death\")) |>\n  select(name, village, relation_name_pension, relation_name_death, age_2024, age_at_death)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  name   village relation_name_pension relation_name_death age_2024 age_at_death\n  <chr>  <chr>   <chr>                 <chr>                  <dbl>        <dbl>\n1 Rames… Chanda… Jagdish Yadav         Rakesh Yadav              81           45\n```\n\n\n:::\n:::\n\n\nAnd that one pair is wrong! *Ramesh Yadav* of Chandanpura in the death register is a different person. His father's name is *Rakesh*, not *Jagdish*, and he died at 45, while our pensioner is 81. Meanwhile the join has missed both true pairs. *Kamla Devi* and *Smt. Kamala Devi*, with the same husband, village and nearly the same age, are surely the same person. So are *Sita Ram Verma* and *Sitaram Verma*.\n\nTwo lessons follow, and the rest of the chapter builds on them.\n\n1. **Names alone are not enough.** Common names repeat, especially within a village. We must use several details together: name, father's or husband's name, age, village.\n2. **Each detail must be compared with tolerance**, allowing for spelling variations, titles, and small differences in age.\n\n## The steps of record linkage {#sec-linkage-steps}\n\nEvery record linkage, however large, follows the same seven steps. We will go through each with our example.\n\n| Step | What we do | Why |\n|------|------------------------|------------------------|\n| 1. Standardise | Clean each field in the same way in both lists | Remove differences that do not matter, like titles and punctuation |\n| 2. Block | Choose which pairs of records to compare | Comparing every record with every other is too slow |\n| 3. Compare | Measure how closely each field agrees, for each pair | Allow for spelling and age differences |\n| 4. Weigh | Turn the agreements into a total score of evidence | Agreement on a rare detail counts more than on a common one |\n| 5. Decide | Link, review by hand, or reject each pair, by its score | Not every pair can be decided by the data alone |\n| 6. One-to-one | Keep the best partner for each record | A person can die only once |\n| 7. Check | Verify the links, and measure the quality | Every link becomes an audit observation |\n\n: The seven steps of record linkage {#tbl-linkage-steps}\n\n## Our data, pensioners and the death register {#sec-linkage-data}\n\nWe have the list of 3,000 beneficiaries of an old-age pension scheme in a development block, all being paid ₹1,000 a month (₹1,500 for those aged 80 or more) as on 31 March 2025. We also have the death register of the same block for April 2022 to December 2024, with 1,212 entries. The audit question is: **are any of the pensioners in the death register, and still being paid?**\n\nThe two lists were prepared independently. The pension list records the date of birth. The death register, as is common, records only the *age at death*, often as told by a relative, and so often rounded to a multiple of five. Names are written with variations, and some death records have no father's or husband's name.\n\nThe code below creates the data. It is long, because it imitates the many ways in which real records differ. New readers may skip it. What matters is that, unknown to the auditor, 150 of the pensioners died during the period, and their death records carry the kinds of variation described above. We also planted a dozen *traps*: deaths of other persons who share the name and village of a living pensioner. Since the data are simulated, we keep the true answer in a separate table, `truth`, only to measure how well our linkage works at the end. In a real audit there is no such table.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the pension list and death register\"}\nset.seed(2024)\nmale_first   <- c(\"Ram\", \"Shyam\", \"Mohan\", \"Sohan\", \"Ramesh\", \"Suresh\", \"Mahesh\", \"Dinesh\",\n                  \"Rajendra\", \"Surendra\", \"Mahendra\", \"Narendra\", \"Om\", \"Jagdish\", \"Harish\",\n                  \"Krishna\", \"Gopal\", \"Govind\", \"Bhagwan\", \"Hari\", \"Shiv\", \"Shankar\", \"Prem\",\n                  \"Kailash\", \"Laxman\", \"Bharat\", \"Sita Ram\", \"Ram Prasad\", \"Kishan\", \"Babu\",\n                  \"Bansi\", \"Chhote\", \"Mangal\", \"Budhram\", \"Rameshwar\", \"Ganga Ram\", \"Dayaram\",\n                  \"Mohd Yusuf\", \"Abdul Rashid\", \"Gurmeet\")\nfemale_first <- c(\"Kamla\", \"Shanti\", \"Lakshmi\", \"Savitri\", \"Sarla\", \"Sushila\", \"Kaushalya\",\n                  \"Bimla\", \"Vimla\", \"Ramkali\", \"Phoolwati\", \"Geeta\", \"Sita\", \"Radha\", \"Parvati\",\n                  \"Durga\", \"Kalawati\", \"Bhagwati\", \"Shakuntala\", \"Urmila\", \"Pushpa\", \"Krishna\",\n                  \"Gayatri\", \"Chandrakala\", \"Munni\", \"Ramrati\", \"Sumitra\", \"Kesar\", \"Sughra\",\n                  \"Jaswant Kaur\")\nsurnames     <- c(\"Verma\", \"Sharma\", \"Yadav\", \"Singh\", \"Kushwaha\", \"Patel\", \"Maurya\", \"Gupta\",\n                  \"Prajapati\", \"Pal\", \"Lodhi\", \"Rajput\", \"Ahirwar\", \"Kori\", \"Khan\", \"Ansari\",\n                  \"Tiwari\", \"Mishra\", \"Pandey\", \"Chaurasia\", \"Sahu\", \"Rathore\", \"Jatav\",\n                  \"Baghel\", \"Kumar\")\nvillages     <- c(\"Amarpur\", \"Bhagwantpur\", \"Chandanpura\", \"Daulatpur\", \"Fatehgarh\", \"Gopalganj\",\n                  \"Hariharpur\", \"Islamnagar\", \"Jamunia\", \"Kakrahi\", \"Lalpur\", \"Madhopur\",\n                  \"Nayagaon\", \"Pipariya\", \"Rajapur\", \"Sahjanpur\", \"Tilakpur\", \"Umaria\",\n                  \"Vishnupura\", \"Barkheda\", \"Khajuri\", \"Semri\", \"Bilkheda\", \"Dhaneta\",\n                  \"Kesli\", \"Mehgaon\", \"Narsinghpur Khurd\", \"Pathariya\", \"Rampura\", \"Sukha\",\n                  \"Tikamgarh Kalan\", \"Udaipura\", \"Bamhori\", \"Chhapra\", \"Gadarwara\", \"Hirapur\",\n                  \"Imlia\", \"Jaitpur\", \"Kundalpur\", \"Lakhanpur\")\n\nn_pen <- 3000\npensioners <- tibble(\n  ben_id    = sprintf(\"OAP-%05d\", 1:n_pen),\n  gender    = sample(c(\"M\", \"F\"), n_pen, TRUE),\n  surname   = sample(surnames, n_pen, TRUE),\n  rel_first = sample(male_first, n_pen, TRUE),\n  village   = sample(villages, n_pen, TRUE),\n  dob       = as.Date(\"1925-01-01\") + sample(0:(365 * 36), n_pen, TRUE),\n  mobile    = if_else(runif(n_pen) < 0.55,\n                      paste0(sample(6:9, n_pen, TRUE), sprintf(\"%09d\", sample(0:999999999, n_pen, TRUE))),\n                      NA_character_)\n) |>\n  mutate(first = if_else(gender == \"M\", sample(male_first, n_pen, TRUE),\n                         sample(female_first, n_pen, TRUE)),\n         name = if_else(gender == \"M\" | runif(n_pen) < 0.5, paste(first, surname),\n                        paste(first, \"Devi\")),\n         relation_name = paste(rel_first, surname),\n         pension = if_else(as.numeric(as.Date(\"2025-03-31\") - dob) / 365.25 >= 80, 1500, 1000)) |>\n  select(ben_id, name, relation_name, gender, dob, village, mobile, pension)\n\n# Ways in which the death register writes the same name differently\nvariants <- c(\"Lakshmi\" = \"Laxmi\", \"Kamla\" = \"Kamala\", \"Bimla\" = \"Vimla\", \"Shanti\" = \"Santi\",\n              \"Sushila\" = \"Susheela\", \"Savitri\" = \"Savitree\", \"Kaushalya\" = \"Kausalya\",\n              \"Phoolwati\" = \"Phulwati\", \"Ramkali\" = \"Ram Kali\", \"Jagdish\" = \"Jagdeesh\",\n              \"Rajendra\" = \"Rajendar\", \"Surendra\" = \"Surender\", \"Mahendra\" = \"Mahender\",\n              \"Narendra\" = \"Narender\", \"Kailash\" = \"Kelash\", \"Laxman\" = \"Lakshman\",\n              \"Prasad\" = \"Parsad\", \"Yadav\" = \"Yadaw\", \"Kushwaha\" = \"Kushwah\",\n              \"Prajapati\" = \"Prajapti\", \"Chaurasia\" = \"Chourasia\", \"Ahirwar\" = \"Aharwar\",\n              \"Maurya\" = \"Mourya\", \"Mohd\" = \"Mohammad\", \"Rameshwar\" = \"Rameshwer\",\n              \"Sita Ram\" = \"Sitaram\", \"Ganga Ram\" = \"Gangaram\", \"Dayaram\" = \"Daya Ram\",\n              \"Chhote\" = \"Chote\", \"Shakuntala\" = \"Sakuntala\", \"Pushpa\" = \"Puspa\",\n              \"Gayatri\" = \"Gaytri\", \"Urmila\" = \"Urmilla\", \"Tiwari\" = \"Tiwary\")\ntypo <- function(x) {   # drop one letter from the middle\n  map_chr(x, \\(s) {\n    pos <- 2 + sample.int(max(1, nchar(s) - 3), 1)\n    paste0(substr(s, 1, pos - 1), substr(s, pos + 1, nchar(s)))\n  })\n}\napply_variant <- function(x) {\n  map_chr(x, \\(s) {\n    hits <- names(variants)[str_detect(s, fixed(names(variants)))]\n    if (length(hits) == 0) return(s)\n    h <- sample(hits, 1)\n    str_replace(s, fixed(h), variants[[h]])\n  })\n}\nmessy <- function(x, p_variant, p_typo) {\n  v <- runif(length(x)) < p_variant\n  x[v] <- apply_variant(x[v])\n  t <- runif(length(x)) < p_typo\n  x[t] <- typo(x[t])\n  x\n}\n\n# Planted. 150 pensioners died, but are still on the pension list\ndead <- pensioners |>\n  slice_sample(n = 150) |>\n  mutate(date_of_death = as.Date(\"2022-04-01\") + sample(0:1004, n(), TRUE),\n         true_age = floor(as.numeric(date_of_death - dob) / 365.25))\nrecorded <- dead |>\n  mutate(\n    reg_name = messy(name, 0.45, 0.15),\n    reg_name = case_when(runif(n()) < 0.12 ~ paste(\"Late\", reg_name),\n                         runif(n()) < 0.12 & gender == \"F\" ~ paste(\"Smt.\", reg_name),\n                         runif(n()) < 0.10 & gender == \"M\" ~ paste(\"Shri\", reg_name),\n                         .default = reg_name),\n    reg_relation = messy(relation_name, 0.4, 0.15),\n    reg_relation = if_else(runif(n()) < 0.08, NA_character_, reg_relation),\n    reg_age = true_age + sample(c(0, 0, 0, 0, 1, -1, 1, 2, -2), n(), TRUE),\n    reg_age = if_else(runif(n()) < 0.15, 5 * round(true_age / 5), reg_age),  # age rounded\n    reg_village = messy(village, 0, 0.12)\n  )\n\n# Deaths of other persons in the block\nn_other <- 1050\nothers <- tibble(\n  gender      = sample(c(\"M\", \"F\"), n_other, TRUE),\n  surname     = sample(surnames, n_other, TRUE),\n  rel_first   = sample(male_first, n_other, TRUE),\n  reg_village = sample(villages, n_other, TRUE),\n  reg_age     = sample(35:95, n_other, TRUE),\n  date_of_death = as.Date(\"2022-04-01\") + sample(0:1004, n_other, TRUE)\n) |>\n  mutate(first = if_else(gender == \"M\", sample(male_first, n_other, TRUE),\n                         sample(female_first, n_other, TRUE)),\n         reg_name = if_else(gender == \"M\" | runif(n_other) < 0.5, paste(first, surname),\n                            paste(first, \"Devi\")),\n         reg_relation = paste(rel_first, surname))\n\n# Planted traps. Same name and village as a living pensioner, but a different person\nalive <- pensioners |> anti_join(dead, by = \"ben_id\") |> slice_sample(n = 12)\ntraps <- alive |>\n  transmute(gender, reg_name = name, reg_village = village,\n            reg_relation = paste(sample(male_first, 12, TRUE), word(name, -1)),\n            reg_age = sample(40:58, 12, TRUE),\n            date_of_death = as.Date(\"2022-04-01\") + sample(0:1004, 12, TRUE))\n\ndeaths <- bind_rows(\n  recorded |> select(ben_id, reg_name, reg_relation, gender, reg_age, date_of_death, reg_village),\n  others |> select(reg_name, reg_relation, gender, reg_age, date_of_death, reg_village),\n  traps\n) |>\n  slice_sample(prop = 1) |>\n  mutate(reg_no = sprintf(\"D/%d/%04d\", year(date_of_death), row_number()), .before = 1)\n\ntruth  <- deaths |> filter(!is.na(ben_id)) |> select(reg_no, ben_id)   # known only in simulation\ndeaths <- deaths |>\n  select(reg_no, name = reg_name, relation_name = reg_relation, gender,\n         age_at_death = reg_age, date_of_death, village = reg_village)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npensioners\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,000 × 8\n   ben_id    name         relation_name gender dob        village mobile pension\n   <chr>     <chr>        <chr>         <chr>  <date>     <chr>   <chr>    <dbl>\n 1 OAP-00001 Parvati Devi Sohan Chaura… F      1958-12-22 Tikamg… 68664…    1000\n 2 OAP-00002 Krishna Gup… Ram Gupta     M      1947-03-26 Jamunia <NA>      1000\n 3 OAP-00003 Ganga Ram C… Om Chaurasia  M      1959-09-30 Umaria  64313…    1000\n 4 OAP-00004 Geeta Devi   Shiv Jatav    F      1929-11-30 Tilakp… 87486…    1500\n 5 OAP-00005 Narendra Ra… Bhagwan Rath… M      1956-06-16 Hirapur 67852…    1000\n 6 OAP-00006 Mahendra Pal Budhram Pal   M      1935-05-05 Jaitpur 68478…    1500\n 7 OAP-00007 Rajendra Ku… Narendra Kum… M      1946-04-19 Kakrahi 85627…    1000\n 8 OAP-00008 Pushpa Tiwa… Gurmeet Tiwa… F      1939-09-21 Tikamg… 62873…    1500\n 9 OAP-00009 Kishan Verma Dinesh Verma  M      1954-07-19 Udaipu… <NA>      1000\n10 OAP-00010 Parvati Devi Govind Maurya F      1949-09-30 Sahjan… 75168…    1000\n# ℹ 2,990 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\ndeaths\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,212 × 7\n   reg_no      name      relation_name gender age_at_death date_of_death village\n   <chr>       <chr>     <chr>         <chr>         <dbl> <date>        <chr>  \n 1 D/2024/0001 Shakunta… Abdul Rashid… F                54 2024-08-25    Sahjan…\n 2 D/2023/0002 Prem Sha… Kishan Sharma M                67 2023-08-22    Jaitpur\n 3 D/2023/0003 Babu Cha… Narendra Cha… M                42 2023-03-02    Imlia  \n 4 D/2024/0004 Jaswant … Dinesh Verma  F                49 2024-04-28    Semri  \n 5 D/2022/0005 Bimla Pal Chhote Pal    F                76 2022-04-27    Sahjan…\n 6 D/2022/0006 Bhagwan … Abdul Rashid… M                74 2022-11-07    Narsin…\n 7 D/2024/0007 Radha Ba… Krishna Bagh… F                72 2024-03-30    Mehgaon\n 8 D/2024/0008 Harish P… Mahendra Pan… M                57 2024-02-18    Udaipu…\n 9 D/2023/0009 Kailash … Sohan Singh   M                50 2023-10-26    Dhaneta\n10 D/2022/0010 Sushila … Mahesh Ratho… F                46 2022-09-07    Chhapra\n# ℹ 1,202 more rows\n```\n\n\n:::\n:::\n\n\n## Step 1. Standardise {#sec-linkage-standardise}\n\nFirst, we remove the differences that carry no information. We write one function and apply it to every text field in *both* lists, so that both are cleaned in exactly the same way. It is similar to the `clean_name()` function of @sec-strsim, with words common in death registers, like *Late*, added.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstd_text <- function(x) {\n  x |>\n    str_to_lower() |>\n    str_replace_all(\"[[:punct:]]\", \" \") |>\n    str_replace_all(\"\\\\b(late|shri|sri|smt|shrimati|mr|mrs)\\\\b\", \" \") |>\n    str_replace_all(\"\\\\b(mohd|md)\\\\b\", \"mohammad\") |>\n    str_squish()\n}\n\nstd_text(c(\"Late Shri Ram Prasad\", \"Smt. Kamala Devi\", \"Mohd. Yusuf Khan\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ram prasad\"          \"kamala devi\"         \"mohammad yusuf khan\"\n```\n\n\n:::\n:::\n\n\nFor comparing names, we also remove the spaces, so that *Sita Ram* and *Sitaram*, or *Ram Kali* and *Ramkali*, become identical. We keep the version with spaces too, because we need the first word for blocking in the next step.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprepare <- function(df) {\n  df |>\n    mutate(name_std    = std_text(name),\n           name_cmp    = str_remove_all(name_std, \" \"),\n           rel_cmp     = str_remove_all(std_text(relation_name), \" \"),\n           village_cmp = str_remove_all(std_text(village), \" \"),\n           # phonetic code of the first word of the name, used for blocking\n           name_code   = double_metaphone(word(name_std, 1))$primary)\n}\n\npen <- prepare(pensioners)\ndth <- prepare(deaths)\n\ndth |> select(name, name_cmp, relation_name, rel_cmp, name_code) |> head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  name               name_cmp         relation_name       rel_cmp      name_code\n  <chr>              <chr>            <chr>               <chr>        <chr>    \n1 Shakuntala Rajput  shakuntalarajput Abdul Rashid Rajput abdulrashid… XKNTL    \n2 Prem Sharma        premsharma       Kishan Sharma       kishansharma PRM      \n3 Babu Chaurasia     babuchaurasia    Narendra Chaurasia  narendracha… PP       \n4 Jaswant Kaur Verma jaswantkaurverma Dinesh Verma        dineshverma  JSNT     \n5 Bimla Pal          bimlapal         Chhote Pal          chhotepal    PML      \n6 Bhagwan Patel      bhagwanpatel     Abdul Rashid Patel  abdulrashid… PKN      \n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## Audit tip\n\nStandardise both lists with the *same* function. A cleaning step applied to only one list creates differences instead of removing them. And always keep the original columns. The cleaned versions are for the computer; the original names are what we report.\n:::\n\n## Step 2. Block {#sec-linkage-block}\n\nHow many pairs could we compare?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(pen) * nrow(dth)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3636000\n```\n\n\n:::\n:::\n\n\nThat is more than 36 lakh pairs, for a single block. For a district, or a State, comparing every pair becomes impossible. But we do not need to. A pensioner of Amarpur is very unlikely to appear in the death register under Pipariya. So we compare only pairs which share a **blocking key**, here the same village and the same gender. A blocking key is a cheap test which every true pair is expected to pass.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs_village <- pen |>\n  inner_join(dth, by = c(\"village_cmp\", \"gender\"), relationship = \"many-to-many\") |>\n  select(ben_id, reg_no)\nnrow(pairs_village)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 44856\n```\n\n\n:::\n:::\n\n\nBlocking has reduced the work about 80 times. But it has a cost. If a true pair *fails* the blocking test, it is never compared, and so never found. Here, a death record whose village is misspelt, say *Chandanpur* for *Chandanpura*, would never be compared with the right pensioner.\n\nThe usual remedy is to block **twice**, with two different keys, and combine the pairs. Our second key is the phonetic code of the first word of the name, with gender. A misspelt village is now caught through the name, and a misspelt name through the village. Only a record with *both* wrong slips through.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs_name <- pen |>\n  inner_join(dth, by = c(\"name_code\", \"gender\"), relationship = \"many-to-many\") |>\n  select(ben_id, reg_no)\n\npairs <- bind_rows(pairs_village, pairs_name) |> distinct()\nc(village_block = nrow(pairs_village), name_block = nrow(pairs_name), combined = nrow(pairs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvillage_block    name_block      combined \n        44856         53807         97146 \n```\n\n\n:::\n:::\n\n\n\n\nWe now have 97,146 pairs to compare instead of 36 lakh. Since our data are simulated, we can peek at how many of the 150 true pairs survived. The village block alone kept 132, the name block alone 133, and the two together 147. Two keys are clearly better than one.\n\n::: callout-note\nGood blocking keys are fields that are rarely wrong and split the data into many small groups: village or PIN code, year of birth, gender, or a phonetic code of the surname. A key that is often wrong loses true pairs, and a key with few values, like gender alone, saves little work.\n:::\n\n## Step 3. Compare {#sec-linkage-compare}\n\nFor each pair, we now compare the fields one by one.\n\n- **Name**, **father's or husband's name** and **village**, with Jaro-Winkler similarity (@sec-strsim), which gives 1 for identical strings and less for different ones.\n- **Age**. The pension list has the date of birth, and the death register the age at death. From the date of birth and the date of death we can work out what the pensioner's age *would have been* at that death, and compare it with the recorded age.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompared <- pairs |>\n  left_join(pen |> select(ben_id, name_p = name_cmp, rel_p = rel_cmp,\n                          village_p = village_cmp, dob), by = \"ben_id\") |>\n  left_join(dth |> select(reg_no, name_d = name_cmp, rel_d = rel_cmp,\n                          village_d = village_cmp, age_at_death, date_of_death), by = \"reg_no\") |>\n  mutate(name_sim    = stringsim(name_p, name_d, method = \"jw\", p = 0.1),\n         rel_sim     = stringsim(rel_p, rel_d, method = \"jw\", p = 0.1),\n         village_sim = stringsim(village_p, village_d, method = \"jw\", p = 0.1),\n         age_gap     = abs(floor(as.numeric(date_of_death - dob) / 365.25) - age_at_death))\n\n# a few pairs whose names are close but not identical\ncompared |>\n  filter(name_sim > 0.9, name_sim < 1, !is.na(rel_sim)) |>\n  select(name_p, name_d, rel_p, rel_d, name_sim, rel_sim, village_sim, age_gap) |>\n  mutate(across(ends_with(\"sim\"), \\(x) round(x, 2))) |>\n  arrange(age_gap) |>\n  slice(c(1:3, n() - 2:0))   # three with close ages, three far apart\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  name_p         name_d         rel_p rel_d name_sim rel_sim village_sim age_gap\n  <chr>          <chr>          <chr> <chr>    <dbl>   <dbl>       <dbl>   <dbl>\n1 radhamishra    radhamisra     gang… gang…     0.98    1           1          0\n2 surendrajatav  surenderjatav  dine… dine…     0.94    0.98        1          0\n3 shakuntalasahu shakuntalaver… ramp… mahe…     0.9     0.5         1          0\n4 gayatridevi    gayatriyadav   prem… kish…     0.91    0.44        0.66      62\n5 mahendrakori   mahendralodhi  mang… sure…     0.92    0.52        0.48      63\n6 gayatridevi    gayatriyadav   raje… kish…     0.91    0.54        0.67      63\n```\n\n\n:::\n:::\n\n\nThe first two, with the same age and nearly the same father's name, look like the same person written differently (*Misra* for *Mishra*, *Surender* for *Surendra*). The third has the same first name and age, but a different surname and father, so is probably someone else. The last three, decades apart in age, are clearly different people, despite their similar names. No single field decides; we need to weigh them together.\n\nSimilarities are numbers between 0 and 1. To weigh them in the next step, it is simpler to sort each comparison into a few **levels**.\n\n| Field | Agree | Partly agree | Disagree | Far apart |\n|-------|-------|------|------|------|\n| Name | similarity 0.95 or more | 0.90 to 0.95 | below 0.90 | |\n| Father's or husband's name | 0.95 or more | 0.90 to 0.95 | below 0.90 | |\n| Village | 0.88 or more | | below 0.88 | |\n| Age | differs by 0 or 1 year | 2 or 3 years | 4 to 10 years | more than 10 years |\n\n: Comparison levels {#tbl-linkage-levels}\n\nA missing father's or husband's name gives the level *missing*. The age levels allow for the common rounding of age in death registers. A gap of more than 10 years is almost impossible for the same person, so it gets a level of its own. We write the levels as a function, because we will need it twice.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadd_levels <- function(df) {\n  df |>\n    mutate(\n      name_lvl    = case_when(name_sim >= 0.95 ~ \"agree\", name_sim >= 0.90 ~ \"partial\",\n                              .default = \"disagree\"),\n      rel_lvl     = case_when(is.na(rel_sim) ~ \"missing\", rel_sim >= 0.95 ~ \"agree\",\n                              rel_sim >= 0.90 ~ \"partial\", .default = \"disagree\"),\n      village_lvl = if_else(village_sim >= 0.88, \"agree\", \"disagree\"),\n      age_lvl     = case_when(age_gap <= 1 ~ \"agree\", age_gap <= 3 ~ \"partial\",\n                              age_gap <= 10 ~ \"disagree\", .default = \"far\"))\n}\ncompared <- add_levels(compared)\n```\n:::\n\n\n## Step 4. Weigh the evidence {#sec-linkage-weigh}\n\nNow the central question. For a given pair, the name agrees, the village agrees, the age is two years off and the father's name is missing. Is that the same person? We need a way to add up the evidence. The method used almost everywhere, by statistics offices and census bureaus, was set out by *Fellegi and Sunter* in 1969. Its idea is simple, and every auditor already uses it by instinct.\n\n**Not all agreements are equal.** Suppose two records agree on gender. That means almost nothing, since half of all pairs of people agree on gender by chance. Now suppose they agree on the full name *Rameshwar Kushwaha*. That means a lot, because two different people rarely share such a name. Agreement on something that is *rarely* shared by chance is *strong* evidence.\n\nFor each field, and each level, we need two probabilities.\n\n- **m**, the chance of this level when the two records *are* the same person. It measures how *reliable* the field is. If the same person's name is written identically in both lists 85% of the time, then m for name \"agree\" is 0.85.\n- **u**, the chance of this level when the two records are *different* people. It measures *coincidence*. If two random people have matching names once in 400 pairs, then u for name \"agree\" is 0.0025.\n\nThe **weight** of the evidence is then\n\n$$\\text{weight} = \\log_2\\left(\\frac{m}{u}\\right)$$\n\nIf m is much larger than u, the level is far more likely for a true pair than for a false one, and the weight is large and positive. If m is smaller than u, as for \"disagree\", the weight is negative, evidence *against* a match. The logarithm to base 2 makes the weights add up. Each point of weight doubles the odds that the pair is a match.\n\n**Estimating u.** The chance of a coincidence can be measured from the data itself. Pair up records at random, thousands of times. Almost all random pairs are different people, so the share of random pairs at each level is a good estimate of u. We must use *random* pairs, not our blocked pairs, because pairs from the same village obviously agree on village far more often than random people do.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(99)\nrandom_pairs <- tibble(i = sample(nrow(pen), 20000, TRUE),\n                       j = sample(nrow(dth), 20000, TRUE)) |>\n  transmute(name_sim    = stringsim(pen$name_cmp[i], dth$name_cmp[j], method = \"jw\", p = 0.1),\n            rel_sim     = stringsim(pen$rel_cmp[i], dth$rel_cmp[j], method = \"jw\", p = 0.1),\n            village_sim = stringsim(pen$village_cmp[i], dth$village_cmp[j], method = \"jw\", p = 0.1),\n            age_gap     = abs(floor(as.numeric(dth$date_of_death[j] - pen$dob[i]) / 365.25) -\n                                dth$age_at_death[j])) |>\n  add_levels()\n\nu_values <- bind_rows(\n  random_pairs |> count(level = name_lvl)    |> mutate(field = \"name\"),\n  random_pairs |> count(level = rel_lvl)     |> mutate(field = \"relation\"),\n  random_pairs |> count(level = village_lvl) |> mutate(field = \"village\"),\n  random_pairs |> count(level = age_lvl)     |> mutate(field = \"age\")\n) |>\n  mutate(u = n / sum(n), .by = field) |>\n  select(field, level, u)\n```\n:::\n\n\n**Setting m.** The reliability of each field is set from experience, and checked against a few pairs confirmed by hand. In our district, names are written the same way in most records, villages almost always, and ages, because of rounding, are often a year or two off.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_values <- tribble(\n  ~field,     ~level,     ~m,\n  \"name\",     \"agree\",    0.85,\n  \"name\",     \"partial\",  0.12,\n  \"name\",     \"disagree\", 0.03,\n  \"relation\", \"agree\",    0.80,\n  \"relation\", \"partial\",  0.10,\n  \"relation\", \"disagree\", 0.03,\n  \"village\",  \"agree\",    0.98,\n  \"village\",  \"disagree\", 0.02,\n  \"age\",      \"agree\",    0.75,\n  \"age\",      \"partial\",  0.20,\n  \"age\",      \"disagree\", 0.045,\n  \"age\",      \"far\",      0.005\n)\n\nweights <- m_values |>\n  left_join(u_values, by = c(\"field\", \"level\")) |>\n  mutate(weight = round(log2(m / u), 2))\nweights |> mutate(u = signif(u, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 5\n   field    level        m      u weight\n   <chr>    <chr>    <dbl>  <dbl>  <dbl>\n 1 name     agree    0.85  0.0024   8.44\n 2 name     partial  0.12  0.0022   5.74\n 3 name     disagree 0.03  1       -5.05\n 4 relation agree    0.8   0.0012   9.32\n 5 relation partial  0.1   0.004    4.66\n 6 relation disagree 0.03  0.99    -5.04\n 7 village  agree    0.98  0.025    5.3 \n 8 village  disagree 0.02  0.98    -5.61\n 9 age      agree    0.75  0.054    3.8 \n10 age      partial  0.2   0.068    1.56\n11 age      disagree 0.045 0.21    -2.25\n12 age      far      0.005 0.67    -7.06\n```\n\n\n:::\n:::\n\n\n\n\nRead the table like a reviewer. Agreement on the name adds 8.44 points, because a coincidental name match is rare. Agreement on the village adds only 5.3, because one in 40 random pairs share a village anyway. An age more than 10 years apart takes away 7.06 points, strong evidence that these are two different people. A missing father's name gives no evidence either way, so we give it a weight of 0.\n\nNow each pair gets a total score, the sum of its weights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweight_of <- function(field, level) {\n  weights$weight[match(paste(field, level), paste(weights$field, weights$level))]\n}\n\nscored <- compared |>\n  mutate(w_name     = weight_of(\"name\", name_lvl),\n         w_relation = if_else(rel_lvl == \"missing\", 0, weight_of(\"relation\", rel_lvl)),\n         w_village  = weight_of(\"village\", village_lvl),\n         w_age      = weight_of(\"age\", age_lvl),\n         score      = w_name + w_relation + w_village + w_age)\n```\n:::\n\n\nLet us see how the score handles the two kinds of difficult pair we met at the start: a true pair written differently, and a trap, two different persons with the same name in the same village.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscored |>\n  filter(name_lvl == \"agree\", village_lvl == \"agree\") |>\n  slice(c(which.min(score), which.max(score))) |>\n  select(name_p, name_d, rel_p, rel_d, age_gap, w_name, w_relation, w_village, w_age, score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 10\n  name_p      name_d rel_p rel_d age_gap w_name w_relation w_village w_age score\n  <chr>       <chr>  <chr> <chr>   <dbl>  <dbl>      <dbl>     <dbl> <dbl> <dbl>\n1 urmiladevi  urmil… shiv… laxm…      35   8.44      -5.04       5.3 -7.06  1.64\n2 radhamishra radha… gang… gang…       0   8.44       9.32       5.3  3.8  26.9 \n```\n\n\n:::\n:::\n\n\n\n\nThe first row has the same name and village, but a different father's or husband's name and an age gap of 35 years. Its score of 1.6 says clearly that these are two different persons, however alike the names. A name-only match would have reported this pensioner as dead. The second row agrees on everything, and scores 26.9.\n\n## Step 5. Decide {#sec-linkage-decide}\n\nLet us look at the scores of all the pairs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscored |>\n  filter(score > -5) |>\n  ggplot(aes(score)) +\n  geom_histogram(binwidth = 1, fill = \"steelblue\", colour = \"white\") +\n  geom_vline(xintercept = c(10, 20), linetype = \"dashed\") +\n  annotate(\"text\", x = c(4, 15, 26), y = Inf, vjust = 1.5,\n           label = c(\"Reject\", \"Review\", \"Link\")) +\n  labs(x = \"Total score (weight of evidence)\", y = \"Number of pairs\",\n       subtitle = \"Only pairs with score above -5 are shown\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Scores of the compared pairs. Most pairs are clearly different persons; the true matches form the hump on the right.](20b-record-linkage_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nMost pairs score far below zero, and are clearly different people. A separate hump of high scores on the right holds the likely matches. In between is a grey zone. So we set **two** cut-offs, not one.\n\n- **Score of 20 or more: link.** The evidence is overwhelming.\n- **Score from 10 to 20: review.** The data cannot decide. These pairs go for manual checking, of the files, or in the field.\n- **Score below 10: reject.**\n\nThe cut-offs are chosen by reading the pairs around them, as in @sec-strsim, and by how many pairs the audit team can review. They are not fixed numbers to be used everywhere.\n\n## Step 6. One record, one partner {#sec-linkage-onetoone}\n\nA pensioner can die only once, and a death record belongs to only one person. But a common name may give a death record high scores with two pensioners. We keep, for each record, only its best partner. The simplest way is to go down the pairs from the highest score, and accept a pair only if neither of its records has been used already.\n\n\n::: {.cell}\n\n```{.r .cell-code}\none_to_one <- function(candidates) {\n  candidates <- candidates |> arrange(desc(score))\n  used_ben <- character()\n  used_reg <- character()\n  keep <- logical(nrow(candidates))\n  for (k in seq_len(nrow(candidates))) {\n    if (!(candidates$ben_id[k] %in% used_ben) && !(candidates$reg_no[k] %in% used_reg)) {\n      keep[k]  <- TRUE\n      used_ben <- c(used_ben, candidates$ben_id[k])\n      used_reg <- c(used_reg, candidates$reg_no[k])\n    }\n  }\n  candidates[keep, ]\n}\n\ndecided <- scored |>\n  filter(score >= 10) |>\n  one_to_one() |>\n  mutate(decision = if_else(score >= 20, \"Link\", \"Review\"))\ncount(decided, decision)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  decision     n\n  <chr>    <int>\n1 Link       127\n2 Review      50\n```\n\n\n:::\n:::\n\n\nWe used a `for` loop from @sec-control, because each decision depends on the ones before it.\n\n## Step 7. Check the result {#sec-linkage-check}\n\nIn a real audit, we would now verify a sample of the links from the files, and all the review cases, before reporting anything. Since our data are simulated, we can also measure exactly how well the linkage did, using the `truth` table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquality <- decided |>\n  left_join(truth |> mutate(true_pair = TRUE), by = c(\"reg_no\", \"ben_id\")) |>\n  mutate(true_pair = coalesce(true_pair, FALSE))\n\nquality |>\n  summarise(pairs = n(), true_pairs = sum(true_pair), .by = decision)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  decision pairs true_pairs\n  <chr>    <int>      <int>\n1 Link       127        127\n2 Review      50         18\n```\n\n\n:::\n:::\n\n\n\n\n- All 127 automatic links are in fact true pairs (127 correct). The two-cut-off design keeps automatic decisions to the cases where the evidence is overwhelming.\n- The 50 pairs for review contain 18 more true pairs. The rest are different persons with similar details, mostly the same common name in the same village with a different father's name, which a reviewer can reject quickly.\n- Of the 150 deceased pensioners, 5 were not found at all. Some were lost at blocking, with both the village and the name written differently. Others lost out to a namesake in step 6.\n\nLet us look at one of the hard cases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhard_case <- dth |> filter(name_cmp == \"ramratidevi\", village_cmp == \"kundalpur\", is.na(rel_cmp))\n\nscored |>\n  filter(reg_no %in% hard_case$reg_no, score >= 10) |>\n  left_join(truth |> mutate(true_pair = TRUE), by = c(\"reg_no\", \"ben_id\")) |>\n  mutate(true_pair = coalesce(true_pair, FALSE)) |>\n  select(reg_no, ben_id, name_p, name_d, rel_p, rel_d, age_gap, score, true_pair)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  reg_no      ben_id    name_p      name_d   rel_p rel_d age_gap score true_pair\n  <chr>       <chr>     <chr>       <chr>    <chr> <chr>   <dbl> <dbl> <lgl>    \n1 D/2022/0959 OAP-00355 ramratidevi ramrati… govi… <NA>        1  17.5 FALSE    \n2 D/2022/0959 OAP-01092 ramratidevi ramrati… shan… <NA>        0  17.5 TRUE     \n3 D/2022/0959 OAP-01286 ramratidevi ramrati… mahe… <NA>        0  17.5 FALSE    \n```\n\n\n:::\n:::\n\n\nA *Ramrati Devi* of Kundalpur appears in the death register without her husband's name. Three pensioners of that name live in Kundalpur, and all three have an age within a year of the recorded age. On the record, they are equally likely, with the same score. Step 6 had to pick one, and picked the wrong one. No method can decide such a case from the data. It needs a visit, or a look at the death certificate. This is the honest limit of record linkage, and why its results are leads for verification, never findings by themselves.\n\n::: callout-caution\nRecord linkage always makes some mistakes in both directions: false links, and missed links. A false link can mean stopping the pension of a living, poor person. So never act, or report, on a link without verifying it. Report the method, the cut-offs and the number of links verified, along with the findings.\n:::\n\n## The audit finding {#sec-linkage-finding}\n\nLet us now value the finding, for the automatic links, assuming that each was verified. Pension continued after the month of death until March 2025.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverpaid <- decided |>\n  filter(decision == \"Link\") |>\n  left_join(pensioners |> select(ben_id, name, village, pension), by = \"ben_id\") |>\n  left_join(deaths |> select(reg_no, death_name = name), by = \"reg_no\") |>\n  mutate(months_after_death = interval(date_of_death, as.Date(\"2025-03-31\")) %/% months(1),\n         amount = months_after_death * pension)\n\noverpaid |>\n  select(ben_id, name, death_name, village, date_of_death, months_after_death, amount) |>\n  arrange(desc(amount)) |>\n  head(8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 7\n  ben_id    name      death_name village date_of_death months_after_death amount\n  <chr>     <chr>     <chr>      <chr>   <date>                     <dbl>  <dbl>\n1 OAP-01645 Gayatri … Gatri Devi Rampura 2022-04-15                    35  52500\n2 OAP-01857 Om Singh  Om Singh   Umaria  2022-04-01                    35  52500\n3 OAP-00385 Prem Cha… Pre Chaur… Rajapur 2022-04-07                    35  52500\n4 OAP-01584 Bharat J… Bharat Ja… Khajuri 2022-04-24                    35  52500\n5 OAP-00550 Sohan Ko… Sohan Kori Bilkhe… 2022-05-28                    34  51000\n6 OAP-02974 Sughra D… Sughra evi Amarpur 2022-05-07                    34  51000\n7 OAP-01353 Sushila … Late Sush… Hirapur 2022-05-07                    34  51000\n8 OAP-02011 Shanti D… Sani Devi  Nayaga… 2022-05-25                    34  51000\n```\n\n\n:::\n\n```{.r .cell-code}\noverpaid |>\n  summarise(deceased_pensioners = n(), total_overpaid = sum(amount))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  deceased_pensioners total_overpaid\n                <int>          <dbl>\n1                 127        3039500\n```\n\n\n:::\n:::\n\n\n\n\nPension of about ₹30.4 lakh was paid to 127 persons after their death, in one block alone, and more may follow from the review cases. Beyond the money, the finding points to a control failure. The pension sanctioning authority was not receiving, or not acting on, information from the registrar of births and deaths. That systemic weakness is often the more important part of the audit observation.\n\n## Other uses, and linking a list with itself {#sec-linkage-other}\n\nThe same seven steps work for every audit linkage. Only the fields change.\n\n| Audit question | Lists to link | Useful fields |\n|------------------------|------------------------|------------------------|\n| Government employees in a scheme for the poor | Scheme beneficiaries, payroll or pension data | Name, father's name, date of birth, address, bank account |\n| Same beneficiary in two schemes | The two beneficiary lists | Name, father's name, age, village, bank account, mobile |\n| Conflict of interest | Employees, proprietors and partners of suppliers | Name, father's name, address, PAN, mobile, bank account |\n| Scholarship from two States | The two scholarship lists | Name, date of birth, institution, course, bank account |\n| Ration cards of income tax payers | Ration card holders, tax data | Name, address, PAN, mobile |\n\n: Common audit uses of record linkage {#tbl-linkage-uses}\n\nWhere a field like a mobile number, PAN or bank account is available, standardise it with the functions of @sec-regex-validate, such as `clean_mobile()`, and validate it with the check digits of @sec-checkdigits. An exact match on a valid identifier is very strong evidence, and gets a large weight.\n\n**Deduplication.** To find the same person entered twice in *one* list, say a pensioner drawing two pensions under different IDs, link the list with itself. In step 2, join the list to itself on the blocking key, keeping each pair only once with `join_by(ben_id < ben_id)`, as in @sec-dup-fuzzy. The remaining steps are the same.\n\n::: callout-note\n## Packages for record linkage\n\nWe built every step ourselves, so that each is clear. For regular work, two packages are worth knowing. `reclin2` provides functions for each of the steps above. `fastLink` estimates the m and u probabilities from the data itself, using the *EM algorithm*, instead of setting m by judgement, and handles large lists efficiently. A further refinement, offered by both, is to give agreement on a *rare* name more weight than agreement on a common one like *Vimla Devi*.\n:::\n\n::: callout-warning\n## Privacy\n\nRecord linkage brings together personal data from different sources, which is exactly what makes it powerful and sensitive. Do it only on secure systems approved for such data, keep the linked data no longer than needed, and report individual details only where the audit requires it. Never upload such lists to online tools or AI chatbots.\n:::\n\n## A suggested workflow\n\n1. **Frame the question**, and the lists to link. Is there a reliable common identifier? If so, an exact join may be enough.\n2. **Standardise** every field in both lists with the same functions, keeping the originals.\n3. **Block** with two or more keys, and combine the pairs.\n4. **Compare** each field with a suitable measure, and sort the results into levels.\n5. **Weigh** each level by log~2~(m/u), estimating u from random pairs and m from experience or a checked sample.\n6. **Score** each pair, look at the distribution of scores, and set two cut-offs: link, and review.\n7. **Keep one partner per record.**\n8. **Verify** all review cases and a sample of the links, before reporting.\n9. **Value the finding**, and look for the control weakness behind it.\n\n::: callout-important\n## Remember\n\n- Record linkage finds the same person in two lists when there is no common key.\n- Use several fields together. A name alone, especially a common one, proves nothing.\n- Blocking makes linkage feasible; blocking with two keys keeps it from losing true pairs.\n- Agreement on something rarely shared by chance is strong evidence; the weight log~2~(m/u) captures this.\n- Use two cut-offs, and send the grey zone for manual review.\n- Every link is a lead to be verified, never a finding by itself.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `str_to_lower()`, `str_replace_all()`, `str_remove_all()`, `str_squish()` | stringr | Standardise text fields |\n| `double_metaphone()` | fullmetaphone | Phonetic code, used as a blocking key |\n| `inner_join(relationship = \"many-to-many\")` | dplyr | Form the candidate pairs within each block |\n| `bind_rows()`, `distinct()` | dplyr | Combine the pairs from two blocking keys |\n| `stringsim(method = \"jw\")` | stringdist | Jaro-Winkler similarity of two strings |\n| `case_when()` | dplyr | Sort similarities into comparison levels |\n| `count()`, `tribble()` | dplyr, tibble | Estimate u from random pairs, and write m by hand |\n| `log2()` | base R | Weight of evidence, log~2~(m/u) |\n| `semi_join()`, `anti_join()` | dplyr | Check pairs against the truth, or find unmatched records |\n| `interval()`, `months()` | lubridate | Months of pension paid after death |\n\n: Functions used in this chapter {#tbl-linkagefunctions}\n",
    "supporting": [
      "20b-record-linkage_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}