{
  "hash": "d4f145d144aeedd30650d052373cc01f",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Multiple Regression in Audit {#sec-mregression}\n\nIn @sec-regression we explained the office expenses of block offices by one driver, their staff strength. That model found one of the two offices we had planted. It missed the other. It also pointed to several offices in the hills which may have done nothing wrong. One driver is rarely enough. The expenses of an office also depend on the beneficiaries it serves and on the terrain it covers.\n\nAn auditor meets this in most data. The cost of a road depends on its width, the terrain, the lead and the price of bitumen. The salary bill of an office depends on its staff and on the class of its city, which fixes the house rent allowance. Multiple regression lets us use all these drivers together. It gives a fairer expected amount for every unit. The units which spend more than expected then stand out more clearly, and innocent units drop away.\n\nWe end the chapter with the question we posed at the start of @sec-regression. Which offices spend much more on salary than their staff strength explains? That is where ghost employees hide.\n\nIn this chapter we will learn to\n\n- use several predictors together, including categories like terrain, and interactions,\n- detect predictors which repeat each other's information (multi-collinearity),\n- avoid being misled by a hidden variable (Simpson's paradox), and\n- finally, flag offices which spend more than expected, and measure the excess in rupees.\n\n## Prerequisites\n\nWe use the same packages as in @sec-regression, and three more. `car` calculates the variance inflation factor. `GGally` draws correlation plots and `moderndive` draws parallel slopes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(performance)\nlibrary(car)\nlibrary(GGally)\nlibrary(moderndive)\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## The block office data\n\nWe continue with the office expenses of block offices, described in @sec-reg-data. For each office we know its district and terrain, its staff in position and sanctioned posts, the floor area of its building, the population of its block and the beneficiaries it serves. We also know its office expenses for 2023-24, in ₹ lakh. Two offices have expenses inflated by ₹11 lakh each, as if vehicle hire was paid for vehicles never used. The code below creates exactly the same data as before.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the block office data\"}\nset.seed(4012)\nn <- 120\ndistrict_terrain <- c(Etawah = \"Plain\", Sitapur = \"Plain\", Firozpur = \"Plain\",\n                      Almora = \"Hilly\", Chamba = \"Hilly\",\n                      Bastar = \"Tribal\", Mayurbhanj = \"Tribal\")\nbdo <- tibble(\n  office_id = sprintf(\"BDO-%03d\", 1:n),\n  district  = sample(names(district_terrain), n, replace = TRUE,\n                     prob = c(0.17, 0.17, 0.16, 0.13, 0.12, 0.13, 0.12))\n) |>\n  mutate(\n    terrain = factor(district_terrain[district], levels = c(\"Plain\", \"Hilly\", \"Tribal\")),\n    # offices in the hills and tribal areas are smaller\n    staff = round(case_when(terrain == \"Plain\" ~ runif(n, 22, 55),\n                            terrain == \"Hilly\" ~ runif(n, 12, 38),\n                            TRUE               ~ runif(n, 16, 44))),\n    sanctioned    = round(staff / runif(n, 0.80, 0.95)),\n    # bigger offices have bigger buildings\n    area_sqm      = round(120 + 11 * staff + rnorm(n, 0, 45)),\n    population    = round(runif(n, 60, 200) * if_else(terrain == \"Plain\", 1.2, 0.8)),\n    beneficiaries = round(population * runif(n, 0.25, 0.35), 1),\n    # office expenses in lakh, driven by staff, beneficiaries and terrain\n    office_exp = round(5 + 0.45 * staff + 0.12 * beneficiaries +\n                       c(Plain = 0, Hilly = 6, Tribal = 3.5)[as.character(terrain)] +\n                       rnorm(n, 0, 1.6), 2)\n  )\n\n# Planted cases. Vehicle hire of Rs 11 lakh paid without any vehicle used\nplanted <- c(\"BDO-027\", \"BDO-088\")\nbdo <- bdo |>\n  mutate(office_exp = if_else(office_id %in% planted, office_exp + 11, office_exp))\n```\n:::\n\n\nWe will compare our new models with the model of staff alone, `lin_reg1`, from @sec-regression. So let us fit it again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlin_reg1 <- lm(office_exp ~ staff, data = bdo)\n```\n:::\n\n\n## Multiple linear regression\n\nIn multiple linear regression, several independent variables together explain the dependent variable. The regression equation becomes\n\n$$\ny = \\beta_0 + \\beta_1x_1 + \\beta_2x_2 + \\beta_3x_3 + ... + \\epsilon\n$$ {#eq-lr12}\n\nwhere $x_1$, $x_2$, $x_3$ ..., $x_n$ are the $n$ independent variables and $y$ is the dependent variable as usual.\n\nWith two predictors, this equation is no longer a line but a flat *plane* in three dimensions. With more predictors, it is a *hyperplane*, which we cannot draw. So we usually look at the predictors one at a time, or use correlation plots.\n\nAs we noted in @sec-regression, there is one more assumption now. **The independent variables should not be strongly related to each other, that is, there should be no multi-collinearity.** Let us build an example. We just add the predictors to the formula using the `+` operator.\n\n**Example 2.** Staff strength alone explained about 60% of the variation in office expenses. Let us try to explain office expenses using staff strength `staff`, floor area of the building `area_sqm` and the number of beneficiaries `beneficiaries` together. First, let us visualise each relationship separately, in @fig-ex2vis.\n\n::: {#fig-ex2vis}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-4Reg-multiple_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=31%}\n:::\n\n::: {.cell-output-display}\n![](12-4Reg-multiple_files/figure-html/unnamed-chunk-5-2.png){fig-align='center' width=31%}\n:::\n\n::: {.cell-output-display}\n![](12-4Reg-multiple_files/figure-html/unnamed-chunk-5-3.png){fig-align='center' width=31%}\n:::\n:::\n\n\nRelationship between each predictor and office expenses\n:::\n\nLet us also visualise the correlation between all these variables. See @fig-ex2vis2.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Correlation between the variables in Example 2](12-4Reg-multiple_files/figure-html/fig-ex2vis2-1.png){#fig-ex2vis2 fig-align='center' width=672}\n:::\n:::\n\n\nNotice that two of the predictors are strongly correlated with each other too. Staff strength and floor area have a correlation of 0.93. Offices with more staff need bigger buildings. Keep this in mind. Now let us build the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata2 <- bdo[, c(\"office_exp\", \"staff\", \"area_sqm\", \"beneficiaries\")]\nlin_reg2 <- lm(office_exp ~ .,\n               data = data2)\nsummary(lin_reg2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = office_exp ~ ., data = data2)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-6.447 -1.860  0.174  1.697  7.215 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   14.278375   1.263300  11.302  < 2e-16 ***\nstaff          0.343135   0.068615   5.001 2.05e-06 ***\narea_sqm      -0.002411   0.006299  -0.383 0.702572    \nbeneficiaries  0.065658   0.017518   3.748 0.000279 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.762 on 116 degrees of freedom\nMultiple R-squared:  0.6407,\tAdjusted R-squared:  0.6314 \nF-statistic: 68.96 on 3 and 116 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nIn the formula, we used `.` instead of naming all the variables. The `.` is a shorthand for \"all other columns of the data\". There is now one slope for each predictor and one intercept. The equation can be written as @eq-lr13.\n\n$$\n\\text{Office expenses} = 14.2784 + 0.3431 \\cdot \\text{Staff} - 0.002411 \\cdot \\text{Area} + 0.0657 \\cdot \\text{Beneficiaries}\n$$ {#eq-lr13}\n\n**Interpretation.** The slopes of staff and beneficiaries are positive, so office expenses rise with both. Each slope is read *keeping the other variables constant*. For example, if two offices have the same floor area and the same number of beneficiaries, the one with 1 more employee spends ₹0.343 lakh more a year. Similarly, 1,000 more beneficiaries add ₹0.066 lakh, for the same staff and floor area. \"Keeping other variables constant\" is important. If the other variables also change, the effect on expenses is different.\n\n**Results.** The model explains about 64% of the variation in office expenses (Multiple R-squared), against 60% with staff alone. Adjusted R-squared is a little lower, at 63%, after the penalty for three predictors. The F-test p-value is very small, so at least one slope is not zero.\n\nLook at `area_sqm`, however. On its own, floor area is clearly related to office expenses (@fig-ex2vis, middle). In this model, its slope is -0.0024, slightly *negative*, as if a bigger building cost less to run. Its p-value is 0.70, not significant at all. This is because `area_sqm` carries almost the same information as `staff`. Once staff is in the model, area has little new to say, and its slope is left to chance. We could remove `area_sqm` and re-run the model. We will come back to this when we discuss multi-collinearity.\n\n## Including categorical or factor variables in `lm`\n\nSo far, both our response variable and our predictors were numeric. But what if a predictor is categorical, like the terrain of a block, the city class of an office, or the type of a contract?\n\nIn such a case, we should make sure that the categorical variable is of type `factor` before building the model. We learnt about factors in @sec-factors. The first level of the factor matters, as we will see. We created `terrain` with the levels in the order Plain, Hilly, Tribal.\n\n**Example 3.** Let us try to explain `office_exp` by `terrain` alone. Offices in the hills and tribal areas need more vehicle hire to cover the same block, so we would expect them to spend more. `terrain` is already a factor, so we need not convert it. Before moving on, let us visualise the relationship. Box plots are best suited here.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Office expenses by terrain](12-4Reg-multiple_files/figure-html/fig-fact1-1.png){#fig-fact1 fig-align='center' width=672 height=30%}\n:::\n:::\n\n\nNow let us build the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_fact <- lm(office_exp ~ terrain, data = bdo)\nsummary(lm_fact)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = office_exp ~ terrain, data = bdo)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-9.6503 -3.3458  0.0324  3.3282 11.1032 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    27.3068     0.5985  45.622   <2e-16 ***\nterrainHilly   -1.6142     0.9792  -1.648    0.102    \nterrainTribal  -1.4965     1.0307  -1.452    0.149    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.519 on 117 degrees of freedom\nMultiple R-squared:  0.02967,\tAdjusted R-squared:  0.01308 \nF-statistic: 1.789 on 2 and 117 DF,  p-value: 0.1718\n```\n\n\n:::\n:::\n\n\nWe now got one intercept and *two* slopes for a single predictor `terrain`. What happened?\n\n**Interpretation.** R converts a factor into *dummy variables*. A dummy variable is 1 when a row belongs to a category and 0 otherwise. Being numeric, the dummies can be used in linear regression as before. The first level of the factor is taken as the *baseline*. It gets no dummy of its own. `terrain` has three levels, so it is encoded as two dummy variables. To see this, we can use the `contrasts()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(bdo$terrain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Hilly Tribal\nPlain      0      0\nHilly      1      0\nTribal     0      1\n```\n\n\n:::\n:::\n\n\nWe can also see the actual numbers that went into the model with `model.matrix()`. Let us look at the first office of each terrain.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfirst_rows <- match(levels(bdo$terrain), bdo$terrain)\nmodel.matrix(office_exp ~ terrain, data = bdo)[first_rows, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept) terrainHilly terrainTribal\n2           1            0             0\n7           1            1             0\n1           1            0             1\n```\n\n\n:::\n:::\n\n\nWhen the office is in the hills, `terrainHilly` is `1` and `terrainTribal` is `0`, and the other way round for a tribal area. When both are `0`, the office is in the plains, the baseline. That is why there is no separate coefficient for `Plain`. Now we can write the regression equation as @eq-lr14.\n\n$$\n\\text{Office expenses} = 27.307 - 1.614 \\cdot \\text{terrainHilly} - 1.496 \\cdot \\text{terrainTribal}\n$$ {#eq-lr14}\n\nReading this equation is now easy. For an office in the hills, the predicted expense is 27.307 - 1.614, or 25.693. When both dummy variables are zero, the predicted expense is just the intercept. So the intercept is the prediction for the baseline level, `Plain`, and each slope is the *difference* from the baseline. If we remove the intercept by adding `- 1` to the formula, R gives us one coefficient for each level directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_fact0 <- lm(office_exp ~ terrain -1, data = bdo)\nsummary(lm_fact0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = office_exp ~ terrain - 1, data = bdo)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-9.6503 -3.3458  0.0324  3.3282 11.1032 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \nterrainPlain   27.3068     0.5985   45.62   <2e-16 ***\nterrainHilly   25.6926     0.7750   33.15   <2e-16 ***\nterrainTribal  25.8103     0.8391   30.76   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.519 on 117 degrees of freedom\nMultiple R-squared:  0.9724,\tAdjusted R-squared:  0.9717 \nF-statistic:  1376 on 3 and 117 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n**Results.** Compare these coefficients with @fig-fact1. They are nothing but the mean office expenses of each terrain, which is logical. The equation without intercept is @eq-lr15.\n\n$$\n\\text{Office expenses} = 27.307 \\cdot \\text{terrainPlain} + 25.693 \\cdot \\text{terrainHilly} + 25.810 \\cdot \\text{terrainTribal}\n$$ {#eq-lr15}\n\nSince these coefficients are not slopes in the true sense, we will call them intercepts in the next examples.\n\nThere is a surprise here. Offices in the hills and tribal areas seem to spend *less* than offices in the plains, not more. And the p-values of the two slopes in `lm_fact`, 0.10 and 0.15, say that terrain makes no real difference at all. Should we conclude that terrain does not matter? Not yet. We will find the answer in the next section.\n\n::: callout-warning\n## Caution\n\nLook at the R-squared of the two models. With an intercept it is 0.030. Without an intercept it jumps to 0.972. The fit has not improved at all, since the predictions are exactly the same. Without an intercept, R measures R-squared against zero instead of against the mean, which makes it look much larger. So use `- 1` to *read* the coefficients easily, but compare models using the version with an intercept.\n:::\n\n### Parallel slopes regression\n\nTo understand how a categorical predictor works together with a numeric one, let us build a model step by step.\n\n**Example 4.** Let us explain office expenses `office_exp` by staff strength `staff` and terrain `terrain` together. Let us visualise the variables first. From @fig-ex4vis it is clear that office expenses rise linearly with staff, in all three terrains. Notice also that the offices in the hills and tribal areas are generally smaller.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(bdo, aes(staff, office_exp)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE, formula = \"y ~ x\") +\n  facet_wrap(.~ terrain) +\n  labs(x = \"Staff in position\", y = \"Office expenses (₹ lakh)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Office expenses vs. staff, for each terrain](12-4Reg-multiple_files/figure-html/fig-ex4vis-1.png){#fig-ex4vis fig-align='center' width=672 height=35%}\n:::\n:::\n\n\n\n**Step 1.** Let us first use only the numeric variable `staff` to explain office expenses, and look at the coefficients. This is the same model as Example 1 of @sec-regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar_slop1 <- lm(office_exp ~ staff, data = bdo)\ncoef(par_slop1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)       staff \n 15.5084352   0.3477244 \n```\n\n\n:::\n:::\n\n\nWe got one intercept and one slope. We can see the line in @fig-parrslop (left).\n\n**Step 2.** Now let us explain office expenses by `terrain` only. *We also add `- 1` to the formula, which removes the common intercept and gives one intercept for each terrain.* This is the model `lm_fact0` of Example 3. If a variable is not yet a factor, like a year stored as a number, we can convert it inside the formula with `factor()`. Now see the coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar_slop2 <- lm(office_exp ~ factor(terrain) - 1, data = bdo)\ncoef(par_slop2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n factor(terrain)Plain  factor(terrain)Hilly factor(terrain)Tribal \n             27.30684              25.69265              25.81034 \n```\n\n\n:::\n:::\n\n\nWe got one intercept for each terrain. As @fig-parrslop (right) shows, these are nothing but the mean expenses for each terrain. The three means are close to each other.\n\n::: {#fig-parrslop}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-4Reg-multiple_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=47%}\n:::\n\n::: {.cell-output-display}\n![](12-4Reg-multiple_files/figure-html/unnamed-chunk-12-2.png){fig-align='center' width=47%}\n:::\n:::\n\n\nOffice expenses vs. staff (left) and terrain (right)\n:::\n\n**Step 3.** Now we build the complete model with both variables together, and look at the coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar_slop <- lm(office_exp ~ staff + terrain - 1, data = bdo)\ncoef(par_slop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        staff  terrainPlain  terrainHilly terrainTribal \n    0.4416366    11.1599895    15.3011985    12.0282383 \n```\n\n\n:::\n:::\n\n\nThere is one slope for the numeric variable and a separate intercept for each terrain. If we draw these, we get three *parallel* lines with the same slope. See @fig-parrslop2.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Parallel slopes](12-4Reg-multiple_files/figure-html/fig-parrslop2-1.png){#fig-parrslop2 fig-align='center' width=95% height=35%}\n:::\n:::\n\n\nThis is also clear from the equation, @eq-lr16.\n\n$$\n\\text{Office expenses} = 0.4416 \\cdot \\text{Staff} + 11.1600 \\cdot \\text{Plain} + 15.3012 \\cdot \\text{Hilly} + 12.0282 \\cdot \\text{Tribal}\n$$ {#eq-lr16}\n\nFor any office, one of the three dummy variables is 1 and the others are 0. The one with `1` acts as the intercept, but the slope stays the same. In other words, whatever the terrain, office expenses change with staff at the same rate.\n\nNotice something interesting. In Step 2, the three terrains had almost the same mean expenses. But now, for the *same* staff strength, an office in the hills spends about ₹4.1 lakh a year more than an office in the plains. An office in a tribal area spends about ₹0.9 lakh more. The difference was hidden because offices in the hills are smaller on average (23.5 staff against 36.6 in the plains). This is the power of multiple regression. It separates the effect of one variable from another. It also answers the surprise of Example 3. Terrain does matter, once we compare offices of the same size.\n\nBut is it right to force the same slope on all terrains? Perhaps each extra employee in the hills costs more, because each one travels more. How do we allow for that? The answer is `interaction`, discussed next.\n\n### Extending multiple linear regression by including `interactions`\n\nThe parallel slopes model forced a common slope on each category. That is not always the best option.\n\n**Example 4, continued.** In the same example, we can allow an `interaction` between the two predictors using the operator `:` in the formula.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_model <- lm(office_exp ~ staff + terrain + staff:terrain - 1, data = bdo)\ncoef(new_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              staff        terrainPlain        terrainHilly       terrainTribal \n         0.41006413         12.31432196         13.90042255         11.71979650 \n staff:terrainHilly staff:terrainTribal \n         0.09110541          0.04145620 \n```\n\n\n:::\n:::\n\n\nNotice the two extra coefficients. Each is the *change* in slope when we move from the baseline terrain, `Plain`, to `Hilly` or to `Tribal`. So the model now has a different slope for each terrain. See @fig-parrslop3.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Changing slopes with interaction](12-4Reg-multiple_files/figure-html/fig-parrslop3-1.png){#fig-parrslop3 fig-align='center' width=95% height=35%}\n:::\n:::\n\n\nLet us see the summary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(new_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = office_exp ~ staff + terrain + staff:terrain - 1, \n    data = bdo)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.1826 -1.5569  0.1208  1.5467  9.3339 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \nstaff                0.41006    0.03737  10.972  < 2e-16 ***\nterrainPlain        12.31432    1.40597   8.759 2.12e-14 ***\nterrainHilly        13.90042    1.37275  10.126  < 2e-16 ***\nterrainTribal       11.71980    1.78908   6.551 1.72e-09 ***\nstaff:terrainHilly   0.09111    0.06685   1.363    0.176    \nstaff:terrainTribal  0.04146    0.06680   0.621    0.536    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.499 on 114 degrees of freedom\nMultiple R-squared:  0.9918,\tAdjusted R-squared:  0.9914 \nF-statistic:  2294 on 6 and 114 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nWe may write the equation now (@eq-lr17).\n\n$$\n\\begin{aligned}\n\\text{Office expenses} = {} & 0.4101 \\cdot \\text{Staff} + 12.3143 \\cdot \\text{Plain} + 13.9004 \\cdot \\text{Hilly} + 11.7198 \\cdot \\text{Tribal} \\\\\n& + 0.0911 \\cdot \\text{Staff} \\cdot \\text{Hilly} + 0.0415 \\cdot \\text{Staff} \\cdot \\text{Tribal}\n\\end{aligned}\n$$ {#eq-lr17}\n\nSo for offices in the hills, the slope of `staff` is $0.4101 + 0.0911$, or 0.5012. But look at the p-values of the two interaction terms, 0.18 and 0.54. They are far above 0.05. So the data does not give us any real evidence that the slopes differ between the terrains. The three lines in @fig-parrslop3 are nearly parallel too. Here the simpler parallel slopes model is good enough. Always check whether an interaction is significant before reading meaning into it. We will see an interaction which *does* matter in @sec-reg-audit.\n\nWe can add as many interactions as we like using `:`. When there are many, we can use another shorthand, `*`. So `x*z` means `x + z + x:z`, and `x*z*w` means `x + z + w + x:z + x:w + z:w + x:z:w`. It does not change the model, but saves a lot of typing.\n\n## Multi-collinearity and the variance inflation factor (VIF)\n\nMulti-collinearity means that the predictor variables are strongly related to each other. This creates a problem. When two predictors move together, the model cannot tell which of them is really affecting $y$. The coefficient estimates become unstable. A small change in the data can change them a lot, sometimes even flip their sign. Their standard errors become large, so useful variables may look insignificant. We saw this with `area_sqm` in Example 2.\n\nNote that multi-collinearity does not spoil the *predictions* of the model much. It spoils our ability to *interpret* the individual coefficients. For an auditor, who usually wants to explain a finding, that matters.\n\nThere are many ways to detect multi-collinearity. One is to use correlation plots, as in @fig-ex2vis2. Another is the *Variance Inflation Factor* or VIF. To find the VIF of a predictor, we regress it on all the other predictors and note the $R^2$ of that regression. The VIF score thus tells us how well a predictor is explained by the other predictors.\n\n$$\n{VIF} = \\frac{1}{1-R^2}\n$$ {#eq-lr18}\n\nSo the closer this $R^2$ is to $1$, the higher the ${VIF}$.\n\n- $VIF$ starts at $1$ and has no upper limit.\n- ${VIF} = 1$ means the predictor is not related to the other predictors at all.\n- ${VIF}$ above $5$ is commonly taken to indicate a problem, and above $10$ a serious one.\n\nIn R, we do not have to calculate ${VIF}$ by hand. The function `vif()` from the package `car` does it. Let us first check our model of Example 2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::vif(lin_reg2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        staff      area_sqm beneficiaries \n     7.507741      7.599050      1.109000 \n```\n\n\n:::\n:::\n\n\nThe VIFs of `staff` and `area_sqm` are 7.5 and 7.6, both above 5. That confirms what we suspected. The VIF of `beneficiaries` is close to 1, so it brings its own information. Now let us try a model where office expenses are explained by all the numeric columns of our data. Sanctioned posts move with staff in position, and beneficiaries move with the population of the block. We again use the shorthand `.` for all other variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbdo_num <- bdo |>\n  select(office_exp, staff, sanctioned, area_sqm, population, beneficiaries)\nmod <- lm(office_exp ~ . , data = bdo_num)\ncar::vif(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        staff    sanctioned      area_sqm    population beneficiaries \n    46.598673     39.612223      7.630437     16.333157     16.109711 \n```\n\n\n:::\n:::\n\n\nFour predictors here have a VIF above 10. Such a model would be hard to interpret. In practice, we would keep only one predictor from each related pair, the one which makes more business sense. For office expenses, staff in position matters more than sanctioned posts, because vacant posts spend nothing.\n\n::: callout-tip\n## Audit tip\n\nMany indicators in government data come in related pairs. Sanctioned posts and staff in position, population and beneficiaries, budget and expenditure, length and cost of a road. Putting both members of a pair in one model rarely helps. Pick the one closer to the actual cause of the expenditure. @sec-pca shows another way, which combines related indicators into one.\n:::\n\n## Audit use case, block offices with inflated expenses {#sec-reg-bdoflags}\n\nLet us now return to the two block offices we planted. We have learnt a good deal about their data. Office expenses rise with staff and with beneficiaries. Offices in the hills and tribal areas spend more for the same size. Floor area, sanctioned posts and population add little once staff and beneficiaries are in the model. So the model which makes business sense uses staff, beneficiaries and terrain.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbdo_final <- lm(office_exp ~ staff + beneficiaries + terrain, data = bdo)\nsummary(bdo_final)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = office_exp ~ staff + beneficiaries + terrain, data = bdo)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.4439 -1.0171  0.0541  1.1266  9.4715 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    6.86558    1.04020   6.600 1.32e-09 ***\nstaff          0.42329    0.02250  18.812  < 2e-16 ***\nbeneficiaries  0.10770    0.01459   7.380 2.68e-11 ***\nterrainHilly   5.38553    0.56025   9.613  < 2e-16 ***\nterrainTribal  2.62761    0.54161   4.851 3.88e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.066 on 115 degrees of freedom\nMultiple R-squared:  0.8005,\tAdjusted R-squared:  0.7936 \nF-statistic: 115.4 on 4 and 115 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nAll the predictors are significant, and the model explains 80% of the variation in office expenses, against 60% with staff alone. The residual standard error has come down from ₹2.90 lakh to ₹2.07 lakh. Now let us find the offices which spend more than expected, with `augment()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naugment(bdo_final, data = bdo) |>\n  mutate(excess = office_exp - .fitted) |>\n  arrange(desc(.std.resid)) |>\n  select(office_id, district, staff, beneficiaries, office_exp, .fitted, excess, .std.resid) |>\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 8\n  office_id district   staff beneficiaries office_exp .fitted excess .std.resid\n  <chr>     <chr>      <dbl>         <dbl>      <dbl>   <dbl>  <dbl>      <dbl>\n1 BDO-088   Firozpur      27          46         32.7    23.2   9.47       4.65\n2 BDO-027   Sitapur       26          18.9       26.4    19.9   6.47       3.24\n3 BDO-074   Mayurbhanj    40          37.1       33.6    30.4   3.19       1.58\n4 BDO-115   Etawah        34          33         28.0    24.8   3.15       1.54\n5 BDO-010   Firozpur      46          37         33.4    30.3   3.06       1.51\n```\n\n\n:::\n:::\n\n\nTwo offices, BDO-088 and BDO-027, have standardised residuals above 3. They are exactly the two offices we planted. Together they spent about ₹15.9 lakh more than expected. No other office comes close.\n\nWhy did `BDO-027` hide in the model of staff alone, in @sec-regression? Let us compare it under both models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  augment(lin_reg1, data = bdo) |> mutate(model = \"Staff only\"),\n  augment(bdo_final, data = bdo) |> mutate(model = \"Staff, beneficiaries, terrain\")\n) |>\n  filter(office_id == \"BDO-027\") |>\n  select(model, staff, beneficiaries, office_exp, .fitted, .std.resid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  model                        staff beneficiaries office_exp .fitted .std.resid\n  <chr>                        <dbl>         <dbl>      <dbl>   <dbl>      <dbl>\n1 Staff only                      26          18.9       26.4    24.5      0.635\n2 Staff, beneficiaries, terra…    26          18.9       26.4    19.9      3.24 \n```\n\n\n:::\n:::\n\n\n\n\n`BDO-027` serves only 18.9 thousand beneficiaries, against an average of 38.0 thousand. An office of its size with so few beneficiaries should spend *less* than the average. The model with staff alone did not know this. It expected the expenses of an average office of that size, and the inflated bill looked normal against it. Once beneficiaries are in the model, the expected expenses fall, and the inflation stands out.\n\n::: callout-warning\n## Caution\n\nA model that leaves out an important driver does more than fit badly. It can *hide* an irregularity, as it hid `BDO-027`, or point to innocent offices, as it pointed to the offices in the hills. Before trusting the residuals, make sure the model includes every driver which the business suggests.\n:::\n\nWhat would the auditor do next? For each of the two offices, we would call for the vehicle hire bills, the log books of the vehicles and the sanction for hiring them. Bills without matching log book entries, or log books written up in one hand at the end of the year, are common signs of payments for vehicles never used. We would ask the office to explain the excess in writing, and record the model, the flagged offices and the replies in the working papers.\n\n## A complete example, cost of rural road works {#sec-reg-roads}\n\n**Example 5.** Let us now go through the whole process on a different audit dataset. A state builds rural roads under a scheme. We have 90 road works completed in five financial years, 2019-20 to 2023-24. For each work we know\n\n- `cost_lakh`, the cost per kilometre, in ₹ lakh,\n- `width_m`, the width of the carriageway in metres,\n- `hilly_pct`, the percentage of the road length in hilly terrain,\n- `lead_km`, the distance from the quarry, from which stone is carried,\n- `rain_cm`, the average annual rainfall of the area, in centimetres,\n- `bitumen_k`, the rate of bitumen in the year of the work, in ₹ thousand per tonne, and\n- `year_no`, the year of the work, from 1 for 2019-20 to 5 for 2023-24.\n\nThe cost of a road should depend on its width, the terrain, the lead and the price of bitumen. The auditor would like a model of the *expected* cost per kilometre. Works which cost far more than expected can then be picked for detailed examination of their estimates and measurement books.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the road works data\"}\nset.seed(2411)\nn <- 90\nroads <- tibble(\n  work_id   = sprintf(\"RW-%03d\", 1:n),\n  fin_year  = sample(2019:2023, n, replace = TRUE),\n  width_m   = sample(c(3, 3.75, 5.5), n, replace = TRUE, prob = c(0.4, 0.4, 0.2)),\n  hilly_pct = round(100 * rbeta(n, 0.7, 1.8)),\n  lead_km   = round(runif(n, 5, 60)),\n  rain_cm   = round(runif(n, 60, 250))\n) |>\n  mutate(\n    # bitumen rate rises every year\n    bitumen_k = round(38 + 3.5 * (fin_year - 2019) + rnorm(n, 0, 1.5), 1),\n    year_no   = fin_year - 2018,\n    # rainfall has no effect on cost in this data\n    cost_lakh = round(20 + 9 * width_m + 0.22 * hilly_pct + 0.12 * lead_km +\n                      0.8 * bitumen_k + rnorm(n, 0, 8), 1)\n  )\n# Keep only the response and the predictors, for the model\nroad_vars <- roads |>\n  select(cost_lakh, width_m, hilly_pct, lead_km, rain_cm, bitumen_k, year_no)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# See the first 6 rows\nhead(road_vars)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  cost_lakh width_m hilly_pct lead_km rain_cm bitumen_k year_no\n      <dbl>   <dbl>     <dbl>   <dbl>   <dbl>     <dbl>   <dbl>\n1     104.     3.75        35      24      91      47         4\n2      95.4    3           15      13     102      42.3       3\n3     132.     5.5         72      35     240      50.1       4\n4     100.     3.75        59      21     164      37.7       1\n5     102.     5.5          2      24     200      49.6       4\n6      72.2    3            7      23     196      38         1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Build a model\nex1 <- lm(cost_lakh ~ . , data = road_vars)\n```\n:::\n\n\nIn the formula, `.` again means all variables other than `cost_lakh`. Let us see the output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ex1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = cost_lakh ~ ., data = road_vars)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-21.4089  -5.5939  -0.0582   4.6437  22.5095 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 48.72657   20.56891   2.369  0.02016 *  \nwidth_m      8.52106    0.98704   8.633 3.54e-13 ***\nhilly_pct    0.24558    0.03210   7.650 3.22e-11 ***\nlead_km      0.16274    0.05706   2.852  0.00548 ** \nrain_cm      0.01773    0.01629   1.088  0.27955    \nbitumen_k   -0.08728    0.59762  -0.146  0.88424    \nyear_no      2.88528    2.22617   1.296  0.19854    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.663 on 83 degrees of freedom\nMultiple R-squared:  0.6795,\tAdjusted R-squared:  0.6563 \nF-statistic: 29.33 on 6 and 83 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nMultiple R-squared is about 68%. But look at `bitumen_k`. Its slope is -0.087, which would mean that roads get *cheaper* as bitumen gets costlier. Its p-value is 0.88. Something is not right. Let us see some diagnostic plots (@fig-perf2).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_model(ex1)\n```\n\n::: {.cell-output-display}\n![Diagnostic plots](12-4Reg-multiple_files/figure-html/fig-perf2-1.png){#fig-perf2 fig-align='center' width=960}\n:::\n:::\n\n\nWe can notice high collinearity between `bitumen_k` and `year_no` in @fig-perf2. It is clearly visible in @fig-multi2. The rate of bitumen rose every year, so the two move together.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nroad_vars %>%\n  ggplot(aes(year_no, bitumen_k)) +\n  geom_point()+\n  geom_smooth(method = 'lm', formula = 'y~x') +\n  labs(x = \"Year of work (1 is 2019-20)\", y = \"Bitumen rate (₹ thousand per tonne)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Are the year and the bitumen rate correlated?](12-4Reg-multiple_files/figure-html/fig-multi2-1.png){#fig-multi2 fig-align='center' width=672 height=30%}\n:::\n:::\n\n\nThis can also be seen in the correlation plots in @fig-corrp.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Correlation plots](12-4Reg-multiple_files/figure-html/fig-corrp-1.png){#fig-corrp fig-align='center' width=672 height=45%}\n:::\n:::\n\n\nLet us see the VIF of the predictors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::vif(ex1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  width_m hilly_pct   lead_km   rain_cm bitumen_k   year_no \n 1.071049  1.089254  1.146704  1.192879 14.623986 14.823085 \n```\n\n\n:::\n:::\n\n\nBoth `bitumen_k` and `year_no` have a VIF above 5. The other predictors have a VIF close to 1. So let us remove one of the pair. The bitumen rate is the actual cause of the change in cost, while the year only stands in for it. So we remove `year_no` and re-run the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nex2 <- lm(cost_lakh ~ width_m + hilly_pct + lead_km + rain_cm + bitumen_k, data = road_vars)\nsummary(ex2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = cost_lakh ~ width_m + hilly_pct + lead_km + rain_cm + \n    bitumen_k, data = road_vars)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-21.3905  -5.8660  -0.4977   4.5828  21.3593 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 24.84885    9.18404   2.706 0.008254 ** \nwidth_m      8.56951    0.99032   8.653 2.96e-13 ***\nhilly_pct    0.24861    0.03214   7.734 2.06e-11 ***\nlead_km      0.14456    0.05554   2.603 0.010924 *  \nrain_cm      0.01177    0.01569   0.750 0.455057    \nbitumen_k    0.65861    0.16176   4.072 0.000105 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.694 on 84 degrees of freedom\nMultiple R-squared:  0.673,\tAdjusted R-squared:  0.6535 \nF-statistic: 34.57 on 5 and 84 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nMultiple R-squared has dropped a little, to 67.3%. That is expected, since R-squared never rises when we remove a variable. But look at what we gained. The slope of `bitumen_k` is now 0.659, positive as it should be. Its standard error has fallen from 0.598 to 0.162. Its estimate is now much more precise. Let us also remove `rain_cm`, whose coefficient is not significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nex3 <- lm(cost_lakh ~ width_m + hilly_pct + lead_km + bitumen_k, data = road_vars)\nsummary(ex3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = cost_lakh ~ width_m + hilly_pct + lead_km + bitumen_k, \n    data = road_vars)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-21.8051  -5.5384  -0.2481   4.1768  20.7802 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 28.22990    7.98257   3.536 0.000660 ***\nwidth_m      8.49810    0.98320   8.643 2.85e-13 ***\nhilly_pct    0.24337    0.03129   7.777 1.59e-11 ***\nlead_km      0.14085    0.05517   2.553 0.012471 *  \nbitumen_k    0.63868    0.15915   4.013 0.000129 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.675 on 85 degrees of freedom\nMultiple R-squared:  0.6708,\tAdjusted R-squared:  0.6553 \nF-statistic:  43.3 on 4 and 85 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nMultiple R-squared falls slightly again, to 67.1%. But adjusted R-squared stays almost the same (0.6535 before, 0.6553 now). So `rain_cm` was adding nothing useful, and the simpler model with four predictors does as well as the one with five. All of its coefficients are significant. When two models explain the data about equally well, we prefer the simpler one.\n\nNow the model reads sensibly. A road 1 metre wider costs about ₹8.5 lakh more per kilometre. Each 10 percentage points of hilly length add about ₹2.4 lakh per kilometre. A rise of ₹1,000 per tonne in the bitumen rate adds about ₹0.64 lakh per kilometre. The auditor can compare these with the schedule of rates. If the model says that terrain or lead adds much more than the rates allow, the estimates deserve a look.\n\nLet us visualise one of the main relationships through a scatter plot.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nroad_vars %>%\n  ggplot(aes(hilly_pct, cost_lakh)) +\n  geom_point() +\n  geom_smooth(method = 'lm', formula = 'y ~ x', se = FALSE) +\n  labs(x = \"Hilly length (%)\", y = \"Cost per km (₹ lakh)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Ascertaining linear relationship](12-4Reg-multiple_files/figure-html/fig-ex5scatter-1.png){#fig-ex5scatter fig-align='center' width=672 height=30%}\n:::\n:::\n\n\nThe relationship between hilly length and cost is real, but the points are widely scattered around the line. That is because width, lead and the bitumen rate also vary from work to work. Only the model with all of them together explains about two thirds of the variation. The rest is due to things this data does not have, like soil, culverts and the quality of the contractor's work.\n\n## Simpson's paradox\n\nEdward Hugh Simpson, a statistician and former cryptanalyst at Bletchley Park, described this phenomenon in a paper in 1951. It is a classic example of how a regression that leaves out an important variable can mislead. The paradox arises when a trend seen in each subgroup of the data *reverses* or *disappears* when the subgroups are combined. We saw a mild form of it in Example 4, where terrain seemed not to matter until we compared offices of the same size.\n\n**Example 6.** A health department runs 60 hospitals of three types. There are primary health centres (PHCs), community health centres (CHCs) and district hospitals. For each we know the number of patients treated in the year (`patients`, in thousand) and the cost per patient (`cost_pp`, in ₹). Does a hospital that treats more patients spend less per patient? Let us try to establish a relationship between the two. See the plots in @fig-ex3.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the hospital data\"}\nset.seed(77)\nhosp_types <- c(\"PHC\", \"CHC\", \"District hospital\")\nhosp <- tibble(type = factor(rep(hosp_types, each = 20), levels = hosp_types)) |>\n  mutate(\n    patients = round(case_when(type == \"PHC\" ~ runif(n(), 5, 15),\n                               type == \"CHC\" ~ runif(n(), 18, 35),\n                               TRUE          ~ runif(n(), 40, 80)), 1),\n    # within each type, cost per patient falls as the number of patients grows\n    base    = c(PHC = 950, CHC = 1700, \"District hospital\" = 3300)[as.character(type)],\n    centre  = c(PHC = 10, CHC = 26, \"District hospital\" = 60)[as.character(type)],\n    cost_pp = round(base - 18 * (patients - centre) + rnorm(n(), 0, 80))\n  ) |>\n  select(type, patients, cost_pp)\n```\n:::\n\n\n::: {#fig-ex3}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-4Reg-multiple_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=47%}\n:::\n\n::: {.cell-output-display}\n![](12-4Reg-multiple_files/figure-html/unnamed-chunk-25-2.png){fig-align='center' width=47%}\n:::\n:::\n\n\nRegression having variable hidden (left) and exposed (right)\n:::\n\nIn the left plot, the relationship is positive. Hospitals treating more patients seem to spend *more* per patient. But when the hidden variable `type` is exposed (right), we see a *negative* relationship within each type. A busier PHC costs less per patient than a quieter PHC, and the same holds for CHCs and district hospitals. Let us confirm this with two models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(lm(cost_pp ~ patients, data = hosp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)    patients \n  638.36759    41.53393 \n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(lm(cost_pp ~ patients + type, data = hosp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          (Intercept)              patients               typeCHC \n           1126.86491             -19.10646            1086.58582 \ntypeDistrict hospital \n           3296.68779 \n```\n\n\n:::\n:::\n\n\nWithout type, the slope of patients is 41.53. Once type is in the model, it becomes -19.11. The sign has flipped. Type of hospital is a *confounding* variable here. District hospitals treat more patients *and* treat costlier cases. An auditor who compared all hospitals together might wrongly conclude that busy hospitals are wasteful. So before finalising a model, we must make sure that we are not missing an important variable. To avoid being misled by Simpson's paradox, we should\n\n- **Identify confounding variables.** Think about what else could affect both variables under study.\n- **Consider all levels.** Analyse the data at the subgroup level and at the combined level, and compare.\n- **Use statistical techniques** such as multiple regression, as we just did, to control for confounding variables.\n- **Report transparently.** Clearly state the method, assumptions and limitations of the analysis so that others can evaluate the findings.\n\n::: callout-tip\n## Audit tip\n\nSimpson's paradox is common in audit data. A scheme may show a falling rejection rate in every district, yet a rising rate for the state as a whole, because the mix of districts has changed. Before reporting a trend on combined data, always check it within the main subgroups, like districts, years, or types of contract.\n:::\n\n## Audit use case, offices that spend more than expected {#sec-reg-audit}\n\nWe have used regression on audit data throughout this chapter. Let us now put it all together on the question with which we started. Salary expenditure of an office should depend mainly on its staff strength. If an office spends far more than its staff strength explains, it may have *ghost employees* on its pay roll, or other irregular payments. Regression gives us an *expected* expenditure for every office. The residual is then the *unexplained* part. Large positive residuals are our leads.\n\n### Our sample data\n\nWe create the data of 90 sub-divisional offices (SDOs) of an imaginary department. For each office we have its staff strength, the class of the city where it is located, and its monthly salary expenditure in ₹ lakh. House rent allowance (HRA) is 30%, 20% and 10% of pay in X, Y and Z class cities respectively. So, for the same staff, an office in an X class city spends more.\n\nWe have planted a few cases.\n\n- Three offices have salary expenditure inflated by 16%, as if ghost employees were added.\n- In one office, the staff strength was keyed in with an extra zero.\n\nAs before, new readers may skip the code which creates the data.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the sample office data\"}\nset.seed(2026)\nn <- 90\noffices <- tibble(\n  office_id  = sprintf(\"SDO-%02d\", 1:n),\n  city_class = factor(sample(c(\"X\", \"Y\", \"Z\"), n, replace = TRUE,\n                             prob = c(0.2, 0.4, 0.4)),\n                      levels = c(\"Z\", \"Y\", \"X\")),\n  staff      = sample(8:60, n, replace = TRUE)\n) |>\n  mutate(hra    = c(Z = 0.10, Y = 0.20, X = 0.30)[as.character(city_class)],\n         # about ₹0.85 lakh basic cost per employee, plus HRA, plus noise\n         salary = round(staff * 0.85 * (1 + hra) + rnorm(n, 0, 1.2), 2)) |>\n  select(-hra)\n\n# Planted case 1. Ghost employees, salary inflated by 16%\nghost <- c(\"SDO-17\", \"SDO-44\", \"SDO-63\")\noffices <- offices |>\n  mutate(salary = if_else(office_id %in% ghost, round(salary * 1.16, 2), salary))\n\n# Planted case 2. Staff strength keyed in with an extra zero\noffices <- offices |>\n  mutate(staff = if_else(office_id == \"SDO-81\", staff * 10L, staff))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(offices)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  office_id city_class staff salary\n  <chr>     <fct>      <int>  <dbl>\n1 SDO-01    Z             11   9.67\n2 SDO-02    Z             36  33.8 \n3 SDO-03    Y             15  14.3 \n4 SDO-04    Y             45  46.3 \n5 SDO-05    Z             23  23.6 \n6 SDO-06    Y             13  14.1 \n```\n\n\n:::\n:::\n\n\n### First model, and a surprise\n\nLet us fit a model of salary on staff strength and city class.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noff_m1 <- lm(salary ~ staff + city_class, data = offices)\nsummary(off_m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = salary ~ staff + city_class, data = offices)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-28.4279  -9.3392  -0.3861  10.1467  25.8925 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 32.16193    2.45813  13.084  < 2e-16 ***\nstaff        0.09919    0.02362   4.199 6.51e-05 ***\ncity_classY -0.52788    3.18400  -0.166    0.869    \ncity_classX  1.53420    4.00355   0.383    0.703    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 13.54 on 86 degrees of freedom\nMultiple R-squared:  0.1708,\tAdjusted R-squared:  0.1419 \nF-statistic: 5.906 on 3 and 86 DF,  p-value: 0.001031\n```\n\n\n:::\n:::\n\n\nSomething is wrong. Salary expenditure must surely rise steeply with staff strength. Yet the slope of `staff` is only 0.099 lakh per employee, and R-squared is only 17%. Let us look at the influence of each office, using `augment()` and Cook's distance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naugment(off_m1, data = offices) |>\n  arrange(desc(.cooksd)) |>\n  select(office_id, staff, salary, .fitted, .hat, .cooksd) |>\n  head(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  office_id staff salary .fitted   .hat  .cooksd\n  <chr>     <int>  <dbl>   <dbl>  <dbl>    <dbl>\n1 SDO-81      600  62.7     91.1 0.948  384.    \n2 SDO-80        9   7.93    34.6 0.0607   0.0667\n3 SDO-84       60  65.5     39.6 0.0609   0.0632\n4 SDO-08       58  64.3     39.4 0.0606   0.0580\n```\n\n\n:::\n:::\n\n\nOne office, `SDO-81`, has a Cook's distance of 384, where the rest are below 0.1. Its staff strength is shown as 600, while no other office has more than 60. Its leverage (`.hat`) is close to 1, the maximum possible. This single wrong entry has pulled the whole line towards itself. @fig-reg-lever shows this.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(offices, aes(staff, salary)) +\n  geom_point(aes(color = office_id == \"SDO-81\"), show.legend = FALSE) +\n  geom_smooth(method = \"lm\", formula = \"y ~ x\", se = FALSE) +\n  scale_color_manual(values = c(\"grey40\", \"red\")) +\n  labs(x = \"Staff strength (as recorded)\", y = \"Monthly salary (₹ lakh)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![One wrong entry (red) pulls the whole line](12-4Reg-multiple_files/figure-html/fig-reg-lever-1.png){#fig-reg-lever fig-align='center' width=672 height=35%}\n:::\n:::\n\n\n::: callout-tip\n## Audit tip\n\nAlways check Cook's distance and leverage *before* reading the residuals. A single data entry error with an extreme value can spoil the whole model. It then makes genuine outliers look normal, and normal offices look odd. Such an entry is itself an audit finding about the quality of the data.\n:::\n\nOn checking the records, suppose we find that the office actually has 60 staff. We should correct the entry. Here we simply keep it aside and re-fit.\n\n### A better model\n\nHRA is a *percentage* of pay. So each extra employee in an X class city costs more than an extra employee in a Z class city. In other words, the slope of `staff` should be different for each city class. This is exactly what an interaction does. Let us fit both the parallel slopes model and the interaction model on the clean data, and compare them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- offices |> filter(office_id != \"SDO-81\")\n\noff_m2 <- lm(salary ~ staff + city_class, data = clean)\noff_m3 <- lm(salary ~ staff * city_class, data = clean)\nsummary(off_m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = salary ~ staff * city_class, data = clean)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.6904 -1.0081 -0.0339  0.6564  6.1181 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        0.32799    0.70731   0.464  0.64406    \nstaff              0.93692    0.01751  53.514  < 2e-16 ***\ncity_classY        0.17978    0.96590   0.186  0.85280    \ncity_classX       -1.18493    1.06279  -1.115  0.26810    \nstaff:city_classY  0.07495    0.02482   3.019  0.00337 ** \nstaff:city_classX  0.18740    0.02749   6.816 1.39e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.42 on 83 degrees of freedom\nMultiple R-squared:  0.9909,\tAdjusted R-squared:  0.9903 \nF-statistic:  1798 on 5 and 83 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nBoth interaction terms are significant. For every extra employee, the expected salary goes up by 0.94 lakh in a Z class city, and by 1.12 lakh in an X class city. R-squared is now 99.1%.\n\nTo check formally whether the interaction model is better, we can compare the two models with `anova()`. It tests whether the extra terms reduce the residuals by more than chance would.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(off_m2, off_m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: salary ~ staff + city_class\nModel 2: salary ~ staff * city_class\n  Res.Df    RSS Df Sum of Sq     F    Pr(>F)    \n1     85 261.20                                 \n2     83 167.46  2    93.736 23.23 9.733e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe p-value is very small, so the interaction model is clearly better. Its residual standard error is 1.42 lakh, against 1.75 lakh for the parallel slopes model. The more accurate our expected values are, the easier it is to spot offices which do not fit.\n\n### Finding the offices\n\nNow let us look at the residuals. Raw residuals are in lakh. To judge how unusual each one is, we use the *standardised* residual (`.std.resid`). It is the residual divided by its standard error, so it is on a common scale. Under our assumptions, values beyond 3 are very rare, about 3 in 1,000. Let us also calculate the excess expenditure in rupees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflagged <- augment(off_m3, data = clean) |>\n  mutate(excess = salary - .fitted) |>\n  arrange(desc(.std.resid)) |>\n  select(office_id, staff, city_class, salary, .fitted, excess, .std.resid)\n\nhead(flagged, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 7\n  office_id staff city_class salary .fitted excess .std.resid\n  <chr>     <int> <fct>       <dbl>   <dbl>  <dbl>      <dbl>\n1 SDO-63       41 Z            44.9    38.7   6.12       4.37\n2 SDO-44       28 Z            31.4    26.6   4.79       3.45\n3 SDO-79       28 Y            31.3    28.8   2.42       1.73\n4 SDO-17       27 Z            27.7    25.6   2.10       1.51\n5 SDO-88       30 X            34.8    32.9   1.89       1.37\n```\n\n\n:::\n:::\n\n\n\n\nTwo offices, SDO-63 and SDO-44, have standardised residuals above 3. Together they spend about ₹10.9 lakh a month, or about ₹1.3 crore a year, more than expected. Both are planted ghost employee cases. They are clearly our first leads.\n\nThe third planted office, `SDO-17`, has a standardised residual of only 1.51. Its excess of ₹2.1 lakh is within the normal variation between offices. Regression cannot separate it from genuine offices. Let us see all of this in @fig-reg-flags.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naugment(off_m3, data = clean) |>\n  ggplot(aes(.fitted, .std.resid)) +\n  geom_hline(yintercept = c(-3, 3), linetype = 2, color = \"red\") +\n  geom_hline(yintercept = 0, color = \"grey50\") +\n  geom_point(aes(color = office_id %in% ghost)) +\n  geom_text(data = \\(d) filter(d, abs(.std.resid) > 3 | office_id %in% ghost),\n            aes(label = office_id), vjust = -0.8, size = 3) +\n  scale_color_manual(values = c(\"grey40\", \"red\"),\n                     labels = c(\"Other offices\", \"Planted cases\")) +\n  labs(x = \"Expected salary (₹ lakh)\", y = \"Standardised residual\", color = NULL) +\n  theme_bw() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Standardised residuals of offices. Offices beyond 3 are leads.](12-4Reg-multiple_files/figure-html/fig-reg-flags-1.png){#fig-reg-flags fig-align='center' width=672}\n:::\n:::\n\n\n::: callout-warning\n## Caution\n\nRegression finds only those deviations which are large compared to the normal variation between offices. A small office with a few ghost employees, like `SDO-17`, can hide in that variation. So a clean result from regression does not prove that there is no fraud. For individual offices, it must be followed by other tests, like matching the pay roll with the attendance and bank account data (see @sec-dup).\n:::\n\n::: callout-note\n## What about large negative residuals?\n\nOffices which spend much *less* than expected may also deserve a look. The reason may be vacant posts, salary not paid on time, or expenditure booked under the wrong head. Here no office has a standardised residual below -3.\n:::\n\n### What the auditor does next\n\nThe model has given us 2 leads and one data quality finding. None of them is yet an audit finding. For each lead, we would\n\n- obtain the pay roll of the office for a few months, and count the employees actually paid against the staff strength reported,\n- match the employees paid with the attendance register, the service books and the bank accounts into which pay was credited, looking for the same account shared by two employees, or employees who never mark attendance,\n- ask the office to explain the excess of about ₹10.9 lakh a month, in writing, and\n- record the model, the residuals and the replies in the working papers, so that the selection of these offices can be justified later.\n\nThe keying error in the staff strength of `SDO-81` should be reported as a weakness in the data, because the same figure may be used elsewhere, for example to sanction posts or to allot funds.\n\n## Uses of regression in audit\n\nWe have seen that regression analysis is a powerful tool for an auditor. It may be used, among other things, for the following.\n\n- **Detection of anomalies and outliers.** As in our office examples, regression gives the *expected* value of an amount based on its drivers. Large residuals point to transactions or units which do not fit, and these may be errors, irregularities or fraud.\n- **Analytical procedures.** The auditor can estimate what an expenditure *should* be, say fuel cost from vehicle kilometres, or electricity charges from the connected load, and compare it with what was booked.\n- **Risk assessment.** Units with large unexplained deviations can be ranked and taken up first in the audit plan. This helps the auditor use limited time and staff well.\n- **Benchmarking.** Regression can compare the performance of an organisation with similar ones, after adjusting for size and other factors. Deviations from the expected relationship highlight areas that deserve a closer look. The cost of road works per kilometre, adjusted for width, terrain and lead, is one example.\n\n## A suggested workflow\n\nFor any regression analysis in audit, we may follow these steps.\n\n1. **Understand the drivers.** Decide, from knowledge of the business, which variables should explain the amount under audit. Regression only confirms or rejects relationships which make sense.\n2. **Visualise first.** Draw scatter plots and box plots to see whether the relationships look linear, and to spot obvious errors.\n3. **Fit a simple model** with `lm()`, and read its `summary()`.\n4. **Check influence.** Look at Cook's distance and leverage. Investigate and correct data entry errors before going further.\n5. **Check the assumptions** with `plot()` or `check_model()`. Check multi-collinearity with `vif()` when there are several predictors, and keep only one predictor from each related pair.\n6. **Improve the model.** Add factors and interactions that make business sense. Watch for hidden variables which can reverse a trend. Compare models with adjusted R-squared or `anova()`.\n7. **Flag the residuals.** Use `augment()` and pick the units with large standardised residuals. Quantify the excess in rupees.\n8. **Verify with records.** Examine the documents of the flagged units before drawing any conclusion.\n\n::: callout-important\n## Remember\n\nA regression model shows association, not cause. A large residual means only that a unit does not fit the pattern of the others. It is a *lead*, not a *finding*. There may be a genuine reason which the model does not know about. Always examine the records before reporting.\n:::\n\n## Where next\n\nLinear regression predicts a number. When the audit question has a yes or no answer, like whether a claim is irregular, we use logistic regression, in @sec-logistic. When many indicators are related to each other, @sec-pca shows how to combine them before modelling.\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `lm()` | base R (stats) | Fits a linear regression model |\n| `summary()` | base R | Shows coefficients, p-values, R-squared and F-test of a model |\n| `coef()` | base R (stats) | Gives the coefficients of a model |\n| `sigma()`, `cooks.distance()` | base R (stats) | Gives the residual standard error and Cook's distance |\n| `contrasts()`, `model.matrix()` | base R (stats) | Shows how factors are converted to dummy variables |\n| `factor()` | base R | Converts a variable to a factor, also inside a formula |\n| `anova()` | base R (stats) | Compares two nested models |\n| `augment()` | broom | Gives fitted values, residuals, leverage and Cook's distance as a data frame |\n| `check_model()` | performance | Draws all diagnostic plots together, with guidance |\n| `vif()` | car | Calculates the variance inflation factor of each predictor |\n| `ggpairs()` | GGally | Draws a matrix of scatter plots and correlations |\n| `geom_parallel_slopes()` | moderndive | Draws a parallel slopes model in ggplot2 |\n\n: Functions used in this chapter {#tbl-mregfunctions}\n",
    "supporting": [
      "12-4Reg-multiple_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}