{
  "hash": "5bd2e1c233be242714b9fedcb4440714",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Random Forests {#sec-forest}\n\nA single decision tree (@sec-trees) is easy to read, but it has a weakness we noted there. It is *unstable*. Grow it on a slightly different sample, and the questions, the thresholds and the predictions can all change. A **random forest** turns this weakness into a strength. It grows hundreds of trees, each on a slightly different sample of the data, and lets them *vote*. Individual trees make different mistakes, and in the average, many of the mistakes cancel out.\n\nIt is the same reason why an audit committee is wiser than any one of its members, or why the average of many independent estimates is usually closer to the truth than most of the estimates themselves. Random forests are among the most reliable methods for scoring risk, and they need very little tuning. The price is that a forest of 500 trees cannot be read like a single tree. We will see how to look inside it all the same.\n\n**Prerequisites**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(rpart)    # single trees, for comparison\nlibrary(ranger)   # fast random forests\n```\n:::\n\n\n`ranger` is installed from CRAN with `install.packages(\"ranger\")`. We also need the AUC function of @sec-logistic-evaluate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nauc <- function(score, actual) {\n  r  <- rank(score)\n  n1 <- sum(actual)\n  n0 <- sum(!actual)\n  (sum(r[actual]) - n1 * (n1 + 1) / 2) / (n1 * n0)\n}\n```\n:::\n\n\n## Our data, refund claims with many red flags {#sec-forest-data}\n\nWe return to GST refund claims, as in @sec-logistic, but this time the audit party recorded many more features for each of the 5,000 claims examined last year.\n\n| Feature | Meaning |\n|----------------|--------------------------------------------|\n| `exporter_type` | Manufacturer or merchant exporter |\n| `sector` | Sector of the exporter |\n| `reg_months` | Months since GST registration |\n| `amount_lakh` | Refund claimed, ₹ lakh |\n| `nonfiler_pct` | Percentage of input credit from suppliers who did not file returns |\n| `refund_ratio` | Refund claimed as a share of the year's turnover |\n| `n_suppliers` | Number of suppliers |\n| `top_supplier_pct` | Share of purchases from the largest supplier |\n| `shared_address` | Whether the address is shared with another claimant |\n| `quarter_end` | Whether the claim was filed in the last week of a quarter |\n| `prior_claims` | Number of earlier refund claims |\n\n: Features of each refund claim {#tbl-forest-features}\n\nSome of these matter and some do not, and the ones that matter do so in different ways: some gradually, some beyond a threshold, some only in combination with another feature. This is the kind of data where forests do well. The code is folded, and its comments say what was planted.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the refund claims\"}\nset.seed(46)\nn <- 5000\nclaims <- tibble(\n  exporter_type    = sample(c(\"Manufacturer\", \"Merchant\"), n, TRUE, prob = c(0.65, 0.35)),\n  sector           = sample(c(\"Textiles\", \"Engineering\", \"Chemicals\", \"Agro\",\n                              \"Electronics\", \"Gems\"), n, TRUE),\n  reg_months       = pmax(1, round(rexp(n, 1 / 40))),\n  amount_lakh      = round(rlnorm(n, log(8), 1), 2),\n  nonfiler_pct     = round(100 * rbeta(n, 0.6, 6), 1),\n  refund_ratio     = round(rbeta(n, 2, 5), 3),\n  n_suppliers      = rpois(n, 8) + 1,\n  top_supplier_pct = round(100 * rbeta(n, 2, 2.5), 1),\n  shared_address   = runif(n) < 0.06,\n  quarter_end      = runif(n) < 0.3,\n  prior_claims     = rpois(n, 3)\n) |>\n  mutate(\n    # The true risk, unknown to the auditor:\n    true_logodds = -3.2 +\n      0.03 * nonfiler_pct +                                   # gradual effect\n      0.07 * nonfiler_pct * (exporter_type == \"Merchant\") +   # stronger for merchants\n      2.2 * (refund_ratio > 0.45) +                           # a threshold\n      1.8 * (n_suppliers <= 5 & top_supplier_pct > 60) +      # a combination\n      1.6 * shared_address +\n      1.2 * (reg_months < 12) +\n      0.6 * sin(amount_lakh / 6),                             # a weak, wavy effect\n    # sector, quarter_end and prior_claims have no effect at all\n    irregular = runif(n) < plogis(true_logodds)) |>\n  select(-true_logodds)\n\nset.seed(1)\ntrain_rows <- sample(nrow(claims), size = 0.7 * nrow(claims))\ntrain <- claims[train_rows, ]\ntest  <- claims[-train_rows, ]\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclaims\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 12\n   exporter_type sector      reg_months amount_lakh nonfiler_pct refund_ratio\n   <chr>         <chr>            <dbl>       <dbl>        <dbl>        <dbl>\n 1 Manufacturer  Electronics         55        7.36          1.4        0.404\n 2 Manufacturer  Textiles            10       11.2           1.8        0.175\n 3 Manufacturer  Agro               103        1.15          2.5        0.207\n 4 Manufacturer  Gems                 5        5.11         16.4        0.294\n 5 Manufacturer  Chemicals           28        4.33          2.6        0.152\n 6 Merchant      Chemicals           16        4.08          2.7        0.454\n 7 Merchant      Chemicals           58        5.66          1.3        0.265\n 8 Manufacturer  Electronics          5        5.39          4.5        0.287\n 9 Merchant      Gems                34        6.75          2.1        0.385\n10 Merchant      Gems                 1        3.66         10.1        0.592\n# ℹ 4,990 more rows\n# ℹ 6 more variables: n_suppliers <dbl>, top_supplier_pct <dbl>,\n#   shared_address <lgl>, quarter_end <lgl>, prior_claims <int>,\n#   irregular <lgl>\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(claims$irregular)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2226\n```\n\n\n:::\n:::\n\n\nAbout 22% of the claims were irregular. As before, the model learns from 70% of the claims and is judged on the other 30%.\n\n## From one tree to many {#sec-forest-bagging}\n\nBefore using a ready-made forest, let us build a small one by hand, to see why it works. First, a single tree, judged on the test set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\none_tree <- rpart(irregular ~ ., data = train, method = \"anova\")\nauc(predict(one_tree, test), test$irregular)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7450786\n```\n\n\n:::\n:::\n\n\nNow we grow 50 trees, each on a *bootstrap sample* of the training data: a sample of the same size, drawn *with replacement*, so that some claims appear twice and others not at all. Each tree sees a slightly different picture of the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2)\nmany_trees <- map(1:50, \\(i) {\n  boot <- train[sample(nrow(train), replace = TRUE), ]\n  rpart(irregular ~ ., data = boot, method = \"anova\")\n})\n\n# each tree's own AUC on the test set\ntree_aucs <- map_dbl(many_trees, \\(t) auc(predict(t, test), test$irregular))\nsummary(tree_aucs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.7148  0.7423  0.7497  0.7485  0.7618  0.7748 \n```\n\n\n:::\n\n```{.r .cell-code}\n# the AUC of their average prediction\navg_score <- map(many_trees, \\(t) predict(t, test)) |> reduce(`+`) / 50\nauc(avg_score, test$irregular)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7838601\n```\n\n\n:::\n:::\n\n\n\n\nThe 50 trees vary, with AUCs from 0.715 to 0.775. But their *average* scores 0.784, better than even the best single tree among them. This is called *bagging* (from *bootstrap aggregating*), and it is the heart of a random forest.\n\nA random forest adds one more twist. At every split, each tree may choose only from a *random subset* of the features, not from all of them. This stops all the trees from asking the same strong question first, and makes them more different from one another. Usually that improves the average further, though, as we will see, not always by much.\n\n## Growing a random forest with `ranger()` {#sec-forest-ranger}\n\n`ranger()` does all this, quickly. The formula is as before; `irregular ~ .` means \"irregular, explained by all the other columns\". We turn the outcome into a factor and ask for `probability = TRUE`, so that the forest gives the share of trees voting *irregular*, a risk score, rather than just a yes or no.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nforest <- ranger(irregular ~ ., data = train |> mutate(irregular = factor(irregular)),\n                 num.trees = 500, probability = TRUE, importance = \"permutation\")\nforest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRanger result\n\nCall:\n ranger(irregular ~ ., data = mutate(train, irregular = factor(irregular)),      num.trees = 500, probability = TRUE, importance = \"permutation\") \n\nType:                             Probability estimation \nNumber of trees:                  500 \nSample size:                      3500 \nNumber of independent variables:  11 \nMtry:                             3 \nTarget node size:                 10 \nVariable importance mode:         permutation \nSplitrule:                        gini \nOOB prediction error (Brier s.):  0.1369406 \n```\n\n\n:::\n:::\n\n\nThe printout gives the settings. `Mtry` is the number of features each split may choose from (by default, about the square root of the number of features), and `Target node size` the smallest group a tree will split further. These defaults work well most of the time.\n\nThe `OOB prediction error` deserves a word. Each tree was grown on a bootstrap sample, which leaves out about a third of the claims. For each claim, the trees that did *not* see it can predict it, like a test set built into the method. This *out-of-bag* (OOB) error is an honest estimate of how the forest will do on new data, available without setting aside a test set. For a probability forest, it is the *Brier score*, the average squared difference between the predicted probability and the actual outcome (0 or 1). Smaller is better.\n\nPredictions on new data come from `predict()`. The result holds a matrix of probabilities, one column per outcome.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nforest_score <- predict(forest, data = test)$predictions[, \"TRUE\"]\nhead(round(forest_score, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.097 0.053 0.363 0.263 0.726 0.278\n```\n\n\n:::\n:::\n\n\n## Forest, tree and logistic regression compared {#sec-forest-compare}\n\nLet us fit a logistic regression with all the features too, and compare the three on the test set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit <- glm(irregular ~ ., family = binomial, data = train)\n\nmodel_aucs <- c(logistic    = auc(predict(logit, test), test$irregular),\n                single_tree = auc(predict(one_tree, test), test$irregular),\n                forest      = auc(forest_score, test$irregular))\nround(model_aucs, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   logistic single_tree      forest \n      0.753       0.745       0.769 \n```\n\n\n:::\n:::\n\n\nThe forest ranks the claims better than the other two. Logistic regression assumes each feature acts separately and in a straight line, so it misses the threshold, the combination and the stronger effect for merchants. The single tree can capture these, but crudely and unstably. The forest captures them more smoothly.\n\nNotice, though, that our hand-made bag of 50 pruned trees did a little better still (0.784). The reason is in the settings. By default, `ranger()` grows each tree very deep, until groups of about 10 claims remain. Whether a claim turned out irregular is partly chance, and such deep trees learn some of that chance. Our pruned trees were shallower. We come back to this in @sec-forest-tuning.\n\nIn audit terms, the gains table of @sec-logistic-evaluate shows what this means for a team that can examine one claim in five.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_fifth_capture <- function(score) {\n  picked <- rank(-score) <= 0.2 * length(score)\n  round(100 * sum(test$irregular[picked]) / sum(test$irregular))\n}\nmap_dbl(list(logistic = predict(logit, test), single_tree = predict(one_tree, test),\n             forest = forest_score), top_fifth_capture)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   logistic single_tree      forest \n         49          41          52 \n```\n\n\n:::\n:::\n\n\nThe figures are the percentage of all the irregular claims that fall in the top 20% of each model's scores.\n\n## Looking inside the forest {#sec-forest-inside}\n\nA forest cannot be drawn like a tree, but two tools tell us what it has learnt.\n\n### Which features matter? Variable importance\n\nWe asked for `importance = \"permutation\"`. For each feature, the forest *shuffles* that column, so that its link with the outcome is broken, and measures how much worse the out-of-bag predictions become. A feature the forest relies on causes a big loss when shuffled. A useless one causes none.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimportance_df <- tibble(feature = names(forest$variable.importance),\n                        importance = forest$variable.importance) |>\n  arrange(importance)\n\nimportance_df |>\n  ggplot(aes(importance, fct_inorder(feature))) +\n  geom_col(fill = \"darkgreen\") +\n  labs(x = \"Loss in accuracy when the feature is shuffled\", y = NULL) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Permutation importance of each feature](12-4d-forest_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nThe refund-to-turnover ratio and the credit from non-filers matter most, followed by exporter type, new registration and a shared address. `sector`, `quarter_end` and `prior_claims`, which we planted with no effect, are at or near zero, and slightly negative values simply mean \"no use at all\". Note also `top_supplier_pct`. It does matter, but only together with a small number of suppliers, a combination that affects few claims, so its importance is low. Importance measures a feature's *overall* contribution, and a real but rare pattern can score low. So read a low importance as \"rarely useful\", not as \"never matters\". This alone is valuable to an audit team. It tells them which red flags have actually gone with irregularity in the past, and which are folklore.\n\n### How does risk change with a feature? Partial dependence\n\nImportance says *how much* a feature matters, not *how*. A *partial dependence* plot shows how the average predicted risk changes as one feature changes, with everything else as it was. We compute it ourselves: set the feature to each value in turn for every claim in the test set, predict, and average.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npartial_dependence <- function(model, data, feature, values) {\n  map_dbl(values, \\(v) {\n    data[[feature]] <- v\n    mean(predict(model, data = data)$predictions[, \"TRUE\"])\n  })\n}\n\nratio_grid <- seq(0.05, 0.80, by = 0.05)\npd_ratio <- tibble(refund_ratio = ratio_grid,\n                   avg_risk = partial_dependence(forest, test, \"refund_ratio\", ratio_grid))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npd_ratio |>\n  ggplot(aes(refund_ratio, avg_risk)) +\n  geom_line(linewidth = 1) +\n  geom_point() +\n  labs(x = \"Refund claimed as a share of turnover\", y = \"Average predicted risk\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Partial dependence of risk on the refund-to-turnover ratio](12-4d-forest_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nThe risk is flat up to a ratio of about 0.45, then jumps, and is flat again. The forest has found the threshold we planted, without being told, and shows it in a form an audit team can turn into a rule of thumb: refund claims above about 45% of turnover deserve a closer look. A logistic regression would have drawn a smooth slope instead, too high below the threshold and too low above it.\n\nThe same function, applied separately to merchants and manufacturers, shows the combined effect of exporter type and credit from non-filers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnonfiler_grid <- seq(0, 60, by = 5)\npd_nonfiler <- map(c(\"Manufacturer\", \"Merchant\"), \\(type) {\n  subset <- test |> filter(exporter_type == type)\n  tibble(exporter_type = type, nonfiler_pct = nonfiler_grid,\n         avg_risk = partial_dependence(forest, subset, \"nonfiler_pct\", nonfiler_grid))\n}) |> list_rbind()\n\npd_nonfiler |>\n  ggplot(aes(nonfiler_pct, avg_risk, colour = exporter_type)) +\n  geom_line(linewidth = 1) +\n  labs(x = \"Input credit from non-filing suppliers (%)\", y = \"Average predicted risk\",\n       colour = NULL) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Risk rises faster with credit from non-filers for merchant exporters](12-4d-forest_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nFor merchants the risk climbs much more steeply.\n\n## Tuning, briefly {#sec-forest-tuning}\n\nForests need little tuning, but three settings are worth knowing.\n\n- `num.trees`, the number of trees. More is never worse, only slower. 500 is usually plenty.\n- `mtry`, the number of features each split may choose from. Smaller values make the trees more different.\n- `min.node.size`, the smallest group a tree may split. Larger values make simpler trees.\n\nThe out-of-bag error lets us compare settings without touching the test set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntuning <- expand_grid(mtry = c(2, 3, 5), min.node.size = c(10, 50, 200)) |>\n  mutate(oob_error = map2_dbl(mtry, min.node.size, \\(m, s) {\n    set.seed(1)\n    ranger(irregular ~ ., data = train |> mutate(irregular = factor(irregular)),\n           num.trees = 500, probability = TRUE, mtry = m, min.node.size = s)$prediction.error\n  }))\ntuning |> arrange(oob_error)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 3\n   mtry min.node.size oob_error\n  <dbl>         <dbl>     <dbl>\n1     3            50     0.136\n2     2            50     0.136\n3     5            50     0.136\n4     5           200     0.137\n5     2            10     0.137\n6     3            10     0.137\n7     3           200     0.137\n8     5            10     0.138\n9     2           200     0.139\n```\n\n\n:::\n:::\n\n\n\n\nThe lowest out-of-bag error is at `mtry` = 3 and `min.node.size` = 50. Larger leaves, as we suspected, suit this noisy outcome better than the default of 10. Let us refit with the chosen settings, and only now check the test set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nforest_tuned <- ranger(irregular ~ ., data = train |> mutate(irregular = factor(irregular)),\n                       num.trees = 500, probability = TRUE,\n                       mtry = best$mtry, min.node.size = best$min.node.size)\ntuned_auc <- auc(predict(forest_tuned, data = test)$predictions[, \"TRUE\"], test$irregular)\nround(c(default_forest = model_aucs[[\"forest\"]], tuned_forest = tuned_auc), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndefault_forest   tuned_forest \n         0.769          0.780 \n```\n\n\n:::\n:::\n\n\nThe tuned forest's AUC rises to 0.78, level with our hand-made bag of pruned trees. The differences between settings are small, as they usually are. Do not expect tuning to transform a forest. Better *features* (@sec-logistic-features) usually help far more. One more point: the out-of-bag error measures how close the predicted *probabilities* are to the outcomes, while the AUC measures the *ranking*. The two usually agree on what is better, but not always exactly.\n\n## When a forest does not help {#sec-forest-nohelp}\n\nForests are not always better. In @sec-trees, irregularity in works contracts followed two simple rules, \"short window and few bidders\" and \"large nomination\". A single pruned tree is exactly the right shape for such data. Let us grow a forest on the same data.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to recreate the works contracts of the decision trees chapter\"}\nset.seed(33)\nn_w <- 3000\nworks <- tibble(\n  department  = sample(c(\"Roads\", \"Buildings\", \"Irrigation\", \"Water Supply\"), n_w, TRUE),\n  tender_mode = sample(c(\"Open\", \"Limited\", \"Nomination\"), n_w, TRUE, prob = c(0.7, 0.2, 0.1)),\n  value_lakh  = round(rlnorm(n_w, log(60), 0.9), 1),\n  window_days = pmax(3, round(rnorm(n_w, 26, 7))),\n  bidders     = pmax(1, rpois(n_w, 4.5))\n) |>\n  mutate(bidders = if_else(tender_mode == \"Nomination\", 1, bidders),\n         risk = case_when(\n           tender_mode == \"Nomination\" & value_lakh > 100 ~ 0.60,\n           window_days < 21 & bidders <= 2               ~ 0.65,\n           window_days < 21                              ~ 0.15,\n           TRUE                                          ~ 0.04),\n         irregular = runif(n_w) < risk) |>\n  select(-risk)\nset.seed(1)\nw_rows  <- sample(nrow(works), size = 0.7 * nrow(works))\nw_train <- works[w_rows, ]\nw_test  <- works[-w_rows, ]\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nw_tree <- rpart(irregular ~ ., data = w_train, method = \"anova\")\nset.seed(1)\nw_forest <- ranger(irregular ~ ., data = w_train |> mutate(irregular = factor(irregular)),\n                   num.trees = 500, probability = TRUE)\n\nround(c(single_tree = auc(predict(w_tree, w_test), w_test$irregular),\n        forest = auc(predict(w_forest, data = w_test)$predictions[, \"TRUE\"], w_test$irregular)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsingle_tree      forest \n      0.775       0.736 \n```\n\n\n:::\n:::\n\n\nHere the single tree does as well as, or better than, the forest. The forest's many deep trees also pick up chance patterns in the noise, while the pruned tree keeps only the two real rules, and gives them to us in readable form. So, as always, compare the methods on test data, and prefer the simpler one when it does as well.\n\n| | Logistic regression | Single tree | Random forest |\n|----------------|----------------|----------------|----------------|\n| Ranking accuracy | Good when effects are gradual and separate | Good when risk follows a few simple rules | Usually the best, especially with many features and mixed effects |\n| Explaining the result | Odds ratios, one per feature | Readable rules | Importance and partial dependence plots only |\n| Stability | Stable | Unstable | Very stable |\n| Effort | Needs features shaped by hand | Needs pruning | Works well with defaults |\n\n: Choosing between the three methods {#tbl-forest-choice}\n\n::: callout-tip\n## Audit tip\n\nUse a forest to *rank* cases and to learn *which* red flags matter, and a logistic regression or a tree to *explain* the selection. A common pattern is to select cases by forest score, and then show, in the audit plan, the importance chart and partial dependence plots, along with a simple tree fitted to the forest's scores, as a readable summary of what drove the selection.\n:::\n\n::: callout-note\nThe *isolation forest* of @sec-ano-iforest is a cousin of the random forest. It too grows many random trees, but uses them to find unusual records, without needing any past audit outcomes.\n:::\n\n::: callout-caution\nA forest is harder to explain to an auditee, or to a court, than a rule. Never present a forest's score as the reason for an observation. The observation must rest on what the examination of the case found. The score only explains why the case was examined.\n:::\n\n## A suggested workflow\n\n1. **Prepare** past cases with known outcomes, and split them into training and test sets.\n2. **Fit a baseline**: a logistic regression and a pruned tree.\n3. **Grow a forest** with `ranger(..., probability = TRUE, importance = \"permutation\")`, with default settings.\n4. **Compare** all three on the test set, with the AUC and the share caught in the top-ranked cases.\n5. **Look inside** the forest with variable importance and partial dependence plots, and check them against audit experience.\n6. **Tune lightly** with the out-of-bag error. For noisy audit outcomes, try larger values of `min.node.size`.\n7. **Score new cases**, select mostly by score with a random part, and explain the selection with the plots and a simple summary model.\n\n::: callout-important\n## Remember\n\n- A random forest averages hundreds of trees, each grown on a bootstrap sample with random subsets of features.\n- Averaging cancels out the mistakes of individual trees, so forests are stable and usually rank well.\n- The out-of-bag error is a free, honest estimate of performance on new data.\n- Permutation importance shows which features matter; partial dependence shows how.\n- A forest is not always better. Compare it with simpler models, and prefer them when they do as well.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `ranger()` | ranger | Grow a random forest; `probability = TRUE` for risk scores, `importance = \"permutation\"` for importance |\n| `predict()` | ranger, stats | Predictions for new data; for ranger, in `$predictions` |\n| `$prediction.error`, `$variable.importance` | ranger | Out-of-bag error and feature importance of a forest |\n| `rpart()` | rpart | A single tree, for comparison and bagging by hand |\n| `glm(family = binomial)` | stats | Logistic regression, for comparison |\n| `sample(replace = TRUE)` | base R | Draw a bootstrap sample |\n| `map()`, `map_dbl()`, `map2_dbl()`, `reduce()` | purrr | Grow many trees, and average their predictions |\n| `expand_grid()` | tidyr | All combinations of tuning settings |\n\n: Functions used in this chapter {#tbl-forestfunctions}\n",
    "supporting": [
      "12-4d-forest_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}