{
  "hash": "2ce767680cf94b4c786883f190aa168d",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Time Series Analysis {#sec-ts}\n\nTime series analysis is an essential technique for analysing and forecasting data over time. It is commonly used in fields like finance, economics and engineering.\n\nSo what is a time series? A time series is a sequence of data points recorded over time, in chronological order. Monthly expenditure of an office, daily cash balance, quarterly GST collections and yearly rainfall are all time series. Time series analysis means studying such data to understand its patterns and trends, and to predict its future values. It is therefore used for descriptive as well as predictive analysis.\n\nTime series analysis plays an important role in audit analytics as well. A few of the use cases are\n\n- **Revenue analysis.** An auditor may examine revenue data over time to find irregular or suspicious patterns. Unexpected fluctuations, unusual growth or decline, or a change in the usual seasonal pattern may indicate misstatement, leakage or fraud. We will see a complete example of this at the end of the chapter, in @sec-ts-audit.\n- **Expenditure analysis.** Government offices are known to spend much more in March, to use up the budget before the financial year ends. Time series methods let us see this *March rush* clearly, and find months which are unusual even after allowing for it. We discuss this in @sec-ano-ts.\n- **Inventory analysis.** Auditors examine inventory data to assess whether stock levels are adequate, to identify obsolescence or shrinkage, and to evaluate inventory management. Time series analysis helps in understanding inventory patterns and identifying risks.\n\nSeveral time series datasets are loaded by default in R. A few of these are listed below. We will use them to understand the various concepts of time series analysis.\n\n- `AirPassengers` contains monthly airline passenger numbers from 1949-1960. See @fig-tsex (a)\n- `Nile` contains the yearly flow of the river Nile from 1871 to 1970. See @fig-tsex (b)\n- `sunspots` contains monthly sunspot numbers from 1749-1983. See @fig-tsex (c)\n- `JohnsonJohnson` contains quarterly earnings per Johnson & Johnson share from 1960 to 1980. See @fig-tsex (d)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Few time series data sets in R](12-9ts_files/figure-html/fig-tsex-1.png){#fig-tsex fig-align='center' width=672}\n:::\n:::\n\n\nTo analyse any time series, we have to understand its different components.\n\n## Components of Time series\n\nA time series can be broken down into several components.\n\n- **Level.** The baseline value or average of the series. If a series were a straight horizontal line, it would have only a level, equal to the value where the line cuts the y-axis.\n- **Trend.** The long-term direction of the series. It shows whether the series is increasing, decreasing or staying about constant over time. For example, a clear increasing trend can be seen in Johnson & Johnson earnings in @fig-tsex (d).\n- **Seasonality.** A pattern which repeats at a *fixed and known* interval, like every year, every quarter or every week. For example, in @fig-tsex (d) the earnings of Johnson & Johnson go up and down in the same way every year. Monthly government expenditure peaks every March.\n- **Cycle.** Rises and falls which are *not* of a fixed length. Business cycles, which last a few years each, are an example. The sunspots in @fig-tsex (c) show cycles of roughly 11 years, but the length varies from one cycle to the next. That is why they are a cycle and not a season.\n- **Errors (Residuals).** The random fluctuations or noise that cannot be explained by the level, trend, seasonality or cycle. The year-to-year ups and downs of the Nile flow in @fig-tsex (b) are mostly of this kind. The error component tells us how uncertain and variable the data is, and so how much we can trust a forecast.\n\n## Additive or multiplicative components\n\nThe trend, seasonal and error components can combine with each other in two ways, additive or multiplicative. Which one fits depends on the data.\n\nAn **additive model** assumes that the components are *added* together. The value of the series at any time is the sum of the trend, seasonal and error components at that time.\n\n$$\ny_t = T_t + S_t + e_t\n$$ {#eq-ts-add}\n\nwhere $y_t$, $T_t$, $S_t$ and $e_t$ are the values of the series, trend component, seasonal component and residuals, respectively, at time $t$. In an additive series, the seasonal ups and downs stay about the same size, whatever the level of the series.\n\nA **multiplicative model** assumes that the components are *multiplied* together.\n\n$$\ny_t = T_t \\times S_t \\times e_t\n$$ {#eq-ts-mult}\n\nwhere $y_t$, $T_t$, $S_t$ and $e_t$ are defined as before. In a multiplicative series, the seasonal ups and downs grow as the series grows. The seasonal component is then a *percentage* of the trend, like \"March is 40% above an average month\". Note that the seasonal swings in `AirPassengers`, @fig-tsex (a), become wider every year. So its seasonality is multiplicative.\n\nWe can convert a multiplicative series into an additive one by taking its logarithm, because $\\log(T \\times S \\times e) = \\log T + \\log S + \\log e$. See @fig-logts. On the log scale, the seasonal swings of `AirPassengers` are about the same size every year.\n\n::: {#fig-logts}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-9ts_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=49%}\n:::\n\n::: {.cell-output-display}\n![](12-9ts_files/figure-html/unnamed-chunk-2-2.png){fig-align='center' width=49%}\n:::\n:::\n\n\nTransforming Time Series\n:::\n\nWe will learn how to separate these components in later sections.\n\n**Damped Trends:** Gardner and McKenzie [@mcke] observed in 1985 that most forecasting methods assume a trend will continue forever, however far ahead we forecast. Based on their empirical findings, they suggested that forecasts become more accurate if trends are *damped*, that is, made to flatten out gradually. We will learn about this concept as well in later sections.\n\n## Practical examples in R\n\nLet us first see how time series objects are handled in R.\n\n### Prerequisites {.unnumbered}\n\nMost of the time we will use base R. For forecasting, we will use `forecast`, a fabulous package developed by **Rob Hyndman**. Forecasting future values also tells us how well we have captured the trends and patterns in a series. We will also use `zoo` for rolling averages, `patchwork` for combining plots, and `tidyverse` for the audit example.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(forecast)\nlibrary(zoo)\nlibrary(patchwork)\nlibrary(tidyverse)\n```\n:::\n\n\n### Creating a time series object in R\n\nR provides a simple function `ts()` to convert a series of observations (basically a vector) into a time series object. The main arguments are\n\n```\nts(data,\n  start = 1,\n  end = numeric(),\n  frequency = 1,\n  ...)\n```\n\nwhere\n\n- `data` is a numeric vector or matrix containing the observations.\n- `start` is the time of the first observation. It is a single number, like `1871` for yearly data, or a pair of numbers, like `c(2022, 4)` for April 2022 in monthly data.\n- `end` is the time of the last observation, written the same way. We usually give only `start`, and R works out `end` from the length of the data.\n- `frequency` is the number of observations per unit of time. Monthly data has a frequency of 12, quarterly data 4, and yearly data 1.\n- `...` are other, rarely needed arguments, like `names` for the columns of a matrix of series.\n\nExample-1: Let us create a time series.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Monthly sales of a year, for the financial year 2022-23\nsales <- c(10, 20, 30, 25, 35, 40, 45, 50, 55, 60, 65, 70)\n\n# A monthly time series starting from April 2022\nsales_ts <- ts(sales, start = c(2022, 4), frequency = 12)\n\n# Print the time series object\nsales_ts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec\n2022              10  20  30  25  35  40  45  50  55\n2023  60  65  70                                    \n```\n\n\n:::\n:::\n\n\nNotice that R has placed the 12 values from April 2022 to March 2023 in a calendar layout. We can check its class.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(sales_ts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ts\"\n```\n\n\n:::\n:::\n\n\nLet us also check `Nile`, which is already available in base R. It is a yearly series, so it has a frequency of 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNile\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 1871 \nEnd = 1970 \nFrequency = 1 \n  [1] 1120 1160  963 1210 1160 1160  813 1230 1370 1140  995  935 1110  994 1020\n [16]  960 1180  799  958 1140 1100 1210 1150 1250 1260 1220 1030 1100  774  840\n [31]  874  694  940  833  701  916  692 1020 1050  969  831  726  456  824  702\n [46] 1120 1100  832  764  821  768  845  864  862  698  845  744  796 1040  759\n [61]  781  865  845  944  984  897  822 1010  771  676  649  846  812  742  801\n [76] 1040  860  874  848  890  744  749  838 1050  918  986  797  923  975  815\n [91] 1020  906  901 1170  912  746  919  718  714  740\n```\n\n\n:::\n:::\n\n\nWe can take out a part of a time series with `window()`. For example, the Nile flow from 1950 onwards is\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwindow(Nile, start = 1950)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime Series:\nStart = 1950 \nEnd = 1970 \nFrequency = 1 \n [1]  890  744  749  838 1050  918  986  797  923  975  815 1020  906  901 1170\n[16]  912  746  919  718  714  740\n```\n\n\n:::\n:::\n\n\n### Plotting Time Series Objects\n\nTo plot a `ts` object we can simply use `plot()`. Alternatively we can use `autoplot()`, which draws the series with `ggplot2`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Plotting in base R\nplot(sales_ts, main = \"Sales during FY 2022-23\\nDummy Data by author\")\n\nautoplot(AirPassengers) +\n  scale_y_log10('Logarithmic values') +\n  ggtitle('AirPassengers converted to additive') +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Example of time series plotting in R; Base R (Left) and ggplot2 (Right)](12-9ts_files/figure-html/fig-tsex2-1.png){#fig-tsex2-1 fig-align='center' width=48%}\n:::\n\n::: {.cell-output-display}\n![Example of time series plotting in R; Base R (Left) and ggplot2 (Right)](12-9ts_files/figure-html/fig-tsex2-2.png){#fig-tsex2-2 fig-align='center' width=48%}\n:::\n:::\n\n\n*Note: `autoplot()` is a function of `ggplot2`. The library `forecast` teaches it how to draw time series and forecasts. The plot is a `ggplot2` object, so it can be fine-tuned with the usual `ggplot2` functions, as we did with `scale_y_log10()` above.*\n\n## Time series modelling and forecasting\n\nForecasting the future is an important part of time series analysis. To forecast, we first need to *model* the data, that is, describe its pattern. Forecasting techniques can be broadly divided into two groups. *Data-based techniques*, like averaging, smoothing and decomposition, work directly on the observed values. *Model-based techniques*, like ARIMA, assume a particular statistical structure for the data and estimate its parameters. In practice the line between the two is not sharp. We will start with the simplest ones.\n\n### Naive method\n\nThis method assumes that the future value will be the same as the last observed value. It is the simplest and most basic forecasting method, and hence named *naive*. The formula is\n\n$$\n\\text{Naive method: }\\hat{Y}_{T+1} = Y_T\n$$ {#eq-ts-naive}\n\nHere, $\\hat{Y}_{T+1}$ is the forecast for the next period and $Y_T$ is the last observed value, in a series of $T$ observations. So predicting with the naive method requires no special skill. Yet it is useful. Any better method should at least beat the naive forecast.\n\n**Problem Statement-1:** Let us forecast the Nile flow for 5 future years. In `forecast` there is a function `naive()` which does this, once we give the value of the parameter `h`, short for forecasting **h**orizon. In @fig-naive, the forecast values (the blue line) are exactly the same as the last observed value. The shaded bands show the range in which the actual values are likely to fall.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nforecast::naive(Nile, h = 5) %>%\n  autoplot() +\n  theme_bw() +\n  labs(title = \"Nile flow - forecast by Naive method\",\n       x = \"Year\")\n```\n\n::: {.cell-output-display}\n![Naive forecasting](12-9ts_files/figure-html/fig-naive-1.png){#fig-naive fig-align='center' width=98%}\n:::\n:::\n\n\nBy default, 80% and 95% prediction intervals are shown as bands. We can choose other levels with the parameter `level`, for example `level = 90`. If we do not want the bands at all, we can use `autoplot(..., PI = FALSE)`.\n\nFor seasonal data, there is a variant called the *seasonal naive* method, `snaive()`. It forecasts each month as the value of the same month last year. Auditors use this idea all the time, when they compare this March with last March.\n\n### Moving averages\n\nIn this technique, the forecast is the average of the most recent $n$ observations. As new data comes in, the window of $n$ observations slides forward. A moving average smooths a time series by averaging neighbouring values. It reduces noise and reveals the underlying trend.\n\nThe formula for forecasting with a moving average is\n\n$$\n\\hat{Y}_{t+1} = \\frac{1}{n}(Y_t + Y_{t-1} + ... + Y_{t-n+1})\n$$ {#eq-ts-ma}\n\nHere, $\\hat{Y}_{t+1}$ is the forecast for the next period and $Y_t$, $Y_{t-1}$, ..., $Y_{t-n+1}$ are the past $n$ observations.\n\nA moving average can be *centred* or *trailing*.\n\n- In a **centred** moving average of order $k$, each value is replaced by the mean of itself, the $(k-1)/2$ values before it and the $(k-1)/2$ values after it. So $k$ is naturally an odd number. For an even $k$, like 12 for monthly data, `ma()` from `forecast` takes care of centring automatically. Centred averages are used to *see* the trend in past data.\n- In a **trailing** moving average, each value is replaced by the mean of itself and the $k-1$ values *before* it. It uses only past data, so it is the one we use for *forecasting*. The function `rollmeanr()` from `zoo` calculates it.\n\nSmoothed versions of `AirPassengers` for different $k$ can be seen in @fig-ma. Notice that the trailing average lags behind the data, since it uses only the past.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Simple Moving Averages](12-9ts_files/figure-html/fig-ma-1.png){#fig-ma fig-align='center' width=672}\n:::\n:::\n\n\n**Problem Statement-2:** Let us forecast the Nile flow using a moving average. We take a trailing moving average of the last 7 years with `rollmeanr()`. The forecast for every future year is then simply the last value of this moving average. Applying `naive()` to the moving average gives exactly that, as in the left side of @fig-ma1.\n\nIn the right side of @fig-ma1, we have done the same with the `wineind` data, which shows *Australian total wine sales by wine makers in bottles <= 1 litre. Jan 1980 – Aug 1994.* This is monthly data with a strong seasonal pattern. So we have used a 12-month moving average. An average over exactly one full year contains every month once, so the seasonal ups and downs cancel out and only the trend remains. We have also drawn the original series in black, so we can see both the original and the smoothed series.\n\n::: {#fig-ma1}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Nile flow, 7 year trailing moving average\nnile_ma <- rollmeanr(Nile, k = 7)\nnaive(nile_ma, h = 10) |>\n  plot(ylim = range(Nile), col = \"red\",\n       main = \"Forecasting\\nNile Flow\")\nlines(Nile)\n\n# Wine sales, 12 month trailing moving average\nnaive(rollmeanr(wineind, k = 12), h = 12) |>\n  plot(ylim = range(wineind),\n       xlim = c(1980, 1996),\n       col = \"red\",\n       main = \"Forecasting\\nAustralian Wine sales\")\nlines(wineind)\n```\n\n::: {.cell-output-display}\n![](12-9ts_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=48%}\n:::\n\n::: {.cell-output-display}\n![](12-9ts_files/figure-html/unnamed-chunk-8-2.png){fig-align='center' width=48%}\n:::\n:::\n\n\nSimple Moving averages\n:::\n\n::: callout-warning\n## Caution\n\nA moving average forecast is flat. It cannot follow a trend or a seasonal pattern into the future. Look at the wine sales forecast in @fig-ma1. It gives the average month, not the peaks and dips we can clearly expect. For such data we need the methods discussed next.\n:::\n\n### Exponential smoothing\n\nExponential smoothing methods forecast with weighted averages of past observations, giving more weight to recent observations. Examples are simple exponential smoothing, Holt's method and the Holt-Winters method.\n\n**Simple exponential smoothing (SES)** is the simplest of these. It is a weighted moving average in which the weights fall *exponentially* as the observations get older. *This method is suitable for data with no clear trend or seasonal pattern.*\n\n$$\n\\hat{y}_{T+1} = \\alpha{y_T} + \\alpha(1- \\alpha){y_{T-1}} + \\alpha(1 - \\alpha)^2{y_{T-2}} + ...\n$$ {#eq-ts-ses}\n\nThe smoothing parameter $\\alpha$ lies between $0$ and $1$. A value close to 1 gives almost all the weight to the latest observation, so the forecast follows the data closely. A value close to 0 spreads the weight over many past observations, so the forecast is very smooth. An example with $\\alpha = 0.1$ is shown in @fig-ses1 (Left).\n\nHolt extended SES by adding a trend component, with its own smoothing parameter $\\beta$. The method is named after him as **Holt's Linear Method**. Mathematically, there are now three equations.\n\n$$\n\\begin{aligned}\n\\hat{y}_{t+h|t} &= l_t + hb_t \\\\\nl_t &= \\alpha y_t + (1-\\alpha)(l_{t-1} + b_{t-1}) \\\\\nb_t &= \\beta(l_t - l_{t-1}) + (1-\\beta)b_{t-1}\n\\end{aligned}\n$$ {#eq-ts-holt}\n\nHere $\\alpha$ and $\\beta$ (again $0 \\le \\beta \\le 1$) are the smoothing parameters for level and trend respectively, and $h$ is the forecast horizon. Also, $y_t$ is the actual value, $l_t$ is the level (or intercept) and $b_t$ is the trend (or slope) of the series at time $t$. The first equation says that the forecast $h$ periods ahead is the latest level plus $h$ times the latest slope. Refer @fig-ses1 (Right).\n\nTo apply *SES* in R, we use the function `ses()`, and for *Holt's* method, `holt()`, both from `forecast`. If we do not give the values of $\\alpha$ and $\\beta$, R chooses the best values itself. Here we have fixed them, to see their effect.\n\n::: {#fig-ses1}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlynxses <- ses(lynx, h= 10, alpha = 0.1)\nholtfit <- holt(airmiles, h = 10, alpha = 0.3, beta = 0.1)\n\nautoplot(lynxses) +\n  autolayer(lynxses$fitted) +\n  ggplot2::ggtitle('SES with alpha = 0.1 : Lynx data') +\n  ggplot2::theme_bw() +\n  ggplot2::theme(legend.position = \"bottom\") +\n  ggplot2::labs(color = \"\")\n\nautoplot(holtfit) +\n  autolayer(holtfit$fitted) +\n  ggplot2::ggtitle(\"Holt's Linear Trend method with beta = 0.1 : AirMiles data\") +\n  ggplot2::theme_bw() +\n  ggplot2::theme(legend.position = \"bottom\") +\n  ggplot2::labs(color = \"\")\n```\n\n::: {.cell-output-display}\n![](12-9ts_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=49%}\n:::\n\n::: {.cell-output-display}\n![](12-9ts_files/figure-html/unnamed-chunk-9-2.png){fig-align='center' width=49%}\n:::\n:::\n\n\nSimple Exponential Smoothing (Left) Vs. Holt's Linear Method (Right)\n:::\n\nAs discussed earlier, damped trends often work better. Based on the work of Gardner and McKenzie, a damping parameter $\\phi$ was added. The equations become\n\n$$\n\\begin{aligned}\n\\hat{y}_{t+h|t} &= l_t + (\\phi + \\phi^2 + ... + \\phi^h)b_t \\\\\nl_t &= \\alpha y_t + (1-\\alpha)(l_{t-1} + \\phi b_{t-1}) \\\\\nb_t &= \\beta(l_t - l_{t-1}) + (1-\\beta)\\phi b_{t-1}\n\\end{aligned}\n$$ {#eq-ts-damped}\n\nIf $\\phi = 1$, these are the same as Holt's Linear Method. A value $0 < \\phi < 1$ damps the trend, so the forecast line gradually flattens, as shown in @fig-hl2 (Left). The two methods are compared in @fig-hl2 (Right).\n\nTo use *damped trends* in R, we set `damped = TRUE` in the `holt()` function. Example code is below.\n\n::: {#fig-hl2}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nholtfit <- holt(airmiles, h = 10, alpha = 0.3, beta = 0.1, damped = TRUE, phi = 0.8)\nautoplot(holtfit) +\n  autolayer(holtfit$fitted) +\n  ggplot2::ggtitle('Damped Trend Forecast with phi=0.8') +\n  ggplot2::theme_bw() +\n  ggplot2::theme(legend.position = \"bottom\") +\n  ggplot2::labs(color = \"\")\n\n\nholtfit <- holt(airmiles,\n                h = 10,\n                alpha = 0.3,\n                beta = 0.1)\n\nholtfit2 <- holt(\n  airmiles,\n  h = 10,\n  alpha = 0.3,\n  beta = 0.1,\n  damped = TRUE,\n  phi = 0.8\n)\n\nautoplot(airmiles)+\n  autolayer(holtfit, series=\"Holt's method\", PI = FALSE) +\n  autolayer(holtfit2, series=\"Holt's method with damped trend\", PI = FALSE)+\n  ggplot2::ggtitle(\"Holt's method\") + xlab(\"Year\") +\n  ylab(\"Revenue passenger miles\") +\n  guides(colour=guide_legend(title=\"Method\")) +\n  ggplot2::theme_bw() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](12-9ts_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=49%}\n:::\n\n::: {.cell-output-display}\n![](12-9ts_files/figure-html/unnamed-chunk-10-2.png){fig-align='center' width=49%}\n:::\n:::\n\n\nLinear method Vs. Damped trends\n:::\n\nTo include *seasonality* with $m$ periods in a year (12 for monthly data) along with trend and level, Holt and Winters added a seasonal component $s_t$ with its own smoothing parameter $\\gamma$. The equations of the **Holt-Winters additive method** are\n\n$$\n\\begin{aligned}\n\\hat{y}_{t+h|t} &= l_t + hb_t + s_{t+h-m(k+1)} \\\\\nl_t &= \\alpha(y_t - s_{t-m}) + (1-\\alpha)(l_{t-1} + b_{t-1}) \\\\\nb_t &= \\beta(l_t - l_{t-1}) + (1-\\beta)b_{t-1} \\\\\ns_t &= \\gamma(y_t - l_{t-1} - b_{t-1}) + (1-\\gamma)s_{t-m}\n\\end{aligned}\n$$ {#eq-ts-hw}\n\nwhere $k$ is the whole number part of $(h-1)/m$. The term $s_{t+h-m(k+1)}$ looks complicated, but it only means \"the seasonal value of the same month in the latest year of data\". So a forecast for next March uses the seasonal effect estimated for the latest March. In the *multiplicative* version, the seasonal effect multiplies the level and trend instead of being added.\n\nTo apply the *Holt-Winters* method in R, we use the function `hw()`. In the code below, we forecast `AirPassengers` with both `additive` and `multiplicative` seasonality. See @fig-hw1.\n\n::: {#fig-hw1}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhw1 <- hw(AirPassengers, seasonal = \"additive\")\nhw2 <- hw(AirPassengers, seasonal = \"multiplicative\")\n\n\nautoplot(hw1) +\n  ggtitle(\"Additive Model\") +\n  theme_bw()\n\nautoplot(hw2) +\n  ggtitle(\"Multiplicative Method\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](12-9ts_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=48%}\n:::\n\n::: {.cell-output-display}\n![](12-9ts_files/figure-html/unnamed-chunk-11-2.png){fig-align='center' width=48%}\n:::\n:::\n\n\nHolt-Winter's Method of Forecasting\n:::\n\nThe multiplicative forecast (right) keeps the seasonal swings growing, as in the data. The additive one (left) keeps them at a fixed size. As we saw, the seasonality of `AirPassengers` is multiplicative, so the right one is more believable.\n\nWe do not always have to choose between SES, Holt and Holt-Winters ourselves. The function `ets()` (short for Error, Trend, Seasonal) tries all these methods, with and without damping, additive and multiplicative. It picks the best one automatically. We will use it in the audit example.\n\n### Seasonal decomposition methods {.unnumbered}\n\nSeasonal decomposition separates a time series into its components, like trend, seasonality and noise. This lets us study each component and its effect on the series separately. There are several methods. We will discuss two of them.\n\n### Classical seasonal decomposition\n\nThe first is the **classical decomposition method**. It assumes that the seasonal pattern repeats *identically* every year. Its steps are\n\n- **Trend component.** The trend is estimated with a centred moving average over one full season, a 12-month average for monthly data. As we saw in the moving averages section, such an average cancels out the seasonal ups and downs.\n- **Seasonal component.** The trend is removed from the series. What is left is averaged for each month (or quarter) across all the years. This gives one seasonal value for each month.\n- **Residual component.** The trend and seasonal components are removed from the original series. What remains is the residual.\n\n**Problem Statement:** Let us decompose `AirPassengers` to see its components. In R, we use the function `decompose()`. Since we know the seasonality of `AirPassengers` is multiplicative, we set `type = \"multiplicative\"` (the default is additive).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndecomposed_air_passengers <- decompose(AirPassengers, type = \"multiplicative\")\n```\n:::\n\n\nThe result is a list. Its element `figure` gives the seasonal value of each month. In a multiplicative decomposition, these are seasonal *indices*. An index of 1.10 means that the month is usually 10% above the trend.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(decomposed_air_passengers$figure, 3) |>\n  setNames(month.abb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec \n0.910 0.884 1.007 0.976 0.981 1.113 1.227 1.220 1.060 0.922 0.801 0.899 \n```\n\n\n:::\n:::\n\n\nJuly and August are the peak months, about 22% above the trend, and November is the lowest, about 20% below it. Such seasonal indices are useful in audit as well. For example, we can measure how far March expenditure usually exceeds an average month.\n\nA plot of the decomposed `AirPassengers` is shown in @fig-stl1. It has four panels, (i) the observed, that is, original values, (ii) the trend, (iii) the seasonal pattern and (iv) the random noise.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndecomposed_air_passengers |>\n  plot()\n```\n\n::: {.cell-output-display}\n![Classical decomposition of AirPassengers (multiplicative)](12-9ts_files/figure-html/fig-stl1-1.png){#fig-stl1 fig-align='center' width=672}\n:::\n:::\n\n\nNotice that the trend is missing for the first six and last six months. A centred 12-month average needs six months on each side, which are not available at the ends of the series.\n\n### Seasonal and Trend decomposition using Loess^[Loess is a method for fitting a smooth curve through data, by fitting many small regressions on nearby points.]\n\nSTL (Seasonal and Trend decomposition using Loess) is a robust and flexible method for decomposing a time series into trend, seasonal and residual components. Instead of simple averages, it uses Loess, a method of fitting smooth curves, to estimate both the trend and the seasonal component. It repeats the two steps a few times, each time improving both estimates. It has some advantages over classical decomposition.\n\n- It gives a trend for the whole series, including the first and last months.\n- The seasonal pattern may be allowed to change slowly over the years.\n- It is *robust*, meaning a few unusual values do not spoil the estimates much.\n\nSTL works only with additive components. So for a multiplicative series like `AirPassengers`, we first take its logarithm. In R, we use the function `stl()`. Setting `s.window = \"periodic\"` tells it to keep the seasonal pattern the same every year. A plot of the STL decomposed `AirPassengers` is shown in @fig-stl2.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstl(log(AirPassengers), s.window = \"periodic\") %>%\n  plot()\n```\n\n::: {.cell-output-display}\n![STL Decomposition of log(AirPassengers)](12-9ts_files/figure-html/fig-stl2-1.png){#fig-stl2 fig-align='center' width=672}\n:::\n:::\n\n\n### Model-based techniques {.unnumbered}\n\nModel-based techniques fit a specific statistical model to the time series, and estimate its parameters from the data. They need more assumptions, but can give a more detailed understanding of the series. The most widely used are\n\n1. **Autoregressive Integrated Moving Average (ARIMA)** models. These explain each value from the previous values of the series (the *autoregressive* part, of order $p$) and from the previous forecast errors (the *moving average* part, of order $q$). Many series, like those with a trend, do not have a constant level. ARIMA handles them by working on the *differences* between consecutive values (the *integrated* part, of order $d$). An ARIMA model is written as ARIMA($p$,$d$,$q$).\n2. **Seasonal ARIMA (SARIMA)** models. These extend ARIMA to include seasonality, by also relating each value to the values of the same month in earlier years. They are written as ARIMA($p$,$d$,$q$)($P$,$D$,$Q$)$_m$, where the second set of orders is for the seasonal part, and $m$ is the number of periods in a season.\n\nChoosing $p$, $d$, $q$ and their seasonal versions by hand needs experience. Fortunately, the function `auto.arima()` from `forecast` tries many combinations and picks the best one. The argument `lambda = 0` asks it to work on the logarithm of the series, as `AirPassengers` is multiplicative. The forecasts are converted back to the original scale automatically.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nair_arima <- auto.arima(AirPassengers, lambda = 0)\nair_arima\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: AirPassengers \nARIMA(0,1,1)(0,1,1)[12] \nBox Cox transformation: lambda= 0 \n\nCoefficients:\n          ma1     sma1\n      -0.4018  -0.5569\ns.e.   0.0896   0.0731\n\nsigma^2 = 0.001371:  log likelihood = 244.7\nAIC=-483.4   AICc=-483.21   BIC=-474.77\n```\n\n\n:::\n:::\n\n\n`auto.arima()` has chosen an ARIMA(0,1,1)(0,1,1)$_{12}$ model. This model works so well for such data that it is famously known as the *airline model*, after this very dataset. Its forecast is shown in @fig-arima.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nforecast(air_arima, h = 24) |>\n  autoplot() +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Forecast of AirPassengers with a seasonal ARIMA model](12-9ts_files/figure-html/fig-arima-1.png){#fig-arima fig-align='center' width=672}\n:::\n:::\n\n\n### Which method to choose?\n\nWe have seen many methods. Which one forecasts best? The honest way to find out is to *test* them. We hide the last part of the data, forecast it with each method using only the earlier data, and compare the forecasts with what actually happened. The earlier part is called the *training* data, and the hidden part the *test* data.\n\nLet us keep 1949 to 1958 of `AirPassengers` for training, and the last two years, 1959 and 1960, for testing. The function `accuracy()` compares a forecast with the actual values. It gives the error measures we met in the regression chapter (@sec-regression), like RMSE, MAE and MAPE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain <- window(AirPassengers, end = c(1958, 12))\ntest  <- window(AirPassengers, start = c(1959, 1))\n\nforecasts <- list(\n  \"Naive\"                 = naive(train, h = 24),\n  \"Seasonal naive\"        = snaive(train, h = 24),\n  \"Holt-Winters (mult.)\"  = hw(train, h = 24, seasonal = \"multiplicative\"),\n  \"ETS (automatic)\"       = forecast(ets(train), h = 24),\n  \"ARIMA (automatic)\"     = forecast(auto.arima(train, lambda = 0), h = 24)\n)\n\nsapply(forecasts, \\(f) accuracy(f, test)[\"Test set\", c(\"RMSE\", \"MAE\", \"MAPE\")]) |>\n  t() |>\n  round(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      RMSE   MAE MAPE\nNaive                137.3 115.2 23.6\nSeasonal naive        77.0  71.2 15.5\nHolt-Winters (mult.)  37.2  33.2  7.3\nETS (automatic)       72.5  63.2 13.3\nARIMA (automatic)     43.2  39.4  8.5\n```\n\n\n:::\n:::\n\n\n\n\nThe naive forecast is off by 23.6% on average. The seasonal naive forecast does better, at 15.5%. The multiplicative Holt-Winters method is the best here, at 7.3%, closely followed by ARIMA at 8.5%.\n\n::: callout-note\n## No method is always best\n\nThe automatic choices of `ets()` and `auto.arima()` are made on the *training* data. They are good starting points, but they do not always win on the test data. Here `ets()` chose a damped trend, which turned out to be too cautious for these fast growing numbers. On another series, the order may change. So it is good practice to try a few methods and compare them on test data, as we did here.\n:::\n\n## Plotting different elements of time series\n\n`forecast` has some more plots which help us see the elements of a time series.\n\n- `ggseasonplot()` draws each year as a separate line against the months. It shows the seasonal pattern and how it changes over the years.\n- `ggsubseriesplot()` draws a mini plot for each month across the years, with the mean of that month as a horizontal line.\n- `gglagplot()` plots the series against *lagged* (earlier) values of itself.\n- `ggAcf()` plots the *autocorrelation function* (ACF), that is, the correlation of the series with its own lagged values.\n\nExample-1: The seasonal plot and sub-series plot of `AirPassengers` are in @fig-seasplots. Both show that July and August are the peak months every year. The seasonal plot also shows that each year is above the previous one, which is the trend.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ng1 <- ggseasonplot(AirPassengers) +\n  theme_bw()\ng2 <- ggsubseriesplot(AirPassengers) +\n  ggtitle('Sub-Series Plot') +\n  theme_bw() +\n  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))\n(g1 / g2)\n```\n\n::: {.cell-output-display}\n![Seasonality through seasonal and sub-series plots](12-9ts_files/figure-html/fig-seasplots-1.png){#fig-seasplots fig-align='center' width=672}\n:::\n:::\n\n\nExample-2: The lag plots of `AirPassengers` can be seen in @fig-lagp. Each panel plots the series against itself a certain number of months earlier. Notice the panel for lag 12. The points lie very close to the diagonal line. So each month is very similar to the same month a year earlier, which tells us that the series has a seasonality of 12 periods.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngglagplot(AirPassengers) +\n  ggtitle('Lag Plots') +\n  theme_bw() +\n  theme(legend.position = \"bottom\") +\n  labs(color = NULL) +\n  guides(color = guide_legend(nrow = 1))\n```\n\n::: {.cell-output-display}\n![Seasonality through lag plots](12-9ts_files/figure-html/fig-lagp-1.png){#fig-lagp fig-align='center' width=672}\n:::\n:::\n\n\nExample-3: The same information appears as numbers in the ACF plot of @fig-acf. Each bar is the correlation of the series with itself at that lag. The bars fall slowly, because of the trend, and peak again at lag 12 and 24, because of the seasonality. Bars crossing the blue dashed lines are significantly different from zero.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggAcf(AirPassengers, lag.max = 36) +\n  ggtitle('Autocorrelation function') +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Autocorrelation of AirPassengers](12-9ts_files/figure-html/fig-acf-1.png){#fig-acf fig-align='center' width=672 height=35%}\n:::\n:::\n\n\n## An audit example: is this year's revenue believable? {#sec-ts-audit}\n\nLet us now use forecasting the way an auditor would. Revenue collected by a government office usually follows a steady pattern of growth and seasonality. If we forecast this year's revenue from the past years, and the actual revenue falls well below the forecast, we have a lead. There may be leakage of revenue, like undervaluation, short levy, or receipts not accounted for.\n\n### Our sample data\n\nWe create monthly stamp duty receipts of an imaginary sub-registrar office, in ₹ lakh, from April 2017 to March 2024. Receipts grow by about 8% every year. They dip in the monsoon months, rise in the festive months of October and November, and peak in March. We have built two events into the data.\n\n- In April and May 2020, receipts nearly stopped because of the COVID-19 lockdown. This is a genuine, known event.\n- From September 2023, receipts are about 22% lower than they should be. This is our planted case of leakage.\n\nAs usual, new readers may skip the code which creates the data.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the stamp duty receipts\"}\nset.seed(2024)\nn <- 84  # April 2017 to March 2024\n\n# Seasonal pattern from April to March\nseason <- c(0.95, 0.95, 0.85, 0.80, 0.85, 0.90, 1.10, 1.15, 1.00, 1.00, 1.05, 1.40)\n\nreceipts <- 250 * 1.08^((0:(n - 1)) / 12) * rep(season, 7) * exp(rnorm(n, 0, 0.05))\n\n# Lockdown in April and May 2020\nreceipts[37:38] <- receipts[37:38] * c(0.08, 0.35)\n\n# Planted case. Receipts about 22% lower from September 2023\nreceipts[78:84] <- receipts[78:84] * 0.78\n\nstamp <- ts(round(receipts, 1), start = c(2017, 4), frequency = 12)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstamp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec\n2017                   249.5 244.7 214.1 201.7 231.0 247.8 293.5 298.8 247.5\n2018 250.4 257.4 384.5 267.4 262.0 197.4 218.6 224.8 256.7 284.8 293.7 300.9\n2019 290.6 318.5 401.3 282.6 258.1 249.6 246.1 229.5 269.5 310.2 345.1 299.3\n2020 328.1 318.4 446.7  24.3 102.8 263.5 262.4 262.9 292.6 369.0 418.1 312.3\n2021 335.8 358.4 489.2 333.6 358.3 284.8 267.0 287.2 300.3 375.8 380.8 374.4\n2022 356.1 400.3 510.1 377.9 366.6 324.9 302.2 347.8 339.2 380.0 457.9 396.3\n2023 350.0 435.2 519.5 382.5 380.7 344.9 318.5 371.5 297.6 335.8 372.5 306.1\n2024 344.5 361.7 425.8                                                      \n```\n\n\n:::\n:::\n\n\nLet us plot the data in @fig-stamp. The lockdown dip in 2020 is obvious. The fall after September 2023 is harder to see by eye.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nautoplot(stamp) +\n  labs(x = NULL, y = \"Receipts (₹ lakh)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Monthly stamp duty receipts of the sub-registrar office](12-9ts_files/figure-html/fig-stamp-1.png){#fig-stamp fig-align='center' width=672 height=35%}\n:::\n:::\n\n\n### Forecasting the year under audit\n\nThe year under audit is 2023-24. So we take the data up to March 2023 as training data, and keep 2023-24 aside to compare with the forecast.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_stamp  <- window(stamp, end = c(2023, 3))\nactual_stamp <- window(stamp, start = c(2023, 4))\n```\n:::\n\n\nWe fit a model with `ets()` on the training data and forecast the 12 months of 2023-24, with a 95% prediction interval. Let us also write a small function to put the forecast and actual values side by side.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_with_actual <- function(fc, actual) {\n  tibble(month    = as.yearmon(time(actual)),\n         actual   = as.numeric(actual),\n         forecast = as.numeric(fc$mean),\n         lower    = as.numeric(fc$lower),\n         upper    = as.numeric(fc$upper)) |>\n    mutate(gap   = actual - forecast,\n           below = actual < lower)\n}\n\nfc1 <- forecast(ets(train_stamp), h = 12, level = 95)\ncompare_with_actual(fc1, actual_stamp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 7\n   month     actual forecast lower upper    gap below\n   <yearmon>  <dbl>    <dbl> <dbl> <dbl>  <dbl> <lgl>\n 1 Apr 2023    382.     331.  239.  424.  51.1  FALSE\n 2 May 2023    381.     344.  245.  443.  36.8  FALSE\n 3 Jun 2023    345.     334.  229.  438.  11.3  FALSE\n 4 Jul 2023    318.     327.  216.  437.  -8.11 FALSE\n 5 Aug 2023    372.     337.  222.  453.  34.1  FALSE\n 6 Sep 2023    298.     357.  237.  478. -59.9  FALSE\n 7 Oct 2023    336.     412.  287.  538. -76.5  FALSE\n 8 Nov 2023    372.     433.  303.  563. -60.6  FALSE\n 9 Dec 2023    306.     389.  255.  524. -83.4  FALSE\n10 Jan 2024    344.     392.  254.  531. -47.8  FALSE\n11 Feb 2024    362.     410.  268.  553. -48.6  FALSE\n12 Mar 2024    426.     520.  373.  667. -93.8  FALSE\n```\n\n\n:::\n:::\n\n\n\n\nNot a single month is below the lower limit. The intervals are very wide. On average, the range from the lower to the upper limit is about ₹243 lakh, almost as large as a month's receipts. With such wide limits, almost nothing can look unusual. Why?\n\nThe reason is the lockdown. The model has seen receipts fall to nearly zero in April 2020, and so it believes that such falls can happen any time. A single extraordinary event in the past has made the model very unsure about the future.\n\n### Cleaning a known event\n\nThe lockdown was a known, one-time event. It is not part of the normal behaviour of this office. So it is fair to replace those two months with values the series would normally have had. The function `tsclean()` from `forecast` finds such outliers and replaces them with values estimated from the rest of the series.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_clean <- tsclean(train_stamp)\n\n# Compare the original and cleaned values for March to June 2020\ncbind(original = train_stamp, cleaned = train_clean) |>\n  window(start = c(2020, 3), end = c(2020, 6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         original  cleaned\nMar 2020    446.7 446.7000\nApr 2020     24.3 316.7061\nMay 2020    102.8 305.6639\nJun 2020    263.5 263.5000\n```\n\n\n:::\n:::\n\n\nOnly April and May 2020 have changed. Now let us forecast again from the cleaned data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfc2 <- forecast(ets(train_clean), h = 12, level = 95)\ncmp2 <- compare_with_actual(fc2, actual_stamp)\ncmp2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 7\n   month     actual forecast lower upper      gap below\n   <yearmon>  <dbl>    <dbl> <dbl> <dbl>    <dbl> <lgl>\n 1 Apr 2023    382.     390.  347.  433.   -7.46  FALSE\n 2 May 2023    381.     381.  339.  424.   -0.557 FALSE\n 3 Jun 2023    345.     327.  290.  363.   18.1   FALSE\n 4 Jul 2023    318.     319.  283.  354.   -0.140 FALSE\n 5 Aug 2023    372.     335.  297.  373.   36.4   FALSE\n 6 Sep 2023    298.     361.  321.  402.  -63.9   TRUE \n 7 Oct 2023    336.     427.  379.  476.  -91.5   TRUE \n 8 Nov 2023    372.     463.  411.  516.  -90.8   TRUE \n 9 Dec 2023    306.     406.  359.  452.  -99.4   TRUE \n10 Jan 2024    344.     405.  359.  451.  -60.5   TRUE \n11 Feb 2024    362.     440.  390.  491.  -78.5   TRUE \n12 Mar 2024    426.     580.  513.  647. -154.    TRUE \n```\n\n\n:::\n:::\n\n\n\n\nThe intervals are now much narrower, about ₹91 lakh on average. And the picture is clear. From April to August 2023, the actual receipts are close to the forecast. From Sep 2023 onwards, *every* month is below the lower limit. Together, the receipts in these 7 months are ₹639 lakh, or about ₹6.4 crore, less than forecast. @fig-stampfc shows this.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nautoplot(fc2) +\n  autolayer(actual_stamp, series = \"Actual\", linewidth = 0.8) +\n  scale_colour_manual(values = c(Actual = \"red\")) +\n  coord_cartesian(xlim = c(2021, 2024.25)) +\n  labs(x = NULL, y = \"Receipts (₹ lakh)\", title = NULL, colour = NULL) +\n  theme_bw() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Forecast (blue, with 95% interval) and actual receipts (red) for 2023-24](12-9ts_files/figure-html/fig-stampfc-1.png){#fig-stampfc fig-align='center' width=672}\n:::\n:::\n\n\n::: callout-tip\n## Audit tip\n\nA *sustained* shortfall, month after month from a clear starting point, is a much stronger lead than a single bad month. Find out what changed at that point. It could be a new officer, a change in the guideline values of property, a new software, or a change in the procedure of registration. Then examine the documents registered after that point, for example for undervaluation of property.\n:::\n\n::: callout-warning\n## Caution\n\nClean only those past events which are known, genuine and one-time, like a lockdown, a strike or a system failure. Record what was cleaned and why. Never clean the period under audit itself. That would hide the very problem we are looking for.\n:::\n\n## A suggested workflow\n\nFor any time series analysis in audit, we may follow these steps.\n\n1. **Create the time series.** Arrange the data by month or quarter, without gaps, and convert it with `ts()`, giving the correct `start` and `frequency`.\n2. **Plot it.** Look at the trend, the seasonality and any unusual events with `autoplot()`, `ggseasonplot()` and `ggsubseriesplot()`.\n3. **Decide additive or multiplicative.** If the seasonal swings grow with the level of the series, take the logarithm, or use multiplicative methods.\n4. **Decompose** the series with `decompose()` or `stl()`, to measure the seasonal pattern and see the trend clearly.\n5. **Clean known one-time events** in the past with `tsclean()`, and record what was cleaned.\n6. **Forecast** the period under audit from the earlier data, with `ets()`, `hw()` or `auto.arima()`. Where possible, compare methods on test data with `accuracy()`.\n7. **Compare the actual values with the forecast** and its prediction interval. Quantify the gap in rupees.\n8. **Verify with records.** Find out what changed, and examine the documents of the period.\n\n::: callout-important\n## Remember\n\nA forecast is the auditor's *expectation*, not the truth. A gap between the actual and the forecast is a *lead*, not a *finding*. There may be a genuine reason, like a change in tax rates, a court order or a slowdown in the market. Always find out the reason and examine the records before reporting.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `ts()` | base R (stats) | Creates a time series object |\n| `window()` | base R (stats) | Takes out a part of a time series between two times |\n| `plot()`, `autoplot()` | base R, ggplot2 with forecast | Plots a time series or a forecast |\n| `naive()`, `snaive()` | forecast | Naive and seasonal naive forecasts |\n| `ma()` | forecast | Centred moving average |\n| `rollmeanr()` | zoo | Trailing moving average |\n| `ses()`, `holt()`, `hw()` | forecast | Simple exponential smoothing, Holt's method and Holt-Winters method |\n| `ets()` | forecast | Chooses and fits the best exponential smoothing model automatically |\n| `auto.arima()` | forecast | Chooses and fits the best ARIMA model automatically |\n| `forecast()` | forecast | Forecasts from a fitted model, with prediction intervals |\n| `accuracy()` | forecast | Compares forecasts with actual values (RMSE, MAE, MAPE etc.) |\n| `decompose()`, `stl()` | base R (stats) | Classical and STL decomposition into trend, season and remainder |\n| `tsclean()` | forecast | Replaces outliers and missing values in a time series |\n| `ggseasonplot()`, `ggsubseriesplot()` | forecast | Seasonal and sub-series plots |\n| `gglagplot()`, `ggAcf()` | forecast | Lag plots and autocorrelation plot |\n\n: Functions used in this chapter {#tbl-tsfunctions}\n",
    "supporting": [
      "12-9ts_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}