{
  "hash": "79109ef2d0d8da8d8a855974b93a95d7",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Simple Linear Regression {#sec-regression}\n\nEvery office of the government spends money. An auditor cannot examine every voucher of every office. So we would like to know, before we start, which offices spend *more than they should*. But what should an office spend? A large office with many staff, a big building and many beneficiaries will naturally spend more than a small one. Comparing raw amounts only tells us which offices are big.\n\nRegression solves this problem. It learns, from all the offices together, how expenditure depends on its *drivers*, like staff strength, floor area or number of beneficiaries. It then gives an *expected* expenditure for each office. The difference between what an office actually spent and what was expected is the part its drivers cannot explain. Offices with a large unexplained part are our leads.\n\nAs an example, suppose we establish a relationship between the number of employees in an office and its monthly expenditure on salary. We can then predict the salary expenditure of any office if we know its staff strength. How much should an office with 10 employees spend on salary every month? And for the auditor, the more interesting question is the reverse one. Which offices are spending *much more* than their staff strength explains? We will answer exactly this question in @sec-reg-audit, once we have learnt to use several predictors together.\n\nFormally, regression models are a class of statistical models that let us explore the relationship between a response variable and one or more explanatory variables. Explanatory variables are also called *regressors*, *independent* variables or *predictors*. The response variable is also called the *dependent* or *outcome* variable. When the response variable is numeric and its relationship with the predictors is linear, the regression is called *linear regression*. There are some other assumptions too, which we will discuss later in the chapter.\n\nIn this chapter we will learn to\n\n- fit a regression line with one predictor, and read every part of its output,\n- check the assumptions behind it, with diagnostic plots,\n- predict expected amounts, with a range of likely values, and\n- use the residuals to pick the offices which spend more than their staff strength explains.\n\n@sec-mregression then builds on this with several predictors.\n\n## Prerequisites\n\nBesides `tidyverse`, we will use two more packages in this chapter. `broom` turns model results into tidy data frames. `performance` and `see` draw diagnostic plots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(performance)\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## Our data, office expenses of block offices {#sec-reg-data}\n\nMost of this chapter runs on one dataset. A state has 120 Block Development Offices (BDOs) in seven districts. Besides salaries, each office spends on electricity, telephone, stationery, vehicle hire, camps for beneficiaries and other contingencies. We call this the *office expenses* of the office. For the financial year 2023-24 we have, for each office,\n\n- `office_id` and `district`,\n- `terrain`, whether the block is in the plains, in the hills or in a tribal area,\n- `staff`, the number of employees in position,\n- `sanctioned`, the number of sanctioned posts,\n- `area_sqm`, the floor area of the office building in square metres,\n- `population`, the population of the block in thousand,\n- `beneficiaries`, the number of beneficiaries of the schemes run by the office, in thousand, and\n- `office_exp`, the office expenses for the year, in ₹ lakh.\n\nOffice expenses should grow with staff and with the number of beneficiaries served. Offices in the hills and in tribal areas should spend more on vehicle hire, for the same work. We have also planted two offices whose expenses are inflated by ₹11 lakh each, as if bills for vehicle hire were paid without any vehicle being used. Let us see if regression can find them. As in other chapters, new readers may skip the code which creates the data.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the block office data\"}\nset.seed(4012)\nn <- 120\ndistrict_terrain <- c(Etawah = \"Plain\", Sitapur = \"Plain\", Firozpur = \"Plain\",\n                      Almora = \"Hilly\", Chamba = \"Hilly\",\n                      Bastar = \"Tribal\", Mayurbhanj = \"Tribal\")\nbdo <- tibble(\n  office_id = sprintf(\"BDO-%03d\", 1:n),\n  district  = sample(names(district_terrain), n, replace = TRUE,\n                     prob = c(0.17, 0.17, 0.16, 0.13, 0.12, 0.13, 0.12))\n) |>\n  mutate(\n    terrain = factor(district_terrain[district], levels = c(\"Plain\", \"Hilly\", \"Tribal\")),\n    # offices in the hills and tribal areas are smaller\n    staff = round(case_when(terrain == \"Plain\" ~ runif(n, 22, 55),\n                            terrain == \"Hilly\" ~ runif(n, 12, 38),\n                            TRUE               ~ runif(n, 16, 44))),\n    sanctioned    = round(staff / runif(n, 0.80, 0.95)),\n    # bigger offices have bigger buildings\n    area_sqm      = round(120 + 11 * staff + rnorm(n, 0, 45)),\n    population    = round(runif(n, 60, 200) * if_else(terrain == \"Plain\", 1.2, 0.8)),\n    beneficiaries = round(population * runif(n, 0.25, 0.35), 1),\n    # office expenses in lakh, driven by staff, beneficiaries and terrain\n    office_exp = round(5 + 0.45 * staff + 0.12 * beneficiaries +\n                       c(Plain = 0, Hilly = 6, Tribal = 3.5)[as.character(terrain)] +\n                       rnorm(n, 0, 1.6), 2)\n  )\n\n# Planted cases. Vehicle hire of Rs 11 lakh paid without any vehicle used\nplanted <- c(\"BDO-027\", \"BDO-088\")\nbdo <- bdo |>\n  mutate(office_exp = if_else(office_id %in% planted, office_exp + 11, office_exp))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(bdo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 120\nColumns: 9\n$ office_id     <chr> \"BDO-001\", \"BDO-002\", \"BDO-003\", \"BDO-004\", \"BDO-005\", \"…\n$ district      <chr> \"Mayurbhanj\", \"Etawah\", \"Etawah\", \"Mayurbhanj\", \"Bastar\"…\n$ terrain       <fct> Tribal, Plain, Plain, Tribal, Tribal, Plain, Hilly, Hill…\n$ staff         <dbl> 40, 46, 34, 18, 35, 32, 13, 14, 34, 46, 26, 27, 14, 45, …\n$ sanctioned    <dbl> 45, 56, 42, 22, 38, 39, 16, 17, 40, 50, 27, 29, 17, 54, …\n$ area_sqm      <dbl> 614, 644, 445, 360, 533, 469, 241, 267, 509, 631, 406, 4…\n$ population    <dbl> 127, 188, 109, 65, 105, 165, 86, 146, 126, 115, 147, 112…\n$ beneficiaries <dbl> 31.8, 59.5, 29.2, 20.6, 31.2, 55.8, 28.7, 43.6, 34.6, 37…\n$ office_exp    <dbl> 28.02, 29.65, 24.20, 22.24, 28.63, 27.68, 20.53, 22.65, …\n```\n\n\n:::\n:::\n\n\nTogether these offices spent ₹31.79 crore on office expenses in the year. The smallest spent ₹16.16 lakh and the largest ₹38.41 lakh.\n\n## Basic concepts\n\nBefore we build a regression model, it is always good practice to visualise the data. It helps us see the nature of the relationship between the predictors and the response variable, if there is one. To see the relationship between two numeric variables, we use a scatter plot. See the two examples in @fig-concept. In the first plot there is a near perfect linear relationship between the sanctioned posts and the staff in position (correlation 0.99). In the second plot there is a clear positive relationship between office expenses and staff (correlation 0.77). The points are much more scattered around the line here.\n\n::: {#fig-concept}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-4Reg_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=47% height=45%}\n:::\n\n::: {.cell-output-display}\n![](12-4Reg_files/figure-html/unnamed-chunk-5-2.png){fig-align='center' width=47% height=45%}\n:::\n:::\n\n\nThe idea behind linear regression\n:::\n\nWhen the outcome variable has a linear relationship with the explanatory variable, the best prediction lies on a straight line. So the maths behind the prediction is finding the equation of that line, @eq-lr1.\n\n$$\ny = mx + c\n$$ {#eq-lr1}\n\nWhere\n\n- `m` is the slope of the line\n- `c` is the intercept on the Y-axis (value of $y$ when $x$ is `0`)\n\nFitting a regression thus means estimating both $m$ and $c$. In statistics, these two are usually written as $\\beta_1$ (slope) and $\\beta_0$ (intercept). Those familiar with coordinate geometry know that two points are enough to draw a line. But real data has many points, and they rarely lie on one line. So we can draw many different lines through them. Our goal is to find the *best* of these lines. But how?\n\nTo answer this, note that in practice the points do not lie on the regression line. See the plots in @fig-concept again. Hardly any point lies exactly on the line. So for each point there is an *actual* value of $y$ and a *fitted* value, the one on the line. The difference between the two is called the *residual*. It is the part of $y$ that the model is not able to explain. If $\\hat{y}$ is the fitted value and $y$ is the actual value, the residual $\\epsilon$ is\n\n$$\n\\epsilon = y - \\hat{y}\n$$ {#eq-lr2}\n\nor, we can say that\n\n$$\ny = \\beta_0 + \\beta_1x + \\epsilon\n$$ {#eq-lr3}\n\nThe best line is the one which leaves the smallest residuals. We cannot simply add up the residuals, because some are positive and some negative, and they cancel out. See @fig-errors, which shows the first 25 offices. So we either take their absolute values or their squares. The usual method is to minimise the *sum of squares* of residuals. Squaring gives more weight to large residuals than to small ones. It also gives a simple formula for the best line. That is why this technique is called **Ordinary Least Squares** or **OLS** regression.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Residuals are the gaps between the points and the line](12-4Reg_files/figure-html/fig-errors-1.png){#fig-errors fig-align='center' width=672 height=35%}\n:::\n:::\n\n\nFor an auditor, the residual is the most useful number of all. It is the amount which an office spent over and above (or below) what its drivers explain.\n\n## Simple linear regression in R\n\nWe do not have to do this minimisation ourselves. Base R has a function `lm()` which fits the best regression line for a given set of variables. The syntax is simple.\n\n```\nlm(formula, data, ...)\n```\n\nwhere\n\n- `formula` is a symbolic description of the model to be fitted. For our example above, we write `y ~ x`, read as \"y is explained by x\".\n- `data` is the data frame which contains the variables.\n\n`lm()` returns a special object. We can print it directly like other R objects. But it is best printed with the `summary()` function. Let us first see an example of *simple* linear regression, which is linear regression with only one independent variable.\n\n**Example 1.** Let us try to explain the office expenses (`office_exp`) of our block offices by their staff strength (`staff`). How much does one more employee add to the yearly office expenses?\n\nAs already stated, it is good practice to visualise the data first. So let us make a scatter plot, as in @fig-ex1plot.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbdo %>%\n  ggplot(aes(staff, office_exp)) +\n  # Scatter plot\n  geom_point() +\n  # adding a trend line without error bands\n  geom_smooth(method = 'lm', se=FALSE, formula = \"y~x\") +\n  labs(x = \"Staff in position\", y = \"Office expenses (₹ lakh)\") +\n  # Theme Black and White\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Office expenses and staff strength of block offices](12-4Reg_files/figure-html/fig-ex1plot-1.png){#fig-ex1plot fig-align='center' width=672 height=30%}\n:::\n:::\n\n\nThe relationship looks fairly linear (@fig-ex1plot), so let us build the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlin_reg1 <- lm(formula = office_exp ~ staff, data = bdo)\n\n# Let us print the object directly\nlin_reg1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = office_exp ~ staff, data = bdo)\n\nCoefficients:\n(Intercept)        staff  \n    15.5084       0.3477  \n```\n\n\n:::\n\n```{.r .cell-code}\n# Try printing it with summary()\nsummary(lin_reg1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = office_exp ~ staff, data = bdo)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-7.352 -1.682  0.070  2.006  7.823 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 15.50844    0.87125   17.80   <2e-16 ***\nstaff        0.34772    0.02629   13.23   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.899 on 118 degrees of freedom\nMultiple R-squared:  0.5972,\tAdjusted R-squared:  0.5938 \nF-statistic:   175 on 1 and 118 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nSimply printing the object gives us only the coefficients. Printing it with `summary()` gives us a lot of other information. But how do we read it? Before that, let us understand a few assumptions which we made, silently, while fitting the line.\n\n## Assumptions of linear regression\n\nLinear regression makes several assumptions about the data.\n\n- **Linearity.** The relationship between the predictor ($x$) and the outcome ($y$) is assumed to be linear. If we fit a straight line to a curved relationship, our results will be wrong. See @fig-linearity. The relationship there is actually cubic (green dashed line), and the straight line (red) misses it badly. When we use many predictors, as we will shortly, we also assume that their effects *add up*.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Is the relationship linear?](12-4Reg_files/figure-html/fig-linearity-1.png){#fig-linearity fig-align='center' width=50%}\n:::\n:::\n\n\n- **Normality of residuals.** The residuals are assumed to be normally distributed with a mean of $0$. Note that it is the *residuals* which should be normal, not the $y$ variable itself. If the model has captured the relationship well, what is left should be random noise. This assumption matters mainly for the p-values and confidence intervals. The line itself can be fitted without it.\n\n- **Homogeneity of residual variance.** The residuals are assumed to have the same spread at all values of $x$. Statistically this is called *homoskedasticity*. If the spread changes with $x$, it is called *heteroskedasticity*. See @fig-homod. The residuals in the left plot have equal spread. In the right plot, the spread grows as $x$ grows, which shows heteroskedasticity clearly. In audit data this is very common. Big offices, big contracts and big claims vary more, in rupees, than small ones.\n\n::: {#fig-homod}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-4Reg_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=47%}\n:::\n\n::: {.cell-output-display}\n![](12-4Reg_files/figure-html/unnamed-chunk-6-2.png){fig-align='center' width=47%}\n:::\n:::\n\n\nHomoskedasticity (left) vs. heteroskedasticity (right). Sample data created for demonstration only.\n:::\n\n- **Independence of residuals.** Each observation is assumed to be independent of the others. In our example, the expenses of one block office do not affect the expenses of another. Monthly data of the same office, on the other hand, is usually *not* independent, because this month's expenditure is related to last month's. Such data needs time series methods (@sec-ts).\n\n## Interpreting the output of `lm`\n\nLet us discuss each section of the `summary()` output, which we will call the model from here on.\n\n### `Call`\n\nThe `Call` section shows the formula used to fit the model. `office_exp` is our response variable and `staff` is the predictor. The data is `bdo`, all 120 offices.\n\n### `Residuals`\n\nThis is the five point summary of the residuals. As discussed, residuals are the actual values minus the fitted values. We can get the same numbers ourselves.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bdo$office_exp - lin_reg1$fitted.values)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-7.35244 -1.68198  0.07004  0.00000  2.00575  7.82301 \n```\n\n\n:::\n:::\n\n\nIdeally, the median of the residuals should be close to `0`, and the first and third quartiles should be about equally far from it. That tells us the residuals are roughly symmetrical, and the model is not consistently over-predicting or under-predicting. In our example the median is 0.070 lakh, practically zero. The quartiles, -1.68 and 2.01, are nearly balanced too. The histogram in @fig-ex1hist shows that the residuals look fairly normal, as we assumed.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Histogram of residuals](12-4Reg_files/figure-html/fig-ex1hist-1.png){#fig-ex1hist fig-align='center' width=672}\n:::\n:::\n\n\n### `Coefficients`\n\nThese were the goal of our exercise. There is one coefficient for the predictor (the slope, $\\beta_1$) and one for the intercept ($\\beta_0$). A positive slope means $y$ goes up when $x$ goes up. A negative slope means $y$ goes down when $x$ goes up. In our example,\n\n- when staff strength is `0`, the office expenses would be ₹15.51 lakh. We may think of it as the fixed cost of keeping an office open. But no office in our data has fewer than 13 staff. The intercept often has no practical meaning when $x = 0$ lies far outside the data, so we read it with care.\n- for every additional employee, the office expenses go up by ₹0.348 lakh, or about ₹34,800, a year on average.\n\nThus our regression line is\n\n$$\n\\text{Office expenses} = 15.5084 + 0.3477 \\times \\text{Staff}\n$$ {#eq-lr4}\n\nWe fitted the line on the offices of one state in one year. Another year's data would give slightly different coefficients. So the coefficients are only *estimates*, and each comes with some uncertainty. We can see a range of likely values for each coefficient, called the confidence interval, using the function `confint()`. By default, it gives 95% confidence intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(lin_reg1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept) 13.7831321 17.2337383\nstaff        0.2956649  0.3997839\n```\n\n\n:::\n:::\n\n\nSo each extra employee adds somewhere between ₹0.30 lakh and ₹0.40 lakh a year. The other columns of the coefficients table measure this uncertainty.\n\n- The *standard error* (`Std. Error`) tells us how much the estimate would vary from sample to sample. The confidence intervals above are built from it.\n- The *t value* is simply the estimate divided by its standard error. A large t value (positive or negative) means the estimate is large compared to its uncertainty.\n- The *p-value* (`Pr(>|t|)`) tests the null hypothesis that the true coefficient is zero, that is, $x$ has no effect on $y$. A small p-value, say below 0.05, lets us reject this.\n\nIn our example, the p-value of `staff` is very small, so staff strength clearly affects office expenses. The p-value of the intercept is very small too. We are rarely interested in the intercept, though.\n\n### `Signif. codes`\n\nThese are just legends for the stars shown next to each p-value. Notice the three stars next to `staff`. They mean its p-value is below 0.001, and we can safely reject the null hypothesis that $\\beta_1$ is $0$. The stars give a quick visual sense of which coefficients matter.\n\n### `Residual standard error`\n\nThe residual standard error (RSE) is one of the measures of how well the model fits the data. It is the standard deviation of the residuals, except that we divide by the *degrees of freedom* instead of $n$.\n\n$$\nRSE = \\sqrt{\\frac{1}{(n-2)} \\sum_{i=1}^n (y_i - \\hat{y_i})^2}\n$$ {#eq-lr5}\n\nHere the degrees of freedom are $n-2$, because we estimated two coefficients, one slope and one intercept. With 120 offices, that is 118. We can verify @eq-lr5 by calculation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsqrt(sum((bdo$office_exp - lin_reg1$fitted.values)^2) / (nrow(bdo) - 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.899115\n```\n\n\n:::\n:::\n\n\nThe RSE is in the units of $y$. So we can say that the model's predictions of office expenses are typically off by about ₹2.90 lakh.\n\n### `R-Squared`, both multiple and adjusted\n\n*Multiple R-squared* is also called the coefficient of determination. It is the most cited measure of how well a model fits. It tells us what share of the variation in the response variable is explained by the model. In our example about 60% of the variation in office expenses is explained by staff strength. We will discuss it in detail in the next section.\n\n*Adjusted R-squared* is R-squared with a penalty for the number of predictors in the model. R-squared never goes down when we add a predictor, even a useless one. Adjusted R-squared goes up only if the new predictor improves the model more than would be expected by chance. So it is the better measure to compare models with different numbers of predictors.\n\n### `F-Statistic` and `p-value`\n\nWhy another p-value? Here the null hypothesis is about the *whole* model. It says that *none* of the predictors has any relationship with the response variable, or that all slopes are zero. The alternative is that at least one slope is not zero. This is tested with the F-statistic. In our example, the p-value is very small. So we reject the null hypothesis and conclude that there is a relationship between `staff` and `office_exp`.\n\nWith one predictor, this test gives the same p-value as the t-test of the slope. With many predictors, the F-test is useful because it tests them all together. If we test twenty coefficients one by one, one or two may look significant just by chance.\n\n## Model evaluation metrics\n\nTo judge how accurate a model is, we need evaluation metrics. There are several. We will discuss a few of them here.\n\n### Mean absolute error (MAE)\n\nAs the name suggests, it is the mean of the absolute values of the residuals, @eq-lr6.\n\n$$\n{MAE} = \\frac{1}{N}\\sum_{i = 1}^{N}{\\lvert}{y_i - \\hat{y_i}}{\\rvert}\n$$ {#eq-lr6}\n\nIt is the average size of the error, in the units of $y$. A larger value means a less accurate model. On its own, MAE does not tell us much. But when we compare several models on the same data, we can choose the one with the lower MAE.\n\nOnce we extract `$residuals` from the model, calculating it is easy. In our example,\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mean Absolute Error\nlin_reg1$residuals |> abs() |> mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.295802\n```\n\n\n:::\n:::\n\n\nOn average, our expected expenses miss the actual expenses by about ₹2.30 lakh.\n\n### Mean square error (MSE) and root mean square error (RMSE)\n\nThe mean of the squares of the residuals is the mean square error or MSE, @eq-lr7.\n\n$$\n{MSE} = \\frac{1}{N}\\sum_{i = 1}^{N}({y_i - \\hat{y_i}})^2\n$$ {#eq-lr7}\n\nMSE punishes large residuals more, by squaring them. Like MAE, we can use it to choose the better of several models. In fact, MSE is exactly what OLS minimises while finding the coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mean Square Error\nlin_reg1$residuals^2 |> mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.264789\n```\n\n\n:::\n:::\n\n\nRMSE or root mean square error is the square root of MSE. It brings the error back to the units of $y$.\n\n$$\n{RMSE} = \\sqrt{\\frac{1}{N}\\sum_{i = 1}^{N}({y_i - \\hat{y_i}})^2}\n$$ {#eq-lr8}\n\nIn our example,\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Root Mean Square Error\nlin_reg1$residuals^2 |> mean() |> sqrt()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.874855\n```\n\n\n:::\n:::\n\n\nNotice that RMSE is very close to the residual standard error we saw earlier. The only difference is that RMSE divides by $N$, and RSE divides by the degrees of freedom.\n\n### Mean absolute percentage error (MAPE)\n\nThis metric takes each residual as a percentage of the actual value, @eq-lr9.\n\n$$\n{MAPE} = \\frac{1}{N}\\sum_{i = 1}^{N}{\\lvert}\\frac{({y_i - \\hat{y_i}})}{y_i}\\cdot{100}\\%{\\rvert}\n$$ {#eq-lr9}\n\nSince it is a percentage, MAPE does not depend on the scale of the data. We can compare a model on expenses in rupees with a model on expenses in lakh. In our example,\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mean Absolute Percentage Error\n{lin_reg1$residuals/bdo$office_exp} %>%\n  {abs(.)*100} %>%\n  mean(.) %>%\n  sprintf(\"MAPE is %1.2f%%\", .)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"MAPE is 8.99%\"\n```\n\n\n:::\n:::\n\n\n::: callout-warning\n## Caution\n\nMAPE breaks down when some actual values are zero or close to zero, because we divide by them. A ₹10 error on a ₹20 bill is a 50% error. In audit data, which often has zero or tiny amounts, check for these before using MAPE.\n:::\n\n### R-squared and adjusted R-squared\n\nAs already discussed, R-squared is the coefficient of determination. Its formula is @eq-lr10.\n\n$$\nR^2 = 1 - \\frac{\\sum_{i=1}^{N}(y_i - \\hat{y_i})^2}{\\sum_{i=1}^{N}(y_i - \\bar{y})^2}\n$$ {#eq-lr10}\n\nThe numerator in the fraction is called $SSE$ or Sum of Squares of Errors. The denominator is called $TSS$ or Total Sum of Squares, which measures how much $y$ varies around its own mean $\\bar{y}$. So $\\frac{SSE}{TSS}$ is the share of variation *left unexplained* by the model, and $R^2$ is the share *explained*. As $SSE$ gets closer to $0$, $R^2$ gets closer to $1$, a perfect model.\n\nWe can verify the formula with the results we have.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Sum of Squares of Errors\ny_bar <- mean(bdo$office_exp)\n(SSE <- sum(lin_reg1$residuals^2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 991.7747\n```\n\n\n:::\n\n```{.r .cell-code}\n(TSS <- sum((bdo$office_exp - y_bar)^2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2462.228\n```\n\n\n:::\n\n```{.r .cell-code}\n(r_sq <- 1 - SSE/TSS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5972044\n```\n\n\n:::\n:::\n\n\nThere is one more way to think of $R^2$. It is simply the square of the correlation between the actual and the fitted values. Let us verify.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(cor(bdo$office_exp, lin_reg1$fitted.values))^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5972044\n```\n\n\n:::\n:::\n\n\nAs we keep adding predictors to a model, $R^2$ keeps going up, even when the new predictors are useless. The model then starts fitting the noise in our sample, which is called *over-fitting*. Adjusted R-squared corrects for this by penalising the number of predictors, @eq-lr11.\n\n$$\n{Adjusted}\\;{ R^2} = 1 - \\frac{(1-R^2)(N - 1)}{(N - p - 1)}\n$$ {#eq-lr11}\n\nwhere $p$ is the number of predictors in the model. The `summary()` function gives both these metrics. We can verify the calculation. Here $N$ is 120 and $p$ is 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- nrow(bdo)\n1 - ((1 - r_sq) * (N - 1) / (N - 1 - 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5937908\n```\n\n\n:::\n:::\n\n\n## Plotting the results and their interpretation\n\nWe can pass the output of `lm()` to `plot()` to see six diagnostic plots. We choose them with the `which` argument. By default, R shows plots 1, 2, 3 and 5. The six plots are\n\n1. Residuals vs. fitted values\n2. Normal Q-Q\n3. Scale-Location\n4. Cook's distance\n5. Residuals vs. leverage\n6. Cook's distance vs. leverage\n\nLet us see these for our example.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), oma = c(0, 0, 2, 0))\nplot(lin_reg1, which = 1:2, sub.caption = \"\")\n```\n\n::: {.cell-output-display}\n![First two diagnostic plots](12-4Reg_files/figure-html/fig-plots1-1.png){#fig-plots1 fig-align='center' width=672 height=40%}\n:::\n:::\n\n\n\n\n1. **Residuals vs. fitted values.** This plot checks the first assumption, linearity. If the red line across the plot is roughly flat, the relationship is linear and a straight line is a fair choice. If the red line shows a clear curve, a straight line is missing some pattern. In our example the red line wanders a little, but there is no clear curve. So linear regression is appropriate.\n2. **Normal Q-Q.** This plot checks whether the residuals are normally distributed. If the points fall roughly along the straight diagonal line, they are. In our example, they follow the line closely.\n\nNotice also that R labels the three most extreme residuals with their row numbers. Here rows 88, 94, 52 are labelled. Row 88 is BDO-088, one of the two offices we planted. Already, with just one predictor, it stands out. We will come back to it in the audit use case at the end of this chapter.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), oma = c(0, 0, 2, 0))\nplot(lin_reg1, which = 3:4, sub.caption = \"\")\n```\n\n::: {.cell-output-display}\n![Next two diagnostic plots](12-4Reg_files/figure-html/fig-plots2-1.png){#fig-plots2 fig-align='center' width=672 height=40%}\n:::\n:::\n\n\n3. **Scale-Location.** This plot checks the assumption of equal variance or homoskedasticity. If the red line is roughly flat and the points are spread evenly around it, the assumption is met. A line going up from left to right is the usual sign of heteroskedasticity. In our example the red line has a gentle hump in the middle, but no steady rise. So the assumption is reasonably met.\n4. **Cook's distance.** An *influential* point is one which, if removed, would change the regression line noticeably. Not every outlier is influential. A point with a large residual but an ordinary $x$ value often moves the line very little. A point with an extreme $x$ value has more power to pull the line towards itself. This power is called *leverage*. Cook's distance combines the size of the residual and the leverage into one measure of influence. A common rule of thumb is to look closely at any point with Cook's distance above 0.5, or well above the others. In our example, row 92 has the largest Cook's distance, 0.06, which is not alarming.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), oma = c(0, 0, 2, 0))\nplot(lin_reg1, which = 5:6, sub.caption = \"\")\n```\n\n::: {.cell-output-display}\n![Last two diagnostic plots](12-4Reg_files/figure-html/fig-plots3-1.png){#fig-plots3 fig-align='center' width=672 height=40%}\n:::\n:::\n\n\n5. **Residuals vs. leverage.** This plot also finds influential points. Points with high leverage lie to the right. Any point outside the dashed red lines of Cook's distance is influential. In our example, no point is even close to these lines.\n6. **Cook's distance vs. leverage.** This shows the same information in another way. Points in the top right corner, with both high leverage and high Cook's distance, need attention.\n\nBase R's `plot()` can draw all these plots. The package `performance` draws all the relevant diagnostic plots together, nicely, and writes under each plot what to look for. See @fig-perf.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(lin_reg1)\n```\n\n::: {.cell-output-display}\n![Output from the performance package](12-4Reg_files/figure-html/fig-perf-1.png){#fig-perf fig-align='center' width=960}\n:::\n:::\n\n\nWith only one predictor there is no question of *multi-collinearity*, so `check_model()` cannot draw that plot and may give a message about it. Multi-collinearity is about one more assumption, which applies only when there are two or more predictors. The predictors should not be strongly related to each other. We will discuss it with multiple linear regression in @sec-mregression.\n\n## Using `lm` for predictions\n\nThe output of `lm()` is actually a list. It contains much more information than we saw above. Let us see what it contains.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(lin_reg1) |>\n  as.data.frame() |>\n  setNames('Objects')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Objects\n1   coefficients\n2      residuals\n3        effects\n4           rank\n5  fitted.values\n6         assign\n7             qr\n8    df.residual\n9        xlevels\n10          call\n11         terms\n12         model\n```\n\n\n:::\n:::\n\n\nWe may extract any of these as needed. For example,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlin_reg1$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)       staff \n 15.5084352   0.3477244 \n```\n\n\n:::\n:::\n\n\nThe package `broom` gives all this information as a tidy data frame. Its function `augment()` gives the fitted value, residual, leverage (`.hat`), Cook's distance (`.cooksd`) and standardised residual (`.std.resid`) for every row. If we pass the original data as `data = `, it keeps all the other columns too, like `office_id`. Let us sort the offices by their standardised residual, which we will explain in @sec-reg-staffleads.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naugment(lin_reg1, data = bdo) |>\n  select(office_id, terrain, staff, office_exp, .fitted, .resid, .std.resid, .hat, .cooksd) |>\n  arrange(desc(.std.resid)) |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  office_id terrain staff office_exp .fitted .resid .std.resid    .hat .cooksd\n  <chr>     <fct>   <dbl>      <dbl>   <dbl>  <dbl>      <dbl>   <dbl>   <dbl>\n1 BDO-088   Plain      27       32.7    24.9   7.82       2.71 0.0101   0.0374\n2 BDO-086   Hilly      37       34.5    28.4   6.14       2.13 0.0108   0.0246\n3 BDO-035   Hilly      34       32.6    27.3   5.27       1.83 0.00882  0.0148\n4 BDO-081   Hilly      25       29.4    24.2   5.22       1.81 0.0119   0.0197\n5 BDO-062   Hilly      28       30.5    25.2   5.22       1.81 0.00938  0.0155\n6 BDO-105   Hilly      34       32.2    27.3   4.83       1.67 0.00882  0.0124\n```\n\n\n:::\n:::\n\n\n\n\nThe planted office BDO-088 is at the top. It spent ₹7.82 lakh more than offices of its size usually do. But where is the other planted office, `BDO-027`? It is only at number 35 when all the offices are sorted this way. We will find out why in @sec-reg-bdoflags. Notice also that the other five offices at the top are all in the hills. Our model does not know about terrain yet. We will add it in @sec-mregression.\n\nLet us also visualise the predicted values against the actual values and residuals, in @fig-predvsact.\n\n::: {#fig-predvsact}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-4Reg_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=48%}\n:::\n\n::: {.cell-output-display}\n![](12-4Reg_files/figure-html/unnamed-chunk-17-2.png){fig-align='center' width=48%}\n:::\n:::\n\n\nPredicted vs. actual values (left) and residuals (right)\n:::\n\nTo predict for new data, we use the base R function `predict()`. The new data must be a data frame with a column of the *same name* as the predictor. Suppose three new block offices are being opened, with 15, 30 and 45 staff. Let us predict their yearly office expenses, which can help to check the budget estimates they send.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_vals <- data.frame(staff = c(15, 30, 45))\npredict(lin_reg1, new_vals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1        2        3 \n20.72430 25.94017 31.15603 \n```\n\n\n:::\n:::\n\n\nA prediction is never exact. We can ask `predict()` for a *prediction interval*, the range in which the expenses of a new office are likely to fall, 95 times out of 100.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(lin_reg1, new_vals, interval = \"prediction\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 20.72430 14.89517 26.55343\n2 25.94017 20.17468 31.70566\n3 31.15603 25.34891 36.96315\n```\n\n\n:::\n:::\n\n\n\n\nSo an office with 30 staff will most likely spend between about ₹20.2 lakh and ₹31.7 lakh a year. An office of that size which spends well beyond this range deserves a question.\n\n::: callout-warning\n## Caution\n\nPredict only within the range of the data used to build the model. Our block offices have from 13 to 54 staff. The model knows nothing about an office with 300 staff, and its prediction there may be nonsense. Predicting outside the range is called *extrapolation*. In audit, a model built on block offices should not be used to judge a district headquarters office.\n:::\n\n## Audit use case, offices that spend more than their staff explains {#sec-reg-staffleads}\n\nLet us now put this chapter's tools to one audit question. Which block offices spend much more than their staff strength explains? `augment()` already gives us the residual of every office. To judge how unusual each residual is, we use the *standardised* residual (`.std.resid`). It is the residual divided by its standard error, so all offices are on one scale. Under our assumptions, a value above 2 happens by chance in only about 1 office in 40. Let us keep such offices and show their excess in lakh.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleads1 <- augment(lin_reg1, data = bdo) |>\n  mutate(excess = office_exp - .fitted) |>\n  filter(.std.resid > 2) |>\n  arrange(desc(.std.resid)) |>\n  select(office_id, district, terrain, staff, office_exp, .fitted, excess, .std.resid)\nleads1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 8\n  office_id district terrain staff office_exp .fitted excess .std.resid\n  <chr>     <chr>    <fct>   <dbl>      <dbl>   <dbl>  <dbl>      <dbl>\n1 BDO-088   Firozpur Plain      27       32.7    24.9   7.82       2.71\n2 BDO-086   Chamba   Hilly      37       34.5    28.4   6.14       2.13\n```\n\n\n:::\n:::\n\n\nOnly 2 offices cross this line. Together they spent about ₹14.0 lakh more than offices of their size usually do. The first, BDO-088 in Firozpur, is one of the two offices we planted. The second, BDO-086 in Chamba, is in a hilly block.\n\nWhat would the auditor do with these leads? For BDO-088, we would call for the bills of its largest heads of expense, like vehicle hire, and check them with the log books. For BDO-086, we would first ask whether the terrain itself explains the excess. Vehicle hire costs more in the hills, and our model knows nothing about terrain. We would record the model, the leads and the replies in the working papers.\n\n::: callout-warning\n## Caution\n\nA model with one driver is only a first screen. This one missed the other planted office, `BDO-027`, and it points to offices in the hills which may be innocent. @sec-mregression adds beneficiaries and terrain to the model. In @sec-reg-bdoflags both planted offices then stand out clearly.\n:::\n\n## A suggested workflow\n\nFor a simple regression in audit, we may follow these steps.\n\n1. **Understand the drivers.** Decide, from knowledge of the business, which variable should explain the amount under audit. Regression only confirms or rejects relationships which make sense.\n2. **Visualise first.** Draw a scatter plot to see whether the relationship looks linear, and to spot obvious errors.\n3. **Fit a simple model** with `lm()`, and read its `summary()`.\n4. **Check influence.** Look at Cook's distance and leverage. Investigate and correct data entry errors before going further.\n5. **Check the assumptions** with `plot()` or `check_model()`.\n6. **Measure the fit.** Use R-squared, the residual standard error, MAE or RMSE to judge how far the expected values miss.\n7. **Flag the residuals.** Use `augment()` and pick the units with large standardised residuals. Quantify the excess in rupees. If many leads share a feature, like terrain, add it to the model first (@sec-mregression).\n8. **Verify with records.** Examine the documents of the flagged units before drawing any conclusion.\n\n::: callout-important\n## Remember\n\nA regression model shows association, not cause. A large residual means only that a unit does not fit the pattern of the others. It is a *lead*, not a *finding*. A model with one predictor knows only one driver. It may miss an irregular unit and point to an innocent one. Always examine the records before reporting.\n:::\n\n## Where next\n\n@sec-mregression adds more predictors to the model, including categories like terrain and interactions. It finds both planted block offices, and it looks for ghost employees in the salary bills of sub-divisional offices.\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `lm()` | base R (stats) | Fits a linear regression model |\n| `summary()` | base R | Shows coefficients, p-values, R-squared and F-test of a model |\n| `coef()`, `confint()` | base R (stats) | Gives the coefficients and their confidence intervals |\n| `residuals()`, `fitted()`, `sigma()` | base R (stats) | Gives the residuals, fitted values and residual standard error |\n| `predict()` | base R (stats) | Predicts for new data, optionally with prediction intervals |\n| `plot()` on a model | base R | Draws the six diagnostic plots, chosen with `which` |\n| `cooks.distance()`, `rstandard()` | base R (stats) | Gives Cook's distance and standardised residuals |\n| `names()` | base R | Lists the parts of a model object |\n| `augment()` | broom | Gives fitted values, residuals, leverage and Cook's distance as a data frame |\n| `check_model()` | performance | Draws all diagnostic plots together, with guidance |\n| `glimpse()` | dplyr | Shows the columns of a data frame, with their types and first values |\n\n: Functions used in this chapter {#tbl-regfunctions}\n",
    "supporting": [
      "12-4Reg_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}