{
  "hash": "aeb8e8e2544e613c83ca809d2ba4ffab",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Nigrini's Tests for Unusual Amounts {#sec-nigrini}\n\nIn @sec-benford we met **Mark Nigrini**, the accounting professor who turned Benford's Law into a practical tool for fraud detection. Benford analysis is only one part of his work. Nigrini also put together a full set of simple tests, which forensic auditors now use all over the world. Each test looks at the *amounts* in a data set from a different angle. Each one is good at catching a different kind of problem.\n\nThe good thing about these tests is that none of them needs advanced statistics. They mostly count, sort and compare. Yet together they can point an auditor to a handful of suspicious records out of lakhs.\n\nSome of these tests are already covered in this book. The rest are covered in this chapter. @tbl-nigrini gives the complete picture.\n\n| Test | What it looks for | Where covered |\n|---------------------|---------------------------------|-----------------|\n| Benford's first digit, second digit, first-two digits tests | Digit patterns which are unnatural for real-life data | @sec-benford |\n| Same-Same-Same test | Same transaction recorded or paid more than once | @sec-dup |\n| Same-Same-Different test | Near duplicates, like the same bill with a new number | @sec-dup |\n| Largest subsets test | Vendors, employees or offices with the biggest totals | This chapter |\n| Relative Size Factor (RSF) test | One amount far larger than the rest of its group | This chapter |\n| Number duplication test | Exact amounts which repeat too often | This chapter |\n| Round number test | Too many amounts like ₹ 10,000 or ₹ 25,000 | This chapter |\n| Last-two digits test | Unusual endings like 00 or 50, a sign of made-up amounts | This chapter |\n\n: Nigrini's forensic analytics tests in this book {#tbl-nigrini}\n\nGaps in sequence numbers, which is another standard check, are covered in @sec-gaps.\n\n## Prerequisites\n\nWe will need only `tidyverse` in this chapter.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n## Our sample data\n\nLet us imagine a government department with five district offices in Uttar Pradesh. Each office makes small payments for day-to-day needs, like stationery, printing, catering, taxis, repairs and security. Such payments are often called *contingent expenditure*. Our data has all such bills paid during the financial year 2024-25.\n\nOne rule is important for this data. **The head of a district office can sanction a bill only up to ₹ 50,000.** A bill above this limit needs sanction from a higher authority. Such limits exist in almost every organisation. They are known as *delegation of financial powers*.\n\nAs in the previous chapter, we have planted a few problems in the data. We will find them one by one, using a different test each time. The code to create the data is folded below.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the sample data of contingent bills\"}\nset.seed(1947)\n\noffices <- c(\"Agra\", \"Bareilly\", \"Gorakhpur\", \"Jhansi\", \"Varanasi\")\n\n# Each vendor has a typical bill amount and a number of bills in the year\nvendors <- tibble(\n  vendor = c(\"Annapurna Caterers\", \"Bharat Stationers\", \"City Cab Services\",\n             \"Deep Electricals\", \"Ganga Printers\", \"Gupta Computers\",\n             \"Himalaya Furnishers\", \"Kaveri Suppliers\", \"Laxmi Hardware\",\n             \"National Xerox Centre\", \"New India Tent House\", \"Om Sai Caterers\",\n             \"Prakash Medical Store\", \"Rajdhani Travels\", \"Sai Ram Plumbing Works\",\n             \"Shree Ganesh Transport\", \"Sharma Office Solutions\",\n             \"Surya Security Services\", \"Verma & Sons\", \"Yamuna Cleaning Services\"),\n  typical = c(18000, 6000, 9000, 22000, 14000, 45000, 60000, 15000, 7000, 3500,\n              25000, 20000, 4000, 30000, 8000, 50000, 12000, 70000, 16000, 28000),\n  n_bills = c(60, 110, 90, 45, 70, 30, 20, 80, 75, 140,\n              35, 50, 95, 40, 55, 45, 65, 24, 60, 36)\n)\n\n# Genuine bills. Amounts vary around each vendor's typical amount.\nbills <- vendors |>\n  rowwise() |>\n  reframe(vendor = vendor,\n          amount = round(rlnorm(n_bills, log(typical), 0.45))) |>\n  mutate(office = sample(offices, n(), replace = TRUE),\n         bill_date = as.Date(\"2024-04-01\") + sample(0:364, n(), replace = TRUE))\n\n# A vendor with only two bills in the year\nmehta <- tibble(vendor = \"Mehta Interiors\", amount = c(42000, 168000),\n                office = \"Agra\", bill_date = as.Date(c(\"2024-06-12\", \"2024-12-03\")))\n\n# Planted case 1. A bill of 21,450 keyed in as 2,14,500\nslip <- tibble(vendor = \"Kaveri Suppliers\", amount = 214500,\n               office = \"Jhansi\", bill_date = as.Date(\"2024-11-18\"))\n\n# Planted case 2. One hugely inflated transport bill\ninflated <- tibble(vendor = \"Shree Ganesh Transport\", amount = 392800,\n                   office = \"Gorakhpur\", bill_date = as.Date(\"2025-01-22\"))\n\n# Planted case 3. Bills kept just below the limit of 50,000\nbelow_limit <- tibble(vendor = \"Om Sai Caterers\", office = \"Varanasi\",\n                      amount = c(rep(49500, 7), 49800, 49900, 49999, 48750, 49200),\n                      bill_date = as.Date(\"2024-08-01\") + sort(sample(0:150, 12)))\n\n# Planted case 4. Made-up round amounts\nround_bills <- tibble(vendor = \"Verma & Sons\", office = \"Bareilly\",\n                      amount = c(15000, 18000, 20000, 12000, 25000, 16000,\n                                 14000, 20000, 18000, 22000, 15000, 17500),\n                      bill_date = as.Date(\"2024-04-01\") + sort(sample(0:364, 12)))\n\nbills <- bind_rows(bills, mehta, slip, inflated, below_limit, round_bills) |>\n  arrange(bill_date) |>\n  mutate(voucher_no = sprintf(\"CV-%04d\", row_number())) |>\n  select(voucher_no, bill_date, office, vendor, amount)\n```\n:::\n\n\nLet us have a quick look.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(bills)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,253\nColumns: 5\n$ voucher_no <chr> \"CV-0001\", \"CV-0002\", \"CV-0003\", \"CV-0004\", \"CV-0005\", \"CV-…\n$ bill_date  <date> 2024-04-01, 2024-04-01, 2024-04-01, 2024-04-01, 2024-04-02…\n$ office     <chr> \"Agra\", \"Jhansi\", \"Gorakhpur\", \"Jhansi\", \"Varanasi\", \"Agra\"…\n$ vendor     <chr> \"City Cab Services\", \"Deep Electricals\", \"Shree Ganesh Tran…\n$ amount     <dbl> 13785, 17848, 87368, 86991, 5523, 10355, 1829, 26908, 4331,…\n```\n\n\n:::\n:::\n\n\nWe have 1253 bills from 21 vendors. The columns are simple. `voucher_no` is the contingent voucher number. `bill_date` is the date of the bill. `office` is the district office which paid it. `vendor` is the party paid, and `amount` is the amount paid in rupees.\n\n## Largest subsets test\n\nBefore looking for anything unusual, an auditor should first know *where the money goes*. In Nigrini's language, a **subset** is a group of records which share something in common. Here, all bills of one vendor form a subset. All bills of one office form another kind of subset.\n\nThe largest subsets test simply ranks the subsets by their total amount. It needs only `summarise()` and `arrange()`, which we learnt in @sec-DPLYRR.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbills |>\n  summarise(bills = n(),\n            total = sum(amount),\n            .by = vendor) |>\n  arrange(desc(total)) |>\n  head(6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  vendor                  bills   total\n  <chr>                   <int>   <dbl>\n1 Shree Ganesh Transport     46 2881647\n2 Surya Security Services    24 1938008\n3 Om Sai Caterers            62 1804706\n4 Himalaya Furnishers        20 1596145\n5 Gupta Computers            30 1539797\n6 Kaveri Suppliers           81 1468401\n```\n\n\n:::\n:::\n\n\nSix vendors account for a large part of the money. *Shree Ganesh Transport* is at the top. *Om Sai Caterers* is third, though the typical bill of a caterer is not large. That itself is a small hint, and we will come back to it.\n\n::: callout-tip\n## Audit tip\n\nThe largest subsets test does not find fraud by itself. It tells you where to look first. A vendor, an employee or a scheme which receives a big share of money deserves more attention, simply because more money is at risk there. Run the same test by office, by head of account and by month as well.\n:::\n\n## Relative Size Factor (RSF) test\n\nThe purpose of the RSF test is to identify anomalies where the largest amount for subsets in a given key is outside the norm for those subsets. This test compares the top two amounts for each subset and calculates the RSF for each.\n\n$$\nRSF = \\frac{Largest\\:Record\\:in\\:a\\:Subset}{Second\\:Largest\\:Record\\:in\\:a\\:Subset}\n$$ {#eq-rsf}\n\nLet us understand the idea with a simple example. Suppose a vendor usually sends bills of ₹ 10,000 to ₹ 20,000. One day a bill of ₹ 1,80,000 is paid to the same vendor. Compared with the whole data, ₹ 1,80,000 may not look large at all, because other vendors are paid much more. So a simple sort on amount will not show it. But compared with *this vendor's own* bills, it is nine times the next largest. RSF catches exactly this.\n\nA large RSF usually means one of these.\n\n-   **A keying error.** For example, ₹ 21,450 entered as ₹ 2,14,500, because of an extra zero or a missed decimal point.\n-   **An inflated bill.** The vendor, possibly with someone inside, has claimed far more than the actual supply.\n-   **A genuine but unusual purchase.** For example, the annual purchase of furniture in one go. This must be confirmed from documents.\n\n### Calculating RSF in R\n\nFor each vendor, we need the largest amount and the second largest amount. `max()` gives the largest. For the second largest, we sort the amounts in decreasing order and pick the second one with `[2]`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrsf <- bills |>\n  summarise(bills = n(),\n            largest = max(amount),\n            second_largest = sort(amount, decreasing = TRUE)[2],\n            .by = vendor) |>\n  mutate(rsf = round(largest / second_largest, 2)) |>\n  arrange(desc(rsf))\n\nrsf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 21 × 5\n   vendor                   bills largest second_largest   rsf\n   <chr>                    <int>   <dbl>          <dbl> <dbl>\n 1 Kaveri Suppliers            81  214500          48822  4.39\n 2 Mehta Interiors              2  168000          42000  4   \n 3 Shree Ganesh Transport      46  392800         127604  3.08\n 4 Gupta Computers             30  181403         104889  1.73\n 5 Prakash Medical Store       95   18183          11391  1.6 \n 6 Ganga Printers              70   56501          39998  1.41\n 7 Annapurna Caterers          60   93906          67254  1.4 \n 8 Bharat Stationers          110   23434          17435  1.34\n 9 Verma & Sons                72   58331          43532  1.34\n10 Yamuna Cleaning Services    36  108126          85885  1.26\n# ℹ 11 more rows\n```\n\n\n:::\n:::\n\n\nFor most vendors, RSF is between 1 and 2. That is normal. The largest bill of a vendor is usually not very far from its second largest. But three vendors stand out at the top, with RSF of 3 or more.\n\n### Subsets with very few records\n\nLook at *Mehta Interiors*. Its RSF is 4. But it has only two bills in the whole year. With just two bills, one of them is bound to be the largest, and the ratio can easily be large. So the RSF of a small subset tells us very little.\n\nThat is why we normally apply RSF only to subsets with some minimum number of records. Let us keep only vendors with at least five bills.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrsf |>\n  filter(bills >= 5, rsf >= 2.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  vendor                 bills largest second_largest   rsf\n  <chr>                  <int>   <dbl>          <dbl> <dbl>\n1 Kaveri Suppliers          81  214500          48822  4.39\n2 Shree Ganesh Transport    46  392800         127604  3.08\n```\n\n\n:::\n:::\n\n\nNow two vendors remain. Let us look at their three largest bills each. `slice_max()` picks the rows with the largest values in each group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbills |>\n  filter(vendor %in% c(\"Kaveri Suppliers\", \"Shree Ganesh Transport\")) |>\n  slice_max(amount, n = 3, by = vendor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  voucher_no bill_date  office    vendor                 amount\n  <chr>      <date>     <chr>     <chr>                   <dbl>\n1 CV-1009    2025-01-22 Gorakhpur Shree Ganesh Transport 392800\n2 CV-0285    2024-06-23 Agra      Shree Ganesh Transport 127604\n3 CV-1064    2025-02-06 Bareilly  Shree Ganesh Transport 118242\n4 CV-0783    2024-11-18 Jhansi    Kaveri Suppliers       214500\n5 CV-1057    2025-02-05 Bareilly  Kaveri Suppliers        48822\n6 CV-0950    2025-01-07 Gorakhpur Kaveri Suppliers        43107\n```\n\n\n:::\n:::\n\n\nIt also helps to compare the largest bill with the *usual* bill of the vendor. The median is a good measure of the usual bill.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbills |>\n  filter(vendor %in% c(\"Kaveri Suppliers\", \"Shree Ganesh Transport\")) |>\n  summarise(median_bill = median(amount),\n            largest = max(amount),\n            times_median = round(max(amount) / median(amount), 1),\n            .by = vendor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  vendor                 median_bill largest times_median\n  <chr>                        <dbl>   <dbl>        <dbl>\n1 Shree Ganesh Transport      51190.  392800          7.7\n2 Kaveri Suppliers            13513   214500         15.9\n```\n\n\n:::\n:::\n\n\nThe bill of ₹ 2,14,500 of *Kaveri Suppliers* is many times its usual bill. Its digits \"2145\" also look like a typical bill of this vendor with an extra zero, which points towards a keying error. The bill of ₹ 3,92,800 of *Shree Ganesh Transport* is also several times its usual bill.\n\nNotice one more thing. Both these bills are far above ₹ 50,000, the limit of the office head. So the auditor should also check whether sanction of the higher authority was taken for them.\n\n::: callout-note\n## Choosing the cut-offs\n\nThe minimum of five bills and the RSF cut-off of 2.5 are not fixed rules. Sort the table by RSF and read from the top. Look at the bills behind each high RSF until the cases stop being interesting. In large data, it also helps to add a materiality condition, for example, consider only those subsets where the largest amount is above a certain value.\n:::\n\n## Number duplication test\n\nIn real life, amounts of bills vary a lot. A stationery bill may be ₹ 5,523 one day and ₹ 6,218 the next. So if we count how many times each *exact* amount appears in the data, most amounts should appear only once, or perhaps twice by coincidence.\n\nThe number duplication test counts each exact amount and looks at the ones which repeat the most. `count()` with `sort = TRUE` does exactly this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbills |>\n  count(amount, sort = TRUE) |>\n  head(8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 2\n  amount     n\n   <dbl> <int>\n1  49500     7\n2   4501     3\n3   2491     2\n4   2599     2\n5   2647     2\n6   2924     2\n7   3202     2\n8   3410     2\n```\n\n\n:::\n:::\n\n\nThe amount of ₹ 49,500 has been paid seven times. No other amount appears more than three times. Let us see who received these payments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbills |>\n  filter(amount == 49500)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 5\n  voucher_no bill_date  office   vendor          amount\n  <chr>      <date>     <chr>    <chr>            <dbl>\n1 CV-0456    2024-08-11 Varanasi Om Sai Caterers  49500\n2 CV-0482    2024-08-18 Varanasi Om Sai Caterers  49500\n3 CV-0531    2024-09-04 Varanasi Om Sai Caterers  49500\n4 CV-0555    2024-09-09 Varanasi Om Sai Caterers  49500\n5 CV-0595    2024-09-22 Varanasi Om Sai Caterers  49500\n6 CV-0601    2024-09-24 Varanasi Om Sai Caterers  49500\n7 CV-0681    2024-10-20 Varanasi Om Sai Caterers  49500\n```\n\n\n:::\n:::\n\n\nAll seven bills are of the same vendor, and from the same office.\n\n::: callout-note\n## Number duplication and Same-Same-Same\n\nHow is this different from the duplicate tests of @sec-dup? There we looked for the same *bill* paid twice. Here, the bills are different, with different voucher numbers and dates. What repeats is only the *amount*. Repeated amounts are a sign that the amounts may not come from real supplies. Of course, there can be genuine reasons, like a fixed monthly rent or a fixed rate contract. Those can be quickly ruled out.\n:::\n\n### Amounts just below a limit\n\nThe amount of ₹ 49,500 is suspicious for one more reason. It is just below ₹ 50,000, the limit up to which the office head can sanction a bill. If bills are deliberately kept below this limit, the purchase escapes the scrutiny of the higher authority. A large purchase may also be *split* into several smaller bills for the same reason. This is commonly called **splitting of bills** or *threshold avoidance*.\n\nSo let us count, for each vendor, how many bills fall in a narrow band just below the limit, say between ₹ 45,000 and ₹ 50,000.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbills |>\n  summarise(bills = n(),\n            near_limit = sum(amount >= 45000 & amount < 50000),\n            .by = vendor) |>\n  filter(near_limit > 0) |>\n  mutate(pct_near_limit = round(100 * near_limit / bills, 1)) |>\n  arrange(desc(near_limit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 4\n   vendor                   bills near_limit pct_near_limit\n   <chr>                    <int>      <int>          <dbl>\n 1 Om Sai Caterers             62         14           22.6\n 2 Shree Ganesh Transport      46          6           13  \n 3 Surya Security Services     24          3           12.5\n 4 Himalaya Furnishers         20          3           15  \n 5 Gupta Computers             30          2            6.7\n 6 Yamuna Cleaning Services    36          2            5.6\n 7 Deep Electricals            45          1            2.2\n 8 Kaveri Suppliers            81          1            1.2\n 9 Rajdhani Travels            40          1            2.5\n10 Annapurna Caterers          60          1            1.7\n11 New India Tent House        35          1            2.9\n```\n\n\n:::\n:::\n\n\n*Om Sai Caterers* has the most bills in this band. Let us read this along with what we already know. A caterer's typical bill is not near ₹ 50,000. Yet this vendor's bills crowd just below the limit, seven of them for the very same amount, all from one office. This is a strong lead.\n\n*Shree Ganesh Transport* also has several bills in the band. But this vendor's usual bill is itself around ₹ 50,000, as we saw in the RSF section. So for this vendor, bills near ₹ 50,000 are expected. This is a good example of why the output of every test must be read with business sense.\n\n::: callout-tip\n## Audit tip\n\nAlso look at the *dates* of bills near the limit. Several bills of the same vendor, from the same office, within a few days of each other, strongly suggest that one purchase has been split. In our data, try `filter(vendor == \"Om Sai Caterers\", amount >= 45000)` and look at the `bill_date` column.\n:::\n\n## Round number test\n\nWhen a person makes up an amount, they tend to choose a round figure. ₹ 15,000 or ₹ 20,000 comes to mind more easily than ₹ 15,437. Real bills, on the other hand, are made of quantities multiplied by rates, plus taxes. So they rarely come out as exact thousands.\n\nIn R, the operator `%%` gives the remainder of a division. If `amount %% 1000` is zero, the amount is an exact multiple of ₹ 1,000. Let us find the share of such round amounts for each vendor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbills |>\n  mutate(is_round = amount %% 1000 == 0) |>\n  summarise(bills = n(),\n            round_bills = sum(is_round),\n            pct_round = round(100 * mean(is_round), 1),\n            .by = vendor) |>\n  arrange(desc(pct_round)) |>\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 4\n  vendor                bills round_bills pct_round\n  <chr>                 <int>       <int>     <dbl>\n1 Mehta Interiors           2           2     100  \n2 Verma & Sons             72          12      16.7\n3 Laxmi Hardware           75           1       1.3\n4 National Xerox Centre   140           1       0.7\n5 City Cab Services        90           0       0  \n```\n\n\n:::\n:::\n\n\nTaking the mean of a logical (`TRUE`/`FALSE`) column gives the proportion of `TRUE` values. We learnt this trick in @sec-basefuns.\n\nAgain, *Mehta Interiors* is at the top only because it has two bills, both round. We can ignore it, for the same reason as in the RSF test. The real outlier is *Verma & Sons*, with a much higher share of round amounts than any other vendor. For genuine bills, this share is close to zero.\n\n::: callout-warning\n## Caution\n\nSome payments are genuinely round. Fixed monthly charges, advances, honorarium and lump-sum contracts are good examples. Before treating round amounts as suspicious, check whether the nature of payment allows round figures.\n:::\n\n## Last-two digits test\n\nThe round number test looks at amounts ending in 000. The last-two digits test looks at the endings more broadly. Take the last two digits of every amount. For example, ₹ 15,437 ends in 37, and ₹ 49,500 ends in 00. In genuine data, every ending from 00 to 99 should be about equally common. So each ending should appear in about 1% of the amounts.\n\nMade-up amounts break this pattern. They end in 00 or 50 too often, because people like such numbers.\n\nWe can get the last two digits with `amount %% 100`. We consider amounts of ₹ 100 or more only, because smaller amounts do not have two meaningful last digits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlast_two <- bills |>\n  filter(amount >= 100) |>\n  mutate(last_two = amount %% 100) |>\n  count(last_two)\n\nexpected <- sum(last_two$n) / 100\nexpected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12.53\n```\n\n\n:::\n:::\n\n\nOn average, each ending should appear about 13 times. Let us see the actual counts in a bar chart, with the expected count as a dashed line (@fig-lasttwo).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(last_two, aes(last_two, n)) +\n  geom_col(fill = \"steelblue\") +\n  geom_hline(yintercept = expected, linetype = \"dashed\", colour = \"red\") +\n  scale_x_continuous(breaks = seq(0, 90, 10)) +\n  labs(x = \"Last two digits of amount\", y = \"Number of bills\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Last-two digits test on contingent bills](19-nigrini-tests_files/figure-html/fig-lasttwo-1.png){#fig-lasttwo width=672}\n:::\n:::\n\n\nMost bars are close to the dashed line, rising and falling by chance. But the bar at 00 stands far above all others.\n\nIs this difference large enough, or could it be just chance? The chi-square test, which we discussed in @sec-chis, answers this. We compare the observed counts with equal expected counts for all 100 endings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nendings <- bills |>\n  filter(amount >= 100) |>\n  pull(amount) %% 100\n\nobserved <- tabulate(endings + 1, nbins = 100)\nchisq.test(observed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  observed\nX-squared = 175.33, df = 99, p-value = 3.583e-06\n```\n\n\n:::\n:::\n\n\nThe p-value is far below 0.05. So the endings are *not* evenly spread, and this is unlikely to be due to chance. Now let us find who contributes to the extra 00 endings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbills |>\n  filter(amount %% 100 == 0) |>\n  count(vendor, sort = TRUE) |>\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  vendor                n\n  <chr>             <int>\n1 Verma & Sons         13\n2 Om Sai Caterers      11\n3 City Cab Services     2\n4 Mehta Interiors       2\n5 Bharat Stationers     1\n```\n\n\n:::\n:::\n\n\nThe same names appear again. *Verma & Sons* with its round amounts and *Om Sai Caterers* with its ₹ 49,500 bills together explain most of the spike.\n\n::: callout-note\n## About `tabulate()`\n\n`tabulate()` counts how many times each whole number from 1 to `nbins` appears. Endings run from 0 to 99, so we add 1 to make them run from 1 to 100. This also makes sure that endings which never appear are counted as zero, instead of being left out.\n:::\n\n## Putting the tests together\n\nEach test looked at the data from a different angle. A vendor which shows up in more than one test is a stronger lead than one which shows up only once. So let us build one table, with one row per vendor, and a flag for each test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvendor_flags <- bills |>\n  summarise(\n    bills      = n(),\n    rsf        = max(amount) / sort(amount, decreasing = TRUE)[2],\n    repeats    = max(table(amount)),\n    near_limit = sum(amount >= 45000 & amount < 50000),\n    pct_round  = 100 * mean(amount %% 1000 == 0),\n    .by = vendor\n  ) |>\n  filter(bills >= 5) |>\n  mutate(\n    flag_rsf    = rsf >= 2.5,\n    flag_repeat = repeats >= 4,\n    flag_limit  = near_limit >= 5,\n    flag_round  = pct_round >= 10,\n    total_flags = flag_rsf + flag_repeat + flag_limit + flag_round\n  ) |>\n  filter(total_flags > 0) |>\n  arrange(desc(total_flags))\n\nvendor_flags |>\n  select(vendor, bills, starts_with(\"flag\"), total_flags)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  vendor            bills flag_rsf flag_repeat flag_limit flag_round total_flags\n  <chr>             <int> <lgl>    <lgl>       <lgl>      <lgl>            <int>\n1 Shree Ganesh Tra…    46 TRUE     FALSE       TRUE       FALSE                2\n2 Om Sai Caterers      62 FALSE    TRUE        TRUE       FALSE                2\n3 Verma & Sons         72 FALSE    FALSE       FALSE      TRUE                 1\n4 Kaveri Suppliers     81 TRUE     FALSE       FALSE      FALSE                1\n```\n\n\n:::\n:::\n\n\n`max(table(amount))` gives the number of times the most repeated amount of a vendor appears. Adding logical columns counts the `TRUE` values, so `total_flags` is the number of tests in which a vendor was flagged.\n\nThis short table is what an auditor carries forward. Each vendor in it has a clear reason for being there. But the flags must still be *read*, not just counted. *Shree Ganesh Transport* has two flags. Yet we already know that bills near ₹ 50,000 are normal for this vendor. Its real issue is the single inflated bill. On the other hand, *Om Sai Caterers* also has two flags, and both point to the same story of bills kept just below the limit. The next step is to call for the original bills, sanctions and payment records of these vendors.\n\n## A suggested workflow\n\n1.  **Know the data and the rules.** Find the financial limits, rate contracts and fixed payments which apply. Without these, the output of the tests cannot be judged.\n2.  **Run the largest subsets test** to know where the money goes.\n3.  **Run the RSF test** on subsets with a reasonable number of records. Compare the largest amount with the usual amount of the subset.\n4.  **Run the number duplication test**, and look especially at amounts just below any financial limit.\n5.  **Run the round number and last-two digits tests** to look for made-up amounts.\n6.  **Combine the results** in one table, and examine first the subsets flagged by more than one test.\n7.  **Verify with documents.** Every flag is a question, not an answer.\n\n::: callout-important\n## Remember\n\nThese tests are *filters*. They reduce lakhs of records to a few dozen worth examining. A flag does not prove any wrongdoing. Genuine reasons, such as a fixed rate contract or a one-time bulk purchase, must be ruled out from records before any audit observation is made.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `summarise(.by = )` | dplyr | Calculates totals, counts, largest values etc. for each subset |\n| `max()`, `sort(x, decreasing = TRUE)[2]` | base R | Largest and second largest values, for RSF |\n| `slice_max()` | dplyr | Picks the rows with the largest values in each group |\n| `median()` | base R | Usual value of a subset, for comparison with the largest |\n| `count(sort = TRUE)` | dplyr | Counts each value and sorts by frequency |\n| `%%` | base R | Remainder of division, used to find round amounts and last two digits |\n| `mean()` of a logical column | base R | Proportion of `TRUE` values |\n| `tabulate()` | base R | Counts whole numbers, including those that never appear |\n| `chisq.test()` | stats | Tests whether observed counts differ from expected counts |\n| `table()` | base R | Counts each distinct value |\n\n: Functions used in this chapter {#tbl-nigrinifunctions}\n",
    "supporting": [
      "19-nigrini-tests_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}