{
  "hash": "0f79f1e8eb5a2fc9d241e421c5a7876e",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Logistic Regression for Risk Scoring {#sec-logistic}\n\nIn @sec-regression we used linear regression to predict a *number*, the expected salary expenditure of an office. Many audit questions, though, have a *yes or no* answer. Was this refund claim irregular? Will this contract overrun? Is this beneficiary ineligible? We cannot examine every case, so we would like to know, before examining them, which cases are most likely to be a \"yes\".\n\n*Logistic regression* answers exactly this. It learns from cases whose outcome is already known, like claims examined in last year's audit, how the chance of a \"yes\" depends on the features of a case. It then gives every new case a *risk score*, the estimated probability of a \"yes\". Examining the highest-scoring cases first finds far more irregularities for the same effort than picking cases at random.\n\nLogistic regression is the workhorse of risk scoring in tax departments, banks and insurers. For auditors it has one more virtue. Its results can be explained in plain words, \"claims of merchant exporters had about twice the odds of being irregular\", which matters when a selection has to be justified.\n\n**Prerequisites**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)\n```\n:::\n\n\n## From a straight line to an S-curve {#sec-logistic-idea}\n\nWhy not use linear regression for a yes/no outcome, coding \"yes\" as 1 and \"no\" as 0? Because a straight line goes on rising, or falling, for ever. For large enough values it predicts \"probabilities\" above 1 or below 0, which make no sense.\n\nLogistic regression instead fits an S-shaped curve, which always stays between 0 and 1. It rises slowly at first, then steeply, and then flattens out as it approaches 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(x = seq(-6, 6, by = 0.1)) |>\n  ggplot(aes(x, plogis(x))) +\n  geom_line(linewidth = 1) +\n  geom_hline(yintercept = c(0, 1), linetype = \"dashed\", colour = \"grey50\") +\n  labs(x = \"Combined risk from all features (log-odds)\", y = \"Probability of 'yes'\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![The logistic curve stays between 0 and 1](12-4b-logistic_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nTo understand the output, we need one idea, the **odds**. The odds of an event are the chance that it happens divided by the chance that it does not.\n\n- A probability of 0.5 is odds of 0.5/0.5 = 1, often said \"1 to 1\" or \"evens\".\n- A probability of 0.2 is odds of 0.2/0.8 = 0.25, or \"1 to 4\".\n- A probability of 0.8 is odds of 0.8/0.2 = 4, or \"4 to 1\".\n\nLogistic regression is a linear regression, not on the probability itself, but on the logarithm of the odds (the *log-odds*). We need not work with log-odds directly. What matters is how to read the result. Each coefficient, converted with `exp()`, becomes an **odds ratio**, the number by which the odds are *multiplied* when that feature increases by one unit. An odds ratio of 2 doubles the odds, 1 leaves them unchanged, and 0.5 halves them.\n\n## Our data, last year's refund audit {#sec-logistic-data}\n\nExporters can claim a refund of the GST paid on their inputs. Refunds are a known risk area, because fake input tax credit, claimed on invoices from suppliers who never paid the tax, can be turned into cash. Last year, the audit party examined 2,000 refund claims in detail, and recorded whether each was found irregular. For each claim we know\n\n- `exporter_type`, a manufacturer or a merchant exporter (who buys goods and exports them without manufacturing),\n- `reg_months`, how many months the claimant had been registered under GST,\n- `amount_lakh`, the refund claimed, in ₹ lakh,\n- `nonfiler_pct`, the percentage of the claimant's input tax credit which came from suppliers who had *not* filed their own returns,\n- `irregular`, the outcome of the audit.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the refund claims\"}\nmake_claims <- function(n, prefix) {\n  tibble(\n    claim_id      = sprintf(\"%s-%04d\", prefix, 1:n),\n    exporter_type = sample(c(\"Manufacturer\", \"Merchant\"), n, TRUE, prob = c(0.65, 0.35)),\n    reg_months    = pmax(1, round(rexp(n, 1 / 40))),\n    amount_lakh   = round(rlnorm(n, log(8), 1), 2),\n    nonfiler_pct  = round(100 * rbeta(n, 0.6, 6), 1)\n  ) |>\n    # The true risk, unknown to the auditor: higher for merchants, for claimants\n    # registered less than a year ago, for larger claims, and above all for\n    # credit from non-filing suppliers\n    mutate(true_logodds = -4.3 + 1.1 * (exporter_type == \"Merchant\") +\n             1.5 * (reg_months < 12) + 0.3 * log(amount_lakh) + 0.08 * nonfiler_pct,\n           irregular = runif(n) < plogis(true_logodds)) |>\n    select(-true_logodds)\n}\nset.seed(2028)\npast <- make_claims(2000, \"RF23\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npast\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,000 × 6\n   claim_id  exporter_type reg_months amount_lakh nonfiler_pct irregular\n   <chr>     <chr>              <dbl>       <dbl>        <dbl> <lgl>    \n 1 RF23-0001 Manufacturer          50        2.15         11.2 FALSE    \n 2 RF23-0002 Merchant              55        4.04          3.4 FALSE    \n 3 RF23-0003 Manufacturer          99        4.44          9.7 FALSE    \n 4 RF23-0004 Merchant              62        1.43          1.6 FALSE    \n 5 RF23-0005 Manufacturer          47        5.12         10.9 TRUE     \n 6 RF23-0006 Manufacturer          11        3.07          0.7 FALSE    \n 7 RF23-0007 Merchant              53        2.46          2.7 FALSE    \n 8 RF23-0008 Manufacturer          23        4.19          6.5 FALSE    \n 9 RF23-0009 Merchant               4        7.06          9.6 TRUE     \n10 RF23-0010 Merchant              17       11.9           0.3 TRUE     \n# ℹ 1,990 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\npast |> summarise(claims = n(), irregular = sum(irregular),\n                  irregular_pct = round(100 * mean(irregular), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  claims irregular irregular_pct\n   <int>     <int>         <dbl>\n1   2000       307         30700\n```\n\n\n:::\n:::\n\n\nAbout 15% of the claims examined were irregular. If we picked claims at random, about 15 of every 100 examined would turn out irregular. Let us see if we can do better.\n\n## Look at the data first\n\nBefore fitting any model, let us see how the irregular share varies with each feature. For the numeric features, we group them into bands with `cut()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npast |>\n  summarise(claims = n(), irregular_pct = round(100 * mean(irregular), 1), .by = exporter_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  exporter_type claims irregular_pct\n  <chr>          <int>         <dbl>\n1 Manufacturer    1288          11  \n2 Merchant         712          23.2\n```\n\n\n:::\n\n```{.r .cell-code}\npast |>\n  mutate(nonfiler_band = cut(nonfiler_pct, c(-Inf, 5, 10, 20, 30, Inf),\n                             labels = c(\"Up to 5%\", \"5-10%\", \"10-20%\", \"20-30%\", \"Over 30%\"))) |>\n  summarise(claims = n(), irregular_pct = round(100 * mean(irregular), 1), .by = nonfiler_band) |>\n  arrange(nonfiler_band)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  nonfiler_band claims irregular_pct\n  <fct>          <int>         <dbl>\n1 Up to 5%        1003           8  \n2 5-10%            351          11.7\n3 10-20%           388          19.3\n4 20-30%           149          34.2\n5 Over 30%         109          55  \n```\n\n\n:::\n\n```{.r .cell-code}\npast |>\n  mutate(registered = cut(reg_months, c(0, 6, 12, 24, 60, Inf),\n                          labels = c(\"Up to 6 months\", \"6-12 months\", \"1-2 years\",\n                                     \"2-5 years\", \"Over 5 years\"))) |>\n  summarise(claims = n(), irregular_pct = round(100 * mean(irregular), 1), .by = registered) |>\n  arrange(registered)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  registered     claims irregular_pct\n  <fct>           <int>         <dbl>\n1 Up to 6 months    293          31.1\n2 6-12 months       238          27.3\n3 1-2 years         410          12  \n4 2-5 years         597          10.2\n5 Over 5 years      462           8.9\n```\n\n\n:::\n:::\n\n\nMerchant exporters, and claims with much of their credit from non-filers, are clearly riskier. The registration table shows something worth noting. The risk is high for claimants registered for less than a year, and then drops sharply, changing only gently after that. It does not fall steadily month by month. We will come back to this.\n\n## Training and test data {#sec-logistic-split}\n\nA model always fits the data it learnt from better than new data, just as a student does best on questions already seen. To judge honestly how well it will work on *new* claims, we keep part of the data aside. The model learns from 70% of the claims, the *training* set, and is judged on the remaining 30%, the *test* set, which it has never seen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\ntrain_rows <- sample(nrow(past), size = 0.7 * nrow(past))\ntrain <- past[train_rows, ]\ntest  <- past[-train_rows, ]\nc(train = nrow(train), test = nrow(test))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntrain  test \n 1400   600 \n```\n\n\n:::\n:::\n\n\n## Fitting the model {#sec-logistic-fit}\n\nLogistic regression is fitted with `glm()`, the function for *generalised linear models*. The formula is written as in `lm()`. The argument `family = binomial` makes it a logistic regression. Since amounts are skewed, we use the logarithm of the amount, as is usual for money.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- glm(irregular ~ exporter_type + reg_months + log(amount_lakh) + nonfiler_pct,\n              family = binomial, data = train)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = irregular ~ exporter_type + reg_months + log(amount_lakh) + \n    nonfiler_pct, family = binomial, data = train)\n\nCoefficients:\n                       Estimate Std. Error z value Pr(>|z|)    \n(Intercept)           -3.208706   0.271141 -11.834  < 2e-16 ***\nexporter_typeMerchant  1.241768   0.174881   7.101 1.24e-12 ***\nreg_months            -0.014396   0.002945  -4.888 1.02e-06 ***\nlog(amount_lakh)       0.206591   0.089481   2.309    0.021 *  \nnonfiler_pct           0.082169   0.007209  11.399  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1155.47  on 1399  degrees of freedom\nResidual deviance:  933.44  on 1395  degrees of freedom\nAIC: 943.44\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\nThe output looks like that of `lm()`. Every feature has a small p-value, so each is related to the risk. But the coefficients are in log-odds, which are hard to read. `broom::tidy()` with `exponentiate = TRUE` converts them into odds ratios, with confidence intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nor1 <- tidy(model1, exponentiate = TRUE, conf.int = TRUE)\nor1 |> mutate(across(where(is.numeric), \\(x) round(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 7\n  term                  estimate std.error statistic p.value conf.low conf.high\n  <chr>                    <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 (Intercept)              0.04      0.271    -11.8    0        0.023     0.068\n2 exporter_typeMerchant    3.46      0.175      7.10   0        2.46      4.90 \n3 reg_months               0.986     0.003     -4.89   0        0.98      0.991\n4 log(amount_lakh)         1.23      0.089      2.31   0.021    1.03      1.47 \n5 nonfiler_pct             1.09      0.007     11.4    0        1.07      1.10 \n```\n\n\n:::\n:::\n\n\n\n\nRead them like this.\n\n- **Exporter type.** Merchant exporters have 3.5 times the odds of an irregular claim, compared with manufacturers with the same other features. The comparison is with the first category, `Manufacturer`, just as with factors in `lm()`.\n- **Credit from non-filers.** Each extra percentage point multiplies the odds by 1.086. That looks small, but it is per point. Ten more points multiply the odds by 1.086^10^, or 2.3.\n- **Amount.** Since we used the logarithm, the odds ratio applies to each multiplication of the amount by *e* (about 2.7). Larger claims are somewhat riskier.\n- **Months registered.** An odds ratio of 0.986 per month, slightly below 1. Older registrations are slightly less risky.\n\n::: callout-caution\nOdds ratios describe *association*, not cause. Being a merchant exporter does not make a claim irregular. Merchant exporters have simply been riskier in this data, perhaps because fake invoices are easier to use when nothing is manufactured. The model tells us where to look, not who is guilty.\n:::\n\n## Risk scores {#sec-logistic-score}\n\n`predict()` with `type = \"response\"` gives the predicted probability for each claim, its *risk score*. Without `type = \"response\"`, it gives log-odds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest <- test |> mutate(score = predict(model1, newdata = test, type = \"response\"))\n\ntest |>\n  arrange(desc(score)) |>\n  select(claim_id, exporter_type, reg_months, amount_lakh, nonfiler_pct, score, irregular) |>\n  head(8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 7\n  claim_id  exporter_type reg_months amount_lakh nonfiler_pct score irregular\n  <chr>     <chr>              <dbl>       <dbl>        <dbl> <dbl> <lgl>    \n1 RF23-1771 Merchant              44        8.89         61.7 0.949 TRUE     \n2 RF23-1892 Manufacturer           7       42.2          66.2 0.948 TRUE     \n3 RF23-0148 Merchant              37        7.99         54.8 0.919 TRUE     \n4 RF23-0327 Merchant               5       10.1          46   0.902 TRUE     \n5 RF23-1585 Manufacturer          20       12.3          56.9 0.845 FALSE    \n6 RF23-0305 Merchant               7       14.1          36.5 0.814 TRUE     \n7 RF23-1821 Merchant              13       13.9          36.5 0.800 TRUE     \n8 RF23-1106 Merchant              25        8.15         38.6 0.782 FALSE    \n```\n\n\n:::\n:::\n\n\nThe highest scores go to claims with a large share of credit from non-filers, often merchant exporters or recent registrations. Most of them were indeed found irregular.\n\n## How good is the model? {#sec-logistic-evaluate}\n\n### The accuracy trap\n\nThe obvious way to use a probability is to call a claim \"irregular\" if its score is above 0.5. Let us count how that works on the test set, in a *confusion matrix*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(predicted_irregular = test$score > 0.5, actually_irregular = test$irregular)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   actually_irregular\npredicted_irregular FALSE TRUE\n              FALSE   486   87\n              TRUE      9   18\n```\n\n\n:::\n:::\n\n\n\n\nThe model is right for 84% of the claims. That sounds good, until we notice that calling *every* claim regular would be right for 82.5%, since most claims are regular. Worse, it catches only 18 of the 105 irregular claims, 17%. When \"yes\" cases are rare, as irregularities usually are, *accuracy is a misleading measure*. Two other measures matter to an auditor.\n\n- **Recall** (or *sensitivity*), the share of irregular claims that the selection catches. Low recall means irregularities slip through.\n- **Precision**, the share of selected claims that turn out irregular. Low precision means examining many clean claims.\n\nA lower cut-off catches more irregular claims, at the cost of examining more clean ones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nevaluate_cutoff <- function(cutoff) {\n  picked <- test$score > cutoff\n  tibble(cutoff,\n         selected  = sum(picked),\n         caught    = sum(picked & test$irregular),\n         recall    = round(mean(picked[test$irregular]), 2),\n         precision = round(mean(test$irregular[picked]), 2))\n}\nmap(c(0.5, 0.3, 0.2, 0.1), evaluate_cutoff) |> list_rbind()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  cutoff selected caught recall precision\n   <dbl>    <int>  <int>  <dbl>     <dbl>\n1    0.5       27     18   0.17      0.67\n2    0.3       77     38   0.36      0.49\n3    0.2      149     62   0.59      0.42\n4    0.1      290     86   0.82      0.3 \n```\n\n\n:::\n:::\n\n\nThere is no single right cut-off. It depends on how many claims the audit party can examine, and on the cost of missing an irregular claim compared with examining a clean one.\n\n### Ranking: the ROC curve and AUC\n\nIn audit we rarely need a yes/no prediction at all. We need a good *ranking*, so that we can examine claims from the top down as far as our resources allow. The standard measure of ranking quality is the **AUC**, the *area under the ROC curve*. It has a simple meaning. Pick one irregular claim and one regular claim at random. The AUC is the probability that the model gives the irregular one the higher score. An AUC of 0.5 is no better than tossing a coin, and 1 is a perfect ranking. In practice, 0.7 to 0.8 is useful, and above 0.8 is good.\n\nThe AUC can be calculated from ranks, in the same way as the Wilcoxon test of @sec-tests-wilcox.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nauc <- function(score, actual) {\n  r  <- rank(score)\n  n1 <- sum(actual)\n  n0 <- sum(!actual)\n  (sum(r[actual]) - n1 * (n1 + 1) / 2) / (n1 * n0)\n}\nauc1 <- auc(test$score, test$irregular)\nauc1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7983261\n```\n\n\n:::\n:::\n\n\nThe AUC on the test set is 0.80. The ROC curve itself shows, for every possible cut-off, the share of irregular claims caught against the share of regular claims wrongly selected.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroc_points <- function(score, actual) {\n  ord <- order(score, decreasing = TRUE)\n  tibble(false_alarm_rate = c(0, cumsum(!actual[ord]) / sum(!actual)),\n         catch_rate       = c(0, cumsum(actual[ord]) / sum(actual)))\n}\nroc_points(test$score, test$irregular) |>\n  ggplot(aes(false_alarm_rate, catch_rate)) +\n  geom_line(linewidth = 1) +\n  geom_abline(linetype = \"dashed\", colour = \"grey50\") +\n  labs(x = \"Share of regular claims selected (false alarms)\",\n       y = \"Share of irregular claims caught\",\n       subtitle = paste(\"AUC =\", sprintf(\"%.2f\", auc1), \"; the dashed line is random selection\")) +\n  coord_equal() +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![ROC curve of the refund risk model on the test set](12-4b-logistic_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThe further the curve bows towards the top-left corner, the better. The dashed diagonal is what random selection would achieve.\n\n### The gains table, in audit language\n\nThe most useful view for planning is the *gains table*. Sort the claims by score, divide them into ten equal groups (*deciles*), and count how many irregular claims each group holds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngains <- test |>\n  mutate(decile = ntile(desc(score), 10)) |>\n  summarise(claims = n(), irregular = sum(irregular), .by = decile) |>\n  arrange(decile) |>\n  mutate(cum_claims_pct = round(100 * cumsum(claims) / sum(claims)),\n         cum_caught_pct = round(100 * cumsum(irregular) / sum(irregular)))\ngains\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 5\n   decile claims irregular cum_claims_pct cum_caught_pct\n    <int>  <int>     <int>          <dbl>          <dbl>\n 1      1     60        30             10             29\n 2      2     60        23             20             50\n 3      3     60        21             30             70\n 4      4     60         8             40             78\n 5      5     60         6             50             84\n 6      6     60         9             60             92\n 7      7     60         3             70             95\n 8      8     60         2             80             97\n 9      9     60         2             90             99\n10     10     60         1            100            100\n```\n\n\n:::\n:::\n\n\n\n\nExamining the top 20% of claims by score would have caught 50% of the irregular ones, and the top 30%, 70%. Random selection of 20% of claims would catch only about 20%. That is the value of the model, stated in terms any audit manager understands.\n\n## Making better features {#sec-logistic-features}\n\nRemember the registration table. The risk was high for claimants registered for less than a year, and much lower after that. But `model1` uses `reg_months` as a straight-line effect, a small change in risk for every month. It cannot capture a jump at one year. A simple feature that says whether the claimant is a *new registrant* matches the pattern better.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain <- train |> mutate(new_registrant = reg_months < 12)\ntest  <- test  |> mutate(new_registrant = reg_months < 12)\n\nmodel2 <- glm(irregular ~ exporter_type + new_registrant + log(amount_lakh) + nonfiler_pct,\n              family = binomial, data = train)\nor2 <- tidy(model2, exponentiate = TRUE, conf.int = TRUE)\nor2 |> mutate(across(where(is.numeric), \\(x) round(x, 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 7\n  term                  estimate std.error statistic p.value conf.low conf.high\n  <chr>                    <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 (Intercept)              0.012     0.295    -15.0    0        0.007     0.021\n2 exporter_typeMerchant    3.74      0.182      7.26   0        2.63      5.38 \n3 new_registrantTRUE       5.49      0.184      9.26   0        3.84      7.91 \n4 log(amount_lakh)         1.22      0.091      2.14   0.032    1.02      1.46 \n5 nonfiler_pct             1.09      0.008     11.9    0        1.08      1.11 \n```\n\n\n:::\n\n```{.r .cell-code}\ntest <- test |> mutate(score2 = predict(model2, newdata = test, type = \"response\"))\nauc2 <- auc(test$score2, test$irregular)\nc(model1 = round(auc1, 3), model2 = round(auc2, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmodel1 model2 \n 0.798  0.825 \n```\n\n\n:::\n:::\n\n\nNew registrants have 5.5 times the odds of an irregular claim, and the AUC on the test set improves from 0.798 to 0.825.\n\nWith only about 100 irregular claims in the test set, a small difference in AUC could be the luck of one particular split. A simple check is to repeat the split many times, and see how often the new model wins. (Repeating the split in a systematic way is called *cross-validation*.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nauc_gain <- map_dbl(1:40, \\(i) {\n  set.seed(i)\n  rows <- sample(nrow(past), size = 0.7 * nrow(past))\n  tr <- past[rows, ] |> mutate(new_registrant = reg_months < 12)\n  te <- past[-rows, ] |> mutate(new_registrant = reg_months < 12)\n  m1 <- glm(irregular ~ exporter_type + reg_months + log(amount_lakh) + nonfiler_pct,\n            family = binomial, data = tr)\n  m2 <- glm(irregular ~ exporter_type + new_registrant + log(amount_lakh) + nonfiler_pct,\n            family = binomial, data = tr)\n  auc(predict(m2, te), te$irregular) - auc(predict(m1, te), te$irregular)\n})\nc(splits = length(auc_gain), new_model_better = sum(auc_gain > 0),\n  average_gain = round(mean(auc_gain), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          splits new_model_better     average_gain \n          40.000           38.000            0.028 \n```\n\n\n:::\n:::\n\n\nThe new feature improves the ranking in 38 of 40 random splits, so the gain is real. Features built from audit knowledge, like \"registered less than a year ago\", \"supplier and claimant share an address\" or \"claim filed in the last week of the quarter\", often add more than any statistical refinement. Looking at the data first, as we did, is how such features are found.\n\n::: callout-tip\n## Audit tip\n\nCompare models on the *test* set, never on the training set. Adding features always improves the fit on the training data, even useless ones. Only the test set tells whether a change really helps on new cases.\n:::\n\n## Using the model on new claims {#sec-logistic-use}\n\nThis year, 1,500 refund claims are pending, and the audit party can examine 150 of them. Their outcomes are, of course, not known yet. We first refit the model on *all* of last year's claims, since the test set has done its job, and then score the new claims.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npast <- past |> mutate(new_registrant = reg_months < 12)\nfinal_model <- glm(irregular ~ exporter_type + new_registrant + log(amount_lakh) + nonfiler_pct,\n                   family = binomial, data = past)\n\nset.seed(2029)\npending <- make_claims(1500, \"RF24\") |>\n  select(-irregular) |>                         # outcomes not known yet\n  mutate(new_registrant = reg_months < 12)\n\npending <- pending |>\n  mutate(risk_score = predict(final_model, newdata = pending, type = \"response\"),\n         risk_rank  = min_rank(desc(risk_score)))\n\npending |> arrange(risk_rank) |>\n  select(claim_id, exporter_type, reg_months, amount_lakh, nonfiler_pct, risk_score) |>\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 6\n   claim_id  exporter_type reg_months amount_lakh nonfiler_pct risk_score\n   <chr>     <chr>              <dbl>       <dbl>        <dbl>      <dbl>\n 1 RF24-1343 Merchant              53       14.1          67.5      0.974\n 2 RF24-0411 Merchant               5        3.69         47.6      0.964\n 3 RF24-1298 Manufacturer           1        7.25         57.4      0.956\n 4 RF24-0360 Merchant               3       10.6          41        0.946\n 5 RF24-0685 Merchant              11        7.94         39.9      0.938\n 6 RF24-1477 Merchant              10       62.7          34.1      0.928\n 7 RF24-1157 Manufacturer           1        8.17         48.3      0.905\n 8 RF24-0892 Manufacturer           1       17.2          46.8      0.905\n 9 RF24-0535 Merchant               8       17.2          32.8      0.901\n10 RF24-0110 Manufacturer           4       27.6          45.3      0.900\n```\n\n\n:::\n:::\n\n\nHow should the 150 claims be chosen? Not only from the top of the list.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(11)\ntop_risk    <- pending |> slice_max(risk_score, n = 120)\nrandom_part <- pending |> anti_join(top_risk, by = \"claim_id\") |> slice_sample(n = 30)\n\nselection <- bind_rows(top_risk |> mutate(basis = \"Risk score\"),\n                       random_part |> mutate(basis = \"Random\")) |>\n  arrange(desc(risk_score))\ncount(selection, basis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  basis          n\n  <chr>      <int>\n1 Random        30\n2 Risk score   120\n```\n\n\n:::\n:::\n\n\nWe take the 120 highest-risk claims, and 30 more chosen at random from the rest, using `anti_join()` from @sec-joins so that no claim is picked twice. The random part is not a waste. It keeps the selection unpredictable, so claimants cannot learn to stay just below the model's radar. It catches kinds of irregularity the model has never seen. And it gives unbiased data for training next year's model, which brings us to the cautions.\n\n::: callout-caution\n## Cautions in using risk models\n\n- **The model learns only from what was examined.** If last year's audit examined mostly large claims, the model knows little about small ones. Outcomes from a partly random selection, as above, correct this over time.\n- **The past is not the future.** Once a risk becomes known, the fraud moves elsewhere. Refit the model every year, and check its AUC on the new year's results.\n- **Do not use features that should not decide treatment**, such as the religion, caste or gender of a proprietor, even if they appear predictive. Such a selection cannot be defended, and usually reflects bias in past selections rather than real risk.\n- **A score is not evidence.** A high score is a reason to examine a claim, never a finding in itself. The finding comes from the examination.\n- **Watch for perfect separation.** If some feature predicts the outcome perfectly in the training data, say every claim from one district was irregular, `glm()` warns that \"fitted probabilities numerically 0 or 1 occurred\", and the coefficients become unreliable. Merge such small groups, or drop the feature.\n:::\n\n## More than two outcomes, multinomial regression {#sec-logistic-multinom}\n\nSo far each claim was either regular or irregular. Real audit results are often richer. Suppose last year's audit party had recorded three outcomes for each claim examined.\n\n- **Clean**, nothing wrong.\n- **Procedural lapse**, such as a missing document or a wrongly filled form. The refund is due, but the claim needs correcting.\n- **Fraudulent**, a refund claimed on fake input tax credit.\n\nThese call for very different responses. A procedural lapse calls for a letter, a fraud for an investigation. And they may have quite different causes. Lumping them together as \"irregular\" throws this information away. **Multinomial logistic regression** extends logistic regression to an outcome with three or more categories.\n\nThe idea is a small step from what we know. One category is chosen as the *baseline*, here *Clean*. The model then fits one logistic regression for each other category against the baseline: *lapse* against *clean*, and *fraud* against *clean*, at the same time. Each feature gets one coefficient for each comparison. So a feature can raise the risk of fraud while having no effect on lapses, or the other way round.\n\nLet us give last year's claims such three-way outcomes. Unknown to the auditor, procedural lapses are commoner among new registrants and among small claims, while fraud goes with merchant exporters, large claims and credit from non-filers, as before.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the three-way outcomes\"}\nset.seed(2030)\noutcomes <- past |>\n  mutate(lp_lapse = -1.6 + 1.3 * new_registrant - 0.35 * log(amount_lakh),\n         lp_fraud = -4.6 + 1.2 * (exporter_type == \"Merchant\") + 0.3 * log(amount_lakh) +\n                    0.09 * nonfiler_pct,\n         # probabilities of the three outcomes, from the two log-odds\n         p_lapse = exp(lp_lapse) / (1 + exp(lp_lapse) + exp(lp_fraud)),\n         p_fraud = exp(lp_fraud) / (1 + exp(lp_lapse) + exp(lp_fraud)),\n         u = runif(n()),\n         outcome = case_when(u < p_fraud ~ \"Fraudulent\",\n                             u < p_fraud + p_lapse ~ \"Procedural lapse\",\n                             .default = \"Clean\"),\n         outcome = factor(outcome, levels = c(\"Clean\", \"Procedural lapse\", \"Fraudulent\"))) |>\n  select(claim_id, exporter_type, new_registrant, amount_lakh, nonfiler_pct, outcome)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(outcomes, outcome) |> mutate(pct = round(100 * n / sum(n), 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  outcome              n   pct\n  <fct>            <int> <dbl>\n1 Clean             1561  78  \n2 Procedural lapse   266  13.3\n3 Fraudulent         173   8.7\n```\n\n\n:::\n:::\n\n\nThe first level of the factor, *Clean*, is the baseline. Multinomial regression is fitted with `multinom()` from the package `nnet`, which comes with every installation of R. The formula is written as before. (`trace = FALSE` stops it printing the progress of its calculations.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(nnet)\nmulti_model <- multinom(outcome ~ exporter_type + new_registrant + log(amount_lakh) + nonfiler_pct,\n                        data = outcomes, trace = FALSE)\n```\n:::\n\n\n`broom::tidy()` works here too, with one row for each feature *and* each comparison. With `exponentiate = TRUE`, the estimates are again odds ratios, now the odds of that outcome *rather than a clean claim*. We show them side by side.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_or <- tidy(multi_model, exponentiate = TRUE, conf.int = TRUE)\n\nmulti_or |>\n  filter(term != \"(Intercept)\") |>\n  mutate(result = paste0(round(estimate, 2), \" (\", round(p.value, 3), \")\")) |>\n  select(term, y.level, result) |>\n  pivot_wider(names_from = y.level, values_from = result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n  term                  `Procedural lapse` Fraudulent  \n  <chr>                 <chr>              <chr>       \n1 exporter_typeMerchant 1.61 (0.001)       3.78 (0)    \n2 new_registrantTRUE    4.22 (0)           0.71 (0.146)\n3 log(amount_lakh)      0.65 (0)           1.42 (0)    \n4 nonfiler_pct          1.01 (0.376)       1.09 (0)    \n```\n\n\n:::\n:::\n\n\n\n\nEach cell shows the odds ratio, with its p-value in brackets. Reading across a row tells a clear story.\n\n- **New registrants** have 4.2 times the odds of a procedural lapse, but their odds of fraud (0.71) are not clearly different from others'. Newcomers make mistakes; they are not, on this evidence, more dishonest.\n- **Merchant exporters** have 3.8 times the odds of fraud, and a smaller rise, 1.6 times, in the odds of a lapse. (We did not plant this second effect. Even in simulated data, chance produces patterns, which is one more reason to confirm a model's findings on fresh data.)\n- **Credit from non-filers** raises the odds of fraud by a factor of 1.094 for each percentage point, and has little to do with lapses.\n- **Larger claims** are more likely to be fraudulent, and *less* likely to have lapses, perhaps because large claimants employ professionals to file their claims.\n\nA two-way logistic regression on \"irregular\" would have mixed these opposite patterns together, and blurred both.\n\n**Predictions.** `predict()` with `type = \"probs\"` gives the probability of each outcome for each claim, and the three add up to 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmulti_probs <- predict(multi_model, newdata = outcomes, type = \"probs\")\nhead(round(multi_probs, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Clean Procedural lapse Fraudulent\n1 0.849            0.123      0.028\n2 0.803            0.135      0.062\n3 0.876            0.091      0.033\n4 0.766            0.199      0.035\n5 0.875            0.087      0.038\n6 0.668            0.325      0.007\n```\n\n\n:::\n:::\n\n\nThese support two separate selections from the same list of claims: the highest probabilities of *fraud* for the investigation wing, and the highest probabilities of a *procedural lapse* for a compliance drive by letter. Each can be judged with the AUC and gains table, exactly as before, using its own column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(fraud_auc = round(auc(multi_probs[, \"Fraudulent\"], outcomes$outcome == \"Fraudulent\"), 3),\n  lapse_auc = round(auc(multi_probs[, \"Procedural lapse\"], outcomes$outcome == \"Procedural lapse\"), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfraud_auc lapse_auc \n    0.813     0.722 \n```\n\n\n:::\n:::\n\n\n(These are measured on the same claims the model learnt from, to keep the example short. In practice, use a training and test split, as earlier in the chapter.)\n\n::: callout-note\nIf the categories have a natural *order*, such as *nil*, *minor* and *major* irregularity, an *ordinal* logistic regression uses that order and needs fewer coefficients. It is fitted with `polr()` from the package `MASS`. When the categories are simply different kinds, as here, multinomial regression is the right choice.\n:::\n\n## A suggested workflow\n\n1. **Define the outcome** clearly, such as \"irregularity of more than ₹1 lakh found on examination\", and collect past cases with known outcomes.\n2. **List candidate features** from audit knowledge, and look at the outcome rate by each feature, banding numeric ones with `cut()`.\n3. **Split** the data into training and test sets.\n4. **Fit** with `glm(..., family = binomial)`, and read the odds ratios with `tidy(exponentiate = TRUE, conf.int = TRUE)`.\n5. **Evaluate on the test set** with the AUC and a gains table. Do not rely on accuracy.\n6. **Improve the features**, comparing models only on the test set.\n7. **Refit on all the data, and score the new cases.**\n8. **Select** mostly by risk score, with a random part, within the capacity available.\n9. **Record** the model, its features and its test results in the working papers, and refit when new outcomes arrive.\n\n::: callout-important\n## Remember\n\n- Logistic regression predicts the probability of a yes/no outcome, and its scores rank cases by risk.\n- `exp()` of a coefficient is an odds ratio, the factor by which the odds change for one unit of the feature.\n- Judge a model on data it has not seen. Use the AUC and a gains table, not accuracy, when \"yes\" is rare.\n- Good features come from audit knowledge and from looking at the data.\n- Select mostly by risk, partly at random, and treat a score as a lead, never as evidence.\n- For three or more kinds of outcome, multinomial regression fits one comparison per outcome against a baseline, and shows how the drivers differ.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `glm(family = binomial)` | stats | Fit a logistic regression |\n| `multinom()` | nnet | Fit a multinomial logistic regression, for three or more outcomes |\n| `predict(type = \"probs\")` | stats | Probability of each outcome, from a multinomial model |\n| `summary()` | base R | Coefficients, standard errors and p-values of a model |\n| `tidy(exponentiate = TRUE, conf.int = TRUE)` | broom | Odds ratios with confidence intervals, as a table |\n| `predict(type = \"response\")` | stats | Predicted probabilities (risk scores) for new data |\n| `plogis()` | stats | The logistic curve, turning log-odds into probabilities |\n| `sample()` | base R | Split data into training and test sets |\n| `table()` | base R | Confusion matrix of predicted and actual outcomes |\n| `rank()`, `cumsum()` | base R | Calculate the AUC and the ROC curve |\n| `ntile()`, `min_rank()` | dplyr | Divide into deciles, and rank by score |\n| `slice_max()`, `slice_sample()`, `anti_join()` | dplyr | Select the top-risk cases and a random part from the rest |\n\n: Functions used in this chapter {#tbl-logisticfunctions}\n",
    "supporting": [
      "12-4b-logistic_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}