{
  "hash": "fa7f016a06d9a5601ce0262242721f47",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Importing and Exporting Data {#sec-read}\n\nAudit data comes from outside. A district treasury sends a file of every voucher it passed in a month. A works division sends its register as an Excel workbook, with a sheet for each sub-division. A scheme's portal gives a download of its beneficiaries. Before we can check anything, this data has to come into R, whole and correct.\n\nThis step is not as simple as it looks. A file read carelessly can lose payments without any error. An amount written as \"1,25,000\" can quietly become a missing value, and drop out of every total. A DDO code like `0204015` can lose its leading zero and stop matching the master. So reading a file is itself an audit step. The auditor must be able to show that the data analysed is the data received, row for row and rupee for rupee.\n\nAfter the analysis, the results travel the other way. Exception lists, summaries and charts are exported, for the working papers, for the audit report, and for the auditee's reply. In this chapter we learn both directions. We first see the base R functions for reading and writing files, and then the `tidyverse` packages which do these jobs faster and more safely. We end with the most important point for an auditor, checking that nothing went wrong while reading, and reconciling a treasury file with its covering letter.\n\n**Prerequisites**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(writexl)\n```\n:::\n\n\n## Our data, files received from a treasury\n\nTo practise, we need some files. So let us create them, in a temporary folder given by `tempdir()`, so that nothing is left behind in our project. There are four files.\n\n- `amarpur_vouchers_apr2024.csv`, the vouchers passed by the District Treasury, Amarpur, in April 2024. Each row has the voucher number, the code of the drawing and disbursing officer (DDO), the date of the bill, the head of account, the payee, the mode of payment and the amount in rupees.\n- `cancelled_cheques.txt`, the numbers of cheques reported as cancelled, one on each line.\n- `covering_letter.txt`, the letter sent by the treasury with the file.\n- `works_register.xlsx`, an Excel workbook from a works division, with one sheet for each of two sub-divisions.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the files used in this chapter\"}\nfolder <- file.path(tempdir(), \"audit_files\")\ndir.create(folder, showWarnings = FALSE)\n\nset.seed(2024)\nn <- 120\nddo_codes <- c(\"0204015\", \"0204022\", \"0204031\", \"0204047\", \"0204058\")\nheads <- c(\"2054-00-095-01\", \"2202-01-101-02\", \"2210-03-103-01\", \"4059-01-051-03\")\npayees <- c(\"Sharma Traders\", \"Kaveri Infra\", \"Om Sai Suppliers\", \"Laxmi Electricals\",\n            \"Patel Hardware\", \"Salaries, establishment\", \"Gupta Enterprises\")\n\namarpur <- tibble(\n  voucher_no = sprintf(\"TV/AMR/%04d\", 1:n),\n  ddo_code   = sample(ddo_codes, n, replace = TRUE),\n  bill_date  = format(sort(as.Date(\"2024-04-01\") + sample(0:29, n, replace = TRUE)),\n                      \"%d/%m/%Y\"),\n  head       = sample(heads, n, replace = TRUE),\n  payee      = sample(payees, n, replace = TRUE),\n  mode       = sample(c(\"e-payment\", \"Cheque\"), n, replace = TRUE, prob = c(0.85, 0.15)),\n  amount     = round(rlnorm(n, log(80000), 1), -1)\n)\n# Planted. Three large payments of works contracts\namarpur$amount[c(17, 58, 93)] <- c(1245000, 1870500, 2310000)\namarpur$payee[c(17, 58, 93)] <- \"Kaveri Infra\"\namarpur_file <- file.path(folder, \"amarpur_vouchers_apr2024.csv\")\nwrite.csv(amarpur, amarpur_file, row.names = FALSE)\n\ncheque_file <- file.path(folder, \"cancelled_cheques.txt\")\nwriteLines(c(\"504117\", \"504123\", \"504188\", \"504190\", \"504201\", \"504236\"), cheque_file)\n\nletter_file <- file.path(folder, \"covering_letter.txt\")\nwriteLines(c(\"Office of the Treasury Officer, District Treasury, Amarpur\",\n             \"To the Senior Audit Officer\",\n             \"Data of vouchers passed in April 2024\",\n             \"Number of vouchers passed, 120\",\n             \"Total amount in rupees, see the enclosed file\"),\n           letter_file)\n\nxl_file <- file.path(folder, \"works_register.xlsx\")\nwrite_xlsx(list(\n  \"Amarpur North\" = tibble(work_id = c(\"W-101\", \"W-102\", \"W-103\"),\n                           work = c(\"Road repair, Km 4 to 9\", \"School boundary wall\",\n                                    \"Culvert at Sonpur\"),\n                           estimate_lakh = c(42.5, 18.0, 9.6)),\n  \"Amarpur South\" = tibble(work_id = c(\"W-201\", \"W-202\"),\n                           work = c(\"Panchayat bhawan\", \"Drain, ward 7\"),\n                           estimate_lakh = c(25.0, 12.4))),\n  xl_file)\n```\n:::\n\n\n`file.path()` joins the parts of a path with `/`, the separator which works on every computer. The four paths are now saved in `amarpur_file`, `cheque_file`, `letter_file` and `xl_file`, and we use these names below. With your own data, you would instead give the path of the file on your computer, like `\"Data/vouchers.csv\"`.\n\n## Importing data with base R\n\nBase R has functions to import nearly any kind of external data. There are also packages which make certain tasks easier, and we will learn some of them later in this chapter. Let us first see the base R functions which are used most often.\n\n### Reading tables with `read.table()` and `read.csv()` {-}\n\nThese two are the most common functions for reading tabular data from plain text files. `read.table()` reads data whose columns are separated by spaces or another separator. `read.csv()` reads *comma separated values* (.csv) files. They have three more cousins.\n\n- `read.csv2()` reads csv files where `;` is the separator and `,` the decimal mark, as used in many European countries.\n- `read.delim()` reads files where a `tab` character separates the columns and `.` is the decimal mark.\n- `read.delim2()` reads tab separated files where `,` is the decimal mark.\n\nThe most important arguments of these functions are these.\n\n- `file`, the name of the file, with its path, as a string^[If backslashes `\\` are used in file paths, they must be escaped, since R treats `\\` as an escape character. So `\"my/location/here/file.txt\"` and `\"my\\\\location\\\\here\\\\file.txt\"` are both correct ways of giving a file name.].\n- `header`, a logical value, telling whether the first line of the file holds the column names.\n- `sep`, the character which separates the columns.\n- `colClasses`, a character vector giving the type of each column, if the columns must be read in these types only.\n- `skip`, the number of lines to skip at the beginning of the file.\n\nReaders may see `?read.table()` for the complete list of arguments. Let us read the voucher file of the Amarpur treasury.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvouchers <- read.csv(amarpur_file)\n# Check dimensions\ndim(vouchers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120   7\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check column names\ncolnames(vouchers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"voucher_no\" \"ddo_code\"   \"bill_date\"  \"head\"       \"payee\"     \n[6] \"mode\"       \"amount\"    \n```\n\n\n:::\n\n```{.r .cell-code}\nhead(vouchers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   voucher_no ddo_code  bill_date           head             payee      mode\n1 TV/AMR/0001   204022 01/04/2024 2202-01-101-02    Patel Hardware e-payment\n2 TV/AMR/0002   204058 01/04/2024 2210-03-103-01    Patel Hardware e-payment\n3 TV/AMR/0003   204058 01/04/2024 2210-03-103-01  Om Sai Suppliers e-payment\n4 TV/AMR/0004   204047 01/04/2024 2054-00-095-01 Laxmi Electricals e-payment\n5 TV/AMR/0005   204015 01/04/2024 2202-01-101-02 Laxmi Electricals e-payment\n6 TV/AMR/0006   204058 01/04/2024 4059-01-051-03      Kaveri Infra e-payment\n  amount\n1  10040\n2  80700\n3 124580\n4  41620\n5  16300\n6 110990\n```\n\n\n:::\n:::\n\n\nThe data has 120 rows and 7 columns. But look at `ddo_code`. The first code in the file is `0204022`, but R shows 204022. `read.csv()` has seen digits, and read the column as numbers, so the leading zero is gone. These codes will no longer match the DDO master. The argument `colClasses` tells R the type of the columns we name.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvouchers <- read.csv(amarpur_file, colClasses = c(ddo_code = \"character\"))\nhead(vouchers$ddo_code)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0204022\" \"0204058\" \"0204058\" \"0204047\" \"0204015\" \"0204058\"\n```\n\n\n:::\n:::\n\n\nA file can also be read directly from a web address, without downloading it first, by giving the address in place of the file name.\n\n::: callout-note\nUse `\"clipboard\"` as the file name to paste copied data into R. For example, copy a few rows and columns from an Excel sheet, and run `read.delim(\"clipboard\", header = FALSE)`. This works on Windows.\n:::\n\n### Reading data into a vector with `scan()` and `readline()` {-}\n\n`read.table()` and its cousins read data into tables. Sometimes we need to read data into a simple vector instead. The two functions `scan()` and `readline()` are used for this.\n\nThe basic syntax of `scan()` is as follows.\n\n```\nscan(file = \"\",\n     what = double(),\n     nmax = -1,\n     ...\n)\n```\n\nThe arguments mean this.\n\n- `file` is the name of the file, or a link.\n- `what` is the type of data to be read. The default is double.\n- `nmax` is the maximum number of values to be read. The default, `-1`, means all.\n\nThere are many other useful arguments, which can be seen with `?scan`. Let us read the numbers of the cancelled cheques.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncancelled <- scan(cheque_file)\ncancelled\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 504117 504123 504188 504190 504201 504236\n```\n\n\n:::\n:::\n\n\nIn the console, `scan()` also says how many items it read. The result is a plain vector, ready to be checked against the cheque issue register with `%in%` (@sec-subset).\n\n`scan()` can also read data typed on the keyboard into a vector. Just give a blank string `\"\"` as the file name. See this example.\n\n![](images/scan.png)\n\nThe function `readline()` does a similar job, but shows a prompt. See this example.\n\n![](images/readline.png)\n\n### Reading text files with `readLines()` {-}\n\nThe function `readLines()` reads the lines of a text file (or connection), giving one element for each line. Let us read the covering letter of the treasury.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nletter <- readLines(letter_file)\nletter\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Office of the Treasury Officer, District Treasury, Amarpur\"\n[2] \"To the Senior Audit Officer\"                               \n[3] \"Data of vouchers passed in April 2024\"                     \n[4] \"Number of vouchers passed, 120\"                            \n[5] \"Total amount in rupees, see the enclosed file\"             \n```\n\n\n:::\n:::\n\n\nEach line is now one element of a character vector, which we can search and subset like any other. We use `readLines()` again to read the Budget speech in @sec-textviz.\n\n## Exporting data with base R\n\nIn most analysis, we read external data, and then clean, transform and analyse it, all in R. So we export less often than we import. Still, cleaned data, summaries and exception lists often need to be exported. The following functions meet nearly all such needs.\n\n### Writing tables with `write.table()` and `write.csv()` {-}\n\nData frames can be exported with these functions. The latter writes csv files specifically. The syntax is as follows.\n\n```\nwrite.table(x, file = \"\", sep = \" \", ...)\nwrite.csv(x, file = \"\", ...)\nwrite.csv2(x, file = \"\", ...)\n```\n\nThe arguments mean this.\n\n- `x` is the data frame to be exported.\n- `file` is the file name, with its path.\n- `sep` is the separator.\n- `...` are many more arguments for customised exports. See `?write.table()` for full details.\n\nFor example, let us export the vouchers of ₹10 lakh or more as a csv file, for the working papers. We pick them out exactly as in @sec-subset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbig_vouchers <- vouchers[which(vouchers$amount >= 1e6), c(\"voucher_no\", \"payee\", \"amount\")]\nwrite.csv(big_vouchers, file.path(folder, \"big_vouchers.csv\"), row.names = FALSE)\nbig_vouchers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    voucher_no        payee  amount\n17 TV/AMR/0017 Kaveri Infra 1245000\n58 TV/AMR/0058 Kaveri Infra 1870500\n93 TV/AMR/0093 Kaveri Infra 2310000\n```\n\n\n:::\n:::\n\n\nThere are 3 such vouchers, for a total of ₹54.26 lakh. By default, `write.csv()` also writes the row numbers as a first, unnamed column. `row.names = FALSE` stops this, which is nearly always what we want.\n\n### Writing text line by line with `writeLines()` {-}\n\nLike `readLines()`, the function `writeLines()` writes text into a file of the given name, one element on each line. It is handy for a short note to go with an exported file.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwriteLines(c(\"Vouchers of Rs 10 lakh or more, District Treasury Amarpur, April 2024\",\n             paste(\"Number of vouchers,\", nrow(big_vouchers))),\n           file.path(folder, \"big_vouchers_note.txt\"))\nreadLines(file.path(folder, \"big_vouchers_note.txt\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Vouchers of Rs 10 lakh or more, District Treasury Amarpur, April 2024\"\n[2] \"Number of vouchers, 3\"                                                \n```\n\n\n:::\n:::\n\n\n### Getting the code for an object with `dput()` {-}\n\nThis function prints the code which would recreate a given R object. It is particularly useful when asking for help online. For example, on [_Stack Overflow_](https://stackoverflow.com/), a question should include [reproducible data](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example). Please also refer to @sec-reprex. Let us make up three rows of voucher data and see.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_data <- data.frame(voucher_no = c(\"TV-0001\", \"TV-0002\", \"TV-0003\"),\n                      amount = c(18500, 125000, 9800))\ndput(my_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstructure(list(voucher_no = c(\"TV-0001\", \"TV-0002\", \"TV-0003\"\n), amount = c(18500, 125000, 9800)), class = \"data.frame\", row.names = c(NA, \n-3L))\n```\n\n\n:::\n:::\n\n\nAnd to recreate someone else's data from their `dput()` output, we simply run it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnow_mydata <- structure(list(voucher_no = c(\"TV-0001\", \"TV-0002\", \"TV-0003\"\n), amount = c(18500, 125000, 9800)), class = \"data.frame\", row.names = c(NA,\n-3L))\n\nnow_mydata\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  voucher_no amount\n1    TV-0001  18500\n2    TV-0002 125000\n3    TV-0003   9800\n```\n\n\n:::\n:::\n\n\n::: callout-warning\n## Caution\n\nNever share real audit data this way. Make up a few rows of similar data instead, as we did here. Audit data often holds names, account numbers and other personal details, which must not be posted on a public forum.\n:::\n\n## Reading and writing with packages\n\n### Package `readr`\n\nThe `readr` package [@R-readr] is part of the core `tidyverse`, and is loaded with `library(tidyverse)`. It has a counterpart for each of the reading and writing functions of base R.\n\n| Base R     | readr        | Uses                                    |\n| :---------:| :----------: | :-------------------------------------- |\n| read.table | read\\_table  | Reading tables separated by white space |\n| read.csv   | read\\_csv    | Reading CSV file with comma as sep      |\n| read.csv2  | read\\_csv2   | Reading CSV file with semi-colon as sep |\n| read.delim | read\\_tsv    | Reading tab delimited file              |\n| \\--        | read\\_delim  | Reading files with any delimiter        |\n| read.fwf   | read\\_fwf    | Reading fixed width files               |\n| \\--        | write\\_delim | Writing files with any delimiter        |\n| write.csv  | write\\_csv   | Writing files with comma delimiter      |\n| write.csv2 | write\\_csv2  | Writing files with semi-colon delimiter |\n| \\--        | write\\_tsv   | Writing a tab delimited file            |\n\n: Base R and readr functions {#tbl-readr}\n\nWhat is the difference between the two sets? Firstly, the `readr` functions are much faster, which matters for large files. Secondly, they report the problems they meet while reading, as we will see shortly. And thirdly, they never turn text into factors, or change column names, behind our back. Let us read the same voucher file with `read_csv()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_csv(amarpur_file)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 120 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (6): voucher_no, ddo_code, bill_date, head, payee, mode\ndbl (1): amount\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 120 × 7\n   voucher_no  ddo_code bill_date  head           payee             mode  amount\n   <chr>       <chr>    <chr>      <chr>          <chr>             <chr>  <dbl>\n 1 TV/AMR/0001 0204022  01/04/2024 2202-01-101-02 Patel Hardware    e-pa…  10040\n 2 TV/AMR/0002 0204058  01/04/2024 2210-03-103-01 Patel Hardware    e-pa…  80700\n 3 TV/AMR/0003 0204058  01/04/2024 2210-03-103-01 Om Sai Suppliers  e-pa… 124580\n 4 TV/AMR/0004 0204047  01/04/2024 2054-00-095-01 Laxmi Electricals e-pa…  41620\n 5 TV/AMR/0005 0204015  01/04/2024 2202-01-101-02 Laxmi Electricals e-pa…  16300\n 6 TV/AMR/0006 0204058  01/04/2024 4059-01-051-03 Kaveri Infra      e-pa… 110990\n 7 TV/AMR/0007 0204015  01/04/2024 2202-01-101-02 Salaries, establ… e-pa…  82870\n 8 TV/AMR/0008 0204022  01/04/2024 4059-01-051-03 Laxmi Electricals e-pa… 165110\n 9 TV/AMR/0009 0204022  02/04/2024 2054-00-095-01 Salaries, establ… e-pa… 363250\n10 TV/AMR/0010 0204058  02/04/2024 2210-03-103-01 Om Sai Suppliers  e-pa…  25320\n# ℹ 110 more rows\n```\n\n\n:::\n:::\n\n\nNotice that the type of each column has been printed. `readr` *guesses* the types from the first 1,000 rows. Here it has kept `ddo_code` as text (`chr`), because the values begin with a zero. But it has also read `bill_date` as text, since it does not recognise dates written day first. If the guesses are not what we want, we use the argument `col_types`. We can see the guessed types with `spec()`, and modify them for use in `col_types`. See this example.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspec(read_csv(amarpur_file))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 120 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (6): voucher_no, ddo_code, bill_date, head, payee, mode\ndbl (1): amount\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncols(\n  voucher_no = col_character(),\n  ddo_code = col_character(),\n  bill_date = col_character(),\n  head = col_character(),\n  payee = col_character(),\n  mode = col_character(),\n  amount = col_double()\n)\n```\n\n\n:::\n\n```{.r .cell-code}\nvouchers <- read_csv(amarpur_file,\n                     col_types = cols(\n                       voucher_no = col_character(),\n                       ddo_code   = col_character(),\n                       bill_date  = col_date(format = \"%d/%m/%Y\"),\n                       head       = col_character(),\n                       payee      = col_character(),\n                       mode       = col_factor(levels = c(\"e-payment\", \"Cheque\")),\n                       amount     = col_double()\n                     ))\nvouchers |> head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  voucher_no  ddo_code bill_date  head           payee            mode    amount\n  <chr>       <chr>    <date>     <chr>          <chr>            <fct>    <dbl>\n1 TV/AMR/0001 0204022  2024-04-01 2202-01-101-02 Patel Hardware   e-paym…  10040\n2 TV/AMR/0002 0204058  2024-04-01 2210-03-103-01 Patel Hardware   e-paym…  80700\n3 TV/AMR/0003 0204058  2024-04-01 2210-03-103-01 Om Sai Suppliers e-paym… 124580\n```\n\n\n:::\n:::\n\n\nNow `bill_date` is a true date, and `mode` a factor with the two modes of payment. The format `\"%d/%m/%Y\"` says that the day comes first, then the month, then the year in four digits, separated by `/`. We will learn more about such formats in @sec-lubridate.\n\nTwo other arguments are often useful. `col_select` reads only the columns we need, which saves time and memory with wide files.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_csv(amarpur_file, col_select = c(voucher_no, amount), show_col_types = FALSE) |>\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  voucher_no  amount\n  <chr>        <dbl>\n1 TV/AMR/0001  10040\n2 TV/AMR/0002  80700\n3 TV/AMR/0003 124580\n```\n\n\n:::\n:::\n\n\n`locale` handles files with other encodings or number formats. For example, files with Hindi or other Indian scripts, saved from older software, may need `locale = locale(encoding = \"UTF-16LE\")` or another encoding, to be read correctly.\n\n### Package `readxl`\n\nThis package is also part of `tidyverse`, but has to be loaded separately with `library(readxl)`. It *reads* Excel files. An Excel file (with extension .xls or .xlsx) can hold several *sheets*. The functions `read_excel()`, `read_xlsx()` and `read_xls()` read a sheet. The syntax is as follows.\n\n```\nread_excel(path, sheet = NULL, range = NULL, skip = 0, col_types = NULL)\n```\n\nThe arguments mean this.\n\n- `sheet` is the name or number of the sheet. The default is the first sheet.\n- `range` reads only a block of cells, like `\"B3:H120\"`.\n- `skip` skips rows at the top, like a title.\n- `col_types = \"text\"` reads every column as text, which is the safest way to begin with a messy file.\n\nTo get the names of all the sheets in an Excel file, we use `excel_sheets()`. Let us look at the works register.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexcel_sheets(xl_file)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Amarpur North\" \"Amarpur South\"\n```\n\n\n:::\n\n```{.r .cell-code}\nread_excel(xl_file, sheet = \"Amarpur South\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  work_id work             estimate_lakh\n  <chr>   <chr>                    <dbl>\n1 W-201   Panchayat bhawan          25  \n2 W-202   Drain, ward 7             12.4\n```\n\n\n:::\n\n```{.r .cell-code}\nread_excel(xl_file, sheet = 1, range = \"A1:B3\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  work_id work                  \n  <chr>   <chr>                 \n1 W-101   Road repair, Km 4 to 9\n2 W-102   School boundary wall  \n```\n\n\n:::\n:::\n\n\nThe first call read the whole of the second sheet, by its name. The second read only the cells `A1:B3` of the first sheet, that is the headings and two rows of the first two columns. We read all the sheets of a file together in @sec-merge.\n\n### Writing Excel files\n\n`readxl` cannot write Excel files. For that, the package `writexl` has a simple function, `write_xlsx()`. A named list of data frames is written as one sheet each, which is a convenient way to give the auditee all the exception lists in one file.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexceptions_file <- file.path(folder, \"exceptions.xlsx\")\nwrite_xlsx(list(big_vouchers   = vouchers |> filter(amount >= 1e6),\n                cheque_payments = vouchers |> filter(mode == \"Cheque\")),\n           exceptions_file)\nexcel_sheets(exceptions_file)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"big_vouchers\"    \"cheque_payments\"\n```\n\n\n:::\n:::\n\n\n`filter()` keeps the rows meeting a condition. We will learn it properly in @sec-DPLYRR. For formatted Excel output, with colours, column widths and formulas, the package `openxlsx2` can be used.\n\n## Checking that the data was read correctly {#sec-read-check}\n\nThis is the most important step for an auditor, and the one most often skipped. When `readr` cannot read a value as the type expected, it puts `NA` in its place and moves on. Only a short message is printed. Let us see this with a small file of payments, written in the way real files often are.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncsv_text <- \"voucher_no,emp_code,amount,date\nPV-01,00123,1250,15/04/2024\nPV-02,00456,\\\"1,25,000\\\",16/04/2024\nPV-03,01789,-,2024-04-17\nPV-04,12001,3400.50,NA\"\n\npayments <- read_csv(I(csv_text), col_types = cols(amount = col_double()))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: One or more parsing issues, call `problems()` on your data frame for details,\ne.g.:\n  dat <- vroom(...)\n  problems(dat)\n```\n\n\n:::\n\n```{.r .cell-code}\npayments\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  voucher_no emp_code amount date      \n  <chr>      <chr>     <dbl> <chr>     \n1 PV-01      00123     1250  15/04/2024\n2 PV-02      00456       NA  16/04/2024\n3 PV-03      01789       NA  2024-04-17\n4 PV-04      12001     3400. <NA>      \n```\n\n\n:::\n:::\n\n\nHere, `I()` tells `read_csv()` that the text itself is the data, not a file name. Look at the `amount` column. The amount of ₹1,25,000, written with Indian commas, has become `NA`, and so has the `-`. Both payments have silently disappeared from any total we calculate. `problems()` lists every value that could not be read.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproblems(payments)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n    row   col expected actual   file                                            \n  <int> <int> <chr>    <chr>    <chr>                                           \n1     3     3 a double 1,25,000 C:/Users/User/AppData/Local/Temp/Rtmps5eiAR/vro…\n2     4     3 a double -        C:/Users/User/AppData/Local/Temp/Rtmps5eiAR/vro…\n```\n\n\n:::\n:::\n\n\nThe safest approach is to read such columns as text first, and convert them ourselves, with a function that understands the format. `parse_number()` removes the commas and any other non-numeric characters around the number. The argument `na` lists the values to be treated as missing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npayments <- read_csv(I(csv_text), col_types = cols(.default = col_character()))\n\npayments |>\n  mutate(amount_num = parse_number(amount, na = c(\"-\", \"NA\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  voucher_no emp_code amount   date       amount_num\n  <chr>      <chr>    <chr>    <chr>           <dbl>\n1 PV-01      00123    1250     15/04/2024      1250 \n2 PV-02      00456    1,25,000 16/04/2024    125000 \n3 PV-03      01789    -        2024-04-17        NA \n4 PV-04      12001    3400.50  <NA>            3400.\n```\n\n\n:::\n:::\n\n\nNow ₹1,25,000 has been read correctly. Notice also that `emp_code` keeps its leading zeros, because we read it as text. Read as a number, `00123` would have become `123`, and joins with other tables would fail, as we saw in @sec-strng-zeros.\n\n::: callout-tip\n## Audit tip\n\nAfter reading any file, always check three things before analysis. (1) The number of rows matches the number in the source, or the count given by the auditee. (2) The totals of amount columns match the totals in the source. (3) `problems()` is empty, or every problem is understood. Read code columns, like employee numbers, PIN codes and account numbers, as text.\n:::\n\n## Asking for help with `reprex` {#sec-reprex}\n\nThe package `reprex` is part of tidyverse too, but has to be loaded with `library(reprex)`. Its name is short for *reproducible example*. It is useful when we are stuck with a problem and seek help on a forum, such as [Stack Overflow](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) or [Posit Community](https://forum.posit.co).\n\nAs an example, do this in your console. It uses `iris`, a small data set that comes with R, since a helper on a forum will have it too.\n\n```\nlibrary(reprex)\n\nx <- dput(head(iris))\nx\n```\n\nThereafter, copy the code and run `reprex()`. A small window opens in the `Viewer` tab, like this, showing the code with its output. The formatted result is also copied to the clipboard, ready to paste into a question.\n\n![](images/reprex.png)\n\nFor more reading please refer to [this page.](https://www.tidyverse.org/help/)^[https://www.tidyverse.org/help/]\n\n## Audit use case, reconciling a treasury file with its covering letter {#sec-read-audit}\n\nThe District Treasury, Belapur, has sent its vouchers for April 2024 as a csv file. Its covering letter states the number of vouchers and their total amount. Before any analysis, we must show that the file we analyse agrees with the letter. The code below creates the file and the letter. Like many real extracts, the file writes some amounts with Indian commas and some as `-`, and it may not be complete.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the Belapur file and covering letter\"}\nset.seed(77)\nm <- 85\nbelapur <- tibble(\n  voucher_no = sprintf(\"TV/BLP/%04d\", 1:m),\n  ddo_code   = sample(c(\"0311004\", \"0311012\", \"0311019\", \"0311026\"), m, replace = TRUE),\n  bill_date  = format(sort(as.Date(\"2024-04-01\") + sample(0:29, m, replace = TRUE)),\n                      \"%d/%m/%Y\"),\n  payee      = sample(payees, m, replace = TRUE),\n  amount     = round(rlnorm(m, log(90000), 0.9), -1)\n)\nletter_total <- sum(belapur$amount)\n\n# Write a whole number with Indian commas, like 1,25,000\nindian <- function(x) {\n  s <- format(x, scientific = FALSE, trim = TRUE)\n  ifelse(nchar(s) <= 3, s,\n         paste0(gsub(\"(\\\\d)(?=(\\\\d{2})+$)\", \"\\\\1,\", substr(s, 1, nchar(s) - 3), perl = TRUE),\n                \",\", substr(s, nchar(s) - 2, nchar(s))))\n}\n\nbelapur_out <- belapur |>\n  mutate(amount = format(amount, scientific = FALSE, trim = TRUE))\n# Planted. Amounts of a lakh or more written with Indian commas\nbig <- which(belapur$amount >= 1e5)\nbelapur_out$amount[big] <- indian(belapur$amount[big])\n# Planted. Two amounts left as \"-\" in the extract\nbelapur_out$amount[c(23, 61)] <- \"-\"\n# Planted. One voucher missing from the extract\nbelapur_out <- belapur_out[-47, ]\n\nbelapur_file <- file.path(folder, \"belapur_vouchers_apr2024.csv\")\nwrite_csv(belapur_out, belapur_file)\n\nbelapur_letter <- file.path(folder, \"belapur_letter.txt\")\nwriteLines(c(\"Office of the Treasury Officer, District Treasury, Belapur\",\n             \"Data of vouchers passed in April 2024\",\n             paste0(\"Number of vouchers passed, \", m),\n             paste0(\"Total amount in rupees, \", indian(letter_total))),\n           belapur_letter)\n```\n:::\n\n\n**Step 1, take the control totals from the letter.** The letter is a text file, so we read it with `readLines()`. `parse_number()` takes out the number from each line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nletter <- readLines(belapur_letter)\nletter\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Office of the Treasury Officer, District Treasury, Belapur\"\n[2] \"Data of vouchers passed in April 2024\"                     \n[3] \"Number of vouchers passed, 85\"                             \n[4] \"Total amount in rupees, 1,06,73,100\"                       \n```\n\n\n:::\n\n```{.r .cell-code}\ncontrol <- parse_number(letter[3:4])\ncontrol\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]       85 10673100\n```\n\n\n:::\n:::\n\n\nThe treasury says it passed 85 vouchers, for a total of ₹106.73 lakh.\n\n**Step 2, read the file the quick way, and see what goes wrong.** Suppose we tell `read_csv()` that the amount is a number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquick <- read_csv(belapur_file, col_types = cols(amount = col_double()))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: One or more parsing issues, call `problems()` on your data frame for details,\ne.g.:\n  dat <- vroom(...)\n  problems(dat)\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(quick)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 84\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(quick$amount, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2464290\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(problems(quick))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 39\n```\n\n\n:::\n:::\n\n\n\n\nThe total is only ₹24.64 lakh, against ₹106.73 lakh in the letter. 39 amounts could not be read, and have become `NA`. Had we not compared with the letter, we would have analysed a file short of ₹82.09 lakh, without knowing it.\n\n**Step 3, read everything as text, and convert the amounts ourselves.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreceived <- read_csv(belapur_file, col_types = cols(.default = col_character())) |>\n  mutate(amount_num = parse_number(amount, na = \"-\"))\n\nreceived |> filter(is.na(amount_num))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  voucher_no  ddo_code bill_date  payee             amount amount_num\n  <chr>       <chr>    <chr>      <chr>             <chr>       <dbl>\n1 TV/BLP/0023 0311004  10/04/2024 Gupta Enterprises -              NA\n2 TV/BLP/0061 0311019  20/04/2024 Patel Hardware    -              NA\n```\n\n\n:::\n:::\n\n\n\n\nOnly the two vouchers written as `-` are now without an amount. The commas have been read correctly.\n\n**Step 4, reconcile the rows and the total.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(item     = c(\"Vouchers\", \"Amount (Rs)\"),\n       letter   = control,\n       file     = c(nrow(received), read_total),\n       shortfall = letter - file)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  item          letter     file shortfall\n  <chr>          <dbl>    <dbl>     <dbl>\n1 Vouchers          85       84         1\n2 Amount (Rs) 10673100 10361810    311290\n```\n\n\n:::\n:::\n\n\nThe file has 84 vouchers, one fewer than the letter. Since voucher numbers run in a series, the missing one is easy to find, by the method of @sec-gaps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nserials <- parse_number(str_extract(received$voucher_no, \"\\\\d+$\"))\nmissing_voucher <- setdiff(1:max(serials), serials)\nmissing_voucher\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 47\n```\n\n\n:::\n:::\n\n\n\n\nVoucher TV/BLP/0047 is not in the file. The total is still short by ₹3,11,290. This is the amount of the missing voucher and of the two vouchers, TV/BLP/0023 and TV/BLP/0061, shown as `-`.\n\nWhat next? The auditor writes to the treasury, asking for voucher TV/BLP/0047 and for the amounts of the two vouchers shown as `-`. When the corrected file arrives, the same code is run again, and the reconciliation table goes into the working papers. Only then does the analysis begin. If the treasury cannot explain the gap, the incomplete extract is itself a point to report, about the reliability of the treasury's data.\n\n::: callout-warning\n## Caution\n\nA file that reconciles in count but not in total, or the other way round, is not ready for analysis. Never \"adjust\" the data in R to make it agree with the letter. Find the reason, record it, and get the corrected data from the source.\n:::\n\n## A suggested workflow\n\nFor any file received from the auditee, an auditor may follow these steps.\n\n1.  **Look at the file first.** Note its format, its sheets with `excel_sheets()`, and any title rows to skip.\n2.  **Note the control totals.** Take the number of records and the total amount from the covering letter, with `readLines()` and `parse_number()` if the letter is a text file.\n3.  **Read everything as text to begin with.** Use `col_types = cols(.default = col_character())` in `read_csv()`, or `col_types = \"text\"` in `read_excel()`. This keeps leading zeros in codes and stops values from turning into `NA` silently.\n4.  **Check for problems.** Run `problems()` and make sure every problem is understood.\n5.  **Convert amounts and dates yourself.** Use `parse_number()` with a suitable `na` argument, so that amounts written with Indian commas are read correctly. Give the date format with `col_date()`.\n6.  **Keep code columns as text.** DDO codes, employee numbers, PIN codes and account numbers should stay as text.\n7.  **Reconcile with the source.** Match the number of rows and the totals of amount columns with the covering letter. Look for missing serial numbers with `setdiff()`.\n8.  **Export the results.** Write exception lists with `write_csv()` or `write.csv()`, or with `write_xlsx()` to put each list on its own sheet in one file.\n\n::: callout-important\n## Remember\n\nA value that cannot be read becomes `NA` with only a short message. Such a payment silently drops out of every total. Always check `problems()`, the row count and the totals against the covering letter before starting the analysis.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `read.table()`, `read.csv()`, `read.delim()` | base R | Read text files with columns |\n| `scan()`, `readline()`, `readLines()` | base R | Read data into a vector, or lines of text |\n| `write.table()`, `write.csv()`, `writeLines()` | base R | Write data frames or text to files |\n| `dput()` | base R | Code which recreates an object |\n| `tempdir()`, `file.path()` | base R | A temporary folder, and a path joined from its parts |\n| `dim()`, `colnames()`, `head()` | base R | The size, the column names and the first rows of a table |\n| `setdiff()` | base R | Values in the first vector but not in the second, like missing serial numbers |\n| `read_csv()`, `read_tsv()`, `read_delim()` | readr | Read text files, faster and with problem reports |\n| `spec()`, `cols()`, `col_character()`, `col_date()`, `col_factor()` and others | readr | See and set the type of each column |\n| `problems()` | readr | Values which could not be read as the expected type |\n| `parse_number()` | readr | Numbers from text, ignoring commas and symbols |\n| `write_csv()` | readr | Write a data frame to a csv file |\n| `str_extract()` | stringr | Take out the part of a text matching a pattern |\n| `filter()`, `mutate()` | dplyr | Keep rows meeting a condition, and add columns |\n| `read_excel()`, `excel_sheets()` | readxl | Read Excel sheets, and list the sheets in a file |\n| `write_xlsx()` | writexl | Write one or more data frames to an Excel file |\n| `reprex()` | reprex | Prepare a reproducible example for asking help |\n\n: Functions used in this chapter {#tbl-readfunctions}\n",
    "supporting": [
      "07-1-reading_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}