<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="A practical guide to data analytics for auditors, using R and the tidyverse: reading and cleaning audit data, forensic tests, sampling, statistics, machine learning, text, network and geospatial analytics, and reproducible reports, with Indian audit examples throughout.">
<title>28&nbsp; Statistical Tests for Auditors – R for Audit Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./part5-forensic.html" rel="next">
<link href="./12-3Samp.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-631496449bf32ff9b0bb69a6bfd9195d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-a64f2b92d8b4b45ab5f5d9261e8b8c9d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-631496449bf32ff9b0bb69a6bfd9195d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link rel="stylesheet" href="style.css">
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./part4-explore-sample.html">Part IV: Exploring and Sampling</a></li><li class="breadcrumb-item"><a href="./12-3b-tests.html"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Statistical Tests for Auditors</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R for Audit Analytics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/anilyayavar/new-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index-about-author.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About the Author</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how-to-use.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to Use This Book</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-Zero.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gearing Up</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part1-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part I: R Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Objects, Data Types and Data Structures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Subsets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Subsetting and Indexing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Functions and Operators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-functions-existing-and-useful-functions-in-base-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Useful Base R Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-functions-pipes-in-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Pipes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-1conditionals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Conditions and Loops</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-1-functionalprog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Functional Programming</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part2-data-ready.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part II: Getting Data Ready</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-2-workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Working with Files and Folders</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-1-reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Importing and Exporting Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-1-reading-data-cleaning-in-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Cleaning Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-1b-pdf-excel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data from PDFs and Messy Excel Files</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-2-merge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Combining Many Similar Files</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-1-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Transforming Data with dplyr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-2-joins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Joining Tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-tidyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Reshaping Data with tidyr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-8Lubridate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Dates and Times</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-8b-duckdb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Large Data with DuckDB and data.table</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part3-text-fields.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part III: Working with Text Fields</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-1Stringr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Working with Strings in stringr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-2Regex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Regular Expressions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-2Regex-regex-in-human-readble-format-using-rebu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Readable Regular Expressions with rebus</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part4-explore-sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part IV: Exploring and Sampling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Charts in Base R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-1ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Charts with ggplot2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-2ggplot2-polish.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Polishing Charts for Audit Reports</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-3Factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Factors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-1Desc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-2stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-3Samp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Random Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-3b-tests.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Statistical Tests for Auditors</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part5-forensic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part V: Forensic Tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17a-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Rule-Based Validation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-Anamolous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Benford Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-nigrini-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Nigrini’s Tests for Unusual Amounts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-duplicates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Duplicate Detection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-stringdist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">String Similarity and Fuzzy Matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20b-record-linkage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Record Linkage</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-gaps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Gaps in Sequences</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21b-process-mining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Process Mining</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part6-risk-scoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part VI: Modelling and Risk Scoring</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-4Reg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-4Reg-multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Multiple Regression in Audit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-4b-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Logistic Regression for Risk Scoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-4c-trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Decision Trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-4d-forest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Random Forests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-DEA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Data Envelopment Analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part7-hidden-patterns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part VII: Finding Hidden Patterns</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-5PCA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Principal Component Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-6KMeans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Clustering with k-Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-7Apriori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Association Rules (Apriori)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-9ts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Time Series Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-anomaly.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Anomaly Detection</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part8-beyond-tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part VIII: Beyond Tables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-4text.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Text Analytics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-4text-sentiment-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Sentiment Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-4text-visualising-text-analytics-through-wordc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Visualising Text</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Network.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Networks and Graph Theory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Network-applying-network-analysis-in-audit-fraud.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Network Analysis in Audit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-Rgeo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Maps</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-Rgeo-geo-coding-in-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Geocoding</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-Rgeo-reverse-geo-coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Reverse Geocoding</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part9-reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part IX: Reporting</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Reproducible Audit Reports</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./audit-questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Audit Question Finder</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98-datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Datasets Used in This Book</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">R Packages Used in This Book</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./97-colors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Colours in R</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#sec-tests-idea" id="toc-sec-tests-idea" class="nav-link active" data-scroll-target="#sec-tests-idea"><span class="header-section-number">28.1</span> The idea of a test</a></li>
  <li><a href="#our-data" id="toc-our-data" class="nav-link" data-scroll-target="#our-data"><span class="header-section-number">28.2</span> Our data</a></li>
  <li><a href="#sec-tests-binom" id="toc-sec-tests-binom" class="nav-link" data-scroll-target="#sec-tests-binom"><span class="header-section-number">28.3</span> Is the error rate above the tolerable rate?</a></li>
  <li><a href="#sec-tests-prop" id="toc-sec-tests-prop" class="nav-link" data-scroll-target="#sec-tests-prop"><span class="header-section-number">28.4</span> Comparing two rates</a></li>
  <li><a href="#sec-tests-chisq" id="toc-sec-tests-chisq" class="nav-link" data-scroll-target="#sec-tests-chisq"><span class="header-section-number">28.5</span> Comparing many groups at once</a></li>
  <li><a href="#sec-tests-multiple" id="toc-sec-tests-multiple" class="nav-link" data-scroll-target="#sec-tests-multiple"><span class="header-section-number">28.6</span> Drilling down, and the problem of many tests</a></li>
  <li><a href="#sec-tests-t" id="toc-sec-tests-t" class="nav-link" data-scroll-target="#sec-tests-t"><span class="header-section-number">28.7</span> Comparing averages</a></li>
  <li><a href="#sec-tests-wilcox" id="toc-sec-tests-wilcox" class="nav-link" data-scroll-target="#sec-tests-wilcox"><span class="header-section-number">28.8</span> When amounts are skewed</a></li>
  <li><a href="#sec-tests-kruskal" id="toc-sec-tests-kruskal" class="nav-link" data-scroll-target="#sec-tests-kruskal"><span class="header-section-number">28.9</span> More than two groups</a></li>
  <li><a href="#sec-tests-gof" id="toc-sec-tests-gof" class="nav-link" data-scroll-target="#sec-tests-gof"><span class="header-section-number">28.10</span> Does the data follow an expected pattern?</a></li>
  <li><a href="#sec-tests-cor" id="toc-sec-tests-cor" class="nav-link" data-scroll-target="#sec-tests-cor"><span class="header-section-number">28.11</span> Are two things related?</a></li>
  <li><a href="#sec-tests-effect" id="toc-sec-tests-effect" class="nav-link" data-scroll-target="#sec-tests-effect"><span class="header-section-number">28.12</span> Significant is not the same as important</a></li>
  <li><a href="#sec-tests-choose" id="toc-sec-tests-choose" class="nav-link" data-scroll-target="#sec-tests-choose"><span class="header-section-number">28.13</span> Choosing a test</a></li>
  <li><a href="#a-suggested-workflow" id="toc-a-suggested-workflow" class="nav-link" data-scroll-target="#a-suggested-workflow"><span class="header-section-number">28.14</span> A suggested workflow</a></li>
  <li><a href="#summary-of-functions-used" id="toc-summary-of-functions-used" class="nav-link" data-scroll-target="#summary-of-functions-used"><span class="header-section-number">28.15</span> Summary of functions used</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/anilyayavar/new-book/edit/master/12-3b-tests.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/anilyayavar/new-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./part4-explore-sample.html">Part IV: Exploring and Sampling</a></li><li class="breadcrumb-item"><a href="./12-3b-tests.html"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Statistical Tests for Auditors</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-tests" class="quarto-section-identifier"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Statistical Tests for Auditors</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>An auditor finds that one office approves 91 out of every 100 medical claims, while the rest of the department approves 84. Is that office lax in its checks, or is the difference just the kind of variation we should expect between any two offices? One dealing officer’s claims are larger on average than everyone else’s. Is that a pattern worth an inquiry, or a coincidence?</p>
<p>These are the questions a <em>statistical test</em> answers. It tells us whether a difference we see is larger than chance alone would usually produce. A test does not prove an irregularity. But it helps us decide where to spend our limited audit time, and it protects us from two embarrassments: chasing differences that mean nothing, and missing ones that matter.</p>
<p>In this chapter we learn the idea of a test in plain words, and then the tests an auditor needs most often. Each answers a question that comes up in real audits.</p>
<p><strong>Prerequisites</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span>   <span class="co"># turns test results into tidy tables</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>All the tests themselves come with base R, in the package <code>stats</code>, which is always loaded.</p>
<section id="sec-tests-idea" class="level2" data-number="28.1"><h2 data-number="28.1" class="anchored" data-anchor-id="sec-tests-idea">
<span class="header-section-number">28.1</span> The idea of a test</h2>
<p>Every test follows the same reasoning, which is very close to how an auditor already thinks.</p>
<ol type="1">
<li>
<strong>Start by assuming nothing is unusual.</strong> This assumption is called the <em>null hypothesis</em>. For example, “this office approves claims at the same rate as the others”. It is like presuming an auditee innocent until the evidence says otherwise.</li>
<li>
<strong>Ask how surprising the data would be, if nothing were unusual.</strong> The answer is the <em>p-value</em>, a probability between 0 and 1. A p-value of 0.30 means that, if nothing were unusual, a difference at least this large would turn up 30% of the time by chance alone. Not surprising at all. A p-value of 0.001 means it would turn up only once in a thousand times. Very surprising.</li>
<li>
<strong>Decide.</strong> If the p-value is small, below a limit we fix in advance, we conclude that chance is an unlikely explanation, and call the difference <em>statistically significant</em>. The usual limit is 0.05, or 5%.</li>
</ol>
<p>A test can go wrong in two ways, and both have an audit meaning.</p>
<div id="tbl-test-errors" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-test-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;28.1: The two errors of a test, in audit terms
</figcaption><div aria-describedby="tbl-test-errors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead><tr class="header">
<th></th>
<th>Nothing is actually unusual</th>
<th>Something is actually unusual</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Test says significant</strong></td>
<td>
<em>Type I error</em>, a false alarm. Time wasted on an inquiry, and an auditee questioned unfairly.</td>
<td>Correct. A real issue found.</td>
</tr>
<tr class="even">
<td><strong>Test says not significant</strong></td>
<td>Correct. No time wasted.</td>
<td>
<em>Type II error</em>, a miss. A real issue goes unreported. This is audit risk.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The 5% limit is the chance of a false alarm we are willing to accept. A smaller limit means fewer false alarms but more misses. With a small sample, a test may miss even a large difference, as we will see.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What if we have the whole population?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Auditors often analyse 100% of the data, not a sample. If one office approved 94% of its claims and another 86%, that difference is a <em>fact</em>. Why test it? Because claims are approved or rejected for many reasons, and even two identical offices would not show identical rates in a year. The test asks whether the difference is larger than this ordinary variation in the process. So tests are useful on full data too, as long as we read “significant” as “unlikely to be ordinary variation”, and not as a finding in itself.</p>
</div>
</div>
</section><section id="our-data" class="level2" data-number="28.2"><h2 data-number="28.2" class="anchored" data-anchor-id="our-data">
<span class="header-section-number">28.2</span> Our data</h2>
<p>We use one data set through most of the chapter. It is a year’s register of medical reimbursement claims of a department with six offices, each office with two dealing officers. For each claim we have the amount, whether it was approved, and the days taken to settle it.</p>
<div class="cell">
<details class="code-fold"><summary>Code to create the claims register</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">6</span><span class="op">)</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">3000</span></span>
<span><span class="va">offices</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Amarpur"</span>, <span class="st">"Belapur"</span>, <span class="st">"Chandpur"</span>, <span class="st">"Devgarh"</span>, <span class="st">"Fatehpur"</span>, <span class="st">"Rampur"</span><span class="op">)</span></span>
<span><span class="va">claims</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  claim_id <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span><span class="op">(</span><span class="st">"MR-%04d"</span>, <span class="fl">1</span><span class="op">:</span><span class="va">n</span><span class="op">)</span>,</span>
<span>  office   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">offices</span>, <span class="va">n</span>, <span class="cn">TRUE</span>, prob <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.2</span>, <span class="fl">0.18</span>, <span class="fl">0.17</span>, <span class="fl">0.16</span>, <span class="fl">0.15</span>, <span class="fl">0.14</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  desk     <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">2</span>, <span class="va">n</span>, <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>  amount   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Lognormal.html">rlnorm</a></span><span class="op">(</span><span class="va">n</span>, <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="fl">18000</span><span class="op">)</span>, <span class="fl">0.8</span><span class="op">)</span>, <span class="op">-</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>officer <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/chartr.html">toupper</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/substr.html">substr</a></span><span class="op">(</span><span class="va">office</span>, <span class="fl">1</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span>, <span class="st">"-"</span>, <span class="va">desk</span><span class="op">)</span>,</span>
<span>         <span class="co"># Planted. Officer RAM-2 approves almost everything</span></span>
<span>         approved <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span> <span class="op">&lt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">officer</span> <span class="op">==</span> <span class="st">"RAM-2"</span>, <span class="fl">0.97</span>, <span class="fl">0.86</span><span class="op">)</span>,</span>
<span>         <span class="co"># Planted. Chandpur is slow to settle claims</span></span>
<span>         days_to_settle <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/GammaDist.html">rgamma</a></span><span class="op">(</span><span class="va">n</span>, shape <span class="op">=</span> <span class="fl">4</span>,</span>
<span>                                       rate <span class="op">=</span> <span class="fl">4</span> <span class="op">/</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">office</span> <span class="op">==</span> <span class="st">"Chandpur"</span>, <span class="fl">27</span>, <span class="fl">21</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,</span>
<span>         <span class="co"># Planted. Claims handled by DEV-2 are inflated</span></span>
<span>         amount <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">officer</span> <span class="op">==</span> <span class="st">"DEV-2"</span>, <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">amount</span> <span class="op">*</span> <span class="fl">1.4</span>, <span class="op">-</span><span class="fl">1</span><span class="op">)</span>, <span class="va">amount</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">claim_id</span>, <span class="va">office</span>, <span class="va">officer</span>, <span class="va">amount</span>, <span class="va">approved</span>, <span class="va">days_to_settle</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">claims</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,000 × 6
   claim_id office   officer amount approved days_to_settle
   &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;    &lt;dbl&gt; &lt;lgl&gt;             &lt;dbl&gt;
 1 MR-0001  Devgarh  DEV-2    91630 TRUE                 15
 2 MR-0002  Rampur   RAM-1    64380 FALSE                13
 3 MR-0003  Belapur  BEL-2    55860 FALSE                16
 4 MR-0004  Chandpur CHA-1    10320 FALSE                45
 5 MR-0005  Fatehpur FAT-1    44060 TRUE                 20
 6 MR-0006  Rampur   RAM-2    10610 TRUE                 13
 7 MR-0007  Rampur   RAM-2    15150 TRUE                  9
 8 MR-0008  Fatehpur FAT-1    12210 FALSE                15
 9 MR-0009  Chandpur CHA-1    10460 TRUE                 25
10 MR-0010  Amarpur  AMA-1    32840 TRUE                  2
# ℹ 2,990 more rows</code></pre>
</div>
</div>
</section><section id="sec-tests-binom" class="level2" data-number="28.3"><h2 data-number="28.3" class="anchored" data-anchor-id="sec-tests-binom">
<span class="header-section-number">28.3</span> Is the error rate above the tolerable rate?</h2>
<p>Let us start with a question from a test of controls. The auditor checks a random sample of 60 claims, and finds 6 settled without the required verification. The tolerable deviation rate is 5%. The sample’s rate is 10%, twice the tolerable rate. Can we conclude that the control is failing?</p>
<p><code><a href="https://rdrr.io/r/stats/binom.test.html">binom.test()</a></code> compares a count of “successes” (here, deviations) in a number of trials with an expected proportion. Since we only care whether the rate is <em>above</em> 5%, we use <code>alternative = "greater"</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dev_test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/binom.test.html">binom.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">6</span>, n <span class="op">=</span> <span class="fl">60</span>, p <span class="op">=</span> <span class="fl">0.05</span>, alternative <span class="op">=</span> <span class="st">"greater"</span><span class="op">)</span></span>
<span><span class="va">dev_test</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  6 and 60
number of successes = 6, number of trials = 60, p-value = 0.07872
alternative hypothesis: true probability of success is greater than 0.05
95 percent confidence interval:
 0.04445297 1.00000000
sample estimates:
probability of success 
                   0.1 </code></pre>
</div>
</div>
<p>The p-value is 0.079, above 0.05. Surprisingly, a sample of 60 with 6 deviations is <em>not</em> enough to conclude that the true rate exceeds 5%. With 60 claims, a true rate of 5% would give 6 or more deviations about 8% of the time. The confidence interval says the same: the true rate could be as low as 4.4%.</p>
<p>What if the auditor had found 9 deviations instead?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/binom.test.html">binom.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">9</span>, n <span class="op">=</span> <span class="fl">60</span>, p <span class="op">=</span> <span class="fl">0.05</span>, alternative <span class="op">=</span> <span class="st">"greater"</span><span class="op">)</span><span class="op">$</span><span class="va">p.value</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.002848606</code></pre>
</div>
</div>
<p>Now the conclusion is clear. This is the reason why sample sizes for tests of controls are planned in advance, as we did in <a href="12-3Samp.html#sec-samplesize" class="quarto-xref"><span>Section 27.7</span></a>. A test on a sample too small to detect the difference we care about can only end in “not proven”.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>“Not significant” does not mean “no problem”. It means the data are not strong enough to rule out chance. Never report a control as effective only because a test was not significant, least of all on a small sample. Report what was found, 6 deviations in 60, and the limit of what the sample can tell.</p>
</div>
</div>
</section><section id="sec-tests-prop" class="level2" data-number="28.4"><h2 data-number="28.4" class="anchored" data-anchor-id="sec-tests-prop">
<span class="header-section-number">28.4</span> Comparing two rates</h2>
<p>Back to the full register. Rampur approves more claims than the rest of the department. Is the difference more than chance?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">claims</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>claims <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>, n_approved <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">approved</span><span class="op">)</span>,</span>
<span>            approval_rate <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">approved</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>            .by <span class="op">=</span> <span class="va">office</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">approval_rate</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  office   claims n_approved approval_rate
  &lt;chr&gt;     &lt;int&gt;      &lt;int&gt;         &lt;dbl&gt;
1 Rampur      433        395         0.912
2 Fatehpur    445        381         0.856
3 Belapur     527        445         0.844
4 Amarpur     587        495         0.843
5 Chandpur    523        440         0.841
6 Devgarh     485        405         0.835</code></pre>
</div>
</div>
<p><code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code> compares two (or more) proportions. We give it the number approved and the number of claims in each group.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">rampur</span> <span class="op">&lt;-</span> <span class="va">claims</span><span class="op">$</span><span class="va">office</span> <span class="op">==</span> <span class="st">"Rampur"</span></span>
<span><span class="va">rampur_test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/prop.test.html">prop.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">claims</span><span class="op">$</span><span class="va">approved</span><span class="op">[</span><span class="va">rampur</span><span class="op">]</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">claims</span><span class="op">$</span><span class="va">approved</span><span class="op">[</span><span class="op">!</span><span class="va">rampur</span><span class="op">]</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                         n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">rampur</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">!</span><span class="va">rampur</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">rampur_test</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  c(sum(claims$approved[rampur]), sum(claims$approved[!rampur])) out of c(sum(rampur), sum(!rampur))
X-squared = 13.355, df = 1, p-value = 0.0002577
alternative hypothesis: two.sided
95 percent confidence interval:
 0.03697932 0.09992800
sample estimates:
   prop 1    prop 2 
0.9122402 0.8437865 </code></pre>
</div>
</div>
<p>Rampur approved 91.2% of its claims, against 84.4% elsewhere. The p-value is 0.00026, far below 0.05. A difference this large would almost never arise by chance. The confidence interval says that Rampur’s rate is higher by somewhere between 3.7 and 10 percentage points.</p>
</section><section id="sec-tests-chisq" class="level2" data-number="28.5"><h2 data-number="28.5" class="anchored" data-anchor-id="sec-tests-chisq">
<span class="header-section-number">28.5</span> Comparing many groups at once</h2>
<p>Rampur caught our eye because we looked at the table first. A fairer way is to test all six offices together, without picking one in advance. The <em>chi-square test of independence</em> checks whether two categorical variables, here office and approval, are related. If approval did not depend on the office, every office would approve about the same share.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">approval_table</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">claims</span><span class="op">$</span><span class="va">office</span>, <span class="va">claims</span><span class="op">$</span><span class="va">approved</span><span class="op">)</span></span>
<span><span class="va">approval_table</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
           FALSE TRUE
  Amarpur     92  495
  Belapur     82  445
  Chandpur    83  440
  Devgarh     80  405
  Fatehpur    64  381
  Rampur      38  395</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">office_test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">(</span><span class="va">approval_table</span><span class="op">)</span></span>
<span><span class="va">office_test</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  approval_table
X-squared = 14.77, df = 5, p-value = 0.01139</code></pre>
</div>
</div>
<p>The p-value of 0.011 is below 0.05, so approval rates do differ between offices. But the test does not say <em>which</em> office is different. For that, look at the <em>standardised residuals</em>. Each says how far an office’s count is from what we would expect if all offices were alike, in units of standard deviation. Values beyond about 2 (or below -2) deserve attention.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">office_test</span><span class="op">$</span><span class="va">stdres</span>, <span class="fl">2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
           FALSE  TRUE
  Amarpur   0.79 -0.79
  Belapur   0.66 -0.66
  Chandpur  0.88 -0.88
  Devgarh   1.27 -1.27
  Fatehpur -0.16  0.16
  Rampur   -3.73  3.73</code></pre>
</div>
</div>
<p>Only Rampur stands out, with 3.7 standard deviations more approvals than expected. Every other office is within 2.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Audit tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The chi-square test with its residuals is one of the most useful tests in audit. It works on any cross-table of counts: rejections by inspector, tenders won by bidder and department, cases disposed of by officer and type, or exceptions by branch. The residuals point straight at the cells which are out of line.</p>
</div>
</div>
<p>The chi-square test needs enough data in every cell. If any <em>expected</em> count, <code>office_test$expected</code>, is below 5, R gives a warning that the result may be inaccurate. Then use <code><a href="https://rdrr.io/r/stats/fisher.test.html">fisher.test()</a></code>, which is exact, or combine small groups.</p>
</section><section id="sec-tests-multiple" class="level2" data-number="28.6"><h2 data-number="28.6" class="anchored" data-anchor-id="sec-tests-multiple">
<span class="header-section-number">28.6</span> Drilling down, and the problem of many tests</h2>
<p>Rampur has two dealing officers. Is the high approval rate the office’s, or one officer’s? A natural step is to test every officer against the rest. But with many tests, a new problem appears.</p>
<p><strong>Many tests mean some false alarms.</strong> Each test at the 5% level has a 5% chance of a false alarm. Run 20 tests where nothing is unusual, and on average one will come out “significant” anyway. Let us see this with 40 imaginary offices which all approve at exactly the same true rate of 86%.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">p_values</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://purrr.tidyverse.org/reference/map.html">map_dbl</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">40</span>, \<span class="op">(</span><span class="va">i</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">approved_here</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="fl">1</span>, size <span class="op">=</span> <span class="fl">300</span>, prob <span class="op">=</span> <span class="fl">0.86</span><span class="op">)</span>    <span class="co"># this office, 300 claims</span></span>
<span>  <span class="va">approved_rest</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="fl">1</span>, size <span class="op">=</span> <span class="fl">12000</span>, prob <span class="op">=</span> <span class="fl">0.86</span><span class="op">)</span>  <span class="co"># all the others</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/prop.test.html">prop.test</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">approved_here</span>, <span class="va">approved_rest</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">300</span>, <span class="fl">12000</span><span class="op">)</span><span class="op">)</span><span class="op">$</span><span class="va">p.value</span></span>
<span><span class="op">}</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">p_values</span> <span class="op">&lt;</span> <span class="fl">0.05</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>2 of the 40 identical offices look “significantly” different, purely by chance. Reporting them would be unfair to their staff. The remedy is to <em>adjust</em> the p-values for the number of tests. <code><a href="https://rdrr.io/r/stats/p.adjust.html">p.adjust()</a></code> does this. The Holm method is a safe general choice.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/p.adjust.html">p.adjust</a></span><span class="op">(</span><span class="va">p_values</span>, method <span class="op">=</span> <span class="st">"holm"</span><span class="op">)</span> <span class="op">&lt;</span> <span class="fl">0.05</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>After adjustment, no false alarms remain. Now the real drill-down. We test each of the 12 officers against all the others, collect the results with <code><a href="https://generics.r-lib.org/reference/tidy.html">broom::tidy()</a></code>, and adjust.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">officer_tests</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://purrr.tidyverse.org/reference/map.html">map</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">claims</span><span class="op">$</span><span class="va">officer</span><span class="op">)</span><span class="op">)</span>, \<span class="op">(</span><span class="va">o</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">mine</span> <span class="op">&lt;-</span> <span class="va">claims</span><span class="op">$</span><span class="va">officer</span> <span class="op">==</span> <span class="va">o</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/prop.test.html">prop.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">claims</span><span class="op">$</span><span class="va">approved</span><span class="op">[</span><span class="va">mine</span><span class="op">]</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">claims</span><span class="op">$</span><span class="va">approved</span><span class="op">[</span><span class="op">!</span><span class="va">mine</span><span class="op">]</span><span class="op">)</span><span class="op">)</span>,</span>
<span>            n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">mine</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">!</span><span class="va">mine</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>officer <span class="op">=</span> <span class="va">o</span>, claims <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">mine</span><span class="op">)</span>, .before <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://purrr.tidyverse.org/reference/list_c.html">list_rbind</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>p_adjusted <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/p.adjust.html">p.adjust</a></span><span class="op">(</span><span class="va">p.value</span>, method <span class="op">=</span> <span class="st">"holm"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">officer</span>, <span class="va">claims</span>, own_rate <span class="op">=</span> <span class="va">estimate1</span>, rest_rate <span class="op">=</span> <span class="va">estimate2</span>, <span class="va">p.value</span>, <span class="va">p_adjusted</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">p.value</span><span class="op">)</span></span>
<span></span>
<span><span class="va">officer_tests</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">own_rate</span>, <span class="va">rest_rate</span><span class="op">)</span>, \<span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">x</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span>,</span>
<span>                        <span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">p.value</span>, <span class="va">p_adjusted</span><span class="op">)</span>, \<span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">signif</a></span><span class="op">(</span><span class="va">x</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 6
   officer claims own_rate rest_rate   p.value p_adjusted
   &lt;chr&gt;    &lt;int&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 RAM-2      216    0.963     0.845 0.0000039   0.000047
 2 DEV-1      243    0.819     0.857 0.13        1       
 3 AMA-2      277    0.83      0.856 0.29        1       
 4 BEL-2      281    0.833     0.856 0.34        1       
 5 FAT-1      240    0.871     0.852 0.49        1       
 6 CHA-1      261    0.839     0.855 0.54        1       
 7 FAT-2      205    0.839     0.855 0.61        1       
 8 CHA-2      262    0.844     0.855 0.69        1       
 9 RAM-1      217    0.862     0.853 0.8         1       
10 BEL-1      246    0.858     0.853 0.93        1       
11 DEV-2      242    0.851     0.854 0.99        1       
12 AMA-1      310    0.855     0.854 1           1       </code></pre>
</div>
</div>
<p>The picture is clear. Officer RAM-2 approved 96.3% of claims, and stays significant even after adjustment (adjusted p-value less than 0.0001). The other Rampur officer, RAM-1, approved 86.2%, in line with the department. So the office’s high rate comes from one desk. That is where the audit should look, at a sample of the claims RAM-2 approved, to see whether the checks were actually done.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Audit tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><code><a href="https://generics.r-lib.org/reference/tidy.html">broom::tidy()</a></code> turns the output of almost any test into a one-row table. Together with <code><a href="https://purrr.tidyverse.org/reference/map.html">map()</a></code> and <code><a href="https://purrr.tidyverse.org/reference/list_c.html">list_rbind()</a></code>, it lets us run the same test over every officer, vendor or district, and get one table to sort, filter and attach to working papers. Always add a column of adjusted p-values when you do this.</p>
</div>
</div>
</section><section id="sec-tests-t" class="level2" data-number="28.7"><h2 data-number="28.7" class="anchored" data-anchor-id="sec-tests-t">
<span class="header-section-number">28.7</span> Comparing averages</h2>
<p>Rates are about counts. Many audit questions are about amounts and times instead. Is Chandpur slower to settle claims than the other offices? The <em>t-test</em> compares the means of two groups.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">claims</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>mean_days <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">days_to_settle</span><span class="op">)</span>, <span class="fl">1</span><span class="op">)</span>,</span>
<span>            median_days <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">days_to_settle</span><span class="op">)</span>, .by <span class="op">=</span> <span class="va">office</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  office   mean_days median_days
  &lt;chr&gt;        &lt;dbl&gt;       &lt;dbl&gt;
1 Devgarh       21.8          20
2 Rampur        21.4          20
3 Belapur       20.3          19
4 Chandpur      27            25
5 Fatehpur      21.3          19
6 Amarpur       21.4          20</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">chandpur_test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">days_to_settle</span> <span class="op">~</span> <span class="op">(</span><span class="va">office</span> <span class="op">==</span> <span class="st">"Chandpur"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">claims</span><span class="op">)</span></span>
<span><span class="va">chandpur_test</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  days_to_settle by office == "Chandpur"
t = -9.1182, df = 652.93, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0
95 percent confidence interval:
 -7.057826 -4.556638
sample estimates:
mean in group FALSE  mean in group TRUE 
           21.22527            27.03250 </code></pre>
</div>
</div>
<p>Chandpur takes 27 days on average, against 21.2 days elsewhere, and the p-value is extremely small. The difference is real, not chance. R uses <em>Welch’s</em> t-test by default, which does not assume that the two groups vary equally. Keep this default.</p>
<p>The formula <code>days_to_settle ~ (office == "Chandpur")</code> reads “days to settle, by whether the office is Chandpur”. The group <code>FALSE</code> (the other offices) comes first in the output.</p>
</section><section id="sec-tests-wilcox" class="level2" data-number="28.8"><h2 data-number="28.8" class="anchored" data-anchor-id="sec-tests-wilcox">
<span class="header-section-number">28.8</span> When amounts are skewed</h2>
<p>The t-test compares <em>means</em>. Money amounts are usually skewed, with many small values and a few very large ones, as we saw in <a href="12-1Desc.html" class="quarto-xref"><span>Chapter 25</span></a>. A handful of large claims can pull a mean up or down, and make the t-test unreliable. The <em>Wilcoxon rank-sum test</em> (also called the Mann-Whitney test) avoids this. It ranks all the values together, and asks whether one group’s values tend to rank higher than the other’s. A single huge claim is then just “the highest rank”, whatever its size.</p>
<p>Are the claims handled by officer DEV-2 larger than everyone else’s?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">claims</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>group <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">officer</span> <span class="op">==</span> <span class="st">"DEV-2"</span>, <span class="st">"DEV-2"</span>, <span class="st">"Others"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>claims <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>, mean_amount <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">amount</span><span class="op">)</span><span class="op">)</span>,</span>
<span>            median_amount <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">amount</span><span class="op">)</span>, .by <span class="op">=</span> <span class="va">group</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  group  claims mean_amount median_amount
  &lt;chr&gt;   &lt;int&gt;       &lt;dbl&gt;         &lt;dbl&gt;
1 DEV-2     242       36081         26020
2 Others   2758       24549         17980</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dev2_test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/wilcox.test.html">wilcox.test</a></span><span class="op">(</span><span class="va">amount</span> <span class="op">~</span> <span class="op">(</span><span class="va">officer</span> <span class="op">==</span> <span class="st">"DEV-2"</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">claims</span><span class="op">)</span></span>
<span><span class="va">dev2_test</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  amount by officer == "DEV-2"
W = 234586, p-value = 1.68e-14
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>The p-value is less than 0.0001, so DEV-2’s claims are systematically larger. The median tells the same story more plainly than the mean. A follow-up might compare the hospitals, bills and rates in DEV-2’s claims with the others.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Tests like Wilcoxon’s, which work on ranks, are called <em>non-parametric</em>, because they do not assume the data follow a normal distribution. For audit data, which are rarely normal, they are often the safer choice. When both tests are run and they agree, as they usually do on large data, we can be confident. When they disagree, trust the rank test and look for extreme values.</p>
</div>
</div>
</section><section id="sec-tests-kruskal" class="level2" data-number="28.9"><h2 data-number="28.9" class="anchored" data-anchor-id="sec-tests-kruskal">
<span class="header-section-number">28.9</span> More than two groups</h2>
<p>To compare settlement times across all six offices at once, rather than one office against the rest, use the <em>Kruskal-Wallis test</em>, the rank-based version for several groups.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/kruskal.test.html">kruskal.test</a></span><span class="op">(</span><span class="va">days_to_settle</span> <span class="op">~</span> <span class="va">office</span>, data <span class="op">=</span> <span class="va">claims</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  days_to_settle by office
Kruskal-Wallis chi-squared = 86.219, df = 5, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>It says the offices differ, but not which ones. To find out, compare every pair with <code><a href="https://rdrr.io/r/stats/pairwise.wilcox.test.html">pairwise.wilcox.test()</a></code>, which adjusts the p-values for the many comparisons, just as we learnt above.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/pairwise.wilcox.test.html">pairwise.wilcox.test</a></span><span class="op">(</span><span class="va">claims</span><span class="op">$</span><span class="va">days_to_settle</span>, <span class="va">claims</span><span class="op">$</span><span class="va">office</span>, p.adjust.method <span class="op">=</span> <span class="st">"holm"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using Wilcoxon rank sum test with continuity correction 

data:  claims$days_to_settle and claims$office 

         Amarpur Belapur Chandpur Devgarh Fatehpur
Belapur  1.00    -       -        -       -       
Chandpur 4.4e-11 3.0e-15 -        -       -       
Devgarh  1.00    0.26    1.2e-08  -       -       
Fatehpur 1.00    1.00    1.4e-10  1.00    -       
Rampur   1.00    0.76    4.3e-09  1.00    1.00    

P value adjustment method: holm </code></pre>
</div>
</div>
<p>Every pair involving Chandpur has a tiny p-value, while the other pairs do not differ. (The classic test for comparing the means of several groups is <em>analysis of variance</em>, <code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code>. It is closely related to linear regression, which we meet in <a href="12-4Reg.html" class="quarto-xref"><span>Chapter 37</span></a>.)</p>
</section><section id="sec-tests-gof" class="level2" data-number="28.10"><h2 data-number="28.10" class="anchored" data-anchor-id="sec-tests-gof">
<span class="header-section-number">28.10</span> Does the data follow an expected pattern?</h2>
<p>Sometimes we know what pattern the data <em>should</em> follow, and want to test whether it does. This is the <em>chi-square goodness-of-fit test</em>. The number of claims from each office should be roughly in proportion to its staff strength.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">staff</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>Amarpur <span class="op">=</span> <span class="fl">400</span>, Belapur <span class="op">=</span> <span class="fl">360</span>, Chandpur <span class="op">=</span> <span class="fl">340</span>,</span>
<span>           Devgarh <span class="op">=</span> <span class="fl">320</span>, Fatehpur <span class="op">=</span> <span class="fl">300</span>, Rampur <span class="op">=</span> <span class="fl">280</span><span class="op">)</span></span>
<span><span class="va">observed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">claims</span><span class="op">$</span><span class="va">office</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">staff</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span>observed <span class="op">=</span> <span class="va">observed</span>, expected <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">observed</span><span class="op">)</span> <span class="op">*</span> <span class="va">staff</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">staff</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Amarpur Belapur Chandpur Devgarh Fatehpur Rampur
observed     587     527      523     485      445    433
expected     600     540      510     480      450    420</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">fit_test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">(</span><span class="va">observed</span>, p <span class="op">=</span> <span class="va">staff</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">staff</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">fit_test</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  observed
X-squared = 1.436, df = 5, p-value = 0.9203</code></pre>
</div>
</div>
<p>The p-value of 0.92 is large. The claims follow the staff strength well, and there is nothing to report. This, too, is a useful audit result. Not every test should find something, and a clean result lets us move on with confidence.</p>
<p>We have already used goodness-of-fit tests in this book without calling them that. The Benford chi-square in <a href="17-Anamolous.html#sec-chis" class="quarto-xref"><span>Section 30.5.1</span></a> and the digit tests in <a href="19-nigrini-tests.html" class="quarto-xref"><span>Chapter 31</span></a> compare observed counts of digits with the counts expected under a known pattern.</p>
</section><section id="sec-tests-cor" class="level2" data-number="28.11"><h2 data-number="28.11" class="anchored" data-anchor-id="sec-tests-cor">
<span class="header-section-number">28.11</span> Are two things related?</h2>
<p>Do larger claims take longer to settle? <code><a href="https://rdrr.io/r/stats/cor.test.html">cor.test()</a></code> tests whether a correlation is different from zero. For skewed amounts, use Spearman’s rank correlation, <code>method = "spearman"</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cor_test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cor.test.html">cor.test</a></span><span class="op">(</span><span class="va">claims</span><span class="op">$</span><span class="va">amount</span>, <span class="va">claims</span><span class="op">$</span><span class="va">days_to_settle</span>, method <span class="op">=</span> <span class="st">"spearman"</span>, exact <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">cor_test</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  claims$amount and claims$days_to_settle
S = 4.469e+09, p-value = 0.7061
alternative hypothesis: true rho is not equal to 0
sample estimates:
        rho 
0.006888644 </code></pre>
</div>
</div>
<p>The correlation is 0.007, practically zero, and not significant (p = 0.71). Settlement time does not depend on the claim amount here. If it did, say if large claims were settled much faster than small ones, it would be worth asking why.</p>
</section><section id="sec-tests-effect" class="level2" data-number="28.12"><h2 data-number="28.12" class="anchored" data-anchor-id="sec-tests-effect">
<span class="header-section-number">28.12</span> Significant is not the same as important</h2>
<p>A p-value measures how sure we are that a difference is not chance. It does not measure how <em>large</em> or how <em>important</em> the difference is. Two points follow, and both matter in audit.</p>
<p><strong>With very large data, tiny differences become significant.</strong> Two districts, each with two lakh claims, approve 85.0% and 85.4% of them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/prop.test.html">prop.test</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">170000</span>, <span class="fl">170800</span><span class="op">)</span>, n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">200000</span>, <span class="fl">200000</span><span class="op">)</span><span class="op">)</span><span class="op">$</span><span class="va">p.value</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0003741535</code></pre>
</div>
</div>
<p>The difference is highly significant, but 0.4 percentage points is unlikely to matter to anyone. Always look at the size of the difference, the <em>effect size</em>, alongside the p-value. For rates, that is the difference in percentage points, and for amounts, the difference in rupees.</p>
<p><strong>With small data, even large differences may not be significant.</strong> Two small offices, each with 12 claims, approve 10 and 7 of them, 83% against 58%. With counts this small, <code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code> warns that its approximation may be inaccurate, so we use the exact <code><a href="https://rdrr.io/r/stats/fisher.test.html">fisher.test()</a></code> on the cross-table of approved and rejected claims.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">small_offices</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">10</span>, <span class="fl">2</span>,    <span class="co"># office 1: approved, rejected</span></span>
<span>                          <span class="fl">7</span>, <span class="fl">5</span><span class="op">)</span>,    <span class="co"># office 2: approved, rejected</span></span>
<span>                        nrow <span class="op">=</span> <span class="fl">2</span>, byrow <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">small_test</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/fisher.test.html">fisher.test</a></span><span class="op">(</span><span class="va">small_offices</span><span class="op">)</span></span>
<span><span class="va">small_test</span><span class="op">$</span><span class="va">p.value</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3707094</code></pre>
</div>
</div>
<p>A large difference, but far from significant (p = 0.37), because 12 claims are too few to tell. As in <a href="#sec-tests-binom" class="quarto-xref"><span>Section 28.3</span></a>, the honest conclusion is “not proven”, not “no difference”.</p>
<p><strong>How much data is enough?</strong> The function <code><a href="https://rdrr.io/r/stats/power.prop.test.html">power.prop.test()</a></code> answers this before the analysis. How many claims per office do we need to detect a difference between an approval rate of 86% and one of 95%, with an 80% chance of catching it (the <em>power</em>)?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/power.prop.test.html">power.prop.test</a></span><span class="op">(</span>p1 <span class="op">=</span> <span class="fl">0.86</span>, p2 <span class="op">=</span> <span class="fl">0.95</span>, power <span class="op">=</span> <span class="fl">0.80</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample comparison of proportions power calculation 

              n = 165.4353
             p1 = 0.86
             p2 = 0.95
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
</div>
<p>About 166 claims in each group. For smaller differences, many more are needed. <code><a href="https://rdrr.io/r/stats/power.t.test.html">power.t.test()</a></code> does the same for comparing means.</p>
</section><section id="sec-tests-choose" class="level2" data-number="28.13"><h2 data-number="28.13" class="anchored" data-anchor-id="sec-tests-choose">
<span class="header-section-number">28.13</span> Choosing a test</h2>
<div id="tbl-choose-test" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-choose-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;28.2: Choosing a statistical test
</figcaption><div aria-describedby="tbl-choose-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
</colgroup>
<thead><tr class="header">
<th>Question</th>
<th>Data</th>
<th>Test</th>
<th>R function</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Is a rate above (or below) a benchmark?</td>
<td>One count out of a total</td>
<td>Binomial test</td>
<td><code><a href="https://rdrr.io/r/stats/binom.test.html">binom.test()</a></code></td>
</tr>
<tr class="even">
<td>Do two groups have different rates?</td>
<td>Counts and totals of two groups</td>
<td>Test of proportions</td>
<td><code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code></td>
</tr>
<tr class="odd">
<td>Do rates differ across several groups?</td>
<td>Cross-table of counts</td>
<td>Chi-square test of independence</td>
<td>
<code><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test()</a></code>, or <code><a href="https://rdrr.io/r/stats/fisher.test.html">fisher.test()</a></code> for small counts</td>
</tr>
<tr class="even">
<td>Do counts follow an expected pattern?</td>
<td>Counts and expected proportions</td>
<td>Chi-square goodness of fit</td>
<td><code>chisq.test(x, p = )</code></td>
</tr>
<tr class="odd">
<td>Do two groups have different averages?</td>
<td>Amounts or times, roughly symmetric</td>
<td>Welch t-test</td>
<td><code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code></td>
</tr>
<tr class="even">
<td>Do two groups have different typical values?</td>
<td>Skewed amounts</td>
<td>Wilcoxon rank-sum test</td>
<td><code><a href="https://rdrr.io/r/stats/wilcox.test.html">wilcox.test()</a></code></td>
</tr>
<tr class="odd">
<td>Do several groups differ?</td>
<td>Amounts or times</td>
<td>Kruskal-Wallis test, then pairwise tests</td>
<td>
<code><a href="https://rdrr.io/r/stats/kruskal.test.html">kruskal.test()</a></code>, <code><a href="https://rdrr.io/r/stats/pairwise.wilcox.test.html">pairwise.wilcox.test()</a></code>
</td>
</tr>
<tr class="even">
<td>Are two measures related?</td>
<td>Two numeric columns</td>
<td>Correlation test</td>
<td><code>cor.test(method = "spearman")</code></td>
</tr>
<tr class="odd">
<td>Many tests at once?</td>
<td>p-values</td>
<td>Adjust for multiple testing</td>
<td><code><a href="https://rdrr.io/r/stats/p.adjust.html">p.adjust()</a></code></td>
</tr>
<tr class="even">
<td>How much data do I need?</td>
<td>Expected rates or means</td>
<td>Power calculation</td>
<td>
<code><a href="https://rdrr.io/r/stats/power.prop.test.html">power.prop.test()</a></code>, <code><a href="https://rdrr.io/r/stats/power.t.test.html">power.t.test()</a></code>
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Audit tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Decide the test, and the limit for significance, <em>before</em> looking at the results. If we try test after test until one gives a small p-value, the result means nothing, because with enough attempts chance alone will oblige. Write down the question, the test and the limit in the audit plan, just as we fix the sample size in advance.</p>
</div>
</div>
</section><section id="a-suggested-workflow" class="level2" data-number="28.14"><h2 data-number="28.14" class="anchored" data-anchor-id="a-suggested-workflow">
<span class="header-section-number">28.14</span> A suggested workflow</h2>
<ol type="1">
<li>
<strong>State the question in plain words</strong>, such as “does this officer approve more claims than the others?”, and the null hypothesis it implies.</li>
<li>
<strong>Look at the data first.</strong> Summarise by group and plot. A test should confirm what you see, not replace looking.</li>
<li>
<strong>Choose the test</strong> from <a href="#tbl-choose-test" class="quarto-xref">Table&nbsp;<span>28.2</span></a>. Prefer rank tests for money amounts, and check that the chi-square test has enough data in each cell.</li>
<li>
<strong>Fix the significance limit in advance</strong>, usually 5%.</li>
<li>
<strong>When testing many groups, adjust the p-values</strong> with <code><a href="https://rdrr.io/r/stats/p.adjust.html">p.adjust()</a></code>.</li>
<li>
<strong>Report the size of the difference</strong> with the p-value, in percentage points or rupees.</li>
<li>
<strong>Treat a significant result as a lead, not a finding.</strong> Follow it up by examining the actual records, as with RAM-2’s approved claims.</li>
<li>
<strong>Treat a non-significant result as “not proven”</strong>, especially on small samples, and say what the data could and could not show.</li>
</ol>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Remember
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>A test asks one question: is this difference larger than chance would usually produce?</li>
<li>The p-value is the chance of seeing a difference at least this large if nothing were unusual. Small means surprising.</li>
<li>A false alarm wastes effort and is unfair to the auditee; a miss is audit risk. The significance limit balances the two.</li>
<li>Many tests produce false alarms by chance. Adjust the p-values with <code><a href="https://rdrr.io/r/stats/p.adjust.html">p.adjust()</a></code>.</li>
<li>For skewed amounts, prefer rank-based tests like <code><a href="https://rdrr.io/r/stats/wilcox.test.html">wilcox.test()</a></code> and <code><a href="https://rdrr.io/r/stats/kruskal.test.html">kruskal.test()</a></code>.</li>
<li>Significant does not mean important, and not significant does not mean no problem.</li>
</ul>
</div>
</div>
</section><section id="summary-of-functions-used" class="level2" data-number="28.15"><h2 data-number="28.15" class="anchored" data-anchor-id="summary-of-functions-used">
<span class="header-section-number">28.15</span> Summary of functions used</h2>
<div id="tbl-testfunctions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-testfunctions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;28.3: Functions used in this chapter
</figcaption><div aria-describedby="tbl-testfunctions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 22%">
<col style="width: 45%">
</colgroup>
<thead><tr class="header">
<th>Function</th>
<th>Package</th>
<th>What it does</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/binom.test.html">binom.test()</a></code></td>
<td>stats</td>
<td>Test a count of events against an expected proportion</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/stats/prop.test.html">prop.test()</a></code></td>
<td>stats</td>
<td>Compare proportions of two or more groups</td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test()</a></code></td>
<td>stats</td>
<td>Chi-square test of independence for a cross-table, or goodness of fit with <code>p =</code>; <code>$stdres</code> gives standardised residuals</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/stats/fisher.test.html">fisher.test()</a></code></td>
<td>stats</td>
<td>Exact test for a cross-table with small counts</td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code></td>
<td>stats</td>
<td>Compare the means of two groups (Welch’s test by default)</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/stats/wilcox.test.html">wilcox.test()</a></code></td>
<td>stats</td>
<td>Compare two groups by ranks, safe for skewed amounts</td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/kruskal.test.html">kruskal.test()</a></code></td>
<td>stats</td>
<td>Compare several groups by ranks</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/stats/pairwise.wilcox.test.html">pairwise.wilcox.test()</a></code></td>
<td>stats</td>
<td>Compare every pair of groups, with adjusted p-values</td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/aov.html">aov()</a></code></td>
<td>stats</td>
<td>Analysis of variance, comparing the means of several groups</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/r/stats/cor.test.html">cor.test()</a></code></td>
<td>stats</td>
<td>Test whether a correlation differs from zero</td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/stats/p.adjust.html">p.adjust()</a></code></td>
<td>stats</td>
<td>Adjust p-values for multiple testing</td>
</tr>
<tr class="even">
<td>
<code><a href="https://rdrr.io/r/stats/power.prop.test.html">power.prop.test()</a></code>, <code><a href="https://rdrr.io/r/stats/power.t.test.html">power.t.test()</a></code>
</td>
<td>stats</td>
<td>Sample size needed to detect a given difference</td>
</tr>
<tr class="odd">
<td><code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code></td>
<td>broom</td>
<td>Turn a test result into a one-row table</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-R-quarto" class="csl-entry" role="listitem">
Allaire, JJ, and Christophe Dervieux. <em>Quarto: R Interface to Quarto Markdown Publishing System</em>, 2025. <a href="https://github.com/quarto-dev/quarto-r">https://github.com/quarto-dev/quarto-r</a>.
</div>
<div id="ref-R-visNetwork" class="csl-entry" role="listitem">
Almende B.V. and Contributors, and Benoit Thieurmel. <em>visNetwork: Network Visualization Using Vis.js Library</em>, 2025. <a href="https://datastorm-open.github.io/visNetwork/">https://datastorm-open.github.io/visNetwork/</a>.
</div>
<div id="ref-igraph2023" class="csl-entry" role="listitem">
Antonov, Michael, Gábor Csárdi, Szabolcs Horvát, Kirill Müller, Tamás Nepusz, Daniel Noom, Maëlle Salmon, Vincent Traag, Brooke Foucault Welles, and Fabio Zanini. <span>“Igraph Enables Fast and Robust Network Analysis Across Programming Languages.”</span> <em>arXiv Preprint arXiv:2311.10260</em>, 2023. <a href="https://doi.org/10.48550/arXiv.2311.10260">https://doi.org/10.48550/arXiv.2311.10260</a>.
</div>
<div id="ref-R-PGRdup" class="csl-entry" role="listitem">
Aravind, J., J. Radhamani, Kalyani Srinivasan, B. Ananda Subhash, and Rishi Kumar Tyagi. <em>PGRdup: Discover Probable Duplicates in Plant Genetic Resources Collections</em>, 2026. <a href="https://cran.r-project.org/package=PGRdup">https://cran.r-project.org/package=PGRdup</a>.
</div>
<div id="ref-R-magrittr" class="csl-entry" role="listitem">
Bache, Stefan Milton, and Hadley Wickham. <em>Magrittr: A Forward-Pipe Operator for r</em>, 2025. <a href="https://magrittr.tidyverse.org">https://magrittr.tidyverse.org</a>.
</div>
<div id="ref-R-data.table" class="csl-entry" role="listitem">
Barrett, Tyson, Matt Dowle, Arun Srinivasan, Jan Gorecki, Michael Chirico, Toby Hocking, Benjamin Schwendinger, and Ivan Krylov. <em>Data.table: Extension of ‘Data.frame‘</em>, 2026. <a href="https://r-datatable.com">https://r-datatable.com</a>.
</div>
<div id="ref-frank_ben" class="csl-entry" role="listitem">
Benford, Frank. <span>“The Law of Anomalous Numbers.”</span> <em>Proceedings of the American Philosophical Society</em> 78, no. 4 (1938): 551–72. <a href="http://www.jstor.org/stable/984802">http://www.jstor.org/stable/984802</a>.
</div>
<div id="ref-R-FNN" class="csl-entry" role="listitem">
Beygelzimer, Alina, Sham Kakadet, John Langford, Sunil Arya, David Mount, and Shengqiao Li. <em>FNN: Fast Nearest Neighbor Search Algorithms and Applications</em>, 2024. <a href="https://doi.org/10.32614/CRAN.package.FNN">https://doi.org/10.32614/CRAN.package.FNN</a>.
</div>
<div id="ref-R-deaR" class="csl-entry" role="listitem">
Bolos, Vicente, Vicente Coll-Serrano, and Rafael Benitez Suarez. <em>deaR: Conventional and Fuzzy Data Envelopment Analysis</em>, 2026. <a href="https://doi.org/10.32614/CRAN.package.deaR">https://doi.org/10.32614/CRAN.package.deaR</a>.
</div>
<div id="ref-deaR2025" class="csl-entry" role="listitem">
Bolós, V. J., R. Benítez, and V. Coll-Serrano. <span>“deaR: Conventional and Fuzzy DEA Models with r.”</span> <em>SoftwareX</em> 31 (2025): 102266, 1–6. <a href="https://doi.org/10.1016/j.softx.2025.102266">https://doi.org/10.1016/j.softx.2025.102266</a>.
</div>
<div id="ref-R-SnowballC" class="csl-entry" role="listitem">
Bouchet-Valat, Milan. <em>SnowballC: Snowball Stemmers Based on the c Libstemmer UTF-8 Library</em>, 2023. <a href="https://github.com/nalimilan/R.TeMiS">https://github.com/nalimilan/R.TeMiS</a>.
</div>
<div id="ref-R-tidygeocoder" class="csl-entry" role="listitem">
Cambon, Jesse, Diego Hernangómez, Christopher Belanger, and Daniel Possenriede. <em>Tidygeocoder: Geocoding Made Easy</em>, 2025. <a href="https://jessecambon.github.io/tidygeocoder/">https://jessecambon.github.io/tidygeocoder/</a>.
</div>
<div id="ref-R-leaflet" class="csl-entry" role="listitem">
Cheng, Joe, Barret Schloerke, Bhaskar Karambelkar, Yihui Xie, and Garrick Aden-Buie. <em>Leaflet: Create Interactive Web Maps with the JavaScript Leaflet Library</em>, 2025. <a href="https://rstudio.github.io/leaflet/">https://rstudio.github.io/leaflet/</a>.
</div>
<div id="ref-R-benford.analysis" class="csl-entry" role="listitem">
Cinelli, Carlos. <em>Benford.analysis: Benford Analysis for Data Validation and Forensic Analytics</em>, 2018. <a href="http://github.com/carloscinelli/benford.analysis">http://github.com/carloscinelli/benford.analysis</a>.
</div>
<div id="ref-dea" class="csl-entry" role="listitem">
Cooper, William, Lawrence Seiford, and Joe Zhu. <span>“Data Envelopment Analysis: History, Models, and Interpretations.”</span> In <em>Handbook on Data Envelopment Analysis</em>, 1–39, 2011. <a href="https://doi.org/10.1007/978-1-4419-6151-8_1">https://doi.org/10.1007/978-1-4419-6151-8_1</a>.
</div>
<div id="ref-R-isotree" class="csl-entry" role="listitem">
Cortes, David. <em>Isotree: Isolation-Based Outlier Detection</em>, 2026. <a href="https://github.com/david-cortes/isotree">https://github.com/david-cortes/isotree</a>.
</div>
<div id="ref-R-rebus" class="csl-entry" role="listitem">
Cotton, Richard. <em>Rebus: Build Regular Expressions in a Human Readable Way</em>, 2017. <a href="https://doi.org/10.32614/CRAN.package.rebus">https://doi.org/10.32614/CRAN.package.rebus</a>.
</div>
<div id="ref-R-igraphdata" class="csl-entry" role="listitem">
Csardi, Gabor. <em>Igraphdata: A Collection of Network Data Sets for the Igraph Package</em>, 2015. <a href="http://igraph.org">http://igraph.org</a>.
</div>
<div id="ref-igraph2006" class="csl-entry" role="listitem">
Csárdi, Gábor, and Tamás Nepusz. <span>“The Igraph Software Package for Complex Network Research.”</span> <em>InterJournal</em> Complex Systems (2006): 1695. <a href="https://igraph.org">https://igraph.org</a>.
</div>
<div id="ref-R-igraph" class="csl-entry" role="listitem">
Csárdi, Gábor, Tamás Nepusz, Vincent Traag, Szabolcs Horvát, Fabio Zanini, Daniel Noom, Kirill Müller, David Schoch, and Maëlle Salmon. <em>Igraph: Network Analysis and Visualization</em>, 2026. <a href="https://r.igraph.org/">https://r.igraph.org/</a>.
</div>
<div id="ref-R-timetk" class="csl-entry" role="listitem">
Dancho, Matt, and Davis Vaughan. <em>Timetk: A Tool Kit for Working with Time Series</em>, 2025. <a href="https://github.com/business-science/timetk">https://github.com/business-science/timetk</a>.
</div>
<div id="ref-durtschi" class="csl-entry" role="listitem">
Durtschi, Cindy, William Hillison, and Carl Pacini. <span>“The Effective Use of Benford’s Law to Assist in Detecting Fraud in Accounting Data.”</span> <em>J. Forensic Account</em> 5 (January 2004).
</div>
<div id="ref-R-wordcloud" class="csl-entry" role="listitem">
Fellows, Ian. <em>Wordcloud: Word Clouds</em>, 2018. <a href="http://blog.fellstat.com/?cat=11">http://blog.fellstat.com/?cat=11</a>.
</div>
<div id="ref-R-janitor" class="csl-entry" role="listitem">
Firke, Sam. <em>Janitor: Simple Tools for Examining and Cleaning Dirty Data</em>, 2024. <a href="https://github.com/sfirke/janitor">https://github.com/sfirke/janitor</a>.
</div>
<div id="ref-car2019" class="csl-entry" role="listitem">
Fox, John, and Sanford Weisberg. <em>An <span>R</span> Companion to Applied Regression</em>. Third. Thousand Oaks <span>CA</span>: Sage, 2019. <a href="https://www.john-fox.ca/Companion/">https://www.john-fox.ca/Companion/</a>.
</div>
<div id="ref-R-car" class="csl-entry" role="listitem">
Fox, John, Sanford Weisberg, and Brad Price. <em>Car: Companion to Applied Regression</em>, 2026. <a href="https://github.com/bprice2652/car_repo">https://github.com/bprice2652/car_repo</a>.
</div>
<div id="ref-r-stringi" class="csl-entry" role="listitem">
Gagolewski, Marek. <em>Stringi: Fast and Portable Character String Processing in r</em>, 2021. <a href="https://stringi.gagolewski.com/">https://stringi.gagolewski.com/</a>.
</div>
<div id="ref-mcke" class="csl-entry" role="listitem">
Gardner, Everette S., and Ed. Mckenzie. <span>“Forecasting Trends in Time Series.”</span> <em>Management Science</em> 31, no. 10 (1985): 1237–46. <a href="https://doi.org/10.1287/mnsc.31.10.1237">https://doi.org/10.1287/mnsc.31.10.1237</a>.
</div>
<div id="ref-R-tidyxl" class="csl-entry" role="listitem">
Garmonsway, Duncan. <em>Tidyxl: Read Untidy Excel Files</em>, 2023. <a href="https://github.com/nacnudus/tidyxl">https://github.com/nacnudus/tidyxl</a>.
</div>
<div id="ref-R-unpivotr" class="csl-entry" role="listitem">
———. <em>Unpivotr: Unpivot Complex and Irregular Data Layouts</em>, 2024. <a href="https://github.com/nacnudus/unpivotr">https://github.com/nacnudus/unpivotr</a>.
</div>
<div id="ref-JSSv040i03" class="csl-entry" role="listitem">
Grolemund, Garrett, and Hadley Wickham. <span>“Dates and Times Made Easy with Lubridate.”</span> <em>Journal of Statistical Software</em> 40, no. 3 (2011): 1–25. <a href="https://doi.org/10.18637/jss.v040.i03">https://doi.org/10.18637/jss.v040.i03</a>.
</div>
<div id="ref-lubridate2011" class="csl-entry" role="listitem">
———. <span>“Dates and Times Made Easy with <span class="nocase">lubridate</span>.”</span> <em>Journal of Statistical Software</em> 40, no. 3 (2011): 1–25. <a href="https://www.jstatsoft.org/v40/i03/">https://www.jstatsoft.org/v40/i03/</a>.
</div>
<div id="ref-R-arules" class="csl-entry" role="listitem">
Hahsler, Michael, Christian Buchta, Bettina Gruen, and Kurt Hornik. <em>Arules: Mining Association Rules and Frequent Itemsets</em>, 2026. <a href="https://github.com/mhahsler/arules">https://github.com/mhahsler/arules</a>.
</div>
<div id="ref-arules2011" class="csl-entry" role="listitem">
Hahsler, Michael, Sudheer Chelluboina, Kurt Hornik, and Christian Buchta. <span>“The Arules r-Package Ecosystem: Analyzing Interesting Patterns from Large Transaction Datasets.”</span> <em>Journal of Machine Learning Research</em> 12 (2011): 1977–81. <a href="https://jmlr.csail.mit.edu/papers/v12/hahsler11a.html">https://jmlr.csail.mit.edu/papers/v12/hahsler11a.html</a>.
</div>
<div id="ref-arules2005" class="csl-entry" role="listitem">
Hahsler, Michael, Bettina Gruen, and Kurt Hornik. <span>“Arules – <span>A</span> Computational Environment for Mining Association Rules and Frequent Item Sets.”</span> <em>Journal of Statistical Software</em> 14, no. 15 (2005): 1–25. <a href="https://doi.org/10.18637/jss.v014.i15">https://doi.org/10.18637/jss.v014.i15</a>.
</div>
<div id="ref-R-dbscan" class="csl-entry" role="listitem">
Hahsler, Michael, and Matthew Piekenbrock. <em>Dbscan: Density-Based Spatial Clustering of Applications with Noise (DBSCAN) and Related Algorithms</em>, 2026. <a href="https://github.com/mhahsler/dbscan">https://github.com/mhahsler/dbscan</a>.
</div>
<div id="ref-dbscan2019" class="csl-entry" role="listitem">
Hahsler, Michael, Matthew Piekenbrock, and Derek Doran. <span>“<span class="nocase">dbscan</span>: Fast Density-Based Clustering with <span>R</span>.”</span> <em>Journal of Statistical Software</em> 91, no. 1 (2019): 1–30. <a href="https://doi.org/10.18637/jss.v091.i01">https://doi.org/10.18637/jss.v091.i01</a>.
</div>
<div id="ref-t_hill" class="csl-entry" role="listitem">
Hill, Theodore P. <span>“The Significant-Digit Phenomenon.”</span> <em>The American Mathematical Monthly</em> 102, no. 4 (1995): 322–27. <a href="http://www.jstor.org/stable/2974952">http://www.jstor.org/stable/2974952</a>.
</div>
<div id="ref-R-palmerpenguins" class="csl-entry" role="listitem">
Horst, Allison, Alison Hill, and Kristen Gorman. <em>Palmerpenguins: Palmer Archipelago (Antarctica) Penguin Data</em>, 2022. <a href="https://allisonhorst.github.io/palmerpenguins/">https://allisonhorst.github.io/palmerpenguins/</a>.
</div>
<div id="ref-phonics2018" class="csl-entry" role="listitem">
Howard, II, James P. <span>“Phonetic Algorithms in <span>R</span>.”</span> <em>Journal of Open Source Software</em> 3, no. 22 (2018): 480. <a href="https://doi.org/10.21105/joss.00480">https://doi.org/10.21105/joss.00480</a>.
</div>
<div id="ref-phonics2020" class="csl-entry" role="listitem">
———. <span>“Phonetic Spelling Algorithm Implementations for <span>R</span>.”</span> <em>Journal of Statistical Software</em> 95, no. 8 (2020): 1–21. <a href="https://doi.org/10.18637/jss.v095.i08">https://doi.org/10.18637/jss.v095.i08</a>.
</div>
<div id="ref-R-phonics" class="csl-entry" role="listitem">
Howard, James. <em>Phonics: Phonetic Spelling Algorithms</em>, 2026. <a href="https://phonics.jameshoward.us">https://phonics.jameshoward.us</a>.
</div>
<div id="ref-forecast2008" class="csl-entry" role="listitem">
Hyndman, Rob J, and Yeasmin Khandakar. <span>“Automatic Time Series Forecasting: The Forecast Package for <span>R</span>.”</span> <em>Journal of Statistical Software</em> 27, no. 3 (2008): 1–22. <a href="https://doi.org/10.18637/jss.v027.i03">https://doi.org/10.18637/jss.v027.i03</a>.
</div>
<div id="ref-R-forecast" class="csl-entry" role="listitem">
Hyndman, Rob, George Athanasopoulos, Christoph Bergmeir, Gabriel Caceres, Leanne Chhay, Kirill Kuroptev, Maximilian Mücke, et al. <em>Forecast: Forecasting Functions for Time Series and Linear Models</em>, 2026. <a href="https://pkg.robjhyndman.com/forecast/">https://pkg.robjhyndman.com/forecast/</a>.
</div>
<div id="ref-R-gt" class="csl-entry" role="listitem">
Iannone, Richard, Joe Cheng, Barret Schloerke, Shannon Haughton, Ellis Hughes, Alexandra Lauer, Romain François, JooYoung Seo, Ken Brevoort, and Olivier Roy. <em>Gt: Easily Create Presentation-Ready Display Tables</em>, 2026. <a href="https://gt.rstudio.com">https://gt.rstudio.com</a>.
</div>
<div id="ref-R-pointblank" class="csl-entry" role="listitem">
Iannone, Richard, Mauricio Vargas, and June Choe. <em>Pointblank: Data Validation and Organization of Metadata for Local and Remote Tables</em>, 2026. <a href="https://rstudio.github.io/pointblank/">https://rstudio.github.io/pointblank/</a>.
</div>
<div id="ref-10.2307/1390807" class="csl-entry" role="listitem">
Ihaka, Ross, and Robert Gentleman. <span>“R: A Language for Data Analysis and Graphics.”</span> <em>Journal of Computational and Graphical Statistics</em> 5, no. 3 (1996): 299–314. <a href="http://www.jstor.org/stable/1390807">http://www.jstor.org/stable/1390807</a>.
</div>
<div id="ref-R-colorspace" class="csl-entry" role="listitem">
Ihaka, Ross, Paul Murrell, Kurt Hornik, Jason C. Fisher, Reto Stauffer, Claus O. Wilke, Claire D. McWhite, and Achim Zeileis. <em>Colorspace: A Toolbox for Manipulating and Assessing Colors and Palettes</em>, 2025. <a href="https://colorspace.R-Forge.R-project.org/">https://colorspace.R-Forge.R-project.org/</a>.
</div>
<div id="ref-R-bupaR" class="csl-entry" role="listitem">
Janssenswillen, Gert. <em>bupaR: Business Process Analysis in r</em>, 2026. <a href="https://bupar.net/">https://bupar.net/</a>.
</div>
<div id="ref-R-edeaR" class="csl-entry" role="listitem">
———. <em>edeaR: Exploratory and Descriptive Event-Based Data Analysis</em>, 2026. <a href="https://bupar.net/">https://bupar.net/</a>.
</div>
<div id="ref-R-processcheckR" class="csl-entry" role="listitem">
———. <em>processcheckR: Rule-Based Conformance Checking of Business Process Event Data</em>, 2025. <a href="https://bupar.net/">https://bupar.net/</a>.
</div>
<div id="ref-R-processmapR" class="csl-entry" role="listitem">
———. <em>processmapR: Construct Process Maps Using Event Data</em>, 2026. <a href="https://bupar.net/">https://bupar.net/</a>.
</div>
<div id="ref-R-factoextra" class="csl-entry" role="listitem">
Kassambara, Alboukadel, and Fabian Mundt. <em>Factoextra: Extract and Visualize the Results of Multivariate Data Analyses</em>, 2026. <a href="https://github.com/kassambara/factoextra">https://github.com/kassambara/factoextra</a>.
</div>
<div id="ref-R-changepoint" class="csl-entry" role="listitem">
Killick, Rebecca. <em>Changepoint: Methods for Changepoint Detection</em>, 2024. <a href="https://github.com/rkillick/changepoint/">https://github.com/rkillick/changepoint/</a>.
</div>
<div id="ref-changepoint2014" class="csl-entry" role="listitem">
Killick, Rebecca, and Idris A. Eckley. <span>“<span class="nocase">changepoint</span>: An <span>R</span> Package for Changepoint Analysis.”</span> <em>Journal of Statistical Software</em> 58, no. 3 (2014): 1–19. <a href="https://www.jstatsoft.org/article/view/v058i03">https://www.jstatsoft.org/article/view/v058i03</a>.
</div>
<div id="ref-R-moderndive" class="csl-entry" role="listitem">
Kim, Albert Y., and Chester Ismay. <em>Moderndive: Tidyverse-Friendly Introductory Linear Regression</em>, 2026. <a href="https://moderndive.github.io/moderndive/">https://moderndive.github.io/moderndive/</a>.
</div>
<div id="ref-moderndive2021" class="csl-entry" role="listitem">
Kim, Albert Y., Chester Ismay, and Max Kuhn. <span>“Take a Moderndive into Introductory Linear Regression with r.”</span> <em>The Journal of Open Source Education</em> 4, no. 41, 115 (2021). <a href="https://doi.org/10.21105/jose.00115">https://doi.org/10.21105/jose.00115</a>.
</div>
<div id="ref-R-outliers" class="csl-entry" role="listitem">
Komsta, Lukasz. <em>Outliers: Tests for Outliers</em>, 2022. <a href="https://www.R-project.org">https://www.R-project.org</a>.
</div>
<div id="ref-performance2021" class="csl-entry" role="listitem">
Lüdecke, Daniel, Mattan S. Ben-Shachar, Indrajeet Patil, Philip Waggoner, and Dominique Makowski. <span>“<span class="nocase">performance</span>: An <span>R</span> Package for Assessment, Comparison and Testing of Statistical Models.”</span> <em>Journal of Open Source Software</em> 6, no. 60 (2021): 3139. <a href="https://doi.org/10.21105/joss.03139">https://doi.org/10.21105/joss.03139</a>.
</div>
<div id="ref-R-performance" class="csl-entry" role="listitem">
Lüdecke, Daniel, Dominique Makowski, Mattan S. Ben-Shachar, Indrajeet Patil, Philip Waggoner, Brenton M. Wiernik, and Rémi Thériault. <em>Performance: Assessment of Regression Models Performance</em>, 2026. <a href="https://easystats.github.io/performance/">https://easystats.github.io/performance/</a>.
</div>
<div id="ref-R-cluster" class="csl-entry" role="listitem">
Maechler, Martin, Peter Rousseeuw, Anja Struyf, and Mia Hubert. <em>Cluster: "Finding Groups in Data": Cluster Analysis Extended Rousseeuw Et Al.</em>, 2026. <a href="https://svn.r-project.org/R-packages/trunk/cluster/">https://svn.r-project.org/R-packages/trunk/cluster/</a>.
</div>
<div id="ref-R-rpart.plot" class="csl-entry" role="listitem">
Milborrow, Stephen. <em>Rpart.plot: Plot Rpart Models: An Enhanced Version of Plot.rpart</em>, 2026. <a href="http://www.milbo.org/rpart-plot/index.html">http://www.milbo.org/rpart-plot/index.html</a>.
</div>
<div id="ref-R-duckdb" class="csl-entry" role="listitem">
Mühleisen, Hannes, and Mark Raasveldt. <em>Duckdb: DBI Package for the DuckDB Database Management System</em>, 2026. <a href="https://r.duckdb.org/">https://r.duckdb.org/</a>.
</div>
<div id="ref-r-tibble" class="csl-entry" role="listitem">
Müller, Kirill, and Hadley Wickham. <em>Tibble: Simple Data Frames</em>, 2022. <a href="https://CRAN.R-project.org/package=tibble">https://CRAN.R-project.org/package=tibble</a>.
</div>
<div id="ref-R-tibble" class="csl-entry" role="listitem">
———. <em>Tibble: Simple Data Frames</em>, 2026. <a href="https://tibble.tidyverse.org/">https://tibble.tidyverse.org/</a>.
</div>
<div id="ref-R-RColorBrewer" class="csl-entry" role="listitem">
Neuwirth, Erich. <em>RColorBrewer: ColorBrewer Palettes</em>, 2022. <a href="https://doi.org/10.32614/CRAN.package.RColorBrewer">https://doi.org/10.32614/CRAN.package.RColorBrewer</a>.
</div>
<div id="ref-newcomb" class="csl-entry" role="listitem">
Newcomb, Simon. <span>“Note on the Frequency of Use of the Different Digits in Natural Numbers.”</span> <em>American Journal of Mathematics</em> 4, no. 1 (1881): 39–40. <a href="http://www.jstor.org/stable/2369148">http://www.jstor.org/stable/2369148</a>.
</div>
<div id="ref-nigrinifraud" class="csl-entry" role="listitem">
Nigrini, Mark J. <em>Benford’s Law Applications for Forensic Accounting, Auditing and Fraud Detection</em>. 1st ed. John Wiley; Sons, Ltd, 2012. <a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/9781119203094.ch5">https://onlinelibrary.wiley.com/doi/abs/10.1002/9781119203094.ch5</a>.
</div>
<div id="ref-article2007" class="csl-entry" role="listitem">
Nigrini, Mark, and Steven Miller. <span>“Benford’s Law Applied to Hydrology Data—Results and Relevance to Other Geophysical Data.”</span> <em>Mathematical Geology</em> 39 (September 2007): 469–90. <a href="https://doi.org/10.1007/s11004-007-9109-5">https://doi.org/10.1007/s11004-007-9109-5</a>.
</div>
<div id="ref-articlesec" class="csl-entry" role="listitem">
———. <span>“Data Diagnostics Using Second-Order Tests of Benford’s Law.”</span> <em>Auditing a Journal of Practice and Theory AUDITING J PRACT THEOR</em> 28 (November 2009). <a href="https://doi.org/10.2308/aud.2009.28.2.305">https://doi.org/10.2308/aud.2009.28.2.305</a>.
</div>
<div id="ref-article2009" class="csl-entry" role="listitem">
———. <span>“Data Diagnostics Using Second-Order Tests of Benford’s Law.”</span> <em>Auditing-a Journal of Practice and Theory - AUDITING-J PRACT THEOR</em> 28 (November 2009). <a href="https://doi.org/10.2308/aud.2009.28.2.305">https://doi.org/10.2308/aud.2009.28.2.305</a>.
</div>
<div id="ref-R-pdftools" class="csl-entry" role="listitem">
Ooms, Jeroen. <em>Pdftools: Text Extraction, Rendering and Converting of PDF Documents</em>, 2026. <a href="https://ropensci.r-universe.dev/pdftools">https://ropensci.r-universe.dev/pdftools</a>.
</div>
<div id="ref-R-writexl" class="csl-entry" role="listitem">
Ooms, Jeroen, and Bill Denney. <em>Writexl: Export Data Frames to Excel Xlsx Format</em>, 2026. <a href="https://ropensci.r-universe.dev/writexl">https://ropensci.r-universe.dev/writexl</a>.
</div>
<div id="ref-R-sf" class="csl-entry" role="listitem">
Pebesma, Edzer. <em>Sf: Simple Features for r</em>, 2026. <a href="https://r-spatial.github.io/sf/">https://r-spatial.github.io/sf/</a>.
</div>
<div id="ref-sf2018" class="csl-entry" role="listitem">
———. <span>“<span class="nocase">Simple Features for R: Standardized Support for Spatial Vector Data</span>.”</span> <em><span>The R Journal</span></em> 10, no. 1 (2018): 439–46. <a href="https://doi.org/10.32614/RJ-2018-009">https://doi.org/10.32614/RJ-2018-009</a>.
</div>
<div id="ref-sf2023" class="csl-entry" role="listitem">
Pebesma, Edzer, and Roger Bivand. <em><span class="nocase">Spatial Data Science: With applications in R</span></em>. <span>Chapman and Hall/CRC</span>, 2023. <a href="https://doi.org/10.1201/9780429459016">https://doi.org/10.1201/9780429459016</a>.
</div>
<div id="ref-R-ggraph" class="csl-entry" role="listitem">
Pedersen, Thomas Lin. <em>Ggraph: An Implementation of Grammar of Graphics for Graphs and Networks</em>, 2025. <a href="https://ggraph.data-imaginist.com">https://ggraph.data-imaginist.com</a>.
</div>
<div id="ref-R-patchwork" class="csl-entry" role="listitem">
———. <em>Patchwork: The Composer of Plots</em>, 2025. <a href="https://patchwork.data-imaginist.com">https://patchwork.data-imaginist.com</a>.
</div>
<div id="ref-R-PerformanceAnalytics" class="csl-entry" role="listitem">
Peterson, Brian G., and Peter Carl. <em>PerformanceAnalytics: Econometric Tools for Performance and Risk Analysis</em>, 2026. <a href="https://github.com/braverock/PerformanceAnalytics">https://github.com/braverock/PerformanceAnalytics</a>.
</div>
<div id="ref-pinkham" class="csl-entry" role="listitem">
Pinkham, Roger S. <span>“<span class="nocase">On the Distribution of First Significant Digits</span>.”</span> <em>The Annals of Mathematical Statistics</em> 32, no. 4 (1961): 1223–30. <a href="https://doi.org/10.1214/aoms/1177704862">https://doi.org/10.1214/aoms/1177704862</a>.
</div>
<div id="ref-R-base" class="csl-entry" role="listitem">
R Core Team. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing, 2025. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
<div id="ref-R-psych" class="csl-entry" role="listitem">
Revelle, William. <em>Psych: Procedures for Psychological, Psychometric, and Personality Research</em>, 2026. <a href="https://personality-project.org/r/psych/">https://personality-project.org/r/psych/</a>.
</div>
<div id="ref-R-nnet" class="csl-entry" role="listitem">
Ripley, Brian. <em>Nnet: Feed-Forward Neural Networks and Multinomial Log-Linear Models</em>, 2025. <a href="http://www.stats.ox.ac.uk/pub/MASS4/">http://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
<div id="ref-R-MASS" class="csl-entry" role="listitem">
Ripley, Brian, and Bill Venables. <em>MASS: Support Functions and Datasets for Venables and Ripley’s MASS</em>, 2025. <a href="http://www.stats.ox.ac.uk/pub/MASS4/">http://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
<div id="ref-R-broom" class="csl-entry" role="listitem">
Robinson, David, Alex Hayes, Simon Couch, and Emil Hvitfeldt. <em>Broom: Convert Statistical Objects into Tidy Tibbles</em>, 2026. <a href="https://broom.tidymodels.org/">https://broom.tidymodels.org/</a>.
</div>
<div id="ref-R-tidytext" class="csl-entry" role="listitem">
Robinson, David, and Julia Silge. <em>Tidytext: Text Mining Using Dplyr, Ggplot2, and Other Tidy Tools</em>, 2025. <a href="https://juliasilge.github.io/tidytext/">https://juliasilge.github.io/tidytext/</a>.
</div>
<div id="ref-R-openxlsx" class="csl-entry" role="listitem">
Schauberger, Philipp, and Alexander Walker. <em>Openxlsx: Read, Write and Edit Xlsx Files</em>, 2025. <a href="https://ycphs.github.io/openxlsx/index.html">https://ycphs.github.io/openxlsx/index.html</a>.
</div>
<div id="ref-R-GGally" class="csl-entry" role="listitem">
Schloerke, Barret, Di Cook, Joseph Larmarange, Francois Briatte, Moritz Marbach, Edwin Thoen, Amos Elberg, and Jason Crowley. <em>GGally: Extension to Ggplot2</em>, 2025. <a href="https://ggobi.github.io/ggally/">https://ggobi.github.io/ggally/</a>.
</div>
<div id="ref-tidytext2016" class="csl-entry" role="listitem">
Silge, Julia, and David Robinson. <span>“Tidytext: Text Mining and Analysis Using Tidy Data Principles in r.”</span> <em>JOSS</em> 1, no. 3 (2016). <a href="https://doi.org/10.21105/joss.00037">https://doi.org/10.21105/joss.00037</a>.
</div>
<div id="ref-R-ggrepel" class="csl-entry" role="listitem">
Slowikowski, Kamil. <em>Ggrepel: Automatically Position Non-Overlapping Text Labels with Ggplot2</em>, 2026. <a href="https://ggrepel.slowkow.com/">https://ggrepel.slowkow.com/</a>.
</div>
<div id="ref-R-lubridate" class="csl-entry" role="listitem">
Spinu, Vitalie, Garrett Grolemund, and Hadley Wickham. <em>Lubridate: Make Dealing with Dates a Little Easier</em>, 2026. <a href="https://lubridate.tidyverse.org">https://lubridate.tidyverse.org</a>.
</div>
<div id="ref-colorspace2009b" class="csl-entry" role="listitem">
Stauffer, Reto, Georg J. Mayr, Markus Dabernig, and Achim Zeileis. <span>“Somewhere over the Rainbow: How to Make Effective Use of Colors in Meteorological Visualizations.”</span> <em>Bulletin of the American Meteorological Society</em> 96, no. 2 (2009): 203–16. <a href="https://doi.org/10.1175/BAMS-D-13-00155.1">https://doi.org/10.1175/BAMS-D-13-00155.1</a>.
</div>
<div id="ref-R-rpart" class="csl-entry" role="listitem">
Therneau, Terry, and Beth Atkinson. <em>Rpart: Recursive Partitioning and Regression Trees</em>, 2025. <a href="https://github.com/bethatkinson/rpart">https://github.com/bethatkinson/rpart</a>.
</div>
<div id="ref-R-AnomalyDetection" class="csl-entry" role="listitem">
Vallis, Owen S., Jordan Hochenbaum, and Arun Kejariwal. <em>AnomalyDetection: Anomaly Detection Using Seasonal Hybrid Extreme Studentized Deviate Test</em>, 2014. <a href="https://github.com/twitter/AnomalyDetection">https://github.com/twitter/AnomalyDetection</a>.
</div>
<div id="ref-stringdist2014" class="csl-entry" role="listitem">
<span class="nocase">van der Loo, M. P. J.</span> <span>“The Stringdist Package for Approximate String Matching.”</span> <em>The <span>R</span> <span>J</span>ournal</em> 6 (2014): 111–22. <a href="https://journal.r-project.org/articles/RJ-2014-011/">https://journal.r-project.org/articles/RJ-2014-011/</a>.
</div>
<div id="ref-R-stringdist" class="csl-entry" role="listitem">
<span class="nocase">van der Loo, Mark</span>. <em>Stringdist: Approximate String Matching, Fuzzy Text Search, and String Distance Functions</em>, 2026. <a href="https://github.com/markvanderloo/stringdist">https://github.com/markvanderloo/stringdist</a>.
</div>
<div id="ref-validate2021" class="csl-entry" role="listitem">
<span class="nocase">van der Loo, Mark P. J., and Edwin de Jonge</span>. <span>“Data Validation Infrastructure for <span>R</span>.”</span> <em>Journal of Statistical Software</em> 97, no. 10 (2021): 1–31. <a href="https://doi.org/10.18637/jss.v097.i10">https://doi.org/10.18637/jss.v097.i10</a>.
</div>
<div id="ref-R-validate" class="csl-entry" role="listitem">
<span class="nocase">van der Loo, Mark, and Edwin de Jonge</span>. <em>Validate: Data Validation Infrastructure</em>, 2025. <a href="https://github.com/data-cleaning/validate">https://github.com/data-cleaning/validate</a>.
</div>
<div id="ref-MASS2002" class="csl-entry" role="listitem">
Venables, W. N., and B. D. Ripley. <em>Modern Applied Statistics with s</em>. Fourth. New York: Springer, 2002. <a href="https://www.stats.ox.ac.uk/pub/MASS4/">https://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
<div id="ref-nnet2002" class="csl-entry" role="listitem">
———. <em>Modern Applied Statistics with s</em>. Fourth. New York: Springer, 2002. <a href="https://www.stats.ox.ac.uk/pub/MASS4/">https://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
<div id="ref-R-skimr" class="csl-entry" role="listitem">
Waring, Elin, Michael Quinn, Amelia McNamara, Eduardo Arino de la Rubia, Hao Zhu, and Shannon Ellis. <em>Skimr: Compact and Flexible Summaries of Data</em>, 2026. <a href="https://docs.ropensci.org/skimr/">https://docs.ropensci.org/skimr/</a>.
</div>
<div id="ref-layered-grammar" class="csl-entry" role="listitem">
Wickham, Hadley. <span>“A Layered Grammar of Graphics.”</span> <em>Journal of Computational and Graphical Statistics</em> 19, no. 1 (2010): 3–28. <a href="https://doi.org/10.1198/jcgs.2009.07098">https://doi.org/10.1198/jcgs.2009.07098</a>.
</div>
<div id="ref-R-conflicted" class="csl-entry" role="listitem">
———. <em>Conflicted: An Alternative Conflict Resolution Strategy</em>, 2023. <a href="https://conflicted.r-lib.org/">https://conflicted.r-lib.org/</a>.
</div>
<div id="ref-R-forcats" class="csl-entry" role="listitem">
———. <em>Forcats: Tools for Working with Categorical Variables (Factors)</em>, 2025. <a href="https://forcats.tidyverse.org/">https://forcats.tidyverse.org/</a>.
</div>
<div id="ref-ggplot22016" class="csl-entry" role="listitem">
———. <em>Ggplot2: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York, 2016. <a href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>.
</div>
<div id="ref-JSSv021i12" class="csl-entry" role="listitem">
———. <span>“Reshaping Data with the Reshape Package.”</span> <em>Journal of Statistical Software</em> 21, no. 12 (2007): 1–20. <a href="https://doi.org/10.18637/jss.v021.i12">https://doi.org/10.18637/jss.v021.i12</a>.
</div>
<div id="ref-R-stringr" class="csl-entry" role="listitem">
———. <em>Stringr: Simple, Consistent Wrappers for Common String Operations</em>, 2025. <a href="https://stringr.tidyverse.org">https://stringr.tidyverse.org</a>.
</div>
<div id="ref-JSSv059i10" class="csl-entry" role="listitem">
———. <span>“Tidy Data.”</span> <em>Journal of Statistical Software</em> 59, no. 10 (2014): 1–23. <a href="https://doi.org/10.18637/jss.v059.i10">https://doi.org/10.18637/jss.v059.i10</a>.
</div>
<div id="ref-R-tidyverse" class="csl-entry" role="listitem">
———. <em>Tidyverse: Easily Install and Load the Tidyverse</em>, 2023. <a href="https://tidyverse.tidyverse.org">https://tidyverse.tidyverse.org</a>.
</div>
<div id="ref-tidyverse2019" class="csl-entry" role="listitem">
Wickham, Hadley, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D’Agostino McGowan, Romain François, Garrett Grolemund, et al. <span>“Welcome to the <span class="nocase">tidyverse</span>.”</span> <em>Journal of Open Source Software</em> 4, no. 43 (2019): 1686. <a href="https://doi.org/10.21105/joss.01686">https://doi.org/10.21105/joss.01686</a>.
</div>
<div id="ref-R-readxl" class="csl-entry" role="listitem">
Wickham, Hadley, and Jennifer Bryan. <em>Readxl: Read Excel Files</em>, 2025. <a href="https://readxl.tidyverse.org">https://readxl.tidyverse.org</a>.
</div>
<div id="ref-R-ggplot2" class="csl-entry" role="listitem">
<span class="nocase">Wickham, Hadley, Winston Chang, Lionel Henry, Thomas Lin Pedersen, Kohske Takahashi, Claus Wilke, Kara Woo, Hiroaki Yutani, Dewey Dunnington, and Teun van den Brand</span>. <em>Ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics</em>, 2026. <a href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>.
</div>
<div id="ref-R-dplyr" class="csl-entry" role="listitem">
Wickham, Hadley, Romain François, Lionel Henry, Kirill Müller, and Davis Vaughan. <em>Dplyr: A Grammar of Data Manipulation</em>, 2026. <a href="https://dplyr.tidyverse.org">https://dplyr.tidyverse.org</a>.
</div>
<div id="ref-R-dbplyr" class="csl-entry" role="listitem">
Wickham, Hadley, Maximilian Girlich, and Edgar Ruiz. <em>Dbplyr: A Dplyr Back End for Databases</em>, 2026. <a href="https://dbplyr.tidyverse.org/">https://dbplyr.tidyverse.org/</a>.
</div>
<div id="ref-R-purrr" class="csl-entry" role="listitem">
Wickham, Hadley, and Lionel Henry. <em>Purrr: Functional Programming Tools</em>, 2026. <a href="https://purrr.tidyverse.org/">https://purrr.tidyverse.org/</a>.
</div>
<div id="ref-R-readr" class="csl-entry" role="listitem">
Wickham, Hadley, Jim Hester, and Jennifer Bryan. <em>Readr: Read Rectangular Text Data</em>, 2026. <a href="https://readr.tidyverse.org">https://readr.tidyverse.org</a>.
</div>
<div id="ref-R-scales" class="csl-entry" role="listitem">
Wickham, Hadley, Thomas Lin Pedersen, and Dana Seidel. <em>Scales: Scale Functions for Visualization</em>, 2025. <a href="https://scales.r-lib.org">https://scales.r-lib.org</a>.
</div>
<div id="ref-R-tidyr" class="csl-entry" role="listitem">
Wickham, Hadley, Davis Vaughan, and Maximilian Girlich. <em>Tidyr: Tidy Messy Data</em>, 2025. <a href="https://tidyr.tidyverse.org">https://tidyr.tidyverse.org</a>.
</div>
<div id="ref-R-ranger" class="csl-entry" role="listitem">
Wright, Marvin N. <em>Ranger: A Fast Implementation of Random Forests</em>, 2026. <a href="https://imbs-hl.github.io/ranger/">https://imbs-hl.github.io/ranger/</a>.
</div>
<div id="ref-ranger2017" class="csl-entry" role="listitem">
Wright, Marvin N., and Andreas Ziegler. <span>“<span class="nocase">ranger</span>: A Fast Implementation of Random Forests for High Dimensional Data in <span>C++</span> and <span>R</span>.”</span> <em>Journal of Statistical Software</em> 77, no. 1 (2017): 1–17. <a href="https://doi.org/10.18637/jss.v077.i01">https://doi.org/10.18637/jss.v077.i01</a>.
</div>
<div id="ref-xie2015" class="csl-entry" role="listitem">
Xie, Yihui. <em>Dynamic Documents with <span>R</span> and Knitr</em>. 2nd ed. Boca Raton, Florida: Chapman; Hall/CRC, 2015. <a href="http://yihui.name/knitr/">http://yihui.name/knitr/</a>.
</div>
<div id="ref-knitr2015" class="csl-entry" role="listitem">
———. <em>Dynamic Documents with <span>R</span> and Knitr</em>. 2nd ed. Boca Raton, Florida: Chapman; Hall/CRC, 2015. <a href="https://yihui.org/knitr/">https://yihui.org/knitr/</a>.
</div>
<div id="ref-knitr2014" class="csl-entry" role="listitem">
———. <span>“Knitr: A Comprehensive Tool for Reproducible Research in <span>R</span>.”</span> In <em>Implementing Reproducible Computational Research</em>, edited by Victoria Stodden, Friedrich Leisch, and Roger D. Peng. Chapman; Hall/CRC, 2014.
</div>
<div id="ref-R-knitr" class="csl-entry" role="listitem">
———. <em>Knitr: A General-Purpose Package for Dynamic Report Generation in r</em>, 2025. <a href="https://yihui.org/knitr/">https://yihui.org/knitr/</a>.
</div>
<div id="ref-colorspace2020a" class="csl-entry" role="listitem">
Zeileis, Achim, Jason C. Fisher, Kurt Hornik, Ross Ihaka, Claire D. McWhite, Paul Murrell, Reto Stauffer, and Claus O. Wilke. <span>“<span class="nocase">colorspace</span>: A Toolbox for Manipulating and Assessing Colors and Palettes.”</span> <em>Journal of Statistical Software</em> 96, no. 1 (2020): 1–49. <a href="https://doi.org/10.18637/jss.v096.i01">https://doi.org/10.18637/jss.v096.i01</a>.
</div>
<div id="ref-zoo2005" class="csl-entry" role="listitem">
Zeileis, Achim, and Gabor Grothendieck. <span>“Zoo: S3 Infrastructure for Regular and Irregular Time Series.”</span> <em>Journal of Statistical Software</em> 14, no. 6 (2005): 1–27. <a href="https://doi.org/10.18637/jss.v014.i06">https://doi.org/10.18637/jss.v014.i06</a>.
</div>
<div id="ref-R-zoo" class="csl-entry" role="listitem">
Zeileis, Achim, Gabor Grothendieck, and Jeffrey A. Ryan. <em>Zoo: S3 Infrastructure for Regular and Irregular Time Series (z’s Ordered Observations)</em>, 2025. <a href="https://zoo.R-Forge.R-project.org/">https://zoo.R-Forge.R-project.org/</a>.
</div>
<div id="ref-colorspace2009a" class="csl-entry" role="listitem">
Zeileis, Achim, Kurt Hornik, and Paul Murrell. <span>“Escaping <span>RGB</span>land: Selecting Colors for Statistical Graphics.”</span> <em>Computational Statistics &amp; Data Analysis</em> 53, no. 9 (2009): 3259–70. <a href="https://doi.org/10.1016/j.csda.2008.11.033">https://doi.org/10.1016/j.csda.2008.11.033</a>.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/anilyayavar\.github\.io\/new-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./12-3Samp.html" class="pagination-link" aria-label="Random Sampling">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Random Sampling</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./part5-forensic.html" class="pagination-link" aria-label="Part V: Forensic Tests">
        <span class="nav-page-text">Part V: Forensic Tests</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Built with <a href="https://www.r-project.org">R</a> and <a href="https://quarto.org">Quarto</a></p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/anilyayavar/new-book/edit/master/12-3b-tests.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/anilyayavar/new-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>