<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="A practical guide to data analytics for auditors, using R and the tidyverse: reading and cleaning audit data, forensic tests, sampling, statistics, machine learning, text, network and geospatial analytics, and reproducible reports, with Indian audit examples throughout.">
<title>32&nbsp; Duplicate Detection – R for Audit Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./15-stringdist.html" rel="next">
<link href="./19-nigrini-tests.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-631496449bf32ff9b0bb69a6bfd9195d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-a64f2b92d8b4b45ab5f5d9261e8b8c9d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-631496449bf32ff9b0bb69a6bfd9195d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link rel="stylesheet" href="style.css">
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./part5-forensic.html">Part V: Forensic Tests</a></li><li class="breadcrumb-item"><a href="./20-duplicates.html"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Duplicate Detection</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R for Audit Analytics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/anilyayavar/new-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index-about-author.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About the Author</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how-to-use.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to Use This Book</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-Zero.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gearing Up</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part1-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part I: R Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Objects, Data Types and Data Structures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Subsets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Subsetting and Indexing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Functions and Operators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-functions-existing-and-useful-functions-in-base-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Useful Base R Functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-functions-pipes-in-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Pipes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-1conditionals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Conditions and Loops</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-1-functionalprog.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Functional Programming</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part2-data-ready.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part II: Getting Data Ready</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-2-workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Working with Files and Folders</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-1-reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Importing and Exporting Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-1-reading-data-cleaning-in-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Cleaning Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-1b-pdf-excel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data from PDFs and Messy Excel Files</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-2-merge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Combining Many Similar Files</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-1-dplyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Transforming Data with dplyr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-2-joins.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Joining Tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-tidyr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Reshaping Data with tidyr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-8Lubridate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Dates and Times</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-8b-duckdb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Large Data with DuckDB and data.table</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part3-text-fields.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part III: Working with Text Fields</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-1Stringr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Working with Strings in stringr</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-2Regex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Regular Expressions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-2Regex-regex-in-human-readble-format-using-rebu.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Readable Regular Expressions with rebus</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part4-explore-sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part IV: Exploring and Sampling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Charts in Base R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-1ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Charts with ggplot2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-2ggplot2-polish.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Polishing Charts for Audit Reports</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-3Factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Factors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-1Desc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-2stats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-3Samp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Random Sampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-3b-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Statistical Tests for Auditors</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part5-forensic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part V: Forensic Tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17a-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Rule-Based Validation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-Anamolous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Benford Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-nigrini-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Nigrini’s Tests for Unusual Amounts</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-duplicates.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Duplicate Detection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-stringdist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">String Similarity and Fuzzy Matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20b-record-linkage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Record Linkage</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-gaps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Gaps in Sequences</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21b-process-mining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Process Mining</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part6-risk-scoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part VI: Modelling and Risk Scoring</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-4Reg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-4Reg-multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Multiple Regression in Audit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-4b-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Logistic Regression for Risk Scoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-4c-trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Decision Trees</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-4d-forest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Random Forests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-DEA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Data Envelopment Analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part7-hidden-patterns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part VII: Finding Hidden Patterns</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-5PCA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Principal Component Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-6KMeans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Clustering with k-Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-7Apriori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Association Rules (Apriori)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-9ts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Time Series Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-anomaly.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Anomaly Detection</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part8-beyond-tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part VIII: Beyond Tables</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-4text.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Text Analytics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-4text-sentiment-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Sentiment Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-4text-visualising-text-analytics-through-wordc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Visualising Text</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Network.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Networks and Graph Theory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Network-applying-network-analysis-in-audit-fraud.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Network Analysis in Audit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-Rgeo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Maps</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-Rgeo-geo-coding-in-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Geocoding</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-Rgeo-reverse-geo-coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Reverse Geocoding</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./part9-reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Part IX: Reporting</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Reproducible Audit Reports</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./audit-questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Audit Question Finder</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98-datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Datasets Used in This Book</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">R Packages Used in This Book</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./97-colors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Colours in R</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#prerequisites" id="toc-prerequisites" class="nav-link active" data-scroll-target="#prerequisites"><span class="header-section-number">32.1</span> Prerequisites</a></li>
  <li><a href="#our-sample-data" id="toc-our-sample-data" class="nav-link" data-scroll-target="#our-sample-data"><span class="header-section-number">32.2</span> Our sample data</a></li>
  <li><a href="#what-do-we-mean-by-a-duplicate" id="toc-what-do-we-mean-by-a-duplicate" class="nav-link" data-scroll-target="#what-do-we-mean-by-a-duplicate"><span class="header-section-number">32.3</span> What do we mean by a duplicate?</a></li>
  <li><a href="#sec-dup-exact" id="toc-sec-dup-exact" class="nav-link" data-scroll-target="#sec-dup-exact"><span class="header-section-number">32.4</span> Exact duplicates</a></li>
  <li>
<a href="#same-same-same-test" id="toc-same-same-same-test" class="nav-link" data-scroll-target="#same-same-same-test"><span class="header-section-number">32.5</span> Same-Same-Same test</a>
  <ul class="collapse">
<li><a href="#how-much-money-is-involved" id="toc-how-much-money-is-involved" class="nav-link" data-scroll-target="#how-much-money-is-involved"><span class="header-section-number">32.5.1</span> How much money is involved?</a></li>
  </ul>
</li>
  <li>
<a href="#sec-dup-ssd" id="toc-sec-dup-ssd" class="nav-link" data-scroll-target="#sec-dup-ssd"><span class="header-section-number">32.6</span> Same-Same-Different test</a>
  <ul class="collapse">
<li><a href="#reducing-false-alarms-with-a-date-window" id="toc-reducing-false-alarms-with-a-date-window" class="nav-link" data-scroll-target="#reducing-false-alarms-with-a-date-window"><span class="header-section-number">32.6.1</span> Reducing false alarms with a date window</a></li>
  <li><a href="#other-combinations" id="toc-other-combinations" class="nav-link" data-scroll-target="#other-combinations"><span class="header-section-number">32.6.2</span> Other combinations</a></li>
  </ul>
</li>
  <li><a href="#sec-dup-hidden" id="toc-sec-dup-hidden" class="nav-link" data-scroll-target="#sec-dup-hidden"><span class="header-section-number">32.7</span> Hidden duplicates, and why cleaning matters</a></li>
  <li>
<a href="#sec-dup-fuzzy" id="toc-sec-dup-fuzzy" class="nav-link" data-scroll-target="#sec-dup-fuzzy"><span class="header-section-number">32.8</span> Fuzzy duplicates in names</a>
  <ul class="collapse">
<li><a href="#trying-other-similarity-measures" id="toc-trying-other-similarity-measures" class="nav-link" data-scroll-target="#trying-other-similarity-measures"><span class="header-section-number">32.8.1</span> Trying other similarity measures</a></li>
  <li><a href="#a-better-phonetic-measure-double-metaphone" id="toc-a-better-phonetic-measure-double-metaphone" class="nav-link" data-scroll-target="#a-better-phonetic-measure-double-metaphone"><span class="header-section-number">32.8.2</span> A better phonetic measure, Double Metaphone</a></li>
  </ul>
</li>
  <li><a href="#duplicates-across-more-than-one-id" id="toc-duplicates-across-more-than-one-id" class="nav-link" data-scroll-target="#duplicates-across-more-than-one-id"><span class="header-section-number">32.9</span> Duplicates across more than one ID</a></li>
  <li><a href="#a-suggested-workflow" id="toc-a-suggested-workflow" class="nav-link" data-scroll-target="#a-suggested-workflow"><span class="header-section-number">32.10</span> A suggested workflow</a></li>
  <li><a href="#summary-of-functions-used" id="toc-summary-of-functions-used" class="nav-link" data-scroll-target="#summary-of-functions-used"><span class="header-section-number">32.11</span> Summary of functions used</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/anilyayavar/new-book/edit/master/20-duplicates.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/anilyayavar/new-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./part5-forensic.html">Part V: Forensic Tests</a></li><li class="breadcrumb-item"><a href="./20-duplicates.html"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Duplicate Detection</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-dup" class="quarto-section-identifier"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Duplicate Detection</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>Duplicate detection is one of the oldest and most useful checks in audit. It is simple to understand. It is also simple to run. Yet it often gives the quickest results in a fraud or forensic audit.</p>
<p>A duplicate payment means money has gone out twice for the same thing. Sometimes it is an honest mistake. Sometimes it is not. In either case, it is a loss to the organisation, and the auditor must find it.</p>
<p>Duplicates may point to many kinds of problems. A few common ones are:</p>
<ul>
<li>
<strong>Double billing.</strong> A supplier submits the same invoice twice, and both get paid.</li>
<li>
<strong>Expense reimbursement fraud.</strong> An employee claims the same bill twice, perhaps once in each of two months.</li>
<li>
<strong>Payroll fraud.</strong> The same person appears twice on the pay roll, or a “ghost” employee shares the bank account of a real one.</li>
<li>
<strong>Beneficiary fraud.</strong> In welfare schemes, one person registers twice to get the benefit twice.</li>
<li>
<strong>Data entry errors and system glitches.</strong> A record is keyed in twice, or an interface between two systems posts the same transaction again.</li>
</ul>
<p>In this chapter we will learn how to find such duplicates in R. We will start with the simplest case, where two records are exactly the same. We will then move to cases where records are <em>almost</em> the same. These are harder to find, and they are usually the more interesting ones for an auditor.</p>
<section id="prerequisites" class="level2" data-number="32.1"><h2 data-number="32.1" class="anchored" data-anchor-id="prerequisites">
<span class="header-section-number">32.1</span> Prerequisites</h2>
<p>We will use three packages in this chapter. <code>tidyverse</code> gives us <code>dplyr</code> and <code>stringr</code>. <code>janitor</code> gives us a very handy function <code><a href="https://sfirke.github.io/janitor/reference/get_dupes.html">get_dupes()</a></code>. <code>stringdist</code> will help us find names which are similar but not identical. Later in the chapter, we will also use <code>fullmetaphone</code> to find names which sound alike. Its installation is explained in <a href="15-stringdist.html" class="quarto-xref"><span>Chapter 33</span></a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/sfirke/janitor">janitor</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/markvanderloo/stringdist">stringdist</a></span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section><section id="our-sample-data" class="level2" data-number="32.2"><h2 data-number="32.2" class="anchored" data-anchor-id="our-sample-data">
<span class="header-section-number">32.2</span> Our sample data</h2>
<p>To learn the tests, we need some data where we already know the answers. So let us create a small <em>payment register</em> of an imaginary office for the financial year 2024-25. It has about 170 payments made to 14 vendors. We have deliberately planted a few duplicates in it. Our job in this chapter is to find all of them using R.</p>
<p>The code to create the data is given below. New readers need not worry about this code right now. You may expand it later, once you are comfortable with <code>dplyr</code>.</p>
<div class="cell">
<details class="code-fold"><summary>Code to create the sample payment register</summary><div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">2025</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Vendor master</span></span>
<span><span class="va">vendors</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  vendor_id   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span><span class="op">(</span><span class="st">"V%03d"</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">14</span><span class="op">)</span>,</span>
<span>  vendor_name <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Sharma Traders"</span>, <span class="st">"Gupta Enterprises"</span>, <span class="st">"Bharat Stationers"</span>,</span>
<span>                  <span class="st">"Kaveri Suppliers"</span>, <span class="st">"Laxmi Electricals"</span>, <span class="st">"National Printers"</span>,</span>
<span>                  <span class="st">"Om Sai Caterers"</span>, <span class="st">"Patel Hardware"</span>, <span class="st">"Rajdhani Computers"</span>,</span>
<span>                  <span class="st">"Shree Ganesh Transport"</span>, <span class="st">"Ashok Estates"</span>, <span class="st">"Verma &amp; Sons"</span>,</span>
<span>                  <span class="st">"Sharma Trader's"</span>, <span class="st">"Guptha Enterprises"</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># 150 ordinary payments</span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">150</span></span>
<span><span class="va">payments</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  vendor_id    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="va">vendors</span><span class="op">$</span><span class="va">vendor_id</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span>, <span class="fl">12</span><span class="op">)</span><span class="op">]</span>, <span class="va">n</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>  invoice_no   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"INV-"</span>, <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">1000</span><span class="op">:</span><span class="fl">9999</span>, <span class="va">n</span><span class="op">)</span><span class="op">)</span>,</span>
<span>  invoice_date <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/as.Date.html">as.Date</a></span><span class="op">(</span><span class="st">"2024-04-01"</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">330</span>, <span class="va">n</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>  amount       <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">n</span>, <span class="fl">2000</span>, <span class="fl">200000</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Monthly office rent. Same amount every month, but genuine.</span></span>
<span><span class="va">rent</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  vendor_id    <span class="op">=</span> <span class="st">"V011"</span>,</span>
<span>  invoice_no   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"AE/RENT/"</span>, <span class="fl">1</span><span class="op">:</span><span class="fl">12</span><span class="op">)</span>,</span>
<span>  invoice_date <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/as.Date.html">as.Date</a></span><span class="op">(</span><span class="st">"2024-04-01"</span><span class="op">)</span>, by <span class="op">=</span> <span class="st">"month"</span>, length.out <span class="op">=</span> <span class="fl">12</span><span class="op">)</span>,</span>
<span>  amount       <span class="op">=</span> <span class="fl">45000</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Planted case 1. Invoices paid twice (one of them thrice).</span></span>
<span><span class="va">paid_again</span> <span class="op">&lt;-</span> <span class="va">payments</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">12</span>, <span class="fl">47</span>, <span class="fl">47</span>, <span class="fl">101</span><span class="op">)</span>, <span class="op">]</span></span>
<span></span>
<span><span class="co"># Planted case 2. Same invoice keyed in again with a slightly different number.</span></span>
<span><span class="va">retyped</span> <span class="op">&lt;-</span> <span class="va">payments</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">23</span>, <span class="fl">88</span><span class="op">)</span>, <span class="op">]</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>invoice_no <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_remove.html">str_remove</a></span><span class="op">(</span><span class="va">invoice_no</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="st">"-"</span><span class="op">)</span>,</span>
<span>                        <span class="fu"><a href="https://stringr.tidyverse.org/reference/case.html">str_to_lower</a></span><span class="op">(</span><span class="va">invoice_no</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Planted case 3. Same bill raised again with a suffix "A", two days later.</span></span>
<span><span class="va">suffixed</span> <span class="op">&lt;-</span> <span class="va">payments</span><span class="op">[</span><span class="fl">64</span>, <span class="op">]</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>invoice_no   <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="va">invoice_no</span>, <span class="st">"A"</span><span class="op">)</span>,</span>
<span>         invoice_date <span class="op">=</span> <span class="va">invoice_date</span> <span class="op">+</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Planted case 4. Same invoice paid to a look-alike vendor.</span></span>
<span><span class="va">lookalike</span> <span class="op">&lt;-</span> <span class="va">payments</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">vendor_id</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"V001"</span>, <span class="st">"V002"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">5</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>vendor_id <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">vendor_id</span> <span class="op">==</span> <span class="st">"V001"</span>, <span class="st">"V013"</span>, <span class="st">"V014"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">payments</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows</a></span><span class="op">(</span><span class="va">payments</span>, <span class="va">rent</span>, <span class="va">paid_again</span>, <span class="va">retyped</span>, <span class="va">suffixed</span>, <span class="va">lookalike</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>payment_date <span class="op">=</span> <span class="va">invoice_date</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">7</span><span class="op">:</span><span class="fl">45</span>, <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">payment_date</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>voucher_no <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sprintf.html">sprintf</a></span><span class="op">(</span><span class="st">"PV-%04d"</span>, <span class="fu"><a href="https://dplyr.tidyverse.org/reference/row_number.html">row_number</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">vendors</span>, by <span class="op">=</span> <span class="st">"vendor_id"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">voucher_no</span>, <span class="va">payment_date</span>, <span class="va">vendor_id</span>, <span class="va">vendor_name</span>,</span>
<span>         <span class="va">invoice_no</span>, <span class="va">invoice_date</span>, <span class="va">amount</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Planted case 5. Two rows repeated in the data extract itself.</span></span>
<span><span class="va">payments</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows</a></span><span class="op">(</span><span class="va">payments</span>, <span class="va">payments</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">30</span>, <span class="fl">90</span><span class="op">)</span>, <span class="op">]</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">voucher_no</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Let us have a look at the first few rows.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">payments</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  voucher_no payment_date vendor_id vendor_name   invoice_no invoice_date amount
  &lt;chr&gt;      &lt;date&gt;       &lt;chr&gt;     &lt;chr&gt;         &lt;chr&gt;      &lt;date&gt;        &lt;dbl&gt;
1 PV-0001    2024-04-18   V011      Ashok Estates AE/RENT/1  2024-04-01    45000
2 PV-0002    2024-04-21   V005      Laxmi Electr… INV-6900   2024-04-01   169386
3 PV-0003    2024-05-02   V009      Rajdhani Com… INV-5628   2024-04-20   171411
4 PV-0004    2024-05-07   V008      Patel Hardwa… INV-4836   2024-04-27    43171
5 PV-0005    2024-05-11   V009      Rajdhani Com… INV-2321   2024-04-19    97584
6 PV-0006    2024-05-13   V004      Kaveri Suppl… INV-9114   2024-04-27     2354</code></pre>
</div>
</div>
<p>Each row is one payment. The columns are:</p>
<ul>
<li>
<code>voucher_no</code> is the payment voucher number, given by the office.</li>
<li>
<code>payment_date</code> is the date on which payment was made.</li>
<li>
<code>vendor_id</code> and <code>vendor_name</code> tell us who was paid.</li>
<li>
<code>invoice_no</code> and <code>invoice_date</code> come from the bill submitted by the vendor.</li>
<li>
<code>amount</code> is the amount paid, in rupees.</li>
</ul></section><section id="what-do-we-mean-by-a-duplicate" class="level2" data-number="32.3"><h2 data-number="32.3" class="anchored" data-anchor-id="what-do-we-mean-by-a-duplicate">
<span class="header-section-number">32.3</span> What do we mean by a duplicate?</h2>
<p>This question looks simple. But it is the most important step of the whole exercise. Two records are “duplicates” only with respect to some columns, which we choose. These chosen columns are called the <strong>key</strong>.</p>
<p>Consider two payments to Sharma Traders. Both are for ₹ 25,000. Are they duplicates? We cannot say yet. If they also have the same invoice number, they almost certainly are. If the invoice numbers differ and the payments are a month apart, they are probably two genuine supplies.</p>
<p>So, before running any test, the auditor must decide the key. Forensic auditors commonly use the kinds of tests summarised in <a href="#tbl-duptests" class="quarto-xref">Table&nbsp;<span>32.1</span></a>.</p>
<div id="tbl-duptests" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-duptests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;32.1: Types of duplicate tests
</figcaption><div aria-describedby="tbl-duptests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 26%">
</colgroup>
<thead><tr class="header">
<th>Test</th>
<th>What matches</th>
<th>What differs</th>
<th>Typical finding</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Exact duplicate</td>
<td>Every column</td>
<td>Nothing</td>
<td>Same row repeated in data, or keyed in twice</td>
</tr>
<tr class="even">
<td>Same-Same-Same</td>
<td>All key columns, say vendor, invoice number and amount</td>
<td>Other columns like voucher number and date</td>
<td>Same invoice paid twice</td>
</tr>
<tr class="odd">
<td>Same-Same-Different</td>
<td>Two key columns, say vendor and amount</td>
<td>The third key column, say invoice number</td>
<td>Same bill re-submitted with a new or altered number</td>
</tr>
<tr class="even">
<td>Fuzzy duplicate</td>
<td>Values are <em>similar</em>, not equal</td>
<td>Spelling, case, punctuation</td>
<td>Look-alike vendors, retyped invoice numbers</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The names <em>Same-Same-Same</em> and <em>Same-Same-Different</em> are commonly used in forensic analytics literature. They are easy to remember. Three key columns are compared. The name tells us which of the three should match and which should not.</p>
</section><section id="sec-dup-exact" class="level2" data-number="32.4"><h2 data-number="32.4" class="anchored" data-anchor-id="sec-dup-exact">
<span class="header-section-number">32.4</span> Exact duplicates</h2>
<p>Let us begin with the easiest case. Are there rows which are the same in every column?</p>
<p>Base R has a function <code><a href="https://rdrr.io/r/base/duplicated.html">duplicated()</a></code>, which we met in <a href="04-functions-existing-and-useful-functions-in-base-r.html" class="quarto-xref"><span>Chapter 4</span></a>. It returns <code>TRUE</code> for every row which has already appeared earlier in the data. So summing it up gives the number of extra copies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">payments</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>There are two such rows. But <code><a href="https://rdrr.io/r/base/duplicated.html">duplicated()</a></code> marks only the <em>second</em> copy as <code>TRUE</code>. The first copy is marked <code>FALSE</code>. An auditor usually wants to see both copies side by side. For this, <code><a href="https://sfirke.github.io/janitor/reference/get_dupes.html">get_dupes()</a></code> from <code>janitor</code> is much more convenient. If we do not give it any column names, it uses all columns.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">payments</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://sfirke.github.io/janitor/reference/get_dupes.html">get_dupes</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 8
  voucher_no payment_date vendor_id vendor_name   invoice_no invoice_date amount
  &lt;chr&gt;      &lt;date&gt;       &lt;chr&gt;     &lt;chr&gt;         &lt;chr&gt;      &lt;date&gt;        &lt;dbl&gt;
1 PV-0030    2024-07-08   V007      Om Sai Cater… INV-2410   2024-06-07    41810
2 PV-0030    2024-07-08   V007      Om Sai Cater… INV-2410   2024-06-07    41810
3 PV-0090    2024-10-20   V001      Sharma Trade… INV-7755   2024-09-29   103923
4 PV-0090    2024-10-20   V001      Sharma Trade… INV-7755   2024-09-29   103923
# ℹ 1 more variable: dupe_count &lt;int&gt;</code></pre>
</div>
</div>
<p>The output shows each duplicate row along with a new column <code>dupe_count</code>. This column tells us how many times that row appears.</p>
<p>Note that even the voucher numbers are the same here. A real office would never issue the same voucher number twice. So these are not two payments. These are the <em>same</em> payment appearing twice in our data. This usually happens when data is exported from a system, or when two files are merged carelessly.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Audit tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Always check exact duplicates first, and <em>before</em> any other analysis. If the data itself has repeated rows, every total, average and count you calculate will be wrong. Ask the data owner why the rows are repeated. Do not just delete them silently. The answer may itself be an audit finding about the quality of the IT system.</p>
</div>
</div>
<p>Once we are satisfied with the reason, we may remove the repeated rows using <code><a href="https://dplyr.tidyverse.org/reference/distinct.html">dplyr::distinct()</a></code>. It keeps only the first copy of each row.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">payments</span> <span class="op">&lt;-</span> <span class="va">payments</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">payments</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 171</code></pre>
</div>
</div>
</section><section id="same-same-same-test" class="level2" data-number="32.5"><h2 data-number="32.5" class="anchored" data-anchor-id="same-same-same-test">
<span class="header-section-number">32.5</span> Same-Same-Same test</h2>
<p>Now let us look for the real problem. Has any invoice been paid more than once?</p>
<p>For this, our key will be three columns. These are <code>vendor_id</code>, <code>invoice_no</code> and <code>amount</code>. If all three match, the same bill has been paid again. Voucher numbers and payment dates will be different, of course, because these are two separate payments.</p>
<p>We just have to pass the key columns to <code><a href="https://sfirke.github.io/janitor/reference/get_dupes.html">get_dupes()</a></code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sss</span> <span class="op">&lt;-</span> <span class="va">payments</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://sfirke.github.io/janitor/reference/get_dupes.html">get_dupes</a></span><span class="op">(</span><span class="va">vendor_id</span>, <span class="va">invoice_no</span>, <span class="va">amount</span><span class="op">)</span></span>
<span></span>
<span><span class="va">sss</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 8
  vendor_id invoice_no amount dupe_count voucher_no payment_date vendor_name    
  &lt;chr&gt;     &lt;chr&gt;       &lt;dbl&gt;      &lt;int&gt; &lt;chr&gt;      &lt;date&gt;       &lt;chr&gt;          
1 V006      INV-3315    50572          3 PV-0069    2024-09-03   National Print…
2 V006      INV-3315    50572          3 PV-0071    2024-09-05   National Print…
3 V006      INV-3315    50572          3 PV-0079    2024-09-22   National Print…
4 V005      INV-2863   135555          2 PV-0087    2024-10-16   Laxmi Electric…
5 V005      INV-2863   135555          2 PV-0088    2024-10-19   Laxmi Electric…
6 V005      INV-4296   172125          2 PV-0032    2024-07-10   Laxmi Electric…
7 V005      INV-4296   172125          2 PV-0035    2024-07-15   Laxmi Electric…
# ℹ 1 more variable: invoice_date &lt;date&gt;</code></pre>
</div>
</div>
<p>We see three invoices here. One invoice of National Printers has been paid three times. Two invoices of Laxmi Electricals have been paid twice each. Look at the <code>payment_date</code> column. In one case the second payment was made only two days after the first. In real life, such cases need a closer look at the approval process.</p>
<section id="how-much-money-is-involved" class="level3" data-number="32.5.1"><h3 data-number="32.5.1" class="anchored" data-anchor-id="how-much-money-is-involved">
<span class="header-section-number">32.5.1</span> How much money is involved?</h3>
<p>An audit observation is incomplete without the money value. In each group, one payment was correct and the rest were extra. So the excess payment is the amount multiplied by one less than the number of times it was paid.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sss</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>    times_paid <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>    amount <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/nth.html">first</a></span><span class="op">(</span><span class="va">amount</span><span class="op">)</span>,</span>
<span>    excess_paid <span class="op">=</span> <span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/nth.html">first</a></span><span class="op">(</span><span class="va">amount</span><span class="op">)</span>,</span>
<span>    .by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">vendor_id</span>, <span class="va">invoice_no</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  vendor_id invoice_no times_paid amount excess_paid
  &lt;chr&gt;     &lt;chr&gt;           &lt;int&gt;  &lt;dbl&gt;       &lt;dbl&gt;
1 V006      INV-3315            3  50572      101144
2 V005      INV-2863            2 135555      135555
3 V005      INV-4296            2 172125      172125</code></pre>
</div>
</div>
<p>We may add a further <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> to get the grand total. That total is the figure which goes into the audit observation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sss</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>excess_paid <span class="op">=</span> <span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span> <span class="op">-</span> <span class="fl">1</span><span class="op">)</span> <span class="op">*</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/nth.html">first</a></span><span class="op">(</span><span class="va">amount</span><span class="op">)</span>, .by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">vendor_id</span>, <span class="va">invoice_no</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>total_excess <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">excess_paid</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  total_excess
         &lt;dbl&gt;
1       408824</code></pre>
</div>
</div>
<p>So, in our small data, ₹ 4,08,824 has been paid in excess on just three invoices.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Choosing the key wisely
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why did we not use <code>invoice_date</code> in the key? We could have. But dates are often entered differently by different clerks, so adding more columns to the key can make us <em>miss</em> duplicates. On the other hand, too few columns produce too many false alarms. Start with a small key. Then add columns if the output is too long to examine.</p>
</div>
</div>
</section></section><section id="sec-dup-ssd" class="level2" data-number="32.6"><h2 data-number="32.6" class="anchored" data-anchor-id="sec-dup-ssd">
<span class="header-section-number">32.6</span> Same-Same-Different test</h2>
<p>A clever fraudster knows that most accounting software rejects an invoice number already entered for a vendor. So they change the invoice number a little. They may add a suffix, or change one digit. The Same-Same-Same test above will not catch this.</p>
<p>This is where the Same-Same-Different test helps. Here we look for records where the <strong>vendor</strong> and the <strong>amount</strong> are the same, but the <strong>invoice number is different</strong>.</p>
<p>In <code>dplyr</code>, we can do this with <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> and its <code>.by</code> argument, which we learnt in <a href="10-1-dplyr.html" class="quarto-xref"><span>Chapter 13</span></a>. Inside each group of vendor and amount, we keep the group only if it has more than one distinct invoice number. The function <code><a href="https://dplyr.tidyverse.org/reference/n_distinct.html">n_distinct()</a></code> counts the distinct values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ssd</span> <span class="op">&lt;-</span> <span class="va">payments</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/n_distinct.html">n_distinct</a></span><span class="op">(</span><span class="va">invoice_no</span><span class="op">)</span> <span class="op">&gt;</span> <span class="fl">1</span>, .by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">vendor_id</span>, <span class="va">amount</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">vendor_id</span>, <span class="va">amount</span>, <span class="va">invoice_date</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ssd</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">voucher_no</span>, <span class="va">vendor_name</span>, <span class="va">invoice_no</span>, <span class="va">invoice_date</span>, <span class="va">amount</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 5
   voucher_no vendor_name        invoice_no invoice_date amount
   &lt;chr&gt;      &lt;chr&gt;              &lt;chr&gt;      &lt;date&gt;        &lt;dbl&gt;
 1 PV-0139    Gupta Enterprises  INV-9665   2025-01-10    29117
 2 PV-0155    Gupta Enterprises  INV9665    2025-01-10    29117
 3 PV-0160    Rajdhani Computers INV-8850   2025-02-15    93149
 4 PV-0171    Rajdhani Computers INV-8850A  2025-02-17    93149
 5 PV-0066    Rajdhani Computers inv-3601   2024-08-14   127872
 6 PV-0077    Rajdhani Computers INV-3601   2024-08-14   127872
 7 PV-0001    Ashok Estates      AE/RENT/1  2024-04-01    45000
 8 PV-0008    Ashok Estates      AE/RENT/2  2024-05-01    45000
 9 PV-0034    Ashok Estates      AE/RENT/3  2024-06-01    45000
10 PV-0047    Ashok Estates      AE/RENT/4  2024-07-01    45000
11 PV-0058    Ashok Estates      AE/RENT/5  2024-08-01    45000
12 PV-0078    Ashok Estates      AE/RENT/6  2024-09-01    45000
13 PV-0099    Ashok Estates      AE/RENT/7  2024-10-01    45000
14 PV-0116    Ashok Estates      AE/RENT/8  2024-11-01    45000
15 PV-0133    Ashok Estates      AE/RENT/9  2024-12-01    45000
16 PV-0152    Ashok Estates      AE/RENT/10 2025-01-01    45000
17 PV-0149    Ashok Estates      AE/RENT/11 2025-02-01    45000
18 PV-0169    Ashok Estates      AE/RENT/12 2025-03-01    45000</code></pre>
</div>
</div>
<p>Let us read this output carefully, group by group.</p>
<ol type="1">
<li>
<strong>Gupta Enterprises, ₹ 29,117.</strong> Invoice numbers are <code>INV-9665</code> and <code>INV9665</code>. Only the hyphen is missing. This is clearly the same invoice entered again.</li>
<li>
<strong>Rajdhani Computers, ₹ 93,149.</strong> Invoice numbers are <code>INV-8850</code> and <code>INV-8850A</code>, dated two days apart. Adding a suffix like “A” is a classic way to get a bill paid twice. This needs to be examined with the original documents.</li>
<li>
<strong>Rajdhani Computers, ₹ 1,27,872.</strong> Invoice numbers are <code>inv-3601</code> and <code>INV-3601</code>. Only the case differs. Again the same invoice.</li>
<li>
<strong>Ashok Estates, ₹ 45,000.</strong> Twelve invoices, one for each month. This is the monthly rent of the office building. It is <em>not</em> a duplicate. The same amount is genuinely paid every month.</li>
</ol>
<p>So the test has found the real problems. But it has also raised one <strong>false alarm</strong>. This is normal. Every duplicate test produces some false alarms. The auditor’s job is to reduce them sensibly and then examine the rest.</p>
<section id="reducing-false-alarms-with-a-date-window" class="level3" data-number="32.6.1"><h3 data-number="32.6.1" class="anchored" data-anchor-id="reducing-false-alarms-with-a-date-window">
<span class="header-section-number">32.6.1</span> Reducing false alarms with a date window</h3>
<p>Rent, salary, annual maintenance charges and similar payments repeat by their very nature. But they repeat after a gap, usually a month or more. A bill re-submitted for double payment usually comes within a few days or weeks of the original.</p>
<p>So let us also calculate how many days have passed since the previous invoice of the same vendor and amount. The function <code><a href="https://dplyr.tidyverse.org/reference/lead-lag.html">lag()</a></code> gives us the previous value within each group.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ssd</span> <span class="op">&lt;-</span> <span class="va">ssd</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>days_since_previous <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">invoice_date</span> <span class="op">-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/lead-lag.html">lag</a></span><span class="op">(</span><span class="va">invoice_date</span><span class="op">)</span><span class="op">)</span>,</span>
<span>         .by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">vendor_id</span>, <span class="va">amount</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ssd</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">vendor_name</span>, <span class="va">invoice_no</span>, <span class="va">invoice_date</span>, <span class="va">amount</span>, <span class="va">days_since_previous</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 5
   vendor_name        invoice_no invoice_date amount days_since_previous
   &lt;chr&gt;              &lt;chr&gt;      &lt;date&gt;        &lt;dbl&gt;               &lt;dbl&gt;
 1 Gupta Enterprises  INV-9665   2025-01-10    29117                  NA
 2 Gupta Enterprises  INV9665    2025-01-10    29117                   0
 3 Rajdhani Computers INV-8850   2025-02-15    93149                  NA
 4 Rajdhani Computers INV-8850A  2025-02-17    93149                   2
 5 Rajdhani Computers inv-3601   2024-08-14   127872                  NA
 6 Rajdhani Computers INV-3601   2024-08-14   127872                   0
 7 Ashok Estates      AE/RENT/1  2024-04-01    45000                  NA
 8 Ashok Estates      AE/RENT/2  2024-05-01    45000                  30
 9 Ashok Estates      AE/RENT/3  2024-06-01    45000                  31
10 Ashok Estates      AE/RENT/4  2024-07-01    45000                  30
11 Ashok Estates      AE/RENT/5  2024-08-01    45000                  31
12 Ashok Estates      AE/RENT/6  2024-09-01    45000                  31
13 Ashok Estates      AE/RENT/7  2024-10-01    45000                  30
14 Ashok Estates      AE/RENT/8  2024-11-01    45000                  31
15 Ashok Estates      AE/RENT/9  2024-12-01    45000                  30
16 Ashok Estates      AE/RENT/10 2025-01-01    45000                  31
17 Ashok Estates      AE/RENT/11 2025-02-01    45000                  31
18 Ashok Estates      AE/RENT/12 2025-03-01    45000                  28</code></pre>
</div>
</div>
<p>For rent, the gap is around 30 days each time. For the suspicious groups, the gap is zero or two days. Now we keep only those groups where some invoice came within, say, 15 days of the previous one.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ssd</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/any.html">any</a></span><span class="op">(</span><span class="va">days_since_previous</span> <span class="op">&lt;=</span> <span class="fl">15</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>, .by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">vendor_id</span>, <span class="va">amount</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">voucher_no</span>, <span class="va">vendor_name</span>, <span class="va">invoice_no</span>, <span class="va">invoice_date</span>, <span class="va">amount</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  voucher_no vendor_name        invoice_no invoice_date amount
  &lt;chr&gt;      &lt;chr&gt;              &lt;chr&gt;      &lt;date&gt;        &lt;dbl&gt;
1 PV-0139    Gupta Enterprises  INV-9665   2025-01-10    29117
2 PV-0155    Gupta Enterprises  INV9665    2025-01-10    29117
3 PV-0160    Rajdhani Computers INV-8850   2025-02-15    93149
4 PV-0171    Rajdhani Computers INV-8850A  2025-02-17    93149
5 PV-0066    Rajdhani Computers inv-3601   2024-08-14   127872
6 PV-0077    Rajdhani Computers INV-3601   2024-08-14   127872</code></pre>
</div>
</div>
<p>The rent payments are gone. Only the three suspicious groups remain.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The window of 15 days is only an example. Choose it according to the business. A fortnightly payment would need a shorter window. A fraudster who knows about this test may also wait for a few weeks before re-submitting the bill. So treat the date window as a way to <em>rank</em> cases for examination, not as a final rule.</p>
</div>
</div>
</section><section id="other-combinations" class="level3" data-number="32.6.2"><h3 data-number="32.6.2" class="anchored" data-anchor-id="other-combinations">
<span class="header-section-number">32.6.2</span> Other combinations</h3>
<p>The Same-Same-Different idea works with any combination of columns. We only have to decide which two should match and which one should differ. For example, let us look for the same invoice number and amount, but paid to <strong>different vendors</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">payments</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/n_distinct.html">n_distinct</a></span><span class="op">(</span><span class="va">vendor_id</span><span class="op">)</span> <span class="op">&gt;</span> <span class="fl">1</span>, .by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">invoice_no</span>, <span class="va">amount</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">invoice_no</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">voucher_no</span>, <span class="va">vendor_id</span>, <span class="va">vendor_name</span>, <span class="va">invoice_no</span>, <span class="va">amount</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  voucher_no vendor_id vendor_name        invoice_no amount
  &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;              &lt;chr&gt;       &lt;dbl&gt;
1 PV-0111    V002      Gupta Enterprises  INV-8297    29819
2 PV-0121    V014      Guptha Enterprises INV-8297    29819
3 PV-0097    V013      Sharma Trader's    INV-8564    93897
4 PV-0100    V001      Sharma Traders     INV-8564    93897</code></pre>
</div>
</div>
<p>This is an interesting result. An invoice of <em>Sharma Traders</em> has also been paid to <em>Sharma Trader’s</em>. An invoice of <em>Gupta Enterprises</em> has also been paid to <em>Guptha Enterprises</em>. These look-alike names have different vendor codes. This is a serious red flag. We will come back to it in <a href="#sec-dup-fuzzy" class="quarto-xref"><span>Section 32.8</span></a>.</p>
<p>A few other useful combinations are given in <a href="#tbl-ssdmore" class="quarto-xref">Table&nbsp;<span>32.2</span></a>.</p>
<div id="tbl-ssdmore" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ssdmore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;32.2: Some other Same-Same-Different combinations
</figcaption><div aria-describedby="tbl-ssdmore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 34%">
</colgroup>
<thead><tr class="header">
<th>Same</th>
<th>Same</th>
<th>Different</th>
<th>What it may reveal</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Employee</td>
<td>Amount</td>
<td>Claim number</td>
<td>Same medical or travel bill claimed twice</td>
</tr>
<tr class="even">
<td>Bank account</td>
<td>Scheme</td>
<td>Beneficiary ID</td>
<td>One person drawing benefit under two IDs</td>
</tr>
<tr class="odd">
<td>Bank account</td>
<td>Pay month</td>
<td>Employee ID</td>
<td>Ghost employee sharing a real employee’s account</td>
</tr>
<tr class="even">
<td>Vendor</td>
<td>Invoice number</td>
<td>Amount</td>
<td>Invoice amount altered after first payment</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section></section><section id="sec-dup-hidden" class="level2" data-number="32.7"><h2 data-number="32.7" class="anchored" data-anchor-id="sec-dup-hidden">
<span class="header-section-number">32.7</span> Hidden duplicates, and why cleaning matters</h2>
<p>Look again at the groups found by the Same-Same-Different test. <code>INV-9665</code> and <code>INV9665</code> are the same invoice. So are <code>inv-3601</code> and <code>INV-3601</code>. But the Same-Same-Same test missed them, because to a computer these strings are different.</p>
<p>This teaches us an important lesson. <strong>Clean the key columns before testing for duplicates.</strong> For invoice numbers, a simple cleaning would be to</p>
<ul>
<li>convert everything to upper case, and</li>
<li>remove spaces, hyphens, slashes and other punctuation.</li>
</ul>
<p>We learnt the required <code>stringr</code> functions in <a href="14-1Stringr.html" class="quarto-xref"><span>Chapter 18</span></a>. The regular expression <code>[^A-Z0-9]</code> means “any character which is not a capital letter or a digit”. Removing all such characters leaves only letters and digits.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">payments</span> <span class="op">&lt;-</span> <span class="va">payments</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>invoice_clean <span class="op">=</span> <span class="va">invoice_no</span> <span class="op">|&gt;</span></span>
<span>           <span class="fu"><a href="https://stringr.tidyverse.org/reference/case.html">str_to_upper</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>           <span class="fu"><a href="https://stringr.tidyverse.org/reference/str_remove.html">str_remove_all</a></span><span class="op">(</span><span class="st">"[^A-Z0-9]"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">payments</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://sfirke.github.io/janitor/reference/get_dupes.html">get_dupes</a></span><span class="op">(</span><span class="va">vendor_id</span>, <span class="va">invoice_clean</span>, <span class="va">amount</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">vendor_id</span>, <span class="va">invoice_no</span>, <span class="va">invoice_clean</span>, <span class="va">amount</span>, <span class="va">dupe_count</span>, <span class="va">voucher_no</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 6
   vendor_id invoice_no invoice_clean amount dupe_count voucher_no
   &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt;      &lt;int&gt; &lt;chr&gt;     
 1 V006      INV-3315   INV3315        50572          3 PV-0069   
 2 V006      INV-3315   INV3315        50572          3 PV-0071   
 3 V006      INV-3315   INV3315        50572          3 PV-0079   
 4 V002      INV-9665   INV9665        29117          2 PV-0139   
 5 V002      INV9665    INV9665        29117          2 PV-0155   
 6 V005      INV-2863   INV2863       135555          2 PV-0087   
 7 V005      INV-2863   INV2863       135555          2 PV-0088   
 8 V005      INV-4296   INV4296       172125          2 PV-0032   
 9 V005      INV-4296   INV4296       172125          2 PV-0035   
10 V009      inv-3601   INV3601       127872          2 PV-0066   
11 V009      INV-3601   INV3601       127872          2 PV-0077   </code></pre>
</div>
</div>
<p>Now the Same-Same-Same test finds five invoices instead of three. The two retyped invoices have been caught as well.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Audit tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Similar cleaning applies to other key columns too. Remove spaces from PAN and bank account numbers. Remove leading zeros where the system may or may not store them. Convert names to one case. A few minutes spent on cleaning can bring out duplicates that would otherwise stay hidden.</p>
</div>
</div>
</section><section id="sec-dup-fuzzy" class="level2" data-number="32.8"><h2 data-number="32.8" class="anchored" data-anchor-id="sec-dup-fuzzy">
<span class="header-section-number">32.8</span> Fuzzy duplicates in names</h2>
<p>Our last test found two invoices paid to look-alike vendors. Such vendors are often the root of the problem. A fictitious vendor is created with a name very close to a genuine one. Bills of the genuine vendor are then paid again, to the fictitious one. A casual reader of the payment register will not notice the difference.</p>
<p>Cleaning alone cannot catch these. <em>Sharma Traders</em> and <em>Sharma Trader’s</em> differ by an apostrophe. <em>Gupta</em> and <em>Guptha</em> differ by one letter. We need a way to measure how <em>similar</em> two names are. <a href="15-stringdist.html" class="quarto-xref"><span>Chapter 33</span></a>, which follows this chapter, explains several such measures in detail. Here we will use the Jaro-Winkler distance. It is <code>0</code> for identical strings and close to <code>1</code> for completely different ones.</p>
<p>The idea is simple. We compare every vendor name in the vendor master with every other vendor name. Then we look at the pairs with the smallest distance.</p>
<p><strong>Step-1:</strong> Make all possible pairs of vendors. We do this by joining the <code>vendors</code> table with itself. But we do not want a vendor paired with itself. We also do not want each pair twice, once as (A, B) and again as (B, A). So we join each vendor only with those vendors whose ID is <em>greater</em> than its own. This is an inequality join, which we learnt in <a href="10-2-joins.html#sec-nonequi" class="quarto-xref"><span>Section 14.5</span></a>. The <code>suffix</code> argument tells R how to name the columns coming from the two copies of the table.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">vendor_pairs</span> <span class="op">&lt;-</span> <span class="va">vendors</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">inner_join</a></span><span class="op">(</span><span class="va">vendors</span>, by <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/join_by.html">join_by</a></span><span class="op">(</span><span class="va">vendor_id</span> <span class="op">&lt;</span> <span class="va">vendor_id</span><span class="op">)</span>, suffix <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"_1"</span>, <span class="st">"_2"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">vendor_pairs</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 91</code></pre>
</div>
</div>
<p>With 14 vendors, we get 13 + 12 + … + 1 = 91 pairs.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Why not <code><a href="https://dplyr.tidyverse.org/reference/cross_join.html">cross_join()</a></code>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Another way is to make <em>every</em> combination using <code><a href="https://dplyr.tidyverse.org/reference/cross_join.html">cross_join()</a></code>, and then keep the required pairs with <code>filter(vendor_id_1 &lt; vendor_id_2)</code>. The result is the same. But <code><a href="https://dplyr.tidyverse.org/reference/cross_join.html">cross_join()</a></code> first builds the full table of n × n rows, and then throws away more than half of it. The inequality join builds only the pairs we need. In a test with 6,000 vendors, the inequality join took less than a second, while <code><a href="https://dplyr.tidyverse.org/reference/cross_join.html">cross_join()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> took about 11 seconds and needed more than 1 GB of memory along the way.</p>
</div>
</div>
<p><strong>Step-2:</strong> Calculate the distance between the two names in each pair. We convert both names to lower case first, as the measure is case sensitive.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">vendor_pairs</span> <span class="op">&lt;-</span> <span class="va">vendor_pairs</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>jw_distance <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/stringdist/man/stringdist.html">stringdist</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/chartr.html">tolower</a></span><span class="op">(</span><span class="va">vendor_name_1</span><span class="op">)</span>,</span>
<span>                                  <span class="fu"><a href="https://rdrr.io/r/base/chartr.html">tolower</a></span><span class="op">(</span><span class="va">vendor_name_2</span><span class="op">)</span>,</span>
<span>                                  method <span class="op">=</span> <span class="st">"jw"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Step-3:</strong> Sort the pairs by distance and look at the closest ones.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">vendor_pairs</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">jw_distance</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fl">5</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  vendor_id_1 vendor_name_1     vendor_id_2 vendor_name_2      jw_distance
  &lt;chr&gt;       &lt;chr&gt;             &lt;chr&gt;       &lt;chr&gt;                    &lt;dbl&gt;
1 V002        Gupta Enterprises V014        Guptha Enterprises      0.0185
2 V001        Sharma Traders    V013        Sharma Trader's         0.0222
3 V003        Bharat Stationers V009        Rajdhani Computers      0.292 
4 V001        Sharma Traders    V007        Om Sai Caterers         0.306 
5 V002        Gupta Enterprises V004        Kaveri Suppliers        0.306 </code></pre>
</div>
</div>
<p>The first two pairs stand out clearly. Their distance is about 0.02. The next pair is already at about 0.29, and those names have nothing in common. So, in this data, a cut-off of say 0.1 separates suspicious pairs from the rest.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">vendor_pairs</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">jw_distance</span> <span class="op">&lt;</span> <span class="fl">0.1</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  vendor_id_1 vendor_name_1     vendor_id_2 vendor_name_2      jw_distance
  &lt;chr&gt;       &lt;chr&gt;             &lt;chr&gt;       &lt;chr&gt;                    &lt;dbl&gt;
1 V001        Sharma Traders    V013        Sharma Trader's         0.0222
2 V002        Gupta Enterprises V014        Guptha Enterprises      0.0185</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How to choose the cut-off?
</div>
</div>
<div class="callout-body-container callout-body">
<p>There is no fixed rule. Sort the pairs by distance and read down the list. You will usually find a point after which the pairs stop looking alike. Use that point as the cut-off for this data. With large vendor masters, also compare other fields like PAN, GSTIN, bank account, address and mobile number. Two vendors with different names but the same bank account are even more suspicious than look-alike names.</p>
</div>
</div>
<section id="trying-other-similarity-measures" class="level3" data-number="32.8.1"><h3 data-number="32.8.1" class="anchored" data-anchor-id="trying-other-similarity-measures">
<span class="header-section-number">32.8.1</span> Trying other similarity measures</h3>
<p>Jaro-Winkler is not the only choice. <a href="15-stringdist.html" class="quarto-xref"><span>Chapter 33</span></a> explains several other measures. These include Levenshtein distance, Q-grams and Soundex. All of them are available in the same <code><a href="https://rdrr.io/pkg/stringdist/man/stringdist.html">stringdist()</a></code> function. We only change the <code>method</code> argument. Let us calculate a few of them on our vendor pairs and compare.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">vendor_pairs</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    name_1  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/chartr.html">tolower</a></span><span class="op">(</span><span class="va">vendor_name_1</span><span class="op">)</span>,</span>
<span>    name_2  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/chartr.html">tolower</a></span><span class="op">(</span><span class="va">vendor_name_2</span><span class="op">)</span>,</span>
<span>    lv      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/stringdist/man/stringdist.html">stringdist</a></span><span class="op">(</span><span class="va">name_1</span>, <span class="va">name_2</span>, method <span class="op">=</span> <span class="st">"lv"</span><span class="op">)</span>,</span>
<span>    jw      <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/stringdist/man/stringdist.html">stringdist</a></span><span class="op">(</span><span class="va">name_1</span>, <span class="va">name_2</span>, method <span class="op">=</span> <span class="st">"jw"</span><span class="op">)</span>,</span>
<span>    qgram_3 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/stringdist/man/stringdist.html">stringdist</a></span><span class="op">(</span><span class="va">name_1</span>, <span class="va">name_2</span>, method <span class="op">=</span> <span class="st">"qgram"</span>, q <span class="op">=</span> <span class="fl">3</span><span class="op">)</span>,</span>
<span>    soundex <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/stringdist/man/stringdist.html">stringdist</a></span><span class="op">(</span><span class="va">name_1</span>, <span class="va">name_2</span>, method <span class="op">=</span> <span class="st">"soundex"</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">jw</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">vendor_name_1</span>, <span class="va">vendor_name_2</span>, <span class="va">lv</span>, <span class="va">jw</span>, <span class="va">qgram_3</span>, <span class="va">soundex</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fl">5</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  vendor_name_1     vendor_name_2         lv     jw qgram_3 soundex
  &lt;chr&gt;             &lt;chr&gt;              &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 Gupta Enterprises Guptha Enterprises     1 0.0185       5       0
2 Sharma Traders    Sharma Trader's        1 0.0222       3       0
3 Bharat Stationers Rajdhani Computers    14 0.292       29       1
4 Sharma Traders    Om Sai Caterers       11 0.306       23       1
5 Gupta Enterprises Kaveri Suppliers      14 0.306       29       1</code></pre>
</div>
</div>
<p>All four measures pick out the same two pairs. But each one speaks in its own language. Let us read them one by one.</p>
<ul>
<li>
<strong>Levenshtein (<code>lv</code>)</strong> counts the number of single-character edits. Both look-alike pairs need just one edit. Other pairs need 11 or more. But this is a <em>count</em>, so it depends on the length of the names. One edit in a five-letter name is a big change. One edit in a thirty-letter name is a small one. So the same cut-off does not suit short and long names alike.</li>
<li>
<strong>Jaro-Winkler (<code>jw</code>)</strong> is always between 0 and 1, whatever the length of the names. This makes it easier to choose a single cut-off. It also gives more weight to the beginning of the string, where people usually make fewer mistakes.</li>
<li>
<strong>Q-gram (<code>qgram_3</code>)</strong> counts the groups of three consecutive letters which are present in one name but not in the other. Notice that <em>Gupta</em> and <em>Guptha</em> score 5, though only one letter differs. A single extra letter breaks several three-letter groups at once.</li>
<li>
<strong>Soundex (<code>soundex</code>)</strong> checks whether two strings <em>sound</em> alike in English. It gives only a yes or no answer. <code>0</code> means they sound the same and <code>1</code> means they do not. It caught both pairs, because <em>Gupta</em> and <em>Guptha</em> are pronounced the same way.</li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Caution with Soundex on long names
</div>
</div>
<div class="callout-body-container callout-body">
<p>Soundex looks only at the first letter and the next few consonant sounds of a string. It ignores everything after that. So long names which merely <em>begin</em> alike will also be called a match.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/stringdist/man/stringdist.html">stringdist</a></span><span class="op">(</span><span class="st">"sharma traders"</span>,</span>
<span>           <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"sharma transport"</span>, <span class="st">"sharma tours"</span>, <span class="st">"shree traders"</span><span class="op">)</span>,</span>
<span>           method <span class="op">=</span> <span class="st">"soundex"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0 0 1</code></pre>
</div>
</div>
<p>All three vendors starting with “Sharma Tr…” are treated as the same. Soundex works best on single words like surnames. For full names, use it along with another measure, not alone.</p>
</div>
</div>
</section><section id="a-better-phonetic-measure-double-metaphone" class="level3" data-number="32.8.2"><h3 data-number="32.8.2" class="anchored" data-anchor-id="a-better-phonetic-measure-double-metaphone">
<span class="header-section-number">32.8.2</span> A better phonetic measure, Double Metaphone</h3>
<p>Double Metaphone is a more refined way to check whether two names <em>sound</em> alike. It gives two codes for each name, a <em>primary</em> and a <em>secondary</em> code. Comparing these codes gives three levels of match. These are strong, normal and weak, as <a href="15-stringdist.html" class="quarto-xref"><span>Chapter 33</span></a> explains. The package <code>fullmetaphone</code> keeps the full code, while other packages keep only the first four characters. Full codes matter here, because firm names are long.</p>
<p>Let us calculate the codes for all our vendors. <code><a href="https://rdrr.io/pkg/fullmetaphone/man/double_metaphone.html">double_metaphone()</a></code> returns a data frame with two columns, <code>primary</code> and <code>secondary</code>. We attach these to the vendor master.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/anilyayavar/dblmetaphone">fullmetaphone</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">vendor_codes</span> <span class="op">&lt;-</span> <span class="va">vendors</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_cols.html">bind_cols</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/fullmetaphone/man/double_metaphone.html">double_metaphone</a></span><span class="op">(</span><span class="va">vendors</span><span class="op">$</span><span class="va">vendor_name</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">vendor_codes</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 4
   vendor_id vendor_name            primary      secondary   
   &lt;chr&gt;     &lt;chr&gt;                  &lt;chr&gt;        &lt;chr&gt;       
 1 V001      Sharma Traders         XRMTRTRS     XRMTRTRS    
 2 V002      Gupta Enterprises      KPTNTRPRSS   KPTNTRPRSS  
 3 V003      Bharat Stationers      PRTSTXNRS    PRTSTXNRS   
 4 V004      Kaveri Suppliers       KFRSPLRS     KFRSPLRS    
 5 V005      Laxmi Electricals      LKSMLKTRKLS  LKSMLKTRKLS 
 6 V006      National Printers      NXNLPRNTRS   NXNLPRNTRS  
 7 V007      Om Sai Caterers        AMSKTRRS     AMSKTRRS    
 8 V008      Patel Hardware         PTLRTR       PTLRTR      
 9 V009      Rajdhani Computers     RJTNKMPTRS   RJTNKMPTRS  
10 V010      Shree Ganesh Transport XRKNXTRNSPRT XRKNXTRNSPRT
11 V011      Ashok Estates          AXKSTTS      AXKSTTS     
12 V012      Verma &amp; Sons           FRMSNS       FRMSNS      
13 V013      Sharma Trader's        XRMTRTRS     XRMTRTRS    
14 V014      Guptha Enterprises     KP0NTRPRSS   KPTNTRPRSS  </code></pre>
</div>
</div>
<p>Now we make pairs exactly as before, and compare the codes of each pair.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">vendor_codes</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">inner_join</a></span><span class="op">(</span><span class="va">vendor_codes</span>, by <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/join_by.html">join_by</a></span><span class="op">(</span><span class="va">vendor_id</span> <span class="op">&lt;</span> <span class="va">vendor_id</span><span class="op">)</span>, suffix <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"_1"</span>, <span class="st">"_2"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>match_level <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case-and-replace-when.html">case_when</a></span><span class="op">(</span></span>
<span>    <span class="va">primary_1</span> <span class="op">==</span> <span class="va">primary_2</span> <span class="op">~</span> <span class="st">"strong"</span>,</span>
<span>    <span class="va">primary_1</span> <span class="op">==</span> <span class="va">secondary_2</span> <span class="op">|</span> <span class="va">secondary_1</span> <span class="op">==</span> <span class="va">primary_2</span> <span class="op">~</span> <span class="st">"normal"</span>,</span>
<span>    <span class="va">secondary_1</span> <span class="op">==</span> <span class="va">secondary_2</span> <span class="op">~</span> <span class="st">"weak"</span>,</span>
<span>    <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"none"</span></span>
<span>  <span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">match_level</span> <span class="op">!=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">vendor_name_1</span>, <span class="va">vendor_name_2</span>, <span class="va">match_level</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  vendor_name_1     vendor_name_2      match_level
  &lt;chr&gt;             &lt;chr&gt;              &lt;chr&gt;      
1 Sharma Traders    Sharma Trader's    strong     
2 Gupta Enterprises Guptha Enterprises normal     </code></pre>
</div>
</div>
<p>Only our two look-alike pairs are matched. <em>Sharma Traders</em> and <em>Sharma Trader’s</em> have exactly the same primary code, so it is a strong match. <em>Guptha</em> is coded as <code>KP0...</code>, because “th” may be spoken like the “th” in “think”. But its secondary code is <code>KPT...</code>, the same as the primary code of <em>Gupta</em>. So it is a normal match. Unlike Soundex, the full codes did not match any other firm.</p>
<p><a href="#tbl-simmeasures" class="quarto-xref">Table&nbsp;<span>32.3</span></a> sums up when each measure is useful in audit work.</p>
<div id="tbl-simmeasures" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-simmeasures-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;32.3: Choosing a string similarity measure
</figcaption><div aria-describedby="tbl-simmeasures-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 34%">
</colgroup>
<thead><tr class="header">
<th>Measure</th>
<th>How to calculate</th>
<th>Result</th>
<th>Best suited for</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Levenshtein</td>
<td><code>stringdist(method = "lv")</code></td>
<td>0 upwards, counts edits</td>
<td>Codes of fixed length, like PAN, GSTIN or invoice numbers</td>
</tr>
<tr class="even">
<td>Jaro-Winkler</td>
<td><code>stringdist(method = "jw")</code></td>
<td>0 to 1</td>
<td>Names of persons and firms, with one common cut-off</td>
</tr>
<tr class="odd">
<td>Q-gram</td>
<td><code>stringdist(method = "qgram")</code></td>
<td>0 upwards</td>
<td>Longer text like addresses, where words may be rearranged</td>
</tr>
<tr class="even">
<td>Soundex</td>
<td><code>stringdist(method = "soundex")</code></td>
<td>0 or 1</td>
<td>Single words that sound alike, like <em>Geeta</em> and <em>Gita</em>
</td>
</tr>
<tr class="odd">
<td>Double Metaphone</td>
<td><code><a href="https://rdrr.io/pkg/fullmetaphone/man/double_metaphone.html">double_metaphone()</a></code></td>
<td>Strong, normal, weak or no match</td>
<td>Full names of persons and firms that sound alike</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Audit tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>A pair flagged by two different measures is a stronger lead than a pair flagged by only one. For example, a pair with a low Jaro-Winkler distance <em>and</em> a strong Double Metaphone match deserves a closer look first. One measure checks spelling, the other checks sound. Together they catch both typing mistakes and deliberate look-alike names.</p>
</div>
</div>
<p>Comparing every name with every other name creates a very large table when the master is big. A master of 10,000 vendors gives about five crore pairs. In such cases, compare names only within smaller groups, say within the same state or the same first letter. This is called <em>blocking</em>.</p>
</section></section><section id="duplicates-across-more-than-one-id" class="level2" data-number="32.9"><h2 data-number="32.9" class="anchored" data-anchor-id="duplicates-across-more-than-one-id">
<span class="header-section-number">32.9</span> Duplicates across more than one ID</h2>
<p>Sometimes duplicates are hidden even better. A beneficiary may register twice with a different mobile number but the same bank account. Then again with a different bank account but the same Aadhaar or PAN. No single column shows a duplicate. But together, the records form a chain.</p>
<p>Such chains can be found using graph theory. We discuss this with a complete example in <a href="13-Network-applying-network-analysis-in-audit-fraud.html#sec-dup_net" class="quarto-xref"><span>Section 52.2</span></a>.</p>
</section><section id="a-suggested-workflow" class="level2" data-number="32.10"><h2 data-number="32.10" class="anchored" data-anchor-id="a-suggested-workflow">
<span class="header-section-number">32.10</span> A suggested workflow</h2>
<p>Let us put everything together. For any payment, claim or beneficiary data, an auditor may follow these steps.</p>
<ol type="1">
<li>
<strong>Understand the data.</strong> Know what each column means and which columns identify a transaction.</li>
<li>
<strong>Check exact duplicates.</strong> Find repeated rows with <code><a href="https://sfirke.github.io/janitor/reference/get_dupes.html">get_dupes()</a></code>. Find out why they exist, then remove them with <code><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct()</a></code>.</li>
<li>
<strong>Clean the key columns.</strong> Fix case, spaces, punctuation and leading zeros.</li>
<li>
<strong>Run the Same-Same-Same test</strong> on the cleaned key. Quantify the excess payment.</li>
<li>
<strong>Run Same-Same-Different tests</strong> on suitable combinations. Use date windows and business knowledge to reduce false alarms.</li>
<li>
<strong>Look for fuzzy duplicates</strong> in master data like vendors, employees and beneficiaries.</li>
<li>
<strong>Verify with documents.</strong> Analytics only points to the cases. The finding is confirmed only after examining the original bills, approvals and bank records.</li>
</ol>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Remember
</div>
</div>
<div class="callout-body-container callout-body">
<p>A duplicate found in data is a <em>lead</em>, not a <em>finding</em>. There may be a genuine reason, such as a part payment, a cancelled and re-issued cheque, or a credit note. Always examine the supporting records before reporting.</p>
</div>
</div>
</section><section id="summary-of-functions-used" class="level2" data-number="32.11"><h2 data-number="32.11" class="anchored" data-anchor-id="summary-of-functions-used">
<span class="header-section-number">32.11</span> Summary of functions used</h2>
<div id="tbl-dupfunctions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dupfunctions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;32.4: Functions used in this chapter
</figcaption><div aria-describedby="tbl-dupfunctions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 22%">
<col style="width: 45%">
</colgroup>
<thead><tr class="header">
<th>Function</th>
<th>Package</th>
<th>What it does</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code><a href="https://rdrr.io/r/base/duplicated.html">duplicated()</a></code></td>
<td>base R</td>
<td>Marks every repeat occurrence as <code>TRUE</code>
</td>
</tr>
<tr class="even">
<td><code><a href="https://sfirke.github.io/janitor/reference/get_dupes.html">get_dupes()</a></code></td>
<td>janitor</td>
<td>Shows all copies of duplicate records, with a count</td>
</tr>
<tr class="odd">
<td><code><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct()</a></code></td>
<td>dplyr</td>
<td>Keeps only one copy of each row</td>
</tr>
<tr class="even">
<td><code><a href="https://dplyr.tidyverse.org/reference/n_distinct.html">n_distinct()</a></code></td>
<td>dplyr</td>
<td>Counts distinct values, used in Same-Same-Different tests</td>
</tr>
<tr class="odd">
<td><code><a href="https://dplyr.tidyverse.org/reference/lead-lag.html">lag()</a></code></td>
<td>dplyr</td>
<td>Gives the previous value, used for date windows</td>
</tr>
<tr class="even">
<td>
<code><a href="https://stringr.tidyverse.org/reference/case.html">str_to_upper()</a></code>, <code><a href="https://stringr.tidyverse.org/reference/str_remove.html">str_remove_all()</a></code>
</td>
<td>stringr</td>
<td>Clean key columns before testing</td>
</tr>
<tr class="odd">
<td>
<code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">inner_join()</a></code> with <code>join_by(x &lt; y)</code>
</td>
<td>dplyr</td>
<td>Makes each pair of records only once</td>
</tr>
<tr class="even">
<td><code><a href="https://rdrr.io/pkg/stringdist/man/stringdist.html">stringdist()</a></code></td>
<td>stringdist</td>
<td>Measures how different two strings are, by the chosen <code>method</code>
</td>
</tr>
<tr class="odd">
<td><code><a href="https://rdrr.io/pkg/fullmetaphone/man/double_metaphone.html">double_metaphone()</a></code></td>
<td>fullmetaphone</td>
<td>Gives full length primary and secondary sound codes for names</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-R-quarto" class="csl-entry" role="listitem">
Allaire, JJ, and Christophe Dervieux. <em>Quarto: R Interface to Quarto Markdown Publishing System</em>, 2025. <a href="https://github.com/quarto-dev/quarto-r">https://github.com/quarto-dev/quarto-r</a>.
</div>
<div id="ref-R-visNetwork" class="csl-entry" role="listitem">
Almende B.V. and Contributors, and Benoit Thieurmel. <em>visNetwork: Network Visualization Using Vis.js Library</em>, 2025. <a href="https://datastorm-open.github.io/visNetwork/">https://datastorm-open.github.io/visNetwork/</a>.
</div>
<div id="ref-igraph2023" class="csl-entry" role="listitem">
Antonov, Michael, Gábor Csárdi, Szabolcs Horvát, Kirill Müller, Tamás Nepusz, Daniel Noom, Maëlle Salmon, Vincent Traag, Brooke Foucault Welles, and Fabio Zanini. <span>“Igraph Enables Fast and Robust Network Analysis Across Programming Languages.”</span> <em>arXiv Preprint arXiv:2311.10260</em>, 2023. <a href="https://doi.org/10.48550/arXiv.2311.10260">https://doi.org/10.48550/arXiv.2311.10260</a>.
</div>
<div id="ref-R-PGRdup" class="csl-entry" role="listitem">
Aravind, J., J. Radhamani, Kalyani Srinivasan, B. Ananda Subhash, and Rishi Kumar Tyagi. <em>PGRdup: Discover Probable Duplicates in Plant Genetic Resources Collections</em>, 2026. <a href="https://cran.r-project.org/package=PGRdup">https://cran.r-project.org/package=PGRdup</a>.
</div>
<div id="ref-R-magrittr" class="csl-entry" role="listitem">
Bache, Stefan Milton, and Hadley Wickham. <em>Magrittr: A Forward-Pipe Operator for r</em>, 2025. <a href="https://magrittr.tidyverse.org">https://magrittr.tidyverse.org</a>.
</div>
<div id="ref-R-data.table" class="csl-entry" role="listitem">
Barrett, Tyson, Matt Dowle, Arun Srinivasan, Jan Gorecki, Michael Chirico, Toby Hocking, Benjamin Schwendinger, and Ivan Krylov. <em>Data.table: Extension of ‘Data.frame‘</em>, 2026. <a href="https://r-datatable.com">https://r-datatable.com</a>.
</div>
<div id="ref-frank_ben" class="csl-entry" role="listitem">
Benford, Frank. <span>“The Law of Anomalous Numbers.”</span> <em>Proceedings of the American Philosophical Society</em> 78, no. 4 (1938): 551–72. <a href="http://www.jstor.org/stable/984802">http://www.jstor.org/stable/984802</a>.
</div>
<div id="ref-R-FNN" class="csl-entry" role="listitem">
Beygelzimer, Alina, Sham Kakadet, John Langford, Sunil Arya, David Mount, and Shengqiao Li. <em>FNN: Fast Nearest Neighbor Search Algorithms and Applications</em>, 2024. <a href="https://doi.org/10.32614/CRAN.package.FNN">https://doi.org/10.32614/CRAN.package.FNN</a>.
</div>
<div id="ref-R-deaR" class="csl-entry" role="listitem">
Bolos, Vicente, Vicente Coll-Serrano, and Rafael Benitez Suarez. <em>deaR: Conventional and Fuzzy Data Envelopment Analysis</em>, 2026. <a href="https://doi.org/10.32614/CRAN.package.deaR">https://doi.org/10.32614/CRAN.package.deaR</a>.
</div>
<div id="ref-deaR2025" class="csl-entry" role="listitem">
Bolós, V. J., R. Benítez, and V. Coll-Serrano. <span>“deaR: Conventional and Fuzzy DEA Models with r.”</span> <em>SoftwareX</em> 31 (2025): 102266, 1–6. <a href="https://doi.org/10.1016/j.softx.2025.102266">https://doi.org/10.1016/j.softx.2025.102266</a>.
</div>
<div id="ref-R-SnowballC" class="csl-entry" role="listitem">
Bouchet-Valat, Milan. <em>SnowballC: Snowball Stemmers Based on the c Libstemmer UTF-8 Library</em>, 2023. <a href="https://github.com/nalimilan/R.TeMiS">https://github.com/nalimilan/R.TeMiS</a>.
</div>
<div id="ref-R-tidygeocoder" class="csl-entry" role="listitem">
Cambon, Jesse, Diego Hernangómez, Christopher Belanger, and Daniel Possenriede. <em>Tidygeocoder: Geocoding Made Easy</em>, 2025. <a href="https://jessecambon.github.io/tidygeocoder/">https://jessecambon.github.io/tidygeocoder/</a>.
</div>
<div id="ref-R-leaflet" class="csl-entry" role="listitem">
Cheng, Joe, Barret Schloerke, Bhaskar Karambelkar, Yihui Xie, and Garrick Aden-Buie. <em>Leaflet: Create Interactive Web Maps with the JavaScript Leaflet Library</em>, 2025. <a href="https://rstudio.github.io/leaflet/">https://rstudio.github.io/leaflet/</a>.
</div>
<div id="ref-R-benford.analysis" class="csl-entry" role="listitem">
Cinelli, Carlos. <em>Benford.analysis: Benford Analysis for Data Validation and Forensic Analytics</em>, 2018. <a href="http://github.com/carloscinelli/benford.analysis">http://github.com/carloscinelli/benford.analysis</a>.
</div>
<div id="ref-dea" class="csl-entry" role="listitem">
Cooper, William, Lawrence Seiford, and Joe Zhu. <span>“Data Envelopment Analysis: History, Models, and Interpretations.”</span> In <em>Handbook on Data Envelopment Analysis</em>, 1–39, 2011. <a href="https://doi.org/10.1007/978-1-4419-6151-8_1">https://doi.org/10.1007/978-1-4419-6151-8_1</a>.
</div>
<div id="ref-R-isotree" class="csl-entry" role="listitem">
Cortes, David. <em>Isotree: Isolation-Based Outlier Detection</em>, 2026. <a href="https://github.com/david-cortes/isotree">https://github.com/david-cortes/isotree</a>.
</div>
<div id="ref-R-rebus" class="csl-entry" role="listitem">
Cotton, Richard. <em>Rebus: Build Regular Expressions in a Human Readable Way</em>, 2017. <a href="https://doi.org/10.32614/CRAN.package.rebus">https://doi.org/10.32614/CRAN.package.rebus</a>.
</div>
<div id="ref-R-igraphdata" class="csl-entry" role="listitem">
Csardi, Gabor. <em>Igraphdata: A Collection of Network Data Sets for the Igraph Package</em>, 2015. <a href="http://igraph.org">http://igraph.org</a>.
</div>
<div id="ref-igraph2006" class="csl-entry" role="listitem">
Csárdi, Gábor, and Tamás Nepusz. <span>“The Igraph Software Package for Complex Network Research.”</span> <em>InterJournal</em> Complex Systems (2006): 1695. <a href="https://igraph.org">https://igraph.org</a>.
</div>
<div id="ref-R-igraph" class="csl-entry" role="listitem">
Csárdi, Gábor, Tamás Nepusz, Vincent Traag, Szabolcs Horvát, Fabio Zanini, Daniel Noom, Kirill Müller, David Schoch, and Maëlle Salmon. <em>Igraph: Network Analysis and Visualization</em>, 2026. <a href="https://r.igraph.org/">https://r.igraph.org/</a>.
</div>
<div id="ref-R-timetk" class="csl-entry" role="listitem">
Dancho, Matt, and Davis Vaughan. <em>Timetk: A Tool Kit for Working with Time Series</em>, 2025. <a href="https://github.com/business-science/timetk">https://github.com/business-science/timetk</a>.
</div>
<div id="ref-durtschi" class="csl-entry" role="listitem">
Durtschi, Cindy, William Hillison, and Carl Pacini. <span>“The Effective Use of Benford’s Law to Assist in Detecting Fraud in Accounting Data.”</span> <em>J. Forensic Account</em> 5 (January 2004).
</div>
<div id="ref-R-wordcloud" class="csl-entry" role="listitem">
Fellows, Ian. <em>Wordcloud: Word Clouds</em>, 2018. <a href="http://blog.fellstat.com/?cat=11">http://blog.fellstat.com/?cat=11</a>.
</div>
<div id="ref-R-janitor" class="csl-entry" role="listitem">
Firke, Sam. <em>Janitor: Simple Tools for Examining and Cleaning Dirty Data</em>, 2024. <a href="https://github.com/sfirke/janitor">https://github.com/sfirke/janitor</a>.
</div>
<div id="ref-car2019" class="csl-entry" role="listitem">
Fox, John, and Sanford Weisberg. <em>An <span>R</span> Companion to Applied Regression</em>. Third. Thousand Oaks <span>CA</span>: Sage, 2019. <a href="https://www.john-fox.ca/Companion/">https://www.john-fox.ca/Companion/</a>.
</div>
<div id="ref-R-car" class="csl-entry" role="listitem">
Fox, John, Sanford Weisberg, and Brad Price. <em>Car: Companion to Applied Regression</em>, 2026. <a href="https://github.com/bprice2652/car_repo">https://github.com/bprice2652/car_repo</a>.
</div>
<div id="ref-r-stringi" class="csl-entry" role="listitem">
Gagolewski, Marek. <em>Stringi: Fast and Portable Character String Processing in r</em>, 2021. <a href="https://stringi.gagolewski.com/">https://stringi.gagolewski.com/</a>.
</div>
<div id="ref-mcke" class="csl-entry" role="listitem">
Gardner, Everette S., and Ed. Mckenzie. <span>“Forecasting Trends in Time Series.”</span> <em>Management Science</em> 31, no. 10 (1985): 1237–46. <a href="https://doi.org/10.1287/mnsc.31.10.1237">https://doi.org/10.1287/mnsc.31.10.1237</a>.
</div>
<div id="ref-R-tidyxl" class="csl-entry" role="listitem">
Garmonsway, Duncan. <em>Tidyxl: Read Untidy Excel Files</em>, 2023. <a href="https://github.com/nacnudus/tidyxl">https://github.com/nacnudus/tidyxl</a>.
</div>
<div id="ref-R-unpivotr" class="csl-entry" role="listitem">
———. <em>Unpivotr: Unpivot Complex and Irregular Data Layouts</em>, 2024. <a href="https://github.com/nacnudus/unpivotr">https://github.com/nacnudus/unpivotr</a>.
</div>
<div id="ref-JSSv040i03" class="csl-entry" role="listitem">
Grolemund, Garrett, and Hadley Wickham. <span>“Dates and Times Made Easy with Lubridate.”</span> <em>Journal of Statistical Software</em> 40, no. 3 (2011): 1–25. <a href="https://doi.org/10.18637/jss.v040.i03">https://doi.org/10.18637/jss.v040.i03</a>.
</div>
<div id="ref-lubridate2011" class="csl-entry" role="listitem">
———. <span>“Dates and Times Made Easy with <span class="nocase">lubridate</span>.”</span> <em>Journal of Statistical Software</em> 40, no. 3 (2011): 1–25. <a href="https://www.jstatsoft.org/v40/i03/">https://www.jstatsoft.org/v40/i03/</a>.
</div>
<div id="ref-R-arules" class="csl-entry" role="listitem">
Hahsler, Michael, Christian Buchta, Bettina Gruen, and Kurt Hornik. <em>Arules: Mining Association Rules and Frequent Itemsets</em>, 2026. <a href="https://github.com/mhahsler/arules">https://github.com/mhahsler/arules</a>.
</div>
<div id="ref-arules2011" class="csl-entry" role="listitem">
Hahsler, Michael, Sudheer Chelluboina, Kurt Hornik, and Christian Buchta. <span>“The Arules r-Package Ecosystem: Analyzing Interesting Patterns from Large Transaction Datasets.”</span> <em>Journal of Machine Learning Research</em> 12 (2011): 1977–81. <a href="https://jmlr.csail.mit.edu/papers/v12/hahsler11a.html">https://jmlr.csail.mit.edu/papers/v12/hahsler11a.html</a>.
</div>
<div id="ref-arules2005" class="csl-entry" role="listitem">
Hahsler, Michael, Bettina Gruen, and Kurt Hornik. <span>“Arules – <span>A</span> Computational Environment for Mining Association Rules and Frequent Item Sets.”</span> <em>Journal of Statistical Software</em> 14, no. 15 (2005): 1–25. <a href="https://doi.org/10.18637/jss.v014.i15">https://doi.org/10.18637/jss.v014.i15</a>.
</div>
<div id="ref-R-dbscan" class="csl-entry" role="listitem">
Hahsler, Michael, and Matthew Piekenbrock. <em>Dbscan: Density-Based Spatial Clustering of Applications with Noise (DBSCAN) and Related Algorithms</em>, 2026. <a href="https://github.com/mhahsler/dbscan">https://github.com/mhahsler/dbscan</a>.
</div>
<div id="ref-dbscan2019" class="csl-entry" role="listitem">
Hahsler, Michael, Matthew Piekenbrock, and Derek Doran. <span>“<span class="nocase">dbscan</span>: Fast Density-Based Clustering with <span>R</span>.”</span> <em>Journal of Statistical Software</em> 91, no. 1 (2019): 1–30. <a href="https://doi.org/10.18637/jss.v091.i01">https://doi.org/10.18637/jss.v091.i01</a>.
</div>
<div id="ref-t_hill" class="csl-entry" role="listitem">
Hill, Theodore P. <span>“The Significant-Digit Phenomenon.”</span> <em>The American Mathematical Monthly</em> 102, no. 4 (1995): 322–27. <a href="http://www.jstor.org/stable/2974952">http://www.jstor.org/stable/2974952</a>.
</div>
<div id="ref-R-palmerpenguins" class="csl-entry" role="listitem">
Horst, Allison, Alison Hill, and Kristen Gorman. <em>Palmerpenguins: Palmer Archipelago (Antarctica) Penguin Data</em>, 2022. <a href="https://allisonhorst.github.io/palmerpenguins/">https://allisonhorst.github.io/palmerpenguins/</a>.
</div>
<div id="ref-phonics2018" class="csl-entry" role="listitem">
Howard, II, James P. <span>“Phonetic Algorithms in <span>R</span>.”</span> <em>Journal of Open Source Software</em> 3, no. 22 (2018): 480. <a href="https://doi.org/10.21105/joss.00480">https://doi.org/10.21105/joss.00480</a>.
</div>
<div id="ref-phonics2020" class="csl-entry" role="listitem">
———. <span>“Phonetic Spelling Algorithm Implementations for <span>R</span>.”</span> <em>Journal of Statistical Software</em> 95, no. 8 (2020): 1–21. <a href="https://doi.org/10.18637/jss.v095.i08">https://doi.org/10.18637/jss.v095.i08</a>.
</div>
<div id="ref-R-phonics" class="csl-entry" role="listitem">
Howard, James. <em>Phonics: Phonetic Spelling Algorithms</em>, 2026. <a href="https://phonics.jameshoward.us">https://phonics.jameshoward.us</a>.
</div>
<div id="ref-forecast2008" class="csl-entry" role="listitem">
Hyndman, Rob J, and Yeasmin Khandakar. <span>“Automatic Time Series Forecasting: The Forecast Package for <span>R</span>.”</span> <em>Journal of Statistical Software</em> 27, no. 3 (2008): 1–22. <a href="https://doi.org/10.18637/jss.v027.i03">https://doi.org/10.18637/jss.v027.i03</a>.
</div>
<div id="ref-R-forecast" class="csl-entry" role="listitem">
Hyndman, Rob, George Athanasopoulos, Christoph Bergmeir, Gabriel Caceres, Leanne Chhay, Kirill Kuroptev, Maximilian Mücke, et al. <em>Forecast: Forecasting Functions for Time Series and Linear Models</em>, 2026. <a href="https://pkg.robjhyndman.com/forecast/">https://pkg.robjhyndman.com/forecast/</a>.
</div>
<div id="ref-R-gt" class="csl-entry" role="listitem">
Iannone, Richard, Joe Cheng, Barret Schloerke, Shannon Haughton, Ellis Hughes, Alexandra Lauer, Romain François, JooYoung Seo, Ken Brevoort, and Olivier Roy. <em>Gt: Easily Create Presentation-Ready Display Tables</em>, 2026. <a href="https://gt.rstudio.com">https://gt.rstudio.com</a>.
</div>
<div id="ref-R-pointblank" class="csl-entry" role="listitem">
Iannone, Richard, Mauricio Vargas, and June Choe. <em>Pointblank: Data Validation and Organization of Metadata for Local and Remote Tables</em>, 2026. <a href="https://rstudio.github.io/pointblank/">https://rstudio.github.io/pointblank/</a>.
</div>
<div id="ref-10.2307/1390807" class="csl-entry" role="listitem">
Ihaka, Ross, and Robert Gentleman. <span>“R: A Language for Data Analysis and Graphics.”</span> <em>Journal of Computational and Graphical Statistics</em> 5, no. 3 (1996): 299–314. <a href="http://www.jstor.org/stable/1390807">http://www.jstor.org/stable/1390807</a>.
</div>
<div id="ref-R-colorspace" class="csl-entry" role="listitem">
Ihaka, Ross, Paul Murrell, Kurt Hornik, Jason C. Fisher, Reto Stauffer, Claus O. Wilke, Claire D. McWhite, and Achim Zeileis. <em>Colorspace: A Toolbox for Manipulating and Assessing Colors and Palettes</em>, 2025. <a href="https://colorspace.R-Forge.R-project.org/">https://colorspace.R-Forge.R-project.org/</a>.
</div>
<div id="ref-R-bupaR" class="csl-entry" role="listitem">
Janssenswillen, Gert. <em>bupaR: Business Process Analysis in r</em>, 2026. <a href="https://bupar.net/">https://bupar.net/</a>.
</div>
<div id="ref-R-edeaR" class="csl-entry" role="listitem">
———. <em>edeaR: Exploratory and Descriptive Event-Based Data Analysis</em>, 2026. <a href="https://bupar.net/">https://bupar.net/</a>.
</div>
<div id="ref-R-processcheckR" class="csl-entry" role="listitem">
———. <em>processcheckR: Rule-Based Conformance Checking of Business Process Event Data</em>, 2025. <a href="https://bupar.net/">https://bupar.net/</a>.
</div>
<div id="ref-R-processmapR" class="csl-entry" role="listitem">
———. <em>processmapR: Construct Process Maps Using Event Data</em>, 2026. <a href="https://bupar.net/">https://bupar.net/</a>.
</div>
<div id="ref-R-factoextra" class="csl-entry" role="listitem">
Kassambara, Alboukadel, and Fabian Mundt. <em>Factoextra: Extract and Visualize the Results of Multivariate Data Analyses</em>, 2026. <a href="https://github.com/kassambara/factoextra">https://github.com/kassambara/factoextra</a>.
</div>
<div id="ref-R-changepoint" class="csl-entry" role="listitem">
Killick, Rebecca. <em>Changepoint: Methods for Changepoint Detection</em>, 2024. <a href="https://github.com/rkillick/changepoint/">https://github.com/rkillick/changepoint/</a>.
</div>
<div id="ref-changepoint2014" class="csl-entry" role="listitem">
Killick, Rebecca, and Idris A. Eckley. <span>“<span class="nocase">changepoint</span>: An <span>R</span> Package for Changepoint Analysis.”</span> <em>Journal of Statistical Software</em> 58, no. 3 (2014): 1–19. <a href="https://www.jstatsoft.org/article/view/v058i03">https://www.jstatsoft.org/article/view/v058i03</a>.
</div>
<div id="ref-R-moderndive" class="csl-entry" role="listitem">
Kim, Albert Y., and Chester Ismay. <em>Moderndive: Tidyverse-Friendly Introductory Linear Regression</em>, 2026. <a href="https://moderndive.github.io/moderndive/">https://moderndive.github.io/moderndive/</a>.
</div>
<div id="ref-moderndive2021" class="csl-entry" role="listitem">
Kim, Albert Y., Chester Ismay, and Max Kuhn. <span>“Take a Moderndive into Introductory Linear Regression with r.”</span> <em>The Journal of Open Source Education</em> 4, no. 41, 115 (2021). <a href="https://doi.org/10.21105/jose.00115">https://doi.org/10.21105/jose.00115</a>.
</div>
<div id="ref-R-outliers" class="csl-entry" role="listitem">
Komsta, Lukasz. <em>Outliers: Tests for Outliers</em>, 2022. <a href="https://www.R-project.org">https://www.R-project.org</a>.
</div>
<div id="ref-performance2021" class="csl-entry" role="listitem">
Lüdecke, Daniel, Mattan S. Ben-Shachar, Indrajeet Patil, Philip Waggoner, and Dominique Makowski. <span>“<span class="nocase">performance</span>: An <span>R</span> Package for Assessment, Comparison and Testing of Statistical Models.”</span> <em>Journal of Open Source Software</em> 6, no. 60 (2021): 3139. <a href="https://doi.org/10.21105/joss.03139">https://doi.org/10.21105/joss.03139</a>.
</div>
<div id="ref-R-performance" class="csl-entry" role="listitem">
Lüdecke, Daniel, Dominique Makowski, Mattan S. Ben-Shachar, Indrajeet Patil, Philip Waggoner, Brenton M. Wiernik, and Rémi Thériault. <em>Performance: Assessment of Regression Models Performance</em>, 2026. <a href="https://easystats.github.io/performance/">https://easystats.github.io/performance/</a>.
</div>
<div id="ref-R-cluster" class="csl-entry" role="listitem">
Maechler, Martin, Peter Rousseeuw, Anja Struyf, and Mia Hubert. <em>Cluster: "Finding Groups in Data": Cluster Analysis Extended Rousseeuw Et Al.</em>, 2026. <a href="https://svn.r-project.org/R-packages/trunk/cluster/">https://svn.r-project.org/R-packages/trunk/cluster/</a>.
</div>
<div id="ref-R-rpart.plot" class="csl-entry" role="listitem">
Milborrow, Stephen. <em>Rpart.plot: Plot Rpart Models: An Enhanced Version of Plot.rpart</em>, 2026. <a href="http://www.milbo.org/rpart-plot/index.html">http://www.milbo.org/rpart-plot/index.html</a>.
</div>
<div id="ref-R-duckdb" class="csl-entry" role="listitem">
Mühleisen, Hannes, and Mark Raasveldt. <em>Duckdb: DBI Package for the DuckDB Database Management System</em>, 2026. <a href="https://r.duckdb.org/">https://r.duckdb.org/</a>.
</div>
<div id="ref-r-tibble" class="csl-entry" role="listitem">
Müller, Kirill, and Hadley Wickham. <em>Tibble: Simple Data Frames</em>, 2022. <a href="https://CRAN.R-project.org/package=tibble">https://CRAN.R-project.org/package=tibble</a>.
</div>
<div id="ref-R-tibble" class="csl-entry" role="listitem">
———. <em>Tibble: Simple Data Frames</em>, 2026. <a href="https://tibble.tidyverse.org/">https://tibble.tidyverse.org/</a>.
</div>
<div id="ref-R-RColorBrewer" class="csl-entry" role="listitem">
Neuwirth, Erich. <em>RColorBrewer: ColorBrewer Palettes</em>, 2022. <a href="https://doi.org/10.32614/CRAN.package.RColorBrewer">https://doi.org/10.32614/CRAN.package.RColorBrewer</a>.
</div>
<div id="ref-newcomb" class="csl-entry" role="listitem">
Newcomb, Simon. <span>“Note on the Frequency of Use of the Different Digits in Natural Numbers.”</span> <em>American Journal of Mathematics</em> 4, no. 1 (1881): 39–40. <a href="http://www.jstor.org/stable/2369148">http://www.jstor.org/stable/2369148</a>.
</div>
<div id="ref-nigrinifraud" class="csl-entry" role="listitem">
Nigrini, Mark J. <em>Benford’s Law Applications for Forensic Accounting, Auditing and Fraud Detection</em>. 1st ed. John Wiley; Sons, Ltd, 2012. <a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/9781119203094.ch5">https://onlinelibrary.wiley.com/doi/abs/10.1002/9781119203094.ch5</a>.
</div>
<div id="ref-article2007" class="csl-entry" role="listitem">
Nigrini, Mark, and Steven Miller. <span>“Benford’s Law Applied to Hydrology Data—Results and Relevance to Other Geophysical Data.”</span> <em>Mathematical Geology</em> 39 (September 2007): 469–90. <a href="https://doi.org/10.1007/s11004-007-9109-5">https://doi.org/10.1007/s11004-007-9109-5</a>.
</div>
<div id="ref-articlesec" class="csl-entry" role="listitem">
———. <span>“Data Diagnostics Using Second-Order Tests of Benford’s Law.”</span> <em>Auditing a Journal of Practice and Theory AUDITING J PRACT THEOR</em> 28 (November 2009). <a href="https://doi.org/10.2308/aud.2009.28.2.305">https://doi.org/10.2308/aud.2009.28.2.305</a>.
</div>
<div id="ref-article2009" class="csl-entry" role="listitem">
———. <span>“Data Diagnostics Using Second-Order Tests of Benford’s Law.”</span> <em>Auditing-a Journal of Practice and Theory - AUDITING-J PRACT THEOR</em> 28 (November 2009). <a href="https://doi.org/10.2308/aud.2009.28.2.305">https://doi.org/10.2308/aud.2009.28.2.305</a>.
</div>
<div id="ref-R-pdftools" class="csl-entry" role="listitem">
Ooms, Jeroen. <em>Pdftools: Text Extraction, Rendering and Converting of PDF Documents</em>, 2026. <a href="https://ropensci.r-universe.dev/pdftools">https://ropensci.r-universe.dev/pdftools</a>.
</div>
<div id="ref-R-writexl" class="csl-entry" role="listitem">
Ooms, Jeroen, and Bill Denney. <em>Writexl: Export Data Frames to Excel Xlsx Format</em>, 2026. <a href="https://ropensci.r-universe.dev/writexl">https://ropensci.r-universe.dev/writexl</a>.
</div>
<div id="ref-R-sf" class="csl-entry" role="listitem">
Pebesma, Edzer. <em>Sf: Simple Features for r</em>, 2026. <a href="https://r-spatial.github.io/sf/">https://r-spatial.github.io/sf/</a>.
</div>
<div id="ref-sf2018" class="csl-entry" role="listitem">
———. <span>“<span class="nocase">Simple Features for R: Standardized Support for Spatial Vector Data</span>.”</span> <em><span>The R Journal</span></em> 10, no. 1 (2018): 439–46. <a href="https://doi.org/10.32614/RJ-2018-009">https://doi.org/10.32614/RJ-2018-009</a>.
</div>
<div id="ref-sf2023" class="csl-entry" role="listitem">
Pebesma, Edzer, and Roger Bivand. <em><span class="nocase">Spatial Data Science: With applications in R</span></em>. <span>Chapman and Hall/CRC</span>, 2023. <a href="https://doi.org/10.1201/9780429459016">https://doi.org/10.1201/9780429459016</a>.
</div>
<div id="ref-R-ggraph" class="csl-entry" role="listitem">
Pedersen, Thomas Lin. <em>Ggraph: An Implementation of Grammar of Graphics for Graphs and Networks</em>, 2025. <a href="https://ggraph.data-imaginist.com">https://ggraph.data-imaginist.com</a>.
</div>
<div id="ref-R-patchwork" class="csl-entry" role="listitem">
———. <em>Patchwork: The Composer of Plots</em>, 2025. <a href="https://patchwork.data-imaginist.com">https://patchwork.data-imaginist.com</a>.
</div>
<div id="ref-R-PerformanceAnalytics" class="csl-entry" role="listitem">
Peterson, Brian G., and Peter Carl. <em>PerformanceAnalytics: Econometric Tools for Performance and Risk Analysis</em>, 2026. <a href="https://github.com/braverock/PerformanceAnalytics">https://github.com/braverock/PerformanceAnalytics</a>.
</div>
<div id="ref-pinkham" class="csl-entry" role="listitem">
Pinkham, Roger S. <span>“<span class="nocase">On the Distribution of First Significant Digits</span>.”</span> <em>The Annals of Mathematical Statistics</em> 32, no. 4 (1961): 1223–30. <a href="https://doi.org/10.1214/aoms/1177704862">https://doi.org/10.1214/aoms/1177704862</a>.
</div>
<div id="ref-R-base" class="csl-entry" role="listitem">
R Core Team. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing, 2025. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
<div id="ref-R-psych" class="csl-entry" role="listitem">
Revelle, William. <em>Psych: Procedures for Psychological, Psychometric, and Personality Research</em>, 2026. <a href="https://personality-project.org/r/psych/">https://personality-project.org/r/psych/</a>.
</div>
<div id="ref-R-nnet" class="csl-entry" role="listitem">
Ripley, Brian. <em>Nnet: Feed-Forward Neural Networks and Multinomial Log-Linear Models</em>, 2025. <a href="http://www.stats.ox.ac.uk/pub/MASS4/">http://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
<div id="ref-R-MASS" class="csl-entry" role="listitem">
Ripley, Brian, and Bill Venables. <em>MASS: Support Functions and Datasets for Venables and Ripley’s MASS</em>, 2025. <a href="http://www.stats.ox.ac.uk/pub/MASS4/">http://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
<div id="ref-R-broom" class="csl-entry" role="listitem">
Robinson, David, Alex Hayes, Simon Couch, and Emil Hvitfeldt. <em>Broom: Convert Statistical Objects into Tidy Tibbles</em>, 2026. <a href="https://broom.tidymodels.org/">https://broom.tidymodels.org/</a>.
</div>
<div id="ref-R-tidytext" class="csl-entry" role="listitem">
Robinson, David, and Julia Silge. <em>Tidytext: Text Mining Using Dplyr, Ggplot2, and Other Tidy Tools</em>, 2025. <a href="https://juliasilge.github.io/tidytext/">https://juliasilge.github.io/tidytext/</a>.
</div>
<div id="ref-R-openxlsx" class="csl-entry" role="listitem">
Schauberger, Philipp, and Alexander Walker. <em>Openxlsx: Read, Write and Edit Xlsx Files</em>, 2025. <a href="https://ycphs.github.io/openxlsx/index.html">https://ycphs.github.io/openxlsx/index.html</a>.
</div>
<div id="ref-R-GGally" class="csl-entry" role="listitem">
Schloerke, Barret, Di Cook, Joseph Larmarange, Francois Briatte, Moritz Marbach, Edwin Thoen, Amos Elberg, and Jason Crowley. <em>GGally: Extension to Ggplot2</em>, 2025. <a href="https://ggobi.github.io/ggally/">https://ggobi.github.io/ggally/</a>.
</div>
<div id="ref-tidytext2016" class="csl-entry" role="listitem">
Silge, Julia, and David Robinson. <span>“Tidytext: Text Mining and Analysis Using Tidy Data Principles in r.”</span> <em>JOSS</em> 1, no. 3 (2016). <a href="https://doi.org/10.21105/joss.00037">https://doi.org/10.21105/joss.00037</a>.
</div>
<div id="ref-R-ggrepel" class="csl-entry" role="listitem">
Slowikowski, Kamil. <em>Ggrepel: Automatically Position Non-Overlapping Text Labels with Ggplot2</em>, 2026. <a href="https://ggrepel.slowkow.com/">https://ggrepel.slowkow.com/</a>.
</div>
<div id="ref-R-lubridate" class="csl-entry" role="listitem">
Spinu, Vitalie, Garrett Grolemund, and Hadley Wickham. <em>Lubridate: Make Dealing with Dates a Little Easier</em>, 2026. <a href="https://lubridate.tidyverse.org">https://lubridate.tidyverse.org</a>.
</div>
<div id="ref-colorspace2009b" class="csl-entry" role="listitem">
Stauffer, Reto, Georg J. Mayr, Markus Dabernig, and Achim Zeileis. <span>“Somewhere over the Rainbow: How to Make Effective Use of Colors in Meteorological Visualizations.”</span> <em>Bulletin of the American Meteorological Society</em> 96, no. 2 (2009): 203–16. <a href="https://doi.org/10.1175/BAMS-D-13-00155.1">https://doi.org/10.1175/BAMS-D-13-00155.1</a>.
</div>
<div id="ref-R-rpart" class="csl-entry" role="listitem">
Therneau, Terry, and Beth Atkinson. <em>Rpart: Recursive Partitioning and Regression Trees</em>, 2025. <a href="https://github.com/bethatkinson/rpart">https://github.com/bethatkinson/rpart</a>.
</div>
<div id="ref-R-AnomalyDetection" class="csl-entry" role="listitem">
Vallis, Owen S., Jordan Hochenbaum, and Arun Kejariwal. <em>AnomalyDetection: Anomaly Detection Using Seasonal Hybrid Extreme Studentized Deviate Test</em>, 2014. <a href="https://github.com/twitter/AnomalyDetection">https://github.com/twitter/AnomalyDetection</a>.
</div>
<div id="ref-stringdist2014" class="csl-entry" role="listitem">
<span class="nocase">van der Loo, M. P. J.</span> <span>“The Stringdist Package for Approximate String Matching.”</span> <em>The <span>R</span> <span>J</span>ournal</em> 6 (2014): 111–22. <a href="https://journal.r-project.org/articles/RJ-2014-011/">https://journal.r-project.org/articles/RJ-2014-011/</a>.
</div>
<div id="ref-R-stringdist" class="csl-entry" role="listitem">
<span class="nocase">van der Loo, Mark</span>. <em>Stringdist: Approximate String Matching, Fuzzy Text Search, and String Distance Functions</em>, 2026. <a href="https://github.com/markvanderloo/stringdist">https://github.com/markvanderloo/stringdist</a>.
</div>
<div id="ref-validate2021" class="csl-entry" role="listitem">
<span class="nocase">van der Loo, Mark P. J., and Edwin de Jonge</span>. <span>“Data Validation Infrastructure for <span>R</span>.”</span> <em>Journal of Statistical Software</em> 97, no. 10 (2021): 1–31. <a href="https://doi.org/10.18637/jss.v097.i10">https://doi.org/10.18637/jss.v097.i10</a>.
</div>
<div id="ref-R-validate" class="csl-entry" role="listitem">
<span class="nocase">van der Loo, Mark, and Edwin de Jonge</span>. <em>Validate: Data Validation Infrastructure</em>, 2025. <a href="https://github.com/data-cleaning/validate">https://github.com/data-cleaning/validate</a>.
</div>
<div id="ref-MASS2002" class="csl-entry" role="listitem">
Venables, W. N., and B. D. Ripley. <em>Modern Applied Statistics with s</em>. Fourth. New York: Springer, 2002. <a href="https://www.stats.ox.ac.uk/pub/MASS4/">https://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
<div id="ref-nnet2002" class="csl-entry" role="listitem">
———. <em>Modern Applied Statistics with s</em>. Fourth. New York: Springer, 2002. <a href="https://www.stats.ox.ac.uk/pub/MASS4/">https://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
<div id="ref-R-skimr" class="csl-entry" role="listitem">
Waring, Elin, Michael Quinn, Amelia McNamara, Eduardo Arino de la Rubia, Hao Zhu, and Shannon Ellis. <em>Skimr: Compact and Flexible Summaries of Data</em>, 2026. <a href="https://docs.ropensci.org/skimr/">https://docs.ropensci.org/skimr/</a>.
</div>
<div id="ref-layered-grammar" class="csl-entry" role="listitem">
Wickham, Hadley. <span>“A Layered Grammar of Graphics.”</span> <em>Journal of Computational and Graphical Statistics</em> 19, no. 1 (2010): 3–28. <a href="https://doi.org/10.1198/jcgs.2009.07098">https://doi.org/10.1198/jcgs.2009.07098</a>.
</div>
<div id="ref-R-conflicted" class="csl-entry" role="listitem">
———. <em>Conflicted: An Alternative Conflict Resolution Strategy</em>, 2023. <a href="https://conflicted.r-lib.org/">https://conflicted.r-lib.org/</a>.
</div>
<div id="ref-R-forcats" class="csl-entry" role="listitem">
———. <em>Forcats: Tools for Working with Categorical Variables (Factors)</em>, 2025. <a href="https://forcats.tidyverse.org/">https://forcats.tidyverse.org/</a>.
</div>
<div id="ref-ggplot22016" class="csl-entry" role="listitem">
———. <em>Ggplot2: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York, 2016. <a href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>.
</div>
<div id="ref-JSSv021i12" class="csl-entry" role="listitem">
———. <span>“Reshaping Data with the Reshape Package.”</span> <em>Journal of Statistical Software</em> 21, no. 12 (2007): 1–20. <a href="https://doi.org/10.18637/jss.v021.i12">https://doi.org/10.18637/jss.v021.i12</a>.
</div>
<div id="ref-R-stringr" class="csl-entry" role="listitem">
———. <em>Stringr: Simple, Consistent Wrappers for Common String Operations</em>, 2025. <a href="https://stringr.tidyverse.org">https://stringr.tidyverse.org</a>.
</div>
<div id="ref-JSSv059i10" class="csl-entry" role="listitem">
———. <span>“Tidy Data.”</span> <em>Journal of Statistical Software</em> 59, no. 10 (2014): 1–23. <a href="https://doi.org/10.18637/jss.v059.i10">https://doi.org/10.18637/jss.v059.i10</a>.
</div>
<div id="ref-R-tidyverse" class="csl-entry" role="listitem">
———. <em>Tidyverse: Easily Install and Load the Tidyverse</em>, 2023. <a href="https://tidyverse.tidyverse.org">https://tidyverse.tidyverse.org</a>.
</div>
<div id="ref-tidyverse2019" class="csl-entry" role="listitem">
Wickham, Hadley, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D’Agostino McGowan, Romain François, Garrett Grolemund, et al. <span>“Welcome to the <span class="nocase">tidyverse</span>.”</span> <em>Journal of Open Source Software</em> 4, no. 43 (2019): 1686. <a href="https://doi.org/10.21105/joss.01686">https://doi.org/10.21105/joss.01686</a>.
</div>
<div id="ref-R-readxl" class="csl-entry" role="listitem">
Wickham, Hadley, and Jennifer Bryan. <em>Readxl: Read Excel Files</em>, 2025. <a href="https://readxl.tidyverse.org">https://readxl.tidyverse.org</a>.
</div>
<div id="ref-R-ggplot2" class="csl-entry" role="listitem">
<span class="nocase">Wickham, Hadley, Winston Chang, Lionel Henry, Thomas Lin Pedersen, Kohske Takahashi, Claus Wilke, Kara Woo, Hiroaki Yutani, Dewey Dunnington, and Teun van den Brand</span>. <em>Ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics</em>, 2026. <a href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>.
</div>
<div id="ref-R-dplyr" class="csl-entry" role="listitem">
Wickham, Hadley, Romain François, Lionel Henry, Kirill Müller, and Davis Vaughan. <em>Dplyr: A Grammar of Data Manipulation</em>, 2026. <a href="https://dplyr.tidyverse.org">https://dplyr.tidyverse.org</a>.
</div>
<div id="ref-R-dbplyr" class="csl-entry" role="listitem">
Wickham, Hadley, Maximilian Girlich, and Edgar Ruiz. <em>Dbplyr: A Dplyr Back End for Databases</em>, 2026. <a href="https://dbplyr.tidyverse.org/">https://dbplyr.tidyverse.org/</a>.
</div>
<div id="ref-R-purrr" class="csl-entry" role="listitem">
Wickham, Hadley, and Lionel Henry. <em>Purrr: Functional Programming Tools</em>, 2026. <a href="https://purrr.tidyverse.org/">https://purrr.tidyverse.org/</a>.
</div>
<div id="ref-R-readr" class="csl-entry" role="listitem">
Wickham, Hadley, Jim Hester, and Jennifer Bryan. <em>Readr: Read Rectangular Text Data</em>, 2026. <a href="https://readr.tidyverse.org">https://readr.tidyverse.org</a>.
</div>
<div id="ref-R-scales" class="csl-entry" role="listitem">
Wickham, Hadley, Thomas Lin Pedersen, and Dana Seidel. <em>Scales: Scale Functions for Visualization</em>, 2025. <a href="https://scales.r-lib.org">https://scales.r-lib.org</a>.
</div>
<div id="ref-R-tidyr" class="csl-entry" role="listitem">
Wickham, Hadley, Davis Vaughan, and Maximilian Girlich. <em>Tidyr: Tidy Messy Data</em>, 2025. <a href="https://tidyr.tidyverse.org">https://tidyr.tidyverse.org</a>.
</div>
<div id="ref-R-ranger" class="csl-entry" role="listitem">
Wright, Marvin N. <em>Ranger: A Fast Implementation of Random Forests</em>, 2026. <a href="https://imbs-hl.github.io/ranger/">https://imbs-hl.github.io/ranger/</a>.
</div>
<div id="ref-ranger2017" class="csl-entry" role="listitem">
Wright, Marvin N., and Andreas Ziegler. <span>“<span class="nocase">ranger</span>: A Fast Implementation of Random Forests for High Dimensional Data in <span>C++</span> and <span>R</span>.”</span> <em>Journal of Statistical Software</em> 77, no. 1 (2017): 1–17. <a href="https://doi.org/10.18637/jss.v077.i01">https://doi.org/10.18637/jss.v077.i01</a>.
</div>
<div id="ref-xie2015" class="csl-entry" role="listitem">
Xie, Yihui. <em>Dynamic Documents with <span>R</span> and Knitr</em>. 2nd ed. Boca Raton, Florida: Chapman; Hall/CRC, 2015. <a href="http://yihui.name/knitr/">http://yihui.name/knitr/</a>.
</div>
<div id="ref-knitr2015" class="csl-entry" role="listitem">
———. <em>Dynamic Documents with <span>R</span> and Knitr</em>. 2nd ed. Boca Raton, Florida: Chapman; Hall/CRC, 2015. <a href="https://yihui.org/knitr/">https://yihui.org/knitr/</a>.
</div>
<div id="ref-knitr2014" class="csl-entry" role="listitem">
———. <span>“Knitr: A Comprehensive Tool for Reproducible Research in <span>R</span>.”</span> In <em>Implementing Reproducible Computational Research</em>, edited by Victoria Stodden, Friedrich Leisch, and Roger D. Peng. Chapman; Hall/CRC, 2014.
</div>
<div id="ref-R-knitr" class="csl-entry" role="listitem">
———. <em>Knitr: A General-Purpose Package for Dynamic Report Generation in r</em>, 2025. <a href="https://yihui.org/knitr/">https://yihui.org/knitr/</a>.
</div>
<div id="ref-colorspace2020a" class="csl-entry" role="listitem">
Zeileis, Achim, Jason C. Fisher, Kurt Hornik, Ross Ihaka, Claire D. McWhite, Paul Murrell, Reto Stauffer, and Claus O. Wilke. <span>“<span class="nocase">colorspace</span>: A Toolbox for Manipulating and Assessing Colors and Palettes.”</span> <em>Journal of Statistical Software</em> 96, no. 1 (2020): 1–49. <a href="https://doi.org/10.18637/jss.v096.i01">https://doi.org/10.18637/jss.v096.i01</a>.
</div>
<div id="ref-zoo2005" class="csl-entry" role="listitem">
Zeileis, Achim, and Gabor Grothendieck. <span>“Zoo: S3 Infrastructure for Regular and Irregular Time Series.”</span> <em>Journal of Statistical Software</em> 14, no. 6 (2005): 1–27. <a href="https://doi.org/10.18637/jss.v014.i06">https://doi.org/10.18637/jss.v014.i06</a>.
</div>
<div id="ref-R-zoo" class="csl-entry" role="listitem">
Zeileis, Achim, Gabor Grothendieck, and Jeffrey A. Ryan. <em>Zoo: S3 Infrastructure for Regular and Irregular Time Series (z’s Ordered Observations)</em>, 2025. <a href="https://zoo.R-Forge.R-project.org/">https://zoo.R-Forge.R-project.org/</a>.
</div>
<div id="ref-colorspace2009a" class="csl-entry" role="listitem">
Zeileis, Achim, Kurt Hornik, and Paul Murrell. <span>“Escaping <span>RGB</span>land: Selecting Colors for Statistical Graphics.”</span> <em>Computational Statistics &amp; Data Analysis</em> 53, no. 9 (2009): 3259–70. <a href="https://doi.org/10.1016/j.csda.2008.11.033">https://doi.org/10.1016/j.csda.2008.11.033</a>.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/anilyayavar\.github\.io\/new-book\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./19-nigrini-tests.html" class="pagination-link" aria-label="Nigrini's Tests for Unusual Amounts">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Nigrini’s Tests for Unusual Amounts</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./15-stringdist.html" class="pagination-link" aria-label="String Similarity and Fuzzy Matching">
        <span class="nav-page-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">String Similarity and Fuzzy Matching</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Built with <a href="https://www.r-project.org">R</a> and <a href="https://quarto.org">Quarto</a></p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/anilyayavar/new-book/edit/master/20-duplicates.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/anilyayavar/new-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>