<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Chapter 14 Data Transformation in dplyr | R for Audit Analytics</title>

    <meta name="author" content="Anil Goyal" />
  
   <meta name="description" content="This book is intended for auditors performing exploratory data analytics using R programming language, mainly Base R and Tidyverse." />
   <meta name="generator" content="placeholder" />
  <meta property="og:title" content="Chapter 14 Data Transformation in dplyr | R for Audit Analytics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://anilyayavar.github.io/new-book/" />
  <meta property="og:image" content="https://anilyayavar.github.io/new-book/images/cover.jpg" />
  <meta property="og:description" content="This book is intended for auditors performing exploratory data analytics using R programming language, mainly Base R and Tidyverse." />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 14 Data Transformation in dplyr | R for Audit Analytics" />
  
  <meta name="twitter:description" content="This book is intended for auditors performing exploratory data analytics using R programming language, mainly Base R and Tidyverse." />
  <meta name="twitter:image" content="https://anilyayavar.github.io/new-book/images/cover.jpg" />
  <!-- JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script>
    <script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet" />
    <script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script>
    <script src="libs/bs3compat-0.8.0/transition.js"></script>
    <script src="libs/bs3compat-0.8.0/tabs.js"></script>
    <script src="libs/bs3compat-0.8.0/bs3compat.js"></script>
    <link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet" />
    <script src="libs/bs4_book-1.0.0/bs4_book.js"></script>
    <script src="libs/kePrint-0.0.1/kePrint.js"></script>
    <link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script>

  <!-- CSS -->
  <style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
    <style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 0em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
      <link rel="stylesheet" href="style.css" />
  
</head>

<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book">
    <a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">R for Audit Analytics</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>

      <nav aria-label="Table of contents">
        <h2>Table of contents</h2>
        <div id="book-toc"></div>

        <div class="book-extra">
          <p><a id="book-repo" href="#">View book source <i class="fab fa-github"></i></a></li></p>
        </div>
      </nav>
    </div>
  </header>

  <main class="col-sm-12 col-md-9 col-lg-7" id="content">
<div id="DPLYRR" class="section level1" number="14">
<h1><span class="header-section-number">Chapter 14</span> Data Transformation in <code>dplyr</code></h1>
<p><strong>Prerequisites</strong>
Obviously <code>dplyr</code><span class="citation"><a href="#fn22" class="footnote-ref" id="fnref22"><sup>22</sup></a></span> will be needed. This package also comes with matrittr pipe i.e. <code>%&gt;%</code> and therefore in dplyr syntax we will be using these pipes. <code>library(magrittr)</code> is not needed.</p>
<div class="sourceCode" id="cb850"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb850-1"><a href="DPLYRR.html#cb850-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb850-2"><a href="DPLYRR.html#cb850-2" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code></pre></div>
<p>The package <code>dplyr</code> (<a href="DPLYRR.html#fig:dplyrr">14.1</a>) calls its functions as ‘verbs’ because these are actually doing some action. So <code>dplyr verbs</code> can be divided in three classifications depending upon where they operate -</p>
<ul>
<li>‘Row’ verbs that operate on Rows</li>
<li>‘Column’ verbs</li>
<li>‘group’ verbs that operate on table split into different groups.</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:dplyrr"></span>
<img src="images/dplyr.png" alt="Package Dplyr" width="99%" />
<p class="caption">
Figure 14.1: Package Dplyr
</p>
</div>
<p>Let’s learn each of these -</p>
<div id="column-verb-select" class="section level2" number="14.1">
<h2><span class="header-section-number">14.1</span> Column verb <code>select()</code></h2>
<p>In real world data sets we will often come across with data frames having numerous columns. However for many of the data analysis tasks, most of these columns are not needed. As already stated <code>select</code> (figure <a href="DPLYRR.html#fig:selectr">14.2</a>) operates on columns. Like <code>SELECT</code> in <code>SQL</code>, it just <em>select</em> the column(s) from the given data frame. The basic syntax is - <code>select(data_frame, column_names, ...)</code>. So with pipes the same syntax goes like this</p>
<pre><code>data_frame %&gt;% 
  select(column_name)</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:selectr"></span>
<img src="images/select_dplyr.png" alt="Illustration of dplyr::select()" width="99%" />
<p class="caption">
Figure 14.2: Illustration of dplyr::select()
</p>
</div>
<p>For example, let’s try our hands on <code>mtcars</code> dataset.<br />
Example-1</p>
<div class="sourceCode" id="cb852"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb852-1"><a href="DPLYRR.html#cb852-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb852-2"><a href="DPLYRR.html#cb852-2" tabindex="-1"></a>  <span class="fu">select</span>(mpg)</span></code></pre></div>
<pre><code>##                      mpg
## Mazda RX4           21.0
## Mazda RX4 Wag       21.0
## Datsun 710          22.8
## Hornet 4 Drive      21.4
## Hornet Sportabout   18.7
## Valiant             18.1
## Duster 360          14.3
## Merc 240D           24.4
## Merc 230            22.8
## Merc 280            19.2
## Merc 280C           17.8
## Merc 450SE          16.4
## Merc 450SL          17.3
## Merc 450SLC         15.2
## Cadillac Fleetwood  10.4
## Lincoln Continental 10.4
## Chrysler Imperial   14.7
## Fiat 128            32.4
## Honda Civic         30.4
## Toyota Corolla      33.9
## Toyota Corona       21.5
## Dodge Challenger    15.5
## AMC Javelin         15.2
## Camaro Z28          13.3
## Pontiac Firebird    19.2
## Fiat X1-9           27.3
## Porsche 914-2       26.0
## Lotus Europa        30.4
## Ford Pantera L      15.8
## Ferrari Dino        19.7
## Maserati Bora       15.0
## Volvo 142E          21.4</code></pre>
<p><strong>Note</strong> that output is still a data frame unlike the <code>mtcars[['mpg']]</code> which returns a vector. We can subset multiple columns here. Example-2</p>
<div class="sourceCode" id="cb854"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb854-1"><a href="DPLYRR.html#cb854-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb854-2"><a href="DPLYRR.html#cb854-2" tabindex="-1"></a>  <span class="fu">select</span>(mpg, qsec) <span class="sc">%&gt;%</span> </span>
<span id="cb854-3"><a href="DPLYRR.html#cb854-3" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##                    mpg  qsec
## Mazda RX4         21.0 16.46
## Mazda RX4 Wag     21.0 17.02
## Datsun 710        22.8 18.61
## Hornet 4 Drive    21.4 19.44
## Hornet Sportabout 18.7 17.02
## Valiant           18.1 20.22</code></pre>
<p>We can also provide column numbers instead of names. Example-3</p>
<div class="sourceCode" id="cb856"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb856-1"><a href="DPLYRR.html#cb856-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb856-2"><a href="DPLYRR.html#cb856-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">4</span>, <span class="dv">6</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb856-3"><a href="DPLYRR.html#cb856-3" tabindex="-1"></a>  <span class="fu">tail</span>()</span></code></pre></div>
<pre><code>##                 hp    wt
## Porsche 914-2   91 2.140
## Lotus Europa   113 1.513
## Ford Pantera L 264 3.170
## Ferrari Dino   175 2.770
## Maserati Bora  335 3.570
## Volvo 142E     109 2.780</code></pre>
<p>We can also use <code>select</code> to reorder the columns in output, by using a <code>dplyr</code> <em>helping verb</em> <code>everything()</code> which is basically <em>everything else.</em> See this example-</p>
<div class="sourceCode" id="cb858"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb858-1"><a href="DPLYRR.html#cb858-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb858-2"><a href="DPLYRR.html#cb858-2" tabindex="-1"></a>  <span class="fu">select</span>(qsec, mpg, <span class="fu">everything</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb858-3"><a href="DPLYRR.html#cb858-3" tabindex="-1"></a>  <span class="fu">names</span>()</span></code></pre></div>
<pre><code>##  [1] &quot;qsec&quot; &quot;mpg&quot;  &quot;cyl&quot;  &quot;disp&quot; &quot;hp&quot;   &quot;drat&quot; &quot;wt&quot;   &quot;vs&quot;   &quot;am&quot;   &quot;gear&quot;
## [11] &quot;carb&quot;</code></pre>
<p>We may also use mix and match of <em>column names</em> and <em>column numbers</em>. See</p>
<div class="sourceCode" id="cb860"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb860-1"><a href="DPLYRR.html#cb860-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb860-2"><a href="DPLYRR.html#cb860-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">5</span>, <span class="dv">7</span>, mpg, <span class="fu">everything</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb860-3"><a href="DPLYRR.html#cb860-3" tabindex="-1"></a>  <span class="fu">names</span>()</span></code></pre></div>
<pre><code>##  [1] &quot;drat&quot; &quot;qsec&quot; &quot;mpg&quot;  &quot;cyl&quot;  &quot;disp&quot; &quot;hp&quot;   &quot;wt&quot;   &quot;vs&quot;   &quot;am&quot;   &quot;gear&quot;
## [11] &quot;carb&quot;</code></pre>
<p>Operator <code>:</code> can also be used with column names. Ex-</p>
<div class="sourceCode" id="cb862"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb862-1"><a href="DPLYRR.html#cb862-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb862-2"><a href="DPLYRR.html#cb862-2" tabindex="-1"></a>  <span class="fu">select</span>(mpg<span class="sc">:</span>drat) <span class="sc">%&gt;%</span> </span>
<span id="cb862-3"><a href="DPLYRR.html#cb862-3" tabindex="-1"></a>  <span class="fu">head</span>(<span class="at">n=</span><span class="dv">4</span>)</span></code></pre></div>
<pre><code>##                 mpg cyl disp  hp drat
## Mazda RX4      21.0   6  160 110 3.90
## Mazda RX4 Wag  21.0   6  160 110 3.90
## Datsun 710     22.8   4  108  93 3.85
## Hornet 4 Drive 21.4   6  258 110 3.08</code></pre>
<p><strong>Other helping verbs</strong>
There are other helping verbs, apart from <code>everything()</code> that can be used within <code>select()</code> just to eliminate need to type the column names and select columns based on some conditions. These verbs are self explanatory-</p>
<ul>
<li><code>starts_with('ABC')</code> will select all columns the names of which <strong>starts with</strong> string <code>ABC</code></li>
<li><code>ends_with('ABC')</code> will select all columns the names of which <strong>ends with</strong> string <code>ABC</code></li>
<li><code>contains('ABC')</code> will select all columns the names of which <strong>contains</strong> string <code>ABC</code></li>
<li><code>num_range('A', 1:3)</code> will select all columns named <code>A1</code>, <code>A2</code> and <code>A3</code></li>
</ul>
<p>Some Examples.</p>
<ol style="list-style-type: decimal">
<li>This syntax will select all columns which ends with <code>"color"</code> in column names.</li>
</ol>
<div class="sourceCode" id="cb864"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb864-1"><a href="DPLYRR.html#cb864-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb864-2"><a href="DPLYRR.html#cb864-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">ends_with</span>(<span class="st">&#39;color&#39;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 87 × 3
##    hair_color    skin_color  eye_color
##    &lt;chr&gt;         &lt;chr&gt;       &lt;chr&gt;    
##  1 blond         fair        blue     
##  2 &lt;NA&gt;          gold        yellow   
##  3 &lt;NA&gt;          white, blue red      
##  4 none          white       yellow   
##  5 brown         light       brown    
##  6 brown, grey   light       blue     
##  7 brown         light       blue     
##  8 &lt;NA&gt;          white, red  red      
##  9 black         light       brown    
## 10 auburn, white fair        blue-gray
## # ℹ 77 more rows</code></pre>
<p>Example-2: This syntax will select all columns contains characters <code>"or"</code> in column names.</p>
<div class="sourceCode" id="cb866"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb866-1"><a href="DPLYRR.html#cb866-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb866-2"><a href="DPLYRR.html#cb866-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">&#39;or&#39;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 87 × 4
##    hair_color    skin_color  eye_color homeworld
##    &lt;chr&gt;         &lt;chr&gt;       &lt;chr&gt;     &lt;chr&gt;    
##  1 blond         fair        blue      Tatooine 
##  2 &lt;NA&gt;          gold        yellow    Tatooine 
##  3 &lt;NA&gt;          white, blue red       Naboo    
##  4 none          white       yellow    Tatooine 
##  5 brown         light       brown     Alderaan 
##  6 brown, grey   light       blue      Tatooine 
##  7 brown         light       blue      Tatooine 
##  8 &lt;NA&gt;          white, red  red       Tatooine 
##  9 black         light       brown     Tatooine 
## 10 auburn, white fair        blue-gray Stewjon  
## # ℹ 77 more rows</code></pre>
<p><strong>Using <code>where()</code></strong>: This selection helper selects the variables for which a <em>function</em> when applied to column names, returns <code>TRUE</code>.</p>
<p>Example-3: This syntax will select all numeric columns from the dataset.</p>
<div class="sourceCode" id="cb868"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb868-1"><a href="DPLYRR.html#cb868-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb868-2"><a href="DPLYRR.html#cb868-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric))</span></code></pre></div>
<pre><code>## # A tibble: 87 × 3
##    height  mass birth_year
##     &lt;int&gt; &lt;dbl&gt;      &lt;dbl&gt;
##  1    172    77       19  
##  2    167    75      112  
##  3     96    32       33  
##  4    202   136       41.9
##  5    150    49       19  
##  6    178   120       52  
##  7    165    75       47  
##  8     97    32       NA  
##  9    183    84       24  
## 10    182    77       57  
## # ℹ 77 more rows</code></pre>
</div>
<div id="column-verbmutate" class="section level2" number="14.2">
<h2><span class="header-section-number">14.2</span> Column verb<code>mutate()</code></h2>
<p>This perhaps is one of the most important functions in <code>dplyr</code> kitty. It enables us to create new column(s) that are functions of one or more existing columns. Refer figure <a href="DPLYRR.html#fig:mutater">14.3</a></p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:mutater"></span>
<img src="images/mutate_dplyr.png" alt="Illustration of dplyr::mutate()" width="99%" />
<p class="caption">
Figure 14.3: Illustration of dplyr::mutate()
</p>
</div>
<p>More than one column can be added simultaneously. Newly created column may also be used for creation of another new column. See example.</p>
<div class="sourceCode" id="cb870"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb870-1"><a href="DPLYRR.html#cb870-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb870-2"><a href="DPLYRR.html#cb870-2" tabindex="-1"></a>  <span class="fu">select</span>(name<span class="sc">:</span>mass) <span class="sc">%&gt;%</span> </span>
<span id="cb870-3"><a href="DPLYRR.html#cb870-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">name_upper =</span> <span class="fu">toupper</span>(name),</span>
<span id="cb870-4"><a href="DPLYRR.html#cb870-4" tabindex="-1"></a>         <span class="at">BMI =</span> mass<span class="sc">/</span>(height<span class="sc">/</span><span class="dv">100</span>)<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## # A tibble: 87 × 5
##    name               height  mass name_upper           BMI
##    &lt;chr&gt;               &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt;
##  1 Luke Skywalker        172    77 LUKE SKYWALKER      26.0
##  2 C-3PO                 167    75 C-3PO               26.9
##  3 R2-D2                  96    32 R2-D2               34.7
##  4 Darth Vader           202   136 DARTH VADER         33.3
##  5 Leia Organa           150    49 LEIA ORGANA         21.8
##  6 Owen Lars             178   120 OWEN LARS           37.9
##  7 Beru Whitesun Lars    165    75 BERU WHITESUN LARS  27.5
##  8 R5-D4                  97    32 R5-D4               34.0
##  9 Biggs Darklighter     183    84 BIGGS DARKLIGHTER   25.1
## 10 Obi-Wan Kenobi        182    77 OBI-WAN KENOBI      23.2
## # ℹ 77 more rows</code></pre>
<p>By default the new column will be added to the last of data frame. As shown in above example, more operations can be combined in one using <code>%&gt;%</code>. There is a cousin <code>transmute()</code> of <em>mutate</em> which drops all the old columns and keeps only newly created columns. Example</p>
<div class="sourceCode" id="cb872"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb872-1"><a href="DPLYRR.html#cb872-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb872-2"><a href="DPLYRR.html#cb872-2" tabindex="-1"></a>  <span class="fu">transmute</span>(<span class="at">name_upper =</span> <span class="fu">toupper</span>(name))</span></code></pre></div>
<pre><code>## # A tibble: 87 × 1
##    name_upper        
##    &lt;chr&gt;             
##  1 LUKE SKYWALKER    
##  2 C-3PO             
##  3 R2-D2             
##  4 DARTH VADER       
##  5 LEIA ORGANA       
##  6 OWEN LARS         
##  7 BERU WHITESUN LARS
##  8 R5-D4             
##  9 BIGGS DARKLIGHTER 
## 10 OBI-WAN KENOBI    
## # ℹ 77 more rows</code></pre>
<p><strong>Other useful dplyr functions</strong> Another good use of <code>mutate</code> is to generate summarised result and display it corresponding to each row in data. For example if the requirement is to calculate proportion of say <code>wt</code> column in <code>mtcars</code> data.</p>
<div class="sourceCode" id="cb874"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb874-1"><a href="DPLYRR.html#cb874-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb874-2"><a href="DPLYRR.html#cb874-2" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb874-3"><a href="DPLYRR.html#cb874-3" tabindex="-1"></a>  <span class="fu">select</span>(wt) <span class="sc">%&gt;%</span> </span>
<span id="cb874-4"><a href="DPLYRR.html#cb874-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_wt =</span> <span class="fu">sum</span>(wt),</span>
<span id="cb874-5"><a href="DPLYRR.html#cb874-5" tabindex="-1"></a>         <span class="at">wt_proportion =</span> wt<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span>total_wt) </span></code></pre></div>
<pre><code>##                      wt total_wt wt_proportion
## Mazda RX4         2.620    17.93      14.61238
## Mazda RX4 Wag     2.875    17.93      16.03458
## Datsun 710        2.320    17.93      12.93921
## Hornet 4 Drive    3.215    17.93      17.93084
## Hornet Sportabout 3.440    17.93      19.18572
## Valiant           3.460    17.93      19.29727</code></pre>
<ol style="list-style-type: decimal">
<li><code>n()</code> is used to count number of rows</li>
<li><code>n_distinct()</code> is used to count number of distinct values for the given variable</li>
</ol>
<div class="sourceCode" id="cb876"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb876-1"><a href="DPLYRR.html#cb876-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb876-2"><a href="DPLYRR.html#cb876-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb876-3"><a href="DPLYRR.html#cb876-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_cars =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb876-4"><a href="DPLYRR.html#cb876-4" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat total_cars
## Mazda RX4         21.0   6  160 110 3.90         32
## Mazda RX4 Wag     21.0   6  160 110 3.90         32
## Datsun 710        22.8   4  108  93 3.85         32
## Hornet 4 Drive    21.4   6  258 110 3.08         32
## Hornet Sportabout 18.7   8  360 175 3.15         32
## Valiant           18.1   6  225 105 2.76         32</code></pre>
</div>
<div id="column-verb-rename" class="section level2" number="14.3">
<h2><span class="header-section-number">14.3</span> Column verb <code>rename()</code></h2>
<p>It is used to <em>rename</em> the column names. Refer figure <a href="DPLYRR.html#fig:renamer">14.4</a> for illustration.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:renamer"></span>
<img src="images/rename_dplyr.png" alt="Illustration of dplyr::rename()" width="99%" />
<p class="caption">
Figure 14.4: Illustration of dplyr::rename()
</p>
</div>
<p>See this example</p>
<div class="sourceCode" id="cb878"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb878-1"><a href="DPLYRR.html#cb878-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb878-2"><a href="DPLYRR.html#cb878-2" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">miles_per_gallon =</span> mpg) <span class="sc">%&gt;%</span> </span>
<span id="cb878-3"><a href="DPLYRR.html#cb878-3" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##               miles_per_gallon cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4                 21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag             21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710                22.8   4  108  93 3.85 2.320 18.61  1  1    4    1</code></pre>
<p><strong>Note</strong> that <code>select</code> can also rename the columns but will drop all unselected columns. Check this</p>
<div class="sourceCode" id="cb880"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb880-1"><a href="DPLYRR.html#cb880-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb880-2"><a href="DPLYRR.html#cb880-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">miles_per_gallon =</span> mpg) <span class="sc">%&gt;%</span> </span>
<span id="cb880-3"><a href="DPLYRR.html#cb880-3" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##               miles_per_gallon
## Mazda RX4                 21.0
## Mazda RX4 Wag             21.0
## Datsun 710                22.8</code></pre>
</div>
<div id="column-verb-relocate" class="section level2" number="14.4">
<h2><span class="header-section-number">14.4</span> Column verb <code>relocate()</code></h2>
<p>It <em>relocates</em> column or block of columns simultaneosly either before the column mentioned in argument <code>.before</code> or after mentioned in <code>.after</code>. See the example-</p>
<div class="sourceCode" id="cb882"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb882-1"><a href="DPLYRR.html#cb882-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb882-2"><a href="DPLYRR.html#cb882-2" tabindex="-1"></a>  <span class="fu">relocate</span>(<span class="fu">ends_with</span>(<span class="st">&#39;color&#39;</span>), <span class="at">.after =</span> name) <span class="sc">%&gt;%</span> </span>
<span id="cb882-3"><a href="DPLYRR.html#cb882-3" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 14
##   name      hair_color skin_color eye_color height  mass birth_year sex   gender
##   &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;      &lt;int&gt; &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
## 1 Luke Sky… blond      fair       blue         172    77       19   male  mascu…
## 2 C-3PO     &lt;NA&gt;       gold       yellow       167    75      112   none  mascu…
## 3 R2-D2     &lt;NA&gt;       white, bl… red           96    32       33   none  mascu…
## 4 Darth Va… none       white      yellow       202   136       41.9 male  mascu…
## 5 Leia Org… brown      light      brown        150    49       19   fema… femin…
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
</div>
<div id="row-verb-filter" class="section level2" number="14.5">
<h2><span class="header-section-number">14.5</span> Row verb <code>filter</code></h2>
<p>This verb/function is used to subset the data, or in other words filter rows of data frame based on certain condition. Refer figure <a href="DPLYRR.html#fig:filterr">14.5</a> for illustration.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:filterr"></span>
<img src="images/filter_dplyr.png" alt="Illustration of dplyr::filter()" width="99%" />
<p class="caption">
Figure 14.5: Illustration of dplyr::filter()
</p>
</div>
<p>See this example-</p>
<div class="sourceCode" id="cb884"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb884-1"><a href="DPLYRR.html#cb884-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb884-2"><a href="DPLYRR.html#cb884-2" tabindex="-1"></a>  <span class="fu">filter</span>(eye_color <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;red&#39;</span>, <span class="st">&#39;yellow&#39;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 16 × 14
##    name     height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 C-3PO       167    75 &lt;NA&gt;       gold       yellow         112   none  mascu…
##  2 R2-D2        96    32 &lt;NA&gt;       white, bl… red             33   none  mascu…
##  3 Darth V…    202   136 none       white      yellow          41.9 male  mascu…
##  4 R5-D4        97    32 &lt;NA&gt;       white, red red             NA   none  mascu…
##  5 Palpati…    170    75 grey       pale       yellow          82   male  mascu…
##  6 IG-88       200   140 none       metal      red             15   none  mascu…
##  7 Bossk       190   113 none       green      red             53   male  mascu…
##  8 Nute Gu…    191    90 none       mottled g… red             NA   male  mascu…
##  9 Watto       137    NA black      blue, grey yellow          NA   male  mascu…
## 10 Darth M…    175    80 none       red        yellow          54   male  mascu…
## 11 Dud Bolt     94    45 none       blue, grey yellow          NA   male  mascu…
## 12 Ki-Adi-…    198    82 white      pale       yellow          92   male  mascu…
## 13 Yarael …    264    NA none       white      yellow          NA   male  mascu…
## 14 Poggle …    183    80 none       green      yellow          NA   male  mascu…
## 15 Zam Wes…    168    55 blonde     fair, gre… yellow          NA   fema… femin…
## 16 Dexter …    198   102 none       brown      yellow          NA   male  mascu…
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<p>Multiple conditions can be passed simultaneously. Example</p>
<div class="sourceCode" id="cb886"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb886-1"><a href="DPLYRR.html#cb886-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb886-2"><a href="DPLYRR.html#cb886-2" tabindex="-1"></a>  <span class="fu">filter</span>(skin_color <span class="sc">==</span> <span class="st">&#39;white&#39;</span>,</span>
<span id="cb886-3"><a href="DPLYRR.html#cb886-3" tabindex="-1"></a>         height <span class="sc">&gt;=</span> <span class="dv">150</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 14
##   name      height  mass hair_color skin_color eye_color birth_year sex   gender
##   &lt;chr&gt;      &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
## 1 Darth Va…    202   136 none       white      yellow          41.9 male  mascu…
## 2 Yarael P…    264    NA none       white      yellow          NA   male  mascu…
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<p><strong>Note</strong> that these conditions act simultaneously as in operator <code>AND</code> is used. So if <code>OR</code> is to be used, use <code>|</code> explicitly</p>
<div class="sourceCode" id="cb888"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb888-1"><a href="DPLYRR.html#cb888-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb888-2"><a href="DPLYRR.html#cb888-2" tabindex="-1"></a>  <span class="fu">filter</span>(skin_color <span class="sc">==</span> <span class="st">&#39;white&#39;</span> <span class="sc">|</span> height <span class="sc">&gt;=</span> <span class="dv">150</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb888-3"><a href="DPLYRR.html#cb888-3" tabindex="-1"></a>  <span class="fu">nrow</span>()</span></code></pre></div>
<pre><code>## [1] 71</code></pre>
</div>
<div id="slice_func" class="section level2" number="14.6">
<h2><span class="header-section-number">14.6</span> Row verbs <code>slice()</code> / <code>slice_*()</code></h2>
<p><code>slice()</code> and its cousins also filters rows but based on rows placement. So, <code>data_fr %&gt;% slice(1:5)</code> will filter out first five rows of the <code>data_fr</code>. See example</p>
<div class="sourceCode" id="cb890"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb890-1"><a href="DPLYRR.html#cb890-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb890-2"><a href="DPLYRR.html#cb890-2" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">4</span><span class="sc">:</span><span class="dv">10</span>) <span class="co"># filter 4 to 10th row</span></span></code></pre></div>
<pre><code>## # A tibble: 7 × 14
##   name      height  mass hair_color skin_color eye_color birth_year sex   gender
##   &lt;chr&gt;      &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
## 1 Darth Va…    202   136 none       white      yellow          41.9 male  mascu…
## 2 Leia Org…    150    49 brown      light      brown           19   fema… femin…
## 3 Owen Lars    178   120 brown, gr… light      blue            52   male  mascu…
## 4 Beru Whi…    165    75 brown      light      blue            47   fema… femin…
## 5 R5-D4         97    32 &lt;NA&gt;       white, red red             NA   none  mascu…
## 6 Biggs Da…    183    84 black      light      brown           24   male  mascu…
## 7 Obi-Wan …    182    77 auburn, w… fair       blue-gray       57   male  mascu…
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<p>Other <code>slice()</code> cousins -</p>
<ul>
<li><code>slice_head(5)</code> will slice out first 5 rows</li>
<li><code>slice_tail(10)</code> will slice out last 10 rows</li>
<li><code>slice_min()</code> or <code>slice_max()</code> will slice rows with highest or lowest values of given variable. The full syntax is <code>slice_max(.data, order_by, ..., n, prop, with_ties = TRUE)</code> or equivalent</li>
<li><code>slice_sample()</code> will randomly select the rows. Its syntax is <code>slice_sample(.data, ..., n, prop, weight_by = NULL, replace = FALSE)</code></li>
</ul>
<p>Example-1:</p>
<div class="sourceCode" id="cb892"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb892-1"><a href="DPLYRR.html#cb892-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb892-2"><a href="DPLYRR.html#cb892-2" tabindex="-1"></a>  <span class="fu">slice_min</span>(height, <span class="at">n=</span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 14
##   name      height  mass hair_color skin_color eye_color birth_year sex   gender
##   &lt;chr&gt;      &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
## 1 Yoda          66    17 white      green      brown            896 male  mascu…
## 2 Ratts Ty…     79    15 none       grey, blue unknown           NA male  mascu…
## 3 Wicket S…     88    20 brown      brown      brown              8 male  mascu…
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<p>Example-2:</p>
<div class="sourceCode" id="cb894"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb894-1"><a href="DPLYRR.html#cb894-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2022</span>)</span>
<span id="cb894-2"><a href="DPLYRR.html#cb894-2" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb894-3"><a href="DPLYRR.html#cb894-3" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">prop =</span> <span class="fl">0.1</span>) <span class="co">#sample 10% rows</span></span></code></pre></div>
<pre><code>## # A tibble: 8 × 14
##   name      height  mass hair_color skin_color eye_color birth_year sex   gender
##   &lt;chr&gt;      &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
## 1 Ki-Adi-M…    198  82   white      pale       yellow            92 male  mascu…
## 2 Grievous     216 159   none       brown, wh… green, y…         NA male  mascu…
## 3 Saesee T…    188  NA   none       pale       orange            NA male  mascu…
## 4 Wat Tamb…    193  48   none       green, gr… unknown           NA male  mascu…
## 5 Jango Fe…    183  79   black      tan        brown             66 male  mascu…
## 6 Owen Lars    178 120   brown, gr… light      blue              52 male  mascu…
## 7 Luminara…    170  56.2 black      yellow     blue              58 fema… femin…
## 8 BB8           NA  NA   none       none       black             NA none  mascu…
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
</div>
<div id="row-verb-arrange" class="section level2" number="14.7">
<h2><span class="header-section-number">14.7</span> Row verb <code>arrange()</code></h2>
<p>This verb also act upon rows and it actually <em>rearranges</em> them on the basis of some condition. Refer figure <a href="DPLYRR.html#fig:arranger">14.6</a> for illustration.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:arranger"></span>
<img src="images/arrange_dplyr.png" alt="Illustration of dplyr::arrange()" width="99%" />
<p class="caption">
Figure 14.6: Illustration of dplyr::arrange()
</p>
</div>
<p>Example-</p>
<div class="sourceCode" id="cb896"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb896-1"><a href="DPLYRR.html#cb896-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb896-2"><a href="DPLYRR.html#cb896-2" tabindex="-1"></a>  <span class="fu">arrange</span>(height) <span class="sc">%&gt;%</span> </span>
<span id="cb896-3"><a href="DPLYRR.html#cb896-3" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 14
##   name      height  mass hair_color skin_color eye_color birth_year sex   gender
##   &lt;chr&gt;      &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
## 1 Yoda          66    17 white      green      brown            896 male  mascu…
## 2 Ratts Ty…     79    15 none       grey, blue unknown           NA male  mascu…
## 3 Wicket S…     88    20 brown      brown      brown              8 male  mascu…
## 4 Dud Bolt      94    45 none       blue, grey yellow            NA male  mascu…
## 5 R2-D2         96    32 &lt;NA&gt;       white, bl… red               33 none  mascu…
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
</div>
<div id="group-verb-group_by" class="section level2" number="14.8">
<h2><span class="header-section-number">14.8</span> Group verb <code>group_by()</code></h2>
<p>A data analyst will be hard to find who is not using <code>group_by</code>. It basically groups the rows on the basis of values of a given variable or block of variables. The returned result is still a data frame (and one too) but now the rows are grouped. Refer figure <a href="DPLYRR.html#fig:groupby">14.7</a> for illustration. So any of the above functions we learnt above will give a different result after group by.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:groupby"></span>
<img src="images/groupby_dplyr.png" alt="Illustration of Grouped Operations in dplyr" width="99%" />
<p class="caption">
Figure 14.7: Illustration of Grouped Operations in dplyr
</p>
</div>
<p>Note the output of this simple example</p>
<div class="sourceCode" id="cb898"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb898-1"><a href="DPLYRR.html#cb898-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb898-2"><a href="DPLYRR.html#cb898-2" tabindex="-1"></a>  <span class="fu">group_by</span>(sex)</span></code></pre></div>
<pre><code>## # A tibble: 87 × 14
## # Groups:   sex [5]
##    name     height  mass hair_color skin_color eye_color birth_year sex   gender
##    &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 Luke Sk…    172    77 blond      fair       blue            19   male  mascu…
##  2 C-3PO       167    75 &lt;NA&gt;       gold       yellow         112   none  mascu…
##  3 R2-D2        96    32 &lt;NA&gt;       white, bl… red             33   none  mascu…
##  4 Darth V…    202   136 none       white      yellow          41.9 male  mascu…
##  5 Leia Or…    150    49 brown      light      brown           19   fema… femin…
##  6 Owen La…    178   120 brown, gr… light      blue            52   male  mascu…
##  7 Beru Wh…    165    75 brown      light      blue            47   fema… femin…
##  8 R5-D4        97    32 &lt;NA&gt;       white, red red             NA   none  mascu…
##  9 Biggs D…    183    84 black      light      brown           24   male  mascu…
## 10 Obi-Wan…    182    77 auburn, w… fair       blue-gray       57   male  mascu…
## # ℹ 77 more rows
## # ℹ 5 more variables: homeworld &lt;chr&gt;, species &lt;chr&gt;, films &lt;list&gt;,
## #   vehicles &lt;list&gt;, starships &lt;list&gt;</code></pre>
<p><strong>Note</strong> that output now has 5 groups, though nothing different is seen in the displayed data.</p>
<p>This operation/verb is thus more useful if used in combination with other verbs.</p>
<p>Example-1: How many total characters are with same skin_color?</p>
<div class="sourceCode" id="cb900"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb900-1"><a href="DPLYRR.html#cb900-1" tabindex="-1"></a>starwars <span class="sc">%&gt;%</span> </span>
<span id="cb900-2"><a href="DPLYRR.html#cb900-2" tabindex="-1"></a>  <span class="fu">select</span>(name, skin_color) <span class="sc">%&gt;%</span> </span>
<span id="cb900-3"><a href="DPLYRR.html#cb900-3" tabindex="-1"></a>  <span class="fu">group_by</span>(skin_color) <span class="sc">%&gt;%</span> </span>
<span id="cb900-4"><a href="DPLYRR.html#cb900-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_with_s_c =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 87 × 3
## # Groups:   skin_color [31]
##    name               skin_color  total_with_s_c
##    &lt;chr&gt;              &lt;chr&gt;                &lt;int&gt;
##  1 Luke Skywalker     fair                    17
##  2 C-3PO              gold                     1
##  3 R2-D2              white, blue              2
##  4 Darth Vader        white                    2
##  5 Leia Organa        light                   11
##  6 Owen Lars          light                   11
##  7 Beru Whitesun Lars light                   11
##  8 R5-D4              white, red               1
##  9 Biggs Darklighter  light                   11
## 10 Obi-Wan Kenobi     fair                    17
## # ℹ 77 more rows</code></pre>
<p>Example- 2: Sample 2 rows of each <code>cyl</code> size from <code>mtcars</code>?</p>
<div class="sourceCode" id="cb902"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb902-1"><a href="DPLYRR.html#cb902-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb902-2"><a href="DPLYRR.html#cb902-2" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb902-3"><a href="DPLYRR.html#cb902-3" tabindex="-1"></a>  <span class="fu">group_by</span>(cyl) <span class="sc">%&gt;%</span> </span>
<span id="cb902-4"><a href="DPLYRR.html#cb902-4" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 11
## # Groups:   cyl [3]
##     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
## 2  21.4     4  121    109  4.11  2.78  18.6     1     1     4     2
## 3  21       6  160    110  3.9   2.88  17.0     0     1     4     4
## 4  19.7     6  145    175  3.62  2.77  15.5     0     1     5     6
## 5  10.4     8  472    205  2.93  5.25  18.0     0     0     3     4
## 6  13.3     8  350    245  3.73  3.84  15.4     0     0     3     4</code></pre>
<p>Also note that <code>grouped</code> varaible(s) will always be available in the output.</p>
<div class="sourceCode" id="cb904"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb904-1"><a href="DPLYRR.html#cb904-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb904-2"><a href="DPLYRR.html#cb904-2" tabindex="-1"></a>  <span class="fu">group_by</span>(cyl) <span class="sc">%&gt;%</span> </span>
<span id="cb904-3"><a href="DPLYRR.html#cb904-3" tabindex="-1"></a>  <span class="fu">select</span>(drat) <span class="sc">%&gt;%</span> <span class="co"># despite not selecting cyl</span></span>
<span id="cb904-4"><a href="DPLYRR.html#cb904-4" tabindex="-1"></a>  <span class="fu">head</span>() <span class="co"># it is available in output</span></span></code></pre></div>
<pre><code>## Adding missing grouping variables: `cyl`</code></pre>
<pre><code>## # A tibble: 6 × 2
## # Groups:   cyl [3]
##     cyl  drat
##   &lt;dbl&gt; &lt;dbl&gt;
## 1     6  3.9 
## 2     6  3.9 
## 3     4  3.85
## 4     6  3.08
## 5     8  3.15
## 6     6  2.76</code></pre>
</div>
<div id="group-verb-summarise" class="section level2" number="14.9">
<h2><span class="header-section-number">14.9</span> Group verb <code>summarise()</code></h2>
<p>This verb creates a summary row for each group if grouped data frame is in input, otherwise one single for complete operation.<br />
Example-1:</p>
<div class="sourceCode" id="cb907"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb907-1"><a href="DPLYRR.html#cb907-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb907-2"><a href="DPLYRR.html#cb907-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_wt =</span> <span class="fu">sum</span>(wt))</span></code></pre></div>
<pre><code>##   total_wt
## 1  102.952</code></pre>
<p>Example-2:</p>
<div class="sourceCode" id="cb909"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb909-1"><a href="DPLYRR.html#cb909-1" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb909-2"><a href="DPLYRR.html#cb909-2" tabindex="-1"></a>  <span class="fu">group_by</span>(cyl) <span class="sc">%&gt;%</span> </span>
<span id="cb909-3"><a href="DPLYRR.html#cb909-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_wt =</span> <span class="fu">sum</span>(wt))</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##     cyl total_wt
##   &lt;dbl&gt;    &lt;dbl&gt;
## 1     4     25.1
## 2     6     21.8
## 3     8     56.0</code></pre>
</div>
<div id="group-verb-ungroup" class="section level2" number="14.10">
<h2><span class="header-section-number">14.10</span> Group verb <code>ungroup()</code></h2>
<p>But now, it may have been noticed that grouping the data with <code>group_by</code> and thereafter performing some operation like <code>mutate</code> or <code>slice</code> returns the grouped data. But our requirement in next steps would be of ungrouped data. so there is specially designed function in dplyr which ungroups the grouped data.</p>
<div class="sourceCode" id="cb911"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb911-1"><a href="DPLYRR.html#cb911-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb911-2"><a href="DPLYRR.html#cb911-2" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb911-3"><a href="DPLYRR.html#cb911-3" tabindex="-1"></a>  <span class="fu">group_by</span>(cyl) <span class="sc">%&gt;%</span> </span>
<span id="cb911-4"><a href="DPLYRR.html#cb911-4" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb911-5"><a href="DPLYRR.html#cb911-5" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 11
##     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  22.8     4  141.    95  3.92  3.15  22.9     1     0     4     2
## 2  21.4     4  121    109  4.11  2.78  18.6     1     1     4     2
## 3  21       6  160    110  3.9   2.88  17.0     0     1     4     4
## 4  19.7     6  145    175  3.62  2.77  15.5     0     1     5     6
## 5  10.4     8  472    205  2.93  5.25  18.0     0     0     3     4
## 6  13.3     8  350    245  3.73  3.84  15.4     0     0     3     4</code></pre>
</div>
<div id="new-argument-.by-in-mutate-summarise-filter-etc." class="section level2" number="14.11">
<h2><span class="header-section-number">14.11</span> New argument <code>.by</code> in <code>mutate</code>, <code>summarise</code>, <code>filter</code>, etc.</h2>
<p>Since grouping the data in one step, then performing required step and then again ungrouping it is somewhat cumbersome, coming dplyr 1.1.0 version, the functions <code>mutate()</code>, <code>summarise</code>, <code>slice</code> etc. have gained an additional argument <code>.by</code> wherein the variable names for performing grouped operations may be provided directly, thus eliminating the need of both grouping and ungrouping it. So the following two syntax would produce exactly same results.</p>
<div class="sourceCode" id="cb913"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb913-1"><a href="DPLYRR.html#cb913-1" tabindex="-1"></a><span class="co"># Syntax - 1 (old style)</span></span>
<span id="cb913-2"><a href="DPLYRR.html#cb913-2" tabindex="-1"></a></span>
<span id="cb913-3"><a href="DPLYRR.html#cb913-3" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb913-4"><a href="DPLYRR.html#cb913-4" tabindex="-1"></a>  <span class="fu">group_by</span>(cyl) <span class="sc">%&gt;%</span> </span>
<span id="cb913-5"><a href="DPLYRR.html#cb913-5" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb913-6"><a href="DPLYRR.html#cb913-6" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<pre><code>## # A tibble: 3 × 11
##     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  24.4     4  147.    62  3.69  3.19  20       1     0     4     2
## 2  21       6  160    110  3.9   2.88  17.0     0     1     4     4
## 3  14.3     8  360    245  3.21  3.57  15.8     0     0     3     4</code></pre>
<div class="sourceCode" id="cb915"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb915-1"><a href="DPLYRR.html#cb915-1" tabindex="-1"></a><span class="co"># Syntax 2 (Dplyr 1.1.0 +)</span></span>
<span id="cb915-2"><a href="DPLYRR.html#cb915-2" tabindex="-1"></a></span>
<span id="cb915-3"><a href="DPLYRR.html#cb915-3" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb915-4"><a href="DPLYRR.html#cb915-4" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">2</span>, <span class="at">.by =</span> cyl)</span></code></pre></div>
<pre><code>##                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4 Wag 21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
## Merc 240D     24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
## Duster 360    14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4</code></pre>
</div>
<div id="group-verb-reframe" class="section level2" number="14.12">
<h2><span class="header-section-number">14.12</span> Group verb <code>reframe()</code></h2>
<p><strong>The content is under development.</strong></p>
</div>
<div id="other-useful-functions-in-dplyr" class="section level2" number="14.13">
<h2><span class="header-section-number">14.13</span> Other Useful functions in <code>dplyr</code></h2>
<div id="if_else" class="section level3 unnumbered">
<h3><code>if_else()</code></h3>
<p>This function operates nearly as similar to base R’s <code>ifelse()</code> with two exceptions-</p>
<ul>
<li>There is an extra argument to provide values when missing values are encountered. (See example-1)</li>
<li><code>NA</code> will have to be provided specifically. (See Example-2)</li>
</ul>
<p>See these examples. Example-1:</p>
<div class="sourceCode" id="cb917"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb917-1"><a href="DPLYRR.html#cb917-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span><span class="sc">:</span><span class="dv">2</span>, <span class="cn">NA</span>)</span>
<span id="cb917-2"><a href="DPLYRR.html#cb917-2" tabindex="-1"></a><span class="fu">if_else</span>(x<span class="sc">&gt;=</span><span class="dv">0</span>, <span class="st">&quot;positive&quot;</span>, <span class="st">&quot;negative&quot;</span>, <span class="st">&quot;missing&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;negative&quot; &quot;negative&quot; &quot;positive&quot; &quot;positive&quot; &quot;positive&quot; &quot;missing&quot;</code></pre>
<p>Example-2:</p>
<div class="sourceCode" id="cb919"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb919-1"><a href="DPLYRR.html#cb919-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span><span class="sc">:</span><span class="dv">2</span>, <span class="cn">NA</span>)</span>
<span id="cb919-2"><a href="DPLYRR.html#cb919-2" tabindex="-1"></a><span class="fu">if_else</span>(x<span class="sc">&gt;=</span><span class="dv">0</span>, <span class="st">&quot;positive&quot;</span>, <span class="st">&quot;negative&quot;</span>, <span class="cn">NA_character_</span>)</span></code></pre></div>
<pre><code>## [1] &quot;negative&quot; &quot;negative&quot; &quot;positive&quot; &quot;positive&quot; &quot;positive&quot; NA</code></pre>
<p>Due to the additional restrictions, this function is sometimes faster than its base R alternative and may also be useful in prevention of bugs in code as the output will be known beforehand.</p>
</div>
<div id="case_when" class="section level3 unnumbered">
<h3><code>case_when()</code></h3>
<p>Though both <code>ifelse</code> and <code>if_else</code> variants provide for nesting multiple conditions, yet <code>case_when</code> provides a simpler alternative in these conditions as here multiple conditions can be provided simultaneously. Syntax follows this style-</p>
<pre><code>case_when(
  condition1 ~ value_if_true,
  condition2 ~ value_if_true,
  ...,
  TRUE ~ value_if_all_above_are_false
)</code></pre>
<p>See this example.</p>
<div class="sourceCode" id="cb922"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb922-1"><a href="DPLYRR.html#cb922-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb922-2"><a href="DPLYRR.html#cb922-2" tabindex="-1"></a><span class="co"># Generate Incomes from random (uniform) distribution</span></span>
<span id="cb922-3"><a href="DPLYRR.html#cb922-3" tabindex="-1"></a>income <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">7</span>, <span class="dv">1</span>, <span class="dv">9</span>)<span class="sc">*</span><span class="dv">100000</span></span>
<span id="cb922-4"><a href="DPLYRR.html#cb922-4" tabindex="-1"></a>income</span></code></pre></div>
<pre><code>## [1] 330062.0 730644.1 427181.5 806413.9 852373.8 136445.2 522484.4</code></pre>
<div class="sourceCode" id="cb924"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb924-1"><a href="DPLYRR.html#cb924-1" tabindex="-1"></a><span class="co"># tax brackets say 0% upto 2 lakh, then 10% upto 5 Lakh</span></span>
<span id="cb924-2"><a href="DPLYRR.html#cb924-2" tabindex="-1"></a><span class="co"># then 20% upto 7.5 lakh otherwise 30%</span></span>
<span id="cb924-3"><a href="DPLYRR.html#cb924-3" tabindex="-1"></a>tax_slab <span class="ot">&lt;-</span> <span class="fu">case_when</span>(</span>
<span id="cb924-4"><a href="DPLYRR.html#cb924-4" tabindex="-1"></a>  income <span class="sc">&lt;=</span> <span class="dv">200000</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb924-5"><a href="DPLYRR.html#cb924-5" tabindex="-1"></a>  income <span class="sc">&lt;=</span> <span class="dv">500000</span> <span class="sc">~</span> <span class="dv">10</span>,</span>
<span id="cb924-6"><a href="DPLYRR.html#cb924-6" tabindex="-1"></a>  income <span class="sc">&lt;=</span> <span class="dv">750000</span> <span class="sc">~</span> <span class="dv">20</span>,</span>
<span id="cb924-7"><a href="DPLYRR.html#cb924-7" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">30</span></span>
<span id="cb924-8"><a href="DPLYRR.html#cb924-8" tabindex="-1"></a>)</span>
<span id="cb924-9"><a href="DPLYRR.html#cb924-9" tabindex="-1"></a></span>
<span id="cb924-10"><a href="DPLYRR.html#cb924-10" tabindex="-1"></a><span class="co"># check tax_slab</span></span>
<span id="cb924-11"><a href="DPLYRR.html#cb924-11" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb924-12"><a href="DPLYRR.html#cb924-12" tabindex="-1"></a>  <span class="at">income=</span>income,</span>
<span id="cb924-13"><a href="DPLYRR.html#cb924-13" tabindex="-1"></a>  <span class="at">tax_slab =</span> tax_slab</span>
<span id="cb924-14"><a href="DPLYRR.html#cb924-14" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##     income tax_slab
## 1 330062.0       10
## 2 730644.1       20
## 3 427181.5       10
## 4 806413.9       30
## 5 852373.8       30
## 6 136445.2        0
## 7 522484.4       20</code></pre>
</div>
<div id="case_match" class="section level3 unnumbered">
<h3><code>case_match()</code></h3>
<p>This function is somewhat similar to <code>case_when</code>. While <code>case_when()</code> uses logical expressions on the left-hand side of the formula, <code>case_match()</code> uses values to match with. Syntax is like</p>
<pre><code>case_match(
  .x,  # A vector whose values are to be matched
  ..., # Basically for a condition like .x %in% Y, only Y has to be specified
  .default = NULL, # Default values to be specified for if no match is found
)</code></pre>
<p>So, above example could be rewritten as</p>
<div class="sourceCode" id="cb927"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb927-1"><a href="DPLYRR.html#cb927-1" tabindex="-1"></a>tax_slab <span class="ot">&lt;-</span> <span class="fu">case_match</span>(</span>
<span id="cb927-2"><a href="DPLYRR.html#cb927-2" tabindex="-1"></a>  <span class="fu">floor</span>(income), <span class="co"># Vector to be checked</span></span>
<span id="cb927-3"><a href="DPLYRR.html#cb927-3" tabindex="-1"></a>  <span class="dv">0</span><span class="sc">:</span><span class="dv">200000</span> <span class="sc">~</span> <span class="dv">0</span>, <span class="co"># slab 1</span></span>
<span id="cb927-4"><a href="DPLYRR.html#cb927-4" tabindex="-1"></a>  <span class="dv">200001</span><span class="sc">:</span><span class="dv">500000</span> <span class="sc">~</span> <span class="dv">10</span>, <span class="co"># slab 2</span></span>
<span id="cb927-5"><a href="DPLYRR.html#cb927-5" tabindex="-1"></a>  <span class="dv">500001</span><span class="sc">:</span><span class="dv">750000</span> <span class="sc">~</span> <span class="dv">20</span>, <span class="co"># slab 3</span></span>
<span id="cb927-6"><a href="DPLYRR.html#cb927-6" tabindex="-1"></a>  <span class="at">.default =</span> <span class="dv">30</span> <span class="co"># Slab 4</span></span>
<span id="cb927-7"><a href="DPLYRR.html#cb927-7" tabindex="-1"></a>)</span>
<span id="cb927-8"><a href="DPLYRR.html#cb927-8" tabindex="-1"></a></span>
<span id="cb927-9"><a href="DPLYRR.html#cb927-9" tabindex="-1"></a><span class="co"># check tax_slab</span></span>
<span id="cb927-10"><a href="DPLYRR.html#cb927-10" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb927-11"><a href="DPLYRR.html#cb927-11" tabindex="-1"></a>  <span class="at">income=</span>income,</span>
<span id="cb927-12"><a href="DPLYRR.html#cb927-12" tabindex="-1"></a>  <span class="at">tax_slab =</span> tax_slab</span>
<span id="cb927-13"><a href="DPLYRR.html#cb927-13" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##     income tax_slab
## 1 330062.0       10
## 2 730644.1       20
## 3 427181.5       10
## 4 806413.9       30
## 5 852373.8       30
## 6 136445.2        0
## 7 522484.4       20</code></pre>
</div>
</div>
<div id="across" class="section level2" number="14.14">
<h2><span class="header-section-number">14.14</span> Functional programming in dplyr through <code>across()</code></h2>
<p><strong>The content is under development.</strong></p>
</div>
<div id="window-functionsoperations" class="section level2" number="14.15">
<h2><span class="header-section-number">14.15</span> Window functions/operations</h2>
<p>We learnt that by using <code>group_by</code> function we can create windows in data and we can make our calculations in each separate window specifically.</p>
<p>Dplyr provides us with some useful window functions which will operate on these windows.</p>
<ol style="list-style-type: decimal">
<li><code>row_number()</code> can be used to generate row number</li>
<li><code>dense_rank</code> / <code>min_rank</code> / <code>percent_rank()</code> / <code>ntile()</code> / <code>cume_dist()</code> are other windowed functions in dplyr. Check <code>?dplyr::ranking</code> for complete reference.</li>
<li><code>lead()</code> and <code>lag()</code> will give leading/lagging value in that window.</li>
<li><code>consecutive_id()</code> generates a unique identifier that increments every time a variable (or combination of variables) changes.</li>
</ol>
<p>These functions can be very helpful while analyzing time series data.</p>
<p>Example-1: Generating row numbers and ranks</p>
<div class="sourceCode" id="cb929"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb929-1"><a href="DPLYRR.html#cb929-1" tabindex="-1"></a><span class="co"># example data</span></span>
<span id="cb929-2"><a href="DPLYRR.html#cb929-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb929-3"><a href="DPLYRR.html#cb929-3" tabindex="-1"></a>  <span class="at">val =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="cn">NA</span>)</span>
<span id="cb929-4"><a href="DPLYRR.html#cb929-4" tabindex="-1"></a>)</span>
<span id="cb929-5"><a href="DPLYRR.html#cb929-5" tabindex="-1"></a></span>
<span id="cb929-6"><a href="DPLYRR.html#cb929-6" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb929-7"><a href="DPLYRR.html#cb929-7" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb929-8"><a href="DPLYRR.html#cb929-8" tabindex="-1"></a>    <span class="at">row =</span> <span class="fu">row_number</span>(),</span>
<span id="cb929-9"><a href="DPLYRR.html#cb929-9" tabindex="-1"></a>    <span class="at">min_rank =</span> <span class="fu">min_rank</span>(val),</span>
<span id="cb929-10"><a href="DPLYRR.html#cb929-10" tabindex="-1"></a>    <span class="at">dense_rank =</span> <span class="fu">dense_rank</span>(val),</span>
<span id="cb929-11"><a href="DPLYRR.html#cb929-11" tabindex="-1"></a>    <span class="at">perc_rank =</span> <span class="fu">percent_rank</span>(val),</span>
<span id="cb929-12"><a href="DPLYRR.html#cb929-12" tabindex="-1"></a>    <span class="at">cume_dist =</span> <span class="fu">cume_dist</span>(val)</span>
<span id="cb929-13"><a href="DPLYRR.html#cb929-13" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>##   val row min_rank dense_rank perc_rank cume_dist
## 1  10   1        4          3 1.0000000      1.00
## 2   2   2        1          1 0.0000000      0.50
## 3   3   3        3          2 0.6666667      0.75
## 4   2   4        1          1 0.0000000      0.50
## 5  NA   5       NA         NA        NA        NA</code></pre>
<p>Example-2: Using previous and next values</p>
<div class="sourceCode" id="cb931"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb931-1"><a href="DPLYRR.html#cb931-1" tabindex="-1"></a>Orange <span class="sc">%&gt;%</span> </span>
<span id="cb931-2"><a href="DPLYRR.html#cb931-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Tree) <span class="sc">%&gt;%</span> </span>
<span id="cb931-3"><a href="DPLYRR.html#cb931-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prev_circ =</span> <span class="fu">lag</span>(circumference),</span>
<span id="cb931-4"><a href="DPLYRR.html#cb931-4" tabindex="-1"></a>         <span class="at">next_circ =</span> <span class="fu">lead</span>(circumference))</span></code></pre></div>
<pre><code>## # A tibble: 35 × 5
## # Groups:   Tree [5]
##    Tree    age circumference prev_circ next_circ
##    &lt;ord&gt; &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1 1       118            30        NA        58
##  2 1       484            58        30        87
##  3 1       664            87        58       115
##  4 1      1004           115        87       120
##  5 1      1231           120       115       142
##  6 1      1372           142       120       145
##  7 1      1582           145       142        NA
##  8 2       118            33        NA        69
##  9 2       484            69        33       111
## 10 2       664           111        69       156
## # ℹ 25 more rows</code></pre>
<p>Example-3: generating run length encoding/consecutive ID</p>
<div class="sourceCode" id="cb933"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb933-1"><a href="DPLYRR.html#cb933-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb933-2"><a href="DPLYRR.html#cb933-2" tabindex="-1"></a>  <span class="at">grp =</span> <span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;A&quot;</span>, <span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>),</span>
<span id="cb933-3"><a href="DPLYRR.html#cb933-3" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span> , <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>)</span>
<span id="cb933-4"><a href="DPLYRR.html#cb933-4" tabindex="-1"></a>)</span>
<span id="cb933-5"><a href="DPLYRR.html#cb933-5" tabindex="-1"></a></span>
<span id="cb933-6"><a href="DPLYRR.html#cb933-6" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb933-7"><a href="DPLYRR.html#cb933-7" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">RLE =</span> <span class="fu">consecutive_id</span>(grp))</span></code></pre></div>
<pre><code>##   grp value RLE
## 1   A     1   1
## 2   B     2   2
## 3   B     3   2
## 4   A     4   3
## 5   A     5   3
## 6   B     6   4</code></pre>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="22">
<li id="fn22"><p>Hadley Wickham et al., <em>Dplyr: A Grammar of Data Manipulation</em>, 2023, <a href="https://dplyr.tidyverse.org">https://dplyr.tidyverse.org</a>.<a href="DPLYRR.html#fnref22" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
  </main>

  <div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page">
      <h2>On this page</h2>
      <div id="book-on-this-page"></div>

      <div class="book-extra">
        <ul class="list-unstyled">
          <li><a id="book-source" href="#">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="#">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
      </div>
    </nav>
  </div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5">
  <div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>R for Audit Analytics</strong>" was written by Anil Goyal. It was last built on 2024-11-29.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
<script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>

</html>
