<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Chapter 24 Date and Time calculations | R for Audit Analytics</title>

    <meta name="author" content="Anil Goyal" />
  
   <meta name="description" content="This book is intended for auditors performing exploratory data analytics using R programming language, mainly Base R and Tidyverse." />
   <meta name="generator" content="placeholder" />
  <meta property="og:title" content="Chapter 24 Date and Time calculations | R for Audit Analytics" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://anilyayavar.github.io/new-book/" />
  <meta property="og:image" content="https://anilyayavar.github.io/new-book/images/cover.jpg" />
  <meta property="og:description" content="This book is intended for auditors performing exploratory data analytics using R programming language, mainly Base R and Tidyverse." />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 24 Date and Time calculations | R for Audit Analytics" />
  
  <meta name="twitter:description" content="This book is intended for auditors performing exploratory data analytics using R programming language, mainly Base R and Tidyverse." />
  <meta name="twitter:image" content="https://anilyayavar.github.io/new-book/images/cover.jpg" />
  <!-- JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script>
    <script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet" />
    <script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script>
    <script src="libs/bs3compat-0.8.0/transition.js"></script>
    <script src="libs/bs3compat-0.8.0/tabs.js"></script>
    <script src="libs/bs3compat-0.8.0/bs3compat.js"></script>
    <link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet" />
    <script src="libs/bs4_book-1.0.0/bs4_book.js"></script>
    <script src="libs/kePrint-0.0.1/kePrint.js"></script>
    <link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script>

  <!-- CSS -->
  <style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
    <style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 0em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
      <link rel="stylesheet" href="style.css" />
  
</head>

<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book">
    <a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">R for Audit Analytics</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>

      <nav aria-label="Table of contents">
        <h2>Table of contents</h2>
        <div id="book-toc"></div>

        <div class="book-extra">
          <p><a id="book-repo" href="#">View book source <i class="fab fa-github"></i></a></li></p>
        </div>
      </nav>
    </div>
  </header>

  <main class="col-sm-12 col-md-9 col-lg-7" id="content">
<div id="lubridate" class="section level1" number="24">
<h1><span class="header-section-number">Chapter 24</span> Date and Time calculations</h1>
<div id="base-r-classes-to-deal-with-date-and-time-variables" class="section level2" number="24.1">
<h2><span class="header-section-number">24.1</span> Base R classes to deal with date and time variables</h2>
<p>There may hardly be any data analytics activity, wherein we do not have to deal with temporal information and thus need to manipulate dates and date-time objects/variables. To deal with these variable types, R has four core data types/classes,</p>
<ul>
<li><code>Date</code> To deal with date objects (note: <code>D</code> in UPPER case)</li>
<li><code>POSIXct</code> To deal with times</li>
<li><code>POSIXlt</code> To deal with times (for difference between these two refer section <a href="lubridate.html#timm">24.1.2</a>.)</li>
<li><code>difftime</code> To deal with time-spans</li>
</ul>
<div id="dates" class="section level3" number="24.1.1">
<h3><span class="header-section-number">24.1.1</span> Dates</h3>
<p><code>Date</code> objects can be created from <code>string/character</code> type objects (we will just see that date objects can be created from numeric objects too), using base R’s function <code>as.Date()</code> which accepts a character vector and a format to parse the date from the given string of characters. E.g.</p>
<div class="sourceCode" id="cb1215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1215-1"><a href="lubridate.html#cb1215-1" tabindex="-1"></a><span class="fu">as.Date</span>(<span class="st">&quot;2000-12-12&quot;</span>) <span class="co"># default format</span></span></code></pre></div>
<pre><code>## [1] &quot;2000-12-12&quot;</code></pre>
<div class="sourceCode" id="cb1217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1217-1"><a href="lubridate.html#cb1217-1" tabindex="-1"></a><span class="fu">as.Date</span>(<span class="st">&quot;12-12-2000&quot;</span>, <span class="at">format =</span> <span class="st">&quot;%d-%m-%Y&quot;</span>) <span class="co"># custom format</span></span></code></pre></div>
<pre><code>## [1] &quot;2000-12-12&quot;</code></pre>
<p>In the above example, we can see that a custom format has been given to parse the character string into the date type object. We can check the <code>class</code> of the object created.</p>
<div class="sourceCode" id="cb1219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1219-1"><a href="lubridate.html#cb1219-1" tabindex="-1"></a>a_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">&quot;20-12-2022&quot;</span>, <span class="at">format =</span> <span class="st">&quot;%d-%m-%Y&quot;</span>)</span>
<span id="cb1219-2"><a href="lubridate.html#cb1219-2" tabindex="-1"></a><span class="fu">class</span>(a_date)</span></code></pre></div>
<pre><code>## [1] &quot;Date&quot;</code></pre>
<p>The format used in the above function accepts special codes, which can be seen by running <code>?strptime</code> in your R console. A ready reference for most used codes is however, given in table <a href="lubridate.html#tab:lubri001">24.1</a> in section <a href="lubridate.html#strpp">24.1.9</a>. The date objects in R, are actually based on numeric classes which actually store the number of days since an epoch. Check the following code-</p>
<div class="sourceCode" id="cb1221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1221-1"><a href="lubridate.html#cb1221-1" tabindex="-1"></a><span class="fu">class</span>(<span class="fu">Sys.Date</span>())</span></code></pre></div>
<pre><code>## [1] &quot;Date&quot;</code></pre>
<div class="sourceCode" id="cb1223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1223-1"><a href="lubridate.html#cb1223-1" tabindex="-1"></a><span class="fu">typeof</span>(<span class="fu">Sys.Date</span>())</span></code></pre></div>
<pre><code>## [1] &quot;double&quot;</code></pre>
<div class="sourceCode" id="cb1225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1225-1"><a href="lubridate.html#cb1225-1" tabindex="-1"></a><span class="fu">unclass</span>(<span class="fu">Sys.Date</span>())</span></code></pre></div>
<pre><code>## [1] 20056</code></pre>
<p>So, in R versions 4.3.0 and later, it also accepts a number to convert into a date using the number of days elapsed since epoch. So,</p>
<div class="sourceCode" id="cb1227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1227-1"><a href="lubridate.html#cb1227-1" tabindex="-1"></a><span class="fu">as.Date</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1970-01-02&quot;</code></pre>
<p>Here date since one day of default origin date 1970-01-01 has been returned. However, default <code>origin</code> can be changed using the argument <code>origin</code>. Example,</p>
<div class="sourceCode" id="cb1229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1229-1"><a href="lubridate.html#cb1229-1" tabindex="-1"></a><span class="co"># One day since launch of R version 1.0</span></span>
<span id="cb1229-2"><a href="lubridate.html#cb1229-2" tabindex="-1"></a><span class="fu">as.Date</span>(<span class="dv">1</span>, <span class="at">origin =</span> <span class="st">&quot;2000-02-29&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2000-03-01&quot;</code></pre>
</div>
<div id="timm" class="section level3" number="24.1.2">
<h3><span class="header-section-number">24.1.2</span> Times</h3>
<p>Now, to create date-time objects we can use either of <code>POSIXct</code> and <code>POSIXlt</code> classes, i.e. by using <code>as.POSIXct()</code> and/or <code>as.POSIXlt()</code> functions, as shown below.</p>
<div class="sourceCode" id="cb1231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1231-1"><a href="lubridate.html#cb1231-1" tabindex="-1"></a><span class="fu">as.POSIXct</span>(<span class="st">&quot;1990/2/17 12:20:05&quot;</span>) <span class="co"># default format</span></span></code></pre></div>
<pre><code>## [1] &quot;1990-02-17 12:20:05 IST&quot;</code></pre>
<div class="sourceCode" id="cb1233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1233-1"><a href="lubridate.html#cb1233-1" tabindex="-1"></a><span class="fu">as.POSIXct</span>(<span class="st">&quot;17-2-1990 15:30:00&quot;</span>, <span class="at">format =</span> <span class="st">&quot;%d-%m-%Y %H:%M:%S&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1990-02-17 15:30:00 IST&quot;</code></pre>
<div class="sourceCode" id="cb1235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1235-1"><a href="lubridate.html#cb1235-1" tabindex="-1"></a><span class="fu">as.POSIXlt</span>(<span class="st">&quot;17-2-1990 15:30:00&quot;</span>, <span class="at">format =</span> <span class="st">&quot;%d-%m-%Y %H:%M:%S&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1990-02-17 15:30:00 IST&quot;</code></pre>
<p>As regards, the difference between these two classes, <code>POSIXct</code> stores <em>seconds</em> since UNIX epoch (and other information), and <code>POSIXlt</code>, which stores a list of <em>day</em>, <em>month</em>, <em>year</em>, <em>hour</em>, <em>minute</em>, <em>second</em>, etc., which can be understood from the following codes.</p>
<blockquote>
<p><code>ct</code> in <code>POSIXct</code> stands for calendar time whereas, <code>lt</code> in <code>POSIXlt</code> stands for local time, explaining the conceptual difference.</p>
</blockquote>
<div class="sourceCode" id="cb1237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1237-1"><a href="lubridate.html#cb1237-1" tabindex="-1"></a>time_ct <span class="ot">&lt;-</span> <span class="fu">as.POSIXct</span>(<span class="st">&quot;17-2-1990 15:30:00&quot;</span>, <span class="at">format =</span> <span class="st">&quot;%d-%m-%Y %H:%M:%S&quot;</span>)</span>
<span id="cb1237-2"><a href="lubridate.html#cb1237-2" tabindex="-1"></a><span class="fu">class</span>(time_ct)</span></code></pre></div>
<pre><code>## [1] &quot;POSIXct&quot; &quot;POSIXt&quot;</code></pre>
<div class="sourceCode" id="cb1239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1239-1"><a href="lubridate.html#cb1239-1" tabindex="-1"></a><span class="fu">unclass</span>(time_ct)</span></code></pre></div>
<pre><code>## [1] 635248800
## attr(,&quot;tzone&quot;)
## [1] &quot;&quot;</code></pre>
<div class="sourceCode" id="cb1241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1241-1"><a href="lubridate.html#cb1241-1" tabindex="-1"></a><span class="do">## POSIXlt</span></span>
<span id="cb1241-2"><a href="lubridate.html#cb1241-2" tabindex="-1"></a><span class="co"># Convert above object into POSIXlt type</span></span>
<span id="cb1241-3"><a href="lubridate.html#cb1241-3" tabindex="-1"></a>time_lt <span class="ot">&lt;-</span> <span class="fu">as.POSIXlt</span>(time_ct)</span>
<span id="cb1241-4"><a href="lubridate.html#cb1241-4" tabindex="-1"></a><span class="co"># Let us print</span></span>
<span id="cb1241-5"><a href="lubridate.html#cb1241-5" tabindex="-1"></a>time_lt</span></code></pre></div>
<pre><code>## [1] &quot;1990-02-17 15:30:00 IST&quot;</code></pre>
<div class="sourceCode" id="cb1243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1243-1"><a href="lubridate.html#cb1243-1" tabindex="-1"></a><span class="fu">class</span>(time_lt)</span></code></pre></div>
<pre><code>## [1] &quot;POSIXlt&quot; &quot;POSIXt&quot;</code></pre>
<div class="sourceCode" id="cb1245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1245-1"><a href="lubridate.html#cb1245-1" tabindex="-1"></a><span class="fu">unclass</span>(time_lt)</span></code></pre></div>
<pre><code>## $sec
## [1] 0
## 
## $min
## [1] 30
## 
## $hour
## [1] 15
## 
## $mday
## [1] 17
## 
## $mon
## [1] 1
## 
## $year
## [1] 90
## 
## $wday
## [1] 6
## 
## $yday
## [1] 47
## 
## $isdst
## [1] 0
## 
## $zone
## [1] &quot;IST&quot;
## 
## $gmtoff
## [1] 19800
## 
## attr(,&quot;tzone&quot;)
## [1] &quot;&quot;      &quot;IST&quot;   &quot;+0630&quot;
## attr(,&quot;balanced&quot;)
## [1] TRUE</code></pre>
<p>Similar to <code>as.Date()</code>, <code>as.POSIXct()</code> also accepts a number and converts it into a date-time object using that much number of seconds since epoch.</p>
<div class="sourceCode" id="cb1247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1247-1"><a href="lubridate.html#cb1247-1" tabindex="-1"></a><span class="fu">as.POSIXct</span>(<span class="dv">60</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1970-01-01 05:31:00 IST&quot;</code></pre>
</div>
<div id="times-without-dates" class="section level3" number="24.1.3">
<h3><span class="header-section-number">24.1.3</span> Times (without dates)</h3>
<p>In base R, we do not have specific class to deal with time objects. However, there is a package <code>hms</code> part of <code>tidyverse</code> which can be used to create time objects to perform required calculations.</p>
<div class="sourceCode" id="cb1249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1249-1"><a href="lubridate.html#cb1249-1" tabindex="-1"></a>hms<span class="sc">::</span><span class="fu">as_hms</span>(<span class="dv">10</span>)</span></code></pre></div>
<pre><code>## 00:00:10</code></pre>
</div>
<div id="diffftime" class="section level3" number="24.1.4">
<h3><span class="header-section-number">24.1.4</span> Timespan</h3>
<p>In base R, besides above date/date-time object classes, there is a special class which creates time difference between two given temporal objects in specified units. The class is <code>difftime</code>.</p>
<div class="sourceCode" id="cb1251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1251-1"><a href="lubridate.html#cb1251-1" tabindex="-1"></a>(freedom_age <span class="ot">&lt;-</span> <span class="fu">Sys.Date</span>() <span class="sc">-</span> <span class="fu">as.Date</span>(<span class="st">&quot;1947-08-15&quot;</span>))</span></code></pre></div>
<pre><code>## Time difference of 28231 days</code></pre>
<div class="sourceCode" id="cb1253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1253-1"><a href="lubridate.html#cb1253-1" tabindex="-1"></a><span class="fu">class</span>(freedom_age)</span></code></pre></div>
<pre><code>## [1] &quot;difftime&quot;</code></pre>
<div class="sourceCode" id="cb1255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1255-1"><a href="lubridate.html#cb1255-1" tabindex="-1"></a><span class="fu">unclass</span>(freedom_age)</span></code></pre></div>
<pre><code>## [1] 28231
## attr(,&quot;units&quot;)
## [1] &quot;days&quot;</code></pre>
<p>Function <code>difftime</code> can create difftime objects, as per specific requirement due to presence of an argument <code>units</code> which can take values from one of <code>“auto”</code>, <code>“secs”</code>, <code>“mins”</code>, <code>“hours”</code>, <code>“days”</code>, <code>“weeks”</code>.</p>
<div class="sourceCode" id="cb1257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1257-1"><a href="lubridate.html#cb1257-1" tabindex="-1"></a><span class="fu">difftime</span>(<span class="fu">as.Date</span>(<span class="st">&quot;2020-02-29&quot;</span>), <span class="fu">as.Date</span>(<span class="st">&quot;2019-02-28&quot;</span>), <span class="at">units =</span> <span class="st">&quot;weeks&quot;</span>)</span></code></pre></div>
<pre><code>## Time difference of 52.28571 weeks</code></pre>
<p>We can also create a difftime object by coercion.</p>
<div class="sourceCode" id="cb1259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1259-1"><a href="lubridate.html#cb1259-1" tabindex="-1"></a>a_difftime <span class="ot">&lt;-</span> <span class="fu">as.difftime</span>(<span class="dv">15</span>, <span class="at">units =</span> <span class="st">&quot;days&quot;</span>)</span>
<span id="cb1259-2"><a href="lubridate.html#cb1259-2" tabindex="-1"></a>a_difftime</span></code></pre></div>
<pre><code>## Time difference of 15 days</code></pre>
<div class="sourceCode" id="cb1261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1261-1"><a href="lubridate.html#cb1261-1" tabindex="-1"></a><span class="fu">class</span>(a_difftime)</span></code></pre></div>
<pre><code>## [1] &quot;difftime&quot;</code></pre>
</div>
<div id="time-zones" class="section level3" number="24.1.5">
<h3><span class="header-section-number">24.1.5</span> Time zones</h3>
<p>Run the function <code>Sys.timezone()</code> in your console to check the current timezone. Function <code>OlsonNames()</code> will however, display the known location for time-zones.</p>
<div class="sourceCode" id="cb1263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1263-1"><a href="lubridate.html#cb1263-1" tabindex="-1"></a><span class="fu">Sys.timezone</span>()</span></code></pre></div>
<pre><code>## [1] &quot;Asia/Calcutta&quot;</code></pre>
<div class="sourceCode" id="cb1265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1265-1"><a href="lubridate.html#cb1265-1" tabindex="-1"></a><span class="fu">OlsonNames</span>()[<span class="fu">c</span>(<span class="dv">253</span>, <span class="dv">284</span>)]</span></code></pre></div>
<pre><code>## [1] &quot;Asia/Calcutta&quot; &quot;Asia/Kolkata&quot;</code></pre>
<p>So, we may use <code>tz</code> argument of <code>as.POSIXlt()</code> and <code>as.POSIXct()</code> functions to coerce the numeric or other class variables to dates and/or times.</p>
<div class="sourceCode" id="cb1267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1267-1"><a href="lubridate.html#cb1267-1" tabindex="-1"></a><span class="fu">as.POSIXct</span>(<span class="dv">1</span>, <span class="at">tz =</span> <span class="st">&quot;GMT&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1970-01-01 00:00:01 GMT&quot;</code></pre>
</div>
<div id="coercion" class="section level3" number="24.1.6">
<h3><span class="header-section-number">24.1.6</span> Coercion</h3>
<p>In earlier sections we have already seen coercing functions useful to coerce the objects from one class to another.</p>
<ul>
<li><code>as.Date()</code></li>
<li><code>as.POSIXct()</code></li>
<li><code>as.POSIXlt()</code></li>
<li><code>as.difftime()</code></li>
</ul>
</div>
<div id="extracting-parts-from-datestimes" class="section level3" number="24.1.7">
<h3><span class="header-section-number">24.1.7</span> Extracting parts from dates/times</h3>
<p>Base R provides us some useful function to extract relevant part of objects of dates/times classes.</p>
<ul>
<li><code>weekdays(x, abbreviate = FALSE)</code> to extract the weekday name. (Output is in character vector)</li>
<li><code>months(x, abbreviate = FALSE)</code> to extract the month name. (Output is in character vector)</li>
<li><code>quarters(x)</code> to extract the quarter. Output is in character vector.</li>
<li><code>julian(x)</code> to extract the days elapsed since origin. Output is in numeric vector.</li>
</ul>
<p>Examples-</p>
<div class="sourceCode" id="cb1269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1269-1"><a href="lubridate.html#cb1269-1" tabindex="-1"></a>dates_vec <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="dv">15001</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>)</span>
<span id="cb1269-2"><a href="lubridate.html#cb1269-2" tabindex="-1"></a><span class="fu">weekdays</span>(dates_vec)</span></code></pre></div>
<pre><code>## [1] &quot;Friday&quot;    &quot;Saturday&quot;  &quot;Sunday&quot;    &quot;Monday&quot;    &quot;Tuesday&quot;   &quot;Wednesday&quot;
## [7] &quot;Thursday&quot;</code></pre>
<div class="sourceCode" id="cb1271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1271-1"><a href="lubridate.html#cb1271-1" tabindex="-1"></a><span class="fu">months</span>(dates_vec)</span></code></pre></div>
<pre><code>## [1] &quot;January&quot;  &quot;January&quot;  &quot;January&quot;  &quot;January&quot;  &quot;February&quot; &quot;February&quot; &quot;February&quot;</code></pre>
<div class="sourceCode" id="cb1273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1273-1"><a href="lubridate.html#cb1273-1" tabindex="-1"></a><span class="fu">quarters</span>(dates_vec)</span></code></pre></div>
<pre><code>## [1] &quot;Q1&quot; &quot;Q1&quot; &quot;Q1&quot; &quot;Q1&quot; &quot;Q1&quot; &quot;Q1&quot; &quot;Q1&quot;</code></pre>
<div class="sourceCode" id="cb1275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1275-1"><a href="lubridate.html#cb1275-1" tabindex="-1"></a><span class="fu">julian</span>(dates_vec)</span></code></pre></div>
<pre><code>## [1] 15002 15003 15004 15005 15006 15007 15008
## attr(,&quot;origin&quot;)
## [1] &quot;1970-01-01&quot;</code></pre>
</div>
<div id="other-useful-related-functions" class="section level3" number="24.1.8">
<h3><span class="header-section-number">24.1.8</span> Other useful related functions</h3>
<p>There are certain other useful functions to the related classes which are useful in data analytics.</p>
<ol style="list-style-type: decimal">
<li><code>seq.Date(from, to, by, length.out = NULL, along.with = NULL, ...)</code> where-</li>
</ol>
<ul>
<li><code>from</code> and <code>to</code> are start and end dates respectively</li>
<li><code>by</code> is increment of sequence which can accept either of these
<ul>
<li>a number to be taken in days,</li>
<li>an object of class <code>difftime</code></li>
<li>a character string, containing one of “day”, “week”, “month”, “quarter” or “year”. This can optionally be preceded by a (positive or negative) integer and a space, or followed by “s”.</li>
</ul></li>
<li><code>length.out</code> is optional argument accepting an integer, for desired length of the sequence.</li>
<li><code>along.with</code> take the length from the length of this argument.</li>
</ul>
<p>Example-</p>
<div class="sourceCode" id="cb1277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1277-1"><a href="lubridate.html#cb1277-1" tabindex="-1"></a><span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">&quot;2000/1/1&quot;</span>), <span class="at">by =</span> <span class="st">&quot;month&quot;</span>, <span class="at">length.out =</span> <span class="dv">12</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;2000-01-01&quot; &quot;2000-02-01&quot; &quot;2000-03-01&quot; &quot;2000-04-01&quot; &quot;2000-05-01&quot;
##  [6] &quot;2000-06-01&quot; &quot;2000-07-01&quot; &quot;2000-08-01&quot; &quot;2000-09-01&quot; &quot;2000-10-01&quot;
## [11] &quot;2000-11-01&quot; &quot;2000-12-01&quot;</code></pre>
</div>
<div id="strpp" class="section level3" number="24.1.9">
<h3><span class="header-section-number">24.1.9</span> <code>strptime</code> character codes</h3>
<p>A few format codes useful to parse date/date-time objects in R, are listed below for ready reference. To know more about these codes, readers can see the output of <code>?strptime()</code> in their console. Some useful codes have been reproduced in the table <a href="lubridate.html#tab:lubri001">24.1</a> for ready reference.</p>
<table>
<caption><span id="tab:lubri001">Table 24.1: </span> Conversion Specifications for Date/Date-time</caption>
<colgroup>
<col width="27%" />
<col width="72%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Format</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><code>%y</code> (or <code>%Y</code>)</td>
<td>Year without (or with) Century</td>
</tr>
<tr class="even">
<td align="center"><code>%m</code></td>
<td>Month as decimal number (01-12)</td>
</tr>
<tr class="odd">
<td align="center"><code>%B</code> (or <code>%b</code>)</td>
<td>Month name in full (or abbreviated) in current locale</td>
</tr>
<tr class="even">
<td align="center"><code>%d</code></td>
<td>Day of the month (01-31)</td>
</tr>
<tr class="odd">
<td align="center"><code>%H</code></td>
<td>Hours as decimal number (00-23)</td>
</tr>
<tr class="even">
<td align="center"><code>%I</code></td>
<td>Hours as decimal number, in 12 hour format (00-12)</td>
</tr>
<tr class="odd">
<td align="center"><code>%M</code></td>
<td>Minute as decimal number (00-59)</td>
</tr>
<tr class="even">
<td align="center"><code>%S</code></td>
<td>Second as integer (00-61) allowing up to two leap-seconds</td>
</tr>
<tr class="odd">
<td align="center"><code>%OS</code></td>
<td>Second(s) as decimal number</td>
</tr>
<tr class="even">
<td align="center"><code>%T</code></td>
<td>Equivalent to <code>%H:%M:%S</code></td>
</tr>
<tr class="odd">
<td align="center"><code>%p</code></td>
<td>AM/PM indicator in the locale.</td>
</tr>
<tr class="even">
<td align="center"><code>%A</code> (or <code>%a</code>)</td>
<td>Full (or abbreviated) week-day name, in current locale</td>
</tr>
<tr class="odd">
<td align="center"><code>%j</code></td>
<td>Day of year as decimal number (001–366): For input, 366 is only valid in a leap year.</td>
</tr>
<tr class="even">
<td align="center"><code>%u</code></td>
<td>Weekday as a decimal number (1–7, Monday is 1)</td>
</tr>
<tr class="odd">
<td align="center"><code>%w</code></td>
<td>Weekday as decimal number (0–6, Sunday is 0).</td>
</tr>
<tr class="even">
<td align="center"><code>%U</code></td>
<td>Week of the year as decimal number (00–53) using Sunday as the first day 1 of the week (and typically with the first Sunday of the year as day 1 of week 1). <strong>The US convention.</strong></td>
</tr>
<tr class="odd">
<td align="center"><code>%V</code></td>
<td>Week of the year as decimal number (01–53) as defined in ISO 8601. If the week (starting on Monday) containing 1 January has four or more days in the new year, then it is considered week 1. Otherwise, it is the last week of the previous year, and the next week is week 1.</td>
</tr>
<tr class="even">
<td align="center"><code>%W</code></td>
<td>Week of the year as decimal number (00–53) using Monday as the first day of week (and typically with the first Monday of the year as day 1 of week 1). <strong>The UK convention</strong>.</td>
</tr>
<tr class="odd">
<td align="center"><code>%z</code></td>
<td>Offset from UTC</td>
</tr>
<tr class="even">
<td align="center"><code>%Z</code></td>
<td>Time Zone name</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="using-lubridate-package-for-parsingcreating-dates" class="section level2" number="24.2">
<h2><span class="header-section-number">24.2</span> Using <code>lubridate</code> package for parsing/creating dates</h2>
<p>Package <code>lubridate</code> which is now part of core <code>tidyverse</code> is extremely helpful package while analysing temporal variables in data. Creating date/date-time objects and converting variables from numeric/character to these types is easier than in base R. Besides, it offers us some other temporal class objects to make our time-series analysis easier.</p>
<div id="datedate-time-objects-creation" class="section level3" number="24.2.1">
<h3><span class="header-section-number">24.2.1</span> Date/date-time objects creation</h3>
<p>Date and Date-time object classes in <code>lubridate</code> are defined similarly as in base R. So we can create a date (or date-time) using a number of days (or seconds) elapsed since epoch.</p>
<div class="sourceCode" id="cb1279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1279-1"><a href="lubridate.html#cb1279-1" tabindex="-1"></a><span class="fu">library</span>(lubridate, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1279-2"><a href="lubridate.html#cb1279-2" tabindex="-1"></a><span class="co"># Creation using numbers</span></span>
<span id="cb1279-3"><a href="lubridate.html#cb1279-3" tabindex="-1"></a><span class="fu">as_date</span>(<span class="dv">2392</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1976-07-20&quot;</code></pre>
<div class="sourceCode" id="cb1281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1281-1"><a href="lubridate.html#cb1281-1" tabindex="-1"></a><span class="fu">as_datetime</span>(<span class="dv">206668800</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1976-07-20 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1283-1"><a href="lubridate.html#cb1283-1" tabindex="-1"></a><span class="co"># Converting from one type to another</span></span>
<span id="cb1283-2"><a href="lubridate.html#cb1283-2" tabindex="-1"></a>(date_today <span class="ot">&lt;-</span> <span class="fu">as_date</span>(<span class="fu">now</span>()))</span></code></pre></div>
<pre><code>## [1] &quot;2024-11-29&quot;</code></pre>
<div class="sourceCode" id="cb1285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1285-1"><a href="lubridate.html#cb1285-1" tabindex="-1"></a><span class="co"># Check its class</span></span>
<span id="cb1285-2"><a href="lubridate.html#cb1285-2" tabindex="-1"></a><span class="fu">class</span>(date_today)</span></code></pre></div>
<pre><code>## [1] &quot;Date&quot;</code></pre>
<div class="sourceCode" id="cb1287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1287-1"><a href="lubridate.html#cb1287-1" tabindex="-1"></a><span class="co"># Or see what&#39;s all in there</span></span>
<span id="cb1287-2"><a href="lubridate.html#cb1287-2" tabindex="-1"></a><span class="fu">unclass</span>(date_today)</span></code></pre></div>
<pre><code>## [1] 20056</code></pre>
</div>
<div id="parsing-datedate-time-objects-from-character" class="section level3" number="24.2.2">
<h3><span class="header-section-number">24.2.2</span> Parsing date/date-time objects from <code>character</code></h3>
<p>In <code>lubridate</code> parsing date/date-time objects from character strings is pretty easy as we have a number of functions useful to parse dates/date-times written in any specific locale/order irrespective of the delimiter used to separate different components of date/time therein. In these functions, the orders of the year (<code>y</code>), quarter (<code>q</code>), month (<code>m</code>) date (<code>d</code>) hour (<code>h</code>) minute (<code>m</code>) and second (<code>s</code>) are represented by their first characters. These are -</p>
<ul>
<li><code>ymd_hms</code>, <code>ymd_hm</code>, <code>ymd_h</code>, <code>ymd</code></li>
<li><code>dmy_hms</code>, <code>dmy_hm</code>, <code>dmy_h</code>, <code>dmy</code></li>
<li><code>mdy_hms</code>, <code>mdy_hm</code>, <code>mdy_h</code>, <code>mdy</code></li>
<li><code>ydm_hms</code>, <code>ydm_hm</code>, <code>ydm_h</code>, <code>ydm</code></li>
<li><code>myd</code>, <code>dym</code></li>
<li><code>yq</code>, <code>ym</code>, <code>my</code></li>
</ul>
<p>A few of the examples are -</p>
<div class="sourceCode" id="cb1289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1289-1"><a href="lubridate.html#cb1289-1" tabindex="-1"></a><span class="fu">ymd</span>(<span class="st">&quot;19760720&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1976-07-20&quot;</code></pre>
<div class="sourceCode" id="cb1291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1291-1"><a href="lubridate.html#cb1291-1" tabindex="-1"></a><span class="fu">dmy</span>(<span class="st">&quot;01.12.2004&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2004-12-01&quot;</code></pre>
<div class="sourceCode" id="cb1293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1293-1"><a href="lubridate.html#cb1293-1" tabindex="-1"></a><span class="fu">dmy</span>(<span class="st">&quot;15th of January, 2006&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2006-01-15&quot;</code></pre>
<div class="sourceCode" id="cb1295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1295-1"><a href="lubridate.html#cb1295-1" tabindex="-1"></a><span class="fu">mdy_hm</span>(<span class="st">&quot;August 15th, 1947 at 10:45 PM&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1947-08-15 22:45:00 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1297-1"><a href="lubridate.html#cb1297-1" tabindex="-1"></a><span class="fu">my</span>(<span class="st">&quot;04-2006&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2006-04-01&quot;</code></pre>
<div class="sourceCode" id="cb1299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1299-1"><a href="lubridate.html#cb1299-1" tabindex="-1"></a><span class="fu">yq</span>(<span class="st">&quot;2024: Quarter 4&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2024-10-01&quot;</code></pre>
<p>To parse date-time from a fraction of year passed, we can use <code>date_decimal()</code>. Example-</p>
<div class="sourceCode" id="cb1301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1301-1"><a href="lubridate.html#cb1301-1" tabindex="-1"></a><span class="fu">date_decimal</span>(<span class="fl">2024.162</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2024-02-29 07:00:28 UTC&quot;</code></pre>
</div>
<div id="parsing-datesdate-times-from-individual-conponents" class="section level3" number="24.2.3">
<h3><span class="header-section-number">24.2.3</span> Parsing dates/date-times from individual conponents</h3>
<p>For the scenario, where we have to create date/date-times we can make use of two functions <code>make_date</code> and <code>make_datetime</code>. Syntax is</p>
<pre><code>make_datetime(
  year = 1970L,
  month = 1L,
  day = 1L,
  hour = 0L,
  min = 0L,
  sec = 0,
  tz = &quot;UTC&quot;
)

make_date(year = 1970L, month = 1L, day = 1L)</code></pre>
<p>Example-</p>
<div class="sourceCode" id="cb1304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1304-1"><a href="lubridate.html#cb1304-1" tabindex="-1"></a><span class="fu">make_date</span>(<span class="at">year =</span> <span class="dv">1947</span>, <span class="at">month =</span> <span class="dv">8</span>, <span class="at">day =</span> <span class="dv">15</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1947-08-15&quot;</code></pre>
</div>
</div>
<div id="extracting-and-setting-datedate-time-components" class="section level2" number="24.3">
<h2><span class="header-section-number">24.3</span> Extracting and setting date/date-time components</h2>
<div id="extraction" class="section level3" number="24.3.1">
<h3><span class="header-section-number">24.3.1</span> Extraction</h3>
<p>We can extract the specific components from date/date-times using, intuitively named accessor functions, which are listed below. Note that in all of these functions the individual date components is in singular; as plural component functions will be used in different context, as we will discuss in Section <a href="lubridate.html#perriod">24.4.1</a>.</p>
<ul>
<li><code>year()</code> for Year; <code>isoyear()</code> for ISO 8601 Year</li>
<li><code>semester()</code> for Semester</li>
<li><code>quarter()</code> for Quarter</li>
<li><code>month()</code> for Month</li>
<li><code>week</code> for Week of the year, <code>isoweek()</code> for ISO 8601 Week</li>
<li><code>day</code> for Day of the month, <code>wday()</code> for Day of the week, <code>qday()</code> for Day of the quarter</li>
<li><code>hour()</code>, <code>minute()</code> and <code>second()</code> for Hour, Minute and Second respectively</li>
<li><code>tz()</code> for Time Zone</li>
</ul>
<p>See following examples.</p>
<div class="sourceCode" id="cb1306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1306-1"><a href="lubridate.html#cb1306-1" tabindex="-1"></a><span class="co"># Make an example date</span></span>
<span id="cb1306-2"><a href="lubridate.html#cb1306-2" tabindex="-1"></a>(a_time <span class="ot">&lt;-</span> <span class="fu">as_datetime</span>(<span class="dv">999999999</span>))</span></code></pre></div>
<pre><code>## [1] &quot;2001-09-09 01:46:39 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1308-1"><a href="lubridate.html#cb1308-1" tabindex="-1"></a><span class="co"># Extract the DAY of the month</span></span>
<span id="cb1308-2"><a href="lubridate.html#cb1308-2" tabindex="-1"></a><span class="fu">day</span>(a_time)</span></code></pre></div>
<pre><code>## [1] 9</code></pre>
<div class="sourceCode" id="cb1310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1310-1"><a href="lubridate.html#cb1310-1" tabindex="-1"></a><span class="co"># Extract Weekday name in full</span></span>
<span id="cb1310-2"><a href="lubridate.html#cb1310-2" tabindex="-1"></a><span class="fu">wday</span>(a_time, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] Sunday
## 7 Levels: Sunday &lt; Monday &lt; Tuesday &lt; Wednesday &lt; Thursday &lt; ... &lt; Saturday</code></pre>
<div class="sourceCode" id="cb1312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1312-1"><a href="lubridate.html#cb1312-1" tabindex="-1"></a><span class="co"># Extract second component</span></span>
<span id="cb1312-2"><a href="lubridate.html#cb1312-2" tabindex="-1"></a><span class="fu">second</span>(a_time)</span></code></pre></div>
<pre><code>## [1] 39</code></pre>
<div class="sourceCode" id="cb1314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1314-1"><a href="lubridate.html#cb1314-1" tabindex="-1"></a><span class="co"># Extract Month name (abbreviated)</span></span>
<span id="cb1314-2"><a href="lubridate.html#cb1314-2" tabindex="-1"></a><span class="fu">month</span>(a_time, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] Sep
## 12 Levels: Jan &lt; Feb &lt; Mar &lt; Apr &lt; May &lt; Jun &lt; Jul &lt; Aug &lt; Sep &lt; ... &lt; Dec</code></pre>
<div class="sourceCode" id="cb1316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1316-1"><a href="lubridate.html#cb1316-1" tabindex="-1"></a><span class="co"># Extract week number of the year</span></span>
<span id="cb1316-2"><a href="lubridate.html#cb1316-2" tabindex="-1"></a><span class="fu">week</span>(a_time)</span></code></pre></div>
<pre><code>## [1] 36</code></pre>
<p>Besides above functions, there are a few functions which are helpful in knowing certain characteristics of date/date-time variable. These functions return which logical vectors, are listed as -</p>
<ul>
<li><code>am(x)</code>, <code>pm(x)</code> to know whether the <code>x</code> is in AM or PM, respectively.</li>
<li><code>dst(x)</code> to know whether <code>x</code> is in Daylight savings.</li>
<li><code>leap_year(x)</code> to know whether <code>x</code> is a leap year.</li>
</ul>
<p>Examples-</p>
<div class="sourceCode" id="cb1318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1318-1"><a href="lubridate.html#cb1318-1" tabindex="-1"></a><span class="co"># Is our a_time AM?</span></span>
<span id="cb1318-2"><a href="lubridate.html#cb1318-2" tabindex="-1"></a><span class="fu">am</span>(a_time)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb1320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1320-1"><a href="lubridate.html#cb1320-1" tabindex="-1"></a><span class="co"># Is a_time falling in leap year?</span></span>
<span id="cb1320-2"><a href="lubridate.html#cb1320-2" tabindex="-1"></a><span class="fu">leap_year</span>(a_time)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb1322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1322-1"><a href="lubridate.html#cb1322-1" tabindex="-1"></a><span class="co"># Is it during DST?</span></span>
<span id="cb1322-2"><a href="lubridate.html#cb1322-2" tabindex="-1"></a><span class="fu">dst</span>(a_time)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
</div>
<div id="setting-components" class="section level3" number="24.3.2">
<h3><span class="header-section-number">24.3.2</span> Setting Components</h3>
<p>Just like we used accessor functions to extract the date-time components, we can use those functions to set specific component in date/date-time object/variable. See Example-</p>
<div class="sourceCode" id="cb1324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1324-1"><a href="lubridate.html#cb1324-1" tabindex="-1"></a><span class="co"># Initial variable</span></span>
<span id="cb1324-2"><a href="lubridate.html#cb1324-2" tabindex="-1"></a>a_time</span></code></pre></div>
<pre><code>## [1] &quot;2001-09-09 01:46:39 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1326-1"><a href="lubridate.html#cb1326-1" tabindex="-1"></a><span class="co"># Setting component - Year</span></span>
<span id="cb1326-2"><a href="lubridate.html#cb1326-2" tabindex="-1"></a><span class="fu">year</span>(a_time) <span class="ot">&lt;-</span> <span class="dv">2024</span></span>
<span id="cb1326-3"><a href="lubridate.html#cb1326-3" tabindex="-1"></a><span class="co"># Print modified variable</span></span>
<span id="cb1326-4"><a href="lubridate.html#cb1326-4" tabindex="-1"></a>a_time</span></code></pre></div>
<pre><code>## [1] &quot;2024-09-09 01:46:39 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1328-1"><a href="lubridate.html#cb1328-1" tabindex="-1"></a><span class="co"># Modify Time zone</span></span>
<span id="cb1328-2"><a href="lubridate.html#cb1328-2" tabindex="-1"></a><span class="fu">tz</span>(a_time) <span class="ot">&lt;-</span> <span class="st">&quot;Asia/Kolkata&quot;</span></span>
<span id="cb1328-3"><a href="lubridate.html#cb1328-3" tabindex="-1"></a><span class="co"># print modified variable</span></span>
<span id="cb1328-4"><a href="lubridate.html#cb1328-4" tabindex="-1"></a>a_time</span></code></pre></div>
<pre><code>## [1] &quot;2024-09-09 01:46:39 IST&quot;</code></pre>
<p>Finally, function <code>update</code> can also be used to return a date with the specified elements updated. Example-</p>
<div class="sourceCode" id="cb1330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1330-1"><a href="lubridate.html#cb1330-1" tabindex="-1"></a>EOD <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="st">&quot;31-01-2024&quot;</span>)</span>
<span id="cb1330-2"><a href="lubridate.html#cb1330-2" tabindex="-1"></a>EOD <span class="ot">&lt;-</span> <span class="fu">update</span>(EOD, <span class="at">year =</span> <span class="dv">2020</span>)</span>
<span id="cb1330-3"><a href="lubridate.html#cb1330-3" tabindex="-1"></a>EOD</span></code></pre></div>
<pre><code>## [1] &quot;2020-01-31&quot;</code></pre>
<div class="sourceCode" id="cb1332"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1332-1"><a href="lubridate.html#cb1332-1" tabindex="-1"></a><span class="co"># If values are too big, they will roll-over:</span></span>
<span id="cb1332-2"><a href="lubridate.html#cb1332-2" tabindex="-1"></a><span class="fu">update</span>(EOD, <span class="at">month =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2020-03-02&quot;</code></pre>
</div>
</div>
<div id="time-spans" class="section level2" number="24.4">
<h2><span class="header-section-number">24.4</span> Time spans</h2>
<p>When we subtract a date-time object from another in base R, we get a <code>difftime</code> object, as we have already seen in section <a href="lubridate.html#diffftime">24.1.4</a>.</p>
<p>We know that every time/date unit is not same in strict sense. Like leap years may have 366 days whereas others have 365 days. Now there is a concept of leap seconds too. Moreover, certain countries have daylight saving time and thus, every day is not of equal length there. In order to deal with specific and clear requirements on date calculations, there are three different classes in <code>lubridate</code>, as discussed next.</p>
<p>Lubridate has three classes, which may sound similar at first, but are different in their working. These are -</p>
<ul>
<li><code>period</code></li>
<li><code>duration</code></li>
<li><code>interval</code></li>
</ul>
<p>Let us discuss about each one separately.</p>
<div id="perriod" class="section level3" number="24.4.1">
<h3><span class="header-section-number">24.4.1</span> Periods</h3>
<p>The <code>period</code> objects track changes in clock times and ignore time line irregularities. So every time object is of standard length like our clocks.</p>
<p>Period objects can be created in <code>lubridate</code> using <strong>pluralized</strong> date component functions. Example-</p>
<div class="sourceCode" id="cb1334"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1334-1"><a href="lubridate.html#cb1334-1" tabindex="-1"></a>(one_year <span class="ot">&lt;-</span> <span class="fu">years</span>(<span class="dv">1</span>))</span></code></pre></div>
<pre><code>## [1] &quot;1y 0m 0d 0H 0M 0S&quot;</code></pre>
<div class="sourceCode" id="cb1336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1336-1"><a href="lubridate.html#cb1336-1" tabindex="-1"></a><span class="fu">class</span>(one_year)</span></code></pre></div>
<pre><code>## [1] &quot;Period&quot;
## attr(,&quot;package&quot;)
## [1] &quot;lubridate&quot;</code></pre>
<div class="sourceCode" id="cb1338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1338-1"><a href="lubridate.html#cb1338-1" tabindex="-1"></a><span class="co"># Add one year PERIOD to get a leap year?</span></span>
<span id="cb1338-2"><a href="lubridate.html#cb1338-2" tabindex="-1"></a>a_date <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="st">&quot;01-03-2019&quot;</span>)</span>
<span id="cb1338-3"><a href="lubridate.html#cb1338-3" tabindex="-1"></a>a_date <span class="sc">+</span> <span class="fu">years</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2020-03-01&quot;</code></pre>
</div>
<div id="durations" class="section level3" number="24.4.2">
<h3><span class="header-section-number">24.4.2</span> Durations</h3>
<p>Durations, on the other hand track changes in physical time, i.e. taking into account all the timeline adjusting irregularities. These duration objects can be created in lubridate, by adding <code>d</code> as prefix to all pluralized <code>period</code> objects.</p>
<div class="sourceCode" id="cb1340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1340-1"><a href="lubridate.html#cb1340-1" tabindex="-1"></a>(one_year_duration <span class="ot">&lt;-</span> <span class="fu">dyears</span>(<span class="dv">1</span>))</span></code></pre></div>
<pre><code>## [1] &quot;31557600s (~1 years)&quot;</code></pre>
<div class="sourceCode" id="cb1342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1342-1"><a href="lubridate.html#cb1342-1" tabindex="-1"></a><span class="fu">class</span>(one_year_duration)</span></code></pre></div>
<pre><code>## [1] &quot;Duration&quot;
## attr(,&quot;package&quot;)
## [1] &quot;lubridate&quot;</code></pre>
<div class="sourceCode" id="cb1344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1344-1"><a href="lubridate.html#cb1344-1" tabindex="-1"></a><span class="co"># Add one year DURATION to get a leap year date?</span></span>
<span id="cb1344-2"><a href="lubridate.html#cb1344-2" tabindex="-1"></a>a_date <span class="sc">+</span> <span class="fu">dyears</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2020-02-29 06:00:00 UTC&quot;</code></pre>
</div>
<div id="intervals" class="section level3" number="24.4.3">
<h3><span class="header-section-number">24.4.3</span> Intervals</h3>
<p>The objects of class <code>interval</code> represent <strong>specific</strong> interval on the timeline. In other words, these have a specific start and end date/datetimes. These can be created in lubridate using function <code>interval</code>, which has syntax like -</p>
<pre><code>interval(start = NULL, end = NULL, tzone = tz(start))</code></pre>
<p>This should be clear with the following examples.</p>
<div class="sourceCode" id="cb1347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1347-1"><a href="lubridate.html#cb1347-1" tabindex="-1"></a>(a_interval <span class="ot">&lt;-</span> <span class="fu">interval</span>(<span class="fu">dmy</span>(<span class="st">&quot;15-08-1947&quot;</span>), <span class="fu">today</span>()))</span></code></pre></div>
<pre><code>## [1] 1947-08-15 UTC--2024-11-29 UTC</code></pre>
<div class="sourceCode" id="cb1349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1349-1"><a href="lubridate.html#cb1349-1" tabindex="-1"></a><span class="fu">class</span>(a_interval)</span></code></pre></div>
<pre><code>## [1] &quot;Interval&quot;
## attr(,&quot;package&quot;)
## [1] &quot;lubridate&quot;</code></pre>
<p>Intervals can also be created using special operator <code>%--%</code>. E.g.</p>
<div class="sourceCode" id="cb1351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1351-1"><a href="lubridate.html#cb1351-1" tabindex="-1"></a>(interval1 <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="st">&quot;15-08-1947&quot;</span>) <span class="sc">%--%</span> <span class="fu">dmy</span>(<span class="st">&quot;26-01-1950&quot;</span>))</span></code></pre></div>
<pre><code>## [1] 1947-08-15 UTC--1950-01-26 UTC</code></pre>
</div>
</div>
<div id="performing-calculations-on-intervalsdates" class="section level2" number="24.5">
<h2><span class="header-section-number">24.5</span> Performing calculations on intervals/dates</h2>
<p>There are a few functions to make our life easier while performing data analysis on temporal fields. These are -</p>
<div id="within-operator" class="section level3" number="24.5.1">
<h3><span class="header-section-number">24.5.1</span> <code>%within%</code> operator</h3>
<p>Operator <code>a %within% b</code> checks whether interval/date-time <code>a</code> falls with interval <code>b</code>. Returns boolean value(s).</p>
<div class="sourceCode" id="cb1353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1353-1"><a href="lubridate.html#cb1353-1" tabindex="-1"></a>interval1 <span class="sc">%within%</span> a_interval</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="backward-intervals" class="section level3" number="24.5.2">
<h3><span class="header-section-number">24.5.2</span> Backward intervals</h3>
<p>Intervals in lubridate can be backwards too. E.g.</p>
<div class="sourceCode" id="cb1355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1355-1"><a href="lubridate.html#cb1355-1" tabindex="-1"></a>(back_interval <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="st">&quot;26-01-2024&quot;</span>) <span class="sc">%--%</span> <span class="fu">dmy</span>(<span class="st">&quot;15-01-2024&quot;</span>))</span></code></pre></div>
<pre><code>## [1] 2024-01-26 UTC--2024-01-15 UTC</code></pre>
</div>
<div id="flipping-intervals" class="section level3" number="24.5.3">
<h3><span class="header-section-number">24.5.3</span> Flipping intervals</h3>
<p>Function <code>int_flip()</code> can flip the interval. E.g.</p>
<div class="sourceCode" id="cb1357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1357-1"><a href="lubridate.html#cb1357-1" tabindex="-1"></a><span class="fu">int_flip</span>(back_interval)</span></code></pre></div>
<pre><code>## [1] 2024-01-15 UTC--2024-01-26 UTC</code></pre>
</div>
<div id="checking-alignment-of-two-intervals" class="section level3" number="24.5.4">
<h3><span class="header-section-number">24.5.4</span> Checking alignment of two intervals</h3>
<p>Function <code>int_aligns</code> tests if two intervals share an endpoint. The direction of each interval is ignored. In other words, it actually tests whether the earliest or latest moments of each interval occur at the same time. E.g.</p>
<div class="sourceCode" id="cb1359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1359-1"><a href="lubridate.html#cb1359-1" tabindex="-1"></a>int1 <span class="ot">&lt;-</span> <span class="fu">interval</span>(<span class="fu">ymd</span>(<span class="st">&quot;2001-01-01&quot;</span>), <span class="fu">ymd</span>(<span class="st">&quot;2002-01-01&quot;</span>))</span>
<span id="cb1359-2"><a href="lubridate.html#cb1359-2" tabindex="-1"></a>int2 <span class="ot">&lt;-</span> <span class="fu">interval</span>(<span class="fu">ymd</span>(<span class="st">&quot;2001-06-01&quot;</span>), <span class="fu">ymd</span>(<span class="st">&quot;2002-01-01&quot;</span>))</span>
<span id="cb1359-3"><a href="lubridate.html#cb1359-3" tabindex="-1"></a>int3 <span class="ot">&lt;-</span> <span class="fu">interval</span>(<span class="fu">ymd</span>(<span class="st">&quot;2003-01-01&quot;</span>), <span class="fu">ymd</span>(<span class="st">&quot;2004-01-01&quot;</span>))</span>
<span id="cb1359-4"><a href="lubridate.html#cb1359-4" tabindex="-1"></a></span>
<span id="cb1359-5"><a href="lubridate.html#cb1359-5" tabindex="-1"></a><span class="fu">int_aligns</span>(int1, int2)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb1361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1361-1"><a href="lubridate.html#cb1361-1" tabindex="-1"></a><span class="fu">int_aligns</span>(int1, int3)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
</div>
<div id="checking-overlap-in-two-intervals" class="section level3" number="24.5.5">
<h3><span class="header-section-number">24.5.5</span> Checking Overlap in two intervals</h3>
<p>Function <code>int_overlaps</code> can test if two intervals overlap each other.</p>
<div class="sourceCode" id="cb1363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1363-1"><a href="lubridate.html#cb1363-1" tabindex="-1"></a><span class="fu">int_overlaps</span>(int1, int2)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="length-of-the-interval" class="section level3" number="24.5.6">
<h3><span class="header-section-number">24.5.6</span> Length of the interval</h3>
<p>Function <code>int_length()</code> can calculate the length of interval and returns a <code>numeric</code> variable equal to the seconds in that interval. E.g.</p>
<div class="sourceCode" id="cb1365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1365-1"><a href="lubridate.html#cb1365-1" tabindex="-1"></a><span class="fu">int_length</span>(back_interval)</span></code></pre></div>
<pre><code>## [1] -950400</code></pre>
</div>
<div id="adding-months-without-exceeding-last-day-of-the-month." class="section level3" number="24.5.7">
<h3><span class="header-section-number">24.5.7</span> Adding Months without exceeding last day of the month.</h3>
<p>Operators <code>%m+%</code> and <code>%m-%</code> will add (or subtract) months to a date without exceeding the last day of the new month. E.g.</p>
<div class="sourceCode" id="cb1367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1367-1"><a href="lubridate.html#cb1367-1" tabindex="-1"></a>(leap <span class="ot">&lt;-</span> <span class="fu">ymd</span>(<span class="st">&quot;2012-02-29&quot;</span>))</span></code></pre></div>
<pre><code>## [1] &quot;2012-02-29&quot;</code></pre>
<div class="sourceCode" id="cb1369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1369-1"><a href="lubridate.html#cb1369-1" tabindex="-1"></a>leap <span class="sc">%m+%</span> <span class="fu">years</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2013-02-28&quot;</code></pre>
<div class="sourceCode" id="cb1371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1371-1"><a href="lubridate.html#cb1371-1" tabindex="-1"></a>leap <span class="sc">%m+%</span> <span class="fu">years</span>(<span class="sc">-</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2011-02-28&quot;</code></pre>
<div class="sourceCode" id="cb1373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1373-1"><a href="lubridate.html#cb1373-1" tabindex="-1"></a>leap <span class="sc">%m-%</span> <span class="fu">years</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2011-02-28&quot;</code></pre>
<p>Another Example-</p>
<div class="sourceCode" id="cb1375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1375-1"><a href="lubridate.html#cb1375-1" tabindex="-1"></a>jan <span class="ot">&lt;-</span> <span class="fu">ymd_hms</span>(<span class="st">&quot;2010-01-31 03:04:05&quot;</span>)</span>
<span id="cb1375-2"><a href="lubridate.html#cb1375-2" tabindex="-1"></a>jan <span class="sc">+</span> <span class="fu">months</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) <span class="co"># Feb 31 and April 31 returned as NA</span></span></code></pre></div>
<pre><code>## [1] NA                        &quot;2010-03-31 03:04:05 UTC&quot;
## [3] NA</code></pre>
<div class="sourceCode" id="cb1377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1377-1"><a href="lubridate.html#cb1377-1" tabindex="-1"></a><span class="co"># NA &quot;2010-03-31 03:04:05 UTC&quot; NA</span></span>
<span id="cb1377-2"><a href="lubridate.html#cb1377-2" tabindex="-1"></a>jan <span class="sc">%m+%</span> <span class="fu">months</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) <span class="co"># No rollover</span></span></code></pre></div>
<pre><code>## [1] &quot;2010-02-28 03:04:05 UTC&quot; &quot;2010-03-31 03:04:05 UTC&quot;
## [3] &quot;2010-04-30 03:04:05 UTC&quot;</code></pre>
</div>
<div id="adding-with-rollback" class="section level3" number="24.5.8">
<h3><span class="header-section-number">24.5.8</span> Adding with Rollback</h3>
<p>One more function <code>add_with_rollback()</code> which performs similarly, but has more control due to specific syntax-</p>
<pre><code>add_with_rollback(e1, e2, roll_to_first = FALSE, preserve_hms = TRUE)</code></pre>
<p>Example-</p>
<div class="sourceCode" id="cb1380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1380-1"><a href="lubridate.html#cb1380-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">ymd_hms</span>(<span class="st">&quot;2019-01-29 01:02:03&quot;</span>)</span>
<span id="cb1380-2"><a href="lubridate.html#cb1380-2" tabindex="-1"></a><span class="fu">add_with_rollback</span>(x, <span class="fu">months</span>(<span class="dv">1</span>))</span></code></pre></div>
<pre><code>## [1] &quot;2019-02-28 01:02:03 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1382-1"><a href="lubridate.html#cb1382-1" tabindex="-1"></a><span class="fu">add_with_rollback</span>(x, <span class="fu">months</span>(<span class="dv">1</span>), <span class="at">preserve_hms =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2019-02-28 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1384-1"><a href="lubridate.html#cb1384-1" tabindex="-1"></a><span class="fu">add_with_rollback</span>(x, <span class="fu">months</span>(<span class="dv">1</span>), <span class="at">roll_to_first =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2019-03-01 01:02:03 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1386-1"><a href="lubridate.html#cb1386-1" tabindex="-1"></a><span class="fu">add_with_rollback</span>(x, <span class="fu">months</span>(<span class="dv">1</span>), <span class="at">roll_to_first =</span> <span class="cn">TRUE</span>, <span class="at">preserve_hms =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2019-03-01 UTC&quot;</code></pre>
</div>
<div id="coercing-one-time-span-unit-to-another" class="section level3" number="24.5.9">
<h3><span class="header-section-number">24.5.9</span> Coercing one time span unit to another</h3>
<p>Time-span objects in lubridate can be coerced from one to another using coercing functions,</p>
<ul>
<li><code>as.period(x, unit)</code></li>
<li><code>as.duration(x)</code></li>
<li><code>as.interval(x, start)</code></li>
<li><code>make_difftime(x)</code></li>
</ul>
<p>Examples-</p>
<div class="sourceCode" id="cb1388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1388-1"><a href="lubridate.html#cb1388-1" tabindex="-1"></a><span class="co"># With Period - clock time</span></span>
<span id="cb1388-2"><a href="lubridate.html#cb1388-2" tabindex="-1"></a>(per <span class="ot">&lt;-</span> <span class="fu">days</span>(<span class="dv">31</span>))</span></code></pre></div>
<pre><code>## [1] &quot;31d 0H 0M 0S&quot;</code></pre>
<div class="sourceCode" id="cb1390"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1390-1"><a href="lubridate.html#cb1390-1" tabindex="-1"></a>(int1 <span class="ot">&lt;-</span> <span class="fu">as.interval</span>(per, <span class="fu">dmy</span>(<span class="st">&quot;01022020&quot;</span>)))</span></code></pre></div>
<pre><code>## [1] 2020-02-01 UTC--2020-03-03 UTC</code></pre>
<div class="sourceCode" id="cb1392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1392-1"><a href="lubridate.html#cb1392-1" tabindex="-1"></a><span class="co"># With Duration - physical time</span></span>
<span id="cb1392-2"><a href="lubridate.html#cb1392-2" tabindex="-1"></a>(dur <span class="ot">&lt;-</span> <span class="fu">ddays</span>(<span class="dv">31</span>))</span></code></pre></div>
<pre><code>## [1] &quot;2678400s (~4.43 weeks)&quot;</code></pre>
<div class="sourceCode" id="cb1394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1394-1"><a href="lubridate.html#cb1394-1" tabindex="-1"></a>(int2 <span class="ot">&lt;-</span> <span class="fu">as.interval</span>(dur, <span class="fu">dmy</span>(<span class="st">&quot;01022020&quot;</span>)))</span></code></pre></div>
<pre><code>## [1] 2020-02-01 UTC--2020-03-03 UTC</code></pre>
</div>
</div>
<div id="rounding-date-time-variables" class="section level2" number="24.6">
<h2><span class="header-section-number">24.6</span> Rounding date-time variables</h2>
<p>There are dedicated functions to round the dates as per specific requirements.</p>
<ul>
<li><code>floor_date()</code> takes a date-time object and rounds it down to the nearest boundary of the specified time unit.</li>
<li><code>ceiling_date()</code> takes a date-time object and rounds it up to the nearest boundary of the specified time unit.</li>
<li><code>round_date()</code> takes a date-time object and time unit, and rounds it to the nearest value of the specified time unit.</li>
</ul>
<p>Examples-</p>
<div class="sourceCode" id="cb1396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1396-1"><a href="lubridate.html#cb1396-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">ymd_hms</span>(<span class="st">&quot;2009-08-03 12:01:59.23&quot;</span>)</span>
<span id="cb1396-2"><a href="lubridate.html#cb1396-2" tabindex="-1"></a><span class="fu">round_date</span>(x, <span class="st">&quot;month&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2009-08-01 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1398-1"><a href="lubridate.html#cb1398-1" tabindex="-1"></a><span class="fu">round_date</span>(x, <span class="st">&quot;week&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2009-08-02 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1400-1"><a href="lubridate.html#cb1400-1" tabindex="-1"></a><span class="fu">floor_date</span>(x, <span class="st">&quot;day&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2009-08-03 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1402-1"><a href="lubridate.html#cb1402-1" tabindex="-1"></a><span class="fu">ceiling_date</span>(x, <span class="st">&quot;month&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2009-09-01 UTC&quot;</code></pre>
<p>Three other functions helps rolling a date forward or backwards, as</p>
<ul>
<li><code>rollbackward()</code> changes a date to the last day of the previous month or to the first day of the month.</li>
<li><code>rollforward()</code> rolls to the last day of the current month or to the first day of the next month. Optionally, the new date can retain the same hour, minute, and second information.</li>
<li><code>rollback()</code> is a synonym for <code>rollbackward()</code>.</li>
</ul>
<p>See these examples-</p>
<div class="sourceCode" id="cb1404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1404-1"><a href="lubridate.html#cb1404-1" tabindex="-1"></a>date <span class="ot">&lt;-</span> <span class="fu">ymd_hms</span>(<span class="st">&quot;2010-03-03 12:44:22&quot;</span>)</span>
<span id="cb1404-2"><a href="lubridate.html#cb1404-2" tabindex="-1"></a></span>
<span id="cb1404-3"><a href="lubridate.html#cb1404-3" tabindex="-1"></a><span class="fu">rollbackward</span>(date)</span></code></pre></div>
<pre><code>## [1] &quot;2010-02-28 12:44:22 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1406-1"><a href="lubridate.html#cb1406-1" tabindex="-1"></a><span class="fu">rollbackward</span>(date, <span class="at">roll_to_first =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2010-03-01 12:44:22 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1408-1"><a href="lubridate.html#cb1408-1" tabindex="-1"></a><span class="fu">rollbackward</span>(date, <span class="at">preserve_hms =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2010-02-28 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1410-1"><a href="lubridate.html#cb1410-1" tabindex="-1"></a><span class="fu">rollbackward</span>(date, <span class="at">roll_to_first =</span> <span class="cn">TRUE</span>, <span class="at">preserve_hms =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2010-03-01 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1412-1"><a href="lubridate.html#cb1412-1" tabindex="-1"></a><span class="fu">rollforward</span>(date)</span></code></pre></div>
<pre><code>## [1] &quot;2010-03-31 12:44:22 UTC&quot;</code></pre>
<div class="sourceCode" id="cb1414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1414-1"><a href="lubridate.html#cb1414-1" tabindex="-1"></a><span class="fu">rollforward</span>(date, <span class="at">roll_to_first =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] &quot;2010-04-01 12:44:22 UTC&quot;</code></pre>
</div>
<div id="representing-date-and-date-times-in-cutomised-formats" class="section level2" number="24.7">
<h2><span class="header-section-number">24.7</span> Representing date and date-times in cutomised formats</h2>
<p>In all of the above sections, we saw that once R recognises a temporal object, it depicts that objects in a uniform format. See</p>
<div class="sourceCode" id="cb1416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1416-1"><a href="lubridate.html#cb1416-1" tabindex="-1"></a>(date1 <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="st">&quot;01-01-2020&quot;</span>))</span></code></pre></div>
<pre><code>## [1] &quot;2020-01-01&quot;</code></pre>
<div class="sourceCode" id="cb1418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1418-1"><a href="lubridate.html#cb1418-1" tabindex="-1"></a>(date2 <span class="ot">&lt;-</span> <span class="fu">ymd</span>(<span class="st">&quot;2020/01/01&quot;</span>))</span></code></pre></div>
<pre><code>## [1] &quot;2020-01-01&quot;</code></pre>
<div class="sourceCode" id="cb1420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1420-1"><a href="lubridate.html#cb1420-1" tabindex="-1"></a><span class="fu">as.character</span>(date1)</span></code></pre></div>
<pre><code>## [1] &quot;2020-01-01&quot;</code></pre>
<p>In the output/console all dates print like a character/string. However, sometimes requirement is to have print dates in a specific customised format. In this scenario, function <code>strftime()</code> comes to our rescue which converts objects of classes “POSIXlt” and “POSIXct” representing calendar dates and times to specific character representation. Character codes can be used from the table <a href="lubridate.html#tab:lubri001">24.1</a> in section <a href="lubridate.html#strpp">24.1.9</a>.</p>
<p>See following examples-</p>
<div class="sourceCode" id="cb1422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1422-1"><a href="lubridate.html#cb1422-1" tabindex="-1"></a><span class="fu">strftime</span>(<span class="fu">Sys.Date</span>(), <span class="at">format =</span> <span class="st">&quot;%d %B %Y&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;29 November 2024&quot;</code></pre>
<p>In this context, let’s also discuss about a special date stamping function in <code>lubridate</code> which can format date/time outputs based on human friendly formats. Functions <code>stamp()</code>, <code>stamp_date</code> and <code>stamp_time()</code> will create a function from the given template, which can be applied to date/time objects to re-format them. Example-</p>
<div class="sourceCode" id="cb1424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1424-1"><a href="lubridate.html#cb1424-1" tabindex="-1"></a>eclipse_dates <span class="ot">&lt;-</span> <span class="fu">dmy</span>(<span class="fu">c</span>(<span class="st">&quot;11-7-2010&quot;</span>, <span class="st">&quot;13-11-2012&quot;</span>, <span class="st">&quot;3-11-2013&quot;</span>))</span>
<span id="cb1424-2"><a href="lubridate.html#cb1424-2" tabindex="-1"></a>eclipse_stamp <span class="ot">&lt;-</span> <span class="fu">stamp_date</span>(<span class="st">&quot;There was a solar eclipse on January 13th, 1999&quot;</span>)</span>
<span id="cb1424-3"><a href="lubridate.html#cb1424-3" tabindex="-1"></a><span class="fu">eclipse_stamp</span>(eclipse_dates)</span></code></pre></div>
<pre><code>## [1] &quot;There was a solar eclipse on July 11th, 2010&quot;    
## [2] &quot;There was a solar eclipse on November 13th, 2012&quot;
## [3] &quot;There was a solar eclipse on November 03th, 2013&quot;</code></pre>
</div>
<div id="dates-in-ggplot2-visualisations" class="section level2" number="24.8">
<h2><span class="header-section-number">24.8</span> Dates in GGPLOT2 visualisations</h2>
<p>Before concluding the chapter on date and time variables, it is important to learn the related functions to deal with impact of date and time formats on visualisations. Since we have already seen that, date and date-time variables are actually continuous variables with labels depicted in a specific formats, we have two <code>scale</code> functions in ggplot2 to deal with -</p>
<ul>
<li><code>scale_x_date()</code></li>
<li><code>scale_x_datetime()</code></li>
</ul>
<p>In these functions, we have <code>date_breaks</code> and <code>date_minor_breaks</code> arguments to position the breaks by date units. E.g. <code>date_breaks = "6 months"</code> will place major tick mark every six months.</p>
<p>Using another argument <code>date_labels</code> we can control the display of the labels in the plots. The values of the argument may be in <code>strptime</code> formats as we have already seen in <a href="lubridate.html#tab:lubri001">24.1</a> above.</p>
<p>Example-</p>
<div class="sourceCode" id="cb1426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1426-1"><a href="lubridate.html#cb1426-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1426-2"><a href="lubridate.html#cb1426-2" tabindex="-1"></a></span>
<span id="cb1426-3"><a href="lubridate.html#cb1426-3" tabindex="-1"></a>economics <span class="sc">%&gt;%</span> </span>
<span id="cb1426-4"><a href="lubridate.html#cb1426-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(date, uempmed)) <span class="sc">+</span></span>
<span id="cb1426-5"><a href="lubridate.html#cb1426-5" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1426-6"><a href="lubridate.html#cb1426-6" tabindex="-1"></a>  <span class="fu">scale_x_date</span>(<span class="at">date_labels =</span> <span class="st">&quot;%Y&quot;</span>, </span>
<span id="cb1426-7"><a href="lubridate.html#cb1426-7" tabindex="-1"></a>               <span class="at">date_breaks =</span> <span class="st">&quot;5 years&quot;</span>, </span>
<span id="cb1426-8"><a href="lubridate.html#cb1426-8" tabindex="-1"></a>               <span class="at">date_minor_breaks =</span> <span class="st">&quot;1 year&quot;</span>) <span class="sc">+</span></span>
<span id="cb1426-9"><a href="lubridate.html#cb1426-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-417"></span>
<img src="DauR_files/figure-html/unnamed-chunk-417-1.png" alt="Use of Date Time Scale in ggplot2" width="672" />
<p class="caption">
Figure 24.1: Use of Date Time Scale in ggplot2
</p>
</div>
<hr />

</div>
</div>
  </main>

  <div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page">
      <h2>On this page</h2>
      <div id="book-on-this-page"></div>

      <div class="book-extra">
        <ul class="list-unstyled">
          <li><a id="book-source" href="#">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="#">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
      </div>
    </nav>
  </div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5">
  <div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>R for Audit Analytics</strong>" was written by Anil Goyal. It was last built on 2024-11-29.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
<script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>

</html>
