{
  "hash": "42f4530b2b390f976c112edca41445af",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n# Functional Programming {#sec-fp}\n\n\n::: {.cell}\n\n:::\n\n\nA Public Works department has dozens of divisions. Each sends its voucher file every month. The auditor wants to run the same checks on every file. What did the division spend? How much of it was spent in March? Which vouchers are above the limit? Doing this by hand, file by file, is slow. Copying the code for each file and editing it is quicker, but risky. One forgotten edit, and one division is checked against the wrong limit, without anyone noticing.\n\nThe better way is to write the check *once*, as a function, and then tell R to apply it to every file. This idea, applying a function to each element of a collection, is the heart of *functional programming*. R is very good at it.\n\nIn this chapter we learn the base R tools for this, the `apply` family, and then the more consistent tools of the package `purrr`. We practise on the voucher register of four sub-division offices, and on its quarter-wise expenditure. At the end, we check every office for a rush of expenditure in March, with one function applied to all four.\n\n## What is functional programming?\n\nConceptually functional programming philosophy is based on lambda calculus. Lambda calculus is a framework developed by Alonzo Church^[Alan Turing, who created Turing machine which in turn laid the foundation of imperative programming style, was a student of __Alonzo Church__.] to study computations with functions.\n\nFunctional programming is a style of programming built around functions, in the mathematical sense. It is *declarative*. Its focus is on __what to solve__, in contrast to the *imperative* style, like a `for` loop, whose focus is on __how to solve__. For a fuller definition, readers may see this Wikipedia [link](https://en.wikipedia.org/wiki/Functional_programming). Put simply, instead of writing a loop which says \"take the first element, do this, store the result, take the next element...\", we say \"apply this function to every element\", and let R do the rest.\n\nFunctional programming uses *higher-order functions*, functions which take another function as an argument, or return a function. We have already seen one, perhaps without noticing. `args()` takes a function as its argument, and returns its arguments.\n\nLet us learn a bit more here.\n\n## Our data, vouchers of four offices {#sec-fp-data}\n\nOur data is the voucher register of a Public Works division for the financial year 2024-25. It has four sub-division offices, at Pune, Nashik, Nagpur and Kolhapur. Each row is one voucher, with its office, date, amount and the GST in it. One office has a rush of large payments in the last fortnight of March, which we find at the end of the chapter. From the vouchers we also make a small matrix, `qexp`, of the expenditure of each office in each quarter, in lakh. All names are made up, and the code is folded.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to create the vouchers and the quarter-wise expenditure\"}\nset.seed(7)\noffices <- c(\"Pune\", \"Nashik\", \"Nagpur\", \"Kolhapur\")\nn <- 160\nvouchers <- data.frame(\n  office       = sample(offices, n, replace = TRUE),\n  voucher_date = as.Date(\"2024-04-01\") + sample(0:364, n, replace = TRUE),\n  amount       = round(runif(n, 20000, 200000), -2)\n)\n\n# Planted. A rush of large payments at Nagpur in the second half of March 2025\nmarch_rush <- data.frame(\n  office       = \"Nagpur\",\n  voucher_date = as.Date(\"2025-03-17\") + c(0, 3, 5, 8, 10, 12, 13),\n  amount       = c(480000, 520000, 450000, 610000, 395000, 560000, 470000)\n)\n\nvouchers <- rbind(vouchers, march_rush)\nvouchers <- vouchers[order(vouchers$voucher_date), ]\nvouchers$voucher_no <- sprintf(\"TV/24-25/%03d\", seq_len(nrow(vouchers)))\nvouchers$gst <- round(vouchers$amount * 18 / 118)\nvouchers <- vouchers[, c(\"voucher_no\", \"office\", \"voucher_date\", \"amount\", \"gst\")]\nrownames(vouchers) <- NULL\n\n# Quarter of the financial year. April to June is Q1, January to March is Q4\nquarter <- paste0(\"Q\", (as.integer(format(vouchers$voucher_date, \"%m\")) - 4) %% 12 %/% 3 + 1)\n# Expenditure of each office in each quarter, in lakh\nqexp <- round(tapply(vouchers$amount, list(vouchers$office, quarter), sum) / 1e5, 2)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(vouchers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    voucher_no   office voucher_date amount   gst\n1 TV/24-25/001     Pune   2024-04-01  53000  8085\n2 TV/24-25/002   Nagpur   2024-04-02 163500 24941\n3 TV/24-25/003     Pune   2024-04-03 170200 25963\n4 TV/24-25/004   Nashik   2024-04-05  36200  5522\n5 TV/24-25/005   Nagpur   2024-04-08  65100  9931\n6 TV/24-25/006 Kolhapur   2024-04-14 187800 28647\n```\n\n\n:::\n\n```{.r .cell-code}\nqexp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Q1    Q2    Q3    Q4\nKolhapur  8.19 19.80 15.51 14.02\nNagpur   10.91 10.86 11.92 40.51\nNashik    6.76 10.54 12.62  8.24\nPune      5.94  7.16  8.86  8.39\n```\n\n\n:::\n:::\n\n\nThe register has 167 vouchers, worth ₹200.25 lakh in all.\n\n### Usage of functional programming in R\n\nStrictly speaking, R is not a pure functional programming language, but it supports the style well. We have seen that most functions work on whole vectors at once. But what about lists? Many functions do not work on them. Suppose three amounts have been kept in a list. Check this example.\n\n::: {.cell}\n\n```{.r .cell-code}\nlist1 <- list(50000, 5000, 56)\nsum(list1)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `sum()`:\n! invalid 'type' (list) of argument\n```\n\n\n:::\n:::\n\nOf course, we can solve the above problem with a `for` loop. See\n\n::: {.cell}\n\n```{.r .cell-code}\nlist1 <- list(50000, 5000, 56)\n# for loop strategy\nx <- c()\nfor(i in seq_along(list1)){\n  x[i] <- list1[[i]]\n}\nsum(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 55056\n```\n\n\n:::\n:::\n\nConsider another list, the bills passed by three offices in one week, where we want the average bill of each office.\n\n::: {.cell}\n\n```{.r .cell-code}\noffice_bills <- list(\n  Pune   = c(42000, 18500, 61000, 27500),\n  Nashik = c(99500, 98000, 99900),\n  Nagpur = c(12500, 230000, 45000, 8800, 76000)\n)\n```\n:::\n\n\nWe may use a `for` loop again, but in R such operations are done more simply with the *apply* family of functions, one of the best known features of R. We will come back to `office_bills` shortly.\n\n## `apply` family of functions\n\nThe first of these functions is `apply()`, which works on matrices and data frames.\n\n### Function `apply()`\nThe basic syntax of `apply` is\n```\napply(m, MARGIN, FUN, f_args)\n```\nwhere\n\n- `m` is the matrix\n- `MARGIN` is the dimension. To _apply_ the function to each row, use `1`, and to each column, `2`\n- `FUN` is the function to apply\n- `f_args` are any further arguments to be passed to `FUN`.\n\nAn illustrative construction of `apply` function can be seen in @fig-applyimage.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Illustration of function apply](images/apply.png){#fig-applyimage fig-align='center' width=100%}\n:::\n:::\n\n\nLet us find the average quarterly expenditure of each office, from our matrix `qexp`. Each row is an office, so `MARGIN` is `1`.\n\n::: {.cell}\n\n```{.r .cell-code}\napply(qexp, 1, mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKolhapur   Nagpur   Nashik     Pune \n 14.3800  18.5500   9.5400   7.5875 \n```\n\n\n:::\n:::\n\n**Note:** `rowMeans(qexp)` would have given the same result. We use a simple example to show the idea.\n\n**We may also pass our own function.** Government instructions discourage a rush of expenditure at the end of the year. A common yardstick is that not more than a third, 33%, of the year's spending should fall in the last quarter. Let us write a function which gives the share of the last quarter, Q4, in a row, and then `apply` it to every office.\n\n::: {.cell}\n\n```{.r .cell-code}\nq4_share <- function(x){\n  round(x[4] / sum(x) * 100, 1)\n}\napply(qexp, 1, q4_share)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKolhapur   Nagpur   Nashik     Pune \n    24.4     54.6     21.6     27.6 \n```\n\n\n:::\n:::\n\n\n\n\nNagpur spent 54.6% of its year's money in the last quarter. The other offices are within the yardstick.\n\nIf the function is not needed elsewhere, there is no need to define it beforehand. We may write an anonymous function directly inside `apply()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napply(qexp, 1, FUN = function(x) round(x[4] / sum(x) * 100, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKolhapur   Nagpur   Nashik     Pune \n    24.4     54.6     21.6     27.6 \n```\n\n\n:::\n:::\n\n\n::: callout-note\n**Since R 4.1, a function can be written with a backslash `\\` in place of the word `function`** (see @sec-func). We could have written the above as\n\n::: {.cell}\n\n```{.r .cell-code}\napply(qexp, 1, FUN = \\(x) round(x[4] / sum(x) * 100, 1))\n## Kolhapur   Nagpur   Nashik     Pune \n##     24.4     54.6     21.6     27.6\n```\n:::\n\n:::\n\n#### `apply()` need not necessarily output vectors only {-}\nIf `FUN` returns more than one value for each row or column, the output is a matrix. The thing to note is that the result for each row or column is always placed in a *column* of the output, whether `MARGIN` is `1` or `2`. (A function like `sqrt` would not show this well, since `apply(m, 1, sqrt)` gives the same values as `sqrt(m)`.)\n\nSuppose we want the *progressive* expenditure of each office, that is, its running total at the end of each quarter. The running total is given by `cumsum()`. First, let us do it on each column, with `MARGIN = 2`.\n\n::: {.cell}\n\n```{.r .cell-code}\napply(qexp, 2, cumsum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Q1    Q2    Q3    Q4\nKolhapur  8.19 19.80 15.51 14.02\nNagpur   19.10 30.66 27.43 54.53\nNashik   25.86 41.20 40.05 62.77\nPune     31.80 48.36 48.91 71.16\n```\n\n\n:::\n:::\n\nThe layout is the same as that of `qexp`. But a running total down a column adds up the offices, which means nothing to us. We want the running total along each row, over the quarters.\n\n::: {.cell}\n\n```{.r .cell-code}\napply(qexp, 1, cumsum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Kolhapur Nagpur Nashik  Pune\nQ1     8.19  10.91   6.76  5.94\nQ2    27.99  21.77  17.30 13.10\nQ3    43.50  33.69  29.92 21.96\nQ4    57.52  74.20  38.16 30.35\n```\n\n\n:::\n:::\n\nThe numbers are right, but the output is the _transpose_ of what we expected. The offices are now columns, because the result for each row has gone into a column. Wrap it in `t()` to get the expected layout.\n\n::: {.cell}\n\n```{.r .cell-code}\nt(apply(qexp, 1, cumsum))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Q1    Q2    Q3    Q4\nKolhapur  8.19 27.99 43.50 57.52\nNagpur   10.91 21.77 33.69 74.20\nNashik    6.76 17.30 29.92 38.16\nPune      5.94 13.10 21.96 30.35\n```\n\n\n:::\n:::\n\nLet us check our understanding with one more example, using a function whose output length does not depend on the input. `range()` always gives two values, the smallest and the largest.\n\n\n::: {.cell}\n\n```{.r .cell-code}\napply(qexp, 1, range)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Kolhapur Nagpur Nashik Pune\n[1,]     8.19  10.86   6.76 5.94\n[2,]    19.80  40.51  12.62 8.86\n```\n\n\n:::\n:::\n\n\nThus we may conclude that\n\n- if `FUN` returns a single value, the output of `apply` is a vector whose __length__ is\n   - the number of rows of the input, if `MARGIN` is 1,\n   - the number of columns of the input, if `MARGIN` is 2;\n- if `FUN` returns a vector of length more than 1, the output is a matrix whose __number of columns__ is\n   - the number of rows of the input, if `MARGIN` is 1,\n   - the number of columns of the input, if `MARGIN` is 2.\n\nThese have been tabulated in @tbl-apply.\n\nTable: Relation between input and output data structure in `apply` {#tbl-apply}\n\n| Input matrix $m*n$      | `MARGIN = 1`  | `MARGIN = 2`  |\n|-------------------------|:-------------:|:-------------:|\n| FUN gives scalar        | Vector size $m$ | Vector size $n$ |\n| FUN gives vector size $p$| Matrix $p*m$ | Matrix $p*n$ |\n\n\nSo we have to be careful with the output of `apply()`, or it may introduce a bug in our code.\n\n#### `apply()` on data frames {-}\nData frames, though a kind of list, also behave like matrices, so we may use `apply()` on them too. Let us turn `qexp` into a data frame, and total each quarter.\n\n::: {.cell}\n\n```{.r .cell-code}\n(qexp_df <- as.data.frame(qexp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Q1    Q2    Q3    Q4\nKolhapur  8.19 19.80 15.51 14.02\nNagpur   10.91 10.86 11.92 40.51\nNashik    6.76 10.54 12.62  8.24\nPune      5.94  7.16  8.86  8.39\n```\n\n\n:::\n\n```{.r .cell-code}\napply(qexp_df, 2, sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Q1    Q2    Q3    Q4 \n31.80 48.36 48.91 71.16 \n```\n\n\n:::\n:::\n\n\n::: callout-warning\n## Caution\n`apply()` first converts a data frame into a matrix. If the data frame has even one text column, *every* value becomes text, and numeric functions fail or give wrong results. See what happens when we try to add GST to each amount, row by row, while the voucher number is also in the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmall <- vouchers[1:4, c(\"voucher_no\", \"amount\")]\napply(small, 1, \\(r) r[\"amount\"] * 1.18)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `r[\"amount\"] * 1.18`:\n! non-numeric argument to binary operator\n```\n\n\n:::\n:::\n\n\nThe amounts had become text, and text cannot be multiplied. Use `apply()` only on all-numeric data, and prefer `lapply()`, `sapply()` or, in the tidyverse, `across()` (@sec-across) for data frames.\n:::\n\n\n### Function `lapply()`\n\n`lapply()` is the cousin of `apply()` for `l`ists, as its name suggests. Since a data frame is also a list, `lapply()` works on data frames too, column by column. The basic syntax of `lapply()` is\n```\nlapply(l, FUN, f_args)\n```\nwhere\n\n- `l` is the list\n- `FUN` is the function to apply\n- `f_args` are any further arguments to be passed to `FUN`.\n\nNote that there is no `MARGIN` argument here. Let us total each quarter again, this time with `lapply()`.\n\n::: {.cell}\n\n```{.r .cell-code}\nlapply(qexp_df, sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Q1\n[1] 31.8\n\n$Q2\n[1] 48.36\n\n$Q3\n[1] 48.91\n\n$Q4\n[1] 71.16\n```\n\n\n:::\n:::\n\nYou may have noticed two things here.\n\n1. The output is a `list`.\n2. `FUN` is applied to every element of the list. Each column of a data frame is an element, so `lapply()` works column by column, never row by row.\n\nThus `lapply()`\n\n- loops over a list, iterating over each element in that list\n- then _applies_ the function `FUN` to each element\n- and then returns a list.\n\nThe first thing to check in any file received from an auditee is the type of each column. Is the date really a date? Is the amount a number, or text? `lapply()` with `class()` tells us at once.\n\n::: {.cell}\n\n```{.r .cell-code}\nlapply(vouchers, class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$voucher_no\n[1] \"character\"\n\n$office\n[1] \"character\"\n\n$voucher_date\n[1] \"Date\"\n\n$amount\n[1] \"numeric\"\n\n$gst\n[1] \"numeric\"\n```\n\n\n:::\n:::\n\n\nAs with `apply()`, we can write `FUN` inline (anonymously). This gives the share of each office in each quarter's expenditure, in per cent.\n\n::: {.cell}\n\n```{.r .cell-code}\nlapply(qexp_df, \\(a) round(a / sum(a) * 100, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Q1\n[1] 25.8 34.3 21.3 18.7\n\n$Q2\n[1] 40.9 22.5 21.8 14.8\n\n$Q3\n[1] 31.7 24.4 25.8 18.1\n\n$Q4\n[1] 19.7 56.9 11.6 11.8\n```\n\n\n:::\n:::\n\n\nThe element of the list goes to the *first* argument of `FUN` which is not already named. Suppose we want to pick 3, 2 and 4 voucher numbers at random from the range 1001 to 1050, for three audit teams. `sample()` takes the values to pick from as `x`, and the number to pick as `size`. Since we have named `x`, each number goes to `size`.\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nlapply(c(3, 2, 4), sample, x = 1001:1050)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] 1004 1039 1001\n\n[[2]]\n[1] 1034 1023\n\n[[3]]\n[1] 1043 1014 1018 1033\n```\n\n\n:::\n:::\n\n\n**Note** that even when `lapply()` is applied to a vector, it returns a list.\n\nAnd now `office_bills`, from the beginning of the chapter. The average bill of each office is simply\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlapply(office_bills, mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Pune\n[1] 37250\n\n$Nashik\n[1] 99133.33\n\n$Nagpur\n[1] 74460\n```\n\n\n:::\n:::\n\n\n### Function `sapply()`\n`sapply()` is a `s`implified `lapply()`. It works the same way, but simplifies the result as much as possible, usually into a vector or a matrix.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(qexp_df, sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Q1    Q2    Q3    Q4 \n31.80 48.36 48.91 71.16 \n```\n\n\n:::\n\n```{.r .cell-code}\nsapply(office_bills, mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Pune   Nashik   Nagpur \n37250.00 99133.33 74460.00 \n```\n\n\n:::\n:::\n\n\n::: callout-warning\n## Caution\nThe convenience has a cost. What `sapply()` returns depends on the data, a vector one day and a list another, which can break code silently. For code that will be reused, prefer `vapply()`, described below, or the `purrr` functions.\n:::\n\n## Other loop functions\n\n### Function `replicate()`\n\n`replicate()`\\index{replicate() function} evaluates an expression repeatedly. It is mostly used in simulations. The syntax is\n```\nreplicate(n, expr, simplify = \"array\")\n```\nwhere\n\n - `n` is the number of replications\n - `expr` is the expression to evaluate repeatedly\n - `simplify` says whether the results should be simplified into a vector, matrix or array.\n\nSuppose we draw a random sample of 10 vouchers, and work out their average amount. How much would that average change from one sample to another? `replicate()` draws five such samples, and gives the five averages. Then, with `simplify = FALSE`, it draws three samples of four voucher numbers each, and keeps each sample as an element of a list.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n# Default value of simplify will simplify the results as much possible\nreplicate(5, mean(sample(vouchers$amount, 10)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 128070 104530  95220 196320 108110\n```\n\n\n:::\n\n```{.r .cell-code}\n# Notice the difference with simplify=FALSE\nreplicate(3, sample(vouchers$voucher_no, 4), simplify = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] \"TV/24-25/016\" \"TV/24-25/116\" \"TV/24-25/094\" \"TV/24-25/006\"\n\n[[2]]\n[1] \"TV/24-25/086\" \"TV/24-25/167\" \"TV/24-25/039\" \"TV/24-25/159\"\n\n[[3]]\n[1] \"TV/24-25/118\" \"TV/24-25/050\" \"TV/24-25/034\" \"TV/24-25/004\"\n```\n\n\n:::\n:::\n\n\nAudit sampling itself is the subject of @sec-sampling.\n\n### Function `split()`\n\n`split()`\\index{split() function} divides an object (a vector, list or data frame) into groups, given by a factor. The result is a list, with one element for each group. The basic syntax is\n```\nsplit(x, f, drop=FALSE, ...)\n```\nwhere\n\n- `x` is the object to split, a `vector`, `list` or `data.frame`\n- `f` is a factor, or a list of factors. Anything else is converted to a factor.\n- `drop` says whether groups with no data should be dropped.\n\nFor example, to share the first ten vouchers between two audit teams, alternately,\n\n::: {.cell}\n\n```{.r .cell-code}\nsplit(vouchers$voucher_no[1:10], rep(c(\"Team A\", \"Team B\"), 5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`Team A`\n[1] \"TV/24-25/001\" \"TV/24-25/003\" \"TV/24-25/005\" \"TV/24-25/007\" \"TV/24-25/009\"\n\n$`Team B`\n[1] \"TV/24-25/002\" \"TV/24-25/004\" \"TV/24-25/006\" \"TV/24-25/008\" \"TV/24-25/010\"\n```\n\n\n:::\n:::\n\nThe total expenditure of each office,\n\n::: {.cell}\n\n```{.r .cell-code}\nsplit(vouchers$amount, vouchers$office) |> lapply(sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Kolhapur\n[1] 5752500\n\n$Nagpur\n[1] 7421100\n\n$Nashik\n[1] 3816100\n\n$Pune\n[1] 3035400\n```\n\n\n:::\n:::\n\n\nAnd the largest voucher of each office,\n\n::: {.cell}\n\n```{.r .cell-code}\nsplit(vouchers$amount, vouchers$office) |> sapply(max)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKolhapur   Nagpur   Nashik     Pune \n  196100   610000   199500   194800 \n```\n\n\n:::\n:::\n\n\n### `tapply()`\n\n`tapply()`\\index{tapply() function} combines `split()` and `sapply()` for vectors, exactly as in the last example. It applies a function to each group of a vector. The basic syntax is\n```\ntapply(X, INDEX, FUN = NULL, ..., default = NA, simplify = TRUE)\n```\nwhere\n\n- `X` is a vector\n- `INDEX` is a factor, or a list of factors, giving the groups\n- `FUN` is the function to apply\n- `...` are any further arguments for `FUN`\n- `simplify`, if `TRUE`, simplifies the result.\n\nThe largest voucher of each office again, in one step.\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(vouchers$amount, vouchers$office, max)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKolhapur   Nagpur   Nashik     Pune \n  196100   610000   199500   194800 \n```\n\n\n:::\n:::\n\n\nIf `simplify` is `FALSE`, the results are not simplified. See this example, the average voucher of each office.\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(vouchers$amount, vouchers$office, mean, simplify = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Kolhapur\n[1] 112794.1\n\n$Nagpur\n[1] 172583.7\n\n$Nashik\n[1] 90859.52\n\n$Pune\n[1] 97916.13\n```\n\n\n:::\n:::\n\n\nWith a list of two factors as `INDEX`, `tapply()` gives a cross-table. This is how the matrix `qexp` was made from the vouchers, with the office and the quarter as the two factors.\n\n### `by()` function\n\n`by()`\\index{by() function} works like `tapply()`, but on a whole data frame, passing each group's rows to the function. Let us see the voucher with the largest amount in each office. `which.max()` gives the position of the largest value.\n\n::: {.cell}\n\n```{.r .cell-code}\nby(vouchers, vouchers$office, \\(d) d[which.max(d$amount), ])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nvouchers$office: Kolhapur\n      voucher_no   office voucher_date amount   gst\n154 TV/24-25/154 Kolhapur   2025-03-17 196100 29914\n------------------------------------------------------------ \nvouchers$office: Nagpur\n      voucher_no office voucher_date amount   gst\n161 TV/24-25/161 Nagpur   2025-03-25 610000 93051\n------------------------------------------------------------ \nvouchers$office: Nashik\n     voucher_no office voucher_date amount   gst\n36 TV/24-25/036 Nashik   2024-07-05 199500 30432\n------------------------------------------------------------ \nvouchers$office: Pune\n     voucher_no office voucher_date amount   gst\n32 TV/24-25/032   Pune   2024-06-30 194800 29715\n```\n\n\n:::\n:::\n\n\n### Specifying the output type with `vapply()`\n`vapply()`\\index{vapply() function} works like `sapply()`, except that we must state the type and length of each result, in the argument `FUN.VALUE`. If a result does not match, it stops with an error, instead of returning something unexpected. Its syntax is\n```\nvapply(X, FUN, FUN.VALUE, ..., USE.NAMES = TRUE)\n```\n - In the argument `FUN.VALUE` we give a template of each result. See this example, the largest amount and the largest GST.\n\n::: {.cell}\n\n```{.r .cell-code}\nvapply(vouchers[c(\"amount\", \"gst\")], max, FUN.VALUE = double(1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\namount    gst \n610000  93051 \n```\n\n\n:::\n:::\n\nWith `FUN.VALUE = double(1)` we have said that each result should be a single `double`. To find the `range` of each column, which has two values,\n\n::: {.cell}\n\n```{.r .cell-code}\nvapply(vouchers[c(\"amount\", \"gst\")], range, FUN.VALUE = double(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     amount   gst\n[1,]  20300  3097\n[2,] 610000 93051\n```\n\n\n:::\n:::\n\nIf we try this on the whole register, which has text columns like the voucher number and the office, `vapply()` stops with an error, as we want it to.\n\n::: {.cell}\n\n```{.r .cell-code}\nvapply(vouchers, range, FUN.VALUE = double(2))\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `vapply()`:\n! values must be type 'double',\n but FUN(X[[1]]) result is type 'character'\n```\n\n\n:::\n:::\n\n## Functional Programming in `purrr` {#sec-purrr}\nThe package `purrr`^[[https://purrr.tidyverse.org/](https://purrr.tidyverse.org/)], part of the core `tidyverse`, gives a complete and consistent set of tools for functional programming. Its functions do the job of the apply family, with consistent names and arguments, and a guaranteed type of output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(purrr)\n```\n:::\n\n\n### Iterate over single list/vector with `map_*()` family of functions\nThe most important family of functions in purrr is `map`. The `map_*()` functions work much like `vapply()`, with control over the type of output. They all take a list or vector as the argument `.x` and a function as `.f`, and return an output of the stated type.\n\nLet us total each quarter of `qexp_df` once more.\n\n::: {.cell}\n\n```{.r .cell-code}\nmap(qexp_df, .f = sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Q1\n[1] 31.8\n\n$Q2\n[1] 48.36\n\n$Q3\n[1] 48.91\n\n$Q4\n[1] 71.16\n```\n\n\n:::\n:::\n\nNote that the output is a list, just as with `lapply()`. If each result is a single value, we use one of these functions, depending on its type, to get a vector.\n\n- `map_lgl` for `logical` format\n- `map_int` for `integer` format\n- `map_dbl` for `double` format\n- `map_chr` for `character` format. Since purrr version 1.2, `map_chr()` no longer converts numbers or logical values into text automatically. If the function returns numbers, use `map_dbl()`, or convert the result explicitly with `as.character()`.\n\n`map()` always returns a list.\nSee these further examples.\n\nThe largest amount and the largest GST, as a vector of doubles.\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_dbl(vouchers[c(\"amount\", \"gst\")], max)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\namount    gst \n610000  93051 \n```\n\n\n:::\n:::\n\n\nAn anonymous function, written with `\\(x)`. (Older code often uses a formula instead, like `~ mean(.x)`. It still works, but `\\(x)` is now recommended.) The first line gives the average bill of each office. The second turns month numbers into names.\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_dbl(office_bills, \\(x) mean(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Pune   Nashik   Nagpur \n37250.00 99133.33 74460.00 \n```\n\n\n:::\n\n```{.r .cell-code}\nmap_chr(c(2, 7, 12), \\(m) month.name[m])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"February\" \"July\"     \"December\"\n```\n\n\n:::\n:::\n\n\n### Iterate over two or more lists/vectors using `map2_*()`/ `pmap_*()` family\n\nSo far, `map_*()` has iterated over the elements of one list. Any extra arguments are passed unchanged, the same in every iteration, as in the first illustration in @fig-map2^[Image from [Advanced R](https://adv-r.hadley.nz/functionals.html) by Hadley Wickham].\n\n::: {#fig-map2}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/map1.png){fig-align='center' width=49%}\n:::\n\n::: {.cell-output-display}\n![](images/map2.png){fig-align='center' width=49%}\n:::\n:::\n\n\nWorking of map vs map2 family of functions \\hspace{\\textwidth} Source Advanced R by Hadley Wickham\n:::\nTo iterate over two vectors or lists *together*, taking their elements in pairs, we need the `map2_*()` family of functions (see the second illustration in @fig-map2).\n\nSee the following example. Each office has its own limit for a single bill, and `map2()` takes the bills of each office together with its own limit.\n\n::: {.cell}\n\n```{.r .cell-code}\noffice_limits <- c(Pune = 50000, Nashik = 100000, Nagpur = 100000)\nmap2(office_bills, office_limits, \\(x, lim) x[x > lim])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Pune\n[1] 61000\n\n$Nashik\nnumeric(0)\n\n$Nagpur\n[1] 230000\n```\n\n\n:::\n:::\n\nPune has one bill above its limit, and Nagpur has one above its own. Nashik has none. Its three bills are all a little below ₹1 lakh, which is itself worth a second look (@sec-dplyr-split).\n\nHere is another audit use. Claims under three schemes are to be checked against each scheme's own limit. `map2()` takes each scheme's claims together with its limit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclaims <- list(Health    = c(12000, 155000, 8000, 140000),\n               Education = c(30000, 9000, 61000),\n               Housing   = c(150000, 260000, 90000))\nlimits <- c(Health = 100000, Education = 50000, Housing = 250000)\n\nmap2(claims, limits, \\(x, lim) x[x > lim])      # the claims above the limit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Health\n[1] 155000 140000\n\n$Education\n[1] 61000\n\n$Housing\n[1] 260000\n```\n\n\n:::\n\n```{.r .cell-code}\nmap2_int(claims, limits, \\(x, lim) sum(x > lim)) # how many\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Health Education   Housing \n        2         1         1 \n```\n\n\n:::\n:::\n\n\nAnother use is a completeness check. From the first and last numbers of each cheque book issued, `map2()` builds the full list of cheque leaves, which can then be compared with the cheques accounted for.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheque_books <- data.frame(first = c(500101, 500126), last = c(500125, 500150))\nall_leaves <- map2(cheque_books$first, cheque_books$last, seq) |> unlist()\nlength(all_leaves)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 50\n```\n\n\n:::\n\n```{.r .cell-code}\naccounted <- c(500101:500118, 500120:500150)   # say, from the cheque register\nsetdiff(all_leaves, accounted)                  # leaves not accounted for\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 500119\n```\n\n\n:::\n:::\n\n\nSimilarly, to iterate over three or more lists, we use `pmap_*()`. The only difference is that all the lists are passed to `pmap` together, in one list. This can be better understood with the illustration used by Hadley Wickham in his [book](https://adv-r.hadley.nz/functionals.html). See @fig-pmap.\n\n::: {#fig-pmap}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/pmap.png){fig-align='center' width=49%}\n:::\n\n::: {.cell-output-display}\n![](images/pmap-arg.png){fig-align='center' width=49%}\n:::\n:::\n\n\nWorking of pmap family of functions \\hspace{\\textwidth} Source Advanced R by Hadley Wickham\n:::\n\nFor example, a data frame is a list of columns, so `pmap()` over a data frame takes one row at a time, with the column names matching the names of the function's arguments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbills <- data.frame(qty = c(10, 25, 40), rate = c(150, 80, 12.5), gst = c(18, 5, 18))\npmap_dbl(bills, \\(qty, rate, gst) qty * rate * (1 + gst / 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1770 2100  590\n```\n\n\n:::\n:::\n\n\nHere, plain vector arithmetic, `qty * rate * (1 + gst / 100)`, would have done the same. `pmap()` is needed when the function works on only one value at a time, like `seq()` above, or a function of our own with `if`.\n\n### Other useful purrr functions\n\n- `walk()`, `walk2()` and `iwalk()` work like `map()`, but for functions called for their *side effects*, like saving files or drawing plots, rather than for a result. We use `iwalk()` to save one file per district in @sec-merge.\n- `list_rbind()` binds a list of data frames into one, as when reading many files with `map()`. Its argument `names_to` adds a column with the names of the list elements, like the file each row came from. We use it in the audit use case below.\n- `keep()` and `discard()` keep or drop the elements of a list which meet a condition, like `keep(claims, \\(x) any(x > 100000))`.\n- `imap()` passes each element along with its name, or position, as a second argument.\n\n::: callout-tip\n## Audit tip\n\nWhenever you find yourself running the same analysis on several files, districts, years or schemes, put them in a list and `map()` over it. One function, tested once, then runs on all of them alike. That is both quicker and more reliable than copying and editing code for each, where one small slip can go unnoticed.\n:::\n\n## Audit use case, the March rush in each office {#sec-fp-march}\n\nA rush of expenditure in the last month of the year is a classic audit concern. Money spent in a hurry, to avoid its lapse, is often spent badly. Government of India instructions ask departments to keep spending in March within 15% of the budget, and in the last quarter within 33%. We have no budget figures here. So we use each office's actual spending for the year as a rough yardstick instead.\n\nLet us check every office in the same way. We split the vouchers into a list, one data frame per office. We write one function which checks one office. We test it on one office, and then `map()` it over all four.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noffice_list <- split(vouchers, vouchers$office)\n\nmarch_check <- function(d) {\n  in_march <- format(d$voucher_date, \"%Y-%m\") == \"2025-03\"\n  in_q4    <- d$voucher_date >= as.Date(\"2025-01-01\")\n  data.frame(vouchers   = nrow(d),\n             total_lakh = round(sum(d$amount) / 1e5, 2),\n             q4_pct     = round(100 * sum(d$amount[in_q4]) / sum(d$amount), 1),\n             march_pct  = round(100 * sum(d$amount[in_march]) / sum(d$amount), 1))\n}\n\n# Test on one office first\nmarch_check(office_list$Pune)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  vouchers total_lakh q4_pct march_pct\n1       31      30.35   27.6        16\n```\n\n\n:::\n:::\n\n\nThe function works on one office. Now let us run it on all of them, and bind the results into one table with `list_rbind()`. Its argument `names_to` adds the name of each office as a column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmarch_result <- office_list |>\n  map(march_check) |>\n  list_rbind(names_to = \"office\")\nmarch_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    office vouchers total_lakh q4_pct march_pct\n1 Kolhapur       51      57.52   24.4      13.6\n2   Nagpur       43      74.21   54.6      52.2\n3   Nashik       42      38.16   21.6       3.7\n4     Pune       31      30.35   27.6      16.0\n```\n\n\n:::\n:::\n\n\n\n\nLet us keep the offices which cross either yardstick.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubset(march_result, q4_pct > 33 | march_pct > 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  office vouchers total_lakh q4_pct march_pct\n2 Nagpur       43      74.21   54.6      52.2\n4   Pune       31      30.35   27.6      16.0\n```\n\n\n:::\n:::\n\n\nNagpur stands out. It spent 52.2% of its year's money in March, and 54.6% in the last quarter. Pune is also above the March yardstick, but only just, at 16%. That may be no more than the normal ups and downs of payments.\n\nThe auditor would next look at the Nagpur vouchers of March. Were the goods received, and the works done, before payment? Were any payments made in advance, only to avoid the lapse of funds? The March vouchers, with these questions, go into the working papers.\n\nNote that the same function ran on every office alike. Had there been forty offices, the code would not have changed at all.\n\n## A suggested workflow\n\n1.  **Spot the repetition.** Notice when the same work is done on several files, districts, years or schemes.\n2.  **Put the pieces in a list.** Keep one data frame, or one vector, for each item. Use `split()` to break one table into groups if needed.\n3.  **Write and test one function.** Make it work correctly on a single item first. A short anonymous function written with `\\(x)` is enough for simple jobs.\n4.  **Map it over the list.** Use `map()`, or `lapply()`, to run the same function on every item alike.\n5.  **Ask for the type of output you expect.** Use `map_dbl()`, `map_int()` or `vapply()`, so that a surprise result stops with an error. Be careful with `apply()` on data frames that have text columns.\n6.  **Pair items with their own limits.** Use `map2()` or `pmap()` when each item has its own limit or rate, like scheme-wise claim limits.\n7.  **Combine or save the results.** Bind a list of data frames with `list_rbind()`, and use `walk()` or `iwalk()` to save one file for each item.\n\n::: callout-important\n## Remember\n\nTest the function on one item before mapping it over all. Ask for the output type you expect, so that an odd result stops the code instead of passing silently. One tested function is safer than many copies of edited code.\n:::\n\n## Summary of functions used\n\n| Function | Package | What it does |\n|-----------------------|----------------|--------------------------------|\n| `apply()` | base R | Apply a function to each row or column of a matrix |\n| `lapply()`, `sapply()`, `vapply()` | base R | Apply a function to each element of a list, returning a list, a simplified result, or a result of a stated type |\n| `replicate()` | base R | Evaluate an expression many times |\n| `split()` | base R | Divide an object into a list of groups |\n| `tapply()`, `by()` | base R | Apply a function to each group of a vector or data frame |\n| `t()`, `cumsum()`, `range()`, `which.max()` | base R | Transpose a matrix; running total; smallest and largest values; position of the largest value |\n| `class()` | base R | The class of an object, like numeric, character or Date |\n| `map()`, `map_lgl()`, `map_int()`, `map_dbl()`, `map_chr()` | purrr | Apply a function to each element, returning a list or a vector of the stated type |\n| `map2()`, `pmap()` | purrr | Apply a function to elements of two, or more, lists taken together |\n| `walk()`, `iwalk()` | purrr | Like `map()`, for side effects like saving files |\n| `list_rbind()` | purrr | Bind a list of data frames into one |\n| `keep()`, `discard()`, `imap()` | purrr | Keep or drop elements, or map with names |\n| `unlist()`, `setdiff()` | base R | Flatten a list into a vector; values in one vector but not another |\n| `subset()` | base R | Keep the rows of a data frame which meet a condition |\n\n: Functions used in this chapter {#tbl-fpfunctions}\n",
    "supporting": [
      "06-1-functionalprog_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}